### ISSUE TITLE
must have these days - VCS

### ISSUE THREAD

**Issue by gabiudrescu** [kamranahmedse/developer-roadmap#100]
how about adding versioning control systems such as GIT on frontend dev? and backend? and devops?

**Comment by kamranahmedse** [comment]
How about you looking at the introduction section? ;)

![image](https://cloud.githubusercontent.com/assets/4921183/24421604/c2932b66-1407-11e7-8527-87f8e203b718.png)

**Comment by gabiudrescu** [comment]
Shame on me.
