### ISSUE TITLE
[Enhancement] Header pages links colors

### ISSUE THREAD

**Issue by HaithamLeo** [kamranahmedse/developer-roadmap#1015]
#### What roadmap is this issue about?

- [ ] Frontend Roadmap
- [ ] Backend Roadmap
- [ ] DevOps Roadmap
- [x] All Roadmaps

#### What is this issue about?

- [x] Functionality of the website
- [x] Discussion for a pull request I would want to open.
- [ ] Addition of a new item
- [ ] Removal of some existing item
- [ ] Changing in arrangement
- [ ] General suggestion
- [ ] Sharing an Idea
- [ ] Something else

#### Please acknowledge the below listed

- [x] This is not a duplicate issue. I have searched and there is no existing issue for this.
- [x] I understand that these roadmaps are highly opinionated. The purpose is to not to include everything out there in these roadmaps but to have everything that is most relevant today comparing to the other options listed.
- [x] I have read the [contribution docs](../contributing) before opening this issue.

#### Enter the details about the issue here

For better UI/UX user should know which page is the current page.

I propose to differentiate the current or active page link with a different color.

![image](https://user-images.githubusercontent.com/73870784/150082453-cddb2964-9581-446d-9604-7ac1a85cd50e.png)

Example:
Now the current page link `Roadmaps`  is in different color so user can know in which page is the current page. 

![image](https://user-images.githubusercontent.com/73870784/150083106-fa8ade61-5418-47fd-aef7-1a7cc0127a17.png)

Also mobile has different style for the subscribe button which is different that the one for desktop display.

![image](https://user-images.githubusercontent.com/73870784/150085283-285ad3b8-83ab-47b2-a9cc-c6d7450417a9.png)

**Comment by HaithamLeo** [comment]
Hey @kamranahmedse I already opened PR for this issue #1016 ...I hope you get the chance to review it.

**Comment by kamranahmedse** [comment]
Since there are only three pages in the main nav I don't think we need to add all this logic to highlight the active page. Thank you for your contribution though @HaithamLeo -- for next time, please take the go-ahead by opening an issue before you work on some feature :)
