### ISSUE TITLE
Haml/Pug 

### ISSUE THREAD

**Issue by vasiljevs** [kamranahmedse/developer-roadmap#102]
What about Haml or Pug (Jade) in Front-end section? 

Thanks!

**Comment by minthemiddle** [comment]
I would add [Emmet](https://github.com/emmetio/emmet) as well. It's baked into VSCode and has 3k stars on Github.

**Comment by kamranahmedse** [comment]
Hi @vasiljevs, templating engines isn't really much of a _thing_ these days. You can easily go by if you have never worked with any of them, so I think it is fine without it.

**Comment by minthemiddle** [comment]
Sorry to disagree: Neither is Emmet a templating language nor are they "not really much of a thing". Show me one frontend developer who writes a list with 6 list items in HTML one `<li>` at a time and not with a shortcuts - such as Emmet's `ul.li*6` followed by tab to autoclose all tags. You could dismiss `SASS` or `Bootstrap` with the same argument: Yes, you can write everything from scratch in vanilla `Vim`, but after your first gig you "dig deeper" and get more proficient by learning some of the tools that make your life easier.

**Comment by kamranahmedse** [comment]
Hey @minthemiddle my reply was to close the issue, not to your comment. 

As far as emmet is considered, have you ever seen any job posting stating that as a requirement? I agree it is good for the productivity but not a requirement for being a web developer.
