### ISSUE TITLE
Getting Deeper with HTML

### ISSUE THREAD

**Issue by ademagic** [kamranahmedse/developer-roadmap#103]
I'd add a "Getting Deeper" branch of HTML, which would include:

- Semantic HTML
- WAI-ARIA
- templating tools (twig/haml/handlebars/moustache etc.)
- a11y testing (aXe, ChromeVox, I Want To See Like The Colorblind etc.)
etc etc

**Comment by damengilland** [comment]
* HTML for emails.

**Comment by kamranahmedse** [comment]
Hi @ademagic, thank you for reporting, I could add that but it isn't really necessary to learn the templating tools etc and you could still go by if you have no idea about them. So in order to avoid convolution, I think it is fine.
