### ISSUE TITLE
Add Helm in the DevOps Roadmap

### ISSUE THREAD

**Issue by manishshanker** [kamranahmedse/developer-roadmap#1040]
#### What roadmap is this issue about?

- [ ] Frontend Roadmap
- [ ] Backend Roadmap
- [x] DevOps Roadmap
- [ ] All Roadmaps

#### What is this issue about?

- [ ] Functionality of the website
- [ ] Discussion for a pull request I would want to open.
- [x] Addition of a new item
- [ ] Removal of some existing item
- [ ] Changing in arrangement
- [ ] General suggestion
- [ ] Sharing an Idea
- [ ] Something else

#### Please acknowledge the below listed

- [x] This is not a duplicate issue. I have searched and there is no existing issue for this.
- [x] I understand that these roadmaps are highly opinionated. The purpose is to not to include everything out there in these roadmaps but to have everything that is most relevant today comparing to the other options listed.
- [x] I have read the [contribution docs](../contributing) before opening this issue.

#### Enter the details about the issue here

HELM seems to be a widely used tool for managing Kubernetes packages and a clean way to manage the configuration and deployment of microservices at a large scale. I think it will be a good addition to the list.
https://helm.sh/

**Comment by kamranahmedse** [comment]
Thank you for opening the issue. Helm would fall under a subtree of Kubernetes. Since we don't have a subtree for Kubernetes, I don't see where we can fit Helm in the roadmap. However, we plan on adding a separate roadmap for the Kubernetes ecosystem and would have it there.
