### ISSUE TITLE
Flutter is best mobile framework

### ISSUE THREAD

**Issue by xpwmaosldk** [kamranahmedse/developer-roadmap#1058]
#### What roadmap is this issue about?

- [x] Frontend Roadmap
- [ ] Backend Roadmap
- [ ] DevOps Roadmap
- [ ] All Roadmaps

#### What is this issue about?

- [ ] Functionality of the website
- [ ] Discussion for a pull request I would want to open.
- [ ] Addition of a new item
- [ ] Removal of some existing item
- [x] Changing in arrangement
- [ ] General suggestion
- [ ] Sharing an Idea
- [ ] Something else

#### Please acknowledge the below listed

- [x] This is not a duplicate issue. I have searched and there is no existing issue for this.
- [x] I understand that these roadmaps are highly opinionated. The purpose is to not to include everything out there in these roadmaps but to have everything that is most relevant today comparing to the other options listed.
- [x] I have read the [contribution docs](../contributing) before opening this issue.

#### Enter the details about the issue here

Flutter is best mobile framework rather then React Native

Github star of Flutter(135k) more then Recat Native(101k)

And google trend too

Addtional echo system is grow fast

I  recommendation flutter more than anything

**Comment by kamranahmedse** [comment]
Hey, thanks for opening the issue. These roadmaps are opinionated and your recommendations might not align with the author. Also, GitHub stars are not a good measure of usage. React native is definitely more in demand as compared to Flutter. Open any job board and compare the job openings for Flutter and React native, you will see the difference.
