### ISSUE TITLE
Expand Java trail

### ISSUE THREAD

**Issue by mdtausifahmad** [kamranahmedse/developer-roadmap#108]
In the backed section you should expand the technologies related to Java.

**Comment by mdtausifahmad** [comment]
![javastack](https://cloud.githubusercontent.com/assets/11063325/24491983/51a87aa0-1547-11e7-86b6-752ec8700cfc.png)

[Java+Stack.pdf](https://github.com/kamranahmedse/developer-roadmap/files/881310/Java.Stack.pdf)

I am attaching the Java trails.

**Comment by kamranahmedse** [comment]
Hi @mdtausifahmad,

There has been the similar request before. The graph is already too much convoluted and it is becoming difficult to even read. So let's keep keep it to what we have (PHP, Node, Python and Ruby), till we figure out how to fit in everything.

Thank you
