### ISSUE TITLE
Add node about "URL"

### ISSUE THREAD

**Issue by Steindvart** [kamranahmedse/developer-roadmap#1115]
#### What roadmap is this issue about?

- [x] Frontend Roadmap
- [x] Backend Roadmap

#### What is this issue about?

- [ ] Functionality of the website
- [x] Discussion for a pull request I would want to open.
- [x] Addition of a new item
- [ ] Removal of some existing item
- [ ] Changing in arrangement
- [ ] General suggestion
- [x] Sharing an Idea
- [ ] Something else

#### Please acknowledge the below listed

- [x] This is not a duplicate issue. I have searched and there is no existing issue for this.
- [x] I understand that these roadmaps are highly opinionated. The purpose is to not to include everything out there in these roadmaps but to have everything that is most relevant today comparing to the other options listed.
- [x] I have read the [contribution docs](../contributing) before opening this issue.

#### Enter the details about the issue here

We have nodes about `DNS` and `Hosting`, but nothing about `URL`, the technology that are inextricably linked to them. And I think it is important, for fullness of the roadmap (and student's understanding), to add a node about `URL`.

I made a sketch how I see this:
![Screenshot_3](https://user-images.githubusercontent.com/53004350/152668067-65321fcf-929d-44f5-92ee-1fb7b1e3736b.png)

What do you think?

**Comment by larshei** [comment]
URL/URI are part of understanding DNS,
so it should already be covered?

**Comment by Steindvart** [comment]
> URL/URI are part of understanding DNS, so it should already be covered?

@larshei, the URL involves understanding the abstraction of the domain name, not the other way around. Because the domain name is part of it. But besides it there are also things like "protocol" (http(s), ftp and etc.), "port", "path", "query" and "fragments". Which are quite an important part for understanding web-technology in general, both for the frontend and the backend.

![image](https://user-images.githubusercontent.com/53004350/152717901-c196a53f-79d0-4520-922e-2b3af656b84f.png)

**Comment by kamranahmedse** [comment]
Thank you for opening the issue. We don't want to convolute the roadmap by mentioning every available option. Someone learning about the internet would automatically come across the URL and learn about it, so no need to convolute the roadmap further imho.

This has also been [mentioned in the contribution docs](https://github.com/kamranahmedse/developer-roadmap/blob/master/contributing.md#guidelines). 
Thank you for your suggestion though 🙏
