### ISSUE TITLE
Machine Learning path

### ISSUE THREAD

**Issue by OlegZero13** [kamranahmedse/developer-roadmap#119]
Hello,

First of all, congratulations on your idea!
I would like to loosely ask about the possible place of the _machine learning_ and _AI_ within web development area. Do you think it should too belong there somewhere? Specifically, libraries such as _scikit-learn_ and _tensorflow_ are used to power up certain functionalities, although _ML/AI_ is like a field within itself.

Thanks!

**Comment by kazyka** [comment]
No need, read here for machine learning. [Link here](https://github.com/kazyka/data-science-ipython-notebooks), I know its for python ,but non the less it could be applied to any language and its ofcourse good to read math books, like concrete mathematics and algorithms 4th Ed and Aintroduction to Algorithmes 3rd Ed.

**Comment by OlegZero13** [comment]
Fantastic. Thank you very much for your contribution!

**Comment by bodlaranjithkumar** [comment]
I think this is a masterpiece on full stack web development languages available in 2017.

**Comment by OlegZero13** [comment]
It would be interesting to port _Tensorflow_ and/or _sklearn_ to Ruby. It;s be like an ultimate pleasure I suppose :)

**Comment by kamranahmedse** [comment]
New roadmap requests are being tracked through [roadmap.sh](https://github.com/kamranahmedse/roadmap.sh). Thank you!
