### ISSUE TITLE
Is there a tool to edit the JSON files of roadmaps?

### ISSUE THREAD

**Issue by BOLT04** [kamranahmedse/developer-roadmap#1197]
#### What roadmap is this issue about?

- [ ] Frontend Roadmap
- [ ] Backend Roadmap
- [ ] DevOps Roadmap
- [ ] All Roadmaps
- [x] New roadmap

#### What is this issue about?

- [ ] Functionality of the website
- [ ] Discussion for a pull request I would want to open.
- [ ] Addition of a new item
- [ ] Removal of some existing item
- [ ] Changing in arrangement
- [ ] General suggestion
- [ ] Sharing an Idea
- [x] Something else

#### Please acknowledge the below listed

- [x] This is not a duplicate issue. I have searched and there is no existing issue for this.
- [x] I understand that these roadmaps are highly opinionated. The purpose is to not to include everything out there in these roadmaps but to have everything that is most relevant today comparing to the other options listed.
- [x] I have read the [contribution docs](../contributing) before opening this issue.

#### Enter the details about the issue here

Hi everyone 👋 ,

I'm interested in adding a new roadmap, but I'm not sure how to build the JSON file that a roadmap requires. I was wondering if we wanted to change the boxes, arrows, and text on any roadmap, do we need to edit the JSON file manually, e.g. `public/project/frontend.json`?

Is there any tool to facilitate this?

In the contribution docs, it states `Please provide a rough textual roadmap with what you have in mind with an issue and we can take it from there`. But can we add new roadmaps on a local copy of the repo, without submitting an issue? To simply get it working locally then download an image with the roadmap.

I know how to change the content of the nodes with markdown. Just asking about the JSON roadmap file 🙂.

Any help is very much appreciated 👍,
Thanks!

**Comment by BOLT04** [comment]
From the comment https://github.com/kamranahmedse/developer-roadmap/pull/1190#issuecomment-1073534959 I know we can use [Balsamiq](https://balsamiq.com/) to do the mockups, then there is this tool to convert `.bmpr` files to JSON: https://github.com/waqasilyas/json-converter-bmpr.

Closing this issue since these two tools allow a better experience than to edit JSON files manually 👍

**Comment by zixuniaowu** [comment]
> @BOLT04 hi thanks a lot 
when I use https://github.com/waqasilyas/json-converter-bmpr. to  convert .bmpr files to JSON
seems the json file format is different to the current one. and when open got some error:
------------------------------------------------------------------------------------------
There was an error.
Try loading the page again. or submit an issue on GitHub with following:

Cannot read properties of undefined (reading 'measuredW')
TypeError: Cannot read properties of undefined (reading 'measuredW') at D (http://localhost:3000/node_modules/.vite/deps/roadmap-renderer.js?v=f4505f10:221:27)
___________________________________________________________________________________
what about your suggest?

**Comment by BOLT04** [comment]
> > @BOLT04 hi thanks a lot 
> when I use https://github.com/waqasilyas/json-converter-bmpr. to  convert .bmpr files to JSON
> seems the json file format is different to the current one. and when open got some error:
> ------------------------------------------------------------------------------------------
> There was an error.
> Try loading the page again. or submit an issue on GitHub with following:
> 
> Cannot read properties of undefined (reading 'measuredW')
> TypeError: Cannot read properties of undefined (reading 'measuredW') at D (http://localhost:3000/node_modules/.vite/deps/roadmap-renderer.js?v=f4505f10:221:27)
> ___________________________________________________________________________________
> what about your suggest?

I was able to do a workaround but i dont remember 😅

**Comment by marcthayer** [comment]
@BOLT04 Do you know of a good way to edit existing roadmaps since the BMPR files aren't committed?
