### ISSUE TITLE
Debugging tools

### ISSUE THREAD

**Issue by joestrong** [kamranahmedse/developer-roadmap#12]
I consider debugging tools to be essential to development.

For the languages I know:
- xdebug for PHP
- browser dev tools for Frontend JS

**Comment by ascendbruce** [comment]
Agree!

Add one more debugger I know:

* [byebug](https://github.com/deivid-rodriguez/byebug) for ruby

**Comment by dmitry** [comment]
`ltrace` and `strace` are missing, when application debuggers are not enough.

**Comment by kamranahmedse** [comment]
This has been fixed and will be published in the coming release. Thank you 🙏
