### ISSUE TITLE
Add gofiber to Go Roadmap

### ISSUE THREAD

**Issue by vividsystem** [kamranahmedse/developer-roadmap#1221]
I'd like to suggest the addition of gofiber(https://gofiber.io/) to the list of webfameworks as it's the fastest one in its field and is great for people used to express. It also offers many useful pre-made middlewares like a jwt validator

EDIT: sorry for not using the template, it doesn't work on the mobile version

**Comment by kamranahmedse** [comment]
This has been fixed and will be published in the coming release. Thank you 🙏
