### ISSUE TITLE
Suggetion for Odata to be added to the FE and BE roadmaps

### ISSUE THREAD

**Issue by FelipeMathieu** [kamranahmedse/developer-roadmap#1224]
#### What roadmap is this issue about?

- [x] Frontend Roadmap
- [x] Backend Roadmap
- [ ] DevOps Roadmap
- [ ] All Roadmaps

#### What is this issue about?

- [ ] Functionality of the website
- [ ] Discussion for a pull request I would want to open.
- [x] Addition of a new item
- [ ] Removal of some existing item
- [ ] Changing in arrangement
- [x] General suggestion
- [x] Sharing an Idea
- [ ] Something else

#### Please acknowledge the below listed

- [x] This is not a duplicate issue. I have searched and there is no existing issue for this.
- [x] I understand that these roadmaps are highly opinionated. The purpose is to not to include everything out there in these roadmaps but to have everything that is most relevant today comparing to the other options listed.
- [x] I have read the [contribution docs](../contributing) before opening this issue.

#### Enter the details about the issue here

Hey guys.
I'm opening this issue to share one more thought about the FE and BE roadmaps. I'd like to suggest an additional item at the same level as GraphQL. I've been using Odata for many years now and this tool is as powerful as GraphQL can be. There are a couple of libs for FE to consume it and there is a very consolidated lib for C# to implement it. I know it's a more C# oriented solution, but I think it makes sense to be there. With that said, I think is a little bit more straightforward than GraphQL actually, once it's a well-implemented tool. However, the result of both is very similar.
Here is a good document comparing both https://www.educba.com/odata-vs-graphql/

Well, one more thought I think that could be helpful for everybody who likes this kind of solution. Best regards.

**Comment by kamranahmedse** [comment]
This has been fixed and will be published in the coming release. Thank you 🙏
