### ISSUE TITLE
GraphQL issue

### ISSUE THREAD

**Issue by discover59** [kamranahmedse/developer-roadmap#1225]
#### What roadmap is this issue about?

- [ ] Frontend Roadmap
- [x] Backend Roadmap
- [ ] DevOps Roadmap
- [ ] All Roadmaps

#### What is this issue about?

- [ ] Functionality of the website
- [ ] Discussion for a pull request I would want to open.
- [ ] Addition of a new item
- [ ] Removal of some existing item
- [x] Changing in arrangement
- [ ] General suggestion
- [ ] Sharing an Idea
- [ ] Something else

#### Please acknowledge the below listed

- [x] This is not a duplicate issue. I have searched and there is no existing issue for this.
- [x] I understand that these roadmaps are highly opinionated. The purpose is to not to include everything out there in these roadmaps but to have everything that is most relevant today comparing to the other options listed.
- [x] I have read the [contribution docs](../contributing) before opening this issue.

#### Enter the details about the issue here

Would you explain why GraphQL is not listed in `Learn About APIs` section?

**Comment by 0xf10yd** [comment]
It's mentioned right after `Containerization vs. Virtualization` part, kindly recheck the roadmap.
@discover59

**Comment by discover59** [comment]
Yes, I saw it on that part. My question is why it's not in APIs section.

**Comment by 0xf10yd** [comment]
From a personal perspective, if you're building a complex system, micro-frontends or Event-Driven services, then you'll definitely choose graphql which is more related to brokers.
The APIs mentioned in the roadmap are merely standard, while graphql is a query manipulation language and it takes time and effort to build something realistic that meets modern requirements.
Relatively speaking, I think it should've been right after the APIs section, but not within it.
