### ISSUE TITLE
Angular roadmap: add change detection

### ISSUE THREAD

**Issue by nickbullock** [kamranahmedse/developer-roadmap#1226]
#### What roadmap is this issue about?

- [x] Frontend Roadmap
- [ ] Backend Roadmap
- [ ] DevOps Roadmap
- [ ] All Roadmaps

#### What is this issue about?

- [ ] Functionality of the website
- [ ] Discussion for a pull request I would want to open.
- [x] Addition of a new item
- [ ] Removal of some existing item
- [ ] Changing in arrangement
- [ ] General suggestion
- [ ] Sharing an Idea
- [ ] Something else

#### Please acknowledge the below listed

- [x] This is not a duplicate issue. I have searched and there is no existing issue for this.
- [x] I understand that these roadmaps are highly opinionated. The purpose is to not to include everything out there in these roadmaps but to have everything that is most relevant today comparing to the other options listed.
- [x] I have read the [contribution docs](../contributing) before opening this issue.

#### Enter the details about the issue here
I suggest adding Change Detection to advanced topics, because:
- it's a core concept, understanding of which will help you optimize your apps at scale
- it's a common question / topic for middle/middle+ positions on interviews

**Comment by kamranahmedse** [comment]
This has been fixed and is being deployed. Thank you 🙏
