### ISSUE TITLE
[Suggestion] Add Log Management tools to DevOps Path

### ISSUE THREAD

**Issue by IuryAlves** [kamranahmedse/developer-roadmap#123]
A log management tool isn`t always inside a monitoring tool.

It would be good to have a section about log management tools, like:

* Graylog
* Kibana + logstash
* Splunk

**Comment by damengilland** [comment]
Don't forget papertrail! (=

* Papertrail - cloud-hosted log management, live in seconds || https://papertrailapp.com/

**Comment by GrayW** [comment]
@damengilland How could I forget that :)! Will add the change this afternoon if I get chance.

**Comment by kamranahmedse** [comment]
Done. Thanks
