### ISSUE TITLE
Stanford's white-paper on "How does the Internet Works" links to access forbidden page

### ISSUE THREAD

**Issue by Phishback** [kamranahmedse/developer-roadmap#1252]
#### What roadmap is this issue about?

- [ x ] Frontend Roadmap
- [ ] Backend Roadmap
- [ ] DevOps Roadmap
- [ ] All Roadmaps

#### What is this issue about?

- [ x ] Functionality of the website
- [ ] Discussion for a pull request I would want to open.
- [ ] Addition of a new item
- [ ] Removal of some existing item
- [ ] Changing in arrangement
- [ ] General suggestion
- [ ] Sharing an Idea
- [ ] Something else

#### Please acknowledge the below listed

- [ x ] This is not a duplicate issue. I have searched and there is no existing issue for this.
- [ x ] I understand that these roadmaps are highly opinionated. The purpose is to not to include everything out there in these roadmaps but to have everything that is most relevant today comparing to the other options listed.
- [ x ] I have read the [contribution docs](../contributing) before opening this issue.

#### Enter the details about the issue here

 I noticed going through the roadmap when clicking on Internet -> How does the Internet Work? article from Stanford is showing access forbidden. Not sure if they removed it / removed permission to view it as it doesn't appear to be a server error on their end but indeed 403 forbidden.

**Comment by Ashvith** [comment]
@Phishback [this](https://web.stanford.edu/class/archive/cs/cs106a/cs106a.1216/handouts_w2021/lecture-25-internet.html) is the working link I was able to find. Maybe someone can push a PR and update the old, broken link.

**Comment by Phishback** [comment]
@Ashvith Looks like it got updated somewhere but can't find the PR so closing!
