### ISSUE TITLE
Feature Topic Request: IDL's

### ISSUE THREAD

**Issue by arcman7** [kamranahmedse/developer-roadmap#1253]
#### What roadmap is this issue about?

- [x] Frontend Roadmap
- [x] Backend Roadmap
- [ ] DevOps Roadmap
- [ ] All Roadmaps

#### What is this issue about?

- [ ] Functionality of the website
- [ ] Discussion for a pull request I would want to open.
- [x] Addition of a new item
- [ ] Removal of some existing item
- [ ] Changing in arrangement
- [x] General suggestion
- [ ] Sharing an Idea
- [ ] Something else

#### Please acknowledge the below listed

- [x] This is not a duplicate issue. I have searched and there is no existing issue for this.
- [x ] I understand that these roadmaps are highly opinionated. The purpose is to not to include everything out there in these roadmaps but to have everything that is most relevant today comparing to the other options listed.
- [x ] I have read the [contribution docs](../contributing) before opening this issue.

#### Enter the details about the issue here

I realize that not every JavaScript developer is going to have a need for understanding IDL's, but there's a good argument for having more JavaScript developers aware of their existence and hopefully the ability for making use of them as well. Take for example this one: https://github.com/kripken/ammo.js/blob/main/ammo.idl

This comes from the ammo js library, an advanced physics engine written in C++ ported over to JavaScript. JavaScript developers stand in the unique position of mainly using high-level abstractions when interacting with code; they don't interact with pointers, or even need to worry about memory cleanup (for the most part), but they can also tap into the powerful processing power and speed of lower level languages such as C++ or precompiled binaries such as WASM using IDLs. I think more web developers should be aware of these tools and adding this to your list of covered topics would be a huge benefit or developers in general who want a guided approach to learning about them.

**Comment by kamranahmedse** [comment]
This has been fixed and will be published in the coming release. Thank you 🙏
