### ISSUE TITLE
Is a Flutter roadmap on the horizon?

### ISSUE THREAD

**Issue by camerongable** [kamranahmedse/developer-roadmap#1279]
#### What roadmap is this issue about?

- [x] Frontend Roadmap
- [ ] Backend Roadmap
- [ ] DevOps Roadmap
- [ ] All Roadmaps

#### What is this issue about?

- [ ] Functionality of the website
- [ ] Discussion for a pull request I would want to open.
- [x] Addition of a new item
- [ ] Removal of some existing item
- [ ] Changing in arrangement
- [ ] General suggestion
- [ ] Sharing an Idea
- [ ] Something else

#### Please acknowledge the below listed

- [x] This is not a duplicate issue. I have searched and there is no existing issue for this.
- [x] I understand that these roadmaps are highly opinionated. The purpose is to not to include everything out there in these roadmaps but to have everything that is most relevant today comparing to the other options listed.
- [x] I have read the [contribution docs](../contributing) before opening this issue.

#### Enter the details about the issue here

Is there any discussion about a Flutter roadmap. There has been a lot of momentum and buzz around Flutter lately. There aren't very many good resources about what to learn for Flutter since it is so new. After the release of Flutter 3, I am sure the momentum will continue.

**Comment by Manuel-DaSilva** [comment]
I believe this is a great opportunity, having a flutter roadmap would be amazing. I found this project while researching for a flutter roadmap.

**Comment by Tiska** [comment]
we are currenty writing a roadmap for internal purpose, we would like to propose a PR on this repo but I can't find a how or documentation to on this repo ?

**Comment by kamranahmedse** [comment]
Thanks, @Tiska -- feel free to [submit a textual format similar to this JavaScript roadmap](https://gist.github.com/kamranahmedse/98758d2c73799b3a6ce17385e4c548a5).

**Comment by kamranahmedse** [comment]
[Flutter roadmap is live](https://roadmap.sh/flutter). Thank you guys!
