### ISSUE TITLE
Pinia instead VueX

### ISSUE THREAD

**Issue by GustavoPrietoCode** [kamranahmedse/developer-roadmap#1285]
#### What roadmap is this issue about?

- [X ] Frontend Roadmap
- [ ] Backend Roadmap
- [ ] DevOps Roadmap
- [ ] All Roadmaps

#### What is this issue about?

- [ ] Functionality of the website
- [ ] Discussion for a pull request I would want to open.
- [X ] Addition of a new item
- [X ] Removal of some existing item
- [ ] Changing in arrangement
- [ ] General suggestion
- [ ] Sharing an Idea
- [ ] Something else

#### Please acknowledge the below listed

- [X ] This is not a duplicate issue. I have searched and there is no existing issue for this.
- [ X] I understand that these roadmaps are highly opinionated. The purpose is to not to include everything out there in these roadmaps but to have everything that is most relevant today comparing to the other options listed.
- [X ] I have read the [contribution docs](../contributing) before opening this issue.

#### Enter the details about the issue here

Vuejs recommend to use Pinia (https://pinia.vuejs.org/), instead VueX.

**Comment by marcusviniciusg03dev** [comment]
Hi! i don't ask to remove Vuex, but i wrote new Pinia file in a new pull request. Now i'm just waiting the maintainer approve or disapprove the PR. Thank you for asking for Pinia resource, and i hope i've helped!

**Comment by kamranahmedse** [comment]
This has been fixed and will be published in the coming release. Thank you 🙏

**Comment by marcusviniciusg03dev** [comment]
> This has been fixed and will be published in the coming release. Thank you 🙏 

Thank you so much!
