### ISSUE TITLE
unclear about meaning of "pick any"

### ISSUE THREAD

**Issue by grizfan** [kamranahmedse/developer-roadmap#129]
hi - maybe it's just me, but the "pick any" label is a bit unclear, especially in the context of the beginning "required for any path" block. If these are required, then pick any doesn't apply, it should be "pick all", or am I misreading this? 

I have a summer intern starting in a few weeks and I think this will be an excellent resource for her. Thanks for the great work!

**Comment by NonameSLdev** [comment]
The gold, the recommendation, is something that's recommended to use.
The silver, the possibility, is something that's also good, but not as good as the recommendation.
The bronze, the **"pick any"** is other possibilities, but they are not recommended.

I agree that it's unclear - I had to figure that ^ out by myself after taking a good look. The names should be reconsidered.

**Comment by alinnert** [comment]
I don't think this is how it works if I look at JavaScript frameworks. I read it like "pick any, all are fine".
I even see the gray (silver) ones as "least ideal", but still not "bad".
But I do agree that the colors and the legends could need a rework.

**Comment by kamranahmedse** [comment]
This has been fixed and will be published in the coming release. Thank you 🙏
