### ISSUE TITLE
GitLab should be included as a serious alternative to GitHub

### ISSUE THREAD

**Issue by eddieajau** [kamranahmedse/developer-roadmap#130]
Couple of reasons:

* free private repo's and free org's
* integrated CI (which can be also added to the DevOps chart)
* it's Open Source (GitHub is not)
* you can submit issues that are tracked openly and transparently (everyone knows the GitHub email is a back hole of in-action - gist comment notifications anyone)
* the company is completely focused on the product, not the latest social issue (not that the later is necessarily a bad thing, expect when you seem to be doing more of it than actually building your product)

**Comment by UnitedPE** [comment]
+1

**Comment by luchillo17** [comment]
@UnitedPE Dude dont `+1` the issues you want to support, that's the reason for the 👍  emojis under the issues.

Want to express your support? click the emoji, don't clutter the issue comment history with just `+1` that don't add nothing else to the discussion.

**Comment by uitgewis** [comment]
+1

**Comment by damengilland** [comment]
So look, there are a lot of alternatives to GitHub...

I'd go with Atlassian Bitbucket and AWS CodeCommit over GitLab.  GitLab may get there... but it'll be a while.

And... like I fundamentally don't trust them.  Hard to recommend them to enterprise clients given some of their major SNAFUs in the last year.

* GitLab.com Database Incident | GitLab || https://about.gitlab.com/2017/02/01/gitlab-dot-com-database-incident/

* GitLab.com Database Incident | GitLab || https://about.gitlab.com/2017/02/01/gitlab-dot-com-database-incident/

**Comment by luchillo17** [comment]
I actually have respect for them, though i can't say nothing about their service since i don't use it.

When i say i respect them, is because almost none organization has the b%lls to admit they screw up, they did messed up, and most likely they will not make the same mistake again, at least they are honest with their clients.

To me that's impressive.

**Comment by eddieajau** [comment]
> Hard to recommend them to enterprise clients given some of their major SNAFUs in the last year.

They all have their moments. GitHub has had some stunning failures over the years.

**Comment by NonameSLdev** [comment]
Instead of arguing over who's the best, maybe make this issue about adding alternatives to github _such as_ bitbucket, gitlab, etc.?

**Comment by jeffanthony** [comment]
Git is part of the devops stack, GitHub, GitLab etc. are simply variations of that tool, some with additional awesome features. That being said i consider GitLab to be the 'in-house' solution while GitHub is the 'outsource' solution

**Comment by kamranahmedse** [comment]
@eddieajau thank you for reporting but Github is mentioned not because you should learn it but because of the way it is being used for the opensource and that you should use it to look at the code that people have been sharing.
