### ISSUE TITLE
Add Redux Toolkit (RTK) to the React roadmap

### ISSUE THREAD

**Issue by Briscoooe** [kamranahmedse/developer-roadmap#1302]
#### What roadmap is this issue about?

- [x] Frontend Roadmap
- [ ] Backend Roadmap
- [ ] DevOps Roadmap
- [ ] All Roadmaps

#### What is this issue about?

- [ ] Functionality of the website
- [ ] Discussion for a pull request I would want to open.
- [x] Addition of a new item
- [ ] Removal of some existing item
- [ ] Changing in arrangement
- [ ] General suggestion
- [ ] Sharing an Idea
- [ ] Something else

#### Please acknowledge the below listed

- [x] This is not a duplicate issue. I have searched and there is no existing issue for this.
- [x] I understand that these roadmaps are highly opinionated. The purpose is to not to include everything out there in these roadmaps but to have everything that is most relevant today comparing to the other options listed.
- [x] I have read the [contribution docs](../contributing) before opening this issue.

#### Enter the details about the issue here

[Redux Toolkit](https://redux-toolkit.js.org/) should be added to the React roadmap under `Ecosystem -> State management`. It is, by React's own admission, the [official recommended approach for writing Redux logic](https://redux.js.org/introduction/why-rtk-is-redux-today)

**Comment by kamranahmedse** [comment]
This has been fixed and will be published in the coming release. Thank you 🙏
