### ISSUE TITLE
Changing the starred ranking of this repository

### ISSUE THREAD

**Issue by cr2007** [kamranahmedse/developer-roadmap#1309]
#### What roadmap is this issue about?

- [ ] Frontend Roadmap
- [ ] Backend Roadmap
- [ ] DevOps Roadmap
- [X] All Roadmaps

#### What is this issue about?

- [ ] Functionality of the website
- [ ] Discussion for a pull request I would want to open.
- [ ] Addition of a new item
- [ ] Removal of some existing item
- [X] Changing in arrangement
- [ ] General suggestion
- [ ] Sharing an Idea
- [X] Something else

#### Please acknowledge the below listed

- [X] This is not a duplicate issue. I have searched and there is no existing issue for this.
- [X] I understand that these roadmaps are highly opinionated. The purpose is to not to include everything out there in these roadmaps but to have everything that is most relevant today comparing to the other options listed.
- [X] I have read the [contribution docs](../contributing) before opening this issue.

#### Enter the details about the issue here

When looking at the [most starred GitHub repositories](https://github.com/search?o=desc&q=stars%3A%3E100000&s=stars&type=Repositories), I noticed that [roadmap.sh](roadmap.sh) is officially back in the 6th place instead of the 7th place.

So I wanted to update this change in [`opensource-banner.tsx`](https://github.com/kamranahmedse/developer-roadmap/blob/master/components/opensource-banner.tsx), where I can change the necessary details to change the ranking from 7th to 6th position.

**Comment by cr2007** [comment]
@kamranahmedse

**Comment by kamranahmedse** [comment]
This has been fixed and deployed, thank you!
