### ISSUE TITLE
Provide link somehow to the technologies mentioned

### ISSUE THREAD

**Issue by brijeshprasad89** [kamranahmedse/developer-roadmap#131]
Can we provide link for documentation to all the technologies that are mentioned. I have not yet decided how it can be achieved. But I feel that would be a nice feature and complete the entire package.

**Comment by luchillo17** [comment]
If i remember correctly it's in the roadmap, or at least in the `TODO` section of the README.

**Comment by kamranahmedse** [comment]
These will be added on the website [roadmap.sh](https://roadmap.sh) instead of the repository in the coming weeks after we are done with the 2020 release. Thank you 🙏
