### ISSUE TITLE
Typo in DevOps /roadmaps/devops.png

### ISSUE THREAD

**Issue by creacha** [kamranahmedse/developer-roadmap#1310]
#### What roadmap is this issue about?

- [ ] Frontend Roadmap
- [ ] Backend Roadmap
- [x] DevOps Roadmap
- [ ] All Roadmaps

#### What is this issue about?

- [ ] Functionality of the website
- [ ] Discussion for a pull request I would want to open.
- [ ] Addition of a new item
- [ ] Removal of some existing item
- [ ] Changing in arrangement
- [x] General suggestion
- [ ] Sharing an Idea
- [ ] Something else

#### Please acknowledge the below listed

- [x] This is not a duplicate issue. I have searched and there is no existing issue for this.
- [x] I understand that these roadmaps are highly opinionated. The purpose is to not to include everything out there in these roadmaps but to have everything that is most relevant today comparing to the other options listed.
- [x] I have read the [contribution docs](../contributing) before opening this issue.

#### Enter the details about the issue here

In the DevOps roadmap.png, in the Learn about Managing Servers item, there is a grammatical error. 

Current:
"Pick Ubuntu if you have a little
no experience with Linux."

Proposed:
"Pick Ubuntu if you have little to no experience with Linux."
OR
"Pick Ubuntu if you have (only) a little or no experience with Linux"

Screenshot:
![Screen Shot 2022-06-27 at 10 56 55](https://user-images.githubusercontent.com/338300/175846064-7e0453e2-e20d-4f06-a52e-5d04e19b348e.png)

Obviously, this item expresses the author's opinion, so I can't propose a single correct wording. However, the current doesn't make sense.

**Comment by kamranahmedse** [comment]
This has been fixed and will be published in the coming release. Thank you 🙏
