### ISSUE TITLE
[Suggestion] Move programming principles to the top

### ISSUE THREAD

**Issue by afontcu** [kamranahmedse/developer-roadmap#132]
I'd argue that SOLID, YAGNI, KISS... should be moved to the Introduction section, since I believe every developer should know about this principles and would benefit from them, no matter what language/environment she is working on.

Maybe also Security and Regular Expressions could be moved too.

**Comment by luchillo17** [comment]
Not only would benefit all developers but adopting them early will solidify such principles on new developers, they are named principles for a reason.

**Comment by kamranahmedse** [comment]
There have been changes made to that section which makes this issue outdated. Thank you for reporting though 🙏
