### ISSUE TITLE
READJourney to HTTP/2 need fix link

### ISSUE THREAD

**Issue by coldSeattle** [kamranahmedse/developer-roadmap#1320]
#### What roadmap is this issue about?

- [ ] Frontend Roadmap
- [x] Backend Roadmap
- [ ] DevOps Roadmap
- [ ] All Roadmaps

#### What is this issue about?

- [ ] Functionality of the website
- [ ] Discussion for a pull request I would want to open.
- [ ] Addition of a new item
- [x] Removal of some existing item
- [ ] Changing in arrangement
- [ ] General suggestion
- [ ] Sharing an Idea
- [ ] Something else

#### Please acknowledge the below listed

- [x] This is not a duplicate issue. I have searched and there is no existing issue for this.
- [ ] I understand that these roadmaps are highly opinionated. The purpose is to not to include everything out there in these roadmaps but to have everything that is most relevant today comparing to the other options listed.
- [ ] I have read the [contribution docs](../contributing) before opening this issue.

#### Enter the details about the issue here

link [developer-roadmap](https://github.com/kamranahmedse/developer-roadmap)/[content](https://github.com/kamranahmedse/developer-roadmap/tree/master/content)/[roadmaps](https://github.com/kamranahmedse/developer-roadmap/tree/master/content/roadmaps)/[101-backend](https://github.com/kamranahmedse/developer-roadmap/tree/master/content/roadmaps/101-backend)/[content](https://github.com/kamranahmedse/developer-roadmap/tree/master/content/roadmaps/101-backend/content)/[100-internet](https://github.com/kamranahmedse/developer-roadmap/tree/master/content/roadmaps/101-backend/content/100-internet)/101-what-is-http.md

[READJourney to HTTP/2](https://kamranahmed.info/blog/2016/08/13/http-in-depth/) is not currect link

**Comment by kamranahmedse** [comment]
This has been fixed. Thank you for reporting.
