### ISSUE TITLE
[Suggestion] Add MobX under react.

### ISSUE THREAD

**Issue by john-d-pelingo** [kamranahmedse/developer-roadmap#133]
IMO, [MobX](https://github.com/mobxjs/mobx) deserves a spot under react together with flux and redux. Although I am not sure if this is relevant for 2017.

**Comment by luchillo17** [comment]
I think there's no real reason to put it, it works but today we use either Flux or Redux, since it's a roadmap that shows what should or could be learned, i don't consider MobX an option.

Though that's just my humble opinion, it depends on the rest of the community and the repo owners.

**Comment by kamranahmedse** [comment]
There have been changes made to that section which makes this issue outdated. Thank you for reporting though 🙏
