### ISSUE TITLE
Proposing a change

### ISSUE THREAD

**Issue by dvnschmchr** [kamranahmedse/developer-roadmap#1334]
#### What roadmap is this issue about?

- [X ] Frontend Roadmap
- [ ] Backend Roadmap
- [ ] DevOps Roadmap
- [ ] All Roadmaps

#### What is this issue about?

- [ ] Functionality of the website
- [ ] Discussion for a pull request I would want to open.
- [ ] Addition of a new item
- [ X] Removal of some existing item
- [ ] Changing in arrangement
- [ ] General suggestion
- [ ] Sharing an Idea
- [ ] Something else

#### Please acknowledge the below listed

- [X ] This is not a duplicate issue. I have searched and there is no existing issue for this.
- [X ] I understand that these roadmaps are highly opinionated. The purpose is to not to include everything out there in these roadmaps but to have everything that is most relevant today comparing to the other options listed.
- [X ] I have read the [contribution docs](../contributing) before opening this issue.

#### Enter the details about the issue here

I hope i did this workflow correctly - sorry still new to this all.

I am going through the roadmap to learn web development / programming. 

Thel ink to the course "build 15 websites with javascript" (Build 15 JavaScript Projects - Vanilla JavaScript) feels really out of place to me in the HTML course....

I have not even got to CSS yet, much less Javascript.

Is this intentional or an error? I feel like it should be moved or removed.

Just my 2cents. 

Cheers

**Comment by kamranahmedse** [comment]
It was indeed a mistake, this should have been under the JavaScript node. Thank you for pointing out!
