### ISSUE TITLE
Add Path for Quality Assurance

### ISSUE THREAD

**Issue by damengilland** [kamranahmedse/developer-roadmap#135]
While this isn't a development role, I wanted to open a ticket to encourage people to talk about this.

This was a "getting to done" checklist from an agency I worked at in the past... may not be useful for all projects, but important that we all acknowledge that getting a site built / launched / supported / improved / maintained does take more than just developers.

* General Web Project Overview - Google Sheets || https://docs.google.com/spreadsheets/d/1rGSHT2kZQCahDqoQkryLJ1b3rEq_uVLEX2Qe10RCxB8

**Comment by damengilland** [comment]
Personally, I feel like QA is probably the highest ROI of any role on a project.  Good requirements help a lot... but having people who can catch bugs, and communicate bugs correctly is key for getting professional products shipped.  Assume I had only 2 people on staff, after the first dev my second hire is always a quality assurance role.

**Comment by kamranahmedse** [comment]
Thanks for reporting but this is strictly for the development.
