### ISSUE TITLE
Add Path for Visual Design

### ISSUE THREAD

**Issue by damengilland** [kamranahmedse/developer-roadmap#137]
While this isn't a development role, I wanted to open a ticket to encourage people to talk about this.

This was a "getting to done" checklist from an agency I worked at in the past... may not be useful for all projects, but important that we all acknowledge that getting a site built / launched / supported / improved / maintained does take more than just developers.

* General Web Project Overview - Google Sheets || https://docs.google.com/spreadsheets/d/1rGSHT2kZQCahDqoQkryLJ1b3rEq_uVLEX2Qe10RCxB8

**Comment by damengilland** [comment]
Not a dev thing.

**Comment by togiberlin** [comment]
https://github.com/togiberlin/ui-ux-designer-roadmap

**Comment by damengilland** [comment]
I think of Visual Design more like brand and traditional "graphic design" skillset.  Less UX.

**Comment by kamranahmedse** [comment]
Thanks for reporting but this is strictly for the development.
