### ISSUE TITLE
DevOps roadmap sub sections are not selectable

### ISSUE THREAD

**Issue by paulmarsicloud** [kamranahmedse/developer-roadmap#1388]
Sub-sections of the following sections are not selectable:

- [ ] Linux
- [ ] Unix
- [ ] Terminal Multiplexers
- [ ] Process Monitoring
- [ ] System Performance
- [ ] Network Tools
- [ ] Text Manipulation Tools
- [ ] Other

Not sure if this is by design or not

**Comment by kamranahmedse** [comment]
It was indeed a mistake, this has been fixed in the latest release. Thank you 🙏
