### ISSUE TITLE
Where is elixir ?

### ISSUE THREAD

**Issue by ricking06** [kamranahmedse/developer-roadmap#139]
Like seriously i cant see elixir ?

**Comment by kamranahmedse** [comment]
For now, it doesn't include the functional languages; I could include Elixir, Haskell, Clojure etc but I didn't want to convolute the charts and thus mentioned are the ones that are more in demand for the web development. However, I have plans of restructuring some of the stuff; I might add them in future. 

Thank you for reporting though.
