### ISSUE TITLE
Static site generators / JAMstack

### ISSUE THREAD

**Issue by hsribei** [kamranahmedse/developer-roadmap#141]
I think those deserve a mention as well. Congrats on the great guide!

**Comment by kamranahmedse** [comment]
Hi @hsribei, 

Thank you, I am glad you liked it.

For sure they do but they aren't a *must learn* for being a web developer. The charts do not mention each and everything and only focus on the bare minimum that one needs to know for being a web developer. For example, I have never seen any job description demanding the knowledge of static site generators.

Thank you for suggesting though.

**Comment by hsribei** [comment]
That makes sense! Thank you for the thoughtful response, and congrats on
the project.

2017-04-23 23:51 GMT-04:00 Kamran Ahmed <notifications@github.com>:
