### ISSUE TITLE
I made an interactive version of this repository

### ISSUE THREAD

**Issue by nikitavoloboev** [kamranahmedse/developer-roadmap#144]
[Here it is](https://my.mindnode.com/zRGj6Bjd1T31sVhsJz4HcNbCCz7ZMgKNqJSWSjyt#375.4,-197.2,2). 

It's part of a [bigger interactive mind map](https://github.com/nikitavoloboev/knowledge-map) I am making.

I think it is a lot better than just having static images as I embed links for all nodes and users can pan around and see everything. I would love it if you can add a link of it to the repository. I think it would be really useful.

I will also complete one for 'backend' in similar manner and add it. :)

Thank you.

**Comment by vasiljevs** [comment]
@nikitavoloboev Would you be interested switching to [this](https://coggle.it/) mind map?

**Comment by nikitavoloboev** [comment]
I have looked into it but entering information is 100x times slower for me there than in MindNode.

**Comment by vasiljevs** [comment]
@nikitavoloboev I would say not so comfortable to watch and scroll horizontally. It's my personal taste of course!

**Comment by luchillo17** [comment]
@nikitavoloboev As @vasiljevs says it's about the aesthetics, the map generated in the images actually look like have some structure or order, yours feels like a big wide map, hard to look at.

It doesn't mean it's wrong, it's just not as pleasant to look as the images on this repo.

**Comment by NonameSLdev** [comment]
It's nice, but the interface isn't. Design isn't good, ugly default font, no intuitive scrolling, and the horizontal scrolling is annoying. Other than that I like the idea of this being interactive.

**Comment by kamranahmedse** [comment]
@nikitavoloboev thanks for sharing. Looks nice.
