### ISSUE TITLE
any plans for a roadmap for mobile app developer

### ISSUE THREAD

**Issue by huw30** [kamranahmedse/developer-roadmap#145]
This is super helpful, thanks for putting it together. Given the name of this project as `developer-roadmap`, I assume a developer can be a mobile app developer.

**Comment by luchillo17** [comment]
That's actually an interesting one, though i imagine the main ones can't go far from the predilects:

* Java for Android.
* Objective C or Swing (honestly don't remember which) for IOS.
* Cordova for Cross Platform Hybrid mobile development.
* Ionic on top of Cordova with Angular, (there's Ionic 2 that uses Angular 2).

* React Native aiming for native like performance but still using JS as a base with React.
* NativeScript aiming for native like performance but still using JS as a base with Angular 2.
* Xamarin, heard it was like the predecessor of many of the above, though i haven't heard much about it lately.

That basically conforms the map of mobile app developer, we could go in depth on each but those are the main ones.

**Comment by mst-dev** [comment]
Xamarin builds native apps using C# and .NET.

**Comment by Nuruddinjr** [comment]
Indeed this is very helpful and obvious guide, please add native android, iOS developer roadmap,too!! @kamranahmedse !

**Comment by luchillo17** [comment]
@Nuruddinjr I don't think each should have their own roadmap, i think of them as branches of the `Mobile App Developer` roadmap.

**Comment by Nuruddinjr** [comment]
oh yeah , this also works, looking forward to seeing Mobile App Developer roadmap!

**Comment by kamranahmedse** [comment]
Due to lack of knowledge and this being not relevant to "web developer", I will have to close this issue. However I came across this [mobile developer roadmap](https://github.com/godrm/mobile-developer-roadmap); I am not sure about the accuracy of it though. But you may create an issue there.

Thank you for reporting though.

**Comment by luchillo17** [comment]
That was unexpected, I tough this repo was about dev's in general, not just web ones, if you say it's because of lack of knowledge then that's ok, maybe someone​ with a bit more knowledge​ can make a PR.

**Comment by kamranahmedse** [comment]
![image](https://cloud.githubusercontent.com/assets/4921183/26407532/7999f59e-40ac-11e7-9321-ff5c95cae8b6.png)

@luchillo17 it is just the name. I will update it :)
