### ISSUE TITLE
A common platform for Community

### ISSUE THREAD

**Issue by iArchitSharma** [kamranahmedse/developer-roadmap#1456]
Developer-roadmap is such a large project and there are so many individuals ready to help out and improve it, I'm writing this to say that I believe we all need a common platform where the community can engage with one another, like Discord, Slack, etc. This will not only facilitate organised community effort but also encourage participation from newcomers to the open source community. The roadmap materials will be improved with discussion and collaboration on a single platform, and new features will be released more quickly.

Please do consider this could be really beneficial for this amazing project 😇
@kamranahmedse I have messaged you for the same on twitter

**Comment by kamranahmedse** [comment]
Hey Archit, thank you for opening the issue and for all your contributions to the project -- we really *appreciate* it.

Regarding the community, we do have it already. It's just not really active and also we need to do a better job at getting people to join the community. Hopefully, we will change it in the coming weeks or so. You can [join it here](https://discord.gg/g3XGR8WYC2).

Looking forward to seeing you there! :)
