### ISSUE TITLE
What about html5 game development?

### ISSUE THREAD

**Issue by saeidalidadi** [kamranahmedse/developer-roadmap#148]
It would be useful if added a roadmap for html5 game development field.

**Comment by luchillo17** [comment]
`Game developer` could actually be a new branch, that would be awesome.

**Comment by saeidalidadi** [comment]
I am learning game development currently and I should confess that It is so interesting and has more challenges than web development.

I did research on frameworks and libraries for html5 game development and finally as a beginner I prefer to use `phaser` (a wrapper for `Pixi.js`) rather than `cocos2d-js`, `babylon.js`, and 5 others that I read their features also getting started examples. if anyone has a good experience in this field we would be happy to hear any suggestion :)

**Comment by luchillo17** [comment]
Also i wasn't thinking in Web game developer, but in all kind of game developer.

@saeidalidadi In the web side, as far as i know the main fight is between Three.js and Babylon.js, at least when 3D is involved.

**Comment by saeidalidadi** [comment]
I have a web based 2D game idea and looking for a framework  with simplicity and big community so `phaser.js` is the right one I think

**Comment by Osilos** [comment]
@saeidalidadi Look for Pixi.js too

**Comment by kamranahmedse** [comment]
Hey, that isn't in our scope but we might add it as a part of [roadmap.sh](https://roadmap.sh). Thank you for suggesting though 🙏
