### ISSUE TITLE
Frontend Roadmap - Add iOS / Android

### ISSUE THREAD

**Issue by JulienGenoud** [kamranahmedse/developer-roadmap#15]
I would be nice to add android and iOS to the roadmap.

**Comment by ppihus** [comment]
Web developer ≠ App developer.

Pretty sure that's why iOS/Android are not listed here.

**Comment by JulienGenoud** [comment]
@ppihus i know but mobile development is front end btw.

**Comment by ppihus** [comment]
You're right, it is. And the title of the chart is "_Roadmap to becoming a **web** developer in 2017_"

**Comment by JulienGenoud** [comment]
my bad ! you are true. maybe change the title to be more generic.
