### ISSUE TITLE
Go roadmap is an static image on the website

### ISSUE THREAD

**Issue by narcisonunez** [kamranahmedse/developer-roadmap#1518]
https://roadmap.sh/golang

I would like to know if you are making that roadmap interactive. If you have a guide how to do it, I can do it and submit a PR.

Thanks

**Comment by kamranahmedse** [comment]
Thank you for offering to help @narcisonunez -- I have made it interactive. However, the content isn't there, we'd appreciate it if you could help fill up the [nodes content in this directory](https://github.com/kamranahmedse/developer-roadmap/tree/master/content/roadmaps/108-golang/content) as per the [format listed here](https://github.com/kamranahmedse/developer-roadmap/issues/985).
