### ISSUE TITLE
[devops] New Relic should be added in the Alerting and Monitoring branch

### ISSUE THREAD

**Issue by trivoallan** [kamranahmedse/developer-roadmap#152]
https://newrelic.com/

**Comment by splinterific** [comment]
I've added a PR for this so hopefully its taken up :) https://github.com/kamranahmedse/developer-roadmap/pull/154

**Comment by trivoallan** [comment]
Great :)

Le sam. 29 avr. 2017 à 12:32, Mark Preston <notifications@github.com> a
écrit :

**Comment by kamranahmedse** [comment]
Added
