### ISSUE TITLE
DevOps Roadmap: Replace OpenTracing with OpenTelemetry

### ISSUE THREAD

**Issue by h-s04** [kamranahmedse/developer-roadmap#1527]
Hi There, 
Technical Oversight Committee (TOC) has approved the archiving of the OpenTracing project and following the merger of OpenTracing & OpenCensus into OpenTelemetry. So it's considerable to replace OpenTracing with OpenTelemetry.

Ref: https://www.cncf.io/blog/2022/01/31/cncf-archives-the-opentracing-project/

OpenTelemetry is an open source project that replaces OpenTracing and OpenCensus.
This open standards covers a broader scopes from specifications, APIs, libraries, integrations, e.t.c for different programming languages.

**Comment by kamranahmedse** [comment]
[Done](https://github.com/kamranahmedse/developer-roadmap/commit/8785bf59173ccd0f85783e5ae5fc1cca7f0665d8), thank you for reporting @h-s04 🙏
