### ISSUE TITLE
Can you add DynamoDB to NoSQL databases alternative ?

### ISSUE THREAD

**Issue by diegonalvarez** [kamranahmedse/developer-roadmap#153]
Hi, i'm wondering if it's possible to add DynamoDB to the NoSQL databases.

Or let me know if not apply.

Thanks,
Greetings !

**Comment by thomasklash** [comment]
Agree, add DynamoDB

**Comment by kamranahmedse** [comment]
This has been fixed and will be published in the coming release. Thank you 🙏
