### ISSUE TITLE
Roadmap Creator

### ISSUE THREAD

**Issue by Light2Dark** [kamranahmedse/developer-roadmap#1560]
I love the idea of roadmap.sh but I wonder if there was an idea to create an interactive roadmap maker? To make it possible for individual creators to create their own roadmaps.

Was there thought given to this idea before? Or something similar out there? 
Thank you!

**Comment by kamranahmedse** [comment]
Yes, there was actually [some progress on that as well](https://twitter.com/kamranahmedse/status/1212866266198945792) but I dropped it halfway through because it didn't match the roadmaps style. But yes, there are some options available e.g. [react flow](https://reactflow.dev/) which can be used.

**Comment by Light2Dark** [comment]
Hi, thank you for the answer! I was trying to build a roadmap builder in your website but I'm wondering what's the best direction forward. Do you currently build the roadmap UI structure by manually editing the json?

![image](https://user-images.githubusercontent.com/19585239/186615546-7f336911-d3d0-45e1-97c4-8a3a95681327.png)
