### ISSUE TITLE
Back end Python framework diagram issue

### ISSUE THREAD

**Issue by chuckhousley** [kamranahmedse/developer-roadmap#158]
On the back end diagram, the Python box has a line leading from it to "Frameworks" and then a line to "Sync".  Right below it, there is a line that goes from Python to "Async". Shouldn't the line to "Async" come from "Frameworks"?

**Comment by amirouche** [comment]
Agreed,

It should look like the following

```ascii
                            /---[sync] --> [pyramid, flask, django]
--[framework] --
                           \---[async] --> [aiohttp, etc...]
```

**Comment by amirouche** [comment]
Also, in the async there is a sub family which are based on asyncio like aiohttp is a single example but the most famous IMO.

**Comment by gordol** [comment]
not even that... you can make any synchronous framework asynchronous via monkey patching with eventlet/gevent/etc.

On that note, eventlet is missing from the diagram, too.

**Comment by kamranahmedse** [comment]
Fixed. Thanks
