### ISSUE TITLE
[Suggestion] Add SEO roadmap (Or add it to an existing roadmap)

### ISSUE THREAD

**Issue by DiogoCercilio** [kamranahmedse/developer-roadmap#159]
Add SEO roadmap. Example:
- Semrush,
- Alexa, 
- Google Analytics, Trends, Webmaster tools
- Structured data, 
- AB Testing
more...

**Comment by kamranahmedse** [comment]
There have been changes made to that section which makes this issue outdated. Thank you for reporting though 🙏
