### ISSUE TITLE
[Suggestion] Go Developer

### ISSUE THREAD

**Issue by tehsphinx** [kamranahmedse/developer-roadmap#1590]
First of all: really love those roadmaps! They are awesome!

`logrus`: I know it's still the first choice by people or companies coming to Go but there are faster and better ones now. As is stated on the readme, logrus is in maintainance mode. https://github.com/sirupsen/logrus#logrus----
> There doesn't seem to be a reason to do a major, breaking iteration into Logrus V2, since the fantastic Go community has built those independently. Many fantastic alternatives have sprung up. Logrus would look like those, had it been re-designed with what we know about structured logging in Go today. Check out, for example, [Zerolog](https://github.com/rs/zerolog), [Zap](https://github.com/uber-go/zap), and [Apex](https://github.com/apex/log).

**Comment by kamranahmedse** [comment]
Thanks Gabriel - this has been fixed!
