### ISSUE TITLE
[Suggestion] Roadmaps in general

### ISSUE THREAD

**Issue by toledkrw** [kamranahmedse/developer-roadmap#1612]
Greetings! 
I was wondering if you folks could add a dark theme option in the whole project, not only at the homepage.

It would be much more sight soothing for us with tired eyes 😅

**Comment by kamranahmedse** [comment]
Introducing dark mode will require significant changes to the roadmaps, and it won't be worth the effort at this point. Our focus, right now, is mainly on improving the existing roadmaps and populating the content in these roadmaps. Once we are done with that, maybe we can work on this.
