### ISSUE TITLE
Duplicated "Tutorial with mosh"

### ISSUE THREAD

**Issue by JaviZamudio** [kamranahmedse/developer-roadmap#1620]
Hey! Im reviewing the react native part of the "Front End Roadmap" and i found out, it has a duplicated link

![image](https://user-images.githubusercontent.com/75400668/187038198-727499d4-ed1f-4732-b045-87800195721e.png)

Here, the last two links reference the same video, may be the seccond one could be reused, but with a link like:

https://www.youtube.com/watch?v=1hPgQWbWmEk&t

https://www.youtube.com/watch?v=_ivIUCSOZ78

Thanks!

**Comment by CodeWithUma** [comment]
Hi @JaviZamudio. I have opened one pull request for this issue. Please kindly close this issue.

Thanks!
