### ISSUE TITLE
[Suggestion] Backend Developer

### ISSUE THREAD

**Issue by smakkking** [kamranahmedse/developer-roadmap#1621]
It will be very nice if user was able to export roadmap in check-list

**Comment by kamranahmedse** [comment]
There already is "Mark as Done" functionality (you can either right click on a node or open a topic and "Mark as Done"). Regarding the export, we are working on the accounts functionality which we plan on launching by Q1 2023 -- you will be able to tie your progress to your profile and potentially download it as well. Thank you for the suggestion!
