### ISSUE TITLE
[Suggestion] React Developer

### ISSUE THREAD

**Issue by ilyaSy** [kamranahmedse/developer-roadmap#1636]
It will be very nice to add Redux Thunk and Redux Saga as child of Redux meaning advanced knowledge of asynchronous state management

**Comment by kamranahmedse** [comment]
Thank you for opening the issue. We don't want to convolute the roadmap by mentioning every available option and are just focusing on what is the most relevant item. Redux Thunk and Redux Saga are not an absolute necessity for React apps; anyone who starts working with Redux will probably come across these libraries if needed.

This has also been [mentioned in the contribution docs](https://github.com/kamranahmedse/developer-roadmap/blob/master/CONTRIBUTING.md#guidelines). 
Thank you for your suggestion though 🙏
