### ISSUE TITLE
[Suggestion] Every Roadmap

### ISSUE THREAD

**Issue by antoyne7** [kamranahmedse/developer-roadmap#1639]
Hi, thank you for these amazing ressources!

I suggest to replace http with https in the link. It's a nitpick but for some reason it scares me. What do you think?
![Screenshot 2022-08-31 at 10 39 14](https://user-images.githubusercontent.com/49123231/187635741-106c0713-14ce-458c-93dc-335cd12e6ac5.png)

**Comment by kamranahmedse** [comment]
This has been fixed and will be published in the coming release. Thank you 🙏
