### ISSUE TITLE
Underlying details of roadmap-renderer ？

### ISSUE THREAD

**Issue by genshinw** [kamranahmedse/developer-roadmap#1641]
Hi, I very like the beautiful roadmap, I want to know how to impl such svg clickable roadmap. Do you have any plan to make the roadmap-renderer to public？ Thanks very much.

**Comment by dekadentno** [comment]
Please @kamranahmedse think about making the roadmap renderer public. We'll be able to implement custom and interactive roadmaps for our colleagues. Roadmaps do not have to be strictly related to the world of development and this tool would help everyone who wants to implement something like that.

**Comment by dekadentno** [comment]
@genshinw here's a temporary solution I found: checkout to an commit that is made before the author decided to make the roadmap-renderer private, and simply continue from there.
```
git checkout 83933b9df610a0737779bf6ffd125be6df5347df
```
That commit happened at Aug 28, 2022.

**Comment by genshinw** [comment]
@dekadentno Thank you very much！But after checkout this 83933b9 version, I haven't find the `render` dir in lib. Where did I go wrong?
<img width="1219" alt="image" src="https://user-images.githubusercontent.com/12270447/188316076-42435aa6-31f8-4e63-9892-1dad5c37af8f.png">

**Comment by dekadentno** [comment]
@genshinw I am not entirely sure what happened. If I were you, I would just find the "Add roadmap-renderer package" commit on the master branch from Aug 28, 2022 and go back in time one commit at a time and find the one that works locally. 

https://github.com/kamranahmedse/developer-roadmap/commits/master?after=ed9222c172e3ddf20bd386ca1491f2a5d880e147+69&branch=master&qualified_name=refs%2Fheads%2Fmaster

**Comment by kamranahmedse** [comment]
Thank you for opening the issue. I am in the process of rewriting bits of the project. The roadmap renderer has been taken out from the codebase into a separate package. It needs to be cleaned up and be made feature complete before we make it public. However, you should be able to install the dependencies now.

**Comment by ToastShaman** [comment]
Could the rendering code be open-sourced?
