### ISSUE TITLE
[Suggestion] JavaScript Roadmap 

### ISSUE THREAD

**Issue by harshbisle** [kamranahmedse/developer-roadmap#1642]
Hi, the work you're doing is impressive.

I'm suggesting a few points to add to the module section of the JavaScript roadmap.

1. How to import and export modules 
2. default and named exports

Thank you for instituting roadmap dot sh.

**Comment by kamranahmedse** [comment]
Thank you for opening the issue, Harsh. The "Modules in JavaScript" block should cover that. These details are to be shown on the click of that node.

<img width="592" alt="image" src="https://user-images.githubusercontent.com/4921183/187997873-f9898094-cfae-4027-8bc5-c3ff82b93540.png">
