### ISSUE TITLE
Not able to install modules

### ISSUE THREAD

**Issue by pptyasar** [kamranahmedse/developer-roadmap#1644]
Getting below error when npm i 

`30 error /usr/bin/git ls-remote -h -t ssh://git@github.com/kamranahmedse/roadmap-renderer.git
30 error ERROR: Repository not found.
30 error fatal: Could not read from remote repository.
30 error Please make sure you have the correct access rights
30 error and the repository exists.`

**Comment by leultefera** [comment]
I am having the same issues :(

**Comment by pptyasar** [comment]
@kamranahmedse  can you help on this

**Comment by KKKZOZ** [comment]
I am having the same issues :(

**Comment by AbodyAmer** [comment]
Same issue here

**Comment by 7dir** [comment]
+1

**Comment by rapancristian** [comment]
+1

**Comment by Olayanju-1234** [comment]
> ERROR: Repository not found. 30 error fatal: Could not read from remote repository. 30 error Please make sure you have the correct access rights 30 error and the repository exists.

Check this page and see if it works [https://stackoverflow.com/questions/13509293/git-fatal-could-not-read-from-remote-repository](url)

**Comment by Olayanju-1234** [comment]
> > kamranahmedse/roadmap-renderer
> 
> kamranahmedse/roadmap-renderer does not exist or closed for public users

[If it still doesn't work, just copy the link and paste it in another tab ](https://stackoverflow.com/questions/13509293/git-fatal-could-not-read-from-remote-repository)

**Comment by kamranahmedse** [comment]
This has been fixed. Thank you for reporting!
