### ISSUE TITLE
[Suggestion] Frontend Developer

### ISSUE THREAD

**Issue by leultefera** [kamranahmedse/developer-roadmap#1647]
I am a self taught developer and I have used this tool to guide me learn. I am referring it now for my friends and I wanted to contribute in adding resources as well helping fix issues.

**Comment by kamranahmedse** [comment]
Thanks, @leultefera, for your offer to help. Please go ahead with the content addition. You can [follow the instructions listed in this issue](https://github.com/kamranahmedse/developer-roadmap/issues/985) and start by contributing to the [JavaScript roadmap](https://roadmap.sh/javascript).
