### ISSUE TITLE
About DSA

### ISSUE THREAD

**Issue by AlFahimBinFaruk** [kamranahmedse/developer-roadmap#1667]
Give us a list of Data structure and Algorithms in the DataStructures tab of Java roadmap or separately make a roadmap on it..

**Comment by InquisitiveMe15** [comment]
Hello! @AlFahimBinFaruk I would like to work on this issue. 
It will be helpful if you could elaborate a little more on this issue.
I checked the website, in the DataStructures tab of Java roadmap there was a list of three resources (geeks for geeks, javatpoint and a coursera one).
What precisely you want more?
You can assign this issue to me :)
Thank you!!

**Comment by Rasika020** [comment]
Hello, I want to work on this issue. I will be able to solve this issue more precisely and can give the best solution for this. Thank you.
