### ISSUE TITLE
Frontend: some groups are too bloated

### ISSUE THREAD

**Issue by igoracmelo** [kamranahmedse/developer-roadmap#1668]
I think this section has many groups of stuff.
For example: Storage, Web Sockets, Lighthouse and others could be individual "tasks" instead of one big task.
It makes marking what you've studied easier :)

![image](https://user-images.githubusercontent.com/85039990/188191541-c4d088fa-ce21-42bd-9222-582695a42928.png)

**Comment by kamranahmedse** [comment]
This has been fixed. Thank you!
