### ISSUE TITLE
Add Babel to front end

### ISSUE THREAD

**Issue by NonameSLdev** [kamranahmedse/developer-roadmap#167]
Babel, "_the_ compiler for writing next-gen JS", isn't there! It's an important tool that you need to know. It should be under the "Going deeper > Javascript > ES6" section.

**Comment by luchillo17** [comment]
Babel is a transpiler, it should be just under Typescript as an option.

**Comment by kamranahmedse** [comment]
This has been fixed and will be published in the coming release. Thank you 🙏
