### ISSUE TITLE
Translation into

### ISSUE THREAD

**Issue by janekerry123** [kamranahmedse/developer-roadmap#1696]

**Comment by janekerry123** [comment]
Hi Karman,
Can you authorise me in translating this project in Chinese as I want my friends living in China unsderstand how he or she can be a programmer with little English skill. 

Thanks,
Rosalind

**Comment by kamranahmedse** [comment]
We do have the [chinese translation available here](https://github.com/kamranahmedse/developer-roadmap/tree/0471d44c8fae58b6a36a7c57bba12253916d0249/translations). Feel free to share it with them but please note that the redistribution is not allowed. However, we do plan on implementing the localization soon, so stay tuned.

**Comment by rein0217a** [comment]
Hi Karman,
Do you plan to add videos translation.

I want Japanese translation.

**Comment by rein0217a** [comment]
↑ @kamranahmedse
