### ISSUE TITLE
Elasticsearch

### ISSUE THREAD

**Issue by Vutsuak16** [kamranahmedse/developer-roadmap#171]
Should not elasticsearch be added to NoSQL databases..?
and also what about the other ELK stack tools like Kibana and Logstash.. they might feature in a web developer profile..?

**Comment by Cobrijani** [comment]
My personal opinion is that Elk stack is more for Devops profile, since you only should configure system to work. However, developing custom plugins for Elk stack I would consider as developer part. What do you think?

**Comment by Vutsuak16** [comment]
Well if we go into that I would say developing plugins for each tool in ELK stack require specific set of skills,for instance 

1.kibana plugin requires angular and require js. ( a tutorial is still not available)
2. logtstash plugin development requires "ruby"
3. elasticsearch does not have any confident/active plugin development.

since all this is pretty widespread and is in nascent stage.. I would not recommend "ELK plugin " development for this particular roadmap. Whose sole purpose is to be precise and concise.

I would stress upon the fact that elasticsearch can easily be included in the database section :)

**Comment by kamranahmedse** [comment]
I agree with you on that - yes it could be used as a NoSQL database but for the NoSQL usage the options mentioned are the ones that are used quite often than Elasticsearch and thus it has been put into its own section under Search Engines.
