### ISSUE TITLE
[Suggestion] Android Developer - Jetpack Compose

### ISSUE THREAD

**Issue by DevCapu** [kamranahmedse/developer-roadmap#1717]
Maybe we should have Jetpack Compose as a must, Thoughtworks's [Tech Radar 25](https://www.thoughtworks.com/radar/languages-and-frameworks/jetpack-compose) (2021 October) added Jetpack Compose as technology that should be adopted on new projects

**Comment by kamranahmedse** [comment]
This has been fixed, thank you!
