### ISSUE TITLE
Remove "Start Building" icon from the bottom

### ISSUE THREAD

**Issue by mikeshhoffman** [kamranahmedse/developer-roadmap#174]
Remove the "Start Building" icon.
It is not the case that you learn these technologies and then start building.  In reality, you start building and then research and learn these technologies more as you go along.

**Comment by luchillo17** [comment]
I think it's not about the reality, it's about the ideal path to learn this techonogies, in that regard i think instead of removing, it should be moved to the top, you start building from start, and learn by building.

**Comment by mikeshhoffman** [comment]
I thought of that option (moving "Start Building" to the top) but didn't mention it.  That would solve the following problem: having "Start Building" at the end is discouraging (as well as misrepresenting the sequence).  It would be good to use this opportunity to encourage getting started and prepare people for the real sequence.

An argument in favor of removing the "Start Building" icon is that the diagram should not serve two different purposes: sequence and technologies; the diagram should only cover technologies, not sequence.  It's not a temporal flow diagram.

**Comment by luchillo17** [comment]
Indeed as a roadmap it should cover which technologies are basic, and which ones are recommended in a structured way, if it were a timeline, it wouldn't be a roadmap, but a curriculum.

I agree on removing that node.

**Comment by morajabi** [comment]
Yes it's a source of misunderstand too. When I posted this in a group chat, It was a question which should we start reading this from top to bottom or vice-versa? All was that icon's fault :)

**Comment by kamranahmedse** [comment]
My bad; modified a little to represent that. Thanks for pointing out.
