### ISSUE TITLE
DevOps chart needs VCS choices and branching-model choices

### ISSUE THREAD

**Issue by paul-hammant** [kamranahmedse/developer-roadmap#176]

**Comment by hseritt** [comment]
By VCS, do you mean Version Control Systems? If so, would you elaborate on this? Do you mean a side by side of say Git, TFS, SVN, Mercurial, etc?

**Comment by paul-hammant** [comment]
Yes, Version Control Systems. Only a quick listing of them. Go deeper into branching models.

**Comment by luchillo17** [comment]
Does it actually needs such branching by tool? i think the most widespread are Git and Mercurial.

As branching model i can only think of GitFlow (or is it just a methodology for development?), it should be there, but making a new branch for such is overkill unless there is other ones widely used (i mean putting here a model that only you + 2-3 people use).

**Comment by paul-hammant** [comment]
You're purporting to make something that's useful for others within the DevOps community. Writing an opinion on GitFlow (and its controversies), GitHubFlow, and trunkbaseddevelopment.com/short-lived-feature-branches/ is a **must have** IMO.

**Comment by luchillo17** [comment]
@paul-hammant Sorry, i meant Flow, i knew Flow as GitFlow but it's name is Flow, i don't even use the GitFlow CLI.
