### ISSUE TITLE
Add pnpm as package manager

### ISSUE THREAD

**Issue by kutsan** [kamranahmedse/developer-roadmap#177]
[pnpm](https://github.com/pnpm/pnpm) is also a decent package manager over npm. You should consider adding it.

**Comment by luchillo17** [comment]
Interesting, never heard of it, but it seems very powerful, main advantage would be memory saving, then speed.

However lib creators cannot use this tool, that's a big caveat, also memory is cheaper now days.

**Comment by kutsan** [comment]
Hey @kamranahmedse. Any reason why it's closed?

**Comment by kamranahmedse** [comment]
Sorry, my comment wasn't posted.

Thank you for reporting but we are not including every other alternative that exists out there. The roadmaps mention the _technologies_ that are most in the demand. As far as pnpm is considered, although it looks good, most of the people have never even heard of it. So to avoid the clutter and to make these roadmaps look less spooky I will have to close it without adding pnpm. 

Hope you understand.
