### ISSUE TITLE
[Suggestion] Add reference to UI/UX roadmap

### ISSUE THREAD

**Issue by togiberlin** [kamranahmedse/developer-roadmap#178]
Hey @kamranahmedse,

I made a UI/UX roadmap. A lot of people have asked for it:
https://github.com/togiberlin/ui-ux-designer-roadmap

If you like it, maybe you could reference it in your developer roadmap readme file 😄 

Thanks again for the awesome developer roadmap! Keep it going akhi

Best,
Togi

**Comment by zikelir** [comment]
Man, I just loved your roadmap!

**Comment by brunotdantas** [comment]
@kamranahmedse That would be perfect!

**Comment by msonowal** [comment]
@togiberlin 
This is just awesome must needed

**Comment by kamranahmedse** [comment]
Thank you for mentioning that. Good work on the roadmap. While I can't add it to this repository, I will see how we can incorporate it in [roadmap.sh](https://github.com/kamranahmedse/roadmap.sh). Thank you!
