### ISSUE TITLE
experience share for roadmap development

### ISSUE THREAD

**Issue by phodal** [kamranahmedse/developer-roadmap#18]
Hi,

I have do the similar work in two years ago in Chinese. And, I came here to share some suggestions.

At the beginning, I build a roadmap like this with Graphviz in [https://github.com/phodal/developer](https://github.com/phodal/developer)

![Dot Tree](https://raw.githubusercontent.com/phodal/developer/master/images/tree.gif)

Then, newbie always like to ask books for read. So, I build a book tree to do something. [https://github.com/phodal/booktree](https://github.com/phodal/booktree)

But it's still hard to help they.

So, I build a skill tree like [https://github.com/352Media/skilltree](https://github.com/352Media/skilltree) with D3.js which is [https://github.com/phodal/sherlock](https://github.com/phodal/sherlock)， demo in here [http://sherlock.phodal.com/](http://sherlock.phodal.com/).

when people hover the skill on roadmap in skill tree, it will show the related resources, books, articles, like this:

![Sherlock D3.js](https://github.com/phodal/sherlock/raw/gh-pages/sherlock.jpg)

Finally, the more and more resources add to those projects, like:
 
 - frontend & backend roadmap: [https://github.com/phodal/awesome-growth](https://github.com/phodal/awesome-growth).  
 - daily toolbox : [https://github.com/phodal/toolbox](https://github.com/phodal/toolbox)
 - practise project for newbie: [https://github.com/phodal/awesome-practise-project](https://github.com/phodal/awesome-practise-project)

So I build a app to do this [https://github.com/phodal/growth](https://github.com/phodal/growth), which you can the demo in  [http://web.growth.ren/](http://web.growth.ren/).

---

It look like a lot of ads 😆 😆 , don't block me.

**Comment by kamranahmedse** [comment]
Hi @phodal, thanks for sharing. I will definitely steal some stuff ;)
