### ISSUE TITLE
Add "Visual Programming" Path to Frontend

### ISSUE THREAD

**Issue by cmalven** [kamranahmedse/developer-roadmap#180]
A large, important sub-path is entirely missing from the current frontend roadmap. I would call this a "sub-path" because it is entirely possible to be a successful, competent frontend developer without it, but for many frontend developers this path represents a serious chunk of their workload, and represents a very in-demand option for frontend development – especially for developers who are have a visual aptitude.

*Rough outline of a "Visual Programming" path*

- Visual Programming
  * Animation
    + GSAP (recommendation)
    + MoJs
    + Bodymovin
  * WebGL
    + Shaders (recommendation)
  * 2D
    + `<canvas>` (recommendation)
    + Pixi.js (recommendation)
  * 3D
    + Three.js (recommendation)

These are the tools I've found most important in my growth as a visual programmer, but I'm probably leaving something out. What am I missing?

**Comment by Osilos** [comment]
I think you can add the following :

2D : Phaser.js
3D : BabylonJS. I don't recommand it, but it exist.

**Comment by kamranahmedse** [comment]
Thank you for your suggestion but I don't think there is a need for that in "Web developer roamap"
