### ISSUE TITLE
[Suggestion] Backend Developer

### ISSUE THREAD

**Issue by bhatnagardivyanshu** [kamranahmedse/developer-roadmap#1803]
Can we also add some sense of time each of these items will take or usually take? I know this is very subjective but it will give an important perspective to anyone who wants to prioritise things

**Comment by kamranahmedse** [comment]
Thanks for the suggestion @bhatnagardivyanshu; you said it yourself, it's subjective :) 

We don't have any plans for adding that, everyone is different and learns differently. Having time-bound nodes is going to open up yet another pandora's box.
