### ISSUE TITLE
[Not a suggestion but a question that I can not see Selenium as QA tool. It is one of the most popular testing framework] QA Engineer

### ISSUE THREAD

**Issue by gyaninnovations5** [kamranahmedse/developer-roadmap#1813]
Hi,
First of all thanks for the greate content you provide as roadmap. I was waiting for QA roadmoap for so long.
I can not see selenium there. Just curious about why it is not there.
Thanks

**Comment by kamranahmedse** [comment]
Perhaps an oversight, thank you, this has been fixed. Should be deployed soon.

<img width="313" alt="image" src="https://user-images.githubusercontent.com/4921183/191496024-9ac68af1-4e9e-4464-8aa5-f52bf091c735.png">
