### ISSUE TITLE
[Suggestion] in node js roadmap 

### ISSUE THREAD

**Issue by anassarfraz** [kamranahmedse/developer-roadmap#1824]
Include how to nodejs works topic in **introduction to node js** for understand the flow how nodejs work, if its needs.

https://www.youtube.com/watch?v=jOupHNvDIq8
![image](https://user-images.githubusercontent.com/22854438/191440893-c1a364b2-4786-4259-8e90-d9e94645824a.png)

**Comment by kamranahmedse** [comment]
This would better be a resource under "What is Node.js", instead.

**Comment by anassarfraz** [comment]
Well, it would better
thanks @kamranahmedse
