### ISSUE TITLE
Add content to Go Roadmap

### ISSUE THREAD

**Issue by kamranahmedse** [kamranahmedse/developer-roadmap#1836]
[Go Roadmap](https://roadmap.sh/golang) has been made interactive, but it is missing content in som of the roadmap nodes. We need to fill the [markdown files given here](https://github.com/kamranahmedse/developer-roadmap/tree/master/content/roadmaps/109-golang/content) with a short intro to the topic mentioned in the markdown file and add some resources as [per the guidelines here](https://github.com/kamranahmedse/developer-roadmap/blob/master/contributing.md#adding-content).

**Note** — You don't have to fill all the markdown files simultaneously. Feel free to create separate pull requests with batches of changes (e.g. fill up 15 content files in each PR).

**Comment by nabeel001** [comment]
Hi, I would like to work on this issue during this hacktoberfest, I kindly request you to assign me this issue. Thanks!

**Comment by rajbhoyar729** [comment]
hi @kamranahmedse  i  don't know  much  about   creating  roadmaps  but  i  can try  if  you  guide  me  a  little  bit  bro

**Comment by GabrielMoody** [comment]
Hi @kamranahmedse, I would like to help you with this issue. Can you assign me to this issue?. Thanks!

**Comment by tanvi1110** [comment]
Hello, would like to contribute.

**Comment by nairpranav331** [comment]
Hello! I would like to contribute to it! Thanks.

**Comment by KnightlLORD** [comment]
Hi @kamranahmedse I would like to work on this issue, please assign this issue to me.

**Comment by ozansz** [comment]
Hi @kamranahmedse, I would like to contribute to this issue

**Comment by Zaid-Parkar** [comment]
Hello Sir,
I would like to contribute to this project,
I am new to hacktoctoberfest and this would be a great beginning.
Thank you...

**Comment by dhruvasagar** [comment]
Created PR https://github.com/kamranahmedse/developer-roadmap/pull/2607 for details on go-zero

**Comment by shubhig226** [comment]
@kamranahmedse
I would like to contribute to this issue, can you assign it to me?
