### ISSUE TITLE
Add content to Java roadmap

### ISSUE THREAD

**Issue by kamranahmedse** [kamranahmedse/developer-roadmap#1837]
[Java Roadmap](https://roadmap.sh/java) has been made interactive, but it is missing content in some of the roadmap nodes. We need to fill the [markdown files given here](https://github.com/kamranahmedse/developer-roadmap/tree/master/content/roadmaps/110-java/content) with a short intro to the topic mentioned in the markdown file and add some resources as [per the guidelines here](https://github.com/kamranahmedse/developer-roadmap/blob/master/contributing.md#adding-content).

**Note** — You don't have to fill all the markdown files simultaneously. Feel free to create separate pull requests with batches of changes (e.g. fill up 15 content files in each PR).

**Comment by haseeb-xd** [comment]
I want to work on these nodes which are missing content and resources.

**Comment by SarveshN23** [comment]
Hello @kamranahmedse, I would like to work on this. Can I be assigned to this?

**Comment by umadhatri** [comment]
Hello @kamranahmedse! I would also like to be of help. Can I also work on this issue? Do let me know. Thank you in advance and cheers!

**Comment by joelsathi** [comment]
Hi @kamranahmedse, I also would like to contribute. Can you please assign me to this project?

**Comment by AAnakhe** [comment]
Hello  @kamranahmedse, I  would like to work on this issue, thanks.

**Comment by ojasaklechayt** [comment]
Hello!! I would like to contribute to this issue.

**Comment by haseeb-xd** [comment]
I have made my PRs , but why aren't they merging

**Comment by tanvi1110** [comment]
Hola, would love to contribute.

**Comment by Dauka03** [comment]
Hello!! I would like to contribute to this issue.

**Comment by sudarsan2k5** [comment]
Hi, I would like to contribute to this issue.

**Comment by rishi-kai21** [comment]
Hey, @kamranahmedse  if this issue needs further changes  I would love to work on it . Please assign me this issue if it needs improvements

**Comment by Satakshijain** [comment]
Hello @kamranahmedse I would like to contribute to this

**Comment by kamranahmedse** [comment]
Hey guys, no need to comment here. Just go and find out the empty nodes in roadmap and submit the pull requests.

**Comment by astitva0011** [comment]
!assign

**Comment by rishi-kai21** [comment]
@kamranahmedse please review my pr whenever you get some time off and let me know of things I can add upon .

**Comment by to-program-khushi-jain** [comment]
Can I contribute to this issue?@kamranahmedse

**Comment by Zaid-Parkar** [comment]
Hello Sir,
I would like to contribute to this project,
I am new to hacktoctoberfest and this would be a great beginning.
Thank you...

**Comment by Rasika020** [comment]
Hello, I want to contribute on this issue. I have experience of using java for 3 years now hence I want to contribute here, Thank you.

**Comment by SuchhandaDas** [comment]
@kamranahmedse 
I would like to contribute to this issue, can you assign it to me?

**Comment by shubhig226** [comment]
@kamranahmedse
I would like to contribute to this issue, can you assign it to me?

**Comment by Ironspider42** [comment]
Hey @kamranahmedse, I would like to contribute to this issue, can you assign it to me ?
