### ISSUE TITLE
Add content to JavaScript roadmap

### ISSUE THREAD

**Issue by kamranahmedse** [kamranahmedse/developer-roadmap#1838]
[JavaScript Roadmap](https://roadmap.sh/javascript) has been made interactive, but it is missing content in some of the roadmap nodes. We need to fill the [markdown files given here](https://github.com/kamranahmedse/developer-roadmap/tree/master/content/roadmaps/106-javascript/content) with a short intro to the topic mentioned in the markdown file and add some resources as [per the guidelines here](https://github.com/kamranahmedse/developer-roadmap/blob/master/contributing.md#adding-content).

**Note** — You don't have to fill all the markdown files simultaneously. Feel free to create separate pull requests with batches of changes (e.g. fill up 15 content files in each PR).

**Comment by Nisarg-Chokshi** [comment]
Hello @kamranahmedse, Can I work on this ?

**Comment by ZahraShahid** [comment]
Shall I work on this?

**Comment by johnwinifred** [comment]
Hello, please I would love to work on this

**Comment by CodeWAdi** [comment]
Hey as I am one the user  of your JAVASCRIPT roadmap.sh I would love to contribute in this issue.

**Comment by hitaarthh** [comment]
@kamranahmedse Hey, I'm a JavaScript Developer, Can i Work on this?

**Comment by Rohan27s** [comment]
I want to work on this issue

**Comment by ojasaklechayt** [comment]
Hello!! I would like to work on the project. I have checked out the roadmap and got the chance where I can contribute. So, please assign me.

**Comment by Ryrden** [comment]
Hello There, I want to work on this issue

**Comment by Prashant-17-11** [comment]
Hello @kamranahmedse, I would like to work on this

**Comment by Rishabh044** [comment]
Hello @kamranahmedse, Allow me to contribute on this

**Comment by Arka90** [comment]
Can you please assign it to me

**Comment by yashdev9274** [comment]
> Can you please assign it to me

just make the changes and send the PRs, @kamranahmedse will check whether it should get merged or not

**Comment by puru-khedre** [comment]
#2132

**Comment by sumitbaroniya** [comment]
Please assign me this issue.

**Comment by ishratUmar18** [comment]
Can I work on this one?

**Comment by sudarsan2k5** [comment]
Hello, would like to contribute.

**Comment by KnightlLORD** [comment]
Hello @kamranahmedse , I would like to work on this.

**Comment by c1phani1simha** [comment]
Hello @kamranahmedse, I made a pull request #2299 please check it out!

**Comment by pavilandoangelo** [comment]
Hi @kamranahmedse , could I work on this one? Planning to contribute. Thanks a lot!

**Comment by pranavhole** [comment]
Hey I will love to help you on this

**Comment by shokushwaha** [comment]
Hello  sir, I would love to work on this project. Planning to contribute . I have an awesome idea regarding this.

**Comment by Anika-Roy** [comment]
Hi! Im participating in Hacktoberfest and I'd like to know if this issue is counted in Hacktoberfest and if I can work on it?

**Comment by shokushwaha** [comment]
I want to work in this project.

**Comment by Naveen-Karanamu** [comment]
Hello sir, may you please assign this token to me. I would love to contribute in this. Thank you.

**Comment by johnwinifred** [comment]
Please can I also work on this

**Comment by JP-GECT** [comment]
Hello Sir,
I would like to contribute towards this project,
I am new to hacktoctoberfest and this would be a great beginning.
Thank you...

**Comment by SaurabhBudhwani26** [comment]
Hello Sir,
I would love to work on this, can you assign this to me?

**Comment by sameer1612** [comment]
@kamranahmedse Added content for fetch and XMLHttpRequest in javascript track. Please, merge it.

https://github.com/kamranahmedse/developer-roadmap/pull/2503

**Comment by Zaid-Parkar** [comment]
Hello Sir,
I would like to contribute towards this project,
I am new to hacktoctoberfest and this would be a great beginning.
Thank you...

**Comment by Zaid-Parkar** [comment]
Hello Sir,
I would like to contribute to this project,
I am new to hacktoctoberfest and this would be a great beginning.
Thank you...

**Comment by shubhig226** [comment]
@kamranahmedse
I would like to contribute to this issue, can you assign it to me?

**Comment by bytesofbec** [comment]
Hi can I work on this?

**Comment by bytesofbec** [comment]
@kamranahmedse Hi can I work on this?

**Comment by bytesofbec** [comment]
#2798

**Comment by bytesofbec** [comment]
Javascript resource update. #2798
