### ISSUE TITLE
Add content to QA roadmap

### ISSUE THREAD

**Issue by kamranahmedse** [kamranahmedse/developer-roadmap#1840]
[QA Roadmap](https://roadmap.sh/qa) has been made interactive, but it is missing content in some of the roadmap nodes. We need to fill the [markdown files given here](https://github.com/kamranahmedse/developer-roadmap/tree/master/content/roadmaps/113-qa/content) with a short intro to the topic mentioned in the markdown file and add some resources as [per the guidelines here](https://github.com/kamranahmedse/developer-roadmap/blob/master/contributing.md#adding-content).

**Note** — You don't have to fill all the markdown files simultaneously. Feel free to create separate pull requests with batches of changes (e.g. fill up 15 content files in each PR).

**Comment by KomalMMungekar** [comment]
created #1997 let me know if this looks alright.

**Comment by ethandpark** [comment]
Created [2041](https://github.com/kamranahmedse/developer-roadmap/pull/2041), let me know if it looks alright/needs any changes!

**Comment by ChuckD3ath** [comment]
Already working on this for a week now! :)

**Comment by FercueNat** [comment]
Hello! I just added information to the QA Sdlc node :) Will wait for review on the PR :)

**Comment by ChuckD3ath** [comment]
@FercueNat I already have that one open :/ #1940

**Comment by FercueNat** [comment]
> @FercueNat I already have that one open :/ #1940

Oh man, just checked it and you indeed have a PR open, my bad :( Maybe once yours is merged I can add my own changes as well, as I saw that I left a bit more of info. Thanks for the heads up!

**Comment by PanSem** [comment]
Add management and monitoring node #2212

**Comment by c1phani1simha** [comment]
Hello @kamranahmedse, I added the content to the readme.md file, please check this PR #2339

**Comment by c1phani1simha** [comment]
@kamranahmedse, added content to the readme.md file. Please check this PR #2343

**Comment by ChuckD3ath** [comment]
@c1phani1simha excuse me but you don't need to comment here with your PRs. He will get to it whenever he gets some time as there are over 90 Pull Requests open at the moment.

**Comment by yrhemendra** [comment]
Sir Can i contribute to resolve this issue?

**Comment by Zaid-Parkar** [comment]
Hello Sir,
I would like to contribute to this project,
I am new to hacktoctoberfest and this would be a great beginning.
Thank you...

**Comment by ChuckD3ath** [comment]
@kamranahmedse looks like that with #2902 all QA Roadmap fields have been filled out and this issue could be closed out.

**Comment by kamranahmedse** [comment]
Thank you @ChuckD3ath and everyone for all your contributions! ❤️
