### ISSUE TITLE
[Suggestion] Backend Developer

### ISSUE THREAD

**Issue by ErikWillekens** [kamranahmedse/developer-roadmap#1843]
Hello, I would like to add items (youtube links and edit text) - would be nice if there is a tutorial on how to do that. 

I wanted to add a link yet didn't find how to do it and then gave up. I believe beginning programmers like me might give up if it hasn't got clear instructions yet they find good resources because they are constantly self researching

I wanted to add this link to dns:
https://www.youtube.com/watch?v=2ZUxoi7YNgs

and this one
https://www.youtube.com/watch?v=iYM2zFP3Zn0

**Comment by kamranahmedse** [comment]
Hey @ErikWillekens, the [details are listed here](https://github.com/kamranahmedse/developer-roadmap/blob/master/contributing.md#adding-content)
