### ISSUE TITLE
[Suggestion] Go Developer

### ISSUE THREAD

**Issue by BElluu** [kamranahmedse/developer-roadmap#1846]
Hi,
In slices this link leads to arrays
![image](https://user-images.githubusercontent.com/11333925/191750024-e02b5a3e-4ac8-48cd-b1ea-1db4b03672f0.png)

Please change it to https://go.dev/tour/moretypes/7

**Comment by kamranahmedse** [comment]
Fixed in https://github.com/kamranahmedse/developer-roadmap/commit/ecf64a2e366bc8898faaf184f4b726b2d6897974 - thanks!
