### ISSUE TITLE
Add content to Angular Roadmap

### ISSUE THREAD

**Issue by kamranahmedse** [kamranahmedse/developer-roadmap#1847]
[Angular Roadmap](https://roadmap.sh/angular) has been made interactive, but it is missing content in some of the roadmap nodes. We need to fill the [markdown files given here](https://github.com/kamranahmedse/developer-roadmap/tree/master/content/roadmaps/104-angular/content) with a short introduction to the topic mentioned in the markdown file and add some resources as [per the guidelines here](https://github.com/kamranahmedse/developer-roadmap/blob/master/contributing.md#adding-content).

**Note** — You don't have to fill all the markdown files simultaneously. Feel free to create separate pull requests with batches of changes (e.g. fill up 10 content files in each PR).

**Comment by krupalitrivedi** [comment]
Hello! I would love to work on this during the hacktoberfest and before that too!

**Comment by hitaarthh** [comment]
Hello can i work on it?

**Comment by hitaarthh** [comment]
@kamranahmedse how can i change the colour using ```BadgeLink``` as per the guidelines, i'm unable to get the colour using badgeLink, can i use any other methods to attach the link?

**Comment by hitaarthh** [comment]
Updated the 100-what-is-typescript.md #1938

**Comment by manishtambe** [comment]
If this issue is still open can I contribute  ?

**Comment by GetIbetsamAhmed** [comment]
https://github.com/kamranahmedse/developer-roadmap/pull/2087

**Comment by GetIbetsamAhmed** [comment]
Added Angular state management and life cycle content to angular roadmap https://github.com/kamranahmedse/developer-roadmap/pull/2102

**Comment by GetIbetsamAhmed** [comment]
Added Angular state management and life cycle content to angular roadmap -  https://github.com/kamranahmedse/developer-roadmap/pull/2102

**Comment by GetIbetsamAhmed** [comment]
Add content to Dependency Injection in angular roadmap - https://github.com/kamranahmedse/developer-roadmap/pull/2107

**Comment by Man07har** [comment]
Please Assign it to me would love to contribute.

**Comment by GetIbetsamAhmed** [comment]
Add content to Angular CLI in angular roadmap  - https://github.com/kamranahmedse/developer-roadmap/pull/2131

**Comment by GetIbetsamAhmed** [comment]
**Add content to render block in angular roadmap**  - https://github.com/kamranahmedse/developer-roadmap/pull/2168

**Comment by ishratUmar18** [comment]
I would love to contribute.

**Comment by sudarsan2k5** [comment]
Hello!! I would like to contribute to this issue.

**Comment by deevanshu-k** [comment]
Hello I would like to contribute, Is their any issue for me

**Comment by c1phani1simha** [comment]
Hello @kamranahmedse, I made a pull request #2300 please check it out!

**Comment by c1phani1simha** [comment]
Please check this pull request also #2301

**Comment by c1phani1simha** [comment]
Hello @kamranahmedse, I made the addition of content to readme.md file, please check this #2320 pull request!

**Comment by c1phani1simha** [comment]
I added the content to readme.md file, please check this pull request #2321

**Comment by c1phani1simha** [comment]
@kamranahmedse , I added the content to the readme.md file of 114-angular ssg, please check this pull request #2323

**Comment by shivam1646** [comment]
Hi  @kamranahmedse I have added content for Angular template nodes and resolved conflicts too. Please check  PR #2281

**Comment by c1phani1simha** [comment]
@kamranahmedse, I added the content to the readme.md file of 115-angular-testing folder, Please look into this PR #2345

**Comment by CodeWithUma** [comment]
Hi @kamranahmedse. There are some contents left in this roadmap. I have raised a PR https://github.com/kamranahmedse/developer-roadmap/pull/2428 . Please kindly review it and merge it by labeling it as "HACTOBERFEST-ACCEPTED".
