### ISSUE TITLE
[Suggestion] Python Developer

### ISSUE THREAD

**Issue by Iguinho94CP** [kamranahmedse/developer-roadmap#1851]
Hello, would it be possible to add a feature to keep the nodes marked as done saved? Because if I leave the roadmap website, or clear the browser's history,  it does not keep the nodes I had previously marked as done saved. So I would appreciate if you guys could somehow make a change to keep those nodes marked as done saved, so we can keep track of our study. 

Another thing, would be possible to create a specific roadmap about Flask and Django? If I am not asking too much 😅

**Comment by kamranahmedse** [comment]
We will be adding user accounts to the website soon. Progress will be saved and shareable in the public profile. Stay tuned!

Regarding Flask and Django, sure would you be able to [draft a textual roadmap](https://gist.github.com/kamranahmedse/98758d2c73799b3a6ce17385e4c548a5) and share it with us to start with?
