### ISSUE TITLE
[Suggestion] Frontend Developer

### ISSUE THREAD

**Issue by 45m0d3u5** [kamranahmedse/developer-roadmap#1862]
Hi! 
I want to suggest effector as state manager. It is much more better than all state managers have written on roadmap

https://effector.dev/

community: 
telegram: https://t.me/effector_ru
dev to: https://dev.to/effector
github: https://github.com/effector

**Comment by kamranahmedse** [comment]
Thank you for opening the issue. We don't want to convolute the roadmap by mentioning every available option and are just focusing on what is the most relevant item that you would pick today, and the mentioned item doesn't conform to that. 

This has also been [mentioned in the contribution docs](https://github.com/kamranahmedse/developer-roadmap/blob/master/contributing.md#guidelines). 
Thank you for your suggestion though 🙏
