### ISSUE TITLE
[Suggestion] Frontend Developer

### ISSUE THREAD

**Issue by chkchun** [kamranahmedse/developer-roadmap#1876]
Hi, is it possible to add suggestion on different technology platform or ecosystem? If someone is .NET developer, he/she might interested to know what are the knowledge the frontend developer for .NET. Thanks.

Examples:
Microsoft .NET
Java
Python

**Comment by kamranahmedse** [comment]
@chkchun no plans for that at the moment. However, we have a separate .NET roadmap planned where you will be able to add those.

**Comment by chkchun** [comment]
@kamranahmedse 
Looking forward for .NET roadmap, thank you.
