### ISSUE TITLE
Add content to Software Architect Roadmap

### ISSUE THREAD

**Issue by kamranahmedse** [kamranahmedse/developer-roadmap#1879]
[Software Architect Roadmap](https://roadmap.sh/software-architect) has been made interactive, but it is missing content in some roadmap nodes. We need to fill the [markdown files given here](https://github.com/kamranahmedse/developer-roadmap/tree/master/content/roadmaps/114-software-architect/content) with a short introduction to the topic mentioned in the markdown file and add some resources as [per the guidelines here](https://github.com/kamranahmedse/developer-roadmap/blob/master/contributing.md#adding-content).

**Note** — You don't have to fill all the markdown files simultaneously. Feel free to create separate pull requests with batches of changes (e.g. fill up 10 content files in each PR).

**Comment by samyukthasudhakar** [comment]
Hi @kamranahmedse ! I'd like to take up this task, can you please assign it to me. Thanks !

**Comment by kamranahmedse** [comment]
Thanks for offering to help @samyukthasudhakar -- there are hundreds of nodes, so multiple contributors can contribute to this task by adding content to the nodes. Feel free to open pull requests with batches of 10 or 15 nodes with contents in each PR.

**Comment by samyukthasudhakar** [comment]
Sure @kamranahmedse . Will proceed as suggested 👍🏽

**Comment by KodeyThomas** [comment]
Haven't contributed in a while! Will be making a PR 👍🏻

**Comment by hitaarthh** [comment]
Looking forward to work on it.

**Comment by Man07har** [comment]
Would like to work on this assign it to me

**Comment by ojasaklechayt** [comment]
Hello!! I would like to work on this issue.

**Comment by KodeyThomas** [comment]
> Thanks for offering to help @samyukthasudhakar -- there are hundreds of nodes, so multiple contributors can contribute to this task by adding content to the nodes. Feel free to open pull requests with batches of 10 or 15 nodes with contents in each PR.

@ anyone who is commenting on this :) 

Just open up PRs and they will be reviewed in due course (p.s happy hacktoberfest)

**Comment by gitaroktato** [comment]
Hey @kamranahmedse opened a PR for this one in #2154

**Comment by jeffercbs** [comment]
Hello, I am new to open source. I just made a pull request #2186. I hope I have made a good contribution.

**Comment by shivam1646** [comment]
Hi @kamranahmedse I have added content for web and mobile nodes. Please check PR #2326

**Comment by Anika-Roy** [comment]
Hi! Im participating in Hacktoberfest and I'd like to know if this issue is counted in Hacktoberfest and if I can work on it?

**Comment by sameer1612** [comment]
I am contributing to this repository for the first time. @kamranahmedse are nurturing a good knowledge base. Kudos!

I have added an explanation for the CICD section. https://github.com/kamranahmedse/developer-roadmap/pull/2408

I'll add more content in s/w architecture during weekends. Will be happy to pick NextJS related issues in website if any. 🤝
