### ISSUE TITLE
Text editors & CLI tools for DevOps

### ISSUE THREAD

**Issue by ppihus** [kamranahmedse/developer-roadmap#19]
Unless they are taken for granted under "Linux/Unix", I think DevOps should also include CLI based text editors and different CLI tools such as `grep`, `awk`, `sed` and so on.

PS.
Is (basic) networking and firewalls something that's considered not a DevOps task?

**Comment by kamranahmedse** [comment]
Yeah you are right, actually I focused on the higher level stuff. Plus, it still needs to be reviewed and modified.

**Comment by kamranahmedse** [comment]
Done
