### ISSUE TITLE
[Suggestion] Frontend Developer

### ISSUE THREAD

**Issue by Giorgiosaud** [kamranahmedse/developer-roadmap#1909]
maybe add some kind of sso knoledge, even some like openid and oauth flows

**Comment by khairnarsaurabh23** [comment]
Can I work on this issue?

**Comment by Sonali314** [comment]
hey i would like to work on this issue kindly assign me this work and let me know what i need to do

**Comment by shokushwaha** [comment]
Hello sir , I would like to work on this project please assign me this work and let me know anything special you want on this project.

**Comment by Prachi257** [comment]
Hey! anything can I do for this project?

**Comment by kamranahmedse** [comment]
This has been fixed and will be published in the coming release. Thank you 🙏
