### ISSUE TITLE
[Suggestion] Backend Developer

### ISSUE THREAD

**Issue by yashdev9274** [kamranahmedse/developer-roadmap#1947]
I would like to add Containerization section in Backend roadmap along side with Cloud Providers section.
If you can tell me how can I add new section then  I would love to work on it.

**Comment by codegustavo42** [comment]
Studying about Internet, the box about hosting doesn't have links to articles, so I did a search and found an article by Hostinger which by the way is an excellent article about Web Hosting.
Here's my suggestion to add with article.
https://www.hostinger.com/tutorials/what-is-web-hosting/''

**Comment by being-nitin** [comment]
could you assign m e this task?

**Comment by kamranahmedse** [comment]
We already have that in the Backend Roadmap

<img width="769" alt="image" src="https://user-images.githubusercontent.com/4921183/209153259-d6fc11a6-ba31-4c81-b7e3-44aa98e49d37.png">
