### ISSUE TITLE
[FEATURE] Write article for async/await in nodejs roadmap

### ISSUE THREAD

**Issue by SSHSRN** [kamranahmedse/developer-roadmap#2008]
I want to write the content for the async/await, which is a topic that comes under Asynchronous programming in node js roadmap. 
I got to know that the content for the topic is not written yet as I was checking out the [website](https://roadmap.sh/nodejs).

Screenshots:
* 
![image](https://user-images.githubusercontent.com/62781914/193452670-7091eb48-bb1c-40a4-a5cd-08b70e8f58d0.png)
* 
![image](https://user-images.githubusercontent.com/62781914/193452685-d083cc7b-007f-4e6f-b753-47f5c1f5edb9.png)

**Comment by kamranahmedse** [comment]
You can add the content by [following the contribution guidelines](https://github.com/kamranahmedse/developer-roadmap/blob/master/contributing.md#adding-content)

**Comment by SSHSRN** [comment]
#2057
