### ISSUE TITLE
Add Kyle Simpson's You Don't Know JS Yet (book series) 

### ISSUE THREAD

**Issue by bpires** [kamranahmedse/developer-roadmap#2058]
Consider adding Kyle Simpson's [You Don't Know JS Yet (book series)](https://github.com/getify/You-Dont-Know-JS). I didn't find it on the roadmap and I believe it would be a great addition to the JavaScript-related roadmaps. It's a series of books diving deep into the core mechanisms of the JavaScript language and it's available freely on GitHub.

**Comment by kamranahmedse** [comment]
Feel free to open a PR. Here are the [details on how to add that](https://github.com/kamranahmedse/developer-roadmap/blob/master/contributing.md).
