### ISSUE TITLE
Developer Advocate/ Evangelist Roadmap

### ISSUE THREAD

**Issue by kuberaspeaking** [kamranahmedse/developer-roadmap#2074]
A career in Developer Relations is quite sought after. I can add content for a Developer Advocate / Developer Evangelist roadmap

**Comment by kamranahmedse** [comment]
Please have a look at the contribution docs for [helping with new roadmaps](https://github.com/kamranahmedse/developer-roadmap/blob/master/contributing.md#new-roadmaps)
