### ISSUE TITLE
 Bug in JavaScript Roadmap

### ISSUE THREAD

**Issue by abiyyu03** [kamranahmedse/developer-roadmap#2112]
In [javascript roadmap](https://roadmap.sh/javascript), there is a small bug here. In the 'using this keyword' section, each content cannot be clicked. I hope this is fixed soon
![image](https://user-images.githubusercontent.com/60283562/193848038-7bd77bdf-fbfe-4b00-8577-f2bb97cf150c.png)

**Comment by Aryan-Bhatt-pro** [comment]
Hello, can I work on the issue?

**Comment by atharvagarwal** [comment]
can i work on this issue?

**Comment by kamranahmedse** [comment]
This has been fixed. Thank you!
