### ISSUE TITLE
[Suggestion] To remove the term `Non-Functional` in QA Roadmap

### ISSUE THREAD

**Issue by QAInsights** [kamranahmedse/developer-roadmap#2137]
**Rationale**

QA professionals, especially those working in `Performance Engineering and Testing` negates the term `Non-Functional`. The rationale behind is: the term `performance` is `functional` for any application. Similarly for [`Accessbility Testing`](https://web.dev/accessible/), [`Security Testing`](https://owasp.org/www-project-top-ten/), and more.

![image](https://user-images.githubusercontent.com/2826376/193952008-7fd668db-fc00-4d68-92ef-76d1b6848306.png)

AFAIK, there is no official term for `Non-Functional Testing` or `Non-Functional Requirements`. Industry leaders James Bach, Cem Kaner, Alexander Podelko and more agrees that the term misrepresents the testing objective.

So, I am proposing to change the term to `Extra-Funcational`. 

Credits to [James Bach](https://en.wikipedia.org/wiki/James_Marcus_Bach). 

@kamranahmedse Please share your inputs as well. I can make a PR to change it everywhere. Thanks!

**Comment by kamranahmedse** [comment]
Thank you for the suggestion but the roadmap was reviewed by several subject matter experts before publishing and no-one pointed that out. However, I will leave the issue open for now for people to vote to decide if this change should go in the roadmap or not.

**Comment by QAInsights** [comment]
Thanks @kamranahmedse. The term "Non-Functional" has been used for many years. Many online forums and blogs still quote "Non-Functional". As you mentioned, let us wait for the votes.

**Comment by eldaduzman** [comment]
I think @QAInsights is spot on.

The distinction between 'functional' and 'non-functional' requirements is for the most part arbitrary.

**Comment by perfsid** [comment]
yes, the change jas to be done ...Agree with you ...Extra-Functional.

I Have another proposed word like **Operational Requirements** how abt that ..?

**Comment by tanvi1110** [comment]
I too agree to replace the word non-functional with extra functional  since requirement for the system to be non functional under a certain condition is the right interpretation of it according to me.

**Comment by QAInsights** [comment]
@tanvi1110 thanks for your inputs, please upvote [here](https://github.com/kamranahmedse/developer-roadmap/issues/2137#issue-1396996949)

**Comment by kamranahmedse** [comment]
@QAInsights your recommendation was reviewed by the contributors; while it does seem reasonable, the widely known term _is_ "Non-Functional" and we don't want to change it and confuse the beginners. Feel free to help [add the content under the node instead](https://github.com/kamranahmedse/developer-roadmap/blob/master/content/roadmaps/113-qa/content/100-qa-basics/107-testing-techniques/101-non-functional-testing/readme.md) mentioning the Non-Functional vs Extra-Functional topic.

**Comment by QAInsights** [comment]
@kamranahmedse I understand your point.   

> we don't want to change it and confuse the beginners

This is exactly what I want to change. The beginners needs to understand the exact meaning of other types of testing. They should not literally under the term "Non-Functional".
