### ISSUE TITLE
[Suggestion] Frontend Developer

### ISSUE THREAD

**Issue by MarkShmurm** [kamranahmedse/developer-roadmap#2185]
Add remix.js to static site generators and SSR

**Comment by santoshvijapure** [comment]
@MarkShmurm Can I pick this?

**Comment by MarkShmurm** [comment]
yes please

**Comment by santoshvijapure** [comment]
ok sure

**Comment by kamranahmedse** [comment]
This has been fixed and will be published in the coming release. Thank you 🙏
