### ISSUE TITLE
RoadMap for Sprint Boot

### ISSUE THREAD

**Issue by RamitPahwa** [kamranahmedse/developer-roadmap#2214]
- Introduction to Java
   - Compilation
   - Variable and User Input
   - Simple Math and Logic
   - Strings
   - Conditional Statements
   - Loops
   - Methods
   - Arrays
   - Class and Inheritance
   - Generics
   - ArrayLists
   - HashMap/ HashSet
- What is Spring? 
   - Terminology
   - Spring Architecture
   - Reasons for sustained popularity
- Spring Basics
   - Dependency
   - Decoupling Components
   - Beans 
   - Auto-writing by type - @Primary
   - Auto-writing @Qualifier
   - Constructor
   - Setter Injection
- Spring in Depth
   - Bean Scope
   - @ComponentScan
   - Bean LifeCycle
   - Context and Dependency Injection Framework
   - Spring Application Configuration
   - XML Configuration
   - Stereotype Annotations
   - External Property File
- What is Spring Boot?
   - Rest Service 
   - Developer Tools
   - Actuator
   - Spring Boot vs Spring MVC
- What is Spring MVC?
  - Set up Web Application
  - Servlet
  - JSP File
  - Architecture
  - Components
- Unit Testing

**Comment by omkute** [comment]
@RamitPahwa  I am interested in contributing in this project can you please assign me

**Comment by kamranahmedse** [comment]
Thanks @RamitPahwa 

@omkute please look at the contribution docs. There is no issue assignment. In this particular issue, if you would like to contribute please suggest changes to the roadmap submitted by @RamitPahwa

**Comment by RamitPahwa** [comment]
Hey @kamranahmedse should I start making this page?, maybe @omkute can help me out in completing the roadmap in parallel

**Comment by kamranahmedse** [comment]
@RamitPahwa the list is converted to a visual roadmap in Balsamiq and is done in a particular style matching the other roadmaps, so we keep the translation from list to visual roadmap as an internal task. But thank you for offering to help.

Feel free to polish the list further by adding or improving the listed topics till we pick this up next week.

**Comment by kamranahmedse** [comment]
Spring Boot roadmap has been prepared and will be published in the coming release. Thank you 🙏
