### ISSUE TITLE
[Suggestion] Laravel Road Map

### ISSUE THREAD

**Issue by brantheeman** [kamranahmedse/developer-roadmap#2231]

**Comment by brantheeman** [comment]
@kamranahmedse For the author section of the meta.json do I replace my name with yours? or should I leave yours and add my name?

**Comment by kamranahmedse** [comment]
@brantheeman have a look at the [contribution docs for adding new roadmaps please.](https://github.com/kamranahmedse/developer-roadmap/blob/master/contributing.md#new-roadmaps)
