### ISSUE TITLE
[Suggestion] Python Developer

### ISSUE THREAD

**Issue by shroominic** [kamranahmedse/developer-roadmap#2243]
I just want to add some important stuff you need to learn in the "Advanced" field of python.

[ ... ]

3. Advanced Topics
- List comprehensions [read](https://www.w3schools.com/python/python_lists_comprehension.asp)
- Generator expressions [read](https://www.pythontutorial.net/advanced-python/python-generator-expressions/)
- Paradigms in Python [read](https://www.geeksforgeeks.org/programming-paradigms-in-python/)
- ( ... )
- Regular Expressions
    - match case syntax (new in 3.10) [read](https://stackoverflow.com/questions/70680363/structural-pattern-matching-using-regex)

[ ... ]

**Comment by Anu-Ra-g** [comment]
What should be the PR about?

**Comment by mughalmuneeb786** [comment]
I want to add roadmap extend with Python as Web Application Developer with Django or other related platforms and Rest API and also contribute in Hacktoberfest.

**Comment by shroominic** [comment]
@mughalmuneeb786 Where do you want to add these points? Or do you mean something different?

**Comment by SE-LAPS** [comment]
I am interested in contributing in this project can you please assign me and also contribute in Hacktoberfest.

**Comment by SE-LAPS** [comment]
I am interested in contributing in this project can you please assign me and also contribute in Hacktoberfest-2022.

**Comment by kamranahmedse** [comment]
This has been fixed and will be published in the coming release. Thank you 🙏
