### ISSUE TITLE
Add greetings workflow to greet new contributors when they raise A PR OR CREATE AN ISSUE

### ISSUE THREAD

**Issue by hasnainmakada-99** [kamranahmedse/developer-roadmap#2289]
I would like to integrate `greetings.yml` action workflow in this project so that whenever any new contributor raises their PR or creates a new issue they should be greeted

I would like to request the maintainers to label this issue as hacktoberfest as I am contributing to this issue as a part of the hacktoberfest.

😄

**Comment by kamranahmedse** [comment]
I don't think there is a need for that. Thank you for the suggestion though!
