### ISSUE TITLE
Top Youtube link bar is non-removable by user 

### ISSUE THREAD

**Issue by parthapaul7** [kamranahmedse/developer-roadmap#2351]
The top youtube link bar is a bit annoying because you can not remove it 
There should a close button to remove the top bar 

![image](https://user-images.githubusercontent.com/83518670/194774857-52dd5ac2-6b73-4d2e-9036-d02fb310e366.png)

**Comment by kamranahmedse** [comment]
Thank you for the issue but we are actively working on the [next version of roadmap.sh](https://next.roadmap.sh/) so there is no need to implement this for now. Thanks for opening the issue though!
