### ISSUE TITLE
[Suggestion] Frontend Developer

### ISSUE THREAD

**Issue by sujoy-kr** [kamranahmedse/developer-roadmap#2457]
Add Svelte, Sveltekit in server side rendering.

**Comment by lakshmimaurya** [comment]
could you please assign this to me

**Comment by being-nitin** [comment]
could you please assign this to me .

**Comment by this-mkhy** [comment]
I can do it

**Comment by TanyaaSrivastava** [comment]
I am interested in this, could I be assigned this task? I want to participate in hactoberfest.

**Comment by SE-LAPS** [comment]
I am interested in contributing in this project can you please assign me and also contribute in Hacktoberfest-2022.

**Comment by pjoshi999** [comment]
Hello,
This is Priyanshu. I have been doing Frontend since very long. I can help you with the best beginner-friendly Roadmap for Frontent Development. Kindly assign the task to me so that every learner right there can benefit from this Roadmap.

**Comment by kamranahmedse** [comment]
This has been fixed and will be published in the coming release. Thank you 🙏
