### ISSUE TITLE
Add contents of DBMS-RoadMap

### ISSUE THREAD

**Issue by crescentpartha** [kamranahmedse/developer-roadmap#2542]
Add contents of `DBMS-RoadMap`

**Comment by kamranahmedse** [comment]
Textual version listed below:


> Textual version of the DBMS RoadMap
- Introduction
  - What is a Database?
  - What is DBMS?
  - Why do we need DBMS?
  - File management system vs DBMS
  - What is Database Admin & its Functions?
  - Database Tier-2/Tier-3 Architecture
  - Database Languages
    - DCL
    - DDL
    - DML
    - TCL
  - Imp Terms
    - Instance
    - Schema
    - Sub-Schema
  - How DBMS is implemented?
  - What is Data abstraction in DBMS
  - 3 level of Data Abstraction
  - What is Referential Integrity
- RDBMS
  - What is RDBMS & how it is stored in memory?
  - What is the meaning of word `Relational` in RDBMS?
  - Degree of Relation
    - 1:1
    - 1:M
    - M:M
  - Keys
    - Primary Key
    - Foreign Key
    - Candidate Key
    - Composite Key
    - Alternate Key
    - Super Key
    - Secondary Key
  - Database Schema
    - Physical Database Schema
    - Logical Database Schema
  - Schema Diagrams
    - Relational Model
    - ER Diagram
      - ER to Relational Model conversion
  - Relational Operations
    - Select
    - Project
    - Union
    - Set Different
    - Cartesian Product
    - Rename
  - SQL
    - What is SQL?
    - Difference between SQL and MySQL
    - Important Keywords
    - Types of JOIN
      - Inner Join
      - Left Join
      - Right Join
      - Full Join
      - Self Join
    - View
    - Trigger
    - SQL Injection
    - SQL Privileges
    - Delete vs Truncate
    - Unique key vs Primary key
    - Clustered vs Non-Clustered
    - Cursor
    - SQL Query
  - What is Index in DBMS & its types?
- Relational Database Design
  - Features of Good Relational Design
  - What is Functional Dependency?
    - Types
      - Trivial
      - Non-Trivial
      - Fully-Functional Dependency
      - Partial
      - Transitive
  - What is Normalization?
  - Purpose of Normalization?
  - What are 3 anomalies resolved by normalization?
  - Types of Normalization
    - 1NF
      - Purpose and Steps to convert?
    - 2NF
      - Purpose and Steps to convert?
    - 3NF
      - Purpose and Steps to convert?
    - BCNF
      - Purpose and Steps to convert?
- Storage and File Structure
  - Storage System
  - File Structure
- Transaction Management
  - What is a transaction?
    - State of Transaction
  - IMP terms
    - Commit
    - Rollback
    - Savepoint
  - ACID Properties
  - How to implement Atomicity in Transactions?
  - Concurrent Transaction?
  - Schedule
    - Types
      - Serial
      - Complete
      - Recoverable
      - Cascadeless
      - Strict
    - What is Conflict Operation?
      - How to find whether Schedules are conflicting or not?
  - Concurrency Control
    - Purpose
      - Shared Lock
      - Exclusive Lock
    - 2-Phase Locking Protocol [IMP]
- DeadLock
  - What is a DeadLock?
  - DeadLock Detection
  - DeadLock Prevention
    - Mutual Exclusion
    - Hold and Wait
    - No PreEmption
    - Circular wait
  - Other Techniques to prevent DeadLock
    - use Timestamp
      - Wait-Die Scheme
      - Wound-Wait Scheme
      - Timeout Based Scheme
  - What is Starvation and its reason?
  - DeadLock Recovery
    - Selection of Victim
    - Rollback
    - Starvation

Taken from https://github.com/kamranahmedse/developer-roadmap/pull/2543

**Comment by kamranahmedse** [comment]
Hey there!

Looks like this issue has been hanging around for a bit without much action. Our roadmaps have evolved quite a bit since then, and a bunch of older issues aren't really applicable anymore. So, we're tidying things up by closing out the older ones to keep our issue tracker nice and organized for future feedback.

If you still think this problem needs addressing, don't hesitate to reopen the issue. We're here to help!

Thanks a bunch!
