### ISSUE TITLE
unable to zoom

### ISSUE THREAD

**Issue by varunjvk** [kamranahmedse/developer-roadmap#2556]
I am unable to zoom the page to see the details of roadmap clearly in my mobile browser

**Comment by CodeWAdi** [comment]
kindly share the screenshot of the problem and  the name of it

**Comment by varunjvk** [comment]
https://user-images.githubusercontent.com/97157497/196215026-5bc4883f-6ffb-47b0-99b5-2dd08052bbee.mp4



kindly check this out you will find what's the issue is.

**Comment by alexandersuerof** [comment]
>
I was checking that problem, but it's working just fine when I zoom in with both fingers in the mobile browser(Google Chrome)

**Comment by varunjvk** [comment]
yeah, it was zooming in naturally but when you click on any node and coming back then zooming in is not happening check video i provided here (google chrome)

**Comment by kamranahmedse** [comment]
This should be fixed now. Can you please try again?
