### ISSUE TITLE
Flutter Developer

### ISSUE THREAD

**Issue by numanuddin1** [kamranahmedse/developer-roadmap#2564]
I want to add roadmap for flutter developer

**Comment by AyushRaghuvanshi** [comment]
Hi, I would like to work on this as well, because I feel Flutter is also a skill based techstack, and it should be there.

**Comment by macsakini** [comment]
Hi, I would also like to be included in this.

**Comment by DeleMike** [comment]
Hi, I would love to work on this too but how do we start?

**Comment by Mizerski** [comment]
Hello, I want to add a roadmap for the Flutter developer, I have a personal one that I made while studying

![Captura de tela de 2022-10-26 18-20-21](https://user-images.githubusercontent.com/58005471/198151965-03cf5155-5adc-4ffb-a1ae-45116c672899.png)

**Comment by dmytbolko** [comment]
@kamranahmedse here is the textual version of the flutter roadmap that we have at our company. Feel free to update it as you may see fit.

@AyushRaghuvanshi @macsakini @DeleMike feel free to suggest changes.

- Learn Dart
  - Variables
  - Built-in Types
  - Functions
  - Operators
  - Control Flow Statements
  - Classes
- Setup Environment
  - IDEs
    - VS Code
    - Android Studio
    - Intellij IDEA
  - Flutter CLI
- Widgets
  - Stateless Widgets
  - Stateful Widgets
  - Styled Widgets
    - Material Widgets
    - Cupertino Widgets
- Working with Assets
  - Fonts
  - Images
  - SVGs
- Version Control
  - Git
  - GitHub
- Design Principles
  - OOP
  - SOLID Principles
  - Design Patterns
  - Dependency Injection
- Package Manager
  - flutter pub
  - pub.dev
- Working with APIs
  - RESTful APIs
  - GraphQL
  - Web Sockets
  - JSON
    - Serialize
    - Deserialize
- Storage
  - Shared Preferences
  - SQLite
  - Firebase
    - Authentication
    - Storage
    - Firestore
    - Push Notifications
    - Remote Config
- Dart Advanced
  - Lists
  - Variables
  - Lambdas
  - Functional Programming
  - Collections
  - Isolates
  - Async / Await
  - Future
  - Streams
  - Core Libraries
- State Management
  - Provider
  - BLoC pattern
  - Flutter BLoc
  - Velocity X
  - Get X
  - Flutter Redux
- Animations
  - Animated Widget
  - Animated Builder
  - Animation Controller
  - Curved Animation
  - Hero
  - Opacity
- Testing
  - Unit Testing
  - Widget Testing
  - Integration Testing
  - TDD
  - BDD 
- Reactive Programming
  - RxDart
- Packages and Plugins
- DevTools
  - Flutter Inspector
  - Flutter Outline
  - Memory Allocation
- Internals of Flutter
  - Render Objects
  - 3 Trees
  - Immutability
- Learn Other Languages
  - Kotlin
  - Swift
  - HTML / CSS / JavaScript
- CI / CD
  - Fast Lane
  - Codemagic
  - Bitrise
  - GitHub Actions
  - Firebase App Distribution
- Analytics
  - Firebase Analytics
  - Segments
  - Mix Panel
  - Google Analytics
- Deployment
  - Appstore
  - Playstore
  	- Guidelines and Protocols

**Comment by kamranahmedse** [comment]
[Flutter roadmap is live](https://roadmap.sh/flutter). Thank you guys!

**Comment by DeleMike** [comment]
> @kamranahmedse here is the textual version of the flutter roadmap that we have at our company. Feel free to update it as you may see fit.
> 
> @AyushRaghuvanshi @macsakini @DeleMike feel free to suggest changes.
> 
> * Learn Dart
>   
>   * Variables
>   * Built-in Types
>   * Functions
>   * Operators
>   * Control Flow Statements
>   * Classes
> * Setup Environment
>   
>   * IDEs
>     
>     * VS Code
>     * Android Studio
>     * Intellij IDEA
>   * Flutter CLI
> * Widgets
>   
>   * Stateless Widgets
>   * Stateful Widgets
>   * Styled Widgets
>     
>     * Material Widgets
>     * Cupertino Widgets
> * Working with Assets
>   
>   * Fonts
>   * Images
>   * SVGs
> * Version Control
>   
>   * Git
>   * GitHub
> * Design Principles
>   
>   * OOP
>   * SOLID Principles
>   * Design Patterns
>   * Dependency Injection
> * Package Manager
>   
>   * flutter pub
>   * pub.dev
> * Working with APIs
>   
>   * RESTful APIs
>   * GraphQL
>   * Web Sockets
>   * JSON
>     
>     * Serialize
>     * Deserialize
> * Storage
>   
>   * Shared Preferences
>   * SQLite
>   * NoSQ(Hive , Firebase)
> * Authentication
>
>     * Storage
>     * Firestore
>     * Push Notifications
>     * Remote Config
> * Dart Advanced
>   
>   * Lists
>   * Variables
>   * Lambdas
>   * Functional Programming
>   * Collections
>   * Isolates
>   * Async / Await
>   * Future
>   * Streams
>   * Core Libraries
> * State Management
>   
>   * Provider
>   * Riverpod
>   * BLoC pattern
>   * Flutter BLoc
>   * Velocity X
>   * Get X
>   * Flutter Redux
> * Animations
>   
>   * Animated Widget
>   * Animated Builder
>   * Animation Controller
>   * Curved Animation
>   * Hero
>   * Opacity
> * Testing
>   
>   * Unit Testing
>   * Widget Testing
>   * Integration Testing
>   * TDD
>   * BDD
> * Reactive Programming
>   
>   * RxDart
> * Packages and Plugins
> * DevTools
>   
>   * Flutter Inspector
>   * Flutter Outline
>   * Memory Allocation
> * Internals of Flutter
>   
>   * Render Objects
>   * 3 Trees
>   * Immutability
> * Learn Other Languages
>   
>   * Kotlin
>   * Swift
>   * HTML / CSS / JavaScript
> * CI / CD
>   
>   * Fast Lane
>   * Codemagic
>   * Bitrise
>   * GitHub Actions
>   * Firebase App Distribution
> * Analytics
>   
>   * Firebase Analytics
>   * Segments
>   * Mix Panel
>   * Google Analytics
> * Deployment
>   
>   * Appstore
>   * Playstore
>     
>     * Guidelines and Protocols


I added noSQL and Riverpod(which may potentially replace Provider!)
