### ISSUE TITLE
JavaScript Frameworks

### ISSUE THREAD

**Issue by MikhailTatsky** [kamranahmedse/developer-roadmap#26]
Please add in Front-end, JavaScript Frameworks
ExtJS, EmberJS

**Comment by bennyn** [comment]
I am also missing [Polymer](https://www.polymer-project.org/).

**Comment by ChouUn** [comment]
pls add in front-end: rxjs, immutable.js, backbone, lodash / ramda / underscore.

**Comment by link-alex** [comment]
Is it really suitable to put all the js frameworks on the chart? like, ALL of them? And all the cool libraries should be there also in this case?
I believe a separate chart for this topic is required then..
What do you think guys?

**Comment by arpit1997** [comment]
@ChouUn I agree with @link-alex Its not suitable to pull off every cool javascript library in one chart there is like hundereds. We can try making a list by popularity or category.

**Comment by carlosgalveias** [comment]
+1 for EmberJS, its a very popular framework used by Netflix, LinkedIn, Apple Music and its awesome!!

**Comment by se-panfilov** [comment]
In terms of trending frameworks, I'd say Vue.js and Aurelia

**Comment by deerua** [comment]
angularJs and angular (2.x > ) now separate stuff 
and angular can use redux, rxjs (core stuff of angular)

**Comment by kamranahmedse** [comment]
Ember JS agreed (pushing it in a few minutes). But as @link-alex said, if we keep adding each and everything it will easily become convoluted. Thank you.

**Comment by luchillo17** [comment]
@deerua Is right, angular 2 can now use Redux through `@ngrx/store` npm module which uses `Rxjs` to make redux Observable based, however i don't think Ng1 & Ng2 should be considered separated in the graph, Ng2 is indeed a full rewrite of the framework, but that's just a peculiarity between the 2 versions that shouldn't be included in the graph.

**Comment by mcMickJuice** [comment]
Why not separate out flue/redux into a "state management" section?  By principal they're UI library agnostic and can be used with nearly any frontend framework.
