### ISSUE TITLE
[suggestion] Add Data Science / Machine Learning Road Map

### ISSUE THREAD

**Issue by domenicrosati** [kamranahmedse/developer-roadmap#260]

**Comment by TheHollidayInn** [comment]
I think this would be a good reference: https://github.com/datasciencemasters/go . Thoughts?

**Comment by nikitavoloboev** [comment]
We are working on a search engine to search over community curated learning paths.

[Here](https://learn-anything.xyz/machine-learning) is the path for learning machine learning.

And [here](https://learn-anything.xyz/data-science) is the path for learning Data Science.

**Comment by AnatoliiSirosh** [comment]
Anatolii Sirosh
Software Engineer

Office: +380 44 390 5457<tel:+380%2044%20390%205457> x 66907<tel:66907>   Cell: +380 63 776 5360<tel:+380%2063%20776%205360>   Email: anatolii_sirosh@epam.com<mailto:anatolii_sirosh@epam.com>
Kyiv, Ukraine (GMT+2)   epam.com<http://www.epam.com>

CONFIDENTIALITY CAUTION AND DISCLAIMER
This message is intended only for the use of the individual(s) or entity(ies) to which it is addressed and contains information that is legally privileged and confidential. If you are not the intended recipient, or the person responsible for delivering the message to the intended recipient, you are hereby notified that any dissemination, distribution or copying of this communication is strictly prohibited. All unintended recipients are obliged to delete this message and destroy any printed copies.

**Comment by kamranahmedse** [comment]
Thanks for suggesting but I have no plans at the moment.

**Comment by amravazzi** [comment]
Up vote here
