### ISSUE TITLE
Loopback as Node.js framework?

### ISSUE THREAD

**Issue by amandeepmittal** [kamranahmedse/developer-roadmap#262]
Loopback is a good Node.js framework with some ready to use Enterprise level solutions. I think it will be a good idea to add loopback in the Node.js framewrok section in the **Back-end**.
Loopback [Website](https://loopback.io/)

**Comment by GaryTowers** [comment]
I agree on this. The loopback framework is a great one to explore in the **Back-end** section. Highly robust. They've done some pretty interesting things.

**Comment by kamranahmedse** [comment]
Thank you for reporting. Pushing in a few
