### ISSUE TITLE
[Suggestion] Frontend Developer

### ISSUE THREAD

**Issue by Foxtrot40** [kamranahmedse/developer-roadmap#2644]
On "Testing your apps" is said to study the technologies on the left, but it should be right.

<img width="1026" alt="Screen Shot 2022-10-20 at 18 00 16" src="https://user-images.githubusercontent.com/24324267/197057143-b192362a-9ba4-4608-9121-300884462ed9.png">

**Comment by kamranahmedse** [comment]
Fixed, thank you!
