### ISSUE TITLE
Front End Roadmap

### ISSUE THREAD

**Issue by tsvecak** [kamranahmedse/developer-roadmap#266]
In my opinion front end roadmap is good but most of the focus goes of to JavaScript and I think you should spread focus between JavaScript and CSS( SCSS ) as you can't be good front end dev if you are not strong with CSS. Hope this helps to improve roadmap :)

**Comment by dicexq** [comment]
There is SCSS in the Front-end tree? (Getting deeper > CSS > Pre-processor > SASS).
There is also a whole block for CSS3.

**Comment by tsvecak** [comment]
I know, but I think that all the things in bottom right corner are a bit more important for a pure front end dev then e.g fully know how to work with webpack, again it's a thing of personal preference

**Comment by kamranahmedse** [comment]
Thanks @tsvecak for opening the issue but as @dicexq it is already mentioned.
