### ISSUE TITLE
Add Socket.IO to back-end development roadmap

### ISSUE THREAD

**Issue by amritjha** [kamranahmedse/developer-roadmap#267]
"Socket.IO enables real-time bidirectional event-based communication. It works on every platform, browser or device, focusing equally on reliability and speed." as they describe themselves on their website (https://socket.io). It is a powerful and popular technology that comes immensely handy in real-time analytics, binary streaming, real-time communication and document collaboration among many others.

**Comment by kamranahmedse** [comment]
This has been fixed and will be published in the coming release. Thank you 🙏
