### ISSUE TITLE
let's add a DevRel roadmap

### ISSUE THREAD

**Issue by nikitakoselev** [kamranahmedse/developer-roadmap#2683]
There is issue #2167, which has been completed with no comments.

As an OpenSource DevRel, I help people to follow my steps, but I only have 24h per day, and a lot of people want to become an OpenSource DevRel to create and empower communities around OpenSource projects.

A DevRel OpenSource roadmap would help tens of thousands of people around the world to create communities.
I know it's not an easy task, but I would really like to contribute and bring more open-source contributors to make this roadmap happen.

Let's discuss, even a "no" is appreciated and will help the community, as I will share the reasoning and explain what was my mistake.

**Comment by kamranahmedse** [comment]
@nikitakoselev thank you for offering to help. Would you be able to provide the [textual version of the roadmap](https://gist.github.com/kamranahmedse/98758d2c73799b3a6ce17385e4c548a5). We can then discuss and get it converted to the visual format.

PS, @kuberaspeaking shared her list in https://github.com/kamranahmedse/developer-roadmap/issues/2077 so feel free to improve on that.

**Comment by nikitakoselev** [comment]
Let me start working on that. Many thanks for sharing @kuberaspeaking's list #2077

**Comment by nikitakoselev** [comment]
Just letting you know that I have sorted some things out and now I plan to start working on the issue tomorrow.

**Comment by kamranahmedse** [comment]
We are now closing any issues requesting new roadmap requests to clean up the issues.

However, this doesn't mean that the requested roadmap won't be added to the website. We are putting it in the backlog and will add it to the website depending on how it ranks in the backlog or sooner if we find someone interested in adding that roadmap. Thank you for the request though! 🙏

**Comment by kushal140** [comment]
Has this issue been closed appropriately? Or has the devrel roadmap already been released?
