### ISSUE TITLE
Deep dive into Git

### ISSUE THREAD

**Issue by OSP123** [kamranahmedse/developer-roadmap#271]
- Advanced Git commands, including stash, reset, bisect, squash, rebase. 
- Could be a perfect guide: https://www.toptal.com/git/the-advanced-git-guide

**Comment by luchillo17** [comment]
That should be optional, i've developed for almost 4 years and my GUI makes it so i don't have to know how to use them, maybe `stash` and `reset` whom i've used a lot, but i've never done `bisect`, `squash` nor `rebase`.

**Comment by mstuttgart** [comment]
It is interesting to know the theory behind the tool, especially in UNIX like environments, where the command line is used. I think it's interesting to know the `stash` and `reset` commands, at least. :+1:

**Comment by luchillo17** [comment]
Indeed those 2 i use a lot in my dev cycle, but never had to use `bisect` nor `squash`.

**Comment by OSP123** [comment]
Hey, nice to meet you. I'm actually using your repository as a roadmap for our post grad curriculum :)! https://github.com/OSP123/post-grad-curriculum. I accidentally put the comment I was supposed to put in this Repository.

**Comment by luchillo17** [comment]
Jaja 😃 well, maybe it gets added here too.

**Comment by OSP123** [comment]
You guys can always copy the stuff from our repo :-). Open source is pretty great.
