### ISSUE TITLE
Impossibility to Translate

### ISSUE THREAD

**Issue by DeltaFoxtMike** [kamranahmedse/developer-roadmap#2711]
Hi, I recently checked if I could translate something in this repo, I found this link https://github.com/kamranahmedse/developer-roadmap/tree/0471d44c8fae58b6a36a7c57bba12253916d0249/translations which shows the languages ​​already translated, also at the bottom of the page there is a link that allows you to send your own translation, but it leads to a deleted page, making the translation impossible for those who want to do it.

I am new to contributing to Open Source projects and if possible I can help :)

**Comment by kamranahmedse** [comment]
Hey, translations existed in the older version of the repository. The website doesn't have any way to localize the content. However, it is planned and will be made possible in the future.
