### ISSUE TITLE
TODO: Add relevant resources for each

### ISSUE THREAD

**Issue by artemgurzhii** [kamranahmedse/developer-roadmap#273]
Can this todo item be resolved with those resources [front-end](https://github.com/sindresorhus/awesome#front-end-development), [back-end](https://github.com/sindresorhus/awesome#back-end-development) and [devops](https://github.com/AcalephStorage/awesome-devops)?

P.S. This [awesome list](https://github.com/sindresorhus/awesome) has a lot of resources for the DevOps but not in one section.

**Comment by BitYog** [comment]
Sure. For front-end:
HTML Dog, MDN, freeCodeCamp for most things. 
Getbootstrap & CSS-Tricks for CSS.
For JS, GitHub has a lot of helpful repos

**Comment by lnuon** [comment]
@artemgurzhii and @BitYog - You hit on a question that came of for me as well. What type of resources are we looking for? Digital only? Books? Does it have to have a certain number of likes or upvotes, or are we looking for quantity over a high bar for quality? I've aggregated all my feedback and related issues under issue #316

**Comment by kamranahmedse** [comment]
They are being worked upon and will be added to [roadmap.sh](https://roadmap.sh) once we are done with the 2020 release. Thank you!
