### ISSUE TITLE
[Suggestion] Web GIS developer roadmap

### ISSUE THREAD

**Issue by sembrex** [kamranahmedse/developer-roadmap#276]
As a part of web development, i think webgis development branch should be added. [OpenLayers](http://openlayers.org/), [Leaflet](http://leafletjs.com/), [GoogleMaps JS](https://developers.google.com/maps/documentation/javascript/) for JS mapping library. [Geoserver](http://geoserver.org/), [Map Server](http://mapserver.org/), [Mapnik](http://mapnik.org/) for spatial data server.

**Comment by jorgeas80** [comment]
And [Carto](https://carto.com/) and [Mapbox](https://www.mapbox.com/) for tools

**Comment by pmacMaps** [comment]
I would also add [Esri JS API](https://developers.arcgis.com/javascript/) and the [Esri REST API](http://resources.arcgis.com/en/help/rest/apiref/).

**Comment by kamranahmedse** [comment]
Hey guys,

Thank you for opening the issue but for the time being we are focusing merely on the web development and adding anything "irrelevant" or extra is just going to convolute it and scare the beginners away so unfortunately I will have to close this issue. 

Thank you for suggestion though.

**Comment by pmacMaps** [comment]
@sembrex and @jorgeas80, we could always start a similar repo to this one for GIS Developer.

@kamranahmedse, would you mind if we used your repo and design for the graphics as a base?

**Comment by kamranahmedse** [comment]
@pmacMaps sure, go ahead :)
