### ISSUE TITLE
[Suggestion] Frontend Developer

### ISSUE THREAD

**Issue by jessicateocw** [kamranahmedse/developer-roadmap#2774]
Any chances to add a dark mode to change the theme colors, everything is kinda bright

**Comment by vandit1920** [comment]
Can I give it a shot?

**Comment by musa-almatri-io** [comment]
I also wish there as a dark mode theme for the website. it is too bright at night.

**Comment by kamranahmedse** [comment]
It is planned but not in the near future. We might have it in the second half of 2023. Stay tuned!
