### ISSUE TITLE
[Suggestion] Add CircleCI to DevOps Roadmap (CI/CD)

### ISSUE THREAD

**Issue by ogasawaraShinnosuke** [kamranahmedse/developer-roadmap#280]
CI service [CircleCI](https://circleci.com/)

Of course if you put in jenkins it will not be a comparison, even if I look at the following trends, I feel that circleci can be inserted.

https://trends.google.com/trends/explore?q=circleci,travisci,teamcity

#161

**Comment by Pierstoval** [comment]
👍 for CircleCI, it has cool docker integration now with 2.0 and config is as easy as with Travis-CI

**Comment by kamranahmedse** [comment]
Fixed. Thanks @felicianotech
