### ISSUE TITLE
[Suggestion] VLSI Design and Verification

### ISSUE THREAD

**Issue by AlphonseVA** [kamranahmedse/developer-roadmap#2831]
Would like to suggest a new roadmap for VLSI Design and Verification

_Hardware Engineers are very underpresentated imo_

**Comment by kamranahmedse** [comment]
Would you be able to help with that? If you [could provide a textual roadmap](https://github.com/kamranahmedse/developer-roadmap/blob/master/contributing.md#new-roadmaps), we can get it polished further and added to the website.

**Comment by kamranahmedse** [comment]
We are now closing any issues requesting new roadmap requests to clean up the issues. 

However, this doesn't mean that the requested roadmap won't be added to the website. We are putting it in the backlog and will add it to the website depending on how it ranks in the backlog or sooner if we find someone interested in adding that roadmap. Thank you for the request though! 🙏
