### ISSUE TITLE
QA Automation roadmap

### ISSUE THREAD

**Issue by ant1dot** [kamranahmedse/developer-roadmap#2839]
> Textual version of the QA Automation roadmap

- Internet
    - How to work internet
    - Dns
    - Http
        - Methods
        - Body formats
        - Headers
        - Cookies
        - Status code
    - Websocket
- Theory testing
    - Test design 
    - Testing pyramid 
    - ROI automation 
- Programming language
    - Basic for all languages
        - Syntax
        - Variables and declarations
        - Data types
        - Mutable / unmutable types
        - For / while loops
        - If, switch statement
        - Error handling
        - Functions
        - Work with dates
        - Work with files	
        - Data structures
        - Class
        - OOP
        - Regex
        - Algorithms
        - Algorithm complexity
        - Design patterns KISS, DRY, SOLID
    - Java
        - Env
            - maven
        - Ide
            - IntelliJ IDEA
        - Test frameworks
            - JUnit
            - TestNG
        - Bdd
            - JBehave  
            - Serenity
        - Matchers
            - assertJ
            - hamcrest
        - Api testing
            - rest-assured
        - Web ui testing
            - selenium
            - selenide
            - jdi
            - HtmlElements
        - Visual regression testing
            - **TODO**
        - Mobile ui testing
            - expresso
            - kaspesso
            - appium
    - Python
        - Env
            - pip
            - virtualenv
            - tox
        - Ide
            - Pycharm
            - Visual studio code 
        - Test frameworks
            - pytest 
            - robot
            - unittest 
        - bdd 
            - behave 
            - pytest-bdd 
        - Matchers
            - PyHamcrest
            - assertpy
            - grappa	    
        - Api testing
            - requests
        - web ui testing
            - selenium
            - playwright
            - webium
        - Visual regression
            - **TODO**
        - Mobile testing
            - appium
    - javascript
        - env
            - node
            - npm
            - npx
            - yarn
    - Ide
        - webstorm
        - visual studio code
    - Test frameworks
        - mocha
        - jest (react) 
    - Matchers
        - chai
        - js-must
    - Web ui testing  
        - webdriver.io
        - playwright
        - cypress
    - Visual regression
        - webdriverio Image Comparison service
        - gemini
    - Mobile ui testing
        - appium
    - Bdd
        - cucumber 
        - mocha 
        - jasmine 
- Version control systems
    - git
        - how to work
        - clone
        - branch
        - checkout 
        - fetch 
        - pull 
        - merge
        - rebase 
    - Repo hosting services
        - gitlab 
        - github 
- Automation testing patterns
    - data driven testing
    - page object pattern
    - behavior-driven development

- Learn for testing api testing
    - Formats
        - json  
        - soap 
        - rest 
        - gRpc
        - jsonrpc
        - graphql
    - Microservice / monolith architecture
    - Tools for ui testing
        - soap ui
        - postman
        - paw
    - Documentation
        - swagger
        - open api
    - Mocks
        - mountebank
        - mockoon
        - api mocha

- Learn for web ui testing
    - Html
    - Css
    - Css / xpath selectors
    - Page object pattern
    - Javascript basic work
    - Ajax
    - Cookies
    - localStorage
    - sessionStorage
    - Chrome developers tools 
    - Cache  
    - Spa 
    - Browser render engine 
    - Client side / server side rendering 
    - Adaptive 
- Web test scaling 
    - selenoid (docker) 
    - selenium grid
    - ggr
    - moon (k8s) 
    - cloud services (sauce labs / browserstack / applitools)

- Learn for testing mobile
    - iOS
        - Os
            - views 
            - lifecycle 
            - logs 
            - simulators 
            - sdk 
    - Native automation
        - swift 
        - xcode 
        - locators
        - XcUiTest 
    - Android
        - Os
            - emulator 
            - lifecycle
            - logs
            - views
            - google api
        - Native automation
            - android studio
            - locators
            - kotlin
            - espresso
            - kaspesso

- Mobile test scaling
    - selenoid (docker android)
    - selenium grid
    - ggr
    - cloud services (sauce labs / browserstack / applitools)
    - callisto (k8s + selenoid)

- Ci 
    - jenkins 
    - teamcity 
    - gitlab ci 
    - github actions 

- Linux
    - Package manager yum / apt
    - Basic terminal commands
        - vi / nano / mcedit / vim
        - wget
        - curl
        - tail
        - less
        - find
        - ssh
        - kill
        - lsof
        - ls / mkdir / touch / rm
        - grep

- Docker
    - How to work
    - images
    - contaners
    - volumes
    - network
    - commands
        - run
        - start / stop / restart
        - build
        - ps
        - logs
        - rm
        - system
    - docker-compose
     
- Database
    - How to work
        - Structure
        - CRUD operations
        - Transactions
        - Deadlock
        - Replications
    - Sql
        - postrgesql
        - mysql
    - No sql
        - redis
        - memcached
        - keydb
    - Documentary
        - mongodb
        - rethinkDB
        - couchDB

- Messages queue
    - rabbit mq       
    - kafka

**Comment by ant1dot** [comment]
QA consists of a very large number of referrals. All of them are difficult to reflect in one roadmap, like all the steps of a full-stack developer. I propose to divide the QA roadmap into separate ones: manual, automation, performance, security.
Can I create a PR for new roadmap for QA Automation?

**Comment by ant1dot** [comment]
@kamranahmedse can you get feedback, please?

**Comment by kamranahmedse** [comment]
Hey there!

Looks like this issue has been hanging around for a bit without much action. Our roadmaps have evolved quite a bit since then, and a bunch of older issues aren't really applicable anymore. So, we're tidying things up by closing out the older ones to keep our issue tracker nice and organized for future feedback.

If you still think this problem needs addressing, don't hesitate to reopen the issue. We're here to help!

Thanks a bunch!
