### ISSUE TITLE
DevOps cloud providers addition

### ISSUE THREAD

**Issue by jamdev12** [kamranahmedse/developer-roadmap#2845]
I would state that OCI - Oracle Cloud Interesting - would be another addition to the cloud service providers line up. Many of the same functionality that is available in AWS and Azure is available in OCI.

**Comment by kamranahmedse** [comment]
Thank you for opening the issue. We don't want to convolute the roadmap by mentioning every available option and are just focusing on what is the most relevant item that you would pick today and the mentioned item doesn't conform to that. 

This has also been [mentioned in the contribution docs](https://github.com/kamranahmedse/developer-roadmap/blob/master/CONTRIBUTING.md#guidelines). 
Thank you for your suggestion though 🙏
