### ISSUE TITLE
Delete a link from node.js roadmap

### ISSUE THREAD

**Issue by ashikkabeer** [kamranahmedse/developer-roadmap#2866]
[The npx Node.js Package Runner](https://nodejs.dev/en/learn/the-npx-nodejs-package-runner) is not available. Its from the node.js roadmap. Its in the npx.

**Comment by 36atharva** [comment]
Can someone assign me this issue? I can fix it with a new link!

**Comment by 36atharva** [comment]
> [The npx Node.js Package Runner](https://nodejs.dev/en/learn/the-npx-nodejs-package-runner) is not available. Its from the node.js roadmap. Its in the npx.

How can I assign this issue to myself, or if not, how can someone else assign this issue to me? I want to fix this!

**Comment by 36atharva** [comment]
How can I assign this issue to myself, or if not, how can someone else assign this issue to me? I want to fix this!

**Comment by dansholds** [comment]
This is a none issue.

The link mentioned above is no longer present but instead is a medium article.
