### ISSUE TITLE
[Suggestion] Ability to interact with it and mark progress

### ISSUE THREAD

**Issue by BNewing** [kamranahmedse/developer-roadmap#288]
I love this project! I'm junior front end developer, and have done a few internships now. I printed the front end diagram off and took it into a progress meeting earlier to discuss things that I need to get better on, as a bigger picture of what a Front End developer is. We used it as a tool for evaluation and future learning planning.

It'd be super cool if you could interact with the images - like if there was a colour code and you could mark off things you can do in varying shades of green or something, where white is no knowledge and dark green is confident and shades in between. 

I'm going to do something similar to the above on paper for now. I might also work on a PR for this as a learning activity at some point :) it might be useful for others too - I came across this project from it being shared in the [codebar](/codebar.io) slack group, where lots of people are all also learning and in the process of becoming developers too :)

**Comment by kamranahmedse** [comment]
Hey thank you. It took me a bit longer than expected to get to it but we started working on that through [roadmap.sh](https://roadmap.sh) and will start releasing the updates soon. Thank you 🙏
