### ISSUE TITLE
[Suggestion] Consider adding Meteor to backend chart under 'frameworks'

### ISSUE THREAD

**Issue by randycochran** [kamranahmedse/developer-roadmap#289]
While it doesn't get the same love as other frameworks, it's still viable as a good option for full-stack JS apps.

https://www.meteor.com/

**Comment by kamranahmedse** [comment]
Hey randy,

Thanks for opening the issue but we are keeping the roadmap to depict only what is more demanded in the market and won't be able to add it.

Thanks.
