### ISSUE TITLE
Fix duplicate nodes in Computer Science roadmap

### ISSUE THREAD

**Issue by tdadadavid** [kamranahmedse/developer-roadmap#2898]
The Section for UML has duplicated nodes called Activity Diagrams and Activity Diagrams that cause issues for users 
`[Screenshot_20221108-062452_Chrome](https://user-images.githubusercontent.com/58336536/200483320-d6080f79-2b50-4af0-9c4b-8944d14ad85f.jpg)`

**Comment by kamranahmedse** [comment]
This has been fixed. Thank you!
