### ISSUE TITLE
Fix consistent naming format > Computer Science roadmap 

### ISSUE THREAD

**Issue by tdadadavid** [kamranahmedse/developer-roadmap#2899]
The naming format for the UML is inconsistent. Certain topics or nodes use the plural form while some use the singular form 

![Screenshot_20221108-062452_Chrome](https://user-images.githubusercontent.com/58336536/200483981-5a6de6cc-6f2f-4415-b0f8-4728fcde1649.jpg)

**Comment by kamranahmedse** [comment]
This has been fixed. Thank you!
