### ISSUE TITLE
Front-end section about charts and grids

### ISSUE THREAD

**Issue by MikhailTatsky** [kamranahmedse/developer-roadmap#29]
Not sure, but could be really useful.

When you need to do some chart or grid solution it is quite big challenge to choose and learn
right solution. There is variety of varients.
Just d3 is solution only for some basic things.
And datatables is not mention for grid and also is not always the the best one solution.

So here is super list of chart solutions
https://github.com/zingchart/awesome-charting

And list of grid/table solutions
https://github.com/FancyGrid/awesome-grid

**Comment by kamranahmedse** [comment]
Hi @MikhailTatsky,

Thank you for reporting. Charts, Grids and this stuff becomes more on the libraries side and if you don't learn them, you can still go by. This repository focuses mainly on the skills that you ought to have. Plus if we keep adding this stuff, it would hardly fit in a single page.

Thanks.
