### ISSUE TITLE
Add Environment Management section to python

### ISSUE THREAD

**Issue by k1-hedayati** [kamranahmedse/developer-roadmap#290]
Environment Management tools are pretty essential for python development.
Some of them:
* Pipenv 
* pyenv
* venv
* virtualenv
* virtualenvwrapper

**Comment by kamranahmedse** [comment]
Hey Keyvan,

Thanks for opening the issue; I agree with what you are implying but to keep the roadmap a little less daunting than it already is and to keep it to the bare essentials, we won't be able to add these at this point.

Thanks though.

**Comment by k1-hedayati** [comment]
It is not daunting in Python section, I could even argue it's pretty thin
