### ISSUE TITLE
Add Debugging and Profiling Tools to python

### ISSUE THREAD

**Issue by k1-hedayati** [kamranahmedse/developer-roadmap#291]
They are essential part of any development, Some of them:
* pdb
* ipdb
* remote-pdb
* wdb
* line_profiler 
* memory_profiler
* django-debug-toolbar

**Comment by kamranahmedse** [comment]
Hey Keyvan,

Thanks for opening the issue; I agree with what you are implying but to keep the roadmap a little less daunting than it already is and to keep it to the bare essentials, we won't be able to add these tools at this point.

Thanks though.
