### ISSUE TITLE
[Suggestion] Frontend Developer

### ISSUE THREAD

**Issue by Draichi** [kamranahmedse/developer-roadmap#2922]
Hello, the project looks amazing

Although, I missed the topic about 3D, before all these AI+AR buzz techs like [WebGL](https://developer.mozilla.org/en-US/docs/Web/API/WebGL_API) where been used a lot, libs like Three.js are like an important topic today so my suggestion is to add a WebGL topic.

sources: 
- https://www.npmjs.com/package/three
- https://developer.mozilla.org/en-US/docs/Web/API/WebXR_Device_API
- https://developer.mozilla.org/en-US/docs/Web/API/WebGL_API

**Comment by kamranahmedse** [comment]
Thank you for opening the issue. We don't want to convolute the roadmap by mentioning every available option and are just focusing on most relevant/important items to learn and WebGL, although interesting and does have use cases, is not a necessity in my humble opinion. 

This has also been [mentioned in the contribution docs](https://github.com/kamranahmedse/developer-roadmap/blob/master/contributing.md#guidelines). 
Thank you for your suggestion though 🙏
