### ISSUE TITLE
Improving the Angular roadmap

### ISSUE THREAD

**Issue by envil** [kamranahmedse/developer-roadmap#296]
1. Separate Angular and Angular JS
2. Add ngrx/store (redux like solution inspired by rxjs) to Angular

**Comment by kamranahmedse** [comment]
Hey, thanks for reporting. 

Yes I do have that in mind but rather planning to do it once and for all in twenty days on `January 1st, 2018` :)

**Comment by kamranahmedse** [comment]
Pushing in a few. Thanks for opening.

**Comment by envil** [comment]
@kamranahmedse kam
Thank you for updating. I think it's worth to include ngrx (state management for Angular).
