### ISSUE TITLE
Remove Silex from roadmap

### ISSUE THREAD

**Issue by nickreynke** [kamranahmedse/developer-roadmap#297]
Since Symfony 4 was released (and now is a micro-framework just like Silex) "Silex ends as a project in June 2018". Removing it now would be better than later because Silex users need to migrate to Symfony 4 anyway. Read more here: https://github.com/symfony/symfony-docs/issues/8678

**Comment by kamranahmedse** [comment]
Fixed, thanks. Pushing the update in a few.
