### ISSUE TITLE
[Suggestion] DevOps Roadmap - Missing GitOps

### ISSUE THREAD

**Issue by rowi1de** [kamranahmedse/developer-roadmap#2999]
- Add GitOps Concept as a topic
  - Add ArgoCD, FluxCD as Tools
- Add Secret Management as Concept
  - e.g. Vault, Cloud Specific Tools, SealedSecrets ...

**Comment by davidcorbetta** [comment]
lgtm

**Comment by kamranahmedse** [comment]
This has been fixed and will be published in the coming release. Thank you 🙏
