### ISSUE TITLE
Missing dev environment

### ISSUE THREAD

**Issue by scibuff** [kamranahmedse/developer-roadmap#3]
Nothing about dev env

**Comment by kamranahmedse** [comment]
It talks about the technologies that anyone should consider learning. What does dev environment have to do with that?

**Comment by riconeitzel** [comment]
I do agree partially: Things like Docker, Vagrant etc. or Continous Integration (Travis, Bamboo) and Deployment (Docker, Jenkins) might be worth do mention as it directly affects the way you work as a developer. #sadly
