### ISSUE TITLE
Definitely Bulma

### ISSUE THREAD

**Issue by jppope** [kamranahmedse/developer-roadmap#300]
Bulma (https://bulma.io/) has been picking up a lot of steam over the last year or two... pretty sure it should be added

**Comment by shirohana** [comment]
Bump.

I think Bulma.css should have a place in the roadmap, too ٩(｡・ω・｡)و

**Comment by NickelGhost** [comment]
I totally agree!
Bulma is a great framework that's already quite popular (from what I see, could even be 2nd most after Boootstrap). It already has lots of support from the community - multiple component sets for Vue and React for example. Its philosophy also differs a bit from Bootstrap's, which seems to be beneficial to new developers.

**Comment by kamranahmedse** [comment]
This has been fixed and will be published in the coming release. Thank you 🙏
