### ISSUE TITLE
[Suggestion] Python Developer

### ISSUE THREAD

**Issue by su-shubham** [kamranahmedse/developer-roadmap#3009]
Fastapi should be there on python  developer roadmap.

**Comment by kamranahmedse** [comment]
This has been fixed and will be published in the coming release. Thank you 🙏 

![New Wireframe 1 copy 3](https://user-images.githubusercontent.com/4921183/204105454-fa02ec3c-93e1-4ee7-986d-d30446da9bc8.png)
