### ISSUE TITLE
Add ESLint to Roadmap

### ISSUE THREAD

**Issue by nlaz** [kamranahmedse/developer-roadmap#301]
Linting and the process of checking code before it is compiled and ran is an important part of developing. I would suggest adding ESLint under a 'Linters' section on the Roadmap. Some great configurations under ESLint are [Airbnb's config](https://www.npmjs.com/package/eslint-config-airbnb) and [Prettier's config](https://github.com/prettier/eslint-config-prettier).

**Comment by kamranahmedse** [comment]
Fixed in the latest release. Thank you for reporting.
