### ISSUE TITLE
[Suggestion] React Developer - Better highlighter for sub-main heading section

### ISSUE THREAD

**Issue by pavansuthar** [kamranahmedse/developer-roadmap#3019]
hello team, 

one quick UI suggesstion if we can implement is that - lets say in React Developer roadmap, for **every sub-main heading**, e.g _Routers, SSR/SSG, State management_ etc, can we have **unique color** other then light brown, to highlight i such a way that its the part of **ecosystem** of react.
<img width="125" alt="Screenshot 2022-11-26 at 8 26 47 PM" src="https://user-images.githubusercontent.com/61886678/204095236-295bf411-65e1-4092-abe9-e6933c139d22.png">

**Comment by kamranahmedse** [comment]
This has been fixed and will be published in the coming release. Thank you 🙏
