### ISSUE TITLE
Which tool you use to created the roadmap

### ISSUE THREAD

**Issue by ole3021** [kamranahmedse/developer-roadmap#302]
I want to know the tool/method you use to draw the roadmap, it looks gorgeous to me

Please let me know

**Comment by ole3021** [comment]
found it at the bottom. 

Balsamiq

**Comment by farnetani** [comment]
I have balsamiq but Í don't to see how that you created it. Can you share it?

**Comment by farnetani** [comment]
I see um directory...thanks...
