### ISSUE TITLE
Add ArangoDB & Mosquitto

### ISSUE THREAD

**Issue by McFizh** [kamranahmedse/developer-roadmap#303]
ArangoDB (ArangoDB is an easy to use mostly memory, high performance, open source NoSQL database with a unique combination of features like graph & geo algorithms.) should go under nosql databases

Mosquitto (Eclipse Mosquitto is an open source message broker that implements the MQTT protocol versions 3.1 and 3.1.1.) should go under message brokers.

**Comment by kamranahmedse** [comment]
Thank you for opening the issue. While I agree with that, we don't want to convolute the roadmap by mentioning every available option and are just focusing on what is the most relevant item that you would pick today and mentioned item doesn't conform to that. This has also been [mentioned in the contribution docs](https://github.com/kamranahmedse/developer-roadmap/blob/master/contributing.md#guidelines). Thank your for your suggestion though 🙏
