### ISSUE TITLE
[Suggestion] Frontend Developer

### ISSUE THREAD

**Issue by OzzyTheGiant** [kamranahmedse/developer-roadmap#3067]
For Static Site Generators, Gridsome, although it still works, is not recommended in my opinion because it's been abandoned for almost three years and shows no signs of coming out of Beta. This left a lot of developers burned because we built a lot of websites with this tool, plus there are some bugs that still need to be addressed. I would say I don't recommend this at all for new projects, but may still be a good option for very simple sites, so maybe mark it with gray checkmark?

In it's place, I would recommend Astro as it recently hit 1.0, is backed by Vercel and other companies, and is framework agnostic. Much better DX in my opinion.

Also you could add Server Sent Events next to Web Sockets as they are an alternate way to receive a stream of data using just http requests as opposed to implementing an entire web socket server.

**Comment by kamranahmedse** [comment]
Thanks @OzzyTheGiant -- Gridsome is out. Astro and SSE were planned -- I just added them to the roadmap. It will be published in the coming release. Thank you!
