### ISSUE TITLE
[Suggestion] Frontend Developer

### ISSUE THREAD

**Issue by dominic-deantonio** [kamranahmedse/developer-roadmap#3087]
Flutter is now a viable option for creating desktop applications. Would recommend adding to the Frontend>Desktop Applications topic as an alternative to Electron.

https://flutter.dev/multi-platform/desktop

Thanks for the great work on roadmap.sh

**Comment by kamranahmedse** [comment]
This has been fixed and will be published in the coming release. Thank you 🙏
