### ISSUE TITLE
[Suggestion] Search for key terms

### ISSUE THREAD

**Issue by dfpera** [kamranahmedse/developer-roadmap#309]
Would be great to have search to some degree. Say I hear a technology while talking with some colleagues, but not sure where it falls in the roadmap. Being able to ctrl-f would be quite valuable.

**Comment by kamranahmedse** [comment]
These will be added on the website [roadmap.sh](https://roadmap.sh) instead of the repository in the coming weeks after we are done with the 2020 release. Thank you 🙏
