### ISSUE TITLE
UX feature request

### ISSUE THREAD

**Issue by Mahmoudgalalz** [kamranahmedse/developer-roadmap#3094]
Hello, I found it so daisy to mark the things that I complete I have to click on it
then I look for the marking button, I just want to mention that I discovered it after I decided to build an copy to track my progress.

My recommendations, is to make a progress bar for more engagement, we can use the Local storage for that but it will be not good enough as we need to track that progress over many devices, I know there's maybe limitations as these required a back end services.

But the small change will make different rn is to easy marking the topic

maybe two click or hold or left click. 

so I'm working currently on this and let me know if it's okay to send the PR

**Comment by kamranahmedse** [comment]
We plan on launching accounts in Q1 2023. Progress will then be tied to the user profiles. Stay tuned!

PS, [let me know](mailto:kamranahmed.se@gmail.com) if you want to contribute to that.
