### ISSUE TITLE
Suggesting : What about phonegap ?

### ISSUE THREAD

**Issue by Alex-Werner** [kamranahmedse/developer-roadmap#31]
Hi ! 

Might be a stupid suggestion but what about phonegap/cordova, which could be seen as front dev (I personnaly use that with Angular or React for exemple), and that will extent some research over NodeJS (for automatisation, build etc..) and little knowledge of what is an APK for exemple and how to sign it/ship it.

**Comment by ppihus** [comment]
The name of the chart is _Roadmap to becoming a **web** developer in 2017_.

I believe that until it's focused for web, there is no place for mobile apps here, even if they are sharing some of the technologies.

**Comment by kamranahmedse** [comment]
@Alex-Werner Thank you for reporting; it could be but it isn't :) I wouldn't want to convolute it. However, feel free to create a PR with a separate file for "mobile" maybe.
