### ISSUE TITLE
Add FuseBox to bundlers

### ISSUE THREAD

**Issue by nchanged** [kamranahmedse/developer-roadmap#311]
It will be only fair to add FuseBox, we’ve been around for 1 year already 
fuse-box.org

**Comment by kamranahmedse** [comment]
Thank you for opening the issue. While I agree with that, we don't want to convolute the roadmap by mentioning every available option and are just focusing on what is the most relevant item that you would pick today and mentioned item doesn't conform to that. This has also been [mentioned in the contribution docs](https://github.com/kamranahmedse/developer-roadmap/blob/master/contributing.md#guidelines). Thank your for your suggestion though 🙏
