### ISSUE TITLE
[Suggestion] DevOps Roadmap

### ISSUE THREAD

**Issue by volenbovsky** [kamranahmedse/developer-roadmap#3118]
Hi,
I have few suggestions: 

1) Remove:
`airmon` and `airodump`

Reason: those are fairly "niche" utilities

2) Remove `mtr`
Reason: it is OK to know traceroute and ping

2) Change `ufw` to `ufw/firewalld`
Reason: `firewalld` is firewall manager in Fedora derivatives

3) Change `iptables` to `iptables/nftables`

4) Merge HTTPS with `SSL/TLS`, making it `HTTPS/TLS`

5) Replace `FTP` with `SFTP`

6) Remove `egrep/fgrep`, because there are `grep -E` and `grep -F`

7) Change `CentOS`, `Fedora` `RHEL` to `RHEL/derivatives (e.g.AlmaLinux), Fedora`
Reason: CentOS going to Stream makes AlmaLinux/RockyLinux a free alternative to RHEL

8) Group `Ubuntu` and `Debian` to `Ubuntu/Debian`

More controversial: 

3) Potentially to be removed:
-Mesos
-Salt (which should be SaltStack)
-Caddy 
-Unix (entire section)
Reason: too low adoption.

4) 
-Remove Rust, C, C++
-Potentially remove `Javascript/Node.js` and maybe `Ruby`...

Reason: it doesn't fit well to **DevOps** Roadmap
(Bash,Python is much-much more important in this context, Go will stay because of Kubernetes)

**Comment by kamranahmedse** [comment]
Thank you for the suggestions. We have taken some of your feedback into the consideration. 
Changes will be published in the coming release. Thank you 🙏
