### ISSUE TITLE
Go Lang

### ISSUE THREAD

**Issue by gueroverde** [kamranahmedse/developer-roadmap#312]
i readed "I have been experimenting lately with Go and I quite like it." but don't see go in backend roadmap

**Comment by kamranahmedse** [comment]
![image](https://user-images.githubusercontent.com/4921183/34660998-f4a27a4c-f45f-11e7-848d-86ee7cd166ab.png)


Looks like you missed that little box :)

**Comment by gueroverde** [comment]
I need glasses thank you very much hahaha
