### ISSUE TITLE
[Suggestion] QA Engineer

### ISSUE THREAD

**Issue by northern-tester** [kamranahmedse/developer-roadmap#3129]
_Ash's Notes - I think testability would be an excellent addition to the QA Roadmap, in the 'Learn the Fundamentals' section. I'm happy to do the PR, if it is considered an acceptable idea!_

# Testability

## What is testability

In its simplest form, testability is how easy a system is to test. This hides a lot of complexity but is a great starting point for a conversation. A testable system is one that enables a wide variety of testing types. From unit tests to exploratory testing. Plus other testing activities for specific needs such performance, security and accessibility.

## Why is it important

Testability is a vital property of modern software. It enables software teams to make changes rapidly and safely. With clear feedback loops to understand the impact of changes. Developers need it to put in place change with confidence. Testers need it to assess risk and provide actionable information. With better testability product management can experiment with features for feedback.

## How do you know if something is testable

* You are in control of the amount of feedback your product gives you. Allowing either a deep, detailed view or a wide, shallow view. Rather than trying to parse what your product is doing, it will tell its story.
* The product can be set into a state of your choosing, whether that be data or configuration. Allowing you to develop your product with much more certainty.
* After release, you are not dreading the call from support that your customers are unhappy. Monitoring, alerting and metrics mean any problems are seen early and managed proactively.

Watch - A Super Quick Guide to Testability by Nicola Lindgren <https://www.youtube.com/watch?v=IPtlaOSuX88>

Read - Untangling Testability by Rob Meaney <https://teatimewithtesters.com/untangling-testability/>

Read - Testability and how to improve it by Alex Romanov <https://alexromanov.github.io/2022/08/14/what-is-testability/>

Watch - Architecting for Testability by Emily Bache <https://www.youtube.com/watch?v=pybZziC7y2o>

Act - 30 Days of Testability by Ash Winter and Rob Meaney <https://www.ministryoftesting.com/dojo/lessons/30-days-of-testability?s_id=13945699>

**Comment by kamranahmedse** [comment]
Hey there!

Looks like this issue has been hanging around for a bit without much action. Our roadmaps have evolved quite a bit since then, and a bunch of older issues aren't really applicable anymore. So, we're tidying things up by closing out the older ones to keep our issue tracker nice and organized for future feedback.

If you still think this problem needs addressing, don't hesitate to reopen the issue. We're here to help!

Thanks a bunch!
