### ISSUE TITLE
[Suggestion] iOSDeveloper

### ISSUE THREAD

**Issue by KanishkVijaywargiya** [kamranahmedse/developer-roadmap#3133]
Can u pls bring the roadmap for an iOS developer as well.

**Comment by kamranahmedse** [comment]
We are now closing any issues requesting new roadmap requests to clean up the issues. 

However, this doesn't mean that the requested roadmap won't be added to the website. We are putting it in the backlog and will add it to the website depending on how it ranks in the backlog or sooner if we find someone interested in adding that roadmap. Thank you for the request though! 🙏
