### ISSUE TITLE
[Suggestion] Backend Developer

### ISSUE THREAD

**Issue by Anas-Nabulsi** [kamranahmedse/developer-roadmap#3140]
Add MVC architectural pattern.

**Comment by kamranahmedse** [comment]
This has been fixed and will be published in the coming release. Thank you 🙏

Design and Architectural principles are mentioned in-depth in the [Software Design and Architecture](https://roadmap.sh/software-design-architecture) roadmap, so we have linked to it instead.

<img width="1057" alt="image" src="https://user-images.githubusercontent.com/4921183/209133794-04b4694f-432d-4ee0-af56-4d72fafb7225.png">
