### ISSUE TITLE
[Suggestion] GraphQL

### ISSUE THREAD

**Issue by smyrick** [kamranahmedse/developer-roadmap#3147]
These lines are drawn to the wrong sides, they should be flipped. Relay and Apollo Client are Frontend Frameworks

![Screenshot 2022-12-19 at 10 02 06 AM](https://user-images.githubusercontent.com/2446877/208490590-5ed7bcc5-3335-4878-b613-4fdefd199598.jpg)

**Comment by kamranahmedse** [comment]
Fixed in https://github.com/kamranahmedse/developer-roadmap/commit/be8c82974fbf43608a72e79fca66042012b7622d -- thank you for reporting!
