### ISSUE TITLE
Game development path

### ISSUE THREAD

**Issue by georgeFulgeanu** [kamranahmedse/developer-roadmap#317]
I think if any game developers see this they could add their key topics to it.

**Comment by arnaudmorisset** [comment]
Miloyip do something similar: https://github.com/miloyip/game-programmer

Maybe it can be fun to make a Web Game Development path? 🙂

**Comment by kamranahmedse** [comment]
I can't vouch for the quality of it but there is this game developer roadmap https://github.com/utilForever/game-developer-roadmap maintained by the community
