### ISSUE TITLE
[bug] Backend Developer

### ISSUE THREAD

**Issue by 3r3bu5** [kamranahmedse/developer-roadmap#3171]
Apparently,
 Whenever I press on (**Kafka**) Section still get the (**RabbitMQ**) Resources Modal.
![backend](https://user-images.githubusercontent.com/33455548/209411162-1844f718-85c1-4774-91e4-cd34ae635012.gif)

**Comment by shantanupade** [comment]
Hey, I would like to take this issue. Can you assign this to me?

**Comment by kamranahmedse** [comment]
This has been fixed and will be published in the coming release. Thank you 🙏
