### ISSUE TITLE
Enzyme should be linked to React

### ISSUE THREAD

**Issue by francisc0j0shua** [kamranahmedse/developer-roadmap#318]
Enzyme should be linked to React not to Javascript testing section. 

According to the Enzyme's [README](https://github.com/airbnb/enzyme/#enzyme): "Enzyme is a JavaScript Testing utility for React that makes it easier to assert, manipulate, and traverse your React Components' output."

**Comment by franciscodjosh** [comment]
And Enzyme should be removed from NodeJS testing section as well.
