### ISSUE TITLE
Why download button on roadmap takes me to subscribe page

### ISSUE THREAD

**Issue by noahweasley** [kamranahmedse/developer-roadmap#3182]
I wanted to save the roadmap locally for now but when I clicked the download button it tells me to put my email ( which I did ), but it told me that I had already subscribed, which isn't what I was trying to do. Please is this a bug or is this the normal behaviour ?

**Comment by kamranahmedse** [comment]
Hey, this workflow will be fixed in the coming release by mid-January. 

Here are the PDF links for now https://roadmap.sh/pdfs
