### ISSUE TITLE
[Suggestion] Frontend Developer

### ISSUE THREAD

**Issue by patrickudo2004** [kamranahmedse/developer-roadmap#3193]
I love and recommend this resource to everyone I know that is interested in IT. Can it be possible for an average timeline to crested for this path. Like 2 weeks for HTML, 2 weeks for CSS and so on? Thanks!

**Comment by kamranahmedse** [comment]
Thank you for the suggestion Patrick but we don't want to make it more intimidating than it already is. 

Everyone learns differently at their on pace; factors such as your existing knowledge and skills, learning style, and available time can all affect the speed at which you progress through the materials. Putting the time will just put extra pressure on the people following it
