### ISSUE TITLE
DevOps part lack of precision

### ISSUE THREAD

**Issue by eagleusb** [kamranahmedse/developer-roadmap#32]
Hello there, I'm picky but the DevOps part fails at some point.

1. Cloud > ~Google App Engine~ Google Cloud Platform
1. We probably want to seperate PaaS (Heroku...) and IaaS (AWS, Azure GCP)
1. The Monitoring part lack of Grafana, Kibana and all tools gravitating around ELK stuff
1. By containers you mean only the runtime, which is only one part
1. We can easily add strace, dtrace, systemtap... for system calls debugging in command tools

The list can be long and I don't know how to handle that, can we define a method of suggestion, by categories or something ?

**Comment by kamranahmedse** [comment]
Hi @gooodmorningopenstack this is because of lack of my knowledge in DevOps part. Could you or anyone looking at this open a PR for this. Or list down the relevant groupings and I will update it accordingly.

Thank you.

**Comment by Gmacky2** [comment]
Categories

**Comment by Davidrums** [comment]
DevOps should also have read "The Phoenix Project" and have internalised the three ways of DevOps. Right now this roadmap is just a map to becoming an operations person.

Granted having good Ops knowledge is important it is not the key characteristic of a good DevOp

The three ways:
1. The way of flow.
2. The way os feedback.
3. The way of continuous experimentation and learning.

**Comment by gooodmorningopenstack** [comment]
Totally agree with that, but even for operations person this map is simplistic. We can try to add at least the good categories and some tools as example.

**Comment by k4ml** [comment]
I suggest renaming DevOps to just Ops. Making it separate suggesting it is a distinct field or role while it's more of a culture, which should be embraced by both dev and ops (hence devops).

**Comment by kamranahmedse** [comment]
There have been changes made to that section which makes this issue outdated. Thank you for reporting though 🙏

**Comment by 030** [comment]
I agree with @k4ml. DevOps is a culture and not a role. @kamranahmedse Could

> DevOps Roadmap
> Step by step guide for DevOps or any other Operations Role

be changed to:

```
> Ops Roadmap
> Step by step guide for an Operations Role
```

Apart from this, I like the roadmap.
