### ISSUE TITLE
Add estimated time to spend  on each topic

### ISSUE THREAD

**Issue by SherlockHolmes2022** [kamranahmedse/developer-roadmap#3224]
For each topic you already added a 'TickMark' like that can you add how much average time to spend to each topics (based on your experience) . So in that way beginner like me will find it easy to plan the roadmap out. Otherwise sometimes it's overhwhelming when you look at the roadmap and don't know how to approach it.

**Comment by kamranahmedse** [comment]
Thank you for the suggestion but we don't want to make it more intimidating than it already is.

Everyone learns differently at their on pace; factors such as your existing knowledge and skills, learning style, and available time can all affect the speed at which you progress through the materials. Putting the time will just put extra pressure on the people following it.

**Comment by kamranahmedse** [comment]
Regarding making it less intimidating for developers, we plan on launching something for that soon. Stay tuned!
