### ISSUE TITLE
Add Yii Framework to PHP Path

### ISSUE THREAD

**Issue by sebathi** [kamranahmedse/developer-roadmap#324]
I think is the best PHP Framework for RAD. Lots of features / great doc / Fast.

**Comment by sparxbpoit** [comment]
Zend is better than Yii as per my suggestion.

**Comment by kamranahmedse** [comment]
Thank you for opening the issue. While I agree with that, we don't want to convolute the roadmap by mentioning every available option and are just focusing on what is the most relevant item that you would pick today and mentioned item doesn't conform to that. 

This has also been [mentioned in the contribution docs](https://github.com/kamranahmedse/developer-roadmap/blob/master/contributing.md#guidelines). Thank your for your suggestion though 🙏
