### ISSUE TITLE
Suggestions : RoadMap for UI/UX

### ISSUE THREAD

**Issue by mirameshs** [kamranahmedse/developer-roadmap#3250]
hello
is this possible to draw a roadmap for a UI/UX specialist?
looking at a roadmap, a person makes his mind clear and he can understand what to do.
please, draw a roadmap for UI/UX

**Comment by kamranahmedse** [comment]
We are now closing any issues requesting new roadmap requests to clean up the issues. 

However, this doesn't mean that the requested roadmap won't be added to the website. We are putting it in the backlog and will add it to the website depending on how it ranks in the backlog or sooner if we find someone interested in adding that roadmap. Thank you for the request though! 🙏
