### ISSUE TITLE
[Bug] Git node in Backend roadmap display null

### ISSUE THREAD

**Issue by ahmadshalabi** [kamranahmedse/developer-roadmap#3262]
**How to reproduce:**
1- Go to https://roadmap.sh/backend/
2- Click on the Git node
3- Observe the content
![Screenshot from 2023-01-07 16-53-16](https://user-images.githubusercontent.com/8797792/211154216-55babcd1-6a66-498a-9cf5-0a60d0510a22.png)

**Comment by kamranahmedse** [comment]
This has been fixed and will be published in the coming release. Thank you 🙏
