### ISSUE TITLE
Kotlin

### ISSUE THREAD

**Issue by kardasz** [kamranahmedse/developer-roadmap#327]
How about Kotlin? In my opinion is a promising language. Good choice in 2018 for backend. https://kotlinlang.org/docs/reference/server-overview.html

**Comment by git-oca** [comment]
Kotlin or Scala Or Haskell, I don't really care, but Function programming seems to be missing...

**Comment by mlvandijk** [comment]
Tools for Kotlin:
Unit testing: KotlinTest, Spek
Matchers: HamKrest
(NB more on the Kotlin website)

**Comment by Mifrill** [comment]
dup of #410
