### ISSUE TITLE
[Suggestion] DevOps Roadmap

### ISSUE THREAD

**Issue by kaazuk1987** [kamranahmedse/developer-roadmap#3271]
Why c/c++ dissapeared last month??

**Comment by kamranahmedse** [comment]
Because C/C++ aren't as common as the other listed options when it comes to DevOps. Also we are trying to make these roadmaps less convoluted; mentioning every possible options isn't the goal.

**Comment by kaazuk1987** [comment]
Thx for answer. Generally these roadsmaps are very good idea.
