### ISSUE TITLE
Software Architect Roadmap PDF link is broken

### ISSUE THREAD

**Issue by bedr0** [kamranahmedse/developer-roadmap#3275]
Dear team, 

First of all, I would like to thank you for the great resources source you have been able to gather, but the PDF link for the Software Architect Roadmap (https://roadmap.sh/pdfs/software-architect.pdf) is taking me to a "Page not found!" error page. Could you please take a look?

![image](https://user-images.githubusercontent.com/68359845/211346893-6da23793-162c-4225-95a8-b54a60a08e50.png)

Kind regards, 
Pedro Harutunian

**Comment by kamranahmedse** [comment]
Fixed in https://github.com/kamranahmedse/developer-roadmap/commit/26125fc6d7433f3ba2c1be14c9233cee3c742ff6, thanks Pedro 🙏

**Comment by bedr0** [comment]
> Fixed in [26125fc](https://github.com/kamranahmedse/developer-roadmap/commit/26125fc6d7433f3ba2c1be14c9233cee3c742ff6), thanks Pedro 🙏

Thanks for the quick reply and fix Kamran, have a nice day!
