### ISSUE TITLE
[Bug] Download button redirects to email subscription page

### ISSUE THREAD

**Issue by odysseuskir** [kamranahmedse/developer-roadmap#3276]
This is a follow-up issue to #3182, which was marked as resolved 2 weeks ago.

When clicking on "Download" on the Python roadmap, I get asked to enter my email. After that, I get redirected to a subscription page and don't get the PDF on my email, which leads to the conclusion that the download button redirects to the email subscription page. Also, thanks for your awesome work!

**Comment by kamranahmedse** [comment]
This is expected. Once you confirm your email address on the subscription page, you will get an email with the link to the PDFs.
