### ISSUE TITLE
[Suggestion] iOS developer

### ISSUE THREAD

**Issue by monolithic-adam** [kamranahmedse/developer-roadmap#3280]
Would be great to add an iOS developer roadmap.

**Comment by fulgido** [comment]
Hi,
Completely agree with this suggestion. I want to contribute.

This can be the skeleton that can be used to create it. Suggestions are welcome, let me know.

- Pick a Language
  - Objective C
  - Swift
    - OOP
    - Control flow statement
    - Optional
    - Foundation framework
    - What is ARC
- Fundamentals
  - Version Control Systems
    - Git
  - Repository hosting services
    - GitHub
    - GiLab
  - Xcode
    - How to debug
    - What is Debug View Hierarchy?
    - What is Swift Playground?
  - Interface Builder & Storyboard
    - IBOutlet
  - Asset Management
  - Dependency Manager
    - CocoaPods
      - What is Podfile?
    - Carthage
    - SPM (Swift Pack Manager)
  - Human Interface Guidelines 
- Build Your First Application
  - Architectural Patterns
    - MVVM
    - MVC
    - MVP
  - Design Patterns
    - Delegate
    - Observer
    - Singleton
  - UIKit
    - User Interface (views and controls)
    - User Interactions (gesture recognition, motion detection...)
  - AutoLayout
  - Networking
    - How to call an API
    - get JSON data and parse it
  - CoreLocation, MapKit
  - Data Persistence
    - Realm
    - Keychain
    - CoreData
- Advanced Topics
  - Analytics, data storage and utilities
    - Firebase
  - XCTest
    - TDD
  - CI/CD
  - Push Notification
  - GDC (Grand Central Dispatch)
  - Swift UI
  - In-App Purchases
- More Advanced and Specific Topics
  - CoreML
  - ARKit
  - SpriteKit
- Publish
  - App Store
    - iTunes Store
    - Review guidelines
    - Testflight

**Comment by BrunoCerberus** [comment]
This image might help

![iOS Developer RoadMap-2](https://user-images.githubusercontent.com/10541956/212920794-c2117033-3d18-4e93-8fe9-f831e8292435.png)

source: https://javarevisited.blogspot.com/2022/05/ios-developer-roadmap.html#axzz7qezaAVht

**Comment by BrunoCerberus** [comment]
And it's missing SwiftUi stuff like:
- Combine
- State management
- life cycle views

**Comment by BrunoCerberus** [comment]
For SwiftUI, I highly recommend this apple [course](https://developer.apple.com/tutorials/app-dev-training#resources)
and this [course](https://www.pointfree.co/episodes/ep214-modern-swiftui-introduction) from [Pointfree](https://github.com/pointfreeco)

**Comment by fulgido** [comment]
Hi @BrunoCerberus , thank you for the hint!

I just saw that roadmap, but maybe there are too much arguments for a beginner? 

I try to reduce it like the android roadmap. But feel free to integrate or edit my comment with other fundamental topics are life cycle views and state management 🙌🏻  Or when I have a slot of time I can integrate it

**Comment by fulgido** [comment]
I edited the comment with the skeleton of iOS Developer Roadmap

**Comment by fulgido** [comment]
Up

**Comment by monolithic-adam** [comment]
ah! I made this issue and then completely forgot to checkup on it. Great work guys! 👍

**Comment by TRohit20** [comment]
Hey guys, I'd love to contribute to this issue and build a roadmap for IOS. Is the issue still open?

Can the maintainers assign the issue to me so We can get started to work on building it ? Thankyou.

**Comment by fulgido** [comment]
I think is still open. We write a first skeleton about the roadmap (the second comment) that can be improve, but I don't know how we have to proceed

**Comment by TRohit20** [comment]
It's simple, if a project maintainer or so assigns the issue to us or one, we can fork the repo and build the roadmap and open a pull request when we are done specifying the issue we close. But assigning is required as to not collide with someone who is already working on it or so.

**Comment by fulgido** [comment]
Well, thank you for explain. @kamranahmedse can you assign this issue to @TRohit20 ?

**Comment by SooshMeow** [comment]
Would also love to see this addition. I see many people lost with this path since the recent updates with SwiftUI making it harder for new developers to figure out what they should be looking at.

**Comment by Rychillie** [comment]
up

**Comment by ferdinand1995** [comment]
up

**Comment by bingoku** [comment]
Check this out，But it's Chinese
https://www.processon.com/v/64d49cb64e65c16610352aba

**Comment by huaweiluo** [comment]
> Well, thank you for explain. @kamranahmedse can you assign this issue to @TRohit20 ?

Hi, as an experienced iOS developer, I also would like to join to contribute to the iOS roadmap which is lack currently.
Could you assign this issue to me also? @kamranahmedse

**Comment by peterdsp** [comment]
Hi, I'm an iOS Engineer and I'm eager to contribute to this iOS roadmap initiative. Could you kindly assign this issue to me as well? @kamranahmedse

Thank you!

**Comment by seifer** [comment]
Up

**Comment by marcy731** [comment]
up

**Comment by akshay-99h** [comment]
Hi! Are there any updates on this? it has been a long standing issue but the swift/ios developer roadmap does not seem to be added to the main website. I am planning on learning swift. I am a fullstack web developer planning on getting started with iOS development. Roadmap.sh has always been my favourite website to get appropriate roadmaps. Any information on this will be appreciated.

Thank you!👨‍💻😇

**Comment by shadycyan** [comment]
up

**Comment by IsmaelMiber** [comment]
UP

**Comment by ThangLe9804** [comment]
Up

**Comment by kamranahmedse** [comment]
Hey there!

Looks like this issue has been hanging around for a bit without much action. Our roadmaps have evolved quite a bit since then, and a bunch of older issues aren't really applicable anymore. So, we're tidying things up by closing out the older ones to keep our issue tracker nice and organized for future feedback.

If you still think this problem needs addressing, don't hesitate to reopen the issue. We're here to help!

Thanks a bunch!

**Comment by n0nuser** [comment]
In case someone comes later to this issue, this is the corresponding roadmap for [IOS development](https://roadmap.sh/ios).
