### ISSUE TITLE
Add FuelPHP - Framework

### ISSUE THREAD

**Issue by GabrielCoelho** [kamranahmedse/developer-roadmap#329]
As a minor priority in PHP -> Frameworks path. 
I know that Fuel isn't integrated with PHP7, **but it claims itself as a PHP 5.3+ Framework**.

It have some integrated packages like the [ORM](https://fuelphp.com/docs/packages/orm/intro.html), [AUTH](https://fuelphp.com/docs/packages/auth/intro.html) and [OIL](https://fuelphp.com/docs/packages/oil/intro.html).

**Comment by kamranahmedse** [comment]
Thank you for opening the issue. While I agree with that, we don't want to convolute the roadmap by mentioning every available option and are just focusing on what is the most relevant item that you would pick today and mentioned item doesn't conform to that. 

This has also been [mentioned in the contribution docs](https://github.com/kamranahmedse/developer-roadmap/blob/master/contributing.md#guidelines). Thank your for your suggestion though 🙏
