### ISSUE TITLE
Add Uikit

### ISSUE THREAD

**Issue by pfcodes** [kamranahmedse/developer-roadmap#330]
I love Semantic-UI, but it's really poorly maintained. When I first started coding it was my go-to, but then I realized update intervals are lengthy. Uikit3 on the other hand, is regularly updated and I believe is very fun to work with. I propose adding UIKit to the list.

**Comment by kamranahmedse** [comment]
Thank you for opening the issue. We don't want to convolute the roadmap by mentioning every available option and are just focusing on what is the most relevant item that you would pick today and the mentioned item doesn't conform to that. 

This has also been [mentioned in the contribution docs](https://github.com/kamranahmedse/developer-roadmap/blob/master/CONTRIBUTING.md#guidelines). 
Thank you for your suggestion though 🙏
