### ISSUE TITLE
What about choosing a recognized open source license for the project (code/knowledge)

### ISSUE THREAD

**Issue by raf64flo** [kamranahmedse/developer-roadmap#3332]
Hello here,

I've discovered the project and was happy to go through roadmaps, it's a great initiative I was about to contribute to, in the open source sprirt, as stated on the [website](https://roadmap.sh/) main page: 

> Open Source
>
> The project is **OpenSource**, [6th most starred project on GitHub](https://github.com/search?o=desc&q=stars%3A%3E100000&s=stars&type=Repositories) and is visited by hundreds of thousands of developers every month.

Just before that, I went to look at the [project's license](https://github.com/kamranahmedse/developer-roadmap/blob/86a1a4a078eddf154872d1671013cd13eee61142/license) and I discovered it is not open source at all, for the source code according to the [definition given by OSI](https://opensource.org/osd) as well as for the knowledge/documentation in the spirit of the [Creative Commons](https://creativecommons.org/faq/#what-is-creative-commons-and-what-do-you-do).

It looks to me it is untruthful to state this is an open source project where there are clear restrictions on how to reuse and redistribute the content collaboratively produced.

The project would benefit a lot to clearly use an [OSI license](https://opensource.org/licenses) for the source code and [CC license](https://creativecommons.org/share-your-work/) for the knowledge.

There are several discussions[^1]  [^2] on this topic, none of them being answered at the time of writing.

What is your opinion about that @kamranahmedse?

[^1]: https://github.com/kamranahmedse/developer-roadmap/discussions/2942
[^2]: https://github.com/kamranahmedse/developer-roadmap/discussions/2914

**Comment by serzhan181** [comment]
Good point.

**Comment by danielabai** [comment]
Interesting

**Comment by raf64flo** [comment]
I understand the choice you have made for licensing the project, but as stated above, it does not comply with any open source licenses.

Hence, the banner at the bottom of the website is not relevant at all and is misleading users/collaborators.

Could you please remove it to not be untruthful?
