### ISSUE TITLE
[Suggestion] Security roadmap

### ISSUE THREAD

**Issue by dogpunk** [kamranahmedse/developer-roadmap#334]
Hi, I really love this repo, but what is missing is a good security roadmap for newbies - maybe based on this source https://github.com/jesusprubio/strong-node ?

**Comment by rakeshhny** [comment]
+1.

**Comment by Ayman97** [comment]
+1000

**Comment by nirmaljosehere** [comment]
+1

**Comment by git-oca** [comment]
but who cares about security these days ;)
Jokes apart, having a security roadmap will be for sure a great addition!

**Comment by fropert** [comment]
Fantastic job @kamranahmedse  !
https://snyk.io/ and https://help.github.com/articles/about-security-alerts-for-vulnerable-dependencies/ are amazing resources to detect vulnerabilities in dependencies.

Francois (Fortinet product security team)

**Comment by kamranahmedse** [comment]
New roadmap requests are being tracked through [roadmap.sh](https://github.com/kamranahmedse/roadmap.sh). Thank you!
