### ISSUE TITLE
[Suggestion] Frontend Performance

### ISSUE THREAD

**Issue by thisismairaj** [kamranahmedse/developer-roadmap#3357]
Add use webp image format as a good practice. Webp images are faster and lightweight than jpg or png.

**Comment by kamranahmedse** [comment]
We have a note for that -- details will be added in the popup

<img width="292" alt="image" src="https://user-images.githubusercontent.com/4921183/214550329-5af5d46c-7bd9-482e-b44f-71738a579c23.png">
