### ISSUE TITLE
Angular Js is framework whereas React is a Library. Place them in different buckets.

### ISSUE THREAD

**Issue by mohitsharma1750** [kamranahmedse/developer-roadmap#336]

**Comment by kevinZepeda** [comment]
thats real, upvote this

**Comment by jvitoroc** [comment]
I don't think it will add anything meaningful.

**Comment by pauldraper** [comment]
This is the graph that puts entirely difference languages (C#, Java, and Go) in the same bucket; I don't think there is fine grained categorization ;)
