### ISSUE TITLE
Roadmap for Typescript

### ISSUE THREAD

**Issue by ShuoShenDe** [kamranahmedse/developer-roadmap#3368]
- Introduction to TypeScript
  - What is TypeScript?
  - History of TypeScript
  - TypeScript Versions
  - How to Run TypeScript
  - Difference with JavaScript
- All about Variables
  - Rules for naming variables
  - Ambient Declarations
  - Declaration Space
      - Variable Declarations
          - var
          - let
          - const
      - Structural
- Modules
    - Global Module
    - File Module
        - import
        - export 
- Data Types
  - Primitive Types
    - string
    - number
    - boolean
    - void
    - symbol
    - null
    - undefined
    - any
    - never
  - Class
    - methods
    - constructors
    - blocks
    - nested classes
    - abstract class
    - interfaces
- Member Visibility
    - public
    - protected
    - private
    - readonly
- Data Structures
    - Queue
    - Graph
    - Stack
    - Linked list
    - Vector
    - Hash table
    - Enum
- Function
  - Named Functions
  - Anonymous Function
      - Arrow Functions
  - Parameters
      - Function Parameters
      - Optional Parameters
      - Default Parameters
      - Function Overloading
  - Rest Parameters
  - Function Overloading
- Loops and Iteration
  - for loop
  - for...in loop
  - for...of loop
  -  while loop
  - do while loop
- Control Flow
  - Conditional Statements
    - Ternary operator
    - if...else
    - switch...case
    - try / catch / default
    - then
    - return
- Asynchronous TypeScript
  - Promise
  - callbacks / callback hell
  - async/await
- Iterators and Generators
- Dynamic Import Expressions
- @types
- modules in TypeScript
    - Common JS vs ESM
- Compilation Contex (tsconfig.json)

**Comment by kamranahmedse** [comment]
Thanks @ShuoShenDe we have the [TypeScript roadmap live](https://roadmap.sh/typescript).
