### ISSUE TITLE
Add Tool branch

### ISSUE THREAD

**Issue by zhongqin0820** [kamranahmedse/developer-roadmap#338]
I think know how to good at use these tools is as important as the knowledge and should be regard as a resource

1. Editor || IDE
- Vim
- Emacs
- Sublime
- Atom
- VSCode
- WebStorm
- etc...

2. Debug Tool
- Google Chrome Develooper Tool
- etc...

3.  Terminal || Shell
- iTerm
- bash
- zsh
- oh-my-zsh
- etc...

**Comment by kamranahmedse** [comment]
Thank you for opening the issue. While I agree with that, we don't want to convolute the roadmap. However, I will see if we can mention this somewhere in textual form. Thank you 🙏
