### ISSUE TITLE
Reading List?

### ISSUE THREAD

**Issue by Daniel-Yonkov** [kamranahmedse/developer-roadmap#339]
Sorry if this is a repeated topic, I coudn't find the previous one if such exists =].
Maybe adding a reading list on all the possible technologies with good (mind opening) effect on the readers (proven reading list) by people and reference for the newcommers =].
As a start, my recommendation for OOP and Design Patterns with the PHP technology - PHP, Object, Patterns and Practices.

Hope you like the idea,
Kr,
Dany

**Comment by kamranahmedse** [comment]
These will be added on the website [roadmap.sh](https://roadmap.sh) instead of the repository in the coming weeks after we are done with the 2020 release. Thank you 🙏
