### ISSUE TITLE
add canvas as front-end drawing tool

### ISSUE THREAD

**Issue by chan24092005** [kamranahmedse/developer-roadmap#340]
canvas should be added as a front-end drawing tool
https://developer.mozilla.org/en-US/docs/Web/API/Canvas_API

**Comment by kamranahmedse** [comment]
Thank you for opening the issue. While I agree with that, we don't want to convolute the roadmap by mentioning every available option. 

This has also been [mentioned in the contribution docs](https://github.com/kamranahmedse/developer-roadmap/blob/master/contributing.md#guidelines). Thank your for your suggestion though 🙏
