### ISSUE TITLE
[Suggestion] Node.js Developer (Invalid link)

### ISSUE THREAD

**Issue by nmonastyrskyi** [kamranahmedse/developer-roadmap#3416]
### Steps to reproduce:
Open https://roadmap.sh/nodejs > Event Emmiter > First link
<img width="1368" alt="image" src="https://user-images.githubusercontent.com/29196596/216904279-eaee51ed-ae44-4df8-aa91-14ca70234a99.png">
### AR: 
Invalid link:
https://nodejs.org/en/knowledge/getting-started/control-flow/what-are-event-emitters/
### ER:
Valid link:
https://nodejs.dev/en/learn/the-nodejs-event-emitter/

**Comment by kamranahmedse** [comment]
Fixed, thank you!
