### ISSUE TITLE
Someone violating copyrights?

### ISSUE THREAD

**Issue by puttehi** [kamranahmedse/developer-roadmap#3425]
Just to share the information, seems like someone is blogging copy-pastes of your awesome work over at decipherzone.com blog. Not sure if there is much to be done about it and if it's covered by what licenses, but the graphics in the roadmap blog posts are quite clearly your graphs/roadmaps re-created as PDFs with their company watermark over it.

- [Blockchain](https://www.decipherzone.com/blog-detail/blockchain-roadmap)
- [DevOps](https://www.decipherzone.com/blog-detail/devops-roadmap)
- ...

Thanks for all you've done here. Roadmap.sh has been a great resource!

**Comment by kamranahmedse** [comment]
Thanks @puttehi -- I reached out to them and they have taken down the images 🙏
