### ISSUE TITLE
accounts

### ISSUE THREAD

**Issue by ImRohak** [kamranahmedse/developer-roadmap#3431]
An account system so we can save our progress data across multiple devices.

**Comment by howarddo2208** [comment]
+1, localstorage data will lose on other devices

**Comment by kamranahmedse** [comment]
With the recently launched accounts functionality, you can login to store your progress.

**Comment by howarddo2208** [comment]
> With the recently launched accounts functionality, you can login to store your progress.

Thank you so much! that's awesome
