### ISSUE TITLE
[Suggestion] Backend developer roadmap: add rate limiting, pagination and sorting to the API section

### ISSUE THREAD

**Issue by genericdude1998** [kamranahmedse/developer-roadmap#3446]
It would be nice to add these topics as more about APIs, similar to what we have for the database. They are pretty common cases when developing an API and play an important role.

**Comment by kamranahmedse** [comment]
Thank you for the suggestion but that is intentional. Listing everything is not the goal. We might make a separate roadmap for APIs and include it there.
