### ISSUE TITLE
[Suggestion] Node.js Developer

### ISSUE THREAD

**Issue by mansoorulhaq** [kamranahmedse/developer-roadmap#3456]
I found that an important topic is missing in NodeJS roadmap that is related to scheduled tasks/jobs. it is often required to schedule different tasks/jobs in NodeJS application. To fulfill this requirement there are different NodeJS implementations. some of these implementations are backed by redis and others are in memory.

here is list of NodeJS modules for scheduling tasks/jobs:

Bull - a job queue library that supports scheduling of delayed jobs and recurring jobs.
https://www.npmjs.com/package/bull

BullMQ - a Redis-backed message queue for Node.js that is based on the Bull job queue library and provides additional features such as priority queues and throttling. 
https://www.npmjs.com/package/bullmq

Kue - a Redis-based priority job queue for Node.js that supports job dependencies, delay and retry of failed jobs, and graceful shutdown.
https://www.npmjs.com/package/kue
https://automattic.github.io/kue/

Bee-Queue - a Redis-backed job queue for Node.js that is designed for high-performance and supports features such as job progress tracking and timeouts
https://www.npmjs.com/package/bee-queue

Bree - a  job scheduler for Node.js and JavaScript with cron, dates, ms, later, and human-friendly support.
https://www.npmjs.com/package/bree

RedisSMQ - a Redis-based simple message queue for Node.js that supports message prioritization and multiple consumer groups.
https://www.npmjs.com/package/redis-smq

Node Schedule - a flexible cron-like and repeating task scheduler for Node.js.
https://www.npmjs.com/package/node-schedule

Later - a library that allows you to schedule jobs using a simple, human-readable syntax.
https://www.npmjs.com/package/@breejs/later

Node-cron - a simple cron-like job scheduler for Node.js that allows you to schedule jobs using cron syntax.
https://www.npmjs.com/package/node-cron

Node-resque - a Redis-backed job queue library that supports scheduling of jobs.
https://www.npmjs.com/package/node-resque

Nest-schedule - a module for scheduling tasks in NestJS applications that uses Node Schedule under the hood.
https://www.npmjs.com/package/nest-schedule

Agenda - a lightweight job scheduling library that allows you to define and schedule jobs to run at specific times or intervals. it has Mongo backed persistence layer.
https://www.npmjs.com/package/agenda

**Comment by kamranahmedse** [comment]
Hey there!

Looks like this issue has been hanging around for a bit without much action. Our roadmaps have evolved quite a bit since then, and a bunch of older issues aren't really applicable anymore. So, we're tidying things up by closing out the older ones to keep our issue tracker nice and organized for future feedback.

If you still think this problem needs addressing, don't hesitate to reopen the issue. We're here to help!

Thanks a bunch!
