### ISSUE TITLE
Please add a Java stack to the backend roadmap

### ISSUE THREAD

**Issue by ArtyomZoloto** [kamranahmedse/developer-roadmap#347]
I think it will be a good idea to add Java stack (Spring framework, hibernate, junit etc.) to the backend developer guide.

**Comment by prashantsharanit** [comment]
I agree.

**Comment by Aniruddha-Deb** [comment]
I have added one and sent a pull request for it.
<img width="751" alt="screen shot 2018-01-25 at 12 53 21" src="https://user-images.githubusercontent.com/14949866/35376106-9b41d51a-01cf-11e8-96df-5ad40785c98c.png">

**Comment by ArtyomZoloto** [comment]
Jboss now names as **WildFly**, please check it.

**Comment by kamranahmedse** [comment]
Hey, thanks for opening the issue but we are not intentionally expanding Java, Go or C# to keep it a little less messy and so there are no plans to add that.
