### ISSUE TITLE
Please add neo4j database & socket.io library

### ISSUE THREAD

**Issue by Eddie-CooRo** [kamranahmedse/developer-roadmap#349]

**Comment by git-oca** [comment]
graph database seems to be missing... I would add Neo4j and the recently announced AWS Neptune

**Comment by kamranahmedse** [comment]
Thank you for opening the issue. While I agree with that, we don't want to convolute the roadmap by mentioning every available option and are just focusing on what is the most relevant item that you would pick today and mentioned item doesn't conform to that. 

This has also been [mentioned in the contribution docs](https://github.com/kamranahmedse/developer-roadmap/blob/master/contributing.md#guidelines). Thank your for your suggestion though 🙏
