### ISSUE TITLE
[Suggestion] Frontend Developer - Adding Checkmarks 

### ISSUE THREAD

**Issue by GenieDex** [kamranahmedse/developer-roadmap#3523]
### Suggestion: Allow to track progress by adding checkmarks to the roadmap 
This roadmap is very complete and a great tool and guide. However, I want to suggest adding a way to checkmark the different objectives or to download the roadmap as a checklist in order to allow the user to use the roadmaps as a way to track their progress. 

Cheers!

**Comment by kamranahmedse** [comment]
With the recently launched accounts functionality, you can login to store your progress. Also, we do have the roadmap PDF that you can download and use to track your progress on paper.
