### ISSUE TITLE
Can we add full-stack developer into this roadmap?

### ISSUE THREAD

**Issue by hoangson85** [kamranahmedse/developer-roadmap#355]
Many companies are also hiring full-stack developers who should have knowledge in both frontend and backend.
If we can add that into this roadmap, then it will help others to understand how to become a full-stack developer.

**Comment by dogpunk** [comment]
Finish frontend and backend roadmap, there are no shortcuts :)

**Comment by Amorganskate** [comment]
Literally Full Stack = Front-End & Back-End road maps 

No reason for a full stack roadmap
