### ISSUE TITLE
[Frontend Developer] - Link is not working in resources section.

### ISSUE THREAD

**Issue by Sankhadip-Roy** [kamranahmedse/developer-roadmap#3568]
Frontend Developer -> Visit the Detailed Version -> JavaScript -> ES6+ and modular JavaScript -> Visit the following resources to learn more:
[Modern JavaScript ES6, ES7 & ES8](https://codeloop.org/learn-modern-javascript-es6-es7-es8) link not working.

Link: https://codeloop.org/learn-modern-javascript-es6-es7-es8

![Screenshot from 2023-03-11 13-19-43](https://user-images.githubusercontent.com/91897336/224472673-fc5d0a17-3988-4a5b-b2c6-c31e42acb8a3.png)

**Comment by Suryanshu1005** [comment]
the link is working perfectly fine 

![image](https://user-images.githubusercontent.com/59340699/224564745-520f1557-e155-4cb5-b43c-3c31cfb854db.png)

**Comment by Sankhadip-Roy** [comment]
Maybe that time the website was down.
