### ISSUE TITLE
[Suggestion] Cyber Security Expert

### ISSUE THREAD

**Issue by AbdelrhmanX7** [kamranahmedse/developer-roadmap#3569]
i think it should to say A+ not aplus
![image](https://user-images.githubusercontent.com/74682593/224477519-3699010c-046a-4425-bcaf-d2d0a0ad2dc1.png)

same thing happened with Linux+, Network+, Security+

**Comment by kamranahmedse** [comment]
This is an auto-generated placeholder content and will be replaced soon.
