### ISSUE TITLE
[Suggestion] TypeScript

### ISSUE THREAD

**Issue by Imshk** [kamranahmedse/developer-roadmap#3579]
Please add the prerequisite section in the roadmap of each topic (wherever it make sense ).
E.g I visited Typescript roadmap , and there was no such thing mention . I think it is good to mention the prerequisites. 

Add an box titled prerequisites  - Understanding of JavaScript fundamentals
                                                      ES6 features
                                                      Good understanding of HTML and CSS
                                                      Node.js and the npm package manager

**Comment by Imshk** [comment]
I would like to add this thing , assign me this task with Navigating address of the codebase .

**Comment by kamranahmedse** [comment]
Thank you for the suggestion but I don't think there is a need to mention that. Things that you have mentioned are already covered in the the roadmap nodes when you click them.
