### ISSUE TITLE
What does branching mean? Modular Parts or Alternatives?

### ISSUE THREAD

**Issue by ghost** [kamranahmedse/developer-roadmap#364]
Does the blue-dot-branching thing mean **several different modular parts** that you need, or does it mean **several alternatives**, or it can mean both? Is the following branching (attached screenshot) advising people to learn multiple backend platforms that basically serve the same purposes?
![screen shot 2018-01-27 at 1 11 26 am](https://user-images.githubusercontent.com/10406532/35469250-6deea620-02ff-11e8-9de0-0a56215bcdd9.png)

**Comment by sur0g** [comment]
It works like 'or' logic. You can choose one to proceed to the next node pick multiple before proceeding

**Comment by kamranahmedse** [comment]
Yes, I am working on the rewrite though. Frontend part is done and made a bit more clear. Backend will be done soon. Thank you for reporting.
