### ISSUE TITLE
Add codeigniter to PHP frameworks

### ISSUE THREAD

**Issue by savitoj98** [kamranahmedse/developer-roadmap#366]
Codeigniter claims itself as a PHP 5.3+ Framework.

**Comment by kamranahmedse** [comment]
Thank you for opening the issue. While I agree with that, we don't want to convolute the roadmap by mentioning every available option and are just focusing on what is the most relevant item that you would pick today and mentioned item doesn't conform to that. This has also been [mentioned in the contribution docs](https://github.com/kamranahmedse/developer-roadmap/blob/master/contributing.md#guidelines). Thank your for your suggestion though 🙏
