### ISSUE TITLE
No login in web page

### ISSUE THREAD

**Issue by stuta** [kamranahmedse/developer-roadmap#3660]
Web page shows subscribe but I'm already subscribed. I can't login.

**Comment by arikchakma** [comment]
Subscribing doesn't mean logging in here (currently); it means you've been subscribed to the newsletter.

**Comment by stuta** [comment]
How can I log in to the web page? Do I have to enter the same mail address every time and wait for the mail to come when I want to download some roadmap?

**Comment by arikchakma** [comment]
Currently, login functionality isn't available. If you try to download for the first time, you will have to input your email, and you'll receive an email with the download link of all of the roadmaps.
