### ISSUE TITLE
[Suggestion] VR/AR Developer or Machine Learning Engineer Roadmap Request

### ISSUE THREAD

**Issue by shad674** [kamranahmedse/developer-roadmap#3680]
Hi,

Lately I have been reading a lot about metaverse and AI news, and both of this fields are in good time to study.I am also interested in knowing a good roadmap for them. 

Thank you,

**Comment by kamranahmedse** [comment]
We are now closing any issues requesting new roadmap requests to clean up the issues. 

However, this doesn't mean that the requested roadmap won't be added to the website. We are putting it in the backlog and will add it to the website depending on how it ranks in the backlog or sooner if we find someone interested in adding that roadmap. Thank you for the request though! 🙏
