### ISSUE TITLE
Consider renaming and revising "Dive Deep CSS3" section

### ISSUE THREAD

**Issue by ivanjonas** [kamranahmedse/developer-roadmap#371]
In the front-end map, on the bottom-right, in yellow. I'm quite confused. The capitalization suggests that it's a technical term or title, and the words "dive deep" are usually encountered as "deep dive." 

I suspect that it means "Learn the advanced stuff offered by CSS3, such as..." referring to the items below. Just a label for a list. If that's the case, I recommend using a different visual. In every other list on the map, a grouping of boxes indicates "probably use only one of these per project; each one addresses the same general problem." But here, one is free to use all of these CSS3 properties and features in the same project.

I propose renaming that box to "Advanced CSS3" and taking the label out of the box and onto the blue arrow, just like the "Methodologies" label above it.

**Comment by kamranahmedse** [comment]
There have been changes made to that section which makes this issue outdated. Thank you for reporting though 🙏
