### ISSUE TITLE
Replace nodes that have separate roadmaps with links to that roadmap

### ISSUE THREAD

**Issue by woojiq** [kamranahmedse/developer-roadmap#3753]
Blue node means that there is a separate roadmap for that node, as shown in the figure (backend roadmap): 
![image](https://user-images.githubusercontent.com/122799969/229721011-84200359-0b45-45dc-8a97-49564c0441ec.png)
This is achieved with `ext_link`: `{"controlName":"ext_link:roadmap.sh/best-practices/api-security"}`
However, I found out that some of the new roadmaps don't integrate that way. For example, there is a roadmap for GraphQL and Kubernetes, but nodes are not using it (backend roadmap):
![image](https://user-images.githubusercontent.com/122799969/229721914-3c06bc5a-1725-4106-8e27-9d5b6742c834.png)
So my proposal is to replace all such nodes with "blue" if possible.
If you approve these changes I can try to do it, I have already done it for some nodes. It's worth noting that in this case references to existing resources will be removed, that is why I created the problem in the first place.

**Comment by kamranahmedse** [comment]
This has been fixed and will be deployed in the coming release. Thank you!
