### ISSUE TITLE
Software licences

### ISSUE THREAD

**Issue by dgncan** [kamranahmedse/developer-roadmap#38]
I think every developer should have an idea about software licenses.
This subject should be added to the beginning of the list.

**Comment by Tintress15** [comment]
How do you no when your license is good.

**Comment by dgncan** [comment]
It depends on your project. For example, when you make a commercial project, you need to know if the lib you use allows it.

**Comment by damengilland** [comment]
Thank you!  Totally agree here, when doing an audit one of the first things I ask is for a list of software licenses.  Far too often you have some obscure library using some random license that the creator wrote that says something outlandish like, "Must be used by friendly people..." and look from a legal perspective all of those libraries are junk and should be avoided.

- Apache License, Version 2.0 || http://www.apache.org/licenses/LICENSE-2.0 
- The BSD 3-Clause License | Open Source Initiative || https://opensource.org/licenses/BSD-3-Clause 
- The GNU General Public License v3.0 - GNU Project - Free Software Foundation || https://www.gnu.org/licenses/gpl-3.0.html
- The MIT License (MIT) | Open Source Initiative || https://opensource.org/licenses/MIT

**Comment by PeterMTaylor** [comment]
If these common licenses are indicated on your Roadmap, this makes a useful reference.

**Comment by ivuorinen** [comment]
One way to solve this would be linking to a site like https://choosealicense.com

**Comment by kamranahmedse** [comment]
There have been changes made to that section which makes this issue outdated. Thank you for reporting though 🙏

**Comment by eddiejm007** [comment]
Can you stop sending these out srsly
