### ISSUE TITLE
[Suggestion] Cyber Security Expert

### ISSUE THREAD

**Issue by santitodisco97** [kamranahmedse/developer-roadmap#3814]
I'm not being able to download roadmaps. It seems like something was updated and i can't mark things as Completed when right-clicking a box

**Comment by santitodisco97** [comment]
And i'm getting "failed to fetch" when trying to mark a box as Completed

**Comment by kamranahmedse** [comment]
@santitodisco97 we have added accounts functionality and right-click functionality has been disabled for now. Can you please try it in incognito. Also if you could look at the browser console for any errors?

**Comment by santitodisco97** [comment]
Yes, of course. I'll let you know if I found something.
