### ISSUE TITLE
Roadmap Suggestion - RUST

### ISSUE THREAD

**Issue by sushantAT144** [kamranahmedse/developer-roadmap#3823]
Can we add the Rust language roadmap too?

Rust online community is super helpful and I'm sure they would like to feature Rust in here, They will also give tons of suggestions on the proper steps for this roadmap.

**Comment by anhnmt** [comment]
+1

**Comment by dongdongkuang123** [comment]
+1

**Comment by kevinyin9** [comment]
Please refer to issue #4499.
