### ISSUE TITLE
[Suggestion] PostgreSQL DBA

### ISSUE THREAD

**Issue by robinportigliatti** [kamranahmedse/developer-roadmap#3834]
Hello,

In Query Analysis you should talk about [PEV2](https://github.com/dalibo/pev2) instead of PEV. [PEV](https://github.com/dalibo/pev2#disclaimer) project seems to be abandonned.

You should talk about [explain.dalibo.com](explain.dalibo.com) when talking about PEV2.

Data partitionning and Sharding should not be on the same level. The first is basic and the other one is an advanced concept.

In Log Analysis, you should also talk about [pgCluu](https://pgcluu.darold.net/) from Gilles Darold.

In migration tools you should talk about [ora2pg](https://ora2pg.darold.net/) from Gilles Darold.

Edit: You should also talk about [check_pgactivity](https://github.com/OPMDG/check_pgactivity), [temboard](https://labs.dalibo.com/temboard), [check_pgbackrest](https://github.com/pgstef/check_pgbackrest) in Monitoring.

As for Develop Infrastructure skills you could talk about [pglift](https://gitlab.com/dalibo/pglift) and its ansible collection.

You can also create a topic about anonymisation with [PostgreSQL anonymizer](https://labs.dalibo.com/postgresql_anonymizer)

You should talk about terraform and not only docker.

Robin,

**Comment by robinportigliatti** [comment]
You should also talk about check_pgactivity in Monitoring.

**Comment by kamranahmedse** [comment]
Thank you -- that was really helpful. Updates have been made.
