### ISSUE TITLE
[Suggestion] API Security Best Practices

### ISSUE THREAD

**Issue by josephting** [kamranahmedse/developer-roadmap#3836]
I'm looking for information that expands on this particular point when consuming JWT on browsers.

> Avoid ‘Basic Authentication’, use standard (e.g. JWT)

What is the proper way to handle JWTs? Can I store them in localStorage? What is the best practice?

How worried should I be with XSS if I were to store JWTs in localStorage?

Maybe expand this for frontend consumption?

---

Here's my take.

Have backend prepare 2 endpoints, one for login that accepts POST request with username and password and sets HttpOnly cookie on login success that will only be used on the second endpoint that generates JWT.

All other APIs that serve application's resources shall use JWT for authentication.

Frontend

1. POST /api/login
2. If 1 succeed, GET /api/token (cookie authentication)
3. Store JWT in browser memory only (not storing in localStorage, sessionStorage, cookie or anywhere that maybe persistent)
4. Whenever user comes back on new tab, do (2), if succeeded in getting JWT, continue, else show user the login screen and restart from (1)

**Comment by kamranahmedse** [comment]
There is no need for two different endpoints. When a user logs in, you can simply generate a token and put it inside an HTTP only cookie which is then sent to the client and automatically included in subsequent requests to the server. Apart from that you can have a good Content Security Policy (CSP), proper input sanitization and rate limiting in place to further protect the application.
