### ISSUE TITLE
Kotlin Multiplatform Mobile

### ISSUE THREAD

**Issue by ianmwema07** [kamranahmedse/developer-roadmap#3844]
Hello, 

Having gone through the roadmap for android Mobile application I think it would be nice to prepare a roadmap for Kotlin Multiplatform Mobile development.

**Comment by nileshgsmartiam** [comment]
@kamranahmedse Please add Kotlin roadmap for Android Devs.

**Comment by kamranahmedse** [comment]
We are now closing any issues requesting new roadmap requests to clean up the issues. 

However, this doesn't mean that the requested roadmap won't be added to the website. We are putting it in the backlog and will add it to the website depending on how it ranks in the backlog or sooner if we find someone interested in adding that roadmap. Thank you for the request though! 🙏
