### ISSUE TITLE
Maybe adding static code analysis for javascript ?

### ISSUE THREAD

**Issue by MrCallicles** [kamranahmedse/developer-roadmap#388]
It is not the most widely used tool in the industry according to my knowledge so it may be
irrevelant for the roadmap.
But I think learning to use a software like Jlint, JShint or Google Clojure Linter
is a good thing to do for a web developper.

**Comment by WuglyakBolgoink** [comment]
this will be good to put in QA section.

**Comment by kamranahmedse** [comment]
Frontend roadmap has been rewritten from the ground up. You may have a look
