### ISSUE TITLE
[Typo] System Design. Link in Content Delivery Networks

### ISSUE THREAD

**Issue by nifadyev** [kamranahmedse/developer-roadmap#3881]
There is a small typo in link `Brief aout Content delivery network` at [file](https://github.com/kamranahmedse/developer-roadmap/blob/e05269f1178350751d0e0a01911753929f9f86e4/src/data/roadmaps/system-design/content/108-content-delivery-networks/index.md).

**Comment by amanntank** [comment]
Fixed

**Comment by nifadyev** [comment]
@amanntank , thanks for you work. Could you please change the PR description? It will properly connect issue and PR. Here is the [reference](https://github.com/kamranahmedse/developer-roadmap/pull/3802#issue-1664327273)

**Comment by nifadyev** [comment]
Sorry for misunderstanding. It's just an optional suggestion, you did great.
Here is [documentation](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword) about linking issue and PR
