### ISSUE TITLE
[Suggestion] Frontend Developer

### ISSUE THREAD

**Issue by bhavyakaudinya** [kamranahmedse/developer-roadmap#3896]
Hey Kamran! 
So let me get straight to the point: 

When I was learning Front-end Development from <https://roadmap.sh/frontend> roadmap;
I stumbled upon some broken links in <HTML> portion of this Roadmap....

I've attached and marked the links which are broken in a SS attached to this req...
![Screenshot 2023-05-08 013101](https://user-images.githubusercontent.com/81902744/236700456-916567c0-28cd-43ec-95e4-103537183c71.png)

I'm just getting started with this roadmap and I'll make sure to suggest more changes if I find some more out there.....

Thanks & Regards
Bhavya

**Comment by arikchakma** [comment]
@bhavyakaudinya The web development basics link is broken, and the other works fine. You can check #3897

Thanks
