### ISSUE TITLE
Add Race Condition-related Topics Backend

### ISSUE THREAD

**Issue by mufid** [kamranahmedse/developer-roadmap#39]
Along with the stacks, developers should also understand about theoritical data processing for distributed system, like thread safety, locking, and how to deal with race condition. This is important since nowdays we deal with multiple servers. But i don't know where to include these topics since this does not belong to any stack in the infographic.

**Comment by mufid** [comment]
Or, perhaps, this can be in the "advance theoritical CS topics" that should be followed by anyone who want to step up the game (regardless the major they take). Of course this is not for beginner, but soon after we learn the basic, it is impossible to learn anything without these topics.

Perhaps, "theoritical CS topics" can be consist of these subtopics (taken from "Operating System Concept" book and "Data Structure and Algoritm" book):

- Threading (and building a thread-safe application) since nowadays most computers and OS have multihthreading capability.
- Resource management (deadlock, locking, race condition, mutex), as a one of solution for building thread-safe application.
- Memory management (understanding page, how GC works, RSS, etc), so that we can understand why the program has memory leak.
- Basic complexity calculation (Big O), so we can understand which part of the code that running very slow.
- Basic searching (sequential, binary search, BFS, DFS, A*), so we can make a decision for simple problem.

I tried to cherry pick those topics so new developers can get the gist of most high volume and high scalability problem.

Feel free to improve the list :smile:

**Comment by kamranahmedse** [comment]
Agreed that everybody should know them but I have to close this for being a non-issue as the charts  focus on given a high level overview of the ecosystem and what one needs to learn in terms of the available options. But nice suggestion though; I might add this once I put up the links and resources into the repository.

Thank you.
