### ISSUE TITLE
web developer code

### ISSUE THREAD

**Issue by mansurmaslah** [kamranahmedse/developer-roadmap#391]
#375  all need a betterlife for our new eror we live in new 21century we most make our new life most new and make our idias into building our new life #387 
[communicatio skill.txt](https://github.com/kamranahmedse/developer-roadmap/files/1714748/communicatio.skill.txt)

**Comment by kamranahmedse** [comment]
hey I am not really sure what you are trying to say.

**Comment by Vishenka23** [comment]
#391

**Comment by mansurmaslah** [comment]
sorry guys what was doing was loco but i need an attantion for someone to guid me how to work with github

**Comment by techopsandtraining** [comment]
![pi-2018-02-14-1](https://user-images.githubusercontent.com/34950533/36627585-2ed237d6-1902-11e8-88b0-5b3c612eddbb.jpg)
Bro, I'm new to Github, but I have a group that is called TechOpsAndTraining.com It's my learning and integrated development environment.  You should check it out! I made and app for android that was an Icon and a shortcut with three screenshots back in 2014, I'm finally ready to put the next version together and It needs to bo compatibale with all the platforms like ios, android, web and Id like it to be github tailored also.  I get lost in here sometimes man, maybe we could help each other figure it out?
