### ISSUE TITLE
Firebase maybe?

### ISSUE THREAD

**Issue by parzh** [kamranahmedse/developer-roadmap#392]
Hey there! Good job you are doing! Much appreciated!

I didn't see Firebase in the chart. Please, consider adding it. That is some great tool for serverless development.

**Comment by karltaylor** [comment]
I agree, I didn't see it but it would be good for frontend / backend devs to see it i the ecosystem.

**Comment by karltaylor** [comment]
Firebase isn't **just** a backend/db as a service, it's holds a plethora of different developer utilities like hosting, cloud storage, cloud functions etc. I feel like it falls in both frontend/backend. But not sure how that would work.

**Comment by parzh** [comment]
This would better apply to FE rather than BE, imho. I doubt that beginner BE developer will ever have to know about Firebase.  It may serve, though, as a starting point, but it is very likely that you are already mastered some FE, so changes are that you won't switching to BE.

**Comment by parzh** [comment]
This would better apply to front-end rather than back-end, imho. I doubt that beginner BE developer will ever have to know about Firebase.  It may serve, though, as a starting point, but it is very likely that you are already mastered some FE, so changes are that you won't switching to BE.

**Comment by kamranahmedse** [comment]
The issue has been made obsolete with the update. Please have a look at the updated roadmap.
