### ISSUE TITLE
[Bug]Same content for different map tile (Mongodb)

### ISSUE THREAD

**Issue by CodeVibranium** [kamranahmedse/developer-roadmap#3962]
[MongoDB roadmap](https://roadmap.sh/mongodb)
Map tile **Query Operators** and **Performance Optimisation** open up the model with same content.

https://github.com/kamranahmedse/developer-roadmap/assets/62259994/da499715-2f19-408e-802f-cfd330329132

**Comment by mingjm3** [comment]
And when mark the Query Operators as done, the Performance Optimisation will also be marked

**Comment by dansholds** [comment]
> And when mark the Query Operators as done, the Performance Optimisation will also be marked

This issue has been fixed, the "issue" now is that no content exists in the Performance Optimization section, which will be addressed in a seperate PR.

Closing this issue due to the initital issue no longer occuring.
