### ISSUE TITLE
[Suggestion] Software Architect

### ISSUE THREAD

**Issue by lobodol** [kamranahmedse/developer-roadmap#3964]
Hi there, I don't see any legend about the meaning of colored lines or boxes.
Why are there different colours? 
Why are there plain lines and dotted ones?

Regards,

**Comment by kamranahmedse** [comment]
* Solid line represents the learning path connecting the main topics (yellow boxes).
* Dotted lines are the extension of the main topic into sub topics (light yellow boxes)
