### ISSUE TITLE
v1-get-user-resource-progress not returning any value for skipped topics

### ISSUE THREAD

**Issue by vgtmhl** [kamranahmedse/developer-roadmap#3971]
[roadmap.sh_skipped-bug.webm](https://github.com/kamranahmedse/developer-roadmap/assets/44584815/2764cc42-ef54-46cc-a5bd-3c71f55c082b)

As you can see from the video, although I have a bunch of skipped topics, they are not loaded on startup.
Once I skip a topic again, then all the skipped topics are fetched and stored in localhost correctly (although not displayed in the UI until page refresh)

I checked the code, and the function responsible for fetching progress data when absent/expired from the server is `loadFreshProgress` hitting `v1-get-user-resource-progress` endpoint

Apparently, this endpoint doesn't return any data for skipped topics on startup:
![image](https://github.com/kamranahmedse/developer-roadmap/assets/44584815/29cbbeab-86da-44cb-8286-0080faf99493)

I can reproduce this on backend and frontend roadmaps in both Firefox and Chrome (latest)

**Comment by arikchakma** [comment]
Thank you, @vgtmhl; we've fixed it.
