### ISSUE TITLE
[Suggestion] JavaScript Roadmap

### ISSUE THREAD

**Issue by HarukaYamamoto0** [kamranahmedse/developer-roadmap#3972]
there should have been a button that reset all progress on a roadmap

**Comment by arikchakma** [comment]
You can do it now from the account page.
<img width="1440" alt="image" src="https://github.com/kamranahmedse/developer-roadmap/assets/54026804/32f2ea80-bd6b-424e-845c-289571708c8c">

Thank you, I'm closing the issue.
