### ISSUE TITLE
[Minor Typo] Computer Science roadmap Tries != Trees

### ISSUE THREAD

**Issue by optimizasean** [kamranahmedse/developer-roadmap#3984]
Just a note, computer science roadmap says Tries instead of Trees.

<img width="338" alt="image" src="https://github.com/kamranahmedse/developer-roadmap/assets/8909476/b469acba-a920-46e6-b79b-5299187b89eb">

middle of page: https://roadmap.sh/computer-science

**Comment by kamranahmedse** [comment]
Thank you for reporting that but it's correct; it is supposed to say [Trie](https://en.wikipedia.org/wiki/Trie).

**Comment by optimizasean** [comment]
Oh a prefix tree 😆 nice! I never heard that term before. Looks like I need some learning before I can check that node off
