### ISSUE TITLE
add gitlab-ci to DevOps ci/cd

### ISSUE THREAD

**Issue by hmdshariati** [kamranahmedse/developer-roadmap#399]
gitlab-ci in power of gitlab-runner is similar to jenkins etc.

**Comment by JeSuisUnCaillou** [comment]
I was going to strongly recommand the same
Gitlab-runner is an excellent CI/CD tool, way better than Jenkins in my honest opinion.

**Comment by gitDylanHub** [comment]
I work in an AWS shop and there is a couple spikes regarding the AWS CI/CD tool as well.  Be nice to have it up here.

**Comment by nathieb** [comment]
I'm recommanded also Gitlab with is solution (best) gitlab-runner infra. The solution is simple and integrate GIT repository but also the all solutions to construct CI/CD with pull request.

**Comment by kamranahmedse** [comment]
This has been fixed and will be published in the coming release. Thank you 🙏
