### ISSUE TITLE
Social skills roadmap missing

### ISSUE THREAD

**Issue by luigimannoni** [kamranahmedse/developer-roadmap#40]
Not a recurrent issue but generally can reproduce this bug following these steps:

* Introduce to the team
* Start a new project
* Suggest different tech stacks

Expected result:
* List of pros and cons of different tech architectures, deeper discussion on what fit best

Actual result:
* "X is total crap, we'll be going to use Y"
where X and Y are usually random variables.

After that it's hard to proceed or the application gets unstable, can't debug it either as it crashes way before I launch any debugger.

Dependencies seems to be all in place and I don't get any error usually beforehand.
Is there any workaround for it at the moment?

**Comment by kamranahmedse** [comment]
Social Skills ≠ Web Development but thank you for reporting.
