### ISSUE TITLE
[BUG] Failure to Render Articles Following 404 Error

### ISSUE THREAD

**Issue by CodeVibranium** [kamranahmedse/developer-roadmap#4009]
The present issue entails the failure of all child tiles within the **scaling** MongoDB to render properly, as they consistently encounter a `404` error. Conversely, the main **scaling MongoDB** tile remains unaffected, successfully retrieving data and receiving a `200` response. Nonetheless, after encountering a `404` error, the data fails to render in **any** of the tiles containing information.

https://github.com/kamranahmedse/developer-roadmap/assets/62259994/73b42dd5-e8e6-4fb9-ab26-ff908b31a85b

**Comment by dansholds** [comment]
We now handle topic 404's more gracefully i.e. by displaying "Topic not found" so I don't believe that this is an huge issue anymore, we do have the issue of not having any content within those nodes now, but the issue is not a scary one!
