### ISSUE TITLE
[Issue] Frontend Developer

### ISSUE THREAD

**Issue by NICCANAS** [kamranahmedse/developer-roadmap#4015]
In the link https://roadmap.sh/frontend?r=frontend-beginner, when clicking on "Frontend Roadmap," it shows an error.

> There was an error.
Try loading the page again. or submit an issue on GitHub with following:
> Unexpected token '<', " SyntaxError: Unexpected token '<', "
![issue](https://github.com/kamranahmedse/developer-roadmap/assets/101841361/38db361e-25a5-4eea-8647-d594b48726e9)

**Comment by kawaiier** [comment]
I guess it's already fixed as I couldn't reproduce it in Safari, Brave and Firefox

**Comment by kamranahmedse** [comment]
This has been fixed, thank you for reporting.
