### ISSUE TITLE
Add mobile in front-end

### ISSUE THREAD

**Issue by crjacinro** [kamranahmedse/developer-roadmap#403]
Add Android / ios development
Add Hybrid mobile development

**Comment by WuglyakBolgoink** [comment]
Hybride app should be connected with HTML & CSS & JS + Mobile-Section (iOS/Android/etc...)

for Hybrid create new elements:
* cordova
* telerik
* native script
* ionic
etc...

**Comment by kamranahmedse** [comment]
Thank you for opening the issue but that is out of the scope
