### ISSUE TITLE
[Feature] Keep older versions available

### ISSUE THREAD

**Issue by kerunaru** [kamranahmedse/developer-roadmap#4055]
I started the DevOps Roadmap a couple of weeks ago. Today I tried to continue with it and... Surprise! The topics about SO basic concepts have gone. Although the new roadmap is better focused on day-by-day work, I was enjoying that emphasis on building a foundation before that.

It could be great if you add navigation between the different versions of the same roadmap so one can finish the current studying section at least.

**Comment by ShawnNectar** [comment]
If you need to access older versions, you can refer to the previous commits. Although it may be a bit inconvenient, reviewing the commit history is one way to find the version you want to. Also, I 100% agree with that feature!
