### ISSUE TITLE
Add QA on the main roadmap

### ISSUE THREAD

**Issue by NedkoHristov** [kamranahmedse/developer-roadmap#406]
Manual and Automation QA would be quite useful.

**Comment by vikramvi** [comment]
Don't take away QA job and give it to dev :)

IMHO if Dev team follows BDD religiously with other PM, that itself reduces lots of bugs during coding

**Comment by WuglyakBolgoink** [comment]
hier can be different style/code-checkers, like:

F/E:
* jshint
* eslint
* tslint

B/E:
* pmd
* checkstyle
* firebug

etc...

**Comment by kamranahmedse** [comment]
It is not within the scope of the roadmap. Please have a look at the updated roadmap.
