### ISSUE TITLE
[Broken Link] full-stack roadmap - Node.js

### ISSUE THREAD

**Issue by victoriacheng15** [kamranahmedse/developer-roadmap#4079]
The video from the last link `Node.js Full Course` is not available anymore

**Comment by erasmoh** [comment]
If you mean this link [Node.js and Express.js Full Course](https://www.youtube.com/watch?v=Oe421EPjeBE), it is working now @victoriacheng15.

![image](https://github.com/kamranahmedse/developer-roadmap/assets/12125288/6bb0c76c-7c42-480d-a287-f068d4adb2c8)

**Comment by victoriacheng15** [comment]
@erasmoh Yes, that link, and thank you for letting me know!
