### ISSUE TITLE
Frontend : Jquery

### ISSUE THREAD

**Issue by Poojaaaa** [kamranahmedse/developer-roadmap#408]
Don't we have to learn Jquery for front end web development. Add it on front-end map.

**Comment by mrezaprwr** [comment]
i thought it so

**Comment by Ayush-Rawal** [comment]
jQuery is going out of date, more and more people are avoiding it due to it's large size. Today if one absolutely MUST use jQuery they prefer a slim build.

**Comment by WuglyakBolgoink** [comment]
`jQuery` is a lib, not a framework... In this case you should put in list `LODASH` too, and +100500 other libs in graph...

**Comment by pixelgoo** [comment]
Is jQuery outdated? Yes. Is it used in every second legacy project? Yes. 

It certainly needs to be in the map.

**Comment by maxorlovsky** [comment]
Not in the 2018 map

**Comment by fmaiabatista** [comment]
I think it's relevant to include jQuery considering its importance and contribution to JS and web history. It is also a nice and friendly "first lib" experience for first time learners!

**Comment by Ayush-Rawal** [comment]
Is it used in most of the legacy codebases? yes. Are a lot of these projects trying to remove it from the codebase? yes. Has it influenced most of the web and has been super-important for web history? yes. Should it be there in a map aimed at showing what to learn in **2018**? No.

**Comment by kamranahmedse** [comment]
Frontend roadmap has been rewritten from the ground up. You may have a look
