### ISSUE TITLE
Gluon for JavaFX mobile development

### ISSUE THREAD

**Issue by diegopego** [kamranahmedse/developer-roadmap#409]
Grata Tool that leverages Full development using  Java (nota javascript) from server, desktop and Cross native mobile for Android and IOS

**Comment by kamranahmedse** [comment]
Thank you for opening the issue. We don't want to convolute the roadmap by mentioning every available option and are just focusing on what is the most relevant item that you would pick today and the mentioned item doesn't conform to that. 

This has also been [mentioned in the contribution docs](https://github.com/kamranahmedse/developer-roadmap/blob/master/CONTRIBUTING.md#guidelines). 
Thank you for your suggestion though 🙏
