### ISSUE TITLE
[Suggestion] Frontend Developer

### ISSUE THREAD

**Issue by cholazzzb** [kamranahmedse/developer-roadmap#4100]
Hi, when I see the roadmap on `Type Checkers`, I found there is only Typescript. On the other hand, there are some unpopular alternative, such as [`Flow`](https://flow.org/) (from Facebook), [`ReScript`](https://rescript-lang.org/), or maybe [`JsDoc`](https://jsdoc.app/) ?. I am curious, what do you think about those alternatives?

![image](https://github.com/kamranahmedse/developer-roadmap/assets/37765885/62c678f7-1caa-4bcb-a569-abfe92fd2232)

**Comment by kamranahmedse** [comment]
Thank you for opening the issue. We don't want to convolute the roadmap by mentioning every available option and are just focusing on what is the most relevant item that you would pick today and the mentioned item doesn't conform to that. 

This has also been [mentioned in the contribution docs](https://github.com/kamranahmedse/developer-roadmap/blob/master/contributing.md). 
Thank you for your suggestion though 🙏
