### ISSUE TITLE
[BUG] Link broken

### ISSUE THREAD

**Issue by rtk-rnjn** [kamranahmedse/developer-roadmap#4110]
### Link broken in [Contributing.md](https://github.com/kamranahmedse/developer-roadmap/blob/master/contributing.md) in Section [Existing-Roadmaps](https://github.com/kamranahmedse/developer-roadmap/blob/master/contributing.md#existing-roadmaps)

> `Fixing Typos — Make your changes in the `[`roadmap JSON file`](https://github.com/kamranahmedse/developer-roadmap/tree/master/public/jsons)

---

> 
![image](https://github.com/kamranahmedse/developer-roadmap/assets/37435729/e457ef6a-17d6-4a74-9f8a-cb2fa58753eb)

---

[`roadmap JSON file`](https://github.com/kamranahmedse/developer-roadmap/tree/master/public/jsons) returns 404

![image](https://github.com/kamranahmedse/developer-roadmap/assets/37435729/a9247340-62fb-4a19-a324-7f2faf0adc24)

**Comment by tabishnaqvi1311** [comment]
Fixing this, the link is supposed to be 

```https://github.com/kamranahmedse/developer-roadmap/tree/master/src/data/roadmaps```

not

```https://github.com/kamranahmedse/developer-roadmap/tree/master/roadmaps/jsons```

@rtk-rnjn @kamranahmedse
