### ISSUE TITLE
Grammar check/ambiguity on Backend section

### ISSUE THREAD

**Issue by JoelAzaria** [kamranahmedse/developer-roadmap#412]
Beginning of Backend section you write "personally I would prefer Node.js and PHP 7 for **the full time**. "
Was this supposed to say for the **first** time or was it something else?  
It's unclear to me what is meant as written.

**Comment by mrezaprwr** [comment]
it should be first time, i guess

**Comment by JoelAzaria** [comment]
Submitted with a few other small edits

**Comment by Vishenka23** [comment]
Вы можите писать на Русском

22.02.2018 20:36 пользователь "JoelAzaria" <notifications@github.com>
написал:

**Comment by kamranahmedse** [comment]
The issue has been made obsolete with the update. Please have a look at the updated roadmap.
