### ISSUE TITLE
[Suggestion] All Road Maps

### ISSUE THREAD

**Issue by rosebabu-macroglobal** [kamranahmedse/developer-roadmap#4124]
Hi there,

Just a thought to share with you as a suggestion i have in roadmaps design page.  in some of the roadmaps, there is a legend in the left side top for the suggestions like topics order to be learn (beginner, intermediate. etc), recommendations legend, etc. This order, recommendations are helpful to start learning topics. If you provide a clickable option on these to show only selected legend options that would be nice to filter the topics. if we take "Frontend Developer" and if i click "Personal Recommendation / Opinion" which has purple tick box, then the below shown topics are filtered with the topics for that (purple tick boxes) others will be hidden. This will help to see the selected legend's topics alone and we can further explore the topics. once all the topics are covered then i will click for "Alternative option" and so on. Hope this makes sense to tryout and see how it is coming. Thanks!

**Comment by kamranahmedse** [comment]
We are currently working on a custom editor for making roadmaps. This isn't easily possible to do right now but we will have it in the future. Thank you!
