### ISSUE TITLE
Add Nest.js

### ISSUE THREAD

**Issue by panuhorsmalahti** [kamranahmedse/developer-roadmap#414]
I highly recommend adding Nest.js to Backend -> Node.js -> Framework list.

https://nestjs.com/

**Comment by Arthurensohn** [comment]
Du Zwerg warte mal ab was ich mit dir mache du hundesohn ichwerdedich und dein Mutter fickn du Hund jetzt bin ich dran schieb dir mal Filme aber was für welche

**Comment by Zalafa** [comment]
Hmm

**Comment by arifalishaik** [comment]
Yes. Sounds good to me.

**Comment by kamranahmedse** [comment]
This has been fixed and will be published in the coming release. Thank you 🙏
