### ISSUE TITLE
[BUG] Link broken

### ISSUE THREAD

**Issue by liamtirney** [kamranahmedse/developer-roadmap#4140]
Last link broken in HTML section of the full stack roadmap titled "HTML and CSS Full Course - Beginner To Pro" [100-html.md](https://github.com/kamranahmedse/developer-roadmap/blob/master/src/data/roadmaps/full-stack/content/100-html.md)

**Comment by iwint** [comment]
This issue was fixed and here is the PR link[]( https://github.com/kamranahmedse/developer-roadmap/pull/4147)

**Comment by hamadecd** [comment]
> This issue was fixed and here is the PR [Link](https://github.com/kamranahmedse/developer-roadmap/pull/4147)

I don't think that was fixed, I just tried and the link redirects to a video that does not available anymore.

**Comment by iwint** [comment]
> > This issue was fixed and here is the PR [Link](https://github.com/kamranahmedse/developer-roadmap/pull/4147)
> 
> I don't think that was fixed, I just tried and the link redirects to a video that does not available anymore.

It works for me may be your are checking with the previous file and please do check with a correct file

**Comment by kamranahmedse** [comment]
Thanks, this should be fixed now.
