### ISSUE TITLE
specific  content study

### ISSUE THREAD

**Issue by Eversea2017** [kamranahmedse/developer-roadmap#416]
Hi，I really appreciate  Roadmap to becoming a web developer in 2018,  But there's only a route out it，
I wonder if you can give us some good study websites or documents about the route contents，THANKS

**Comment by Ronkiro** [comment]
#560  is a dupe of this, but it has some more comments inside it.

Could this issue be closed in favor of #560?
@kamranahmedse ?

**Comment by kamranahmedse** [comment]
Thanks @Ronkiro
