### ISSUE TITLE
[Bug] Google Recaptcha Error "Invalid domain for site key"

### ISSUE THREAD

**Issue by Yousef-Salah** [kamranahmedse/developer-roadmap#4167]
While I am trying to downlaod React.js roadmap, I fount this error when website ask me about my email.

here is an image for this error.

![image](https://github.com/kamranahmedse/developer-roadmap/assets/59259816/c9f263b8-e40b-4b3e-a66c-c4102492a97f)

**Comment by kamranahmedse** [comment]
We don't have that captcha anymore. Are you sure you are at [roadmap.sh](https://roadmap.sh/)?
