### ISSUE TITLE
[Suggestion] Frontend Developer

### ISSUE THREAD

**Issue by OneCode-AA** [kamranahmedse/developer-roadmap#4169]
Hello, I love your roadmaps!!! thanks, but i have a suggestion, can you have the Frontend Developer beginner version pdf to be downloadable instead of the detailed version when i click the download button

**Comment by kamranahmedse** [comment]
[Here you go.](https://github.com/kamranahmedse/developer-roadmap/files/11967498/frontend-beginner.pdf)
