### ISSUE TITLE
[Suggestion] Computer Science

### ISSUE THREAD

**Issue by levsargsyan** [kamranahmedse/developer-roadmap#4172]
**In Computer Science roadmap under section MFU, the description is wrong.**

Here in description "_MFU Cache is a variation of the LRU Cache. The difference is that instead of deleting the least recently used entry, the MFU Cache deletes the least frequently used entry._" - 
1) First part of sentence is wrong, MFU not variation of the LRU Cache but is another cache replacement policy.
2) Last part of sentence is wrong, it should be "_MFU Cache deletes the most frequently used entry._",

**Comment by kamranahmedse** [comment]
Thank you, can you submit a PR with these changes?

**Comment by kamranahmedse** [comment]
Thank you!

**Comment by levsargsyan** [comment]
> Thank you!

You are welcome!
