### ISSUE TITLE
Fix Typo: Typescript

### ISSUE THREAD

**Issue by Yasir-Khan22** [kamranahmedse/developer-roadmap#4173]
**Transcript** - Everyday Types ❌

**Typescript** - Everyday Types ✔

![image](https://github.com/kamranahmedse/developer-roadmap/assets/63096083/0b52e051-2ad8-49a4-bb68-2d8a4c66d9b6)

**Comment by kamranahmedse** [comment]
Feel free to submit a PR

**Comment by Yasir-Khan22** [comment]
> **Transcript** - Everyday Types ❌
> 
> **Typescript** - Everyday Types ✔
> 
> ![image](https://user-images.githubusercontent.com/63096083/251476014-0b52e051-2ad8-49a4-bb68-2d8a4c66d9b6.png)


@kamranahmedse 
If It's valid, allow me to submit a PR for this?

**Comment by kamranahmedse** [comment]
Fixed in https://github.com/kamranahmedse/developer-roadmap/commit/05451a0f0795f4d2bcc6efe0f1199d47ba408b2a

**Comment by kamranahmedse** [comment]
@Yasir-Khan22 I went to verify if the title was correct and edited the file in-place -- sorry for the missed opportunity. I am sure you will find some other typos somewhere ;-)
