### ISSUE TITLE
Introduction to the Language has an incorrect link

### ISSUE THREAD

**Issue by jamiecropley** [kamranahmedse/developer-roadmap#4180]
### What is the URL where the issue is happening

https://roadmap.sh/cpp

### What browsers are you seeing the problem on?

Chrome

### Describe the Bug

When you click introduction to the language on C++ road map then the following link
![image](https://github.com/kamranahmedse/developer-roadmap/assets/17186004/f33171d7-f4f0-43cf-bdc6-d65f2f9e75de)

I get the message:
This video isn't available any more

I traced the new link though by using way back machine.

the correct link is: https://www.youtube.com/watch?v=vLnPwxZdW4Y

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by jamiecropley** [comment]
Thanks for updating! Reach out if you need help fixing and finding other broken links.

**Comment by arikchakma** [comment]
That would be great for us.
