### ISSUE TITLE
Add IDE/Editor Suggestion

### ISSUE THREAD

**Issue by easikoglu** [kamranahmedse/developer-roadmap#419]
IDE/Editor is not the most important part becoming a web developer but it is a tool that can change your focus on development.  
You can specify IDE's especially for back-end development : 
 IntelliJ IDEA, Eclipse  for Java 
IntelliJ Webstorm,Sublime for nodejs etc.

**Comment by yssource** [comment]
Vim Emacs is enough

**Comment by diegopego** [comment]
#sarcasm?
IDEs are a very helpful resource, specially for those who develop alone really big projects, with millions of lines of code.

**Comment by yssource** [comment]
I'm sorry. No sarcasm.
I think there are too many IDEs to try, but I believe Vim/Emacs are the fundamental tools for developers.

**Comment by diegopego** [comment]
Understood Your point of view.

Em 28 de fev de 2018 01:51, "jimmy.m.gong" <notifications@github.com>
escreveu:

**Comment by WuglyakBolgoink** [comment]
For example:
* (F/E) WebStorm
* (B/E) PHPStorm
* (B/E) IntelliJ (Java)
* (B/E & Mobile) Eclipse
* (B/E & F/E) NetBeans
* (Mobile) XCode (iOS)
* (Mobile) Android Studio

For geeks:
*  Vim*/Emacs/Nano/Notepad 😉

**Comment by diegopego** [comment]
Like It!

Em 8 de mar de 2018 17:47, "Wuglyak Bolgoink" <notifications@github.com>
escreveu:

**Comment by xAegir** [comment]
You can just use [VS Code](https://code.visualstudio.com/docs?dv=win&wt.mc_id=DX_841432&sku=codewin). It Supports like everything, you can just download the languages and plugins (to help you on your code/projects) through their extension manager.

**Comment by tdmalone** [comment]
There’s also Cloud9 if you want to be portable :) (there’s other cloud options too)

**Comment by necmettin** [comment]
1. There are multiple desktop apps, multiple mobile (tablet/phone) apps, and multiple online apps, each with their pros and cons, possible for each language out there. Is this viable?

2. Editor choice is very subjective. Someone might like the speed of Sublime, and not like it being closed source at the same time. Someone who doesn't like Microsoft can dislike VSCode without even trying it out. Someone who doesn't like Java may similarly dislike IntelliJ products out of the box.

3. Anybody who loves a specific editor/IDE will dislike or discard the others. Will we be able to provide an objective list?

It feels like we may have to create a (mostly) subjective list of comparative properties (speed, license, add-on count, etc. etc.) to be able to provide a list of editors.

Is this what we want?

**Comment by kamranahmedse** [comment]
Thank you for opening the issue. While I agree with that, we don't want to convolute the roadmap by mentioning everything out there. Regarding the IDE, I don't think we should add the recommendations as a part of roadmap. 

However, I will find a place for that in textual form somewhere outside the roadmap. Thank your 🙏
