### ISSUE TITLE
Typo in Input section of API Security Best Practices

### ISSUE THREAD

**Issue by anksh1997** [kamranahmedse/developer-roadmap#4197]
### What is the URL where the issue is happening

https://roadmap.sh/best-practices/api-security

### What browsers are you seeing the problem on?

Chrome

### Describe the Bug

![image](https://github.com/kamranahmedse/developer-roadmap/assets/19568165/d6675cd9-cb2d-4207-86df-cbbbb52786b0)

Please see the attached screenshot.
<b>Use proper</b> HTTP methods for the operation

### Participation

- [X] I am willing to submit a pull request for this issue.

**Comment by yahyatai** [comment]
working on it

**Comment by JamieBort** [comment]
@anksh1997 ,
 
per this https://github.com/kamranahmedse/developer-roadmap/pull/4199#issuecomment-1681499412 comment, THIS issue (#4197) will not be addressed.

**Consequently a label should be assigned to THIS issue stating as much.**

Incidentally, this https://github.com/kamranahmedse/developer-roadmap/pull/4199 Pull Request addresses THIS issue.

**Comment by dansholds** [comment]
> @anksh1997 ,
> 
> per this [#4199 (comment)](https://github.com/kamranahmedse/developer-roadmap/pull/4199#issuecomment-1681499412) comment, THIS issue (#4197) will not be addressed.
> 
> **Consequently a label should be assigned to THIS issue stating as much.**
> 
> Incidentally, this #4199 Pull Request addresses THIS issue.

Thanks for raising Jamie, I have created an internal ticket to resolve!
