### ISSUE TITLE
PHP template engines

### ISSUE THREAD

**Issue by rakhack** [kamranahmedse/developer-roadmap#42]
Yeah, I know many people dislike PHP, but if somebody decides to learn it, shouldn't they at least know about template engines like _blade_, _smarty_, _twig_, etc.?

**Comment by mahald** [comment]
my advice if u want to learn web development today:
forget about server-side templates engines MVC and such old shit ... Learn angular (angular.io).
the server side should only speak GraphQL inbound and json outbound (And use JWT for auth). and nothing else.

**Comment by rakhack** [comment]
Well, deciding whether PHP is dead or not is not the point of this issue. There are two opposite opinions on the topic, and we seem to stand on different sides.
Hovewer, since PHP
- is mentioned in this roadmap
- is still one of the top-10 most popular languages in the world ([proof link](https://www.sitepoint.com/whats-the-best-programming-language-to-learn-in-2017/)),

addition of several template languages doesn't seem a very bad idea, at least for me. We also shouldn't forget that "old" technologies happen to return back eventually, so... Why not?

**Comment by Gmacky2** [comment]
The point and click worked betert

**Comment by mahald** [comment]
php is prefectly fine, but "server-side template engines" are a technologie that is outdated.
so using a template engine with php is a bad idea to learn nowadays.
angular is the (by far and by many reasons) more modern approach, and there it's pure client side.

**Comment by kamranahmedse** [comment]
Hi @rakhack,

Thank you for reporting but this repository focuses more on the core development technologies; if you don't learn templating engines, you can still go-by. Plus if you look at 2017, there are mostly SPAs and stuff and I think it would be fine if you don't want to learn templating engines.

Thank you though.
