### ISSUE TITLE
Checkmarks to track progress

### ISSUE THREAD

**Issue by andreaxmartins** [kamranahmedse/developer-roadmap#4203]
### Feature Description

Hey,
I think it would be useful to have checkmarks available for the user to track their progress according to what they're studying atm.
This way, the user has not only a clear path, but also can keep track of their progression in a visual way, and also get more motivated to continue.

**Comment by kamranahmedse** [comment]
We already have support for marking as in progress

> inside the drawer
<img width="452" alt="image" src="https://github.com/kamranahmedse/developer-roadmap/assets/4921183/bdfe7273-dc06-428c-b921-ea499baf4b49">

> as a shortcut <kbd>shift</kbd> + <kbd>click</kbd>
<img width="423" alt="image" src="https://github.com/kamranahmedse/developer-roadmap/assets/4921183/d1225807-f2e3-45a9-8ff1-2176254262fb">
