### ISSUE TITLE
Adding TypeScript

### ISSUE THREAD

**Issue by mayurmudoi** [kamranahmedse/developer-roadmap#4204]
### Roadmap URL

https://roadmap.sh/react-native

### Suggestions

Adding a **new node** or a **new Roadmap Series** for **TypeScript** will be much useful for developers as well as learners. TypeScript plays an essential role once we move on to make more complex projects. 

_P.S. : I'm still learning, so do correct me if I'm wrong._

**Comment by dansholds** [comment]
Ta Da! https://roadmap.sh/typescript

🎉
