### ISSUE TITLE
Addition of Android Architecture Methods

### ISSUE THREAD

**Issue by CMxSAHAB** [kamranahmedse/developer-roadmap#4213]
### Roadmap URL

https://roadmap.sh/android

### Suggestions

Sir,
Please add=> Android architecture refers to the structural design and organization of an Android application. It provides guidelines and best practices for building robust, maintainable, and scalable apps. The most commonly used architecture patterns in Android development are:
MVC
MVP
MVVM
MVM etc its also major and core

**Comment by kamranahmedse** [comment]
This has been fixed and will be published in the coming release. Thank you 🙏
