### ISSUE TITLE
Caching Strategies is Insufficient And Has No Links

### ISSUE THREAD

**Issue by PeterPCW** [kamranahmedse/developer-roadmap#4215]
### Roadmap URL

https://roadmap.sh/system-design

### Suggestions

I am not sure wear a good resource to link would be, but here are some descriptions and examples from ChatGPT:

1. Cache-Aside:

In cache-aside caching, the application is responsible for managing the cache directly. When data is requested, the application checks the cache first. If the data is found in the cache, it is returned. If not, the application retrieves the data from the underlying data source, adds it to the cache, and then returns it to the requester.

Imagine you have a bookshelf where you keep your favorite books. Whenever you want to read a book, you first check your bookshelf. If the book is already there, you pick it up and start reading. If it's not on the bookshelf, you go to the bookstore, buy the book, bring it home, and add it to your bookshelf before you start reading it.

2. Write-Through:

In write-through caching, when data is updated or written to the cache, it is also immediately written to the underlying data store or database. This ensures that both the cache and the data store are always in sync.

Imagine you have a personal diary where you record your daily activities. Whenever you do something noteworthy, you write it down in your diary and also immediately tell your best friend about it. This way, your diary and your friend always have the same information.

3. Write-Behind:

In write-behind caching, data updates are initially written to the cache without immediately updating the underlying data store. The updates are eventually propagated to the data store in the background or when certain conditions are met, such as a batch write or a specific time interval.

Suppose you have a shopping list that you keep adding items to as you run out of them. Instead of going to the grocery store immediately after adding each item to the list, you wait until the end of the week and then go to the store with your complete list, making one big purchase.

4. Refresh-Ahead:

Refresh-ahead caching, also known as prefetching, involves proactively fetching data from the underlying data source and updating the cache before it is explicitly requested. This anticipates future access to the data and reduces the latency of retrieving it when it is actually needed.

Imagine you are hosting a party, and you know that your guests will likely ask for drinks throughout the evening. Instead of waiting for them to ask for each drink individually, you proactively prepare a tray of assorted drinks and keep it nearby, ready to serve. This way, the drinks are already available, and your guests don't have to wait for each drink to be prepared individually.

**Comment by kamranahmedse** [comment]
Hey there!

Looks like this issue has been hanging around for a bit without much action. Our roadmaps have evolved quite a bit since then, and a bunch of older issues aren't really applicable anymore. So, we're tidying things up by closing out the older ones to keep our issue tracker nice and organized for future feedback.

If you still think this problem needs addressing, don't hesitate to reopen the issue. We're here to help!

Thanks a bunch!
