### ISSUE TITLE
Use interactive checkboxes instead of bullet points

### ISSUE THREAD

**Issue by M-AminAlizadeh** [kamranahmedse/developer-roadmap#4244]
### Roadmap URL

https://roadmap.sh/frontend

### Suggestions

While I using the roadmap for frontend I see when I click on each topic (box)
There are a few links to resources about the topic and in the UI you use bullet points to show those links to resources

check this [link](https://photos.app.goo.gl/bf9qmKriWSmV3pGW6)

My suggestion is to change them with checkboxes because when someone wants to learn something in most cases they can't check out all the links at once for better UX and for remembering which link has been visited and which one doesn't
I suggest using interactive checkboxes  and save the state of each checkbox for each account on the server
That's it I hope my suggestion is beneficial

**Comment by kamranahmedse** [comment]
We are working on the custom editor for making roadmaps. This will be done after the migration. It's not possible currently because the content is all in markdown at the moment and it would be a hassle to implement it now.
