### ISSUE TITLE
Devops: Mesosphere is a company not a product

### ISSUE THREAD

**Issue by moondev** [kamranahmedse/developer-roadmap#427]
The product/platform that the company Mesosphere develops is called DC/OS: https://dcos.io

Also in my humble opinion Kubernetes should be yellow in the orchestrator section.

Cheers for putting this together! Pretty cool to visualize the ecosystem.

**Comment by Anthonyntilelli** [comment]
I think kubernetes/Mesosphere  should be added to the list also,  I am seeing  number of employeers asking for them especially kubernetes

**Comment by kamranahmedse** [comment]
This has been fixed and will be published in the coming release. Thank you 🙏
