### ISSUE TITLE
Android Developer Roadmap

### ISSUE THREAD

**Issue by Denzel313** [kamranahmedse/developer-roadmap#4293]
### Roadmap URL

https://roadmap.sh/android

### Suggestions

why in this section there is only kotlin language, is there no roadmap for java language?, I can feel very helpful if there is a roadmap for java android developers.

**Comment by kamranahmedse** [comment]
We do have a [separate roadmap for Java](https://roadmap.sh/java). Also Android roadmap is not language specific -- there is only fundamentals listed for Kotlin but rest of the roadmap is language agnostic.
