### ISSUE TITLE
the discord link on main website is invaild

### ISSUE THREAD

**Issue by kcfuler** [kamranahmedse/developer-roadmap#4294]
### What is the URL where the issue is happening

https://roadmap.sh/

### Describe the Bug

![image](https://github.com/kamranahmedse/developer-roadmap/assets/87866012/6ab4e66f-a082-4eab-b3f6-048fc8d05f22)
![image](https://github.com/kamranahmedse/developer-roadmap/assets/87866012/30a89d1e-be66-4f37-922d-8af46cdbaf66)

### Output from browser console (if any)

I think it's just not update

### Participation

- [X] I am willing to submit a pull request for this issue.

**Comment by LedgerAcademyPakistan** [comment]
Now Fixed 

![FwOgjdFyxz](https://github.com/kamranahmedse/developer-roadmap/assets/135990135/1ca867e3-7226-4553-a557-26dc38d87575)
