### ISSUE TITLE
Thanks

### ISSUE THREAD

**Issue by RiccoSuave** [kamranahmedse/developer-roadmap#43]
I did not know how else to contact you, so I posted here. First of all, thank you so much for putting this together. Second, is there a way to add technologies needed for developing with and for Social Networking sites regardless of doing this for the Web or Mobile platform; I realize this is more work, but mobile uses a lot of the web technologies and it would be great to know what it takes to be effective in the domain.

**Comment by ashim888** [comment]
:+1:

**Comment by kamranahmedse** [comment]
Thank you for reporting but the repository focuses specifically upon the core web development so it would be out of scope and if we keep adding the _irrelevant_ stuff, it would hardly fit in a single picture. Thanks though.

**Comment by RiccoSuave** [comment]
I understand, I could not resist however to at least ask since the idea 
was a great one. Thank you guys for putting this together.
