### ISSUE TITLE
understand the audience is not clickable

### ISSUE THREAD

**Issue by AdrielMaximus** [kamranahmedse/developer-roadmap#4307]
### What is the URL where the issue is happening

https://roadmap.sh/cyber-security

### Describe the Bug

understand the audience is not clickable, you can't mark as done or anything.

### Participation

- [X] I am willing to submit a pull request for this issue.

**Comment by dansholds** [comment]
duplicate of (the more detailed) https://github.com/kamranahmedse/developer-roadmap/issues/4302
