### ISSUE TITLE
Python Roadmap : Suggestion

### ISSUE THREAD

**Issue by stacked-uk** [kamranahmedse/developer-roadmap#4308]
### Roadmap URL

https://roadmap.sh/python

### Suggestions

I believe Jupyter Notebooks is an essential addition to learning Python.

**Comment by realFranco** [comment]
Hello, seems to me that it is useful it you are pursing roles related with the next positions (and relatives):

 - Data Engineering; 
 - Data Science; 
 - Full Data stack scientist.

Based on my experience I mostly use Python for scripting, web services, automations tools and integration services, and I am not get it in touch with Jupyter Notebooks or any live-code repo tools yet, maybe I am wrong, but that is my perception.
