### ISSUE TITLE
Deployment stamp 

### ISSUE THREAD

**Issue by marianoquevedo** [kamranahmedse/developer-roadmap#4312]
### What is the URL where the issue is happening

https://roadmap.sh/system-design

### What browsers are you seeing the problem on?

Chrome

### Describe the Bug

The "Deployment stamps" reliability pattern seems to have the same copy as the Bulkhead reliability pattern:
The links are fine tho.

<img width="593" alt="image" src="https://github.com/kamranahmedse/developer-roadmap/assets/12384762/aedc6964-64c6-4d41-900e-1df5bcac56f4">

Thanks so much for the website, it's great

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by dansholds** [comment]
This is no longer an issue, thanks for reporting!
