### ISSUE TITLE
Use created instead of built in container context

### ISSUE THREAD

**Issue by tlmikulski** [kamranahmedse/developer-roadmap#4327]
### Roadmap URL

https://roadmap.sh/docker

### Suggestions

Path: Container Security -> Security Patterns and Practices -> Immutable Infrastructure.

I'd change word **built** to **created** in this sentence: "Containers should be treated as immutable units - once ~~built~~ **created**, they should not be altered."

It better fits in container context.

**Comment by Aman254** [comment]
can you please add Metntion the file location: for the changes to be made

**Comment by tlmikulski** [comment]
Sure, here it is: `src/data/roadmaps/docker/content/109-container-security/index.md`

**Comment by Aman254** [comment]
@tlmikulski assign me

**Comment by Aman254** [comment]
@tlmikulski Now, you can close this I updated the file built -> created

**Comment by tlmikulski** [comment]
> @tlmikulski Now, you can close this I updated the file built -> created , but my changes are not visible in the original website as I updated the Index.md

If changes are not visible, have you pushed / merged your changes? :)

**Comment by tlmikulski** [comment]
As per your request - I'm closing this issue.
