### ISSUE TITLE
Big oversight in the tech and tooling for C#

### ISSUE THREAD

**Issue by davidtimovski** [kamranahmedse/developer-roadmap#433]
As a .NET dev I noticed a whole lot of stuff missing in that branch. Seeing as .NET is a major player in enterprise web development and has a ton of interesting tech to offer.

As an example of the missing stuff, here are some things that are there for different languages (PHP) but skipped in C#:

- Laravel -> .NET/ASP.NET MVC/ASP.NET WebApi/ASP.NET WebForms/ASP.NET Core/Service Fabric
- Composer -> NuGet
- PHPUnit -> nUnit/xUnit
- Mockery -> Moq
- Blackfire -> Visual Studio Team Services
- XHProf -> Application Insights/Visual Studio Diagnostics

**Comment by thor5** [comment]
Obviously .net stack was unrevealed

**Comment by kamranahmedse** [comment]
Obsolete issue. Please have a look at the updated roadmap.
