### ISSUE TITLE
remove the tensorflow content from the C++ roadmap

### ISSUE THREAD

**Issue by duhnyel** [kamranahmedse/developer-roadmap#4330]
### What is the URL where the issue is happening

https://roadmap.sh/cpp

### Describe the Bug

In the libraries section of the c++ roadmap is an article??? for tensorflow written in python which i suppose should not be there.

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by alexshibu1** [comment]
ohh yaaaa

**Comment by dansholds** [comment]
Thanks for reporting, I have created a PR that removes the examples in the node but keeps the general information around Tensorflow.
