### ISSUE TITLE
typescript roadmap - Conditional Types - Extends Error

### ISSUE THREAD

**Issue by bhaltair** [kamranahmedse/developer-roadmap#4346]
### What is the URL where the issue is happening

https://roadmap.sh/typescript

### What browsers are you seeing the problem on?

Microsoft Edge

### Describe the Bug

type Extends<T, U> = T extends U ? T : U;

Error
type B = Extends<any, string>; // type B is 'string'

Correct
type B = Extends<any, string>; // type B is any

### Participation

- [X] I am willing to submit a pull request for this issue.

**Comment by dansholds** [comment]
@bhaltair please submit a PR to fix this.
