### ISSUE TITLE
"ideas" directory?

### ISSUE THREAD

**Issue by technicolor1** [kamranahmedse/developer-roadmap#436]
I noticed at the end of frontend roadmap, it mentions an "ideas" directory. But i cannot seem to find it. Or is it in terms of opening an Issue to introduce an idea?

**Comment by saulius-spiridonas-ht** [comment]
yeah me neither. Where is it?

**Comment by kamranahmedse** [comment]
Yes, it is missing. I was planning on adding it afterwards but never got around to doing that. Will do, thanks.

**Comment by Robertroid** [comment]
Is it not yet implemented? :(

**Comment by kamranahmedse** [comment]
I never got around to doing that unfortunately however these will be added on the website [roadmap.sh](https://roadmap.sh) instead of the repository in the coming weeks after we are done with the 2020 release. 

Thank you 🙏
