### ISSUE TITLE
AI and Data Scientist Roadmap - Deep Leaarning Book - Security issue - Bad certificate

### ISSUE THREAD

**Issue by elir0d** [kamranahmedse/developer-roadmap#4360]
### What is the URL where the issue is happening

https://roadmap.sh/ai-data-scientist

### What browsers are you seeing the problem on?

Firefox

### Describe the Bug

When i tried to access the book link a error occur:
The error message indicates that the browser does not recognize the Certificate Authority (CA)

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by dansholds** [comment]
This no longer appears to be an issue.

<img width="1112" alt="Screenshot 2024-05-08 at 12 26 05" src="https://github.com/kamranahmedse/developer-roadmap/assets/25537601/a088847e-820f-470c-82ac-2f6d263a61fb">
