### ISSUE TITLE
Favourites star button  to quickly access roadmaps if u use several roadmaps

### ISSUE THREAD

**Issue by danilvysotsky** [kamranahmedse/developer-roadmap#4379]
### Roadmap URL

any

### Suggestions

Favourites star button  to quickly access roadmaps if u use several roadmaps

**Comment by kamranahmedse** [comment]
We already have bookmark feature for that

<img width="465" alt="image" src="https://github.com/kamranahmedse/developer-roadmap/assets/4921183/428a1b5a-fcdb-4212-92e6-129efad4f6b8">
