### ISSUE TITLE
Logo Proposal

### ISSUE THREAD

**Issue by redmusic27** [kamranahmedse/developer-roadmap#438]
Hello sir, I'm a graphic designer and I would love to contribute to your project with a logo. This is completely free, take it as a contribution. In case you agree I would be presenting sketches and you will be choosing/modifying the aspects you like more so we could work on the perfect logo for your project together.

Let me know what do you think? best regards :)

**Comment by mannafrog** [comment]
yes please send for my review

**Comment by redmusic27** [comment]
Okay sir. I will start to make a logo for you. if it is ready I will be back

**Comment by kamranahmedse** [comment]
Hey @redmusic27 thanks for the proposal but the header image that we have is fine :)

**Comment by redmusic27** [comment]
But I think it would be better if you have a special logo for this project to be easily remembered by people sir @kamranahmedse
