### ISSUE TITLE
Incorrect link to the "Deep Learning Book"

### ISSUE THREAD

**Issue by KananHasanov747** [kamranahmedse/developer-roadmap#4387]
### What is the URL where the issue is happening

https://roadmap.sh/ai-data-scientist

### Describe the Bug

You put a wrong link: replace "https://deeplearningbook.org"  to "https://www.deeplearningbook.org"

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by selvamuthukumaran1** [comment]
Link is correct in the fully-connected-nn.md for [Deep Learning Book](https://www.deeplearningbook.org/)
But still not working in https://roadmap.sh/ai-data-scientist

**Comment by amirs18** [comment]
I think it's something related to SSL at the book site...

**Comment by KananHasanov747** [comment]
> I think it's something related to SSL at the book site...

I still would recommend to change the link to "https://www.deeplearningbook.org", because it doesn't cause any errors at all.

**Comment by chessmadridista** [comment]
Hi, I am new. Can I pick up this issue? This seems simple for a first timer.

**Comment by Mohit888-R** [comment]
> Link is correct in the fully-connected-nn.md for [Deep Learning Book](https://www.deeplearningbook.org/) But still not working in https://roadmap.sh/ai-data-scientist

Not we have to change `ext-link` in ai-data-scientist.json
