### ISSUE TITLE
Which license is chosen for this repo?

### ISSUE THREAD

**Issue by goodjack** [kamranahmedse/developer-roadmap#439]
Hi, i'm a contributor of [goodjack/developer-roadmap-chinese](https://github.com/goodjack/developer-roadmap-chinese).

Thanks for your awesome repository!

I was wondering which licensing terms you choose?

Since there is a `CC0 1.0` image with a `CC BY 4.0` link in readme.md.

https://github.com/kamranahmedse/developer-roadmap/blob/3d96fdf1df0df51c508eeb5255cd2bc2ad81c7d4/readme.md#L58-L61

Look forward to your reply. Thanks!

**Comment by kamranahmedse** [comment]
Hey, it's [CC by NCSA](https://creativecommons.org/licenses/by-nc-sa/4.0/).
You have the correct one in the readme :)
