### ISSUE TITLE
I try starting a project in frontend 

### ISSUE THREAD

**Issue by mugonaan-0097** [kamranahmedse/developer-roadmap#4391]
### Detailed Description

this.containerEl?.replaceChildren is not a function
TypeError: this.containerEl?.replaceChildren is not a function at https://roadmap.sh/_astro/hoisted.fe598283.js:1:1484

**Comment by mugonaan-0097** [comment]
![Uploading Screenshot_20230823-161520.png…]()

**Comment by arikchakma** [comment]
It's not uploaded properly.

**Comment by mugonaan-0097** [comment]
I am using chrome

**Comment by arikchakma** [comment]
OS details, please? Like the Android version etc.

**Comment by mugonaan-0097** [comment]
Android version 10 HiOS version is 6

**Comment by arikchakma** [comment]
Can you try to update the Chrome? Because I've tried it from my Android device (a really old device) it's working fine.

**Comment by mugonaan-0097** [comment]
Waw what is wrong with mine?

**Comment by mugonaan-0097** [comment]
It work sir thank you for the help🙏
