### ISSUE TITLE
Fixing bug which is signing out when change a profile picture

### ISSUE THREAD

**Issue by prn-ic** [kamranahmedse/developer-roadmap#4395]
### What is the URL where the issue is happening

https://roadmap.sh/account/update-profile

### What browsers are you seeing the problem on?

Chrome

### Describe the Bug

When i try to change profile image (select image, and click 'upload' button), i have been logout. Throw 401 status code 
Image params:
- 720x720 px
- Format: jpeg

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by kamranahmedse** [comment]
Thank you for reporting. This should be fine now. Let me know if you still face any issues.
