### ISSUE TITLE
Npm Scripts under Task Runners

### ISSUE THREAD

**Issue by aharris88** [kamranahmedse/developer-roadmap#44]
I would recommend npm scripts instead of gulp or grunt.

https://ponyfoo.com/articles/choose-grunt-gulp-or-npm
https://medium.freecodecamp.com/why-i-left-gulp-and-grunt-for-npm-scripts-3d6853dd22b8#.tdu6qfzdu
https://css-tricks.com/why-npm-scripts/

**Comment by kamranahmedse** [comment]
Done. Thanks
