### ISSUE TITLE
Free resources to Mathematics on AI and Data Scientist Roadmap

### ISSUE THREAD

**Issue by FMGordillo** [kamranahmedse/developer-roadmap#4401]
### Feature Description

![image](https://github.com/kamranahmedse/developer-roadmap/assets/7970174/08d6f92f-2b19-4a16-982f-e205a0378b93)

But if you see some links are pointing to Coursera, how come?
I think Free resources should be prioritary in this case

**Comment by arifkratoss** [comment]
Transformational leadership is defined as a leadership approach that causes change in individuals and social systems. In its ideal form, it creates valuable and positive change in the followers with the end goal of developing followers into leaders.

**Comment by HarshalRathore** [comment]
@arifkratoss wtf???

**Comment by dewstend** [comment]
@FMGordillo What are the Coursera resources that you mention? Do you mean the [Mathematics for Machine Learning Specialization](https://www.coursera.org/specializations/mathematics-machine-learning?)?

If you go individually to each course, you can choose to **audit**, giving you free access to each course.

**Comment by FMGordillo** [comment]
Didn't know that was possible, thank you @dewstend
But still, I'd still add some sort of "label" with this information, I don't think everyone knows about it

([this is the step-by-step guide how to do the audit](https://www.youtube.com/watch?v=SncUKVarjLo))
