### ISSUE TITLE
Checking elements that shouldn't be checkable.

### ISSUE THREAD

**Issue by daghanerdonmez** [kamranahmedse/developer-roadmap#4419]
### What is the URL where the issue is happening

https://roadmap.sh/ai-data-scientist

### What browsers are you seeing the problem on?

Chrome

### Describe the Bug

Right clicking on some elements, for example the "This roadmap was created by...", applies a line-through effect to the element. It is also present on the "Find detailed version of this roadmap along with..." part on the purple box. 

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by dansholds** [comment]
No longer an issue, thanks for reporting!
