### ISSUE TITLE
Older tree style is much easier to read

### ISSUE THREAD

**Issue by GTHell** [kamranahmedse/developer-roadmap#442]
The older tree style (DevOp section) is much easier to read since it only has title and no detail. My suggestion was to have two version of each, one with detail and one with only title which make it easier to skim through.

**Comment by Ayush-Rawal** [comment]
I second this

**Comment by kamranahmedse** [comment]
Yes, I was planning to do that. Will try to do it over the coming weekend. Thanks.

**Comment by SyntaxLogic** [comment]
Agree, the new maps are too complicated.

**Comment by kamranahmedse** [comment]
I am bringing back the old format in the 2019 update. [Frontend roadmap has been updated](https://github.com/kamranahmedse/developer-roadmap#-frontend-roadmap) and changelog can be found [on spectrum](https://spectrum.chat/developer-roadmap/updates/frontend-roadmap-2019-changelog~85b6e11b-85cd-4f74-845e-ae57fe1243a7).

Stay tuned for the backend and DevOps roadmaps.
