### ISSUE TITLE
Bug :  One Step is done but another automatically close/Done 

### ISSUE THREAD

**Issue by Mohit888-R** [kamranahmedse/developer-roadmap#4430]
### What is the URL where the issue is happening

https://roadmap.sh/cyber-security

### What browsers are you seeing the problem on?

Chrome

### Describe the Bug

At the cyber security page In the `Networking Knowledge` Section, we do done step  `Commonn Protocol and their uses`  then automatically done step   `Understand Common Protocols`  otherwise we do reset one tasks any both them also another automatically reset. 
  

### Steps To Reproduce 
 1. Go To  [https://roadmap.sh/cyber-security](https://roadmap.sh/cyber-security)
 2. Scroll Down until  step - `Networking Knowledge`
 3. See `Networking Knowledge` and it's two path for **down** and **left side** 
 4. We you do change progress as done **down** step `Common Protocols and their Uses` 
 5. See **left side** `UnderStood Common Protocols` will also done and check marked both.
 
### Expected Behavior 
Until not change progress as done in `UnderStood Common Protocols` not recall this behavior.

### Screenshots / Videos

https://github.com/kamranahmedse/developer-roadmap/assets/76577184/7e7cf54a-5c96-47bd-8722-91ab8b7d1c9d

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by NabeelAhmed314** [comment]
This is not a bug since "Common Protocols and their Uses" and "Understand Common Protocol" are essentially same topic.
