### ISSUE TITLE
Ember removed in 2018?

### ISSUE THREAD

**Issue by stucampbell** [kamranahmedse/developer-roadmap#444]
Please can you add Ember back as JS framework? It is still one of the best frameworks and is actively used by high-profile companies, and it has a passionate community - albeit a smaller one than those for the three you have listed.

**Comment by christoshrousis** [comment]
imo there should be a rework of the entire diagram where:

- Angular/Ember MVC
- Vue MVVM
- React V 

Where the reader should review the differences and decide what makes most sense to them, or maybe understand the differences. Review the learning curve on each etc.

Oversimplification, but hopefully you get what I mean. Maybe make a PR.

**Comment by kamranahmedse** [comment]
Hey @stucampbell, thank you for opening the issue. While you are right about the use of ember, the roadmap focuses on "if you were to pick today what would you pick" and imho if you compare the job markets React, Angular and Vue should be the ones you should pick from if you were to pick today.
