### ISSUE TITLE
Develop Full Website Dark mood. it's batter to see everything and comfortable our human eyes. 

### ISSUE THREAD

**Issue by morshedulmunna** [kamranahmedse/developer-roadmap#4449]
### Feature Description

Develop Full Website Dark mood. it's batter to see everything and comfortable our human eyes.

**Comment by dansholds** [comment]
Dark mode is planned and will be available at some point, it's not a high priority for the team atm but feel free to join oour Discord to stay up to date with feature releases such as this! 

https://discord.gg/jFkwUQQf
