### ISSUE TITLE
When I click the outside dropdown not hide

### ISSUE THREAD

**Issue by morshedulmunna** [kamranahmedse/developer-roadmap#4450]
### What is the URL where the issue is happening

https://roadmap.sh/

### What browsers are you seeing the problem on?

Microsoft Edge

### Describe the Bug

When I click the outside dropdown, it does not hide. check the output screenshot

### Output from browser console (if any)

![image](https://github.com/kamranahmedse/developer-roadmap/assets/44342051/6a261a1c-9d03-4a4b-968f-28aee6dcd2ae)

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by theunhackable** [comment]
I would like to work on this. Please assign this to me

**Comment by HesamDanaee** [comment]
I would be happy to contribute.

**Comment by dansholds** [comment]
This is no longer an issue, clicking outside of the menu dropdown will now hide it.
