### ISSUE TITLE
Front-end Developer Roadmap suggedtion

### ISSUE THREAD

**Issue by abdulkarimyulchibekov** [kamranahmedse/developer-roadmap#4452]
### Roadmap URL

https://roadmap.sh/frontend

### Suggestions

![image](https://github.com/kamranahmedse/developer-roadmap/assets/103306301/6714dea3-d84d-448b-bdf4-4135b0d1fa9e)

in this part name of libraries should be updated. (For exmaple ant.design should be added). Futhermore, in this roadmap, sass/scss/less and bootstrap are not suggested, however they are very useful in creating web site. In addition to this, Netlify and versel should be added

**Comment by kamranahmedse** [comment]
Sass is there. Bootstrap/ant.design was intentionally removed to keep things simple. Regarding Vercel and Netlify, Deployment was overlooked, we will fix it in the coming release. Thank you!

<img width="334" alt="image" src="https://github.com/kamranahmedse/developer-roadmap/assets/4921183/1127945d-acca-44a8-bf27-68165cb675bd">
