### ISSUE TITLE
Inconsistancy in Beginner DevOps Roadmap

### ISSUE THREAD

**Issue by Prakash4844** [kamranahmedse/developer-roadmap#4453]
### Roadmap URL

https://roadmap.sh/devops?r=devops-beginner

### Suggestions

The cloud computing section mentions that one should learn about EKS, but there is no mention of K8s before that point, i think there should be a block for Kubernetes after Docker section.

**Comment by kamranahmedse** [comment]
EKS shouldn't be there, it's a mistake -- fixed (will be released soon).

**Comment by Prakash4844** [comment]
imho, Basic Kubernetes should have been added instead of removing EKS as Kubernetes is mentioned in almost all DevOps Job posts no matter beginner or experienced.
