### ISSUE TITLE
No course at the provided link(coursera)

### ISSUE THREAD

**Issue by sanjaydokula** [kamranahmedse/developer-roadmap#4475]
### What is the URL where the issue is happening

https://roadmap.sh/ai-data-scientist

### What browsers are you seeing the problem on?

Chrome

### Describe the Bug

when i click the link, the url is  https://www.coursera.org/specializations/deep-learning#courses, I have to remove the part with # for the page to load properly, And some other link dont work even after removing the part after #. The courses might have been updated in coursera.

![image](https://github.com/kamranahmedse/developer-roadmap/assets/50962362/06b25d33-1780-44fe-961d-7be64936edc2)

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by kamranahmedse** [comment]
It's working fine for me. Can you try incognito or a different browser?

<img width="1095" alt="image" src="https://github.com/kamranahmedse/developer-roadmap/assets/4921183/f6cf902b-df02-4829-b9be-4fc623ddfaed">
