### ISSUE TITLE
this.containerEl?.replaceChildren is not a function TypeError: this.containerEl?.replaceChildren is not a function at https://roadmap.sh/_astro/hoisted.9ab3d435.js:1:1484

### ISSUE THREAD

**Issue by bousaleh50** [kamranahmedse/developer-roadmap#4478]
### What is the URL where the issue is happening

https://roadmap.sh/react

### What browsers are you seeing the problem on?

Microsoft Edge

### Describe the Bug

this.containerEl?.replaceChildren is not a function
TypeError: this.containerEl?.replaceChildren is not a function at https://roadmap.sh/_astro/hoisted.9ab3d435.js:1:1484

this erro apears when i tried to get the  react roadmap i'v already started

### Output from browser console (if any)

Uncaught TypeError: Cannot read property 'toLowerCase' of undefined
    at r (use-keydown.0305ad6b.js:1)

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by advaithreddy** [comment]
Can you describe the Bug In a clean and precise manner

**Comment by bousaleh50** [comment]
> Can you describe the Bug In a clean and precise manner

never mind its work now tnx
