### ISSUE TITLE
Dead link

### ISSUE THREAD

**Issue by thinkshihang** [kamranahmedse/developer-roadmap#4485]
### What is the URL where the issue is happening

https://roadmap.sh/angular

### What browsers are you seeing the problem on?

Chrome

### Describe the Bug

In the "Rate limiting" section,  [Blogs and tutorials on RxJS](https://blog.angular-university.io/rxjs-better-performance-with-the-rxjs-audittime-operator/) refers to a 404 page. 

### Participation

- [X] I am willing to submit a pull request for this issue.

**Comment by JamieBort** [comment]
It appears as though this issue has been addressed and should be closed due to this https://github.com/kamranahmedse/developer-roadmap/pull/4491 pull request.

Is that the case? Do you know, @selvamuthukumaran1 ?

**Comment by dansholds** [comment]
No longer an issue, all links in the Rate Limit node are alive.
