### ISSUE TITLE
Render Issue

### ISSUE THREAD

**Issue by advaithreddy** [kamranahmedse/developer-roadmap#4488]
### What is the URL where the issue is happening

https://roadmap.sh/team/roadmaps?t=64f6ebbf5ce9f4ca589190f8

### What browsers are you seeing the problem on?

Microsoft Edge

### Describe the Bug

So when I delete a roadmap from my team, I have to reload the page to display the contents again or I have to move to other section and come back. It's annoying to do this everytime.

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by dansholds** [comment]
This does not appear to be an issue anymore. Deleting custom roadmaps results in the roadmap being instantly removed from view.

https://github.com/kamranahmedse/developer-roadmap/assets/25537601/f006454b-cabd-4ad2-b179-8945d8745832
