### ISSUE TITLE
Makes no sense to have the keyword "Roadmap" for Go

### ISSUE THREAD

**Issue by fibbbonachos** [kamranahmedse/developer-roadmap#4495]
### Roadmap URL

https://roadmap.sh/

### Suggestions

![image](https://github.com/kamranahmedse/developer-roadmap/assets/115238980/59f1209e-61aa-4ad2-9567-8281bcc865f3)

The only roadmap that has the keyword "Roadmap" next to it, is of Golang. It just looks off because none of the others have it, and I don't think there's any special reason to have that after Go.

**Comment by kamranahmedse** [comment]
This is intentional to please the lighthouse (it complains that "Go" is not an informative button text)
