### ISSUE TITLE
Regarding SDE roadmap

### ISSUE THREAD

**Issue by allinhtml** [kamranahmedse/developer-roadmap#450]
Hi @kamranahmedse ,

Thank you for creating a roadmap for Web developer. It's really useful for all.

Are you interested to create similar road map for SDE position.

**Comment by vivek3894** [comment]
@allinhtml  web developer = SDE . Both are not different !

**Comment by dbads** [comment]
@vivek3894  yups :+1:

**Comment by amejiarosario** [comment]
SDE = Software Developer Engineers can work as front-end developers, backend, DevOps. It's a matter of interest

**Comment by allinhtml** [comment]
Then why didn't add data structures and design patterns in the roadmap.

**Comment by kamranahmedse** [comment]
@allinhtml this is planned and will be added as a separate roadmap in the coming weeks once we are done with the 2020 release. Can you possibly share a bulleted list in the textual form of what do you think we should add and in what order?
