### ISSUE TITLE
Suggestion for Backend Roadmap

### ISSUE THREAD

**Issue by swarajkumarsingh** [kamranahmedse/developer-roadmap#4527]
### Roadmap URL

https://roadmap.sh/backend

### Suggestions

In scale, analytics is crucial, especially for the backend, there are many analysis tools, but the preferred ones that are used in scale are **Prometheus, Grafana & Datadog.**

Create a new section **Analysis** and add these topics

1. _Prometheus_
2. _Grafana_
3. _Datadog_

**Comment by kamranahmedse** [comment]
We already have "Instrumentation", "Monitoring" and "Telemetry" which cover these. It's just that we don't have the tool recommendations. I will put it in the details popup.

**Comment by swarajkumarsingh** [comment]
> We already have "Instrumentation", "Monitoring" and "Telemetry" which cover these. It's just that we don't have the tool recommendations. I will put it in the details popup.

ok, then the roadmap is completed!
