### ISSUE TITLE
Wrong text content in "Performance Optimization" topic (MongoDB Roadmap)

### ISSUE THREAD

**Issue by naXa777** [kamranahmedse/developer-roadmap#4538]
### What is the URL where the issue is happening

https://roadmap.sh/mongodb

### What browsers are you seeing the problem on?

Chrome

### Describe the Bug

**Actual**: clicking on "Performance Optimization" node is opening "Query Operators" sidebar.
**Expected**: clicking on "Performance Optimization" node is opening "Performance Optimization" sidebar.

### Demo

![image](https://github.com/kamranahmedse/developer-roadmap/assets/3858548/12d736c6-6e2f-46fd-8d7b-9b2df62568d5)

This is a duplicate of https://github.com/kamranahmedse/developer-roadmap/issues/3958 but with more details.

### Output from browser console (if any)

```
Uncaught TypeError: Cannot read properties of undefined (reading 'toLowerCase')
    at r (use-keydown.bb1f91bb.js:1:120)
```

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by naXa777** [comment]
this is a duplicate of https://github.com/kamranahmedse/developer-roadmap/issues/3962

**Comment by AmineAouragh** [comment]
Hey Pavel! I can't believe that issue is still there since May and probably even before that. Thanks for opening the issue. Did you have any chance to commit changes and create a pull request?

**Comment by AmineAouragh** [comment]
UPDATE:
The Performance Optimization folder doesn't even exist in [https://github.com/kamranahmedse/developer-roadmap/tree/master/src/data/roadmaps/mongodb/content](roadmaps/mongodb/content) that is so weird
![2023-10-18 13_10_13-developer-roadmap_src_data_roadmaps_mongodb_content at master · kamranahmedse_de](https://github.com/kamranahmedse/developer-roadmap/assets/71039249/23086b6d-08fd-463b-a165-8eb879ee7947)
