### ISSUE TITLE
Now build something - Legend

### ISSUE THREAD

**Issue by mvmisha** [kamranahmedse/developer-roadmap#454]
The "Now build something" and the blue dot at the legend, have no usage in the new "tree"... Remove them or change the image 😁

![68747470733a2f2f692e696d6775722e636f6d2f4f5a554f5574492e706e67 copia](https://user-images.githubusercontent.com/7188313/40123564-cab0bf88-5926-11e8-87bd-7e97af4c35f3.png)

**Comment by mvmisha** [comment]
Or better like this

![68747470733a2f2f692e696d6775722e636f6d2f4f5a554f5574492e706e67](https://user-images.githubusercontent.com/7188313/40124092-08a56806-5928-11e8-9bc4-14a28a031987.png)

**Comment by dwiggins4121** [comment]
blue?

**Comment by mvmisha** [comment]
> blue?

I saw they edited this, but in the whole document the dots are still purple/violet

**Comment by kamranahmedse** [comment]
Not relevant anymore. The recent updates to roadmap do not require this legend anymore.
