### ISSUE TITLE
Roadmap Can't Reach 100%

### ISSUE THREAD

**Issue by BusterSR** [kamranahmedse/developer-roadmap#4549]
### What is the URL where the issue is happening

https://roadmap.sh/prompt-engineering

### What browsers are you seeing the problem on?

Chrome

### Describe the Bug

The roadmap doesn't reach 100% completion when I cross everything off it only goes "86% DONE".

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by reynadess** [comment]
@BusterSR I also observed that 51 out 59 are completed. Even though all the displayed cards are marked **DONE**.
Attaching screenshot.
![Screenshot from 2023-10-07 14-07-04](https://github.com/kamranahmedse/developer-roadmap/assets/47269265/11b06dad-95f6-491d-a5fe-8cd402532325)

**Comment by reynadess** [comment]
@BusterSR We have to complete these as well.
![Screenshot from 2023-10-11 13-50-00](https://github.com/kamranahmedse/developer-roadmap/assets/47269265/adb85b1d-bfe5-4c47-b1c1-2c5fb7bab2c8)

**Comment by dansholds** [comment]
Closing due to roadmap being completable, however I do see how the missing sections were not exactly obvious.
