### ISSUE TITLE
Not accessible for blind in firefox

### ISSUE THREAD

**Issue by rernest7** [kamranahmedse/developer-roadmap#4553]
### What is the URL where the issue is happening

https://roadmap.sh/backend and other roadmaps

### What browsers are you seeing the problem on?
Firefox 118.0.1

### Describe the Bug

I'm leaving this more for reference than anything.
On chromium based browsers everything works as expected - List is not a mess and popups opens.
Tested in: Chromium, Edge, Brave
NVDA, MS Narrator 

## Issues
1. The list is a mess. The following is a 1:1 represantation
ObservabilityMetrics logging and otherin debugging and solvingIssues when things go wrong.observable items that can helpArchitectural PatternsMonolithic<...>
2. When pressed on an item the popup does not open.

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by dansholds** [comment]
Thanks for raising this, improved accessibility will be an area for improvement in the future but is not something that we are focussed on right now.
