### ISSUE TITLE
You are not allowed to update this roadmap

### ISSUE THREAD

**Issue by Philipelima** [kamranahmedse/developer-roadmap#4564]
### What is the URL where the issue is happening

https://draw.roadmap.sh/{roadmap_hash}

### What browsers are you seeing the problem on?

Chrome

### Describe the Bug

When I create a personal roadmap and get redirected to "draw.roadmap.sh/{roadmap_hash}", the page shows the message "You are not allowed to update this roadmap", and I can't make any changes to my roadmap.

![image](https://github.com/kamranahmedse/developer-roadmap/assets/69319899/9bb5b02f-c101-4b68-89a7-84790d258d12)

I think it might be a bug.

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by arikchakma** [comment]
Can you please provide the `roadmapId`?

**Comment by arikchakma** [comment]
@Philipelima Could you please check now?

**Comment by Philipelima** [comment]
@arikchakma, the problem still exists.

my roadmapId: 65222aeb91798c250de98b2b

**Comment by arikchakma** [comment]
Try creating a new roadmap, and let me know if you face the same issue.

**Comment by kalayu-ftsum** [comment]
I'm still facing this issue.

**Comment by arikchakma** [comment]
Did you try creating a new roadmap?

**Comment by kalayu-ftsum** [comment]
I tried multiple types still shows me this error.

**Comment by arikchakma** [comment]
Can you join me on a quick call and show me?

**Comment by kalayu-ftsum** [comment]
sure.

**Comment by arikchakma** [comment]
https://meet.google.com/rfj-vmvr-teu

**Comment by arikchakma** [comment]
@kalayu-ftsum We'll look into it and let you know.

**Comment by kalayu-ftsum** [comment]
Sorry I mistakenly closed the browser.

**Comment by arikchakma** [comment]
Okay, no worries. I'll let you know.

**Comment by MorganZhuRunzhe** [comment]
Hi Arik! @arikchakma I am facing the same problems. The roadmap id is 6534c211b5d7a4eb01f495de.

**Comment by kamranahmedse** [comment]
@MorganZhuRunzhe do you by any chance have multiple accounts? Can you try clearing up your cookies and try again?

**Comment by arikchakma** [comment]
> Hi Arik! @arikchakma I am facing the same problems. The roadmap id is 6534c211b5d7a4eb01f495de.

Let me know if we can jump on a quick call.

**Comment by kalayu-ftsum** [comment]
I think the cause for my issue is my github account email. that has changed since I signed to roadmap.sh. when I tried to login using another chrome with different email roadmap.sh has the updated email but not in this current chrome window.

**Comment by arikchakma** [comment]
@kalayu-ftsum Can you also book a meeting please?

**Comment by MorganZhuRunzhe** [comment]
> @MorganZhuRunzhe do you by any chance have multiple accounts? Can you try clearing up your cookies and try again?

Yes, Thx a LOT! The problem comes from that I used two different google accounts, one to log in the chrome and the other used to sign up the developer roadmap. The solution is to keep the account for chrome and developer roadmap consistent.
