### ISSUE TITLE
Not able to save Title and Description of Sub Topic.

### ISSUE THREAD

**Issue by OttlikG** [kamranahmedse/developer-roadmap#4567]
### What is the URL where the issue is happening

https://draw.roadmap.sh/6522dd8391798c250decfbdf

### What browsers are you seeing the problem on?

Chrome

### Describe the Bug

I can't edit the title or the description of a Sub Topic.

### Output from browser console (if any)

Unchecked runtime.lastError: The message port closed before a response was received.

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by kamranahmedse** [comment]
Can you please try in incognito. It seems to be be working fine for me. Probably has to do with some browser extension.

**Comment by dansholds** [comment]
Closing due to 7 monthes with no response from original author, happy to reopen if issue persists.
