### ISSUE TITLE
Expired link

### ISSUE THREAD

**Issue by WebsiteWitcher** [kamranahmedse/developer-roadmap#4568]
### What is the URL where the issue is happening

https://www.codecademy.com/learn/learn-html

### Describe the Bug

![image](https://github.com/kamranahmedse/developer-roadmap/assets/107634700/8ced9d79-00d8-491e-aea3-0a7f22cda013)
### Error 404 in Frontend Developer Roadmap (Beginner Version)### 
This link to be exact-
![image](https://github.com/kamranahmedse/developer-roadmap/assets/107634700/790b2d1e-b458-4a1c-a943-622c7f86e622)

### Participation

- [X] I am willing to submit a pull request for this issue.

**Comment by selvamuthukumaran1** [comment]
The link is working well, try a different browser

**Comment by AmineAouragh** [comment]
Normally if the link is working it should be working on all browsers
It worked for me in Google Chrome
![2023-10-18 12_34_04-Learn HTML _ Codecademy](https://github.com/kamranahmedse/developer-roadmap/assets/71039249/49f3cdfd-3d9e-4156-b4f8-e8154f7ea206)
