### ISSUE TITLE
ojrq.net unreachable for coursera links

### ISSUE THREAD

**Issue by pawann-2000** [kamranahmedse/developer-roadmap#4579]
### What is the URL where the issue is happening

https://www.ojrq.net/p/?return=https%3A%2F%2Fimp.i384100.net%2Fc%2F4863057%2F1164545%2F14726%3Fu%3Dhttps%253A%252F%252Fcoursera.org%252Fspecializations%252Fmathematics-machine-learning%2523courses%26svlink%3D8836798%26level%3D2%26srcref%3Dhttps%253A%252F%252Froadmap.sh%252F&cid=14726&tpsync=yes&auth=5651f6afbddd95a9

### What browsers are you seeing the problem on?

Chrome, Other

### Ojrq.net unreachable error in chrome and brave

Sorry I couldn't test in edge but chrome and brave is general enough I think.

Bug description: Ojrq.net is unreachable error spawning while accessing any of the Coursera links present on roadmaps.sh on brave and chrome (probably general to all the chromium based browsers).

Preconditions:

- User is present on any of the roadmaps as shown in the image below(registration/login is optional).
![image](https://github.com/kamranahmedse/developer-roadmap/assets/59572141/52802528-d2cb-4cb4-9c40-f1025625c093)

Steps to reproduce:

- Click on any coursera link present in the roadmap.

Bug screenshot:

Brave:
![image](https://github.com/kamranahmedse/developer-roadmap/assets/59572141/1ffbb3bc-24b6-4adb-93b3-33e77baf5d8a)

Chrome:
![image](https://github.com/kamranahmedse/developer-roadmap/assets/59572141/1185f2e6-8f1d-4d7b-85cd-cfa50c25df04)

Potential or direct causes for the bug:

- While looking out for a solution for this, I grabbed the link and opened it in firefox, the output is as shown in the screenshot below,
![image](https://github.com/kamranahmedse/developer-roadmap/assets/59572141/742270f0-5d35-4bc2-90b9-c468458109ed)

which shows that ojrq.net is an adware website that is being blocked from being accessed.

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by pawann-2000** [comment]
just for the context in the last screenshot, I have ublock origin setup on firefox which has the hosts file to warn about potential adware or malware sites.

**Comment by AmineAouragh** [comment]
I just checked and I encounter the same issue. Is this issue assigned to anybody? I can work on it.

**Comment by AmineAouragh** [comment]
UPDATE: I just fixed all the broken links in the AI/Data Scientist roadmap and created a pull request.

**Comment by pawann-2000** [comment]
Thanks @AmineAouragh, looking forward for the merge :)

**Comment by AmineAouragh** [comment]
Thank you :) 

There is one more update:

One link "Exploratory Data Analysis in Seaborn" in my branch with the correct link is linking to a guided project in coursera not a course. 

So that's another issue. I opened it. You can read more details here #4603

**Comment by pawann-2000** [comment]
Any updates on the issue? it's been 2 weeks :(

**Comment by dansholds** [comment]
After testing on multiple browsers, this no longer appears to be an issue (possibly due to @AmineAouragh PR he mentioned, but it's not linked 🙃)

I'm going to close the issue but feel free to re-open if the initial problem reoccurs.

**Comment by fviccia** [comment]
Having the same issue now.
With for example https://www.ojrq.net/p/?return=https%3A%2F%2Fimp.i384100.net%2Fc%2F4863057%2F1164545%2F14726%3Fu%3Dhttps%253A%252F%252Fcoursera.org%252Fspecializations%252Fmathematics-machine-learning%2523courses%26svlink%3D8836798%26level%3D1%26srcref%3Dhttps%253A%252F%252Froadmap.sh%252F&cid=14726&tpsync=yes&auth=575b67bada3a6966

**Comment by dansholds** [comment]
@fviccia are you using any ad blockers? what browser are you using?

**Comment by fviccia** [comment]
All adblockers disabled. In incognito mode it says "The link you clicked on is malformed. Contact the editor of the originating page."

**Comment by pawann-2000** [comment]
Works on brave browser actually, what browser are you using and which adblocker (if any)?
