### ISSUE TITLE
BackEnd road mixes Architecture road

### ISSUE THREAD

**Issue by GabGuz18** [kamranahmedse/developer-roadmap#4585]
### Roadmap URL

https://roadmap.sh/backend

### Suggestions

In Backend road is a section where mixes Architeecture road and repeat the same information in both roads. I think it would be great just to keep those sections in Architecture roads
![imagen](https://github.com/kamranahmedse/developer-roadmap/assets/57119079/a19e74d5-110a-493c-a602-2fd551ae71bb)

**Comment by AmineAouragh** [comment]
hey @GabGuz18 i am  sorry i couldn't understand your issue. Can you reformulate it? Or add more details please?
