### ISSUE TITLE
Tool used to make the flow chart?

### ISSUE THREAD

**Issue by ramswaroop** [kamranahmedse/developer-roadmap#46]
Not an issue but rather a question. Can you please name the tool you used to draw the flow charts in the README file?

**Comment by Pixceldev** [comment]
It's called Balsamiq. It's listed in the README under the 'Contribution' header. You must have just missed it!

**Comment by kamranahmedse** [comment]
Yes, [Balsamiq](https://github.com/kamranahmedse/developer-roadmap#-contribution)

**Comment by ramswaroop** [comment]
Thanks a lot @Pixceldev.
