### ISSUE TITLE
Change 'Course' label into 'Project' in Exploratory Data Analysis with Seaborn button in the AI/Data Scientist roadmap

### ISSUE THREAD

**Issue by AmineAouragh** [kamranahmedse/developer-roadmap#4603]
### Roadmap URL

https://roadmap.sh/ai-data-scientist

### This issue is related to the issue #4579 that says there are broken links in the [AI/Data Scientist roadmap](https://roadmap.sh/ai-data-scientist) that are supposed to redirect to Coursera.

I'll explain why both issues are related:

### I worked on a fix for the issue #4579 and I created a pull request [here](https://github.com/kamranahmedse/developer-roadmap/pull/4600)

So now in my branch all the links are working but I'm waiting for my commits to get merged so links become accessible "live".

BUT... 

When I was fixing the links there was one named "Exploratory Data Analysis with Seaborn" that was redirecting into a "guided project" in Coursera, not a "course". 

And in the roadmap there was a "course" label for that link meaning the link you are about to click redirects to a course which is... not true!

![2023-10-18 19_15_25-AI and Data Scientist Roadmap](https://github.com/kamranahmedse/developer-roadmap/assets/71039249/c54ea73d-c2d9-4e50-a19f-112cbe010ed8)

This is where the link is supposed to redirect the user (when my pull request that i linked to above get accepted and commits get merged)

![2023-10-18 19_28_48-Project_ Exploratory Data Analysis with Seaborn  1 5 hrs  _ Coursera](https://github.com/kamranahmedse/developer-roadmap/assets/71039249/8214c59e-7dfa-43b7-8091-4b36dfc01b01)

So as you can see that's not a course, but a guided project. So that's why i am suggesting it would be better to change the "course" label into "project" or "guided project".

I am open to work on that issue myself.

**Comment by kamranahmedse** [comment]
Hey there!

Looks like this issue has been hanging around for a bit without much action. Our roadmaps have evolved quite a bit since then, and a bunch of older issues aren't really applicable anymore. So, we're tidying things up by closing out the older ones to keep our issue tracker nice and organized for future feedback.

If you still think this problem needs addressing, don't hesitate to reopen the issue. We're here to help!

Thanks a bunch!
