### ISSUE TITLE
Roadmap mongoDB Data model and data type "Date"

### ISSUE THREAD

**Issue by AbdelrhmanX7** [kamranahmedse/developer-roadmap#4606]
### Roadmap URL

https://roadmap.sh/mongodb

### Suggestions

This section is incorrect based on the MongoDB documentation. You can't use $currentDate: {$type: 'date'} with insertOne. It's only available for update operations.
![Screenshot from 2023-10-19 10-49-37](https://github.com/kamranahmedse/developer-roadmap/assets/74682593/00c15d93-706a-4bab-bc29-cd0f8ef181ad)

For more details, refer to the MongoDB documentation on this topic:
https://www.mongodb.com/docs/manual/reference/operator/update/currentDate/

**Comment by AmineAouragh** [comment]
Hey @AbdelrhmanX7 that's right! 

Although I don't have experience with MongoDB but after a quick google search here is what I also found 

_In MongoDB, the $currentDate operator sets the value of a field to the current date. It can be set as either a Date or a timestamp type. The default is Date. $currentDate is an update operator, and can only be used when updating documents, not when inserting them (although it can be used in upsert operations)._ - [source](https://database.guide/mongodb-currentdate/#:~:text=In%20MongoDB%2C%20the%20%24currentDate%20operator,be%20used%20in%20upsert%20operations).

I can work on that issue if there is no problem.

**Comment by AbdelrhmanX7** [comment]
That's great. I will probably contribute to the Mongodb Roadmap I found some parts that need to get more clear
