### ISSUE TITLE
Another learning resource

### ISSUE THREAD

**Issue by lotosotol** [kamranahmedse/developer-roadmap#4614]
### Roadmap URL

https://roadmap.sh/cyber-security

### Suggestions

https://app.cybrary.it/ is a pretty neat learning resource as well

**Comment by callmebvk** [comment]
plz remove sign in with saml

**Comment by callmebvk** [comment]
forgot  your password  ? relocate to below of next block aslo center of div

**Comment by callmebvk** [comment]
decraes heading size  of sign in and shift to left side .

**Comment by callmebvk** [comment]
make password block for entering password for email.

**Comment by callmebvk** [comment]
shift left  side do not have account , not in middle of page
