### ISSUE TITLE
Rodmap.sh down

### ISSUE THREAD

**Issue by root-Manas** [kamranahmedse/developer-roadmap#4617]
### What is the URL where the issue is happening

https://rodmap.sh

### What browsers are you seeing the problem on?

Chrome

### Describe the Bug

Can't visit the main page of rodmap.sh. Seems down. Needs fix asap.

### Output from browser console (if any)

![image](https://github.com/kamranahmedse/developer-roadmap/assets/97402139/75b67886-14e9-4158-bba7-84690cf04686)

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by root-Manas** [comment]
Is there some kind of geolocation blocking in place? Able to access with VPN but not normally.

**Comment by kamranahmedse** [comment]
Looks like some networking/internet issue -- shouldn't be happening.

**Comment by AmineAouragh** [comment]
it's [roadmap.sh](roadmap.sh) not rodmap.sh - the website is working

**Comment by root-Manas** [comment]
> it's [roadmap.sh](https://roadmap.sh/) not rodmap.sh - the website is working
> 
> look at the picture you attached above, you are trying to access the wrong URL @root-Manas 
> 
> @kamranahmedse 

![Screenshot_2023-10-22-01-32-46-287_com.android.chrome.jpg](https://github.com/kamranahmedse/developer-roadmap/assets/97402139/7bbdcb43-4c76-4fcf-a4d8-ea6d89020898)

Checkout, it's still not working.

**Comment by AmineAouragh** [comment]
Oh ok gotcha. I don't know what is the problem. It's working for me on Chrome.
