### ISSUE TITLE
OOP, Algorithms, Data Structures, Design Patterns & etc

### ISSUE THREAD

**Issue by senart** [kamranahmedse/developer-roadmap#462]
On the top, there should be a bucket containing **programming fundamentals**. 

A person can learn some frameworks and languages, but jumping straight into those without the principles of programming is not sustainable and leads to a lot of confusion afterwards.

**Comment by chenyang48671155** [comment]
[https://www.sololearn.com/Codes/](url)

**Comment by kamranahmedse** [comment]
Have a look at the `Required for any path`.

But yeah, I have to improve that. Thanks for reporting.
