### ISSUE TITLE
Not able to install modules

### ISSUE THREAD

**Issue by thecrawler1** [kamranahmedse/developer-roadmap#4623]
### What is the URL where the issue is happening

roadmap.sh

### What browsers are you seeing the problem on?

Other

### Describe the Bug

Getting below error when npm i

`npm ERR! code 128
npm ERR! An unknown git error occurred
npm ERR! command git --no-replace-objects ls-remote ssh://git@github.com/roadmapsh/web-draw.git
npm ERR! ERROR: Repository not found.
npm ERR! fatal: Could not read from remote repository.
npm ERR!
npm ERR! Please make sure you have the correct access rights
npm ERR! and the repository exists.`

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by kamranahmedse** [comment]
This should be fine now. Thank you for reporting.
