### ISSUE TITLE
Template Engines

### ISSUE THREAD

**Issue by GHNewbiee** [kamranahmedse/developer-roadmap#463]
Hi,

I think a reference about template engines should be made. It is a category which exists. Maybe not so important but templates exist and are used.

**Comment by Michael-J-Scofield** [comment]
Kind of part of the learn a framework section. Don't you think?

**Comment by Z3n3K** [comment]
@Michael-J-Scofield not necessarily. You can perfectly use for example Pug/Jade without any framework. 
I've done.

I think definitely this guide should have a **template engines** category and mention: Pug, Handlebars, EJS, Nunjucks etc...

**Comment by kamranahmedse** [comment]
This has been fixed and will be published in the coming release. Thank you 🙏
