### ISSUE TITLE
Diversity in languages

### ISSUE THREAD

**Issue by Gmenezes3** [kamranahmedse/developer-roadmap#4633]
### Feature Description

I would like to request a suggestion for the creation of a study plan that can be translated into different languages, including Brazilian Portuguese (PT-BR). I believe that making this roadmap available in multiple languages would be of great assistance to a wide range of people, enabling them to access and learn from the provided content with ease.

**Comment by gu-alves** [comment]
I would be happy to contribute to PT-BR!

**Comment by arikchakma** [comment]
We are now closing any issues requesting new features/roadmap to clean up the issues.

However, this doesn’t mean that the requested feature/roadmap won’t be added to the website. We are putting it in the backlog and will add it to the website depending on how it ranks in the backlog or sooner if we find someone interested in adding that feature/roadmap. Thank you for the request though! :pray:
