### ISSUE TITLE
dark mode

### ISSUE THREAD

**Issue by Optimus4563** [kamranahmedse/developer-roadmap#4634]
### Feature Description

a simple toggle button to change the page to darkmode would be helpful

**Comment by AbdelrhmanX7** [comment]
That's intersting
does roadmap has abilty to switch from light mode to dark mode?

**Comment by mrKingsammy** [comment]
> That's interesting does roadmap has abilty to switch from light mode to dark mode?
I don't think the Feature has been added yet but it would look cool if it does.

**Comment by yashas-hm** [comment]
Can I work on this if the maintainers agree? @kamranahmedse

**Comment by arikchakma** [comment]
We are now closing any issues requesting new features/roadmap to clean up the issues.

However, this doesn’t mean that the requested feature/roadmap won’t be added to the website. We are putting it in the backlog and will add it to the website depending on how it ranks in the backlog or sooner if we find someone interested in adding that feature/roadmap. Thank you for the request though! :pray:
