### ISSUE TITLE
Error on loading any roadmap on Chromium 83

### ISSUE THREAD

**Issue by viniciusalveshax** [kamranahmedse/developer-roadmap#4636]
### What is the URL where the issue is happening

https://roadmap.sh/frontend

### What browsers are you seeing the problem on?

Other

### Describe the Bug

I using Chromium v83 (installed via apt on PopOS 20.04) and all roadmaps are showing the same problem

"There was an error.
Try loading the page again. or submit an issue on GitHub with following:

this.containerEl?.replaceChildren is not a function
TypeError: this.containerEl?.replaceChildren is not a function at https://roadmap.sh/_astro/hoisted.c7b3102e.js:1:1484"

![Captura de tela de 2023-10-28 13-41-02](https://github.com/kamranahmedse/developer-roadmap/assets/548450/90308a61-c894-4193-ad5b-1c6204064bd1)

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by kamranahmedse** [comment]
This should be fine now. Can you please verify?

**Comment by viniciusalveshax** [comment]
> This should be fine now. Can you please verify?

Roadmaps are working now. Thank you very much.

PS: Your repository is awesome!
