### ISSUE TITLE
Outdated X (f.k.a. Twitter) Logo

### ISSUE THREAD

**Issue by hanzalahwaheed** [kamranahmedse/developer-roadmap#4641]
### What is the URL where the issue is happening

https://roadmap.sh/best-practices/api-security

### What browsers are you seeing the problem on?

Other

### Describe the Bug

The twitter logo is old. It must be changed to X.

### Output from browser console (if any)

![image](https://github.com/kamranahmedse/developer-roadmap/assets/101456741/71a87372-c8b2-4861-a16a-09bc3c56eb7a)

### Participation

- [X] I am willing to submit a pull request for this issue.

**Comment by hanzalahwaheed** [comment]
Am I going to be assigned to this Issue or I can directly work on it and create a PR?

**Comment by kamranahmedse** [comment]
@hanzalahwaheed go ahead with the PR
