### ISSUE TITLE
Vue Developer: add Vitest to the testing ecosystem node

### ISSUE THREAD

**Issue by joao-salomao** [kamranahmedse/developer-roadmap#4644]
### Roadmap URL

https://roadmap.sh/vue

### Suggestions

[Vitest](https://vitest.dev/) is a unit testing framework designed specifically for this purpose, created and maintained by Vue / Vite team members. [Vitest is now the oficial recommended package for testing Vue applications](https://vuejs.org/guide/scaling-up/testing.html#recommendation) so it definitely should be part of this roadmap.

### Participation
- [ ] I am willing to submit a pull request for this issue.

**Comment by IvanKushchenko** [comment]
I think it should be added as soon as possible
