### ISSUE TITLE
Duplicate in Computer Science Roadmap

### ISSUE THREAD

**Issue by Monikacg** [kamranahmedse/developer-roadmap#4646]
### What is the URL where the issue is happening

https://roadmap.sh/computer-science

### What browsers are you seeing the problem on?

Chrome

### Describe the Bug

Under Databases, the category "Transactions" are shown twice.

![Skjermbilde 2023-11-01 121326](https://github.com/kamranahmedse/developer-roadmap/assets/21344470/646bdcc3-8690-4906-9b3e-9a1054ee662d)

### Participation

- [x] I am willing to submit a pull request for this issue.

**Comment by callmebvk** [comment]
can i contribution in this issue ?

**Comment by marcthayer** [comment]
Also mentioned here: https://github.com/kamranahmedse/developer-roadmap/issues/3804
