### ISSUE TITLE
Add Kotlin for server side programming language

### ISSUE THREAD

**Issue by WarrenFaith** [kamranahmedse/developer-roadmap#4652]
### Roadmap URL

https://roadmap.sh/server-side-game-developer

### Suggestions

Kotlin would be a suitable programming language for the server side. I think it brings a lot of benefits as it also is available for other platforms like mobile dev. As Java is mentioned, Kotlin should be mentioned too.
Scala could also be a good thing to add...

**Comment by I-MirzaBaig** [comment]
Indeed yes, its has numerous benefits on the development server side too, using FrameWorks of Kotlin for example : Spring, Quarkus etc....
