### ISSUE TITLE
Add Kotlin

### ISSUE THREAD

**Issue by iogilarb** [kamranahmedse/developer-roadmap#4661]
### Roadmap URL

https://roadmap.sh/spring-boot

### Suggestions

Please Add Kotlin, it's stable now and many Developer moved to Kotlin

**Comment by tom2411** [comment]
Yes I support this suggestion because there is a lot of benefit to have Java and Kotlin RoadMap since there interoperable.
Furthermore, we can see that there are more and more people trying to learn Kotlin because of InteliJ pushing the language forward.
