### ISSUE TITLE
Links not working 

### ISSUE THREAD

**Issue by TankEngine-ish** [kamranahmedse/developer-roadmap#4668]
### What is the URL where the issue is happening

https://roadmap.sh/nodejs

### What browsers are you seeing the problem on?

Firefox, Chrome, Microsoft Edge

### Describe the Bug

When you click on the "Visit the following resources to learn more:" links inside the "Node. js vs Browser" and "Running Node.js Code" elements they don't work anymore. You get redirected to the Node.js website but the link throws an error: 404: Page could not be found
ENOENT: no such file or directory

I found the links to the same topics but actually working: 
1.  "Node. js vs Browser"  - https://nodejs.org/en/learn/getting-started/differences-between-nodejs-and-the-browser

2.  "Running Node.js Code" - https://nodejs.org/en/learn/command-line/run-nodejs-scripts-from-the-command-line

If these are the correct topics that were originally meant to be in the two elements I think it's safe to say that they can be replaced.

P.S. For a noob like me this is a fantastic website.

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by ezerindeed** [comment]
Please, can I get assigned to this?

**Comment by kamranahmedse** [comment]
@ezerindeed sure, go ahead

**Comment by ezerindeed** [comment]
@kamranahmedse Thank you, I've created a pull request.
