### ISSUE TITLE
Unable to login or sign up using GitHub or other providers.

### ISSUE THREAD

**Issue by anishshobithps** [kamranahmedse/developer-roadmap#4670]
### What is the URL where the issue is happening

https://roadmap.sh/login

### What browsers are you seeing the problem on?

Firefox, Chrome, Microsoft Edge, Other

### Describe the Bug

This issue is also observed at https://roadmap.sh/signup

The option for Authentication comes up but vanishes quickly, checked with all the browsers I use and as well as on Android phone of mine.

Note: I have also checked on incognito mode.

Video Link: https://i.imgur.com/3KTroxq.mp4

### Output from browser console (if any)

Console Errors: https://sourceb.in/ZnsOayFqt2

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by arikchakma** [comment]
Apparently, there is a bug in the latest version of Astro that caused this.
Here's the workaround for now if anyone is interested. #4676 

Disclaimer: Don't look into the quality of the Pull Request.
