### ISSUE TITLE
resources 

### ISSUE THREAD

**Issue by gardellafacu** [kamranahmedse/developer-roadmap#4671]
### What is the URL where the issue is happening

https://roadmap.sh/frontend

### What browsers are you seeing the problem on?

Microsoft Edge

### Describe the Bug

it doesn´t show any resources when you click on the section. 

### Participation

- [X] I am willing to submit a pull request for this issue.

**Comment by fxt1998** [comment]
lo pudiste solucionar?
you were able to solve it?

**Comment by arikchakma** [comment]
Apparently, there is a bug in the latest version of Astro that caused this.
Here's the workaround for now if anyone is interested. #4676 

Disclaimer: Don't look into the quality of the Pull Request.
