### ISSUE TITLE
Links aren'r working

### ISSUE THREAD

**Issue by shatua-san** [kamranahmedse/developer-roadmap#4672]
### What is the URL where the issue is happening

https://roadmap.sh/qa

### What browsers are you seeing the problem on?

Safari

### Describe the Bug

When i click, with left click in any of  the concepts buttoms,  it  doesn'r redirect me to theory a link as ussual.

https://github.com/kamranahmedse/developer-roadmap/assets/117756417/8228909f-a74a-4e1f-939e-e8ed749d5249

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by fxt1998** [comment]
you were able to solve it?

**Comment by arikchakma** [comment]
Apparently, there is a bug in the latest version of Astro that caused this.
Here's the workaround for now if anyone is interested. #4676 

Disclaimer: Don't look into the quality of the Pull Request.
