### ISSUE TITLE
bug in roadmap when choosing content

### ISSUE THREAD

**Issue by fxt1998** [kamranahmedse/developer-roadmap#4675]
### What is the URL where the issue is happening

https://roadmap.sh/

### What browsers are you seeing the problem on?

Chrome

### Describe the Bug

When entering a roadmap, and then choosing a topic, it does not open, it remains bugged

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by arikchakma** [comment]
Apparently, there is a bug in the latest version of Astro that caused this.
Here's the workaround for now if anyone is interested. #4676 

Disclaimer: Don't look into the quality of the Pull Request.
