### ISSUE TITLE
Road-map for full-stack?

### ISSUE THREAD

**Issue by Tanuj69** [kamranahmedse/developer-roadmap#468]
i'd appreciate if there's a road map for full stack

**Comment by amejiarosario** [comment]
front-end + backend = full stack roadmap

**Comment by Tanuj69** [comment]
but the thing is that I want to know whether you should do full front end first then full back-end or a specific order is present

**Comment by amejiarosario** [comment]
Well, you can start learning backend but just enough to setup a sever, serve a website and API endpoints. Then you can go as deep as you want on the front-end roadmap. 

Depending on the projects you work on you will have to go deeper on one or another

**Comment by Tanuj69** [comment]
To be honest i'm so in out of track i don't know what to do first 
my main motive is to land a job as quick as apossible
currently I can build static websites  using html,css and some js

**Comment by amejiarosario** [comment]
If you already know html, css and js, go the front-end route first. To find a job quickly, you can learn  Reactjs and you would get plenty of jobs

**Comment by Flemo7** [comment]
Front-end then back-end would be ideal, Full-stack takes some time though, its no joke. 

Assuming you know HTML5, CSS3, JS should have no problem getting a job, even if its just building Wordpress websites from .PSD. Whilst you study etc.

See here for another users helpful guide on full-stack dev.

https://github.com/bmorelli25/Become-A-Full-Stack-Web-Developer

**Comment by Tanuj69** [comment]
Well thanks for the link @Flemo7  appreciate the help
