### ISSUE TITLE
Bookmark icon resets when page is refreshed

### ISSUE THREAD

**Issue by loonaticx** [kamranahmedse/developer-roadmap#4683]
### What is the URL where the issue is happening

https://roadmap.sh/cyber-security

### What browsers are you seeing the problem on?

Chrome

### Describe the Bug

Sometimes, it does persist, but it will go away after I reload the site with shift+f5.
![DMXscC8](https://github.com/kamranahmedse/developer-roadmap/assets/8785058/11cab526-22fd-46cc-96ed-0a40eecb9137)

### Participation

- [X] I am willing to submit a pull request for this issue.

**Comment by kamranahmedse** [comment]
Fixed in https://github.com/kamranahmedse/developer-roadmap/commit/be02cc59ea9204e9912f6ea5658942456ae3a76b. Thanks!
