### ISSUE TITLE
Cybersecurity Roadmap: Understand Audience section cannot be selected

### ISSUE THREAD

**Issue by loonaticx** [kamranahmedse/developer-roadmap#4684]
### What is the URL where the issue is happening

https://roadmap.sh/cyber-security

### What browsers are you seeing the problem on?

Chrome

### Describe the Bug

I cannot click on any of the options in the "Understand Audience" section of the roadmap.

I have tried refreshing the page & clearing cache, but problem still persists.

![UDjw66G](https://github.com/kamranahmedse/developer-roadmap/assets/8785058/aca1b01c-7564-4d51-a8da-23128b0418f5)

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by FernandoPazCavalcante** [comment]
Inspecting the HTML in the browser, we can see that these components are outside a clickable group.
<img width="720" alt="Screenshot 2023-11-16 at 12 03 14" src="https://github.com/kamranahmedse/developer-roadmap/assets/32584544/c7e19918-7a29-4e1f-9da7-d91703f7249d">

We just need to know whether this components doesn't have any content and therefore is not in a clickable group or it should really be in a clickable group.

**Comment by AhmadMadi** [comment]
Understand Audience doesn't seem to have any children in the `.json` file. I do not think this is a bug, there is no content for these.

**Comment by FernandoPazCavalcante** [comment]
Maybe no content topics should have a flag or a notification showing that there is no content.

**Comment by dansholds** [comment]
duplicate of https://github.com/kamranahmedse/developer-roadmap/issues/4302
