### ISSUE TITLE
Consider WebGPU and WGSL in Game developer client roadmap

### ISSUE THREAD

**Issue by felixsnz** [kamranahmedse/developer-roadmap#4685]
### Roadmap URL

https://roadmap.sh/game-developer

### Suggestions

WebGPU is a recent API specification for computer graphics that is quickly growing, some say it has the potential to becaome the standard in computer graphics.

The WebGPU specification is not limited to the web and browsers, some implementations like wgpu (in rust) have adapted it to be able to create native apps with modern graphics APIs, like vulkan, metal and directx12 as backend.

so i think it will be important to mention.

**Comment by Blainegith** [comment]
+1
