### ISSUE TITLE
Android Roadmap: Too Legacy Based

### ISSUE THREAD

**Issue by matthew-levene** [kamranahmedse/developer-roadmap#4692]
### Roadmap URL

https://roadmap.sh/android

### Suggestions

With the official release of Jetpack Compose, this roadmap should encourage developers to learn the new UI framework as opposed to the legacy classes and views expected of a XML/viewbinding implementation

For example, consider a LazyColumn over a RecyclerView/Adapter pattern, a TextField over a EditText and a Text composable over a TextView. 

This new UI framework conforms to the latest material design principles and is the approach Google is now advocating on all their Android developer docs.

In terms of patterns, lets remove MVC, most apps nowaways would be MVVM/MVI with some legacy apps using MVP. 

I guess it wiuld be a good idea to review current trends and adjust this roadmap to align with them

**Comment by Kaya-Sem** [comment]
Indeed, the android tree is outdoutdated. Jetpack Compose is a way bigger deal than is currently on that roadmap.
