### ISSUE TITLE
Some minor changes for the Rust roadmap

### ISSUE THREAD

**Issue by joshua-mo-143** [kamranahmedse/developer-roadmap#4695]
### Roadmap URL

https://roadmap.sh/rust

### Suggestions

- SQLx does not actually support MSSQL officially anymore after the release of 0.7 due to it requiring licenses, which you can find more about on the GitHub repo [now that they've updated it.](https://www.github.com/launchbadge/sqlx). Launchbadge (who own SQLx) want to have some kind of paid product offering for it - this should probably be noted somewhere.

As an aside: I'm slightly surprised the Axum framework isn't on here given it's supported by the Tokio team.

Otherwise, great work on the roadmap!

**Comment by sebmaz93** [comment]
Thanks for the suggestions, I've made the roadmap I had to make few changes but I've submitted few months ago and then forgot to make the changes, in my mind also things for WASM like Leptos, Dioxus.

**Comment by kamranahmedse** [comment]
Thanks @joshua-mo-143 and @sebmaz93!

@sebmaz93 feel free to open a new issue with the suggestions (we will also allow the modifications using the roadmap editor soon to make it easier for you to change). I have added axum though.
