### ISSUE TITLE
Game Developer Roadmap modification

### ISSUE THREAD

**Issue by Neilk1021** [kamranahmedse/developer-roadmap#4699]
### Roadmap URL

https://roadmap.sh/game-developer

### Suggestions

In terms of video game programming, the guide is excellent. However, I'd recommend either renaming it to something like "Game Programmer" or adding content that pertains to game design. The title is slightly misleading as game design is a multidisciplinary field that requires much more than just programming.

**Comment by PuzzleZach** [comment]
Absolutely agree here, Game Engine Programmer might be better and the Engine-specific components can be blown up to become a Game Developer roadmap on its own right.
