### ISSUE TITLE
Your Chart is for 2016 (or 2015) rather than 2017

### ISSUE THREAD

**Issue by mahald** [kamranahmedse/developer-roadmap#47]
Frontend ONLY: 

In 2017 throw jQuery away it's for the guys of yesterday...
if u use:

- angular (angular2) (angular.io)   (AngularJS usually means angular1)
- angular-cli (https://www.npmjs.com/package/@angular/cli)
- with bootstrap (css only) (use component ng-bootstrap for js (from google))
- RxJs (use Observables for async callback stuff such as http.post ... !!)

you can pretty mutch forget about: 

- CSS->Preprocessors
- jQuery
- TaskRunners
- Testing
- MooduleLoader
- JavaScript-> Choose a Framework

as angular-cli sets all this up for u and configures it.
it does "compiles" all js and css.
you can debug in realtime just like in C# (with visual studio code)

Some nice angular components:
- ng-bootstrap (https://ng-bootstrap.github.io/#/home)
- for Charts use: https://www.npmjs.com/package/ng2-nvd3
- maybe font aewsome (works very well)

angluar-cli is using typescript.
angular-cli uses: webpack, Karma+Jadmine+protractor, ..

wiht the angluar-cli you can quickly scaffold:

- Component 	ng g component my-new-component
- Directive 	ng g directive my-new-directive
- Pipe 	ng g pipe my-new-pipe
- Service 	ng g service my-new-service
- Class 	ng g class my-new-class
- Guard 	ng g guard my-new-guard
- Interface 	ng g interface my-new-interface
- Enum 	ng g enum my-new-enum
- Module 	ng g module my-module

angular is a fully blown framework/enviroment, rahter than just a library such as react.

AND dont' forget to use "Visual Studio Code" (Free. Runs on linux,mac, win) what gives u awesome intellisense! (with typescript) worlds best editor for angular.

**Comment by kamranahmedse** [comment]
It looks like you want me to remove everything from the frontend part and only include `angular-cli` ..because it does everything for you! Thanks but no thanks.

jQuery part was intentional, because of the ease of DOM manipulation. I still recommend the beginners to use jQuery while learning Javascript and work their way up.

For `Angular JS`, yes it was typo. I meant `Angular`, I will update it.

Thank you.
