### ISSUE TITLE
Create releases to mark the roadmap years

### ISSUE THREAD

**Issue by lukewhitehouse** [kamranahmedse/developer-roadmap#470]
Hey there,

First of all I just wanted to say that this is a great resource that I've used countless times myself and have encouraged others to look at it when they're in a rut with their learning. I'm currently writing a blog post on the topic of how our industry is changing and to show a comparison I thought it'd be cool to show the differences a year has made to your roadmap.

It got me thinking that it'd be really nice for archivability to create a tag/release for the different year versions. Thoughts?

**Comment by kamranahmedse** [comment]
Makes sense. I have [tagged the 2017 version here](https://github.com/kamranahmedse/developer-roadmap/releases)
