### ISSUE TITLE
Perl is a useful language to be familiar with

### ISSUE THREAD

**Issue by pjarosak** [kamranahmedse/developer-roadmap#471]
While not popular (I.e. trendy), it exists in a lot environments and tools and it is useful to at least learn the basics.

**Comment by davehodg** [comment]
I second this. Not mentioning Perl is pretty bigoted. booking.com, Zoopla, Net a Porter would like a word. As well as the Perl conference in London later this year.

**Comment by Ronkiro** [comment]
I think Perl is very important, but i wouldn't recommend it for a "focused to beginner" language place. Maybe this is a point to the reason it isn't on the list (Like C++)
