### ISSUE TITLE
Careers or Technologies?

### ISSUE THREAD

**Issue by CarloMartini** [kamranahmedse/developer-roadmap#4716]
### Feature Description

Now that the list of "paths" is becoming large, I think there should be some kind of distinction between what is "Career Path" and what is "Technology Path": for example, "DevOps [Engineer]" is a job position for which you will need multiple technologies, while "Docker" is a single technology and by itself it probably won't be enough even to get a job in the IT sector.

**Comment by arikchakma** [comment]
We are now closing any issues regarding bug fixes or requesting new features/roadmap to clean up the issues.

However, this doesn’t mean that the requested bug fix/feature/roadmap won’t be fixed/added to the website. We are putting it in the backlog and will add it to the website depending on how it ranks in the backlog or sooner if we find someone interested in fixing the bug or adding that feature/roadmap. Thank you for the request though! :pray:
