### ISSUE TITLE
Add static site generators (GatsbyJs..)

### ISSUE THREAD

**Issue by zakariaharti** [kamranahmedse/developer-roadmap#472]

**Comment by Masturedehghanipoor** [comment]
سلام جناب کامران
امیدوارم شما تسلط به زبان فارسی داشته باشید
من از شما برای بازیابی حساب قفل شده ی گوگل خودم کمک میخواهم
میتونید لطفا این کمک رو به من بکنید؟
My address Google account is;
valiollahnazeri@gmail.com
 قبلا از کمک شما سپاسمندم
با احترام
