### ISSUE TITLE
Update copy-paste for Content & Links in custom roadmaps

### ISSUE THREAD

**Issue by haslie22** [kamranahmedse/developer-roadmap#4728]
### Feature Description

When creating a custom roadmap and attempting to copy (`cmd/ctrl + C` or selecting `Copy` from the context menu) or cut (`cmd/ctrl + X` or selecting `Cut` from the context menu) a piece of text in the **Content & Links** panel, you may accidentally paste a block that you are describing.

It would be much more intuitively clear for the user to have the ability to copy or cut text when working in the **Content & Links** panel using the aforementioned combinations.

Meanwhile, when working in the **Properties** panel, the option to cut or paste blocks should remain available.

**Comment by bastienpetit** [comment]
I'm experiencing the sames issues with the "Content & Links" description field. 

Here is to illustrate:

### Copy / paste

https://github.com/kamranahmedse/developer-roadmap/assets/194437/7feacc7f-494f-4073-a802-76a06b64fba5

### Cut / paste

https://github.com/kamranahmedse/developer-roadmap/assets/194437/415d08a7-d23f-4254-b405-03f5d030ebc0

I tried going around the issue by doing all the writing in a separate text editor, but I can't copy what I've written in "Contents & Links" and paste it into a different app:

https://github.com/kamranahmedse/developer-roadmap/assets/194437/2ef72e45-6eb4-46ab-8054-71a07063839d

Note: 

- These issues only affects the description field, the title field has none of these problems
- Chrome 119.0.6045.159 (macOS)
- No errors in the console

Thanks in advance for your help!
