### ISSUE TITLE
Add a Robotics enginner/Developer roadmap

### ISSUE THREAD

**Issue by Jorfy69** [kamranahmedse/developer-roadmap#4735]
### Feature Description

Could u make a roadmap for someone trying to get into robotics engineering and programming.

**Comment by arikchakma** [comment]
We are now closing any issues requesting new features/roadmap to clean up the issues.

However, this doesn’t mean that the requested feature/roadmap won’t be added to the website. We are putting it in the backlog and will add it to the website depending on how it ranks in the backlog or sooner if we find someone interested in adding that feature/roadmap. Thank you for the request though! :pray:
