### ISSUE TITLE
DevOps “Beginner View” Printing Option

### ISSUE THREAD

**Issue by ACloseShave** [kamranahmedse/developer-roadmap#4737]
### Current state:
Right now, viewers can print the **Detailed version** version of the **DevOps roadmap** and they can switch to view the **Beginner version** for a simplified presentation of the core skills and technology.

However, when printing only the **Detailed version** can be saved as a PDF or sent to print.

### Desired state:
Please make the **Beginner version** printable/save as PDF for those who want a trimmed down version of the roadmap.

**Comment by arikchakma** [comment]
We are now closing any issues requesting new features/roadmap to clean up the issues.

However, this doesn’t mean that the requested feature/roadmap won’t be added to the website. We are putting it in the backlog and will add it to the website depending on how it ranks in the backlog or sooner if we find someone interested in adding that feature/roadmap. Thank you for the request though! :pray:
