### ISSUE TITLE
DevOps is not a career path

### ISSUE THREAD

**Issue by glend** [kamranahmedse/developer-roadmap#474]
I'm a bit confused why DevOps is listed as a path, but in reality DevOps needs to be practiced by software engineers, operations, QA and what else. The formal definition of DevOps is not a profession. If you somehow learn all in this graph, and you have no clue about DevOps practices then you aren't doing DevOps at all.

Right now the career path looks like a mix of operations, SRE and developer, but only tools and nothing else. And some of these tools should be in 'developer' category as well: cli tools, app monitoring, configuration management, debugging containers etc.

This is a misrepresentation of what DevOps actually is imo.

**Comment by affbedran** [comment]
Imo, you are right on most aspects. You should, however, consider that some enterprises and groups tend to centralize SCM and CI/CD tooling (as well as other DevOps related stuff) to a specific professional, which may be called  Leader of DevOps or smth else on these lines.

If you think about it that way, it makes absolute sense to isolate it as a career path. But again, that is just my opinion @glend.

**Comment by ericjeker** [comment]
I am not sure where you read the words "career path"?  Maybe I missed something, but to me those are roadmaps or, as explained in the disclaimer: 

> The purpose of this roadmap is **to give you an idea about the landscape** and to guide you if you are confused about what to learn next...

So yeah, you might want to learn a bit of DevOps whether you are a frontend or backend developer but most probably you don't need to dive deep into every aspect of it as long as you know those tools exist for the day you're going to need them or the day you want to improve your development process.

**Comment by glend** [comment]
I think there should be something clearing out that DevOps is not the same concept as the other paths. Unlike frontend or backend developer, it's not something you can be, but a set of practices meant for the whole organization/team, just like Agile.

Adoption of tools like all those listed in the roadmap does not mean DevOps.

**Comment by trevorbennett** [comment]
@glend While industry is trending away from dev ops as a role and towards dev ops as a developer specialization, there are currently no shortage of dev ops jobs on dev ops teams out there, and I wouldn't be surprised if there are still full time dev ops jobs a decade out from now.

**Comment by jpita** [comment]
Most of my colleagues working as devops a few years ago are moving to tooling developers, building docker and k8s infrastructures and what not.
None of them were developers or software engineers at any time, they started as sysadmins and learned how to code and evolved.
This seems like a career to me (most of them have the role of SRE now) and a very very well paid one...

**Comment by glend** [comment]
@jpita It's not a career, what you are talking about is a bad implementation of DevOps from the upper management, an antipattern, see the antipatterns at https://web.devopstopologies.com/. Just because someone did it doesn't mean it's right. Obviously I already know this because every other job position says 'DevOps Engineer', whatever that means.

You are confusing it now with SRE. SRE is an actual job position (I work as SRE). At Google they say 'SRE implements DevOps' because many of the practices are fulfilled. But that's because SRE try to make developers self-service so it removes the barriers (this is the DevOps part, not the SRE position itself).

@trevorbennett That's not true at all. The industry implemented DevOps wrong. The antipatterns didn't work so now they realize that they have to apply DevOps as principles, not just add more roles. They are just shifting to implement it right now.

DevOps as a role was wrong to begin with.

Check https://www.linux.com/blog/what-devops-patrick-debois-explains, the guy who coined this term.

**Comment by glend** [comment]
Keep misinforming people!! DevOps is about collaboration, communication, breaking down silos and so on. It has nothing to do with tooling.

All the tools listed here are concepts that predate DevOps.

Would you also say that using X issue/project tracker automatically makes your team be Agile? Of course not, it isn't Agile until your team follows the methodology. The tooling offers you different ways to handle things.

And a DevOps roadmap shouldn't be adoption of tools but adoption of concepts/processes/mindset. One could learn ALL the tooling listed and still know nothing about DevOps and not providing any meaningful change to his company/team.

**Comment by Shyam-Chen** [comment]
SRE vs DevOps: https://cloudplatform.googleblog.com/2018/05/SRE-vs-DevOps-competing-standards-or-close-friends.html?m=1

**Comment by atulkumarpccs** [comment]
there are lot of job related to DevOps so the concerns person put it as a path.

**Comment by glend** [comment]
> there are lot of job related to DevOps so the concerns person put it as a path.

What do you mean with "related to DevOps". The whole engineering department is related to DevOps. It's not a single position.

**Comment by jakejarvis** [comment]
<img width="733" alt="screen shot 2019-01-08 at 4 29 28 pm" src="https://user-images.githubusercontent.com/1703673/50859901-98099b80-1362-11e9-849b-bb028711ceb7.png">

@glend Not sure where you saw literally anywhere in the repo referring to these as career paths. The intro image even shows DevOps as an extension to back-end development, which I do agree with you on.

FYI, your personal website is down – perhaps you could learn a bit from the DevOps roadmap before nitpicking everyone's comments and being so critical of @kamranahmedse's hard work? :)

**Comment by JohanLander** [comment]
DevOps is a way of living and how you should think... Not a title !

**Comment by glend** [comment]
@jakejarvis Lol I have no personal website. Also since when replying to people about the topic at hand called nitpicking? Look at yourself.

Also regarding DevOps extending from backend, I thought I was clear that I don't agree that it goes that way.

**Comment by jakejarvis** [comment]
@glend I think all of us are in agreement about DevOps being more of a way of thinking than a corporate position, but are rather confused at how you want the roadmaps to be fixed. And I'm sure you'd also agree that the tools in the DevOps roadmap are far too important in 2019 to just delete the entire thing from the repo.

So why not put in some time this week and make an actual pull request so we can see some practical changes since you're so passionate about this? I'm sure it would be accepted. I don't mean to come off as combative, let me know if you'd want any help with that. 😊

**Comment by learninglincoln** [comment]
hjnl
