### ISSUE TITLE
Oracle Networks > Understanding Oracle Networks is a 404

### ISSUE THREAD

**Issue by danrfletcher** [kamranahmedse/developer-roadmap#4740]
### What is the URL where the issue is happening

https://roadmap.sh/blockchain

### What browsers are you seeing the problem on?

Chrome

### Describe the Bug

The article Oracles > Oracle Networks > Understanding Oracle Networks is a 404

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by dansholds** [comment]
Fixed in #4923
