### ISSUE TITLE
Add Fetch API

### ISSUE THREAD

**Issue by sxnaprkhr** [kamranahmedse/developer-roadmap#475]
Fetch API should be added instead of XMLHttpRequest(XHR) API as fetch uses promises which enables a simpler and cleaner API.

**Comment by jmas** [comment]
@sxnaprkhr It should be added as option, but do not **instead**.

**Comment by miraage** [comment]
Understanding both Fetch/XHR is required for frontend.

**Comment by kamranahmedse** [comment]
Fixed. Thanks
