### ISSUE TITLE
Service mesh description suggests that every sidecar proxy is called Envoy

### ISSUE THREAD

**Issue by jakkaz** [kamranahmedse/developer-roadmap#4751]
### What is the URL where the issue is happening

https://roadmap.sh/backend

### Describe the Bug

The problem is in the general description of a service mesh.

> In a service mesh, each microservice is typically represented by an instance of a lightweight, transparent proxy called an “envoy.” The envoys handle the communication between microservices and provide features such as load balancing, routing, and security.

Considerations for the fix of the service mesh section:
- In a service mesh microservice is represented by a sidecar proxy and the business logic itself (service/pod if we talk k8s).
- `Envoy` is only an example of the sidecar proxy to choose from (for instance `Envoy` is used by Istio). Another example of the sidecar proxy is `micro-proxy` used by Linkerd service mesh. I suggest naming it just a proxy and not `Envoy`, otherwise it just indicates that `Envoy ` is always used.

Service mesh source file: https://github.com/kamranahmedse/developer-roadmap/blob/master/src/data/roadmaps/backend/content/115-architectural-patterns/105-service-mesh.md

### Participation

- [X] I am willing to submit a pull request for this issue.

**Comment by kamranahmedse** [comment]
Thanks @jakkaz -- feel free to submit a PR
