### ISSUE TITLE
Technical Writer Roadmap Suggestions

### ISSUE THREAD

**Issue by Vaishnavi2903** [kamranahmedse/developer-roadmap#4756]
### Roadmap URL

https://roadmap.sh/technical-writer

### Suggestions

Technical writing has evolved over time and companies are constantly adopting DITA and XML Framework. I think the roadmap right now is missing any information related to DITA or Structured Writing. The technical writing roadmap is way more focused technical content writing rather than technical writing. So maybe adding DITA and other forms of Structured writing would really benefit the budding technical writers.

**Comment by sootynemm** [comment]
Agreed.

**Comment by arikchakma** [comment]
We are now closing any issues requesting new features/roadmap to clean up the issues.

However, this doesn’t mean that the requested feature/roadmap won’t be added to the website. We are putting it in the backlog and will add it to the website depending on how it ranks in the backlog or sooner if we find someone interested in adding that feature/roadmap. Thank you for the request though! :pray:
