### ISSUE TITLE
Domain-Driven Design resource is not available anymore

### ISSUE THREAD

**Issue by jakkaz** [kamranahmedse/developer-roadmap#4759]
### What is the URL where the issue is happening

https://roadmap.sh/backend

### Describe the Bug

The resource [Domain Driven Design Quickly](https://matfrs2.github.io/RS2/predavanja/literatura/Avram%20A,%20Marinescu%20F.%20-%20Domain%20Driven%20Design%20Quickly.pdf) in the backend roadmap under Domain-Driven Design node is not working anymore.

I suggest replacing it by [Domain Driven Design](https://redis.com/glossary/domain-driven-design-ddd/) by Redis. Maybe also adding a resource point about fundamental book - "Domain-Driven Design: Tackling Complexity in the Heart of Software" by Eric Evans.

### Participation

- [X] I am willing to submit a pull request for this issue.

**Comment by kamranahmedse** [comment]
Sounds good Jakub, go ahead with the PRs for such issues. No need to ask for the green light :)

**Comment by jakkaz** [comment]
Ok, will go directly for the PR next time @kamranahmedse, thanks for letting me know :-) opened the PR for this one: https://github.com/kamranahmedse/developer-roadmap/pull/4765
