### ISSUE TITLE
Image transparency

### ISSUE THREAD

**Issue by 2E0PGS** [kamranahmedse/developer-roadmap#476]
Greetings,

For us dark theme users who appreciate transparency in images could you please update the rest of the images to be transparrent aswell.

The following already have transparrent backgrounds:

* https://github.com/kamranahmedse/developer-roadmap/blob/master/images/backend.png
* https://github.com/kamranahmedse/developer-roadmap/blob/master/images/devops.png
* https://github.com/kamranahmedse/developer-roadmap/blob/master/images/split.png

The following need updating to be transparrent background. I could do this myself but if you have the source project files for those images then it would save me trying to use magic wand tool on it and getting inaccurate clipping of images:

* https://github.com/kamranahmedse/developer-roadmap/blob/master/images/disclaimer.png
* https://github.com/kamranahmedse/developer-roadmap/blob/master/images/frontend-v2.png

Example of how I detected this issue:

![image](https://user-images.githubusercontent.com/15659301/43194363-13fd3c20-8ffa-11e8-8b13-34672d62c227.png)

Notice how the latter image fits in well with my dark CSS theme since it has a transparrent background.

**Comment by 1337M0nst3r** [comment]
Working on it!

**Comment by kamranahmedse** [comment]
Thank you for reporting. We have fixed the transparency of the roadmaps in the repository. If you are still looking for the transparent backgrounds, you can find the images at [roadmap.sh](https://roadmap.sh).
