### ISSUE TITLE
Check the areas You already know

### ISSUE THREAD

**Issue by renatolacerda** [kamranahmedse/developer-roadmap#4764]
### Roadmap URL

https://roadmap.sh/ai-data-scientist

### Suggestions

There's a way to mark down the areas the you already Know

**Comment by arikchakma** [comment]
We are now closing any issues requesting new features/roadmap to clean up the issues.

However, this doesn’t mean that the requested feature/roadmap won’t be added to the website. We are putting it in the backlog and will add it to the website depending on how it ranks in the backlog or sooner if we find someone interested in adding that feature/roadmap. Thank you for the request though! :pray:
