### ISSUE TITLE
Permalink to content

### ISSUE THREAD

**Issue by jedateach** [kamranahmedse/developer-roadmap#4772]
### Roadmap URL

all roadmaps

### Suggestions

The url doesn't change when you click an item on a roadmap.
It would be handy to be able to permalink to a topic so that you can share with others a specific area of knowledge, containing the description and links to content.

Surely this will generate a bunch more traffic and SEO for the site as people share not just roadmaps, but the specific content within it.

My personal use case is to be able to share internally in my org specifically the Spring MVC page on the Spring Boot Developer roadmap. Something like https://roadmap.sh/spring-boot/spring-mvc
All I can currently do is copy-paste the content, or point people to the roadmap.

**Comment by jedateach** [comment]
What a fluke... https://roadmap.sh/spring-boot/spring-mvc actually produces content (I guessed the url)/

It's just unformatted html though, not the same experience as opening the sidebar in the roadmap view.

**Comment by arikchakma** [comment]
We are now closing any issues requesting new features/roadmap to clean up the issues.

However, this doesn’t mean that the requested feature/roadmap won’t be added to the website. We are putting it in the backlog and will add it to the website depending on how it ranks in the backlog or sooner if we find someone interested in adding that feature/roadmap. Thank you for the request though! :pray:
