### ISSUE TITLE
Add some 3D editors and mention of blockout

### ISSUE THREAD

**Issue by Gohellp** [kamranahmedse/developer-roadmap#4775]
### Roadmap URL

https://roadmap.sh/game-developer

### Suggestions

As it seems to me personally from the experience of working with friends, a link to a roadmap for 3d design or a description of work in any program (Blender, Cinema 4D, etc) together with a guide for choosing a style (this was an EXTREMELY big problem in our team ":D). And node about blockout would be extremely useful and important. Level design is being built on it.

**Comment by arikchakma** [comment]
We are now closing any issues requesting new features/roadmap to clean up the issues.

However, this doesn’t mean that the requested feature/roadmap won’t be added to the website. We are putting it in the backlog and will add it to the website depending on how it ranks in the backlog or sooner if we find someone interested in adding that feature/roadmap. Thank you for the request though! :pray:
