### ISSUE TITLE
Logging in Rust roadmap.

### ISSUE THREAD

**Issue by kernelplv** [kamranahmedse/developer-roadmap#4780]
### Roadmap URL

https://roadmap.sh/rust

### Suggestions

(gpt translate)
Hello! I didn’t notice any logging in the Rust roadmap. Unfortunately, I’m a beginner and can’t suggest anything specific, but I’m sure that logging is a very important part for any language. Thank you!

**Comment by arikchakma** [comment]
We are now closing any issues requesting new features/roadmap to clean up the issues.

However, this doesn’t mean that the requested feature/roadmap won’t be added to the website. We are putting it in the backlog and will add it to the website depending on how it ranks in the backlog or sooner if we find someone interested in adding that feature/roadmap. Thank you for the request though! :pray:
