### ISSUE TITLE
Make "AI and Data Science Roadmap" more granular

### ISSUE THREAD

**Issue by miratorimoonlight** [kamranahmedse/developer-roadmap#4788]
### Roadmap URL

https://roadmap.sh/ai-data-scientist

### Suggestions

I would like to suggest that you add checkbox on each subsection. This will help keep users more motivated every time they check off what they've done.

For example: instead of one checkbox like this (image below), we **add 3 more checkboxes** next to each course.
![Screenshot 2023-11-29 at 11 39 36 AM](https://github.com/kamranahmedse/developer-roadmap/assets/34526907/2a2a4ec4-cffa-40a6-9ce4-6844275fbf43)

**Comment by arikchakma** [comment]
We are now closing any issues requesting new features/roadmap to clean up the issues.

However, this doesn’t mean that the requested feature/roadmap won’t be added to the website. We are putting it in the backlog and will add it to the website depending on how it ranks in the backlog or sooner if we find someone interested in adding that feature/roadmap. Thank you for the request though! :pray:
