### ISSUE TITLE
Two full-points after ✔️ Start learning

### ISSUE THREAD

**Issue by satchit24** [kamranahmedse/developer-roadmap#4789]
### What is the URL where the issue is happening

https://roadmap.sh/

### What browsers are you seeing the problem on?

Firefox

### Describe the Bug

After signing up, on the homepage - 'Start learning' there are two full-points. 
I think those two full-points should not be there. It should be just '✔️ Start learning'.

![image](https://github.com/kamranahmedse/developer-roadmap/assets/48960354/4994670b-4ee5-406c-8d77-f9c79dc29582)

### Output from browser console (if any)

No output

### Participation

- [X] I am willing to submit a pull request for this issue.

**Comment by satchit24** [comment]
Can someone please change the label to suggestions.

**Comment by arikchakma** [comment]
It's not a bug, It's intentional.
