### ISSUE TITLE
GO Coding style and idiomatic code

### ISSUE THREAD

**Issue by tuxerrante** [kamranahmedse/developer-roadmap#4791]
### Feature Description

I think it would be relevant to also study how any language has a different way of thinking code structure and idiomatic ways to do stuff, so it would be nice to see some content coming from Google style guide and Effective Go

https://google.github.io/styleguide/go/guide
https://go.dev/doc/effective_go

**Comment by arikchakma** [comment]
We are now closing any issues requesting new features/roadmap to clean up the issues.

However, this doesn’t mean that the requested feature/roadmap won’t be added to the website. We are putting it in the backlog and will add it to the website depending on how it ranks in the backlog or sooner if we find someone interested in adding that feature/roadmap. Thank you for the request though! :pray:
