### ISSUE TITLE
Good Old GNU Make

### ISSUE THREAD

**Issue by szycha76** [kamranahmedse/developer-roadmap#4793]
### Roadmap URL

https://roadmap.sh/devops

### Suggestions

It seems odd to me that most people forget about a great, ubiquitously present multi-purpose multi-language script enhancer, called `make`.

GNU Make is literally everywhere, or can be installed at little to no cost on many systems and architecture types.

A proficient `Makefile`s author can benefit by using them
1. to automate anything that requires typing
2. to automate of building (or provisioning) virtually anything, not just C/C++ code
3. to simplify scripting, e.g. by tracking dependencies and skipping not needed steps, etc.

Makefiles can be used directly, or as part of pipelines, your imagination is basically the limit here.

Therefore I dare to suggest that you at least mention make / Makefiles in the DevOps roadmap, e.g. as an optional enhancement, possibly next to the `Scripting` section, however, any task group can be augmented with a Makefile.

Feel free to ignore this suggestion, keep up the good work, and thank you for the roadmap.sh project, which is great.

**Comment by arikchakma** [comment]
We are now closing any issues regarding bug fixes or requesting new features/roadmap to clean up the issues.

However, this doesn’t mean that the requested bug fix/feature/roadmap won’t be fixed/added to the website. We are putting it in the backlog and will add it to the website depending on how it ranks in the backlog or sooner if we find someone interested in fixing the bug or adding that feature/roadmap. Thank you for the request though! :pray:
