### ISSUE TITLE
Team invite failed due to capitalization

### ISSUE THREAD

**Issue by nbanyan** [kamranahmedse/developer-roadmap#4796]
### What is the URL where the issue is happening

https://roadmap.sh

### Describe the Bug

I tried inviting a coworker to my team using the capitalization that his email is usually displayed with in Outlook, etc. (ex. John_Smith@company.com).  He already had an account in roadmap.sh, but using all lowercase.  The invites I sent failed until I deleted the invite and used the lowercase variant of his email.

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by arikchakma** [comment]
Interesting, it shouldn't matter though. I've tested it with Capitalize emails, but it works fine.
