### ISSUE TITLE
AWS Roadmap Essential service 

### ISSUE THREAD

**Issue by abaidgulshan** [kamranahmedse/developer-roadmap#4798]
### Roadmap URL

https://roadmap.sh/aws

### Suggestions

Please change,

- Put IAM in first place, 
- DynamoDB should be Serverless even its DB 
- Add API gateway 
- Add more services to Serverless 

![image](https://github.com/kamranahmedse/developer-roadmap/assets/7329596/a52766d4-d10a-4399-a7c0-56ae254d09c2)

**Comment by arikchakma** [comment]
We are now closing any issues regarding bug fixes or requesting new features/roadmap to clean up the issues.

However, this doesn’t mean that the requested bug fix/feature/roadmap won’t be fixed/added to the website. We are putting it in the backlog and will add it to the website depending on how it ranks in the backlog or sooner if we find someone interested in fixing the bug or adding that feature/roadmap. Thank you for the request though! :pray:
