### ISSUE TITLE
Adding William Fiset's series on Data Structures to the Data Structure components.

### ISSUE THREAD

**Issue by randypanopio** [kamranahmedse/developer-roadmap#4801]
### Roadmap URL

https://roadmap.sh/computer-science

### Suggestions

William Fiset has some excellent resources on data structures, introducing them in a visual manner. I think they should be included in the roadmap since they primarily focus on the datastructure over the underlying algorithms these DS allow.

[Hash Tables](https://www.youtube.com/watch?v=2E54GqF0H4s&list=PLDV1Zeh2NRsDH5Wq-Vk5tDb8gH03cULZS&index=1)
[Stack](https://www.youtube.com/watch?v=L3ud3rXpIxA&list=PLDV1Zeh2NRsC0FVi9Rshi-5fFU1QwcFQ1&index=1)
[Queues](https://www.youtube.com/watch?v=KxzhEQ-zpDc&list=PLDV1Zeh2NRsAWrxWRTHJrsgBrbwqGzt-z)
[Priority Queues/Heap](https://www.youtube.com/watch?v=wptevk0bshY&list=PLDV1Zeh2NRsCLFSHm1nYb9daYf60lCcag&index=1)
[BST](https://www.youtube.com/watch?v=JfSdGQdAzq8&list=PLDV1Zeh2NRsCYY48kOkeLQ-cg9-eqInzs)

**Comment by kamranahmedse** [comment]
Thank you! Feel free to submit a PR.
