### ISSUE TITLE
Some basicis

### ISSUE THREAD

**Issue by kyouhan** [kamranahmedse/developer-roadmap#4809]
### Roadmap URL

https://roadmap.sh/aspnet-core

### Suggestions

what about adding some basic things with c# like data structure and algorithms

**Comment by selvamuthukumaran1** [comment]
![image](https://github.com/kamranahmedse/developer-roadmap/assets/86711942/c2be2fe1-9ca7-4df9-a003-eb58a8e0f09d)

**Comment by arikchakma** [comment]
We are now closing any issues regarding bug fixes or requesting new features/roadmap to clean up the issues.

However, this doesn’t mean that the requested bug fix/feature/roadmap won’t be fixed/added to the website. We are putting it in the backlog and will add it to the website depending on how it ranks in the backlog or sooner if we find someone interested in fixing the bug or adding that feature/roadmap. Thank you for the request though! :pray:
