### ISSUE TITLE
Opinion checkmarks

### ISSUE THREAD

**Issue by garvamel** [kamranahmedse/developer-roadmap#4813]
### Roadmap URL

https://roadmap.sh/devops

### Suggestions

1. Indicate whether choosing a certain color means choosing it for the whole roadmap or for the particular set of options.
2. Docker link has a blue box and checkmark which is not on checkmark legend box.
3. Maybe Python should be blue like the docker one.

**Comment by arikchakma** [comment]
We are now closing any issues regarding bug fixes or requesting new features/roadmap to clean up the issues.

However, this doesn’t mean that the requested bug fix/feature/roadmap won’t be fixed/added to the website. We are putting it in the backlog and will add it to the website depending on how it ranks in the backlog or sooner if we find someone interested in fixing the bug or adding that feature/roadmap. Thank you for the request though! :pray:
