### ISSUE TITLE
Truffle being depricated

### ISSUE THREAD

**Issue by DouglasBarra** [kamranahmedse/developer-roadmap#4815]
### Roadmap URL

https://roadmap.sh/blockchain

### Suggestions

Hello there,

Please read the following link to be more up to date on the latest state of Truffle, soon to have no longer support.

https://consensys.io/blog/consensys-announces-the-sunset-of-truffle-and-ganache-and-new-hardhat?utm_source=github&utm_medium=referral&utm_campaign=2023_Sep_truffle-sunset-2023_announcement_

Thanks,
Douglas Barra

**Comment by arikchakma** [comment]
We are now closing any issues regarding bug fixes or requesting new features/roadmap to clean up the issues.

However, this doesn’t mean that the requested bug fix/feature/roadmap won’t be fixed/added to the website. We are putting it in the backlog and will add it to the website depending on how it ranks in the backlog or sooner if we find someone interested in fixing the bug or adding that feature/roadmap. Thank you for the request though! :pray:
