### ISSUE TITLE
Why Restify framework is not under nodejs ? 

### ISSUE THREAD

**Issue by yogeshvar** [kamranahmedse/developer-roadmap#482]
As I could see many frameworks you have listed in the roadmap;  
![node-2018](https://user-images.githubusercontent.com/17572818/43857611-730797cc-9b69-11e8-87f1-086eb6cabd08.png)
It would be nice; if you add it. 
Thanks!

**Comment by makrandgupta** [comment]
here's the source of that graph: https://raygun.com/blog/nodejs-vs-hapi-express-restify-koa/
and according to the same blog, express has already overtaken restify

**Comment by lazarljubenovic** [comment]
It only talks about one aspect of comparing frameworks. Not everything is in number of requests or performance in general.

**Comment by kamranahmedse** [comment]
Thank you for opening the issue. We don't want to convolute the roadmap by mentioning every available option and are just focusing on what is the most relevant item that you would pick today and the mentioned item doesn't conform to that. 

This has also been [mentioned in the contribution docs](https://github.com/kamranahmedse/developer-roadmap/blob/master/CONTRIBUTING.md#guidelines). 
Thank you for your suggestion though 🙏
