### ISSUE TITLE
recommendation 

### ISSUE THREAD

**Issue by Omar-Basel-ALkhasawneh** [kamranahmedse/developer-roadmap#4822]
### Roadmap URL

https://roadmap.sh/ai-data-scientist

### Suggestions

I suggest providing topics instead of structured courses to offer individuals more freedom in their learning journey.

**Comment by arikchakma** [comment]
We are now closing any issues regarding bug fixes or requesting new features/roadmap to clean up the issues.

However, this doesn’t mean that the requested bug fix/feature/roadmap won’t be fixed/added to the website. We are putting it in the backlog and will add it to the website depending on how it ranks in the backlog or sooner if we find someone interested in fixing the bug or adding that feature/roadmap. Thank you for the request though! :pray:
