### ISSUE TITLE
Lack of important topics.

### ISSUE THREAD

**Issue by majornelson4** [kamranahmedse/developer-roadmap#4823]
### Roadmap URL

https://roadmap.sh/java

### Suggestions

Consider adding Reflection API to java advance. Bunch of frameworks use reflection api under the hood, like Spring, Hibernate.
[Link to baeldung tutorial](https://www.baeldung.com/java-reflection).

**Comment by arikchakma** [comment]
We are now closing any issues regarding bug fixes or requesting new features/roadmap to clean up the issues.

However, this doesn’t mean that the requested bug fix/feature/roadmap won’t be fixed/added to the website. We are putting it in the backlog and will add it to the website depending on how it ranks in the backlog or sooner if we find someone interested in fixing the bug or adding that feature/roadmap. Thank you for the request though! :pray:
