### ISSUE TITLE
Why is the number 17 & 18 used twice in the Front End Diagram?

### ISSUE THREAD

**Issue by yogesnsamy** [kamranahmedse/developer-roadmap#483]
I'm sorry if this issue has been raised before; I tried searching but couldn't find it. 

I'm just wondering why the numbering is so? Any special reason for using number 17 & 18 twice in the diagram? 
![frontendnumbering_duplicate](https://user-images.githubusercontent.com/28777569/44083155-c5c9664a-9fe5-11e8-998b-c93408a493eb.png)

**Comment by kamranahmedse** [comment]
By mistake. Will fix it. Thanks.
