### ISSUE TITLE
The text are not visible 

### ISSUE THREAD

**Issue by Joababio** [kamranahmedse/developer-roadmap#4832]
### Detailed Description

Font color and background colors are all bright hence poor visibility

**Comment by rohit-sharma-1802** [comment]
@Joababio Hi can you share the screenshot

**Comment by arikchakma** [comment]
We are now closing any issues requesting new features/roadmap to clean up the issues.

However, this doesn’t mean that the requested feature/roadmap won’t be added to the website. We are putting it in the backlog and will add it to the website depending on how it ranks in the backlog or sooner if we find someone interested in adding that feature/roadmap. Thank you for the request though! :pray:
