### ISSUE TITLE
Highlight selected topic

### ISSUE THREAD

**Issue by MichalFaberr** [kamranahmedse/developer-roadmap#4839]
### Feature Description

**Problem Description**
Description of each topic can be quite long. The reading takes time and after that time it may become hard to find the topic on the map.

**Proposed Solution**
 I know that probably I am suppose to mark the item as in progress or done but for this I need an account. It would be nice to have an improvement without need of creating an account hence the proposition is to simply highlight currently selected item on the map (please take a look at the attached image).
![image](https://github.com/kamranahmedse/developer-roadmap/assets/13886610/10270509-7233-4a9d-9475-18ac39f5ac8b)

**Comment by EthanSKim** [comment]
Created my first pr for this feature. It was my first opensource contribution, and it was a great experience. I would really appreciate some feedback!

**Comment by arikchakma** [comment]
We are now closing any issues requesting new features/roadmap to clean up the issues.

However, this doesn’t mean that the requested feature/roadmap won’t be added to the website. We are putting it in the backlog and will add it to the website depending on how it ranks in the backlog or sooner if we find someone interested in adding that feature/roadmap. Thank you for the request though! :pray:
