### ISSUE TITLE
Hystrix and Eureka are outdated and should be replaced with newer spring cloud stack

### ISSUE THREAD

**Issue by kartiktayal** [kamranahmedse/developer-roadmap#4841]
### Roadmap URL

https://roadmap.sh/spring-boot

### Suggestions

Hystrix and Eureka are outdated and are just being maintained without any new features. They should be replaced with spring cloud load balancer and spring cloud circuit breaker

**Comment by arikchakma** [comment]
We are now closing any issues regarding bug fixes or requesting new features/roadmap to clean up the issues.

However, this doesn’t mean that the requested bug fix/feature/roadmap won’t be fixed/added to the website. We are putting it in the backlog and will add it to the website depending on how it ranks in the backlog or sooner if we find someone interested in fixing the bug or adding that feature/roadmap. Thank you for the request though! :pray:
