### ISSUE TITLE
No loader is configured for ".md" files

### ISSUE THREAD

**Issue by finfin** [kamranahmedse/developer-roadmap#4845]
### What is the URL where the issue is happening

code

### What browsers are you seeing the problem on?

Other

### Describe the Bug

when running local dev it shows large amount of errors

looks like the new astro version with latest vite v5 is causing the issue

https://github.com/vitejs/vite/issues/15281

went back to normal when i revert astro back to v3.5

### Output from browser console (if any)

```
  ✘ [ERROR] No loader is configured for ".md" files: src/data/best-practices/api-security/api-security.md

    src/lib/best-practice-topic.ts:18:45:
      18 │ ...it import(`../data/best-practices/${bestPracticeId}/${bestPract...
         ╵              ~~~~~~~~~
```

### Participation

- [X] I am willing to submit a pull request for this issue.

**Comment by arikchakma** [comment]
We are now closing any issues regarding bug fixes or requesting new features/roadmap to clean up the issues.

However, this doesn’t mean that the requested bug fix/feature/roadmap won’t be fixed/added to the website. We are putting it in the backlog and will add it to the website depending on how it ranks in the backlog or sooner if we find someone interested in fixing the bug or adding that feature/roadmap. Thank you for the request though! :pray:
