### ISSUE TITLE
Create separate OOP section

### ISSUE THREAD

**Issue by AbhinavGS** [kamranahmedse/developer-roadmap#4846]
### Roadmap URL

https://roadmap.sh/javascript

### Suggestions

Create separate OOP section and organize it like below:
OOP 
  --constructor functions
  --es6 classes
  --Object.create()

**Comment by arikchakma** [comment]
We are now closing any issues regarding bug fixes or requesting new features/roadmap to clean up the issues.

However, this doesn’t mean that the requested bug fix/feature/roadmap won’t be fixed/added to the website. We are putting it in the backlog and will add it to the website depending on how it ranks in the backlog or sooner if we find someone interested in fixing the bug or adding that feature/roadmap. Thank you for the request though! :pray:
