### ISSUE TITLE
Android development roadmap Improvement

### ISSUE THREAD

**Issue by gerceboss** [kamranahmedse/developer-roadmap#4848]
### Roadmap URL

https://roadmap.sh/android

### Suggestions

Please add the resources to learn from in each section.

**Comment by arikchakma** [comment]
We are now closing any issues regarding bug fixes or requesting new features/roadmap to clean up the issues.

However, this doesn’t mean that the requested bug fix/feature/roadmap won’t be fixed/added to the website. We are putting it in the backlog and will add it to the website depending on how it ranks in the backlog or sooner if we find someone interested in fixing the bug or adding that feature/roadmap. Thank you for the request though! :pray:
