### ISSUE TITLE
Greenkeeper is down. Snyk is recommended instead

### ISSUE THREAD

**Issue by TomoyaKuroda** [kamranahmedse/developer-roadmap#4853]
### Roadmap URL

https://roadmap.sh/best-practices/frontend-performance

### Suggestions

**Dependency Updates** has a link to Greenkeeper, but the service is not available now. They suggest Snyk instead. Please see the link https://greenkeeper.io/

**Comment by arikchakma** [comment]
The link is working properly. Thanks for creating the issue.

**Comment by TomoyaKuroda** [comment]
@arikchakma I'm sorry.
The link works but the service itself shut down. Please see the fixed header.

**Comment by arikchakma** [comment]
Aha, okay. Sorry for the oversight, I didn't notice that. We'll fix it in the next iteration. Thanks for reporting.
