### ISSUE TITLE
c++ completion impossible

### ISSUE THREAD

**Issue by kerembay9** [kamranahmedse/developer-roadmap#4857]
### Roadmap URL

https://roadmap.sh/cpp

### Suggestions

I have completed 122 of the 123 steps. Either 123rd element is nonexistent or it is the "Backend Roadmap" button which cannot be completed. This damages the sense of completion.

**Comment by arikchakma** [comment]
We are now closing any issues regarding bug fixes or requesting new features/roadmap to clean up the issues.

However, this doesn’t mean that the requested bug fix/feature/roadmap won’t be fixed/added to the website. We are putting it in the backlog and will add it to the website depending on how it ranks in the backlog or sooner if we find someone interested in fixing the bug or adding that feature/roadmap. Thank you for the request though! :pray:
