### ISSUE TITLE
Dead Link: Backend Dev Roadmap - Enabling HTTPS on Your Servers

### ISSUE THREAD

**Issue by ShaunGreiner** [kamranahmedse/developer-roadmap#4862]
### What is the URL where the issue is happening

https://roadmap.sh/backend

### Describe the Bug

The link under HTTPS for [Enabling HTTPS on Your Servers](https://developers.google.com/web/fundamentals/security/encrypt-in-transit/enable-https) appears to have moved or been taken down.

### Output from browser console (if any)

404

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by ntransw** [comment]
also applies to the devops and software architect roadmaps

**Comment by arikchakma** [comment]
This issue has been fixed.
