### ISSUE TITLE
Puro on Setup Development Enviroment

### ISSUE THREAD

**Issue by kelvinwieth** [kamranahmedse/developer-roadmap#4863]
### Roadmap URL

https://roadmap.sh/flutter

### Suggestions

Although not (yet) popular as FVM, [puro](https://puro.dev/) is a good option, both on performance and developer experience, so it can be recommended as a development environment tool.

<img width="795" alt="image" src="https://github.com/kamranahmedse/developer-roadmap/assets/79933699/dd5ad454-a938-4438-af7c-26b7b2c194a9">

**Comment by arikchakma** [comment]
We are now closing any issues regarding bug fixes or requesting new features/roadmap to clean up the issues.

However, this doesn’t mean that the requested bug fix/feature/roadmap won’t be fixed/added to the website. We are putting it in the backlog and will add it to the website depending on how it ranks in the backlog or sooner if we find someone interested in fixing the bug or adding that feature/roadmap. Thank you for the request though! :pray:
