### ISSUE TITLE
Add C++ to language choices 

### ISSUE THREAD

**Issue by Islam-Adel-Dev** [kamranahmedse/developer-roadmap#4866]
### Roadmap URL

https://roadmap.sh/backend

### Suggestions

I have noticed that the [C++ Roadmap](https://roadmap.sh/cpp) contains a link to back-end Roadmap at the end but C++ is not one of the languages mentioned in the step of "Learn a language" in the back-end Roadmap.

![Screenshot 2023-12-14 155040](https://github.com/kamranahmedse/developer-roadmap/assets/153809816/3fbdab4f-9fab-45d1-a65e-229bc2580bd6)

Adding a link to C++ roadmap would be nice.

**Comment by Nishbeu2** [comment]
[![App Deployment](https://github.com/https://github.com/Nishbeu2/developer-roadmap/actions/workflows/deployment.yml/badge.svg?branch=master&event=branch_protection_rule)](https://github.com/https://github.com/Nishbeu2

**Comment by Nishbeu2** [comment]
> ### Roadmap URL
> 
> https://roadmap.sh/backend
> 
> ### Suggestions
> 
> I have noticed that the [C++ Roadmap](https://roadmap.sh/cpp) contains a link to back-end Roadmap at the end but C++ is not one of the languages mentioned in the step of "Learn a language" in the back-end Roadmap.
> 
> ![Screenshot 2023-12-14 155040](https://github.com/kamranahmedse/developer-roadmap/assets/153809816/3fbdab4f-9fab-45d1-a65e-229bc2580bd6)
> 
> Adding a link to C++ roadmap would be nice.

https://patch-diff.githubusercontent.com/raw/up-for-grabs/up-for-grabs.net/pull/4386.patchhttps://github.com/Nishbeu2

**Comment by arikchakma** [comment]
We are now closing any issues regarding bug fixes or requesting new features/roadmap to clean up the issues.

However, this doesn’t mean that the requested bug fix/feature/roadmap won’t be fixed/added to the website. We are putting it in the backlog and will add it to the website depending on how it ranks in the backlog or sooner if we find someone interested in fixing the bug or adding that feature/roadmap. Thank you for the request though! :pray:
