### ISSUE TITLE
Add Array and String methods

### ISSUE THREAD

**Issue by Bhargava-Urs** [kamranahmedse/developer-roadmap#4872]
### Roadmap URL

https://roadmap.sh/javascript

### Suggestions

Add a bit of theory for strings followed by methods for both strings and methods. If possible give small examples for each of the concept.

**Comment by arikchakma** [comment]
We are now closing any issues regarding bug fixes or requesting new features/roadmap to clean up the issues.

However, this doesn’t mean that the requested bug fix/feature/roadmap won’t be fixed/added to the website. We are putting it in the backlog and will add it to the website depending on how it ranks in the backlog or sooner if we find someone interested in fixing the bug or adding that feature/roadmap. Thank you for the request though! :pray:
