### ISSUE TITLE
A section is unclickable

### ISSUE THREAD

**Issue by fadimou** [kamranahmedse/developer-roadmap#4877]
### What is the URL where the issue is happening

https://roadmap.sh/cyber-security

### Describe the Bug

The section "Understand Audience" and all of its sub-sections are unclickable 

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by Mubashir2611** [comment]
Can you share a video? For better understanding

**Comment by arikchakma** [comment]
Thank you for opening the issue. We don't want to convolute the roadmap by mentioning every available option and are just focusing on what is the most relevant item that you would pick today and the mentioned item doesn't conform to that. 

This has also been mentioned in the contribution docs. 
Thank you for your suggestion though 🙏
