### ISSUE TITLE
'Login Required' When Trying To Edit Custom Roadmap and Already Logged In

### ISSUE THREAD

**Issue by dethancosta** [kamranahmedse/developer-roadmap#4880]
### What is the URL where the issue is happening

https://roadmap.sh

### What browsers are you seeing the problem on?

Firefox

### Describe the Bug

On a custom roadmap, I select the 'edit roadmap' button. A new tab opens with url `https://draw.roadmap.sh/login` and message `You must be logged in to use the editor. Please follow the link below to login and come back.`

I am already logged in and even after following the link, the same thing occurs again.

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by Mubashir2611** [comment]
Can you post a video for better explanation or understanding.

**Comment by kamranahmedse** [comment]
I am unable to reproduce this. Please let us know if you are still facing this issue.
