### ISSUE TITLE
link to resource on SSH config files

### ISSUE THREAD

**Issue by s-m33r** [kamranahmedse/developer-roadmap#4883]
### Roadmap URL

https://roadmap.sh/devops

### Suggestions

I suggest linking to a resource on setting up SSH config files in `SSH` under the "Networking Protocols" node.  
[suggested article](https://linuxize.com/post/using-the-ssh-config-file/)

**Comment by arikchakma** [comment]
We are now closing any issues regarding bug fixes or requesting new features/roadmap to clean up the issues.

However, this doesn’t mean that the requested bug fix/feature/roadmap won’t be fixed/added to the website. We are putting it in the backlog and will add it to the website depending on how it ranks in the backlog or sooner if we find someone interested in fixing the bug or adding that feature/roadmap. Thank you for the request though! :pray:
