### ISSUE TITLE
Can be add course links

### ISSUE THREAD

**Issue by merttanitan1** [kamranahmedse/developer-roadmap#4885]
### Roadmap URL

https://roadmap.sh/cyber-security

### Suggestions

Course resources can be added to some titles. Like "https://roadmap.sh/ai-data-scientist" this roadmap.

**Comment by arikchakma** [comment]
We are now closing any issues requesting new suggestions/features/roadmap to clean up the issues.

However, this doesn’t mean that the requested suggestions/features/roadmap won’t be added to the website. We are putting it in the backlog and will add it to the website depending on how it ranks in the backlog or sooner if we find someone interested in adding that suggestion/feature/roadmap. Thank you for the request though! :pray:
