### ISSUE TITLE
Add the Dedicated AWS Roadmap as a Resource in the DevOps Roadmap

### ISSUE THREAD

**Issue by nawelasg** [kamranahmedse/developer-roadmap#4895]
### Roadmap URL

https://roadmap.sh/devops

### Suggestions

In the AWS section of the DevOps Roadmap, You can add the Dedicated AWS Roadmap now. Since it is detailed it is a better resource than listing some of the links. 
You can add the AWS roadmap just like you have done with the Docker Roadmap and the Kubernetes Roadmap.

**Comment by arikchakma** [comment]
We already have the [AWS Roadmap](https://roadmap.sh/aws).
