### ISSUE TITLE
This video is no longer available

### ISSUE THREAD

**Issue by frapalozz** [kamranahmedse/developer-roadmap#4896]
### What is the URL where the issue is happening

https://roadmap.sh/javascript

### Describe the Bug

The video in the section "Exception Handling" of the Javascript roadmap is no longer available.

This is the link of the video: [https://www.youtube.com/watch?v=cftftueq-10]

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by shubhamprkash** [comment]
Made the fix  PR for it.
Reference -> #4898

**Comment by arikchakma** [comment]
This issue has been fixed.
