### ISSUE TITLE
Lets Convert this to Mark Down - Charts

### ISSUE THREAD

**Issue by parv0888** [kamranahmedse/developer-roadmap#49]
An Image is hard to edit for programmers. 
Lets convert this to mark down charts so that. anybody can fork it and edit it a per their convenience.

**Comment by UnitedPE** [comment]
This is a very good idea. I would recommend plantUML.

**Comment by diego-vieira** [comment]
The roadmaps are built using Balsamiq. 
https://balsamiq.com/products/mockups/

Project file can be found at /project-files directory. To modify any of the roadmaps, open Balsamiq, click project > import > Mokup JSON, it will open the roadmap for you, update it, upload and update the images in readme and create a PR.

**Comment by PeterMTaylor** [comment]
Sounds like you have a dynamic business model in place to maintain charts including up front costs, is that true?

**Comment by Sebring** [comment]
By using plantUML, the images could be rendered on-demand by the plantuml server (to png or svg) by linking to source. 

See http://plantuml.com/server and http://stackoverflow.com/questions/32203610/how-to-integrate-uml-diagrams-into-gitlab-or-github for discussion.

**Comment by kamranahmedse** [comment]
We recently started working on this. This should be fixed soon after the 2020 release. Thank you for suggesting! 🙏
