### ISSUE TITLE
🐛 Bug: Incorrect scrolling behavior in side-drawer

### ISSUE THREAD

**Issue by ashrafchowdury** [kamranahmedse/developer-roadmap#4905]
### What is the URL where the issue is happening

https://roadmap.sh/backend

### What browsers are you seeing the problem on?

Chrome, Microsoft Edge

### Describe the Bug

**When attempting to scroll within the side-drawer, the main page content often scrolls instead,** making it difficult to navigate the side-drawer content. This issue occurs intermittently and seems to be more prevalent when the side-drawer contains a large amount of content. 

### Output from browser console (if any)

https://github.com/kamranahmedse/developer-roadmap/assets/87828904/a0e9791f-67b8-4aed-8c39-72fc67471545

### Participation

- [X] I am willing to submit a pull request for this issue.

**Comment by Mubashir2611** [comment]
Is anybody working this issue?

**Comment by ashrafchowdury** [comment]
> Is anybody working on this issue?

Not assigned yet, after a review I will work on it.

**Comment by Mubashir2611** [comment]
can I contribute this issue?
