### ISSUE TITLE
React-native roadmap includes roadmap for c++ 

### ISSUE THREAD

**Issue by pirjademl** [kamranahmedse/developer-roadmap#4907]
### What is the URL where the issue is happening

https://roadmap.sh/react-native

### What browsers are you seeing the problem on?

Chrome

### **React native roadmap pdf includes C++ roadmap** 
 **The react-native roadmap pdf includes the c++ roadmap .**
This can be solved by replacing the pdf in the 
`public/pdfs/roadmaps/react-native.pdf`

https://github.com/kamranahmedse/developer-roadmap/assets/85778551/e1da3555-96ad-4e37-9462-12834e26288e

### Participation

- [X] I am willing to submit a pull request for this issue.

**Comment by arikchakma** [comment]
We are now closing any issues regarding bug fixes or requesting new features/roadmap to clean up the issues.

However, this doesn’t mean that the requested bug fix/feature/roadmap won’t be fixed/added to the website. We are putting it in the backlog and will add it to the website depending on how it ranks in the backlog or sooner if we find someone interested in fixing the bug or adding that feature/roadmap. Thank you for the request though! :pray:
