### ISSUE TITLE
Visual examples

### ISSUE THREAD

**Issue by vignesh22101** [kamranahmedse/developer-roadmap#4909]
### Roadmap URL

https://roadmap.sh/javascript

### Suggestions

A visual example like code snippets or images would be very helpful in certain cases.

Eg: When I click a block named Function parameters in JavaScript roadmap, information appears on the right side of the webpage.
If an image is attached showing what is function parameters exactly, it would be very helpful to relate and understand the concept.
I have attached an example image for the same topic. 
![Parameters example](https://github.com/kamranahmedse/developer-roadmap/assets/47502627/de41428d-a1da-4a86-bc57-f121a6454a63)

**Comment by arikchakma** [comment]
We are now closing any issues regarding bug fixes or requesting new features/roadmap to clean up the issues.

However, this doesn’t mean that the requested bug fix/feature/roadmap won’t be fixed/added to the website. We are putting it in the backlog and will add it to the website depending on how it ranks in the backlog or sooner if we find someone interested in fixing the bug or adding that feature/roadmap. Thank you for the request though! :pray:
