### ISSUE TITLE
Tools vs other knowledge

### ISSUE THREAD

**Issue by aquiladev** [kamranahmedse/developer-roadmap#491]
**Overall it is good roadmap, awesome infographic!**
I have some thoughts about it.

When I interview of candidate I would like to know different sides of his professional knowledge, I wanna say it wouldn't be enough to know some tools or languages. 

The roadmap focuses on languages, tools, libraries, frameworks but it is also good to know solution design, patterns, best practices, clean code, methodologies, etc.

What do you think, should it be part of roadmap?

**Comment by kamranahmedse** [comment]
Thank you for opening the issue. I 100% agree with you on that. Actually the purpose of these roadmaps was more towards laying down the landscape. 

However, this is going to change soon. It is being actively worked upon and should be addressed soon after we are done with the 2020 release through the website [roadmap.sh](https://roadmap.sh) - at which point this repository will just be holding the landscape information and the website would be the detailed resource with all the knowledge tools, resources and the knowledge required based on different seniority levels.

Again, thank you for highlighting that 🙏
