### ISSUE TITLE
QA Roadmap - Types of Functional Testing

### ISSUE THREAD

**Issue by bhuvanthakkar** [kamranahmedse/developer-roadmap#4911]
### Roadmap URL

https://roadmap.sh/qa

### Suggestions

Suggestion: I think there should be API Testing listed in types of Testing, WDYT?

**Comment by arikchakma** [comment]
We are now closing any issues requesting new features/roadmap to clean up the issues.

However, this doesn’t mean that the requested feature/roadmap won’t be added to the website. We are putting it in the backlog and will add it to the website depending on how it ranks in the backlog or sooner if we find someone interested in adding that feature/roadmap. Thank you for the request though! :pray:
