### ISSUE TITLE
General suggestion

### ISSUE THREAD

**Issue by NikitaNetajiraoPawar** [kamranahmedse/developer-roadmap#4918]
### Roadmap URL

https://roadmap.sh/

### Suggestions

I would like to suggest on any roadmap you guys creating . please make this as simpler as you can. I have seen few roadmap like backend developer, you have created it as a general backend developer roadmap which may be confusing for the beginner so I would recommend you to create separate roadmap based on the language & also with that consider their level as well i.e Beginner/Intermediate/Advanced likewise. reason being is in a one go nobody learn this languages so we need to start from basic to advanced so if you can split that would be really helpful.

**Comment by arikchakma** [comment]
We do have some beginner roadmaps for the Frontend roadmap, we'll be adding more. Thanks for your suggestion.
