### ISSUE TITLE
Request to add Ember.js to Frontend frameworks

### ISSUE THREAD

**Issue by obiejuan** [kamranahmedse/developer-roadmap#492]
Great Job with the road map. I especially liked being able to see where I am currently on the map and where there are some holes behind that need to be filled.
I would like to request to consider adding **Ember.js** as one of the Frontend frameworks listed as it is used by Netflix and LinkedIn as well as possessing a great developer community.

**Comment by kamranahmedse** [comment]
Thank you for opening the issue. While I agree with that, we don't want to convolute the roadmap by mentioning every available option and are just focusing on what is the most relevant item that you would pick today and mentioned item doesn't conform to that. 

This has also been [mentioned in the contribution docs](https://github.com/kamranahmedse/developer-roadmap/blob/master/contributing.md#guidelines). Thank your for your suggestion though 🙏
