### ISSUE TITLE
Some slight additions to the AI and data scientist roadmap

### ISSUE THREAD

**Issue by Momina1894** [kamranahmedse/developer-roadmap#4921]
### Roadmap URL

https://roadmap.sh/ai-data-scientist

### Suggestions

Hello! Hope you are doing well. 

I wanted to ask why the Data Scientist Category isn't separate from the AI category. If that could be another roadmap, perhaps a new one under data analytics, that would be amazing!

I also have another suggestion of adding Power BI and R programming under this category since I don't see any other programming languages other than SQL and python. Rstudio is also essential as well.

Please let me know more information about the above since I am a novice in Data science and am very much interested in this field.

**Comment by arikchakma** [comment]
We are now closing any issues regarding bug fixes or requesting new features/roadmap to clean up the issues.

However, this doesn’t mean that the requested bug fix/feature/roadmap won’t be fixed/added to the website. We are putting it in the backlog and will add it to the website depending on how it ranks in the backlog or sooner if we find someone interested in fixing the bug or adding that feature/roadmap. Thank you for the request though! :pray:
