### ISSUE TITLE
Replace 'reach router' from react's roadmap

### ISSUE THREAD

**Issue by mthsoliveira7** [kamranahmedse/developer-roadmap#4927]
### Roadmap URL

https://roadmap.sh/react

### Suggestions

Reach Router and it’s sibling project React Router are merging as React Router v6. In other words, Reach Router v2 and React Router v6 are the same. So there's no need for it to be displayed on the site. My suggestion is to replace it with [Wouter](https://github.com/molefrog/wouter), a simpler, updated and lightweight alternative to RR.

**Comment by arikchakma** [comment]
We are now closing any issues requesting new suggestions/features/roadmap to clean up the issues.

However, this doesn’t mean that the requested suggestions/features/roadmap won’t be added to the website. We are putting it in the backlog and will add it to the website depending on how it ranks in the backlog or sooner if we find someone interested in adding that suggestion/feature/roadmap. Thank you for the request though! :pray:
