### ISSUE TITLE
DevOps Roadmap - App Dynamics - Topic not found.

### ISSUE THREAD

**Issue by fishooo0815** [kamranahmedse/developer-roadmap#4929]
### What is the URL where the issue is happening

https://roadmap.sh/devops

### Describe the Bug

How to reproduce the Bug:
Click on App Dynamics on the DevOps Roadmap.

What Happens:
A red sign and text appears:
(/) Topic not found.

Expected behaviour.
Pop-Up appears. Where the progress can be changed. Also there should appear a description text and usefull links.

### Participation
I am not willing to submit a pull request for this issue.

**Comment by arikchakma** [comment]
Thank you for opening the issue. We don't want to convolute the roadmap by mentioning every available option and are just focusing on what is the most relevant item that you would pick today and the mentioned item doesn't conform to that. 

This has also been mentioned in the contribution docs. 
Thank you for your suggestion though 🙏

**Comment by arikchakma** [comment]
Got it, we have that in the backlog. Thanks for letting us know.
