### ISSUE TITLE
Changes to JavaScript Roadmap

### ISSUE THREAD

**Issue by SJ210033** [kamranahmedse/developer-roadmap#4931]
### Roadmap URL

https://roadmap.sh/javascript

### Suggestions

In introduction to JS add that JS is an interpreted language it will give them an idea of how it runs and if possible add the engines use by browser to run js like v8 for chrome and Chakra for edge

**Comment by arikchakma** [comment]
We are now closing any issues regarding bug fixes or requesting new features/roadmap to clean up the issues.

However, this doesn’t mean that the requested bug fix/feature/roadmap won’t be fixed/added to the website. We are putting it in the backlog and will add it to the website depending on how it ranks in the backlog or sooner if we find someone interested in fixing the bug or adding that feature/roadmap. Thank you for the request though! :pray:
