### ISSUE TITLE
I think there is also a roadmap for the working professionals, who want to change their Field from One technology to another.

### ISSUE THREAD

**Issue by sagardhiman18** [kamranahmedse/developer-roadmap#4932]
### Feature Description

- I think there is also a roadmap for the working professionals, who want to change their Field from One technology to another.
- Also, there is a suggestion for a Salary Calculator tool so that an individual can know their growth(based on the data which you collected from your userbase.)

**Comment by arikchakma** [comment]
We are now closing any issues requesting new features/roadmap to clean up the issues.

However, this doesn’t mean that the requested feature/roadmap won’t be added to the website. We are putting it in the backlog and will add it to the website depending on how it ranks in the backlog or sooner if we find someone interested in adding that feature/roadmap. Thank you for the request though! :pray:
