### ISSUE TITLE
Add Viem to dApps client libraries in blockchain roadmap

### ISSUE THREAD

**Issue by dev-aly3n** [kamranahmedse/developer-roadmap#4933]
### Roadmap URL

https://roadmap.sh/blockchain

### Suggestions

Hi, I suggest adding [Viem](https://viem.sh) to client libraries within the blockchain roadmap under the dApps section, located [here](https://github.com/kamranahmedse/developer-roadmap/tree/master/src/data/roadmaps/blockchain/content/109-dapps/108-client-libraries):

`src/data/roadmaps/blockchain/content/109-dapps/108-client-libraries`

[Viem](https://viem.sh) is a full-featured lightweight JavaScript library for interacting with EVM chains. It is utilized by [Wagmi]([Viem](https://wagmi.sh)), [ConnectKit](https://docs.family.co/connectkit), [Web3Modal](https://web3modal.com), [Dynamic](https://www.dynamic.xyz), and [RainbowKit](https://www.rainbowkit.com). Viem has a smaller bundle size than ethers and web3.js, while its performance surpasses that of ethers and web3.js .

[comparison between Viem, ethers, and web3.js](https://viem.sh/docs/introduction.html)

I recently used Viem in two projects for my clients, and it's amazing. In one of them, I had to migrate from ethers v5 to Viem, and it was really simple. [This is the migration guide](https://viem.sh/docs/ethers-migration.html)

**Comment by arikchakma** [comment]
We are now closing any issues requesting new features/roadmap to clean up the issues.

However, this doesn’t mean that the requested feature/roadmap won’t be added to the website. We are putting it in the backlog and will add it to the website depending on how it ranks in the backlog or sooner if we find someone interested in adding that feature/roadmap. Thank you for the request though! :pray:
