### ISSUE TITLE
Introduction to blockchain links are incorrect

### ISSUE THREAD

**Issue by ArianHamdi** [kamranahmedse/developer-roadmap#4934]
### What is the URL where the issue is happening

https://roadmap.sh/blockchain

### Describe the Bug

The followings links in blockchain roadmap are incorrect:

**Basic blockchain knowledge** > Introduction to blockchain
**Why it matters?** > why blockchain?

### Participation

- [X] I am willing to submit a pull request for this issue.

**Comment by dev-aly3n** [comment]
Hi, it seems they redirected this domain to 'dev.chain.link'. I also found another link that got corrupted because of this issue: [https://www.blockchain.education/blockchain101/smart-contracts](https://www.blockchain.education/blockchain101/smart-contracts)

**Comment by ArianHamdi** [comment]
Hi @dev-aly3n.
Thank you, I'll fix this too.
