### ISSUE TITLE
Subject and BehaviorSubject

### ISSUE THREAD

**Issue by 27hohuuduc** [kamranahmedse/developer-roadmap#4938]
### Roadmap URL

https://roadmap.sh/angular

### Suggestions

# Subject and BehaviorSubject

- A Subject is like an Observable, but can multicast to many Observers. Subjects are like EventEmitters: they maintain a registry of many listeners.
- A BehaviorSubject holds one value. When it is subscribed it emits the value immediately. A Subject doesn't hold a value.

Visit the following resources to learn more:

- [Subject](https://rxjs.dev/guide/subject)
- [BehaviorSubject](https://www.learnrxjs.io/learn-rxjs/subjects/behaviorsubject)

**Comment by arikchakma** [comment]
We are now closing any issues regarding bug fixes or requesting new features/roadmap to clean up the issues.

However, this doesn’t mean that the requested bug fix/feature/roadmap won’t be fixed/added to the website. We are putting it in the backlog and will add it to the website depending on how it ranks in the backlog or sooner if we find someone interested in fixing the bug or adding that feature/roadmap. Thank you for the request though! :pray:
