### ISSUE TITLE
Suggestion to add more frameworks in full stack backend section

### ISSUE THREAD

**Issue by PetreBogdan** [kamranahmedse/developer-roadmap#4939]
### Roadmap URL

https://roadmap.sh/full-stack

### Suggestions

I speak in the view of self learner here. There are a lot of options in therm of choosing the right programming langauge and the right tool for the job but there are a lot of choices that are aiming at the same goal. For example in the backend and full stack roadmap there are only mentions for javascript. I am aiming at learning a backend framework in order to learn more about but right now the only programming langauge that I am curently working profesionally and really confortable with is python. So maybe suggesting a good framework for python like fastAPI or django rest. 
This suggestion is for the backend roadmap too.

**Comment by arikchakma** [comment]
We are now closing any issues requesting new features/roadmap to clean up the issues.

However, this doesn’t mean that the requested feature/roadmap won’t be added to the website. We are putting it in the backlog and will add it to the website depending on how it ranks in the backlog or sooner if we find someone interested in adding that feature/roadmap. Thank you for the request though! :pray:
