### ISSUE TITLE
Have status updates on one roadmap also reflect in all other roadmaps.

### ISSUE THREAD

**Issue by ivandimitrov8080** [kamranahmedse/developer-roadmap#4940]
### Feature Description

Hello,

When I change the status of a step in one roadmap the other roadmaps still show the default value, which doesn't make sense.

**Comment by arikchakma** [comment]
We are now closing any issues requesting new features/roadmap to clean up the issues.

However, this doesn’t mean that the requested feature/roadmap won’t be added to the website. We are putting it in the backlog and will add it to the website depending on how it ranks in the backlog or sooner if we find someone interested in adding that feature/roadmap. Thank you for the request though! :pray:

**Comment by ivandimitrov8080** [comment]
@arikchakma Is there an issue? I can do this at some point.
