### ISSUE TITLE
Project Ideas and Levels

### ISSUE THREAD

**Issue by manthan-sharma-23** [kamranahmedse/developer-roadmap#4944]
### Feature Description

We can add new project ideas mappped with beginner intermediate advanced levels suggest features on top of them in each of the roamaps

**Comment by arikchakma** [comment]
We are now closing any issues requesting new features/roadmap to clean up the issues.

However, this doesn’t mean that the requested feature/roadmap won’t be added to the website. We are putting it in the backlog and will add it to the website depending on how it ranks in the backlog or sooner if we find someone interested in adding that feature/roadmap. Thank you for the request though! :pray:

**Comment by manthan-sharma-23** [comment]
sure thank you !
