### ISSUE TITLE
Numbering

### ISSUE THREAD

**Issue by anasroshdi** [kamranahmedse/developer-roadmap#4947]
### Roadmap URL

https://roadmap.sh/java

### Suggestions

I just want to number the parts because each section has multiple things so I don't know really from where should i start. and i would like to generalize this to all over the roadmaps thanks a lot for your efforts

**Comment by arikchakma** [comment]
We are now closing any issues requesting new features/roadmap to clean up the issues.

However, this doesn’t mean that the requested feature/roadmap won’t be added to the website. We are putting it in the backlog and will add it to the website depending on how it ranks in the backlog or sooner if we find someone interested in adding that feature/roadmap. Thank you for the request though! :pray:
