### ISSUE TITLE
[BUG] App Dynamics topic not found

### ISSUE THREAD

**Issue by jd-apprentice** [kamranahmedse/developer-roadmap#4949]
### What is the URL where the issue is happening

https://roadmap.sh/devops

### What browsers are you seeing the problem on?

Firefox

### Describe the Bug

When I try to see or modify about `Apps Dynamics` under `Application Monitoring` it says topic not found.

![image](https://github.com/kamranahmedse/developer-roadmap/assets/68082746/75327d11-7184-4b82-8d55-81fe0d9f7197)

### Output from browser console (if any)

XHR GET
https://roadmap.sh/devops/monitoring/application-monitoring/app-dynamics
[HTTP/2 404  11ms]

### Participation

- [X] I am willing to submit a pull request for this issue.

**Comment by jd-apprentice** [comment]
Now that I pay attention this is a duplicate of #4929

**Comment by arikchakma** [comment]
Thank you for opening the issue. We don't want to convolute the roadmap by mentioning every available option and are just focusing on what is the most relevant item that you would pick today and the mentioned item doesn't conform to that. 

This has also been mentioned in the contribution docs. 
Thank you for your suggestion though 🙏
