### ISSUE TITLE
Tips: ui-components framework learning for front-end

### ISSUE THREAD

**Issue by Sidfate** [kamranahmedse/developer-roadmap#495]
Maybe for front-enders, we always choose some ui-components frameworks, such as:

* element-ui
* ant-design
* semantic-ui

Learning to build common ui-components by ourselves is an important skill in my sight 😄 .

**Comment by kamranahmedse** [comment]
Closing for being non-relevant. Please have a look at the [contribution docs](https://github.com/kamranahmedse/developer-roadmap/blob/master/contributing.md)
