### ISSUE TITLE
Add additional resources for asymptotic notation to the 'Datastructures and Algorithms' block in the Python roadmap.

### ISSUE THREAD

**Issue by Kazutadashi** [kamranahmedse/developer-roadmap#4950]
### Roadmap URL

https://roadmap.sh/python

### Suggestions

I propose the addition of two resources to the 'Datastructures and Algorithms' block:

- Add [this Khan Academy article](https://www.khanacademy.org/computing/computer-science/algorithms/asymptotic-notation/a/asymptotic-notation) to better explain asymptotic notation. (The follow up articles are accessible from this main link which are also useful). 
- Add [this YouTube video](https://www.youtube.com/watch?v=Q_1M2JaijjQ) to provide visualizations and very clear examples of how you would calculate the runtime and provide a solution using Big-O notation.

This is an exceptionally important topic which is only briefly explained in [the existing resource from programiz](https://www.programiz.com/dsa/asymptotic-notations).

**Comment by arikchakma** [comment]
We are now closing any issues requesting new features/roadmap to clean up the issues.

However, this doesn’t mean that the requested feature/roadmap won’t be added to the website. We are putting it in the backlog and will add it to the website depending on how it ranks in the backlog or sooner if we find someone interested in adding that feature/roadmap. Thank you for the request though! :pray:
