### ISSUE TITLE
Background colour change

### ISSUE THREAD

**Issue by DEVHrishi** [kamranahmedse/developer-roadmap#4959]
### Roadmap URL

https://roadmap.sh/

### When I **"skip"** something its background color changes to white or grey which is almost identical to **"DONE"** background color. 
Pls change the **"skip"** background color to a different color.

**Comment by arikchakma** [comment]
We are now closing any issues requesting new features/roadmap to clean up the issues.

However, this doesn’t mean that the requested feature/roadmap won’t be added to the website. We are putting it in the backlog and will add it to the website depending on how it ranks in the backlog or sooner if we find someone interested in adding that feature/roadmap. Thank you for the request though! :pray:
