### ISSUE TITLE
Add a link to the Rust roadmap in the Backend Developer roadmap (Visit Dedicated Rust Roadmap)

### ISSUE THREAD

**Issue by rekvizitt** [kamranahmedse/developer-roadmap#4971]
### Roadmap URL

https://roadmap.sh/backend

### Suggestions

Add a link to the [Rust roadmap](https://roadmap.sh/rust) in the [Backend Developer](https://roadmap.sh/backend) roadmap (Visit Dedicated Rust Roadmap)

Add to this item:
![image](https://github.com/kamranahmedse/developer-roadmap/assets/58174945/c71ff7a4-0024-4313-8df8-7db0e464fdb7)
A link to the roadmap (as in the picture):
![image](https://github.com/kamranahmedse/developer-roadmap/assets/58174945/02f2e1de-0c93-4c39-8d86-5fbb28a1efc6)

**Comment by arikchakma** [comment]
We are now closing any issues requesting new features/roadmap to clean up the issues.

However, this doesn’t mean that the requested feature/roadmap won’t be added to the website. We are putting it in the backlog and will add it to the website depending on how it ranks in the backlog or sooner if we find someone interested in adding that feature/roadmap. Thank you for the request though! :pray:
