### ISSUE TITLE
Javascript Roadmap

### ISSUE THREAD

**Issue by Alanm17** [kamranahmedse/developer-roadmap#4974]
### Roadmap URL

https://roadmap.sh/javascript

### Suggestions

If i want to use the javascript roadmap. its template is not editable, i want to use javascript roadmap template. 
"Create your own version of this roadmap" is not available for javascript.

**Comment by arikchakma** [comment]
We've not added the forkable JS roadmap yet.

I'm closing this issue for now. However, it doesn't mean that the JS roadmap won't be added to the website. We are putting it in the backlog and will add it to the website depending on how it ranks in the backlog or sooner if we find someone interested in adding that forkable roadmap. Thank you for the request though! 🙏
