### ISSUE TITLE
Copy the content and links during creating own version of a roadmap

### ISSUE THREAD

**Issue by Bapego** [kamranahmedse/developer-roadmap#4976]
### Feature Description

When I copy an existing roadmap (I use the 'Create your own version of this roadmap' button), in the forked version, the steps don't contain the link and content of the original version. But I guess it could be really useful.

**Comment by arikchakma** [comment]
We are now closing any issues requesting new features/roadmap to clean up the issues.

However, this doesn’t mean that the requested feature/roadmap won’t be added to the website. We are putting it in the backlog and will add it to the website depending on how it ranks in the backlog or sooner if we find someone interested in adding that feature/roadmap. Thank you for the request though! :pray:
