### ISSUE TITLE
New Practice for Good Prompt

### ISSUE THREAD

**Issue by omkargarad78** [kamranahmedse/developer-roadmap#4982]
### Roadmap URL

https://roadmap.sh/prompt-engineering

### Suggestions

I would like to add a new practice that is essential and important for the writing Professional Prompts. It makes the prompt Clear and Concise making the language module to be clear, minimizing the risk of generating hallucinated or ambiguous responses.

This practice streamlines communication with the language model, making it more effective and reliable prompt engineering process.

Here is the file:-
[108-Clear-and-precise.md](https://github.com/kamranahmedse/developer-roadmap/files/13838578/108-Clear-and-precise.md)

**Comment by arikchakma** [comment]
We are now closing any issues regarding bug fixes or requesting new features/roadmap to clean up the issues.

However, this doesn’t mean that the requested bug fix/feature/roadmap won’t be fixed/added to the website. We are putting it in the backlog and will add it to the website depending on how it ranks in the backlog or sooner if we find someone interested in fixing the bug or adding that feature/roadmap. Thank you for the request though! :pray:
