### ISSUE TITLE
Generators in Python Roadmap

### ISSUE THREAD

**Issue by tobiasborgesguimaraes** [kamranahmedse/developer-roadmap#4984]
### Roadmap URL

https://roadmap.sh/python

### Suggestions

In the Python Developer Roadmap, there is no 'Generator' topic before the 'Generator Expressions' one. Having a 'Generator' topic linked to the 'iterators' one could help people know that this is a sequence of the knowledge they have just acquired, and only then, they can study Generators Expressions.

**Comment by arikchakma** [comment]
We are now closing any issues regarding bug fixes or requesting new features/roadmap to clean up the issues.

However, this doesn’t mean that the requested bug fix/feature/roadmap won’t be fixed/added to the website. We are putting it in the backlog and will add it to the website depending on how it ranks in the backlog or sooner if we find someone interested in fixing the bug or adding that feature/roadmap. Thank you for the request though! :pray:
