### ISSUE TITLE
Extra resources for Frontend Developer Roadmap

### ISSUE THREAD

**Issue by KananHasanov747** [kamranahmedse/developer-roadmap#4985]
### Roadmap URL

https://roadmap.sh/frontend

### Suggestions

- Add new section for Authentication sources:
  - [Auth0](https://auth0.com)
  - [Supabase](https://supabase.com)
  - [Auth.js](https://authjs.dev)
  - [nuxt/auth](https://auth.nuxtjs.org/)
  - [Clerk](https://clerk.com)

- Add links to these sources, that is, make them interactive:

![Screenshot 2024-01-05 at 9 07 25 PM](https://github.com/kamranahmedse/developer-roadmap/assets/83110215/29f32119-80df-460b-b38f-cddd4f9c93f4)

**Comment by arikchakma** [comment]
We are now closing any issues requesting new features/roadmap to clean up the issues.

However, this doesn’t mean that the requested feature/roadmap won’t be added to the website. We are putting it in the backlog and will add it to the website depending on how it ranks in the backlog or sooner if we find someone interested in adding that feature/roadmap. Thank you for the request though! :pray:
