### ISSUE TITLE
.Net Full-stack developers roadmap

### ISSUE THREAD

**Issue by sumitsorate** [kamranahmedse/developer-roadmap#4988]
### Feature Description

Can you please suggest road map for .net full-stack development. so we can have .net as backend and angular/react as frontend.

**Comment by arikchakma** [comment]
We are now closing any issues requesting new roadmap requests to clean up the issues. 

However, this doesn't mean that the requested roadmap won't be added to the website. We are putting it in the backlog and will add it to the website depending on how it ranks in the backlog or sooner if we find someone interested in adding that roadmap. Thank you for the request though! 🙏
