### ISSUE TITLE
Could you please add a roadmap for Architecture?

### ISSUE THREAD

**Issue by zhaoyao91** [kamranahmedse/developer-roadmap#499]

**Comment by WindNinja** [comment]
or how about something for to become ethical hacker?

**Comment by jjangga0214** [comment]
@WindNinja This repo focuses on web development. Hacker roadmap might be out of consistency, and if you think so, why don't you make a new repo dedicated for the topic? You are just able to reuse the json format for generate roadmap flow image, if it's desired.

**Comment by kamranahmedse** [comment]
New roadmap requests are being tracked through [roadmap.sh](https://github.com/kamranahmedse/roadmap.sh). Thank you!
