### ISSUE TITLE
Specific Cybersecurity Roadmaps

### ISSUE THREAD

**Issue by jirsc** [kamranahmedse/developer-roadmap#4990]
### Roadmap URL

https://roadmap.sh/cyber-security

### Suggestions

Cybersecurity is a very vast field. I hope you create more role-specific roadmaps like Digital Forensics, Blue Team, Red Team, Penetration Tester, Malware Analyst, and so on.

**Comment by arikchakma** [comment]
We are now closing any issues requesting new features/roadmap to clean up the issues.

However, this doesn’t mean that the requested feature/roadmap won’t be added to the website. We are putting it in the backlog and will add it to the website depending on how it ranks in the backlog or sooner if we find someone interested in adding that feature/roadmap. Thank you for the request though! :pray:
