### ISSUE TITLE
New Cyber Security Platform

### ISSUE THREAD

**Issue by besimaltnok** [kamranahmedse/developer-roadmap#4993]
### Roadmap URL

https://roadmap.sh/cyber-security

### Suggestions

We created new platform for teach cyber security to everyone. We want to help everyone. If it is possible can you add our platform: https://cyberexam.io.

**Comment by arikchakma** [comment]
We are now closing any issues regarding bug fixes or requesting new features/roadmap to clean up the issues.

However, this doesn’t mean that the requested bug fix/feature/roadmap won’t be fixed/added to the website. We are putting it in the backlog and will add it to the website depending on how it ranks in the backlog or sooner if we find someone interested in fixing the bug or adding that feature/roadmap. Thank you for the request though! :pray:
