### ISSUE TITLE
Broken link in UX-Design/Understanding Human Decision Making

### ISSUE THREAD

**Issue by OhmSpectator** [kamranahmedse/developer-roadmap#4995]
### What is the URL where the issue is happening

https://roadmap.sh/ux-design

### What browsers are you seeing the problem on?

Chrome

### Describe the Bug

The following link: [Types of Cognitive Bias](https://www.youtube.com/watch?v=wewgbir_riw) points to an unavailable video.

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by dev-aly3n** [comment]
Hi, based on data in [archive.org](https://archive.org) found the video: [12 Cognitive Biases Explained - How to Think Better and More Logically Removing Bias](https://www.youtube.com/watch?v=wEwGBIr_RIw)

**Comment by dansholds** [comment]
Issue fixed in #5014.

@dev-aly3n Thanks for submitting the PR! Next time can you create the branch from the issue in order to auto-close the issue when the PR is merged? Thanks again!
