### ISSUE TITLE
An extensive DSA (data structures and algorithm) and CP (competitive programming) Roadmap.

### ISSUE THREAD

**Issue by singhxayush** [kamranahmedse/developer-roadmap#4996]
### Feature Description

1. An extensive roadmap that beginner can look up to to understand what is the difference between the two
2. What to start and what not to. Differing resources for both. And the the break down of the most frequently asked question on what language to start with for the two.
3. Websites to practice and compete
4. What things to know specific to DSA trend and What extra and different things to know in CP.
5. And a lot more on how to achieve and practice for certain rankings targeting a specific platforms like CodeForces or Leetcode. How to target ICPC and stuff.

**Comment by arikchakma** [comment]
We are now closing any issues requesting new roadmap requests to clean up the issues. 

However, this doesn't mean that the requested roadmap won't be added to the website. We are putting it in the backlog and will add it to the website depending on how it ranks in the backlog or sooner if we find someone interested in adding that roadmap. Thank you for the request though! 🙏

**Comment by singhxayush** [comment]
Thank you @arikchakma :)
