### ISSUE TITLE
Can add the text editors, programming environments etc.

### ISSUE THREAD

**Issue by redemptgtx** [kamranahmedse/developer-roadmap#5]
I can help you for updating this context if you want. It can be helpful for juniors like me :)

**Comment by VictorAvelar** [comment]
@redemptgtx I can jump into this too.

**Comment by damengilland** [comment]
Learning a powerful text editor should be at the top in the "for all paths" section.

I think start with Sublime or Atom.  Vim... seems a bit more complicated to start with.  Notepad++ is old and busted.  I'd stick with just Sublime or Atom. (=

* Sublime Text: The text editor you'll fall in love with || http://www.sublimetext.com/

* Atom || https://atom.io/

**Comment by luchillo17** [comment]
Leaving aside the fact that you leave VSCode out, which should be at the same level that the 2 mentioned.

Should a text editor really be on the roadmap to any developer? you can program with virtually any program that outputs text files with the right extension, or none at all with the terminal and `vi` or `nano`.

Using text editors to do the job is just fanciness, i see the roadmap like a map of the related technologies that should or are recommended to perform well or eve master such area, and a text editor doesn't fit in my criteria.

Take as example the terminal vs an editor, you can ignore the editor but never the terminal, you use the terminal for virtually all, downloading and installing dependencies, running task and build pipelines, connect to servers, it can tell you the hour or destroy the pc with a misplaced `rm -rf /`, the terminal is the greatest weapon in a developer arsenal, and as any weapon if you don't respect it you could end up shooting your own foot.

But an editor is just an editor, fancy, cute, and helpful, but nothing more (well some of them can run tasks by themselves  directly or through their own integrated terminal), so adding them to the roadmap is just cluttering the map with unnecessary information.

Though that's just my opinion, what do you guys think?

**Comment by damengilland** [comment]
@luchillo17 You aren't wrong... but I think knowing a cute fancy text editor helps get people more familiar with other things.  I'd have a hard time taking someone seriously as a dev if they didn't have mastery of some sort of editor or IDE...  It's certainly faster, I think, if you know those tools.  I'd cringe if I hired a contract dev and he wasn't using some sort of fancy editor... paying him hourly to do work... I want him to be efficient.

But... you aren't wrong... an editor isn't needed to write code.

**Comment by luchillo17** [comment]
@damengilland Yep, tough i've read of people that only uses `vi` because they feel slow with the editors.

I'm sorry if i was a bit rough, but actually putting the editors in, would make this look a bit less like a roadmap, and more like a pensum, like a plan of things you could learn, and editors would be in the `optional subjects` section, don't you think?

**Comment by damengilland** [comment]
That works, Optional...  Learn them for your own sanity, and also to help convince others you are a real developer.

**Comment by luchillo17** [comment]
Agree, maybe put it on top but not united by the arrow, but stating as a recommendation or something like that?

**Comment by damengilland** [comment]
* Importance Of Good Text Editors And Ide For Writing Code | Yash Ballani || https://yashballani.com/blog/importance-of-good-text-editors-and-ide-for-writing-code

**Comment by kamranahmedse** [comment]
Thank you for opening the issue. While I agree with that, we don't want to convolute the roadmap by mentioning everything out there. Regarding the IDE, I don't think we should add the recommendations as a part of roadmap.

However, I will find a place for that in textual form somewhere outside the roadmap. Thank you 🙏
