### ISSUE TITLE
Add PowerShell to scripting languages

### ISSUE THREAD

**Issue by halr9000** [kamranahmedse/developer-roadmap#500]
I found PowerShell strangely lumped in with some shell editors (vi, emacs) on the DevOps roadmap. As it's not an editor, it would be great if you moved it next to Python, JavaScript, etc.

**Comment by Ronkiro** [comment]
I find a great idea to remove PowerShell from the same side of Vim, nano, etc.
But i don't think it's a great idea to side it with Python, JS...
Maybe side it with Bash?

**Comment by plarabee** [comment]
I came here to post this issue but was happy to find another one. At least on the DevOps roadmap, I would move Powershell up to the Bash level. I think all DevOps professionals would do well to know Bash but there are a lot of .NET shops around that live and breathe Powershell.

**Comment by kamranahmedse** [comment]
This has been fixed and will be published in the coming release. Thank you 🙏
