### ISSUE TITLE
The progress mark is duplicated

### ISSUE THREAD

**Issue by VovkaLW** [kamranahmedse/developer-roadmap#5000]
### What is the URL where the issue is happening

https://roadmap.sh/game-developer

### What browsers are you seeing the problem on?

Chrome

### Describe the Bug

When you check the progress of the "Orientation" tab, the "Curves" tab is also checked
![photo_2024-01-08_22-01-18](https://github.com/kamranahmedse/developer-roadmap/assets/78707169/db2910ab-c1ee-4de8-9852-4a1d4d6ab408)
![photo_2024-01-08_22-01-28](https://github.com/kamranahmedse/developer-roadmap/assets/78707169/ab65ab21-d501-48ff-be02-1ba5fc764127)

### Participation

- [X] I am willing to submit a pull request for this issue.

**Comment by arikchakma** [comment]
We are now closing any issues regarding bug fixes or requesting new features/roadmap to clean up the issues.

However, this doesn’t mean that the requested bug fix/feature/roadmap won’t be fixed/added to the website. We are putting it in the backlog and will add it to the website depending on how it ranks in the backlog or sooner if we find someone interested in fixing the bug or adding that feature/roadmap. Thank you for the request though! :pray:
