### ISSUE TITLE
Why can I fork some roadmaps and not others?

### ISSUE THREAD

**Issue by mpoferl** [kamranahmedse/developer-roadmap#5004]
### What is the URL where the issue is happening

https://roadmap.sh/flutter

### Describe the Bug

Like for the Frontend Developer, I want to fork the Flutter Developer. Why are some not able to fork?

![Bildschirmfoto 2024-01-09 um 09 19 07](https://github.com/kamranahmedse/developer-roadmap/assets/11260699/f3e4c6bd-32ca-48e6-8e95-76399bb71d07)
![Bildschirmfoto 2024-01-09 um 09 19 16](https://github.com/kamranahmedse/developer-roadmap/assets/11260699/d650c7df-9f54-4360-89ec-3fdfe6be3c47)

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by arikchakma** [comment]
It's because we haven't added that forkable data yet.
