### ISSUE TITLE
Listing Indexes

### ISSUE THREAD

**Issue by Paniconthebrain1** [kamranahmedse/developer-roadmap#5006]
### Roadmap URL

https://roadmap.sh/sql

### Suggestions

select * from sys.indexes
where object_id = (select object_id from sys.objects where name in ('table_name'))

**Comment by arikchakma** [comment]
We are now closing any issues regarding bug fixes or requesting new features/roadmap to clean up the issues.

However, this doesn’t mean that the requested bug fix/feature/roadmap won’t be fixed/added to the website. We are putting it in the backlog and will add it to the website depending on how it ranks in the backlog or sooner if we find someone interested in fixing the bug or adding that feature/roadmap. Thank you for the request though! :pray:
