### ISSUE TITLE
Card Wide is not updating on github profile readme

### ISSUE THREAD

**Issue by AugustoRickes** [kamranahmedse/developer-roadmap#5007]
### What is the URL where the issue is happening

https://api.roadmap.sh/v1-badge/wide/64b17cfa5f038d81eeb3ec57?variant=dark

### Describe the Bug

After updating the roadmap, the card only updates on the https://roadmap.sh/account/road-card website and the api that is used in githubprofile does not update https://api.roadmap.sh/v1-badge/wide/64b17cfa5f038d81eeb3ec57?variant=dark

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by arikchakma** [comment]
Can you please provide a video or screenshot please?

**Comment by AugustoRickes** [comment]
![image](https://github.com/kamranahmedse/developer-roadmap/assets/103668139/f6f815cd-4d34-407c-b331-584787198d6e)
![image](https://github.com/kamranahmedse/developer-roadmap/assets/103668139/59b9f5e8-3a47-4646-8bd3-a6fc592bd066)

**Comment by AugustoRickes** [comment]
Thanks a bunch, that sorted it out!
