### ISSUE TITLE
Game Developer: Curve and Orientation objects are coupled

### ISSUE THREAD

**Issue by crystalsolenoid** [kamranahmedse/developer-roadmap#5011]
### What is the URL where the issue is happening

https://roadmap.sh/game-developer

### What browsers are you seeing the problem on?

Firefox

### Describe the Bug

- When clicking on the Curve section, I instead see a description for the Orientation section.
- When I update the status of the Orientation section, it visually changes both the status of the Curve box and the Orientation box.
- Clicking on the Curve box and then clicking the "edit this content" link leads to the code for the [orientation content file](https://github.com/kamranahmedse/developer-roadmap/blob/master/src/data/roadmaps/game-developer/content/101-game-mathematics/106-orientation/index.md).

Inspecting element shows that both the Curve box and the Orientation box both have the ID `data-group-id="106-game-mathematics:orientation"`

It looks like the sections under the Curve section are all in the [Orientation folder](https://github.com/kamranahmedse/developer-roadmap/tree/master/src/data/roadmaps/game-developer/content/101-game-mathematics/106-orientation).

I'd be happy to figure out how to fix this if it's as straightforward as I think, but I don't see a content file for the Curves section, and I don't think I'm qualified to write it. That would be my hangup if it isn't already written somewhere.

### Participation

- [X] I am willing to submit a pull request for this issue.

**Comment by dansholds** [comment]
Thanks for raising this!

I'll have a look at it 👀

**Comment by dansholds** [comment]
@crystalsolenoid Kamran has just pushed this fix so expect to see it live soon! 🎉
