### ISSUE TITLE
DESIGN PATTERNS

### ISSUE THREAD

**Issue by aravindhnirmal** [kamranahmedse/developer-roadmap#5015]
### Roadmap URL

https://roadmap.sh/java

### Suggestions

Add Design patterns in java for more deep with java

**Comment by karim1safan** [comment]
This course is perfect design patterns using java
https://www.coursera.org/learn/design-patterns

**Comment by simone-boa-ideas** [comment]
I also highly suggest this website for design patterns: https://refactoring.guru/design-patterns
