### ISSUE TITLE
my experience navigating the rodmaps

### ISSUE THREAD

**Issue by saychung** [kamranahmedse/developer-roadmap#5018]
### Roadmap URL

https://roadmap.sh/frontend

### Suggestions

a check box and an information button on each step to update status without  having to select from the drop down in the side overlay. Or have a set of radio buttons on the side overlay for easier status updation!

**Comment by kamranahmedse** [comment]
You can use the shortcuts to mark your progress

<img width="474" alt="image" src="https://github.com/kamranahmedse/developer-roadmap/assets/4921183/da6ab4c7-89c3-4e40-a675-32a39ba6520f">
