### ISSUE TITLE
Link Broken!

### ISSUE THREAD

**Issue by LopesLs** [kamranahmedse/developer-roadmap#5019]
### What is the URL where the issue is happening

https://roadmap.sh/backend

### What browsers are you seeing the problem on?

Firefox

### Describe the Bug

In the backend roadmap, a topic called **HATEOAS** redirects me to a video in youtube that is private right now.

![screenshoot](https://github.com/kamranahmedse/developer-roadmap/assets/97265556/f39929e6-eb3a-437b-bc33-614ee9c4c222)

As a suggest i would remove the link and put [this](https://www.geeksforgeeks.org/hateoas-and-why-its-needed-in-restful-api/) helpfull article

### Participation

- [X] I am willing to submit a pull request for this issue.

**Comment by dansholds** [comment]
Broken link removed.
