### ISSUE TITLE
Validation failure message - Path 'slug' is required

### ISSUE THREAD

**Issue by lewisveale** [kamranahmedse/developer-roadmap#5023]
### What is the URL where the issue is happening

https://draw.roadmap.sh/652e41e8f43a58c923ddaced

### What browsers are you seeing the problem on?

Chrome

### Describe the Bug

I simply open my custom roadmap (URL provided), press the Save Roadmap button, and immediately get a validation message at the bottom, middle of the screen - "Roadmap validation failed: slug: Path 'slug' is required".

### Output from browser console (if any)

PATCH https://api.roadmap.sh/v1-update-roadmap/652e41e8f43a58c923ddaced 500 (Internal Server Error)
p @ Tooltip.9b65fb91.js:1
H @ Tooltip.9b65fb91.js:1
(anonymous) @ MainPage.e4b43e97.js:20
onClick @ MainPage.e4b43e97.js:2
Va @ index.c340ef4b.js:21
Ba @ index.c340ef4b.js:21
Ha @ index.c340ef4b.js:21
Hu @ index.c340ef4b.js:21
ws @ index.c340ef4b.js:21
(anonymous) @ index.c340ef4b.js:21
su @ index.c340ef4b.js:24
Qo @ index.c340ef4b.js:21
Cl @ index.c340ef4b.js:21
Ii @ index.c340ef4b.js:21
lc @ index.c340ef4b.js:21

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by lewisveale** [comment]
Also happens in Edge and Firefox.

**Comment by Musab-Nuirat** [comment]
I have the same bag, when i press `Create your own version of this roadmap` i have `Roadmap validation failed: slug: Path 'slug is required` too.

**Comment by arikchakma** [comment]
Working on it

**Comment by kamranahmedse** [comment]
This should be fine now, please let us know if you still face any issues.
