### ISSUE TITLE
"How to Implement Binary Search Tree in Python" link broken

### ISSUE THREAD

**Issue by bacciotti** [kamranahmedse/developer-roadmap#5043]
### What is the URL where the issue is happening

https://roadmap.sh/python

### What browsers are you seeing the problem on?

Firefox

### Describe the Bug

In the Datastructures & Algorithms -> Binary Search Tree section, the "[How to Implement Binary Search Tree in Python](https://www.section.io/engineering-education/implementing-binary-search-tree-using-python/)" link points to host provider (webscale.com).

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by Nadeem-Ahmad-25** [comment]
is  this issue fixed ? can i contribute

**Comment by dansholds** [comment]
Issue fixed in #5045
