### ISSUE TITLE
[bug] Road Card is Not Showing Properly in Tall Mode

### ISSUE THREAD

**Issue by subhadipbhowmik** [kamranahmedse/developer-roadmap#5048]
### What is the URL where the issue is happening

https://api.roadmap.sh/v1-badge/tall/65550d7d68ca60261335f24b?variant=dark

### What browsers are you seeing the problem on?

Chrome

### Describe the Bug

The tall mode of the Road card is not showing in the browser properly. Like the bottom section of the card content is not loading completely. It's working fine in wide mode only. 
![road-card-problem](https://github.com/kamranahmedse/developer-roadmap/assets/57017965/aa0c2911-c251-41e9-a54e-f5c5507532d5)

### Participation

- [X] I am willing to submit a pull request for this issue.

**Comment by kamranahmedse** [comment]
Can you please share your browser information? This seems to be working fine.
