### ISSUE TITLE
Issues with Frontend Roadmap

### ISSUE THREAD

**Issue by ghost** [kamranahmedse/developer-roadmap#5062]
### What is the URL where the issue is happening

https://roadmap.sh/frontend

### Describe the Bug

![image](https://github.com/kamranahmedse/developer-roadmap/assets/139033312/c30e7489-e167-409c-9a12-84905a5b11fd)
Like this we are able to even check the link to beginner version as completed and even after that,   
![image](https://github.com/kamranahmedse/developer-roadmap/assets/139033312/b705e85a-2f42-4033-b484-4abcb43d40b7)
the roadmap shows as incomplete on the home page

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by Nadeem-Ahmad-25** [comment]
@Paras-Baweja hi! can I contribute if its not been assigned yet?

**Comment by Paras-Baweja** [comment]
@Nadeem-Ahmad-25 Actually, I just reported the issue, and no staff has said to go with it. So, you can go on but I would suggest asking some staff first

**Comment by Mark-kus** [comment]
Hi, I want to give more information about a related bug. I have completed the frontend roadmap, and two things I don´t think should happend occur.

1. When added to favs, It looks as it is not fulfilled
![image](https://github.com/kamranahmedse/developer-roadmap/assets/93273771/0fc3cc6f-dac1-4417-8595-4481f7406249)
2. In my profile, it says I have 123 done from 138 total
![image](https://github.com/kamranahmedse/developer-roadmap/assets/93273771/320a952e-2a58-4921-ab3a-59d5a5cd4df9)

Inside the roadmap it looks all good
![image](https://github.com/kamranahmedse/developer-roadmap/assets/93273771/d1ee4689-e5f0-4a14-93cc-a66296074b66)

Glad to help!

**Comment by dansholds** [comment]
Hey everyone! 

Thanks for reporting this, I can replicate it on my end too so I have created an internal ticket for us to investigate the source of the issue!

@Mark-kus screenshot showing 123 out of 138 is pretty telling though.

**Comment by kamranahmedse** [comment]
Hey there!

Looks like this issue has been hanging around for a bit without much action. Our roadmaps have evolved quite a bit since then, and a bunch of older issues aren't really applicable anymore. So, we're tidying things up by closing out the older ones to keep our issue tracker nice and organized for future feedback.

If you still think this problem needs addressing, don't hesitate to reopen the issue. We're here to help!

Thanks a bunch!
