### ISSUE TITLE
Dead youtube link - esbuilds

### ISSUE THREAD

**Issue by FredericGaudreau** [kamranahmedse/developer-roadmap#5076]
### What is the URL where the issue is happening

https://roadmap.sh/frontend

### What browsers are you seeing the problem on?

Firefox

### Describe the Bug

The last link [What Is ESBuild?](https://www.youtube.com/watch?v=zy8vu8cbwf0) in the esbuilds section leads to a "video is not available" page on youtube.

![image](https://github.com/kamranahmedse/developer-roadmap/assets/88415888/9e4b43ae-60f5-410a-bad0-637017b7d671)

Found here: src/data/roadmaps/frontend/content/110-build-tools/101-module-bundlers/101-esbuild.md (loc: 10)

### Participation

- [X] I am willing to submit a pull request for this issue.

**Comment by dev-aly3n** [comment]
Hi @FredericGaudreau , I found the correct link to this video.
archive link: [https://web.archive.org/web/20230329144815/https://www.youtube.com/watch?v=ZY8Vu8cbWF0](https://web.archive.org/web/20230329144815/https://www.youtube.com/watch?v=ZY8Vu8cbWF0)
youtube link: [https://www.youtube.com/watch?v=ZY8Vu8cbWF0](https://www.youtube.com/watch?v=ZY8Vu8cbWF0)
It seems they have changed the name of their channel to 'Syntax'. but this is the exact same video.

**Comment by FredericGaudreau** [comment]
You're right. I just wanted to let people know about this small "bug" so it can be fixed. I don't mind doing the change if needed.

**Comment by dev-aly3n** [comment]
As you checked the box "I am willing to submit a pull request for this issue." I just wanted to help you fix it.
you can open a PR and mention this issue.
