### ISSUE TITLE
Youtube video deleted

### ISSUE THREAD

**Issue by mteen1** [kamranahmedse/developer-roadmap#5079]
### Roadmap URL

https://roadmap.sh/blockchain

### Suggestions

The Youtube video on blockchain roadmap -> Blockchain forking, with the link of https://www.youtube.com/watch?v=bu1gcyyfz7w
is removed and its not available

**Comment by dansholds** [comment]
If you have content changes for roadmaps then please submit those as a **PR** to the relevant section of the roadmap rather than opening an issue. 

🌮
