### ISSUE TITLE
Provide more vulnerable application or CTF sites (CTFs)

### ISSUE THREAD

**Issue by sinanganiz** [kamranahmedse/developer-roadmap#5083]
### Roadmap URL

https://roadmap.sh/cyber-security

### Suggestions

Hackviser: Exclusive cybersecurity upskilling platform that offers free and paid content.
https://hackviser.com/

Root Me  : CTF challenge platform that provides challenges under many categories.
https://www.root-me.org/

**Comment by dansholds** [comment]
If you have content additions to add to roadmaps then please submit those as a PR to the relevant section of the roadmap rather than opening an issue. 

🌮
