### ISSUE TITLE
Java Web can be expanded

### ISSUE THREAD

**Issue by aravindrajpalani** [kamranahmedse/developer-roadmap#51]
**Tools** 
- Maven
- Gradle

**Frameworks**
- Spring MVC
- JSF
- Grails
- Struts
- Hibernate

**Testing**
- JTest
- JUnit
- TestNG

**IDE**
- Netbeans
- Eclipse
- IntelliJ IDEA

Above are technologies and tools which I am aware of..There may be more tools and technologies.

**Comment by zhangqunshi** [comment]
Frameworks also have:
Spring boost 
ibatis

**Comment by sonipks** [comment]
Agree with it. More frameworks can be added. Also, web-services, web portlets, persistence, web frameworks, spring stuffs, messaging etc can be added

**Comment by kamranahmedse** [comment]
[There was a similar request for .NET](https://github.com/kamranahmedse/developer-roadmap/pull/48) but for now we will not be able to add expand any further technologies. The graph is already too much convoluted and it is becoming difficult to even read. So let's keep keep it to what we have (PHP, Node, Python and Ruby), till we figure out how to fit in everything.

Thank you.
