### ISSUE TITLE
Add some path for functional programming

### ISSUE THREAD

**Issue by PatrickRNG** [kamranahmedse/developer-roadmap#510]
Add in some path, maybe in backend, (a kinda distinct path) for functional programming, maybe something saying why use it too.

**Comment by Ronkiro** [comment]
I don't think this is needed. People ends up studying the same ideas as others paradigms.
I know that functional paradigm is less known than the others, but doing that would "ask" to make a path for each paradigm. Probably not worth.

**Comment by lazarljubenovic** [comment]
None of the charts seem to mention anything about coding style or different ways you can structure the architecture of the system. If the guide mentions functional programming, there's no reason not to mention reactive programming, object-oriented programming, etc.

Also the back-end path already contains "scripting" and "functional" languages at the top, isn't that enough of a nod?
