### ISSUE TITLE
Outdated URL

### ISSUE THREAD

**Issue by Altaner** [kamranahmedse/developer-roadmap#5109]
### What is the URL where the issue is happening

https://github.com/kamranahmedse/developer-roadmap/blob/master/src/data/roadmaps/backend/content/109-apis/104-hateoas.md

### What browsers are you seeing the problem on?

Microsoft Edge

### Describe the Bug

On this page, the YouTube URL is outdated. The URL is not working.

### Participation

- [x] I am willing to submit a pull request for this issue.

**Comment by dansholds** [comment]
No outdated Youtube URL found.
