### ISSUE TITLE
[user experience issue]: right-positioned modal (TopicDetail) on large displays

### ISSUE THREAD

**Issue by dev-aly3n** [kamranahmedse/developer-roadmap#5123]
### Detailed Description

Could we please consider relocating the `TopicDetail` modal to the center for wide screens? Currently, reading content on the right is challenging and causing discomfort in the neck.
 I have attached two images below to visually demonstrate the issue on wide screens.

right-positioned modal:

![DevOps-Roadmap-Learn-to-become-a-DevOps-Engineer-or-SRE2](https://github.com/kamranahmedse/developer-roadmap/assets/79654879/dc26d4e3-15e8-4561-bb3c-03e1be7b53b3)

center-positioned modal:

![DevOps-Roadmap-Learn-to-become-a-DevOps-Engineer-or-SRE](https://github.com/kamranahmedse/developer-roadmap/assets/79654879/0f6be1c3-1ac1-438c-8ec0-c697e993f395)

**Comment by dev-aly3n** [comment]
There can be more improvement instead of just centering the modal. However, I addressed that single issue first to see if you agree with this change. Then we can discuss making it better, such as decreasing the height and centering it vertically, and etc.
@arikchakma @kamranahmedse

**Comment by ArianHamdi** [comment]
I agree. This is a bit annoying on wider screens.

**Comment by dev-aly3n** [comment]
Hi, what do you mean by completed? I can't see this feature in the app. maybe just keep it open or close it as not planned
