### ISSUE TITLE
🚧 WIP: PHP

### ISSUE THREAD

**Issue by iPoetDev** [kamranahmedse/developer-roadmap#5127]
### What is the title of the roadmap you are submitting?

Roadmap to Learn PHP

### Roadmap Link

https://roadmap.sh/r?id=65bd25950c54812283803899
A work in progress. I first touched PHP 20 years ago, so using this in first instance to mind map PHP as a learning tool for personal use, though contribs welcome.

Use the Python one as a comparison.

No content in nodes yet. 

Sources:
https://www.php.net/manual/en/
https://phptherightway.com/
https://www.jetbrains.com/help/phpstorm/

**Comment by developerstudservis** [comment]
Hi! 

Hm, I am interested in PHP roadmap for my colleagues. Any progress? 
By [link](https://roadmap.sh/r?id=65bd25950c54812283803899) I see 
```
Restricted Access
JSON.parse: unexpected character at line 1 column 1 of the JSON data
```

And can't find PHP at roadmap.sh site((
