### ISSUE TITLE
Serverless etc.

### ISSUE THREAD

**Issue by psimondk** [kamranahmedse/developer-roadmap#514]
Even though you could argue that languages Python and JS and to a lesser extend C# covers serverless I think you should add it as it becomes more and more real at the backend - think Firebase and its ilk.

In the same vein consider 'low code' platforms like ServiceNow and SalesForce.

Finally intelligent backends powered by machine learning and other AI is very fast becoming a thing to consider

**Comment by Xeverous** [comment]
There are even more paths for the career, roadmaps do not cover anything like driver or microcontroller OS implementation, HPC, research applications etc.

**Comment by kamranahmedse** [comment]
This has been fixed and will be published in the coming release. Thank you 🙏
