### ISSUE TITLE
Broken link for Domain-Driven Design

### ISSUE THREAD

**Issue by simonebogni** [kamranahmedse/developer-roadmap#5142]
### What is the URL where the issue is happening

https://roadmap.sh/software-architect

### What browsers are you seeing the problem on?

Chrome

### Describe the Bug

The link inside the Domain-Driven Design topic of the Software Architect roadmap points to a non-existing or unavailable resource.
The current link is https://matfrs2.github.io/RS2/predavanja/literatura/Avram%20A,%20Marinescu%20F.%20-%20Domain%20Driven%20Design%20Quickly.pdf
I suggest replacing it with https://www.infoq.com/minibooks/domain-driven-design-quickly/
The new page offers both the option to download the pdf for free, or to pay for the print option. 

### Participation

- [X] I am willing to submit a pull request for this issue.

**Comment by dev-aly3n** [comment]
Hi, this is the exact page. it's a pdf: [https://web.archive.org/web/20230606035225/https://matfrs2.github.io/RS2/predavanja/literatura/Avram%20A,%20Marinescu%20F.%20-%20Domain%20Driven%20Design%20Quickly.pdf](https://web.archive.org/web/20230606035225/https://matfrs2.github.io/RS2/predavanja/literatura/Avram%20A,%20Marinescu%20F.%20-%20Domain%20Driven%20Design%20Quickly.pdf)
