### ISSUE TITLE
Give an ability to view the description of any stage in roadmap in a bigger view(expandable)

### ISSUE THREAD

**Issue by mihirsar** [kamranahmedse/developer-roadmap#5163]
### Feature Description

Recently I went to the Docker Roadmap the initial intro and topic wise description seemed interesting to me, gives a gist about topic & sparks interest but I suggest that **description part of theory things when opened should be made expandable**, thus it will become more readable. Thank you very much

**Comment by mihirsar** [comment]
> ### Feature Description
> 
> Recently I went to the Docker Roadmap the initial intro and topic wise description seemed interesting to me, gives a gist about topic & sparks interest but I suggest that **description part of theory things when opened should be made expandable**, thus it will become more readable. Thank you very much

**Comment by hsengiviaJ** [comment]
please add a screenshot to make your point clearer. I think I understand what you mean but it would be nice to eliminate ambiguity

**Comment by mihirsar** [comment]
![roadmapsuggestion](https://github.com/kamranahmedse/developer-roadmap/assets/116589747/93a6b4df-2696-4170-8a69-6cb1e49dfd25)
Thank you for your attention to this matter. I wanted to suggest an improvement for the developer roadmap. The information panel on the right side could be made expandable, which would greatly enhance readability and user experience. I believe this change would make the roadmap even more useful for developers. Thank you for considering this suggestion.
