### ISSUE TITLE
[user experience issue]: The background scrolling doesn't get disabled when the topic detail is opened

### ISSUE THREAD

**Issue by dev-aly3n** [kamranahmedse/developer-roadmap#5169]
### Detailed Description

Hi, when we open a topic, the background remains scrollable, causing a poor user experience, especially when the content itself is scrollable.

![scroll2](https://github.com/kamranahmedse/developer-roadmap/assets/79654879/4d2771cc-2adc-4a2c-b905-6f8ec41990ed)

As you can see at the right of screen there are 2 scrollbars. one for topic content and one for body.

**Comment by kamranahmedse** [comment]
Thanks for the PR but we will look into it and see if there is an alternative fix. Closing it for now since it is not that critical.
