### ISSUE TITLE
Why C# and Java as other option and not Enterprise Development ?

### ISSUE THREAD

**Issue by unknowedNp** [kamranahmedse/developer-roadmap#517]
Why C# and Java as other option and not Enterprise Development ?

Java and C# development not like usual development and more use in huge company and entrprise applications!

**Comment by zawawimanja** [comment]
I agree with you.

**Comment by gopalroy2025** [comment]
Nonsesnse it's a critical base of most enterprise applications

**Comment by ctolkien** [comment]
>Java and C# development not like usual development

Sure they are... what is the difference here?

**Comment by fabrycyocarvalho** [comment]
View in the GitHub

**Comment by unknowedNp** [comment]
@ctolkien  
because not a script language and are real programing language !
and safer and faster because compile to machine language
andother thing is good oop language and good for manegment of enterprice app

**Comment by mohsenr7596** [comment]
> 
> 
> > Java and C# development not like usual development
> 
> Sure they are... what is the difference here?

to clear road map to develop enterprise app

**Comment by Ronkiro** [comment]
I don't think it's a bad practice to generalize as other options. Many programming sections will appear in future, we can add them in "Other options".

Also, faster is very relative here. You can also compile a Python script, with Pyinstaller, for example. You can make it as fast as Java. I d say better.

Scripting languages also are good and very used for enterprise side, and their simple syntax also make them simple to manage.

**Comment by kamranahmedse** [comment]
This was some bad wording on my part. This has been fixed in the latest update and will be published soon. Thank you 🙏
