### ISSUE TITLE
Implement Dark mode 

### ISSUE THREAD

**Issue by sam1231ui** [kamranahmedse/developer-roadmap#5171]
### Roadmap URL

https://roadmap.sh

### Suggestions

its just suggestion to implement dark mode to site as it will be helpful while study at night 
can take look  at this code site i use for dsa
[https://neetcode.io/roadmap]

**Comment by abdullahshami9** [comment]
It is difficult to use roadmap.sh without darkmode and couldn't find a way to switch on darkmode
