### ISSUE TITLE
Misplaced optimization query in Index optimizations article

### ISSUE THREAD

**Issue by abdivasiyev** [kamranahmedse/developer-roadmap#5181]
### Roadmap URL

https://roadmap.sh/sql

### Suggestions

In [this](https://github.com/kamranahmedse/developer-roadmap/blob/master/src/data/roadmaps/sql/content/110-indexes/101-query-optimization.md) content, optimized query is misplaced

**Comment by abdukhashimov** [comment]
Hi @abdivasiyev please provide your proof how these queries are misplaced

**Comment by abdivasiyev** [comment]
1. Optimized query according to article and query plan:
```sql
select *
from users
where language = 'en'
  and status in (select status from users where status = 'active');
```
![telegram-cloud-photo-size-2-5361649706050114027-y](https://github.com/kamranahmedse/developer-roadmap/assets/46614434/fa9bb205-4b42-44a9-be08-3f930774d32c)

3. Unoptimized query according to article and query plan: 
```sql
select *
from users
where language = 'en'
  and status = 'active';
```
![telegram-cloud-photo-size-2-5361649706050114029-y](https://github.com/kamranahmedse/developer-roadmap/assets/46614434/c1b46baf-4552-4970-a296-c8b2065112c3)
