### ISSUE TITLE
Add Motoko Bootcamp to DAO resources

### ISSUE THREAD

**Issue by seb-icp** [kamranahmedse/developer-roadmap#5196]
### Roadmap URL

https://roadmap.sh/blockchain

### Suggestions

Hello, 

I suggest adding the Motoko Bootcamp to the list of DAO-related resources. The Motoko Bootcamp is a open source and free 1-week bootcamp that takes students from 0 to building and deploying a DAO on the Internet Computer (ICP). 

Link: https://github.com/motoko-bootcamp/dao-adventure

**Comment by alex327** [comment]
I am brand brand new to any form of coding. I have begun the motoko initiation. I am stuck on task #5. I am very much a visual learning. Can someone show me the code I am suppose to use to complete Task#5?

**Comment by seb-icp** [comment]
@alex327 this is not the correct place to ask those questions. I suggest you join our Discord and ask there: https://discord.gg/yy8Kcnh6
