### ISSUE TITLE
Typo Vulcan should be Vulkan

### ISSUE THREAD

**Issue by qbojj** [kamranahmedse/developer-roadmap#5203]
### Detailed Description

Typo in both filename and file itself I could not do it from the github gui.

The file:
`src/data/roadmaps/game-developer/content/109-advanced-rendering/100-real-time-ray-tracing/101-vulcan-ray-tracing.md`

should be `101-vulkan-ray-tracing.md`

and the header inside also should be `Vulkan Ray Tracing`

**Comment by dansholds** [comment]
This has been fixed 🎉
