### ISSUE TITLE
add an indicator that suggests whether the link is a video/article or other than that

### ISSUE THREAD

**Issue by devhindo** [kamranahmedse/developer-roadmap#5223]
### Feature Description

beside each bullet point there should be an indicator to indicate the type of the link (video/article/etc)
![image](https://github.com/kamranahmedse/developer-roadmap/assets/66886118/1564ea6e-83ed-4c75-822c-8c533120a631)

**Comment by AkshatSharma000** [comment]
Hi @devhindo ,  Can i work on this feature??

**Comment by devhindo** [comment]
> Hi @devhindo , Can i work on this feature??

Yeah no problem
