### ISSUE TITLE
change 2018 to 2019 

### ISSUE THREAD

**Issue by mohammadanwar** [kamranahmedse/developer-roadmap#523]
Change 2018 to 2019 where it is applicable.

**Comment by kamranahmedse** [comment]
I have already been working on updating the roadmaps for 2019. Frontend roadmap has been updated and the Changelog can be found [on spectrum](https://spectrum.chat/developer-roadmap?thread=85b6e11b-85cd-4f74-845e-ae57fe1243a7). 

Stay tuned for the backend and DevOps.
