### ISSUE TITLE
Unavailable video at the link

### ISSUE THREAD

**Issue by ShevasTest** [kamranahmedse/developer-roadmap#5231]
### What is the URL where the issue is happening

https://roadmap.sh/javascript

### What browsers are you seeing the problem on?

Chrome

### Describe the Bug

Asynchronous JavaScript block - setTimeout sub-block - item setTimeout EXPLAINED in 5 minutes! not available

![Screenshot_5](https://github.com/kamranahmedse/developer-roadmap/assets/103066278/90799411-e6ce-4532-a159-5def1bd57f6f)

### Participation

- [X] I am willing to submit a pull request for this issue.

**Comment by dansholds** [comment]
This will be fixed by #5445

**Comment by dansholds** [comment]
This will be fixed by #5445
