### ISSUE TITLE
Multi select

### ISSUE THREAD

**Issue by savente93** [kamranahmedse/developer-roadmap#5283]
### Feature Description

I'm a decently experienced developer and while I'd love to go through things, having to go through multiple languages select every individual topic, go to the drop down and selecting done is very time consuming. For someone who already has experience I'd really like a way to either select multiple topics and mark them all as done, or another way of faster checking off things such as a one click solution

**Comment by kamranahmedse** [comment]
That's a nice idea. I have created an internal ticket for this and will get to it soon.
