### ISSUE TITLE
Add Flutter to the front-end mobile applications.

### ISSUE THREAD

**Issue by zhnoah** [kamranahmedse/developer-roadmap#529]
React Native [Personal Recommendation!]
NativeScript [Available Options]
Flutter [Available Options]

**Comment by dbrgn** [comment]
Flutter is its own ecosystem though, with its own programming language (Dart). I don't think it fits in a chart focussed on web technologies.

**Comment by mujz** [comment]
This is intended as a roadmap for web developers to consider, and since mobile applications are mentioned, then flutter should be mentioned as well in my humble opinion, especially since it's receiving increased attention over time.

**Comment by kamranahmedse** [comment]
This has been fixed and will be published in the coming release. Thank you 🙏
