### ISSUE TITLE
More levels of subtopics

### ISSUE THREAD

**Issue by stephenhebert** [kamranahmedse/developer-roadmap#5301]
### Feature Description

First of all, I want to express how much I love this project!  I've been following it for many years, and I recommend it to everyone.  I've always found these sorts of checklists helpful for having a sense of what I don't know and having a guide for what to learn.  Also, as someone who is passionate about education and making the world better through sharing knowledge and resources, I have spent a lot of time dreaming about projects like this.  Thank you for your work on this wonderful contribution!

I have only just discovered that roadmap.sh now has features for tracking progress, creating custom roadmaps, and even collaborating with a team.  As an engineering manager, I am always looking for ways to help my team grow, and this project is very much aligned with what I have envisioned.

Unfortunately, the system currently only supports two levels of depth -- topics and subtopics.  To be able to use this as a robust system for professional development -- eg, sharing progress regularly, incorporating in our 1v1s -- we would need at least one more level of granularity.

This would support something like this:
# Frontend Engineering
### Vue.js
 - defineModel
 
 Is there any chance this feature is planned for the future?

**Comment by kamranahmedse** [comment]
Thank you for the kind words Stephen.

I know that the component section has just two nodes for topics (topic/subtopics) but that doesn't mean you can't have more levels. For deeper levels you can simply use the subtopic under a subtopic node connected with edges:

<img width="533" alt="image" src="https://github.com/kamranahmedse/developer-roadmap/assets/4921183/7feb46a7-f4c8-45f6-8384-f0b1ca02fa4f">

or use the section component that can have one parent topic and a set of subtopic nodes (might not be clear from the picture below but something along these lines).

<img width="904" alt="image" src="https://github.com/kamranahmedse/developer-roadmap/assets/4921183/890a6aab-388c-48df-9365-f5d697426ba4">

**Comment by mosancom** [comment]
This is really a good news.
