### ISSUE TITLE
What Do Software Testers Do? - Invalid link

### ISSUE THREAD

**Issue by cabrerakma** [kamranahmedse/developer-roadmap#5304]
### Roadmap URL

https://roadmap.sh/qa

### Suggestions

**https://www.ministryoftesting.com/dojo/lessons/what-do-software-testers-do-version-0-1** is no longer a valid link. 
100-what-is-qa.md

**Comment by kamranahmedse** [comment]
Thank you for reporting this. Feel free to submit a PR.
