### ISSUE TITLE
Adding A New video link Of DSA  On Data structure

### ISSUE THREAD

**Issue by COCOCHARON** [kamranahmedse/developer-roadmap#5312]
### Roadmap URL

https://roadmap.sh/java

### Suggestions

I Am Learning Java And i found that You have Mentioned Data Structures But It's not I depth and Not in Concept wise. **So Add A Video link Of DSA** _Please add this_[https://youtu.be/2ZLl8GAk1X4?si=Ya4xDM2Y8J_nV2_f](url) This Video is Launched by **Freecodecamp.org**

**Comment by kamranahmedse** [comment]
Feel free to open a PR for this.
