### ISSUE TITLE
Buffalo Framework discontinued

### ISSUE THREAD

**Issue by TheConnorJohnson** [kamranahmedse/developer-roadmap#5318]
### Roadmap URL

https://roadmap.sh/golang

### Suggestions

Unfortunately, it looks like the Buffalo framework has been archived on Github as of February 24, 2024. I wanted to suggest adding or updating to the [Flamingo framework](https://github.com/i-love-flamingo/flamingo). It is actively being maintained and seems to be going strong.

**Comment by kamranahmedse** [comment]
This has been fixed and will be published in the coming release. Thank you 🙏
