### ISSUE TITLE
Use drop/down instead of click to show the answer

### ISSUE THREAD

**Issue by M-AminAlizadeh** [kamranahmedse/developer-roadmap#5333]
### Roadmap URL

https://roadmap.sh/get-started

### Suggestions

Hey there
I realized in the `Tips for Beginners` part the user must click on each tip to see the suggestion this isn't a good approach especially for UX because when the user clicks on it the question disappears and they can't see the tip again the user doesn't have another choice than reload the page.

![Screenshot from 2024-03-12 14-21-30](https://github.com/kamranahmedse/developer-roadmap/assets/67329484/abc6277d-ae44-4b29-8ba2-edd7e351a2c1)

My suggestion is to try to use a drop-down or at least make these tips toggle between the question and answer on each click event.

**Comment by kamranahmedse** [comment]
This is intentional. Tip is part of the expanded item so you don't need to read the title again.
