### ISSUE TITLE
Multiple legend on custom roadmaps

### ISSUE THREAD

**Issue by llermaly** [kamranahmedse/developer-roadmap#5346]
### Feature Description

Hi, thanks for this awesome tool.

I'm trying to create my own roadmap. Forking from the Frontend roadmap I noted two things: 

1. Legend is not forked
2. I can't find the way to change the icon position, or to set multiple legends to a node like this 

<img width="185" alt="image" src="https://github.com/kamranahmedse/developer-roadmap/assets/8575569/a8701b5d-15c6-4376-9d96-7eed3073ea89">

Is this something achievable? 

Thanks!

**Comment by kamranahmedse** [comment]
Not at the moment, but we are working on revamping some parts of the editor, I will see if we can add that.
