### ISSUE TITLE
Stylus as a CSS pre-procesor and also HTML pre-processors

### ISSUE THREAD

**Issue by sturay** [kamranahmedse/developer-roadmap#536]
[Stylus.js](https://github.com/stylus/stylus/) is JS only, no RubyGem required as SASS does, it can also be interchanged with SASS for some things (but not really the other way around). If you're including PostCSS, you should also include Stylus.

HTML pre-processors are also great tools. [HAML](http://haml.info/) and [Pug](https://github.com/pugjs/pug) (formerly Jade) are both good for semantic markup and tag completion, although Pug has a simpler markup system.

**Comment by shirohana** [comment]
Bumped, I love Stylus <3 <3 <3

**Comment by kamranahmedse** [comment]
Thank you for reporting but [as per the contribution docs](https://github.com/kamranahmedse/developer-roadmap/blob/master/contributing.md#guidelines) this won't be added
