### ISSUE TITLE
Comments on roadmaps

### ISSUE THREAD

**Issue by ahmedjameel1** [kamranahmedse/developer-roadmap#5361]
### Feature Description

why don't the developers allow comments on the roadmaps and Q&A to help people figure out what to take and leave from the comprehensive roadmaps such as backend developer which has another roadmap for databases, DevOps, and another for software design and architecture me my self I am confused do really have to finish all those roadmaps to become a backend developer?

**Comment by dansholds** [comment]
Hi!
This is not something that we are currently planning on implementing, but that doesn't mean we never will!

The best place for discussion of Roadmaps (and the main reason why it was created) is our Discord server!

https://discord.gg/jFkwUQQf
