### ISSUE TITLE
DevOps - sh not visible.

### ISSUE THREAD

**Issue by wouerner** [kamranahmedse/developer-roadmap#5366]
### Roadmap URL

https://roadmap.sh/devops

### Suggestions

Hi,

In the section "Learn a Language," it is not explicitly mentioned that learning shell scripting (sh, zsh, bash / PowerShell) is necessary. In my opinion, this is the most sought-after skill in DevOps, surpassing JavaScript/Node.js.

This is important because beginners may overlook this crucial aspect in the roadmap.

**Comment by kamranahmedse** [comment]
We _do_ have that in the "Learn to live in Terminal" section

<img width="733" alt="image" src="https://github.com/kamranahmedse/developer-roadmap/assets/4921183/bb6e60dc-6d79-43c6-921a-854123f7e3bf">
