### ISSUE TITLE
Why is the box with LESS in it grey?

### ISSUE THREAD

**Issue by Oxymoron290** [kamranahmedse/developer-roadmap#538]
There is no legend indicating what grey identifies and it appears to be the only grey box.

**Comment by hawezo** [comment]
> I won't go for it if I was starting in 2019.

According to its attached description, I think it's the color for not-recommended things. Definetly some missing legend though.

**Comment by Oxymoron290** [comment]
Looking at historical roadmaps from 2017 and 2018, the legend includes a grey box in the legend for not-recommended.

**Comment by kamranahmedse** [comment]
This has been fixed and will be published in the coming release. Thank you 🙏
