### ISSUE TITLE
Add a Feature to favorite/Like road maps

### ISSUE THREAD

**Issue by jsaint73** [kamranahmedse/developer-roadmap#5382]
### Feature Description

I'd like to see a feature to add multiple road maps to a list so we can keep track of them

**Comment by dansholds** [comment]
Hi!

This feature already exists 😄 

When on a Roadmap, you will see a save/favourate icon next to the title, clicking this will add it to your favourates which appear at the top of the home page 😄 

<img width="831" alt="favourates" src="https://github.com/kamranahmedse/developer-roadmap/assets/25537601/be3307e3-c335-47af-8bc8-0d7734069b81">
<img width="623" alt="save" src="https://github.com/kamranahmedse/developer-roadmap/assets/25537601/44362ff8-efd2-4488-ae34-6701de98df58">
