### ISSUE TITLE
Anti-Virus Warning after Download a pdf from Roadmap.sh

### ISSUE THREAD

**Issue by Elektrickser** [kamranahmedse/developer-roadmap#5389]
### What is the URL where the issue is happening

https://roadmap.sh/cyber-security

### What browsers are you seeing the problem on?

Firefox

### Describe the Bug

when i Download the pdf from the Site Cybersecurity i become a Warning from my Antivirus 

![grafik](https://github.com/kamranahmedse/developer-roadmap/assets/37211274/fa9be0ab-2db3-4e8b-b970-585c6f85ee97)

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by dansholds** [comment]
@Elektrickser I have ran the PDF through a couple of scanners and it has come up clean.

It looks like the warning is telling you that PDFs downloaded from the internet **could** be dangerous, but please be assured that ours are not!
