### ISSUE TITLE
Missing Ionic for mobile path

### ISSUE THREAD

**Issue by mlynch** [kamranahmedse/developer-roadmap#539]
Ionic is widely used in the frontend world for mobile (and cross-platform) and should be on the mobile roadmap list. Happy to help make it happen

**Comment by erickvieira** [comment]
Specially if we are talking about [Ionic 4](https://ionicframework.com/blog/introducing-ionic-4-ionic-for-everyone/) and the hability to build [PWAs](https://ionicthemes.com/tutorials/about/the-complete-guide-to-progressive-web-apps-with-ionic4).

![](https://i.udemycdn.com/course/750x422/1836270_d74a_2.jpg)

**Comment by kamranahmedse** [comment]
This has been fixed and will be published in the coming release. Thank you 🙏
