### ISSUE TITLE
Enhancement Request: Include Standalone Components in Roadmap.sh Angular

### ISSUE THREAD

**Issue by davidor23** [kamranahmedse/developer-roadmap#5391]
### Roadmap URL

https://roadmap.sh/angular

### Suggestions

I propose the inclusion of standalone components as a distinct section within the Angular roadmap on Roadmap.sh. This addition would offer users a dedicated path to mastering the creation, usage, and best practices associated with standalone components in Angular applications.

**Growing Popularity**: Standalone components are becoming increasingly popular in Angular development due to their reusability, maintainability, and ease of integration.
**Clear Guidance**: Providing a dedicated section for standalone components would offer clear guidance for developers seeking to deepen their understanding and proficiency in this specific area.
**Community Demand**: Numerous discussions and queries within the Angular community highlight the need for more comprehensive resources and guidance on standalone components.

**Comment by kamranahmedse** [comment]
This has been fixed and will be published in the coming release. Thank you 🙏
