### ISSUE TITLE
Improve key features info

### ISSUE THREAD

**Issue by morenonicolelli** [kamranahmedse/developer-roadmap#5396]
### Roadmap URL

https://roadmap.sh/golang

### Suggestions

More emphasis on key feature:

- more focus on concurrency part, it's a key feature and in this status it seems like something not too important
- more focus on interfaces and all the world around it
- generics

Thanks for your attention

**Comment by kamranahmedse** [comment]
Interfaces, generics and goroutines are all there. However, I agree we need to restructure some parts of it -- we will do that soon. Thank you!
