### ISSUE TITLE
System Design - PDF link update for "Performance vs Scalability"

### ISSUE THREAD

**Issue by prasanth1712** [kamranahmedse/developer-roadmap#5397]
### Roadmap URL

https://roadmap.sh/system-design

### Suggestions

Change the link for Scalability, Availability & Stability Patterns (https://www.slideshare.net/jboner/scalability-availability-stability-patterns/) to "https://tehlug.org/events/presentations/183/scalability_patterns.pdf" as it will reduce the adds and readability issues from earlier link
<img width="1791" alt="Screenshot 2024-03-24 at 9 59 56 AM" src="https://github.com/kamranahmedse/developer-roadmap/assets/39219776/164a0f43-9df3-4611-9a8d-82819d0f489f">

**Comment by dansholds** [comment]
Please submit this as a PR rather than a suggestion, thanks! 🎉
