### ISSUE TITLE
Removed article

### ISSUE THREAD

**Issue by muhammadmp97** [kamranahmedse/developer-roadmap#5400]
### What is the URL where the issue is happening

https://roadmap.sh/backend

### What browsers are you seeing the problem on?

Chrome

### Describe the Bug

I'm not sure if here's the right place to make this issue.

This URL has been removed and is not accessible anymore:
https://aws.amazon.com/architecture/well-architected/serverless/patterns/load-shifting/
In here:
https://github.com/kamranahmedse/developer-roadmap/tree/master/src/data/roadmaps/backend/content/123-scalability/100-mitigation-strategies/103-loadshifting.md

I couldn't even find the archived version, so my suggestion is to remove or replace it.

Thanks.

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by dansholds** [comment]
Thanks for raising, I have submitted a PR which will be approved and merged later today.

In future I would suggest submitting your own PR rather than an issue as this benefits everyone involved!

**Comment by muhammadmp97** [comment]
> Thanks for raising, I have submitted a PR which will be approved and merged later today.
> 
> In future I would suggest submitting your own PR rather than an issue as this benefits everyone involved!

You're welcome.
I wasn't familiar with the project, so I preferred to submit an issue.
