### ISSUE TITLE
automate status update in the roadmap

### ISSUE THREAD

**Issue by asmyio** [kamranahmedse/developer-roadmap#5402]
### Feature Description

In the roadmap:

1) Make the main topic change to in progress when only one of a subtopic is in progress or completed.
2) Make the main topic change to done when all of the subtopic is completed
3) Change all of the subtopic to done when one of the main topic is completed

For all those 3, an alert pop up will show to confirm the automated action along with a checkbox button that asks if it shouldn't be asked again.

Cheers!

**Comment by kamranahmedse** [comment]
This would be a bit challenging to implement with the current roadmap setup. However, we are working on something which would make it easier to implement this. Closing it for now and we will revisit this later.
