### ISSUE TITLE
refine webframeworks

### ISSUE THREAD

**Issue by hamedsh** [kamranahmedse/developer-roadmap#5404]
### Roadmap URL

https://roadmap.sh/python

### Suggestions

both recently released Django (Django 4.2 and Django 5.x) also Flask (3.x) are supporBoth Django (versions 4.2 and 5.x) and Flask (version 3.x) now support async programming and can be used alongside FastAPI in the roadmap.

**Comment by kamranahmedse** [comment]
This has been fixed and will be published in the coming release. Thank you 🙏
