### ISSUE TITLE
Roadmaps don't work on Mullvad Browser (Linux) or Tor Browser (Android)

### ISSUE THREAD

**Issue by ruvilonix** [kamranahmedse/developer-roadmap#5405]
### What is the URL where the issue is happening

https://roadmap.sh/ai-data-scientist

### What browsers are you seeing the problem on?

Other

### Describe the Bug

![Screenshot from 2024-03-24 15-43-47](https://github.com/kamranahmedse/developer-roadmap/assets/114708614/4aaf0b74-4e7b-4507-a462-34dcd4ec5abc)

As you can see in the screenshot of Mullvad Browser on Ubuntu, there is no text shown for any of the roadmap items. Same thing occurs in Tor Browser for Android. 

I would assume it is related to the console error shown below.

Is it possible to display the roadmaps in a way that works on browsers with fingerprinting preventions?

### Output from browser console (if any)

`Blocked https://roadmap.sh/ai-data-scientist from extracting canvas data because no user input was detected.`

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by kamranahmedse** [comment]
Thank you for reporting this but I am not sure we can do anything about this. Can you try a different browser maybe?
