### ISSUE TITLE
Invalid link in Java Developer roadmap

### ISSUE THREAD

**Issue by phdangg** [kamranahmedse/developer-roadmap#5408]
### What is the URL where the issue is happening

https://roadmap.sh/java

### What browsers are you seeing the problem on?

Chrome

### Describe the Bug

The YouTube link of Garbage Collection - Geekific in Java roadmap is not working.

Replacing [original link](https://www.youtube.com/watch?v=xxoacv5xm9s) with [uppercase link](https://www.youtube.com/watch?v=XXOaCV5xm9s)

Position: Getting Deeper, Garbage Collection, Garbage Collection in Java - Geekific

### Participation

- [X] I am willing to submit a pull request for this issue.

**Comment by RiteshBorse** [comment]
I am willing to submit a pull request for this issue.

**Comment by deepakmardii** [comment]
Fix : Invalid link in Java Developer roadmap #5425 

PR: [link](https://github.com/kamranahmedse/developer-roadmap/pull/5425)

**Comment by dansholds** [comment]
Closing due to fix PR merged, thanks @belikedeep 💯
