### ISSUE TITLE
Java roadmap suggestion to add MOOC course from University of Helsinki

### ISSUE THREAD

**Issue by maxiwer** [kamranahmedse/developer-roadmap#5410]
### Roadmap URL

https://roadmap.sh/java

### Suggestions

I extremely recommend "Java Programming I" and "Java Programming II" courses provided like [MOOC from University of Helsinki](https://java-programming.mooc.fi/). It's totally in English and allow students to work on IDEs with provided tests. Also the course has well-written theory alongside with some quizzes on the theory.

**PS** Also, I'd suggest to unify this recommended books section somewhere else.
![image](https://github.com/kamranahmedse/developer-roadmap/assets/29051133/aeded651-752f-4fc0-ba60-ae8bf79d907a)

**Comment by dansholds** [comment]
Hey!

Please submit suggestions for content additions and changes as a PR for review, thanks! 🙏
