### ISSUE TITLE
Deep Copy vs Shallow Copy

### ISSUE THREAD

**Issue by aisha-n1** [kamranahmedse/developer-roadmap#5411]
### Roadmap URL

https://roadmap.sh/javascript

### Suggestions

This article explains the concepts of deep copy and shallow copy in Javascript really well and I think others will benefit from it.

[https://dev.to/fpaghar/copy-objects-ways-in-javascript-24gj?ref=dailydev](Copy Objects Ways in JavaScript)

**Comment by dansholds** [comment]
If you have content that you would like to add to a roadmap please open a PR rather than a suggestion 😄
