### ISSUE TITLE
AI and Data Science : require 2 different road maps 

### ISSUE THREAD

**Issue by samarthsaxena** [kamranahmedse/developer-roadmap#5427]
### Roadmap URL

https://roadmap.sh/ai-data-scientist

### Suggestions

Please make a different road map for these 2 fields of studies: 1. AI&ML and 2. Data Science
In AI and ML : Concentrate of the AI and its fields of study related to maths, statistical analysis, artificial and computational intelligence, Machine Learning, Deep Neural Networks, ML Systems and MLOps, Design of Algo, AI in Robotics etc...
In Data Science: Suggest the data science-specific field of study. e.g. Maths for Data Science, Computer Organization and Sytem Software, Intro to Stats, Data Structures and Algo, Bug Data Systems, Data Warehousing, Graphs, deep learning, Data Management for ML, NLP, Stream processing and analytics, Data Visualization and analysis.

Now there is a small difference in both of the fields but it makes specialized road maps for each individual streams.
To support this claim we can see that there are specific degrees and certifications for AI-ML and DataScience.

**Comment by kamranahmedse** [comment]
It is planned -- we will have more focused roadmaps on several different AI topics in future.
