### ISSUE TITLE
Update command for Remove a Docker Image

### ISSUE THREAD

**Issue by SanchithaUdana** [kamranahmedse/developer-roadmap#5450]
### Roadmap URL

https://roadmap.sh/docker

### Suggestions

`docker image rm <image>` and `docker rmi <image>` both commands can remove an image.

<img width="565" alt="Screenshot 2024-04-02 at 3 27 15 PM" src="https://github.com/kamranahmedse/developer-roadmap/assets/109952575/176036fe-f161-4b4f-be29-cda4680cb765">

**Comment by kamranahmedse** [comment]
Feel free to open a PR for this
