### ISSUE TITLE
PHP

### ISSUE THREAD

**Issue by sam-cruzz** [kamranahmedse/developer-roadmap#5456]
### Roadmap URL

https://roadmap.sh/full-stack

### Suggestions

Php should be there for synchronous as a beginner needs to know the line-by-line code snippet.

**Comment by iskandarovshaxzod** [comment]
It would be great if someone experienced could make roadmap for PHP from beginning to becoming backend developer.

**Comment by XAGASKII101** [comment]
How can I use suhail mial

**Comment by kamranahmedse** [comment]
Full stack roadmap is opinionated and recommends Node.js because it starts with frontend which already has JavaScript.
