### ISSUE TITLE
GitHub please let me unsubscribe from this, I have tried so many times but still end up getting mails.. please for god sake forgive me and unsubscribe from this thread alone...

### ISSUE THREAD

**Issue by caojiele** [kamranahmedse/developer-roadmap#547]
GitHub please let me unsubscribe from this, I have tried so many times but still end up getting mails.. please for god sake forgive me and unsubscribe from this thread alone...

_Originally posted by @waheedsid in https://github.com/kamranahmedse/developer-roadmap/issues/542#issuecomment-453910874_

**Comment by danilomo** [comment]
Hahahaha, same here

**Comment by kamranahmedse** [comment]
@caojiele @danilomo click the "Unwatch" button to stop receiving notifications

![image](https://user-images.githubusercontent.com/4921183/51305277-d59db100-1a53-11e9-9cca-2aeb64e724e7.png)

**Comment by fuzion1029** [comment]
same here. Tried unsubscribing to this thread and still keep getting
messaged.
Please remove me from the list.
Thanks,

**Comment by caojiele** [comment]
same here.
