### ISSUE TITLE
missing framework for backend

### ISSUE THREAD

**Issue by karishmak8** [kamranahmedse/developer-roadmap#5470]
### Feature Description

Suggest a framework for backend as it would be waste of resources and time if we follow traditional language to build an application. 
ex.  springboot, express.js, django

**Comment by rohitLovesKrishna** [comment]
Just go for Next Js. It is all in one package . One room for everything. You will not going to feel that there is something like databases, servers ,clients. Cuz they are there.

**Comment by kamranahmedse** [comment]
Backend framework is language/framework agnostic and so we don't have any recommendations here. Have a look at other more specific roadmaps for such details.
