### ISSUE TITLE
Include Prometheus in "Application Monitoring"

### ISSUE THREAD

**Issue by SuperQ** [kamranahmedse/developer-roadmap#5477]
### Roadmap URL

https://roadmap.sh/devops

### Suggestions

While it's widely used for infrastructure monitoring, Prometheus was originally created for application monitoring. It is widely used for this task.

**Comment by kamranahmedse** [comment]
Fixed in https://github.com/kamranahmedse/developer-roadmap/commit/310214848524668d362f5abfcd994d51c7f752b8
