### ISSUE TITLE
Addition of Relevant Topics 

### ISSUE THREAD

**Issue by harsh007-tech** [kamranahmedse/developer-roadmap#5481]
### Roadmap URL

https://roadmap.sh/ai-data-scientist

### Suggestions

Here If the details are also added like what sub-topics to learn instead of just giving the course era link, it would be helpful.

As people who cannot access the course can read these topics on their own or other resources.

<img width="864" alt="image" src="https://github.com/kamranahmedse/developer-roadmap/assets/60573006/4f607a64-9ce0-4e92-b7af-06b78aab4a6c">

**Comment by kamranahmedse** [comment]
AI and Data Scientist roadmap is more course oriented, we do have plans to add separate topic oriented roadmaps in the future.
