### ISSUE TITLE
Changes to MLOps roadmap

### ISSUE THREAD

**Issue by iameminmammadov** [kamranahmedse/developer-roadmap#5499]
### Roadmap URL

https://roadmap.sh/mlops

### Suggestions

Here are the changes I am suggesting:

# Programming Fundamentals

Add `GoLang` as `Optional`. MLOps engineers might have to work on infrastructure side and directly interact with K8s. Will need knowledge of `Go` to be able to do that.

# Data Engineering Fundamentals

Add `Airflow` to `Data Pipelines` or make it as a separate entity. In `Data Pipelines` description add `It is important to understand the difference betweent ELT and ETL pipelines`. Make `Spark` and `Kafka` as separate entities; they are not very related. Add `Flink` as `Optional`. 

Add `Data Ingestion Architectures (Lambda vs. Kappa)`

# Infrastructure as a Code (IaaC)

Add `Terraform` and `Ansible` as separate entities. `Ansible` can be optional. Will add the description for `TerraForm` with some resources in the next PR.

**Comment by iameminmammadov** [comment]
Hey @kamranahmedse ,

Do you know how can I get someone to review this suggestion? Thanks.

**Comment by dansholds** [comment]
Rather than suggesting content additions or changes in an `issue` please submit them as a PR for review, thanks!

**Comment by kamranahmedse** [comment]
@dansholds these were actually some valid suggestions to the roadmap (not content).

@iameminmammadov I have made the changes to the roadmap. Let me know if you have any feedback.
