### ISSUE TITLE
Put 'start building' at the top!

### ISSUE THREAD

**Issue by chrisweight** [kamranahmedse/developer-roadmap#55]
nice one, but the best way to become a developer is to start by building stuff, even if it's rubbish. If you put 'start building' at the end of all your maps, people may never even lay down a line of code :)

**Comment by AffanIndo** [comment]
I agree with this. The "Start building" is too low. I think it should point out the necessary basic, then start building, below that is the more advanced topic, like jquery, es6, etc.

**Comment by luislobo** [comment]
I think it should not even be in the graph ;)

**Comment by tehciolo** [comment]
@luislobo That would be the best option. Just state at the beginning that you should be building along the way, at all times.

**Comment by damengilland** [comment]
Fixed it!

![68747470733a2f2f692e696d6775722e636f6d2f3576465457634f2e706e67](https://cloud.githubusercontent.com/assets/1106778/25299954/fe140798-26ca-11e7-9fa0-c82f530c5564.png)

**Comment by luchillo17** [comment]
The same for the `Back-end` and `Dev-ops`, moving the `start building` to the top, or removing it altogether should be considered.

**Comment by kamranahmedse** [comment]
There have been changes made to that section which makes this issue outdated. Thank you for reporting though 🙏
