### ISSUE TITLE
Prometheus as monitoring platform

### ISSUE THREAD

**Issue by Cougar** [kamranahmedse/developer-roadmap#550]
[Prometheus](https://prometheus.io/) with [alertmanager](https://prometheus.io/docs/alerting/alertmanager/) and all different [exporters](https://prometheus.io/docs/instrumenting/exporters/) is widely used monitoring.

Also [Grafana](https://grafana.com/) which is often used together with Prometheus but supports many different [data sources](https://grafana.com/plugins?type=datasource) has a lot of users from devops community.

**Comment by chshbh** [comment]
I would also like to add [influx-db platform](https://www.influxdata.com/time-series-platform/) as a coupled stack for monitoring and statuspage.

**Comment by snimmagadda1** [comment]
+1 I would also argue that step 8 of the DevOps roadmap could be updated to include more modern monitoring capabilities including (but not limited to) Dynatrace, DataDog, etc or perhaps even cloud specific capabilities like Azure Application Insights...

**Comment by woodpenker** [comment]
PromQL is also important to learn when using Prometheus.

**Comment by kamranahmedse** [comment]
This has been fixed and will be published in the coming release. Thank you 🙏
