### ISSUE TITLE
Change the difficulty level!

### ISSUE THREAD

**Issue by Kishore007raj** [kamranahmedse/developer-roadmap#5500]
### Roadmap URL

https://roadmap.sh/javascript

### Suggestions

Please change the difficulty level for debugging issues from intermediate to advanced level because those things are too complicated and need more  knowledge to learn

**Comment by kamranahmedse** [comment]
Beginner / Intermediate / Advanced are not labeled based on how easy or difficult a topic is. It refers more to how you should proceed with learning these topics.
