### ISSUE TITLE
The download file is not updated

### ISSUE THREAD

**Issue by mahdi-khoshkhabar** [kamranahmedse/developer-roadmap#5502]
### What is the URL where the issue is happening

https://roadmap.sh/flutter

### What browsers are you seeing the problem on?

Chrome, Other

### Describe the Bug

The download file of the road map for Flutter is different from the file available on the website and needs to be updated.

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by dansholds** [comment]
Duplicate of https://github.com/kamranahmedse/developer-roadmap/issues/4358
