### ISSUE TITLE
Non-English content in Kubernetes Roadmap

### ISSUE THREAD

**Issue by skoenig** [kamranahmedse/developer-roadmap#5524]
### What is the URL where the issue is happening

https://roadmap.sh/kubernetes

### Describe the Bug

There is non-English content linked in the Kubernetes roadmap in the [horizontal pod autoscaler](https://github.com/kamranahmedse/developer-roadmap/blob/b2adb619f048190f52af48e00eece46de72f1979/src/data/roadmaps/kubernetes/content/109-autoscaling/100-horizontal-pod-autoscaler.md) section: https://www.youtube.com/watch?v=hm3jnETOoFo
This content is not accessible to many people and is also not in line with the [contribution guidelines](https://github.com/kamranahmedse/developer-roadmap/blob/b2adb619f048190f52af48e00eece46de72f1979/contributing.md#adding-content).

### Participation

- [X] I am willing to submit a pull request for this issue.

**Comment by dansholds** [comment]
@skoenig Thanks for submitting this issue (I'll be more diligent to make sure none-English content doesn't slip through!), I've tackled the issue myself but remember in future that you can submit your own PR to resolve this!

Thanks again!
