### ISSUE TITLE
video about CSI in Kubernetes not available anymore

### ISSUE THREAD

**Issue by skoenig** [kamranahmedse/developer-roadmap#5525]
### Roadmap URL

https://roadmap.sh/kubernetes

### Suggestions

The Youtube video https://www.youtube.com/watch?v=brXPQ1Qwjl4 shows 'This video isn't available anymore' (at least from Germany), so link should be removed / replaced.

**Comment by kamranahmedse** [comment]
Thank you for reporting this. Feel free to submit a PR.
