### ISSUE TITLE
Caching or local storage 

### ISSUE THREAD

**Issue by king-mohitrajsinh** [kamranahmedse/developer-roadmap#5531]
### Roadmap URL

https://roadmap.sh/javascript

### Suggestions

it should contains the cachelocal storage thing, so it could help to make the repetative website load faster! thank you for your service!

**Comment by kamranahmedse** [comment]
JavaScript roadmap covers the language (i.e. what's covered in the ECMASpec) and that's why we don't have things like DOM and Browser APIs.
