### ISSUE TITLE
CyberSecurity Expert: add Portswigger Academy

### ISSUE THREAD

**Issue by Roboyaroslava** [kamranahmedse/developer-roadmap#5532]
### Roadmap URL

https://roadmap.sh/cyber-security

### Suggestions

Hey! Please add WebCyberSecurity Academy PortSwigger, because it's free enteractive ctfs site with many basic exercises https://portswigger.net/web-security

**Comment by kamranahmedse** [comment]
Feel free to open a PR. Thank you!
