### ISSUE TITLE
Possible Misspelling

### ISSUE THREAD

**Issue by bpan2** [kamranahmedse/developer-roadmap#5533]
### What is the URL where the issue is happening

https://roadmap.sh/software-architect

### What browsers are you seeing the problem on?

Firefox

### Describe the Bug

I think the term "SAP EPR" should be "SAP ERP" unless the term "EPR" doesn't stand for Enterprise Resources Planning (ERP).   

<img width="1152" alt="erp-error" src="https://github.com/kamranahmedse/developer-roadmap/assets/5376006/58f071de-2b62-4e39-a8c4-b358d47255f8">

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by pilladipesh33** [comment]
If the issue still open I'll push the pr
