### ISSUE TITLE
Add personal anecdotes helpful for newbies to gain experience related knowledge as they go

### ISSUE THREAD

**Issue by rafeysayeed** [kamranahmedse/developer-roadmap#5536]
### Feature Description

Can I be possible for people to add their personal anecdotes throughout the roadmap stages so that they can experience related knowledge throughout the journey of following through the roadmap. It would really help to learn from senior more experienced people. These anecdotes can be the form of comments throughout the roadmap stages.

**Comment by dansholds** [comment]
Hi!

We are currently not planning on implementing a comment or forum style feature to the site but I have two points on this;

1. The beginner specific roadmaps are tailored more for beginners and come with extra details such as how to create a GH profile etc
2. Our Discord server was created with the intention of just this, a place where the community can collaborate and learn together!

https://roadmap.sh/frontend?r=frontend-beginner
