### ISSUE TITLE
Hugo in the Static Sites Generators

### ISSUE THREAD

**Issue by jamezrin** [kamranahmedse/developer-roadmap#555]
Hugo is a good choice, I hoped it would be there

**Comment by tuengominh** [comment]
I think Jekyll is also a good one!

**Comment by thiagomgd** [comment]
Hugo is awesome! Used it for a while and had a great experience. Also, it's in constant development

**Comment by Midacts** [comment]
Hugo is what our team is looking at switching to from gitbook.

**Comment by amejiarosario** [comment]
@Midacts does Hugo generate PDF and ePub formats? Gitbook and Hugo seems to have different use cases: ebooks vs static sites

**Comment by Midacts** [comment]
I didn't find anything about Hugo being able to generate PDFs or ePubs.

We use gitbook as a static site generator today. Gitbook has moved away from their cli which is why I've looked into Hugo.

**Comment by kamranahmedse** [comment]
This has been fixed and will be published in the coming release. Thank you 🙏
