### ISSUE TITLE
Add a new package

### ISSUE THREAD

**Issue by Debasis08** [kamranahmedse/developer-roadmap#5555]
### Roadmap URL

https://roadmap.sh/frontend

### Suggestions

in "package managers", actually I was suggesting to add a new item named "bun", which is actually a javascript run time package manager.

Link:- https://bun.sh/

**Comment by kamranahmedse** [comment]
Thank you for opening the issue. We don't want to convolute the roadmap by mentioning every available option out there. While bun is slowly picking up steam, we won't be adding it just yet. 

This has also been [mentioned in the contribution docs](https://github.com/kamranahmedse/developer-roadmap/blob/master/CONTRIBUTING.md#guidelines). 
Thank you for your suggestion though 🙏

**Comment by Debasis08** [comment]
Yeah that’s true actually.

Even I thought the same thing after opening the issue. It might confuse the
freshers entering into the tech field.

Thank you for sharing your thoughts with me.
