### ISSUE TITLE
Non information display on Crhome Version 124.0.6367.62

### ISSUE THREAD

**Issue by alfredosandoval-eng** [kamranahmedse/developer-roadmap#5558]
### What is the URL where the issue is happening

https://roadmap.sh/

### What browsers are you seeing the problem on?

Chrome

### Describe the Bug

Non information display on Crhome Version 124.0.6367.62, to make any change for the profile
![Screenshot 2024-04-25 at 11 15 20 AM](https://github.com/kamranahmedse/developer-roadmap/assets/160087667/824dd7a9-f0ad-496c-a4be-bcd90249421a)

### Output from browser console (if any)

non
![Screenshot 2024-04-25 at 11 15 20 AM](https://github.com/kamranahmedse/developer-roadmap/assets/160087667/74dc4e3f-1e5e-48d0-83a8-f2ed82204ee1)

### Participation

- [X] I am willing to submit a pull request for this issue.

**Comment by dansholds** [comment]
I cannot replicate this issue on the **latest** verion of Chrome (124.0.6367.156), can you update your Chrome version and try?
