### ISSUE TITLE
hide unwanted paths

### ISSUE THREAD

**Issue by cherrydub** [kamranahmedse/developer-roadmap#5562]
### Feature Description

Can there be an option where we can choose to hide something, for example im doing the react roadmap and i dont want to see certain state management for example, such as Redux etc, I like the skip/done/ etc options but when you dont go on the site in a while it just gets a bit confusing and a bit too much...thanks!

**Comment by kamranahmedse** [comment]
We are working on something that would make it easier to implement this. In its current setup, doing it would just result in scattered topics making it even difficult to identify the connections and learn. Closing it for now and we will think about it once we launch the v2 or official roadmaps (in the near future).
