### ISSUE TITLE
Link leads nowhere

### ISSUE THREAD

**Issue by emmariescurrena** [kamranahmedse/developer-roadmap#5593]
### What is the URL where the issue is happening

https://roadmap.sh/blockchain

### What browsers are you seeing the problem on?

Firefox

### Describe the Bug

Page never loads

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by kamranahmedse** [comment]
I am not able to reproduce this. Could you please share your browser and OS information?

**Comment by emmariescurrena** [comment]
Browser: Mozilla Firefox 124.0.2 (64-bit) snap for ubuntu
OS: Ubuntu 6.5.0-28-generic
