### ISSUE TITLE
Time which takes to finish the roadmap

### ISSUE THREAD

**Issue by BPavanVenkataSai** [kamranahmedse/developer-roadmap#5595]
### Feature Description

If it is possible, please add a feature where how many days or months minimum it takes to finish a roadmap and add this feature to every roadmap. We can also mention time to finish a roadmap based on desperation level and mention how many hours need to allotted to finish the given roadmap in certain months.

For example, if there is a frontend developer roadmap,
Desperation level
Low - 1-2 hr per day upto for example 4 months
Medium - 2-3 hr per day upto 3 months
High - 3-4 hr per day upto 2 months
Extreme -  5-6 hr per day upto 3 to 4 weeks

Thank you for listening

**Comment by kamranahmedse** [comment]
Everyone learns differently at their on pace; factors such as your existing knowledge and skills, learning style, and available time can all affect the speed at which you progress through the materials. Putting the time will just put extra pressure on the people following it.
