### ISSUE TITLE
[RoadCard] Name cropped

### ISSUE THREAD

**Issue by wesleycoder** [kamranahmedse/developer-roadmap#5599]
### What is the URL where the issue is happening

https://api.roadmap.sh/v1-badge/tall/652b5c75f43a58c923ce56b8

### What browsers are you seeing the problem on?

Chrome, Safari

### Describe the Bug

My name is missing an 's' at the end, which is being cropped on the RoadCard in the `tall` mode.
![api roadmap sh_v1-badge_tall_652b5c75f43a58c923ce56b8_variant=dark](https://github.com/kamranahmedse/developer-roadmap/assets/22945955/78c44003-1fe9-43dc-af71-319ce41e35a7)

There's clearly enough space to show it, but it got cropped.

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by wesleycoder** [comment]
I looked through the codebase trying to find where the svg is generated in order to try and help but I couldn't find where is defined the handler for the `/v1-badge/` api endpoint.
If anyone could point me towards where is this I could try and submit a PR, I assume that this should be an easy fix.

**Comment by arikchakma** [comment]
It's intentional btw, otherwise, it breaks the road card. What I can do is add `...` maybe at the end if there are more words or you can use the `wide` variant.

**Comment by wesleycoder** [comment]
I can undestand that it might break the card, but I genuinely thought that there would be a way to fix this since there is visible space do display more characters, I don't know how the limit is being calculated but I imagine that we could find a more dynamic way to calculate it while using the whole available space.

As I don't know how it's being generated I figured I'd give a shot here.

Also out of my curiosity, is there any reason as to why the text is being rendered to `<path>`s and not to [`<text>`](https://developer.mozilla.org/en-US/docs/Web/SVG/Tutorial/Texts)s?

AFAIK using `<text>` would enable us to style the text with css and possibly use `text-overflow: ellipsis;` while rendering the entire text.

But nevermind if this is impossible, I don't want to be an annoyance, I'm just curious.
If not possible feel free to just close the issue and thanks in advance for your time.

**Comment by kamranahmedse** [comment]
@arikchakma let's reduce the font size by a few pixels and see if we can increase the character length.

@wesleycoder re text being rendered as `<path>`, we are using [satori](https://github.com/vercel/satori) which has this as a default behavior.
