### ISSUE TITLE
Multilingual advice 多语言建议

### ISSUE THREAD

**Issue by TGCwen** [kamranahmedse/developer-roadmap#5603]
### Roadmap URL

https://roadmap.sh/

### Suggestions

It is recommended to add multiple languages, such as Chinese, etc.

**Comment by 578223592** [comment]
如果可以的话，我可以承担一些翻译工作

**Comment by kamranahmedse** [comment]
Localization is planned. We have already started some preparation for that. We will announce it on the website once we start accepting contributions.
