### ISSUE TITLE
[Suggestion] Frontend Developer thanks 

### ISSUE THREAD

**Issue by Nenatullah2001** [kamranahmedse/developer-roadmap#5609]

**Comment by Nenatullah2001** [comment]
Tath is great

**Comment by dansholds** [comment]
Hey @Nenatullah2001, are you thanking us for the Frontend Developer Roadmap?
If so, you're welcome!

If you haven't already, you can join our Discord server (https://discord.gg/H3GDZ2uV) where you can post your appreciation there!
