### ISSUE TITLE
Spelling error

### ISSUE THREAD

**Issue by elvisduru** [kamranahmedse/developer-roadmap#561]
Under the Branch: **Basics of Javascript** - Understand the concepts **Hoisting** not **Hosting**

**Comment by melvinsalas** [comment]
Solved! Please close it.

**Comment by leezhimeng919** [comment]
Hoisting变量提升

**Comment by elvisduru** [comment]
> Solved! Please close it.

It hasn't been solved yet. I still see *Hosting*

**Comment by kamranahmedse** [comment]
It has been fixed. Thank you for reporting.
