### ISSUE TITLE
tensorflow CPP content is wrong

### ISSUE THREAD

**Issue by DestinyOfLove** [kamranahmedse/developer-roadmap#5617]
### Roadmap URL

https://roadmap.sh/cpp

### Suggestions

use cpp example instead of python 
![image](https://github.com/kamranahmedse/developer-roadmap/assets/37801433/d3d9331c-072f-4424-9d93-8a79f2336fdc)

**Comment by dansholds** [comment]
Hey @DestinyOfLove, I just merged a PR removing the Python examples!

Please feel free to add some CPP examples but for now I focussed on just removing the Python 🤙

**Comment by dansholds** [comment]
FYI here is the closed PR - https://github.com/kamranahmedse/developer-roadmap/pull/5619
