### ISSUE TITLE
Edit the contents

### ISSUE THREAD

**Issue by CodeWithMayank-Py** [kamranahmedse/developer-roadmap#5622]
### Roadmap URL

https://roadmap.sh/data-analyst

### Suggestions

Provide additional resources links to complete that part of module.

**Comment by kamranahmedse** [comment]
Hey! We are closing any issues requesting resources or roadmaps. We will be reviewing all the roadmaps and adding resources to each, but for now, it's being handled by the community. Feel free to do some research and suggest any resources you find helpful.
