### ISSUE TITLE
Spelling error

### ISSUE THREAD

**Issue by MBalazs90** [kamranahmedse/developer-roadmap#563]
Teamcit should be Teamcity in the devops roadmap,
same as Puppe should be Puppet

**Comment by Firefishy** [comment]
They are both complete in the source https://github.com/kamranahmedse/developer-roadmap/blob/master/project/devops-map.json , but suspect the text is truncated in render.

**Comment by kamranahmedse** [comment]
This has been fixed and will be published in the coming release. Thank you 🙏
