### ISSUE TITLE
Full Stack Dev Roadmap Stuck Loading

### ISSUE THREAD

**Issue by iasals** [kamranahmedse/developer-roadmap#5631]
### What is the URL where the issue is happening

https://roadmap.sh/full-stack

### What browsers are you seeing the problem on?

Chrome, Microsoft Edge

### Describe the Bug

![image](https://github.com/kamranahmedse/developer-roadmap/assets/47429858/1932da99-371d-412f-aff5-a5ae4ad9c5e3)
Full Stack Developer Roadmap is stuck in loading for 5+ mins. Tried on Chrome, Edge, and even on a different machine. 

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by dansholds** [comment]
Hey!

Can you please try it also on a different internet connection? i.e. if you've been using the same wifi on different machines can you also try on mobile data? Myself and others cannot replicate the issue, unfortunately.

**Comment by iasals** [comment]
Forgot to mention that I tried other roadmaps with no issues.

Just tried different wifi connections to no avail. Yet, trying mobile data seemed to do the trick! Thank you!!

**Comment by dansholds** [comment]
Awesome @iasals!

I sometimes find that my router has cached something badly so trying mobile data often helps me discover where the problem resides! ❤️
