### ISSUE TITLE
Change Google Cloud Container Registry to Artifact Registry

### ISSUE THREAD

**Issue by digitalghost-dev** [kamranahmedse/developer-roadmap#5639]
### Roadmap URL

https://roadmap.sh/docker

### Suggestions

My last issue was closed without even being addressed: #4456 

### Suggestions

Google Cloud has since moved on to using [Artifact Registry](https://cloud.google.com/artifact-registry/). The section under the Docker roadmap > Container Registries > Others should be updated to talk about Artifact Registry.

**Comment by kamranahmedse** [comment]
Fixed in https://github.com/kamranahmedse/developer-roadmap/commit/d9466717a7c50910b08943201fced992a303d86d
