### ISSUE TITLE
Project suggestions?

### ISSUE THREAD

**Issue by chrisgreg** [kamranahmedse/developer-roadmap#564]
It can be quite difficult to think of application ideas to create and practise with.

I.e. On the backend roadmap it mentions learning a message broker - what kind of simple project could people make to learn a message broker?

**Comment by aleon1220** [comment]
depends on what you like. I was planning to create a simple interoperability of services in a multi-cloud environment with a message broker. i.e. message broker notifies AWS (Queue), Google cloud (REST API), Azure (Old SOAP if supported)  and then combines the responses, create an email, send the email to 3 recipients and creates a record in a simple table that the operation was completed.

**Comment by kamranahmedse** [comment]
These will be added on the website [roadmap.sh](https://roadmap.sh) instead of the repository in the coming weeks after we are done with the 2020 release. Thank you.
