### ISSUE TITLE
<Reopen> [Suggestion] Quarkus in Java web frameworks 

### ISSUE THREAD

**Issue by marcelolemes** [kamranahmedse/developer-roadmap#5643]
### Feature Description

https://github.com/kamranahmedse/developer-roadmap/issues/5234
https://github.com/kamranahmedse/developer-roadmap/issues/3468

**Comment by kamranahmedse** [comment]
Fixed in https://github.com/kamranahmedse/developer-roadmap/commit/bb093764bac3811465d69b76286157b3492386f6
