### ISSUE TITLE
Convention Change for PostGreSQL

### ISSUE THREAD

**Issue by HeyProtagonist** [kamranahmedse/developer-roadmap#5646]
### Roadmap URL

https://roadmap.sh/full-stack

### Suggestions

Change to **SQL** and **No-SQL** DB Connection from **PostgreSQL**

---

```txt
             /--- _SQL_ --- _PostgreSQL, MySQL_
_NodeJS_ ---|
             \--- _No-SQL_ --- _MongoDB_
```

**Comment by kamranahmedse** [comment]
Fullstack roadmap is one of the beginner roadmaps and intentionally recommends just one database i.e. PostgreSQL. The linked backend roadmap has more databases and recommendations.
