### ISSUE TITLE
Roadmaps are not loading 

### ISSUE THREAD

**Issue by AnkitAvi11** [kamranahmedse/developer-roadmap#5647]
### What is the URL where the issue is happening

https://roadmap.sh/kubernetes

### What browsers are you seeing the problem on?

Firefox, Chrome, Safari, Microsoft Edge

### Describe the Bug

![image](https://github.com/kamranahmedse/developer-roadmap/assets/54996872/8ba4b973-96bf-44e5-99c7-447973cb2771)

tried multiple browsers but the roadmaps are not loading 
https://roadmap.sh/backend?r=backend
https://roadmap.sh/kubernetes
https://roadmap.sh/docker

### Output from browser console (if any)

![image](https://github.com/kamranahmedse/developer-roadmap/assets/54996872/f6b1b8cb-39ba-4901-a5ae-9b0b238f23d1)
tried multiple browsers but the roadmaps are not loading 
https://roadmap.sh/backend?r=backend
https://roadmap.sh/kubernetes
https://roadmap.sh/docker

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by alexsuhor** [comment]
same issue

**Comment by logeshNcash** [comment]
yeah. Facing the same issue

**Comment by arikchakma** [comment]
Can you have a look now? I have cleared the cache.

**Comment by dansholds** [comment]
Hey Both!

Can you try again now on private browsers? 

We have released the cache and discord users have reported it as fixed 🎉

**Comment by AnkitAvi11** [comment]
It's fixed. Good to be closed.
