### ISSUE TITLE
Vue Developer roadmap suggestions

### ISSUE THREAD

**Issue by skirtles-code** [kamranahmedse/developer-roadmap#5655]
### Roadmap URL

https://roadmap.sh/vue

### Suggestions

This is a follow up to #3741.

- I would remove Vuepress and Gridsome and add [VitePress](https://vitepress.dev/) instead. Most of the Vue ecosystem is using VitePress for documentation. See <https://blog.vuejs.org/posts/vitepress-1.0>.
- [VueUse](https://vueuse.org/) has over 1 million downloads a week and is something every Vue developer should know about. It's more important than almost everything else currently in the ecosystem section, with the possible exceptions of Vue Router and Pinia.
- Vue Formulate was for Vue 2. It's now FormKit.
- The API Calls section seems a bit out of place. Several of the libraries listed there are orthogonal to using Vue. Some are very rarely used in practice. Most applications are using Axios or native fetch. [TanStack Query](https://tanstack.com/query/latest/docs/framework/vue/overview) might also be worth a mention.
- [Component `v-model`](https://vuejs.org/guide/components/v-model.html) should be mentioned as a separate topic.
- The entry for `Custom Events` seems redundant. That's describing the same topic as the entry titled `Events`.
- Vitest [is recommended](https://vuejs.org/guide/scaling-up/testing.html#recommendation) instead of Jest.
- `nextTick` isn't part of the Composition API. I probably wouldn't mention it at all, there are a lot of other topics that are more important than `nextTick` that aren't currently mentioned.
- There are various parts of the Composition API that aren't mentioned, but many of them are advanced topics so that's probably fine. If `toRefs` is worth mentioning then so is `toRef`. Likewise, if `watch` is mentioned then `watchEffect` probably should be too, though arguably `watch` could be removed as it's already covered by the section on Watchers.
- Going further, I'm not sure having a separate box for the Composition API is entirely justified. It seems a bit arbitrary to list specific functions, rather than listing features or the functionality they achieve. As already mentioned, `watch` is just the function used to implement Watchers. `computed` is used to implement Computed Properties.

**Comment by kamranahmedse** [comment]
That's some great feedback @skirtles-code -- thank you so much for taking the time to submit that. I have made changes to the Vue roadmap. Let me know if you have any other suggestions! 🙏
