### ISSUE TITLE
Python developer roadmap suggestion

### ISSUE THREAD

**Issue by salmantec** [kamranahmedse/developer-roadmap#5657]
### Roadmap URL

https://roadmap.sh/python

### Suggestions

Hi team, It's really useful roadmap for Python. You guys already covered everything, I would like share minor addition into that Python roadmap under `Package managers`.

- Can we add `Poetry` (Package manager), as it's also using by most of the developers and I couldn't see it (Attached screenshot FYR).

<img width="942" alt="Screenshot 2024-05-13 at 9 04 42 AM" src="https://github.com/kamranahmedse/developer-roadmap/assets/41512228/194eb9ae-d025-4439-96c9-598973dc4ce8">

**Comment by salmantec** [comment]
Shall I create a PR for this issue ?

**Comment by dansholds** [comment]
Hey @salmantec!

Thanks for the suggestion, one that is pretty valid given the wide adoption of Poetry 😄 

As for the PR, adding roadmap nodes (the visual boxes) via a PR is not possible as it requires editing of the JSON which is not something we currently accept from the community given how hard it is to test and manage!

I'll add your suggestion to our plans and I'll let you know when it's live!

Feel free to join our discord to stay up to date of these changes and even submit them via discord! 

https://discord.com/invite/2D3d7Wzd

**Comment by salmantec** [comment]
> Hey @salmantec!
> 
> Thanks for the suggestion, one that is pretty valid given the wide adoption of Poetry 😄
> 
> As for the PR, adding roadmap nodes (the visual boxes) via a PR is not possible as it requires editing of the JSON which is not something we currently accept from the community given how hard it is to test and manage!
> 
> I'll add your suggestion to our plans and I'll let you know when it's live!
> 
> Feel free to join our discord to stay up to date of these changes and even submit them via discord!
> 
> https://discord.com/invite/2D3d7Wzd

I've joined in that discord channel. Thanks for the reply @dansholds !

**Comment by dansholds** [comment]
@salmantec PR created - https://github.com/kamranahmedse/developer-roadmap/pull/5664
