### ISSUE TITLE
Java Roadmap: Add Working with date and time in Java

### ISSUE THREAD

**Issue by deniscuciuc** [kamranahmedse/developer-roadmap#5658]
### Roadmap URL

https://roadmap.sh/java

### Suggestions

I think it would be a good update to add work with time and dates in Java to the "Learn the fundamentals" section of the road map.

Very often, in real work, business logic can be tied to working with time or dates.

It would be good to mention the new Date/Time API added in java 8 and the old one.

**Comment by deniscuciuc** [comment]
Sources suggested by me:

1. https://chamalwr.medium.com/datetime-api-in-java-2aef5df1c39b
2. https://www.baeldung.com/java-8-date-time-intro
3. https://www.oracle.com/technical-resources/articles/java/jf14-date-time.html

**Comment by kamranahmedse** [comment]
This has been fixed and will be published in the coming release. Thank you 🙏
