### ISSUE TITLE
I just want to know how to draw this roadmap and which tool be used?

### ISSUE THREAD

**Issue by xgqfrms** [kamranahmedse/developer-roadmap#566]
# Q: 

Hi @kamranahmedse, 

> I just want to know how to draw this roadmap and which tool be used?

https://github.com/kamranahmedse/developer-roadmap/blob/master/images/frontend.png

A: 
> ...

**Comment by xgqfrms** [comment]
I want to create one zh-Hans version, that's all.

**Comment by kamranahmedse** [comment]
I used [Balsamiq](https://balsamiq.com)
