### ISSUE TITLE
Add the official Open API website as an additional resource

### ISSUE THREAD

**Issue by nahtandev** [kamranahmedse/developer-roadmap#5661]
### Roadmap URL

https://roadmap.sh/backend

### Suggestions

![image](https://github.com/kamranahmedse/developer-roadmap/assets/59006429/49657639-87e3-4c1e-b925-e021203bc4ce)

I think we can add at the level of the **Open api spec** branch, the official Open API website (https://www.openapis.org/) as an additional resource.

The learning program can also be practical for getting started quickly: https://learn.openapis.org/

**Comment by kamranahmedse** [comment]
Feel free to submit a PR. Thank you!
