### ISSUE TITLE
Backend roadmap suggestions

### ISSUE THREAD

**Issue by salmantec** [kamranahmedse/developer-roadmap#5665]
### Roadmap URL

https://roadmap.sh/backend

### Suggestions

Hi team, thanks for the awesome `Backend` roadmap. I've read it from fresher perspective and I would like to share some suggestions on this `Backend` roadmap (Correct me If I'm wrong)

- Can we add some widely used tools like `Jenkins`, `Github actions` under `CI / CD` option ? As it doesn't have anything right now.
- I could see AWS DynamoDB under `NoSQL Database` option. Why don't we include Azure's `cosmos db` too ?
- It would be helpful to freshers, if we add 
         - some API testing tools like `Swagger`, `insomnia`, `Postman`
         - and API documentation tools like `Postman`, `Swagger`.
- Do we need to include SSR (server-side rendering) ? (As we touched from basic to advance level)

**CI/CD option suggestion**

<img width="1078" alt="Screenshot 2024-05-14 at 8 45 19 PM" src="https://github.com/kamranahmedse/developer-roadmap/assets/41512228/cb5de15a-2564-48aa-8dd5-112b64eef1c7">

**NoSQL Database suggestion**
<img width="1046" alt="Screenshot 2024-05-14 at 8 50 48 PM" src="https://github.com/kamranahmedse/developer-roadmap/assets/41512228/43601293-95dc-41dc-a2a1-c082c1670383">

**Comment by dansholds** [comment]
As we discussed on Discord, the only suggestion that makes sense is the CI/CD one, and we will add it to our internal tasks.
