### ISSUE TITLE
Links on DSA roadmap for Arrays not working

### ISSUE THREAD

**Issue by KortexGit** [kamranahmedse/developer-roadmap#5666]
### What is the URL where the issue is happening

https://roadmap.sh/datastructures-and-algorithms

### What browsers are you seeing the problem on?

Chrome, Safari

### Describe the Bug

Links on the Array node for DSA roadmap where each link is supposed to show arrays in different languages aren't working. Takes you to page not found (https://roadmap.sh/!https://www.youtube.com/watch?v=gDqQf4Ekr2A&ab_channel=codebasics).

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by kamranahmedse** [comment]
Thank you for reporting this Connor. Feel free to submit a PR.
