### ISSUE TITLE
Linux Roadmap: IPV6

### ISSUE THREAD

**Issue by juliaszone** [kamranahmedse/developer-roadmap#5673]
### Detailed Description

The linux roadmap lacks descriptions of IPv6 related topics and nftables instead of the old iptables.
I'm open to contributing, but have no mental capacity at the moment, so I thought of creating this to remind me or other people of it.
I also propose the renaming of "IP" to "IPv4" where something is specific to IPv4 only (like dot notation), as there are more than one stable IP versions.

**Comment by dansholds** [comment]
Hey @juliaszone!

Thanks for raising this! We're not updating the structure (i.e. adding or removing nodes) right now as we are migrating our roadmaps to our own Roadmap Editor, which effects the way they're built and edited :)
