### ISSUE TITLE
Broken link in Javascript Fetch API

### ISSUE THREAD

**Issue by mmasoudih** [kamranahmedse/developer-roadmap#5674]
### Roadmap URL

https://roadmap.sh/frontend

### Suggestions

Hey, 
in Javascript > Fetch API / Ajax (XHR) > [A Simple Guide to JavaScript Fetch API](https://www.javascripttutorial.net/javascript-fetch-api/) there is broken link.
it should change to this: [A Simple Guide to JavaScript Fetch API](https://www.javascripttutorial.net/web-apis/javascript-fetch-api/)

**Comment by kamranahmedse** [comment]
Thanks for reporting, feel free to open a PR.
