### ISSUE TITLE
Project Manager 

### ISSUE THREAD

**Issue by rumoursbehindme** [kamranahmedse/developer-roadmap#5681]
### **A roadmap to become a project manager.**
_Note: "My manager asked me to put a suggestion"_

**Comment by dansholds** [comment]
Hey @rumoursbehindme!

Thanks for the suggestion! We will add it to the roadmap (our internal roadmap of planned roadmaps 😄)!

Feel free to join our Discord to keep informed of upcoming roadmaps and similar stuff! 

https://discord.gg/ghdpyZeC
