### ISSUE TITLE
Deprecated links in Frontend HTTP Caching

### ISSUE THREAD

**Issue by Nipaaaa1** [kamranahmedse/developer-roadmap#5683]
### Roadmap URL

https://roadmap.sh/best-practices/frontend-performance

### Suggestions

There's a deprecated link in Frontend performance > High Priority > Set HTTP cache headers properly.

The old link ([this one](https://varvy.com/pagespeed/cache-control.html)) give a 404 error. When I tried to go back to it's homepage, it now points to a gambling website.

Here is the response I got when visiting the link:
![](https://github.com/kamranahmedse/developer-roadmap/assets/69257425/8ccb42e4-5723-4b9a-95c5-50193223eb4e)

**Comment by dansholds** [comment]
Awesome thanks for point it out!
