### ISSUE TITLE
Forking a community-made roadmap navigates to `/r/undefined`

### ISSUE THREAD

**Issue by eltigerchino** [kamranahmedse/developer-roadmap#5688]
### What is the URL where the issue is happening

https://roadmap.sh/frontend

### What browsers are you seeing the problem on?

Chrome

### Describe the Bug

1. Login to roadmap.sh
1. Visit https://roadmap.sh/frontend
1. Clicking the "[Visit your own version of this Roadmap](https://roadmap.sh/r/undefined)" button

Expected: Opens the roadmap editor with the community roadmap blocks in place.

Actual: It navigates to https://roadmap.sh/r/undefined

Notes:

Other community roadmaps do not have a fork button https://roadmap.sh/qa

### Output from browser console (if any)

Navigated to https://roadmap.sh/r/undefined
13:38:41.955 http.BM4ZdOlV.js:8 
        
GET https://roadmap.sh/api/v1-get-roadmap-by-slug/undefined 404 (Not Found)

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by kamranahmedse** [comment]
This has been fixed and will be released in a few. Thank you for reporting!
