### ISSUE TITLE
Wrong formkit link

### ISSUE THREAD

**Issue by dowellkin** [kamranahmedse/developer-roadmap#5689]
### Roadmap URL

https://roadmap.sh/vue

### Suggestions

Current link (https://formkit.dev/) to FormKit is wrong and opens nothing. Correct link is https://formkit.com/.
https://formkit.com/getting-started/what-is-formkit for documents page

**Comment by dansholds** [comment]
Hey!

Thanks for reporting, please submit this as a PR 😄
