### ISSUE TITLE
Why this Repository have 77k stars?? 

### ISSUE THREAD

**Issue by SpaceG** [kamranahmedse/developer-roadmap#569]
NO content include.? wired

**Comment by stylesm** [comment]
> NO content include.? wired

Why this Issue raised? No meaningful contribution included.

The main content of this repo is visible in the `[readme.md` file](https://github.com/kamranahmedse/developer-roadmap/blob/master/readme.md).

It isn't a code repo as such, but more a data/content repo.

**Comment by Kyslik** [comment]
This is just "bad" ad.
