### ISSUE TITLE
links redirecting wrong

### ISSUE THREAD

**Issue by esau-morais** [kamranahmedse/developer-roadmap#5692]
### What is the URL where the issue is happening

https://roadmap.sh/datastructures-and-algorithms

### What browsers are you seeing the problem on?

Firefox

### Describe the Bug

if i click in a link it opens as a route, not external url

https://roadmap.sh/!https://www.youtube.com/watch?v=cH6Qv47MPwk&pp=ygUKYXJyYXkgcnVzdA%3D%3D

### Participation

- [X] I am willing to submit a pull request for this issue.

**Comment by dansholds** [comment]
@esau-morais I've found the issue, it seems to be all the videos in the `Array` section, I'll fix this.
