### ISSUE TITLE
Design Patterns Flutter Roadmap

### ISSUE THREAD

**Issue by reliek21** [kamranahmedse/developer-roadmap#5695]
### Roadmap URL

https://roadmap.sh/flutter

### Suggestions

When you go to **Design Patterns** of the roadmap of **Flutter** we got a` broke video with the URL`, this is the video: https://www.youtube.com/watch?v=sk5hwzfndqs

**Comment by dansholds** [comment]
Hey @reliek21 I have fixed but next time feel free to submit a PR removing the broken link rather than submitting and issue 😄
