### ISSUE TITLE
Java: threads

### ISSUE THREAD

**Issue by bhavicka** [kamranahmedse/developer-roadmap#5697]
### Roadmap URL

https://roadmap.sh/java

### Suggestions

enter the topic for thread too which is really important but missing in roadmap

**Comment by kamranahmedse** [comment]
It's already there
<img width="652" alt="image" src="https://github.com/kamranahmedse/developer-roadmap/assets/4921183/77e713d9-ef36-48c9-9eaf-23068a43938b">
