### ISSUE TITLE
Missing info related to CI

### ISSUE THREAD

**Issue by Arihantar** [kamranahmedse/developer-roadmap#570]
I really love your work here but I think you missed GitLab in the CI/CD section (Learn infrastructure as code)

I am not saying this to promote it but I would suggest give this a try and then see.

Currently, GitLab can help you remove many learning stages from your current diagram and as it says removing the complexity of multiple toolchains.

In my opinion, developers should not be spending time in integrating tools instead there core focus should be on development. 

Ref: https://about.gitlab.com/2017/09/27/gitlab-leader-continuous-integration-forrester-wave/

**Comment by Arihantar** [comment]
cc// @kamranahmedse

**Comment by boulabiar** [comment]
I spotted that too.
GitLab CI/CD started to get attraction and i think it should be included.

**Comment by kamranahmedse** [comment]
This has been fixed and will be published in the coming release. Thank you 🙏
