### ISSUE TITLE
Vue Roadmap: Changes to GraphQL and Testing

### ISSUE THREAD

**Issue by devtobi** [kamranahmedse/developer-roadmap#5702]
### Roadmap URL

https://roadmap.sh/vue

## Vue Relay

In the "API Calls" section of the roadmap "Vue Relay" is listed as a technology. However it looks like [Vue Relay](https://github.com/vue-relay/vue-relay) was archived and won't get maintained anymore. I couldn't find a section on the official Relay docs (https://relay.dev) talking about Vue.js either.

That's why I suggest to remove "Vue Relay" from the roadmap.

## Testing

Because Playwright rises in popularity as an alternative solution to Cypress (and also support component testing in experimental stage, see https://playwright.dev/docs/test-components), it might be suitable to also list Playwright in the Testing Section for Vue.

However if we purely talk about testing isolated components and no E2E tests at all, I think tools like the already mentioned Vue Testing Library or the underlying https://test-utils.vuejs.org are better suited.

So my suggestion would be to either
- Add Playwright additionally to Cypress or
- Remove Cypress (because its primary a E2E Testing framework (like Playwright) and thus only list Vitest and Vue Testing Library

**Comment by kamranahmedse** [comment]
Thank you Tobias! This has all been fixed and will be published in the coming release.
