### ISSUE TITLE
Only one Contents & Links can be added to the nodes

### ISSUE THREAD

**Issue by wavelolz** [kamranahmedse/developer-roadmap#5703]
### What is the URL where the issue is happening

https://roadmap.sh/r/us-internship-preparation

### What browsers are you seeing the problem on?

Chrome

### Describe the Bug

Hi, I'm recently editing my own roadmaps. However, I found out that I can only add one link to the Contents & Links section for each node. I am certain that it's available to add multiple links for each nodes before. But now, after adding one link, the "add link" button seem to disappear. I tried to clean the cookies but the problem still doesn't fix. 
![messageImage_1716214776627](https://github.com/kamranahmedse/developer-roadmap/assets/71971775/b380920e-32d8-4b32-9f6f-37dcb2227115)
![messageImage_1716214759560](https://github.com/kamranahmedse/developer-roadmap/assets/71971775/e87efa3d-05c5-49e5-8c48-51bac9292ce7)

### Participation

- [X] I am willing to submit a pull request for this issue.

**Comment by kamranahmedse** [comment]
I am not able to reproduce this. Can you please record a short video of the bug and share it with us? Also can you please look at the browser console to see if there are any errors there?

**Comment by wavelolz** [comment]
I've recorded a video to demonstrate the issue. Also, I founded there's an issue within the browser console when I navigate to Contents & Links section

![Full Stack Data Scientist - Google Chrome 2024-05-23 13-38-01 - Trim (2)](https://github.com/kamranahmedse/developer-roadmap/assets/71971775/a70d9e8d-b18b-4d53-ac6f-d61033d8138d)

![image](https://github.com/kamranahmedse/developer-roadmap/assets/71971775/356685c6-ade2-4f35-b692-a89a5b8f80e7)

**Comment by JVitorCarv** [comment]
I was having the same problem. Turns out that the problem is a responsivity issue. Check this out

https://github.com/user-attachments/assets/f05a1b9f-9105-4c90-85c7-8e96fa33805c
