### ISSUE TITLE
replacing or adding Hosting Link

### ISSUE THREAD

**Issue by Vishesh-Saxena077** [kamranahmedse/developer-roadmap#5704]
### What is the title of the roadmap you are submitting?

Types of Web Hosting

### Roadmap Link

[what is hosting its types](https://www.hostinger.in/tutorials/types-of-web-hosting?ppc_campaign=google_search_generic_hosting_all&bidkw=defaultkeyword&lo=9040185&gad_source=1&gclid=Cj0KCQjw6auyBhDzARIsALIo6v-SNqvo-PMWS8ItO93XqrZq4ObrazOdYwdiw9mGDSNh_dZNpNKBNAoaAqYFEALw_wcB)

**Comment by dansholds** [comment]
Hey @Vishesh-Saxena077 you've not specified what roadmap this is for or what topic within the roadmap is should be added to. Please submit this change in a **PR**.
