### ISSUE TITLE
Navigation between flashcards in Questions page

### ISSUE THREAD

**Issue by vidhihattar** [kamranahmedse/developer-roadmap#5706]
### Feature Description

https://roadmap.sh/questions/react
The quiz flashcards right now are not navigable. Going to the previous flashcard is not possible and the only way to go to previous flashcards is to reset the progress. Also, although it shows the number of questions that the user learnt, knew and skipped, the user cannot access only those questions for practice. I believe adding these feature would make the the experience better for the user. I would like to work on these features if you think this needs to be added.

**Comment by kamranahmedse** [comment]
This has been implemented. Thank you for reporting.
