### ISSUE TITLE
Typescript - Add missing Utility Types

### ISSUE THREAD

**Issue by devtobi** [kamranahmedse/developer-roadmap#5708]
### Roadmap URL

https://roadmap.sh/typescript

### Suggestions

I compared the Utility Types in the roadmap to the currently available Utility Types on https://www.typescriptlang.org/docs/handbook/utility-types.html.

The following utility types are missing in the roadmap:
- Required
- ConstructorParameters
- NoInfer
- ThisParameterType
- OmitThisParameter
- ThisType
- String Manipulation Types (Uppercase, Lowercase, Capitalize, Uncapitalize) (I would group those together into a single node)

**Comment by dansholds** [comment]
Hey @devtobi thanks for this, we're currently not updating nodes on the existing roadmaps until we have transitioned them to using the new Roadmap Editor, so we will add this to the back log but it won't be actioned yet 🦖
