### ISSUE TITLE
This site can’t provide a secure connection

### ISSUE THREAD

**Issue by Ehsanghodratiofficial** [kamranahmedse/developer-roadmap#5712]
### Roadmap URL

https://roadmap.sh/ai-data-scientist

### Suggestions

most link not work and tell me "This site can’t provide a secure connectionwww.ojrq.net sent an invalid response.
[Try running Windows Network Diagnostics](javascript:diagnoseErrors()).
ERR_SSL_PROTOCOL_ERROR"

Plz Edit roadmap

![Screenshot 2024-05-21 232351](https://github.com/kamranahmedse/developer-roadmap/assets/68652506/6e155fd4-181f-4174-947a-b0a7fa63089c)

**Comment by dansholds** [comment]
Hey @Ehsanghodratiofficial thanks for reporting!

I can confirm that this is because an adblocker you're using is blocking the affiliate links to Coursera!

So this is not an issue for all users, even some with certain adblockers don't see this.

**Comment by Ehsanghodratiofficial** [comment]
But I don't have blocker


Which browser works?

**Comment by Ehsanghodratiofficial** [comment]
I live in Armenia.
Can the problem be solved by using a VPN U.S?
