### ISSUE TITLE
Semantics of API Desgin

### ISSUE THREAD

**Issue by christophhillisch** [kamranahmedse/developer-roadmap#5715]
### Roadmap URL

https://roadmap.sh/api-design

### Suggestions

For me the semantics of API design as a part of this roadmap is missing.

Here is a suggestion for a good read: https://stackoverflow.blog/2020/03/02/best-practices-for-rest-api-design/

**Comment by dansholds** [comment]
@christophhillisch please feel free to contribute anything around this topic if it fits into already existing topics but we won't be adding new topic nodes to existing roadmaps until we have transitioned them to our new roadmap editor 🙏
