### ISSUE TITLE
Add instructions when explain the icon colors in topics

### ISSUE THREAD

**Issue by Mixteco-san** [kamranahmedse/developer-roadmap#5717]
### Feature Description

In the raodmap UI we can't see a card or instruction that specify what it's the difference between the check icons to right a topic. I attached an example image:
![check icons](https://github.com/kamranahmedse/developer-roadmap/assets/64444213/7a3f2183-9cdb-4bbc-a821-a336e7d0cda5)
I don't know what it's the difference between the green color and purple color. The UI don't show the instructions.

I can add this feature as a contributor in a new PR if you explain to me the differences.

**Comment by dansholds** [comment]
![Screenshot_20240522-192226.png](https://github.com/kamranahmedse/developer-roadmap/assets/25537601/6c098312-78f4-45c4-970b-916283d3ed37)

The key **_should_** be in the top left of the roadmap, can you share what roadmap you're looking at?

**Comment by dansholds** [comment]
Ah yes, I see it on the Android roadmap 👍

I'll fix it tomorrow 🤗

**Comment by Mixteco-san** [comment]
Thanks! If do you need help, send me a message. 

Have a great day
