### ISSUE TITLE
"Rate Limiting" on API Design shows topic not found

### ISSUE THREAD

**Issue by aUnicornDev** [kamranahmedse/developer-roadmap#5721]
### What is the URL where the issue is happening

https://roadmap.sh/api-design

### What browsers are you seeing the problem on?

Chrome

### Describe the Bug

Selecting "Rate Limiting" on API Design shows topic not found.
![image](https://github.com/kamranahmedse/developer-roadmap/assets/86775297/e4f1d8b5-adaf-40c8-859f-0991c713a9aa)

### Output from browser console (if any)

1 requests
14.8 kB transferred
Request URL : https://roadmap.sh/api-design/rate-limiting@O7wjldZ3yTA2s_F-UnJw_
Request Method : GET
Status Code:404 Not Found

### Participation

- [X] I am willing to submit a pull request for this issue.

**Comment by aUnicornDev** [comment]
Happening because the file is named as "reate-limiting@O7wjldZ3yTA2s_F-UnJw_".

![image](https://github.com/kamranahmedse/developer-roadmap/assets/86775297/b6344327-51be-4b0b-9d4a-daaee2e092e1)

**Comment by dansholds** [comment]
Hey thanks for the find! Please submit a PR for this 🤙
