### ISSUE TITLE
A link is not working

### ISSUE THREAD

**Issue by wandrey7** [kamranahmedse/developer-roadmap#5723]
### What is the URL where the issue is happening

https://roadmap.sh/nodejs

### What browsers are you seeing the problem on?

Firefox, Chrome, Safari, Microsoft Edge, Other

### Describe the Bug

A link that is on the nodejs roadmap (specifically in the event loop, Fourth suggestion link) leads to a youtube page that says: 

Video unavailable
This video is no longer available due to a copyright claim by Udemy
GO TO HOME PAGE"

### Participation

- [X] I am willing to submit a pull request for this issue.

**Comment by dansholds** [comment]
Hey!

Please submit a PR removing the link 🤗

**Comment by wandrey7** [comment]
pr #5724
