### ISSUE TITLE
State Managment for Frontend Roadmap

### ISSUE THREAD

**Issue by rp0777** [kamranahmedse/developer-roadmap#5729]
### Roadmap URL

https://roadmap.sh/frontend

### Suggestions

Please add the state management tools for frontend roadmap.
Tools like Redux, Recoil, Zustand or Context Api for React int he roadmap.
I guess this was missing in it.
Thank you

**Comment by kamranahmedse** [comment]
You will find these in the dedicated framework roadmaps. They don't have a place in the generic frontend roadmap.
