### ISSUE TITLE
Desktop developer roadmap

### ISSUE THREAD

**Issue by azzamsa** [kamranahmedse/developer-roadmap#573]
Roadmap for Qt, GTK+, wxWidgets, etc developer

**Comment by athif23** [comment]
+1 For me.

**Comment by rohitkrishna094** [comment]
+1 from me too.

**Comment by Ronkiro** [comment]
@rohitkrishna094 @athif23 Hey guys, please avoid posts with +1, as this doesn't add any relevant info. Post if you guys have something relevant.

About the thread, we could also separate the desktop roadmaps into CLI, GUI, etc

**Comment by kamranahmedse** [comment]
New roadmap requests are now being tracked through [roadmap.sh](https://github.com/kamranahmedse/roadmap.sh). Thank you!
