### ISSUE TITLE
Do not close side drawer when marking status to "In Progress"

### ISSUE THREAD

**Issue by kareemsalah227** [kamranahmedse/developer-roadmap#5730]
### Background
I've been using the roadmaps and when I click on a step in the roadmap to start working on it and the side drawer slides in from the right, I click on the "update status" and naturally choose "in progress" to mark it as the step I'm working on right now. The side drawer is closed automatically.

I then have to click on the step again to continue reading or working, I find this just a tiny bit inefficient.

### Proposal

I think it would be easier that the drawer does not close automatically, it could be when the status selected is "In progress" or in general when there is any status update by the user. I think the latter option is easier to implement and less complex and yields same results.

**Comment by SumanKisku** [comment]
@kamranahmedse Hi can you assign it to me?

**Comment by dansholds** [comment]
@SumanKisku I assigned it to you, are you in the Discord?

**Comment by SumanKisku** [comment]
> @SumanKisku I assigned it to you, are you in the Discord?

Yeah I am on discord.

**Comment by dansholds** [comment]
> > @SumanKisku I assigned it to you, are you in the Discord?
> 
> Yeah I am on discord.

Ok, as this is assigned to you please aim to complete it as soon as realistically possible as it will prevent other people from working on it 🤗

Please tag me on discord in the contributor channel and I'll review 🤙

**Comment by masoudhsd** [comment]
Hi @SumanKisku 
Are you working on this issue?
if not, I'd like to go for it.
Thanks.

**Comment by SumanKisku** [comment]
@masoudhsd Yeah I'm working on it.
