### ISSUE TITLE
Checkbox's are not clickable

### ISSUE THREAD

**Issue by shaikahmadnawaz** [kamranahmedse/developer-roadmap#5736]
### What is the URL where the issue is happening

https://roadmap.sh/aws

### Describe the Bug

In the AWS roadmap, left side checkboxes are not clickable.

![image](https://github.com/kamranahmedse/developer-roadmap/assets/96189881/43047a47-01be-4bdc-bd93-837140065171)

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by arikchakma** [comment]
This isn't supposed to be clickable. Thank you.
