### ISSUE TITLE
Mention the RustRover IDE in "IDEs and Rust Toolchains"

### ISSUE THREAD

**Issue by fellalli** [kamranahmedse/developer-roadmap#5741]
### Roadmap URL

https://roadmap.sh/rust

### Suggestions

https://github.com/kamranahmedse/developer-roadmap/blob/ba630173b8d87dc4b8bbfee99a607ca06489bac0/src/data/roadmaps/rust/content/100-introduction/104-ides-and-rust.md?plain=1#L3

`IntelliJ-based IDEs also support Rust through their plugin.`

It might be a good idea to mention [RustRover](https://www.jetbrains.com/rust/), which was released a few days ago, as it is a full IDE rather than just a plugin.

**Comment by kamranahmedse** [comment]
Thank you, feel free to open a PR.
