### ISSUE TITLE
Missing Roadmap Topics

### ISSUE THREAD

**Issue by AbdullahNjoum98** [kamranahmedse/developer-roadmap#5743]
### Roadmap URL

https://roadmap.sh/frontend

### Suggestions

I think it's crucial for any developer (fullstack, frontend, backend) to solidly understand some basic data structure and algorithms, OOP, and design patterns. Of course the level of diving into these topics might differ based on the specification (for instance, I can imagine that BE guys should delve deeper with data structure and algorithm to include advanced topics such as DP, Trees in depth and so forth) but there should be some basic level of understanding for those topics. I won't have as much experience as you guys do, so I am not going to suggest any further details on what needs to be included in the roadmap but I would really like to hear back with your opinions. Warm Greetings!

**Comment by dansholds** [comment]
Hey!

We have various in-depth Comp Sci roadmaps that cover these topics in great details;

https://roadmap.sh/computer-science
https://roadmap.sh/datastructures-and-algorithms
https://roadmap.sh/system-design
https://roadmap.sh/software-design-architecture
https://roadmap.sh/software-architect


It would be impossible to include deep dives of these topics within other roadmaps, so they have their own 😄
