### ISSUE TITLE
Missing rendering techniques in frontend

### ISSUE THREAD

**Issue by iravikhatri** [kamranahmedse/developer-roadmap#5744]
### Roadmap URL

https://roadmap.sh/frontend

### Suggestions

I couldn't find rendering techniques in the frontend roadmap. These days, it's crucial to learn and some of the techniques are CSR, SSR, SSG, and etc.

**Comment by kamranahmedse** [comment]
Thank you for opening the issue. We don't want to convolute the roadmap by mentioning every available topic and are just focusing on mandatory items. SSR and SSG are already mentioned. For the rest of them anyone following this roadmap will automatically come across them.
