### ISSUE TITLE
Objective - C unnecessary

### ISSUE THREAD

**Issue by fatihdurmaz** [kamranahmedse/developer-roadmap#5754]
### Roadmap URL

https://roadmap.sh/ios

### Suggestions

Swift has been adopted as the primary programming language on the Apple platform. Using Objective - C, It completely disappeared in new projects.

**Comment by dansholds** [comment]
While it's true that Swift is the most popular language, other languages like Objective-C still exist in legacy codebases, which is why we list it as an optional language (note we highlighted Swift as recommended.)
