### ISSUE TITLE
no mention of express topic in the Full Stack Developer Roadmap

### ISSUE THREAD

**Issue by AbhishekJha3511** [kamranahmedse/developer-roadmap#5760]
### Roadmap URL

https://roadmap.sh/full-stack

### Suggestions

In the Full Stack Developer Roadmap, there is no mention of the ExpressJS topic.

**Comment by kamranahmedse** [comment]
We intentionally didn't make any recommendations there to keep the roadmap simple. There are many good options (expressjs, fastify, nestjs etc) and we didn't want to add a single one. Might be better to add it under the node node content. Feel free to open a PR for that.
