### ISSUE TITLE
Mobile-first workflow should be added

### ISSUE THREAD

**Issue by onlinebizsoft** [kamranahmedse/developer-roadmap#577]
Front-end developers now need to follow mobile-first workflow so I guess this should be highlighted in CSS knowledge

**Comment by oryan** [comment]
Screen agnostic CSS is a more future proof concept than focusing on any one device first.
Mobile first is already becoming outdated.

You're much better off thinking about your HTML structure in a way that maximizes syntax and the relationship with the content and functionality it is meant to present to the user over how it will be laid out in one specific scenario.

**Comment by kamranahmedse** [comment]
There have been changes made to that section in the coming release which makes this issue outdated. Thank you for reporting though 🙏
