### ISSUE TITLE
Download quality low 

### ISSUE THREAD

**Issue by NarutoNi** [kamranahmedse/developer-roadmap#5770]
### Detailed Description

When downloading roadmaps the quality is low and tried multiple times but got same result

**Comment by kamranahmedse** [comment]
@NarutoNi what roadmaps are you talking about? How are you downloading it?

**Comment by NarutoNi** [comment]
![Screenshot_20240530-171928_Chrome.jpg](https://github.com/kamranahmedse/developer-roadmap/assets/101825304/5761b008-8872-4a94-a938-2bd3994bb801)

When generating ai roadmaps and downloading the pdf (using the default download option )the quality is really low to understand anything .

**Comment by dansholds** [comment]
@kamranahmedse @NarutoNi The quality on Desktop isn't crystal clear but it's certainly not too low to understand anything.

<img width="708" alt="Screenshot 2024-05-31 at 10 54 39" src="https://github.com/kamranahmedse/developer-roadmap/assets/25537601/2df94539-7f97-4bf1-b513-71083f32ca6c">
