### ISSUE TITLE
Add Transation Isolation Levels

### ISSUE THREAD

**Issue by Sshreydoshi** [kamranahmedse/developer-roadmap#5776]
### Roadmap URL

https://roadmap.sh/sql

### Suggestions

I would like add 4 **Transaction Isolation Levels** as follows:

1. Read Uncommitted
2. Read Committed
3. Repeatable Read
4. Serializable

**Comment by dansholds** [comment]
Hey @Sshreydoshi These already exist in the content of `Transaction Isolation Levels`?

<img width="605" alt="Screenshot 2024-05-31 at 11 13 39" src="https://github.com/kamranahmedse/developer-roadmap/assets/25537601/b8f67eae-8e00-4bf2-be44-df4ccca4cf89">
