### ISSUE TITLE
Standardize using docker ps or docker container ls -a in listing containers

### ISSUE THREAD

**Issue by apun97** [kamranahmedse/developer-roadmap#5783]
### Roadmap URL

https://roadmap.sh/docker

### Suggestions

In the Running Containers section, the Listing Containers description mentions using `docker ps` to list containers whereas the example uses `docker container ls -a`. Can we change the description or example to be consistent and use the same command in both places. Maybe just have another note to mention the existence of the other option to show they both do the same thing.

**Comment by dansholds** [comment]
Hey @apun97 feel free to submit a PR to rectify this :)
