### ISSUE TITLE
React Roadmap not loading

### ISSUE THREAD

**Issue by emargetis** [kamranahmedse/developer-roadmap#5786]
### What is the URL where the issue is happening

https://roadmap.sh/react

### What browsers are you seeing the problem on?

Chrome

### Describe the Bug

React roadmap is not loading for me, but all of the other ones are. 
![Screenshot 2024-06-01 105140](https://github.com/kamranahmedse/developer-roadmap/assets/8213376/c6a3ed70-8b76-4010-bcff-24e918a4d383)

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by arikchakma** [comment]
Let me have a look

**Comment by dansholds** [comment]
Seems good now @arikchakma thank you 🚀
