### ISSUE TITLE
my image #2

### ISSUE THREAD

**Issue by dihpan** [kamranahmedse/developer-roadmap#579]
![Kusuma](https://user-images.githubusercontent.com/49874175/57181484-9ee28e00-6ebe-11e9-9c04-1eab6d312cb2.jpg)
![sECONd GG](https://user-images.githubusercontent.com/49874175/57181485-9ee28e00-6ebe-11e9-9001-28c9478a62d6.jpg)
![4 (2)](https://user-images.githubusercontent.com/49874175/57181486-9ee28e00-6ebe-11e9-8ae4-bd01da41fabc.png)

**Comment by dihpan** [comment]
![dire](https://user-images.githubusercontent.com/49874175/57189188-75b11480-6f35-11e9-9bc0-17891af9fab9.jpg)

**Comment by Kyslik** [comment]
@kamranahmedse I think you can block the person if you haven't yet. https://github.com/settings/blocked_users

**Comment by kamranahmedse** [comment]
Already done. Thanks @Kyslik
