### ISSUE TITLE
MLOPs Go language no topics found. Could hold link to the go language roadmap

### ISSUE THREAD

**Issue by brettearle** [kamranahmedse/developer-roadmap#5793]
### What is the URL where the issue is happening

https://roadmap.sh/mlops

### What browsers are you seeing the problem on?

Firefox

### Describe the Bug

Go button has no content in pop in side bar

### Output from browser console (if any)

XHRGET
https://roadmap.sh/mlops/programming-fundamentals/go
[HTTP/2 404  383ms]

	
GET
	https://roadmap.sh/mlops/programming-fundamentals/go
Status
404
VersionHTTP/2
Transferred13.38 kB (46.54 kB size)
Referrer Policystrict-origin-when-cross-origin
DNS ResolutionSystem

    	
    age
    	27818
    cache-control
    	max-age=0, must-revalidate
    content-encoding
    	br
    content-type
    	text/html; charset=UTF-8
    date
    	Sun, 02 Jun 2024 16:58:55 GMT
    etag
    	W/"b5cc-18fd4894812"
    last-modified
    	Sat, 01 Jun 2024 16:01:57 GMT
    server
    	nginx/1.18.0 (Ubuntu)
    vary
    	Accept-Encoding
    via
    	1.1 77f2beab682f210bbc41ce20e77485aa.cloudfront.net (CloudFront)
    x-amz-cf-id
    	WA3q__oUKTZoTDkKt73E8yH1U2YOuB7kv71AjIw8D7O4x_V6b_Y5gA==
    x-amz-cf-pop
    	MEL50-C1
    x-cache
    	Error from cloudfront
    X-Firefox-Spdy
    	h2
    x-frame-options
    	SAMEORIGIN
    	
    Accept
    	text/html
    Accept-Encoding
    	gzip, deflate, br, zstd
    Accept-Language
    	en-US,en;q=0.5
    authorization
    	Bearer undefined
    Connection
    	keep-alive
    content-type
    	application/json
    Cookie
    	_ga=GA1.2.172522472.1717374616; _gid=GA1.2.1589545951.1717374616; _ga_EZHDT2S2LF=GS1.1.1717374616.1.1.1717375256.60.0.0; vsc-6617f062ec2f026ac21ad5d6=1
    fp
    	9e57b77060863ddf4a98bc976a4196c8
    Host
    	roadmap.sh
    Priority
    	u=4
    Referer
    	https://roadmap.sh/mlops
    Sec-Fetch-Dest
    	empty
    Sec-Fetch-Mode
    	cors
    Sec-Fetch-Site
    	same-origin
    TE
    	trailers
    User-Agent
    	Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:126.0) Gecko/20100101 Firefox/126.0

### Participation

- [X] I am willing to submit a pull request for this issue.

**Comment by dansholds** [comment]
The content does exist, it's just not linked correctly! I'll correct this now, thanks for highlighting!
