### ISSUE TITLE
Adding search bar 

### ISSUE THREAD

**Issue by mukilan2815** [kamranahmedse/developer-roadmap#5796]
### Feature Description

![image](https://github.com/kamranahmedse/developer-roadmap/assets/71129858/a0d611ac-0a02-4ad5-b7bd-43350cb6dc7a)

If there is a search bar here , it will be helpful. I feel some difficulties in searching roadmap in this white background. so that search bar will be helpful to search the Role in this page.

**Comment by dansholds** [comment]
@mukilan2815 is the search field in the main nav bar not sufficient? 

<img width="1025" alt="Screenshot 2024-06-03 at 09 58 07" src="https://github.com/kamranahmedse/developer-roadmap/assets/25537601/90b8daa9-37f8-4e67-895e-8552325c7f58">
