### ISSUE TITLE
Functional testing branch

### ISSUE THREAD

**Issue by marceloogeda** [kamranahmedse/developer-roadmap#58]
I would suggest a branch to "Functional testing".

Frontend: 
- Chimp;
- PhantomJS;
- Nightwatch.js;
- Zombie.js

Backend: 
- Behat;
- Cucumber;
- Behave;

There are many other tools that have the same purpose that can be included in this list.

**Comment by kamranahmedse** [comment]
Hi @marceloogeda, 

I may update it in future to add this stuff but for now the main focus was on answering "what is the bare minimum that one should know to become a web developer?" and I think what you have mentioned is not an absolute necessity.

Thank you for reporting though.
