### ISSUE TITLE
Intermediate/Advanced CompTIA Security-related certifications

### ISSUE THREAD

**Issue by B34RDED1der** [kamranahmedse/developer-roadmap#5802]
### Roadmap URL

https://roadmap.sh/cyber-security

### Suggestions

Hi, 
I would like to see CompTIA's CySA+, Pentest+, and CASP+ certificates on the roadmap. 
CySA+ and Pentest+ might not fit into the general theme, but CASP+ could find a home in the Advanced Certifications section

**Comment by dansholds** [comment]
Sure, we will have a look at what we can do 👍 


Also, did you create an account just to post this issue? 😄

**Comment by B34RDED1der** [comment]
I did indeed ;-) but I have plans to learn some coding over the next
free months, so hopefully will get some use out of it
