### ISSUE TITLE
Add direct links to docs.aws.amazon.com within Roadmap.

### ISSUE THREAD

**Issue by ryanrem921** [kamranahmedse/developer-roadmap#5805]
### Roadmap URL

https://roadmap.sh/aws

### Suggestions

AWS provides resources on many of these topics within their https://docs.aws.amazon.com/ site. For example, for SES Sandbox / Sending Limits, the resource Request production access (Moving out of the Amazon SES sandbox) - https://docs.aws.amazon.com/ses/latest/dg/request-production-access.html provides in detailed steps on how to exactly move out of sandbox. 

The added details within these sites provide additional context that might not have been included in the roadmap. Using the Sending Limits and Production access, example, while this is technically a standard limit increase, it must go through an approval process and must state why the client is using SES.

**Comment by dansholds** [comment]
Hey! 

Feel free to submit new content links in a PR A🤗

Remember to check the contribution docs found in the README or join the discord to get help 😎
