### ISSUE TITLE
Unusual Behavior of "Frequently Asked Questions" section of a few roadmaps

### ISSUE THREAD

**Issue by BeardedOwl1357** [kamranahmedse/developer-roadmap#5811]
### What is the URL where the issue is happening

https://roadmap.sh/backend

### What browsers are you seeing the problem on?

Firefox, Microsoft Edge

### Describe the Bug

# I am not exactly sure whether this is a bug or a UX decision. 

In the frequently asked section of the below articles, if I click on an "open" question, instead of it getting folded / collapsing, it just.... stays there. Normally, you would expect it to close and open as per your clicks

- https://roadmap.sh/backend
- https://roadmap.sh/frontend

The behavior which I am expecting happens when you click on some other question (if question 1 is open and you click on question 2, the question 2 opens and question 1 closes. My expected behavior is that if I click on question 1 which is currently open, it should close and vice versa)

![image](https://github.com/kamranahmedse/developer-roadmap/assets/59707554/bcfba247-7323-4ae8-88a3-0597d7b1e841)

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by kamranahmedse** [comment]
Thank you for reporting but that's expected behavior.
