### ISSUE TITLE
Need badges to distinguish b/w a Read and Watch Resources

### ISSUE THREAD

**Issue by iArchitSharma** [kamranahmedse/developer-roadmap#5812]
### Feature Description

Earlier, we used to have badges to distinguish between Read and Watch content. This issue is a feature request to have something similar for the Resources section. If we are moving forward with this feature, I would love to work on it or help with it.

### Current:
![image](https://github.com/kamranahmedse/developer-roadmap/assets/74408634/cdce869f-d4ad-4586-ad78-cc59c003c0b8)

### Desired:
![image](https://github.com/kamranahmedse/developer-roadmap/assets/74408634/692d4290-7276-4473-85d6-96def20e262f)

**Comment by dansholds** [comment]
Hey @iArchitSharma we're currently not making changes like this to existing roadmaps as we are transitioning to our new editor for all future roadmaps, but we will take this into consideration 🙏

**Comment by arikchakma** [comment]
https://github.com/kamranahmedse/developer-roadmap/pull/5817

@iArchitSharma I hope it will help.

**Comment by iArchitSharma** [comment]
@arikchakma Thanks for bringing it back
