### ISSUE TITLE
Creating Directories 

### ISSUE THREAD

**Issue by CallMeSnacktime** [kamranahmedse/developer-roadmap#5819]
### Roadmap URL

https://roadmap.sh/linux

### Suggestions

There is a node that says "Creating & Deleting Files / Dirs" but only shows how to create a file. I'm suggesting adding how to delete a file to the node and then creating another node on how to create and delete directories. I know its a basic topic but I came across this website in a group that has quite a few beginners so I figured it would be helpful for them. Thank you for your time.

**Comment by kamranahmedse** [comment]
Thank you for opening the issue. Feel free to submit a PR with content change instead. I don't think we need a separate node for that.
