### ISSUE TITLE
Incorrectly redirecting link

### ISSUE THREAD

**Issue by JesusG16** [kamranahmedse/developer-roadmap#5820]
### Detailed Description

On the Software Design and Architecture roadmap, there is an article in the Object oriented programming section: "[Discover Object Oriented Programming](https://blog.hubspot.com/website/object-oriented-programming)", however, the link now redirects to a different blog entry not really related to OOP.

**Comment by dansholds** [comment]
Huh, thats a strange thing for them to do!

Please submit a PR to swap the link for a better one or remove it entirely :)
