### ISSUE TITLE
Cannot edit `Content & Link` description from the middle.

### ISSUE THREAD

**Issue by dansholds** [kamranahmedse/developer-roadmap#5825]
### What is the URL where the issue is happening

Custom roadmaps

### What browsers are you seeing the problem on?

Firefox

### Describe the Bug

When creating a custom roadmap and adding content to the `Content & Links` section of a topic or sub-topic, you cannot navigate to the center of the text using cursor or keyboard arrows (up or down). You instead have to click to the start or end and then use the L or R arrows to navigate to where you want to edit.

https://github.com/kamranahmedse/developer-roadmap/assets/25537601/7c1aa41f-e101-40b3-b692-a0c6de7f78b0

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by kamranahmedse** [comment]
@dansholds can you please confirm/close if it is working fine?

**Comment by dansholds** [comment]
> @dansholds can you please confirm/close if it is working fine?

Still an active bug, it's in the backlog to be fixed 🤙

**Comment by dansholds** [comment]
@arikchakma FYI this is still an issue on Firefox at least.

**Comment by kamranahmedse** [comment]
@dansholds could it be grammarly? Can you try with that disabled?

**Comment by dansholds** [comment]
> @dansholds could it be grammarly? Can you try with that disabled?

No such luck unfortunately

**Comment by dansholds** [comment]
This appeared to be an issue my end so I will close unless it is reopened.
