### ISSUE TITLE
MLOps

### ISSUE THREAD

**Issue by arihant1805** [kamranahmedse/developer-roadmap#5832]
### What is the URL where the issue is happening

https://roadmap.sh/ai-data-scientist

### Describe the Bug

The suggested course is not available now for MLOps which is MLOps specialization.

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by dansholds** [comment]
Hey @arihant1805 I noticed that the course didn't exist a couple of days ago but it now appears to be back? 🤔 


https://github.com/kamranahmedse/developer-roadmap/assets/25537601/86ca38fd-e840-4235-ae23-53d009f45e0e

**Comment by dansholds** [comment]
@arihant1805 we are going to update the link to another MLOPS course such as this one - https://www.coursera.org/specializations/mlops-machine-learning-duke 👍

**Comment by arihant1805** [comment]
I have a doubt about it that, Is that course as valuable as the MLOps specialization by the Deeplearning.ai.

**Comment by dansholds** [comment]
@arihant1805 unfortunately we can't control the original course being removed from Coursera.

**Comment by arihant1805** [comment]
I know that but, i m genuinely searching for a good resource to learn MLOps
