### ISSUE TITLE
Missing project descriptions

### ISSUE THREAD

**Issue by Vincent-Pantaleon** [kamranahmedse/developer-roadmap#5836]
### What is the URL where the issue is happening

https://roadmap.sh/full-stack

### What browsers are you seeing the problem on?

Chrome

### Describe the Bug

The project descriptions to explain the suggested projects are gone, that helped me a lot to practice what I've learned and it's missing.

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by kamranahmedse** [comment]
Thank you for reporting. I am looking into this.

**Comment by kamranahmedse** [comment]
This has been fixed. Thank you for reporting!
