### ISSUE TITLE
Pls add Fundamental CS concepts as well for eg.- Algorithm, data structure in the Front-end Roadmap

### ISSUE THREAD

**Issue by Sandydh** [kamranahmedse/developer-roadmap#5838]
### Roadmap URL

https://roadmap.sh/frontend?r=frontend-beginner

### Suggestions

Please include fundamental CS concepts such as algorithms and data structures in the front-end roadmap, as they are important to understand the "why" and are often asked about in interviews.

I am a beginner from a non-tech background, and I think the roadmap looks great!

**Comment by kamranahmedse** [comment]
We have a separate roadmap for that.
