### ISSUE TITLE
Database "Failure Modes" section under backend roadmap is not rendered

### ISSUE THREAD

**Issue by AlexPetul** [kamranahmedse/developer-roadmap#5842]
### What is the URL where the issue is happening

https://roadmap.sh/backend

### What browsers are you seeing the problem on?

Chrome, Safari

### Describe the Bug

When I navigate to "More about Databases" -> "Failure modes" in backend roadmap I don't see the content of the page. Everything that is displayed is just a text:

> There are several different failure modes that can occur in a database, including:

### Output from browser console (if any)

However the request seems correct and I can see the relevant data being returned from the server:

GET https://roadmap.sh/backend/more-about-databases/failure-modes

Failure Modes
There are several different failure modes that can occur in a database, including:

- Read contention: This occurs when multiple clients or processes are trying to read data from the same location in the database at the same time, which can lead to delays or errors.
- Write contention: This occurs when multiple clients or processes are trying to write data to the same location in the database at the same time, which can lead to delays or errors.
- Thundering herd: This occurs when a large number of clients or processes try to access the same resource simultaneously, which can lead to resource exhaustion and reduced performance.
- Cascade: This occurs when a failure in one part of the database system causes a chain reaction that leads to failures in other parts of the system.
- Deadlock: This occurs when two or more transactions are waiting for each other to release a lock on a resource, leading to a standstill.
- Corruption: This occurs when data in the database becomes corrupted, which can lead to errors or unexpected results when reading or writing to the database.
- Hardware failure: This occurs when hardware components, such as disk drives or memory, fail, which can lead to data loss or corruption.
- Software failure: This occurs when software components, such as the database management system or application, fail, which can lead to errors or unexpected results.
- Network failure: This occurs when the network connection between the database and the client is lost, which can lead to errors or timeouts when trying to access the database.
- Denial of service (DoS) attack: This occurs when a malicious actor attempts to overwhelm the database with requests, leading to resource exhaustion and reduced performance.

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by kamranahmedse** [comment]
This has been fixed. Thank you for reporting!
