### ISSUE TITLE
Missing Data on Website

### ISSUE THREAD

**Issue by shubchaudhary** [kamranahmedse/developer-roadmap#5843]
### What is the URL where the issue is happening

https://roadmap.sh/cpp

### What browsers are you seeing the problem on?

Chrome

### Describe the Bug

![image](https://github.com/kamranahmedse/developer-roadmap/assets/84193899/3e43d4a8-26ee-4673-931c-618989aa972e)
Missing Data after For Example which is available on github but not on website.

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by kamranahmedse** [comment]
It's not a bug, we are looking for contributors to add resources. Feel free to help us populate resources.
