### ISSUE TITLE
Spring Boot Microservices Circuit Breaker

### ISSUE THREAD

**Issue by SuhasBk** [kamranahmedse/developer-roadmap#5844]
### Roadmap URL

https://roadmap.sh/spring-boot

### Suggestions

Since Hystrix is now deprecated, the docs can be updated to include Resilience4j as an alternative in Spring Cloud Circuit Breaker topic.

Resilience4j Docs: https://resilience4j.readme.io/docs/getting-started

**Comment by dansholds** [comment]
Hey @SuhasBk thanks for pointing this out!

The Hystrix node no longer appears on the roadmap! We are in the process of migrating all our roadmaps to a new system so we will tackle deprecated items etc once that's complete :)
