### ISSUE TITLE
Can't complete blue topics?

### ISSUE THREAD

**Issue by bitblocksplicer** [kamranahmedse/developer-roadmap#5849]
### Detailed Description

I don't know if we can truly call this a "bug", so I didn't open this issue under the bug tag.
In [DevOps Roadmap](https://roadmap.sh/devops), There are topics colored blue that link to other roadmaps. However, completing them isn't possible - the only interact that I can make is left click them, which is not what I want.
![resim](https://github.com/kamranahmedse/developer-roadmap/assets/28842754/8c81e761-1a1a-4e6b-85db-9978142cbf79)

**Comment by dansholds** [comment]
@bitblocksplicer the blue topics will take you through to standalone Roadmaps on that topic, is that not what is desired?

**Comment by dansholds** [comment]
I see that being unable to "complete" these topics does make it impossible to complete the DevOps roadmap. I'll create an internal ticket and we will get to it once we have migrated the roadmap to the new editor 😄

**Comment by bitblocksplicer** [comment]
> I see that being unable to "complete" these topics does make it impossible to complete the DevOps roadmap. I'll create an internal ticket and we will get to it once we have migrated the roadmap to the new editor 😄

That sounds great. Looking forward to seeing the updates. 👌
