### ISSUE TITLE
Add bun in frontend package manager roadmap

### ISSUE THREAD

**Issue by yaviskokakola** [kamranahmedse/developer-roadmap#5856]
### Roadmap URL

https://roadmap.sh/frontend

### Suggestions

add bun option for package managers inside frontend roadmal

**Comment by dansholds** [comment]
Hey @yaviskokakola thanks for raising this, we have included an outbound link to Bun in the Build Tools > Task Runner topic (see below). We won't be adding any new interactive nodes to our roadmaps just yet as we are currently in the process of migrating them to the new editor 😄 

<img width="364" alt="Screenshot 2024-06-12 at 09 34 51" src="https://github.com/kamranahmedse/developer-roadmap/assets/25537601/64877337-3ab5-4d92-880b-536401d9982d">
