### ISSUE TITLE
Add swc to the frontend roadmap module bundlers

### ISSUE THREAD

**Issue by yaviskokakola** [kamranahmedse/developer-roadmap#5857]
### Roadmap URL

https://roadmap.sh/frontend

### Suggestions

add swc in the module bundlers in the frontend roadmap

**Comment by dansholds** [comment]
Hey @yaviskokakola we already have 5 bundlers added as their own topics & the SWC bundler is incomplete and not going to be actively developed as per - https://swc.rs/docs/usage/bundling
