### ISSUE TITLE
Concordion for Java

### ISSUE THREAD

**Issue by johnnyredwood** [kamranahmedse/developer-roadmap#5864]
### Roadmap URL

https://roadmap.sh/java

### Suggestions

In the part of tests add Concordion for acceptance tests!

**Comment by dansholds** [comment]
Hey @johnnyredwood the aim isn't to add every tool to the roadmaps, having 2/3 tools per section is enough to give an overview, feel free to add a link to concordion in the Acceptance Tests topic if you feel it's needed.
