### ISSUE TITLE
Game Design

### ISSUE THREAD

**Issue by hchiam** [kamranahmedse/developer-roadmap#5865]
### Roadmap URL

https://roadmap.sh/game-developer

### Suggestions

Would it make sense to add in content for game design within the game-developer roadmap? For example, game mechanics, "fun" (ludology and gamification etc), A/B testing, etc.? The roadmap for Game Developer currently looks like only the implementation side, but I can understand if it'd be better off as a separate roadmap for Game Designer.

**Comment by dansholds** [comment]
I would go with your latter comment and say it would be best suited as a separate roadmap, when they roadmap would be created though...I'm unsure.

You can use https://roadmap.sh/ai to generate one and see how it looks!
