### ISSUE TITLE
Adding DORA to DevOps Roadmap

### ISSUE THREAD

**Issue by NKipouros92** [kamranahmedse/developer-roadmap#5870]
### Roadmap URL

https://roadmap.sh/devops

### Suggestions

Adding a DORA specific section to the DevOps Roadmap

**Comment by dansholds** [comment]
I wouldn't really say DORA is relevant for a DevOps engineer, especially a junior or someone starting their journey.

Adding it to a future Engineering Manager roadmap would make more sense IMO.
