### ISSUE TITLE
Missing of an important topic in the SQL roadmap

### ISSUE THREAD

**Issue by ManojKumar392** [kamranahmedse/developer-roadmap#5875]
### Detailed Description

Hey, I was trying to follow the roadmap for SQL. I have prior SQL knowledge from college and wanted to deep dive. I noted triggers which is a very important SQL concept is missing.

**Comment by fellalli** [comment]
Hi @ManojKumar392, Triggers are mentioned under 'Advanced SQL Concepts'.

https://github.com/kamranahmedse/developer-roadmap/blob/94b245b2cf95dfa31b57c3a3d303eba843977bdb/src/data/roadmaps/sql/content/115-advanced-sql/index.md?plain=1#L16-L26

**Comment by medovanx** [comment]
> Hi @ManojKumar392, Triggers are mentioned under 'Advanced SQL Concepts'.
> 
> https://github.com/kamranahmedse/developer-roadmap/blob/94b245b2cf95dfa31b57c3a3d303eba843977bdb/src/data/roadmaps/sql/content/115-advanced-sql/index.md?plain=1#L16-L26

That's true
![image](https://github.com/kamranahmedse/developer-roadmap/assets/29468096/4f6a960a-a8b2-4cef-8c6b-08adfb6ce42e)
