### ISSUE TITLE
add codeberg to vcs hostings

### ISSUE THREAD

**Issue by MPBCoder** [kamranahmedse/developer-roadmap#5880]
### Roadmap URL

https://roadmap.sh/frontend

### Suggestions

in the vcs hostings there are github, gitlab and git bucket... i think it's good to add codeberg... 
(my English not fine sorry for typos)

**Comment by MPBCoder** [comment]
i forget to say it's good to add to other related roadmaps...

**Comment by dansholds** [comment]
Codeberg is a great FOSS that's self hosted but we're currently not adding anymore interactive nodes to existing roadmaps until we have transitioned them all onto the new editor ☺️

I'll mark this one down then!
