### ISSUE TITLE
Libraries in C++

### ISSUE THREAD

**Issue by bmarques1995** [kamranahmedse/developer-roadmap#5892]
### Roadmap URL

https://roadmap.sh/cpp

### Suggestions

I believe that an important topic on C++ learning is linkage, how to create a library, differences between static and dynamic linking

**Comment by dansholds** [comment]
Hey @bmarques1995 thanks for raising!

We do mention `linkage` in the `Name Mangling` topic, which will hopefully trigger users to investigate what that is, but feel free to submit a PR add a link to a resource about `linkage` 😄 

As for the other topics you mentioned, you can submit a PR to add details about those topics to a topic that already exists, for instance we do also mention `linking` in a few topics but you can probably expand on that 😄
