### ISSUE TITLE
Left exclusive join, right exclusive join and full exclusive join in SQL roadmap

### ISSUE THREAD

**Issue by niharika1102** [kamranahmedse/developer-roadmap#5899]
### Roadmap URL

https://roadmap.sh/sql

### Suggestions

My suggestion is to add the following sub-topics under the **Joins** topic:
1. Left exclusive join
2. Right exclusive join
3. Full exclusive join

**Comment by kamranahmedse** [comment]
It's already listed under the joins node. Feel free to submit a PR with external links covering these topics.
