### ISSUE TITLE
API keys from other providers and local generation? 

### ISSUE THREAD

**Issue by salgadev** [kamranahmedse/developer-roadmap#5900]
### Feature Description

First off, I want to compliment Kamran and the contributors on making an awesome app.
I'd like to know if it's possible to use other API keys, such as but not limited to groq, together.ai, cohere and local ollama. I think there is a valuable use case for users or organizations who want to generate super customized roadmaps or without spending months of research.

**Comment by dansholds** [comment]
Hey @salgadev that's an awesome idea!

It's not something that we're going to focus on atm as we (Kamran & Arik) are currently focused on the new editor and other awesome features! I'll add this to our internal roadmap (the roadmap that builds roadmap 😅).

Feel free to join our Discord community if you haven't already to be kept up to date with all new releases and features!

**Comment by salgadev** [comment]
Sounds good! I think openai-like API's should be pretty easy to add, as far
as I know the only difference is the endpoint. Thanks for following up
