### ISSUE TITLE
Missing in State management 

### ISSUE THREAD

**Issue by Yagnik13** [kamranahmedse/developer-roadmap#5901]
### Roadmap URL

https://roadmap.sh/flutter

### Suggestions

**MobX** is a popular **state management** technique used in Flutter development.

**Comment by dansholds** [comment]
@Yagnik13 thanks for taking the time to submit this!

The point is to use these tools to give the user/reader an overview of what the topic is, not to show them all the options that they have, the tools are used as learning instruments to teach state management.
