### ISSUE TITLE
Add Heap in Data Structures and Algorithms Roadmap

### ISSUE THREAD

**Issue by VasanthTulasi** [kamranahmedse/developer-roadmap#5905]
### Roadmap URL

https://roadmap.sh/datastructures-and-algorithms

### Suggestions

It would be great if we could add Heap in here too. Currently, we only have Heap Sort but it is not mentioned as a separate topic. It's one of the crucial data structures which might even be useful for interviews and people might miss out on this if it is not mentioned. Thanks!

**Comment by dansholds** [comment]
Hey @VasanthTulasi we are currently going through all roadmaps and adding them to the new editor system, so I'll add this to our internal tracker 😄

**Comment by VasanthTulasi** [comment]
Great, thanks!
