### ISSUE TITLE
create-react-app not is recommend now

### ISSUE THREAD

**Issue by zenx5** [kamranahmedse/developer-roadmap#5909]
### Roadmap URL

https://roadmap.sh/react

### Suggestions

**create-react-app not is recommend** in the current version of React or in the next version (19).
However, in the roadmap has the check that as optional method. 

Currenly React recommend use one Framework as Nextjs, Gasby, or Remix. And as optional method recommend use Vite or Parcel

[https://react.dev/learn/start-a-new-react-project#can-i-use-react-without-a-framework](https://react.dev/learn/start-a-new-react-project#can-i-use-react-without-a-framework)
[https://19.react.dev/learn/start-a-new-react-project#can-i-use-react-without-a-framework](https://19.react.dev/learn/start-a-new-react-project#can-i-use-react-without-a-framework)

![image](https://github.com/kamranahmedse/developer-roadmap/assets/26119733/4ec5afd3-b218-4969-bb1b-135086acd531)

**Comment by dansholds** [comment]
While that is true, create-react-app is not depreciated and is still the React recommended method if you're not using a framework, and since this specific roadmap for learning React, it's important that people learn React itself without depending on frameworks.

Feel free to open a PR to add some copy or content links if you feel like it's important.

**Comment by zenx5** [comment]
i think that the recommend method for create a new project without Framework is: **Vite o Parcel**.
In the old documentation (legacy), React recommend create-react-app and they have a article about it, but in the new official documentation is not been.

Maybe you want read the [issue](https://github.com/reactjs/react.dev/pull/5487)

in legacy: https://legacy.reactjs.org/docs/create-a-new-react-app.html#create-react-app
in current: ???

Thanks for your time, and for the roadmaps, is cool

**Comment by JusticeMatthew** [comment]
I just reopened an issue for this before finding this one however, the react docs do specifically state if you want to create a new project without a UI framework or add React to an existing project you are to install `react` and `react-dom` with your chosen package manager. 

CRA is no where to be found from what I saw 🤔

**Comment by zenx5** [comment]
I think the same way, and I tried to explain it but I think that they didn't understand my explainess.

In the current documentation not appear any reference to **CRA**
