### ISSUE TITLE
Add Qase as a tool for test case management

### ISSUE THREAD

**Issue by samelawrence** [kamranahmedse/developer-roadmap#5911]
### Roadmap URL

https://roadmap.sh/qa

### Suggestions

Under the section "Manage your testing" - there are entries for qTest, TestRail, TestLink, and Zephyr. I would suggest adding Qase. Our team switched from TestRail to Qase and we are very happy with our choice. It's a great tool that works well for us, and I think would work for more QA teams. https://qase.io/

**Comment by dansholds** [comment]
Hey @samelawrence thanks for taking the time to create this ticket!

We're currently migrating our roadmaps to a new editor so won't be adding any extra topics to existing ones until this is complete.

We also don't really want to add too many tools to the roadmaps as if we open the flood gate we would be inundated with requests to add every tool!

What I suggest is that you open a PR against the "Manage your testing" topic and add a link to Qase 😄 That way, everyone wins!
