### ISSUE TITLE
Vim for Developers [Roadmap]

### ISSUE THREAD

**Issue by krishmakhijani** [kamranahmedse/developer-roadmap#5912]
### What is the title of the roadmap you are submitting?

Vim for Developers

### Roadmap Link

- Introduction
	- What’s Vim
	- Vim Bindings
	- Vimrc File Configuration
- Lua
	- Variables and Data
	- Conditionals & Logic
	- Functions
	- Loops
	- Error handling
- Neovim
	- File Structure
	- Keymaps Config
	- Option Config
- Neovim Plugin Manager
	- LazyVim
	- Packer
- Neovim Plugins
	- Telescope
	- treesitter
	- Lspconfig
	- Mason
	- NvimDap
- Neovim Pre-Config Distros
	- NvChad
	- LazyVim
	- LunarVim
	- AstroVim
- Tmux
	- Tmux.conf
	- Tmux Scripting
- Bonus
	- ZSH Config
	- Starship
	- Fish Shell
	- FZF

**Comment by krishmakhijani** [comment]
I think this is the best roadmap for those who really want to get into vim or neovim . I am linux user for past 8 years and a vim user for past 5 years and I think this is a best roadmap for the people

**Comment by krishmakhijani** [comment]
@kamranahmedse Shell make a PR for this roadmap ?

**Comment by dansholds** [comment]
Hey @krishmakhijani thanks for taking the time to do this but it's not really in line with the type of roadmap we do, we're not saying no outright, it's possible we will do _something_ for Vim in the future but the content that you've suggested is not befitting of a roadmap.sh roadmap.
