### ISSUE TITLE
Wrong articles on internet section of backend developer roadmap

### ISSUE THREAD

**Issue by laraib07** [kamranahmedse/developer-roadmap#5918]
### What is the URL where the issue is happening

https://roadmap.sh/backend

### What browsers are you seeing the problem on?

Chrome

### Describe the Bug

In the "Internet" section of backend developer roadmap:

- Domain name opens browsers article
- hosting opens DNS 
- DNS opens domain name
- browser opens hosting

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by kamranahmedse** [comment]
Fixed in https://github.com/kamranahmedse/developer-roadmap/commit/f682a6e1a2882da483f8733314659d842c89bc7b. Thank you!
