### ISSUE TITLE
Button to reset all topics in progress

### ISSUE THREAD

**Issue by issdomingoss** [kamranahmedse/developer-roadmap#5919]
### Feature Description

Button to reset all topics in progress. Like a RIGHT MOUSE CLICK.

**Comment by AbdallahEssamGaber** [comment]
I think you can do so by going to https://roadmap.sh/ and following the steps in the image.
![image](https://github.com/kamranahmedse/developer-roadmap/assets/70752242/f614caa3-a4c2-4e10-afb8-ca24382145a6)

**Comment by dansholds** [comment]
Exactly as @AbdallahEssamGaber said 😄
