### ISSUE TITLE
Frontend Roadmap - Remove Semantic UI

### ISSUE THREAD

**Issue by ux-engineer** [kamranahmedse/developer-roadmap#592]
Semantic UI should be removed from the roadmap as this package seems to be drying off...

I used to use it in some projects, but just lately looked at updating it...instead I will be replacing it with some other option:

https://github.com/Semantic-Org/Semantic-UI/graphs/code-frequency
https://github.com/Semantic-Org/Semantic-UI/pulse/monthly

I'm experienced with Bootstrap for 5 years. Lately, I've used AntDesign and Bulma. AntDesign is lacking in English docs but is advancing fast. Bulma doesn't support IE11 which could be a major issue for your client!

Tachyons is looking solid: https://github.com/tachyons-css/tachyons

**Comment by kamranahmedse** [comment]
There have been changes made to that section which makes this issue outdated. Thank you for reporting though 🙏
