### ISSUE TITLE
add traefik and HA-proxy to devops

### ISSUE THREAD

**Issue by PejmanCommits** [kamranahmedse/developer-roadmap#5923]
### Roadmap URL

https://roadmap.sh/devops

### Suggestions

as the need of todays devops positions, please add traefik and HA-proxy in the related sections.

**Comment by dansholds** [comment]
@PejmanCommits Thanks for the suggestion, these are both alternative and optional tools to use for proxies, feel free to open a PR to add links to them in one of the two proxy topics 😄
