### ISSUE TITLE
Add links to learn the basics of programming languages

### ISSUE THREAD

**Issue by fey** [kamranahmedse/developer-roadmap#5925]
### Feature Description

Hi. Thanks for the cool and helpful resource. We have an opensource free project where you can learn the basics of programming. Maybe we could find common ground for general collaboration? For example in PHP, Python, JS we can add links to lessons (https://code-basics.com/languages/python for example, no registration required).

According to Code of Conduct this is possible if you add a link with `@course@` type, am I right? 

Translated with DeepL.com (free version)

**Comment by dansholds** [comment]
Hey @fey do you have discord or twitter? Lets talk!

**Comment by fey** [comment]
Hello, @dansholds. Yes, i have https://x.com/feycot
discord - `feycot`

**Comment by dansholds** [comment]
@fey Awesome, I'll reach out today.

**Comment by fey** [comment]
@dansholds Hi, I didn't get your message. You can message me on Discord, I'm there regularly.

**Comment by Eduardo77117711** [comment]
obrigado
