### ISSUE TITLE
Navigate to wrong description link

### ISSUE THREAD

**Issue by DivyarajsinhRana** [kamranahmedse/developer-roadmap#5938]
### What is the URL where the issue is happening

https://roadmap.sh/backend

### What browsers are you seeing the problem on?

Chrome

### Describe the Bug

In backend road map first point is Internet, So In internet when i click on topics it opens wrong drawer for  description of topics.
Consider following cases
1. For What is Domain Name It opens Browsers .
2. For What is Hosting it opens DNS
3. For DNS it opens Domain Name and
4. For  Browsers it  opens Hosting.

https://github.com/kamranahmedse/developer-roadmap/assets/93385663/825060ae-252d-4a19-94d8-0f301c6f0107

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by dansholds** [comment]
Thanks for raising this @DivyarajsinhRana I'll fix it today ☺️

**Comment by dansholds** [comment]
This has been fixed but not deployed yet.
