### ISSUE TITLE
Java : Missing virtual threads

### ISSUE THREAD

**Issue by leni-kirilov** [kamranahmedse/developer-roadmap#5946]
### Roadmap URL

https://roadmap.sh/java

### Suggestions

https://blogs.oracle.com/javamagazine/post/virtual-threads-futures
https://openjdk.org/jeps/444

**Comment by kamranahmedse** [comment]
Thank you for reporting @leni-kirilov -- we have considerably revamped the Java roadmap. This has been addressed in the coming release. Stay tuned for the new Java roadmap this week.
