### ISSUE TITLE
Incorrect spelling of "Trees" in the computer science roadmap

### ISSUE THREAD

**Issue by cosmolightfoot** [kamranahmedse/developer-roadmap#5952]
### Roadmap URL

https://roadmap.sh/computer-science

### Suggestions

Trees is misspelled as "Tries"

<img width="387" alt="Screenshot 2024-06-26 at 6 40 03 PM" src="https://github.com/kamranahmedse/developer-roadmap/assets/46037490/fc62c506-4327-46c0-a88a-5c141ce0e8b8">

**Comment by dansholds** [comment]
@cosmolightfoot This is actually correct as it refers to data structures used to store strings (note it's not connected to the subtopics of "Balanced Search Trees".
