### ISSUE TITLE
Cannot Add Content

### ISSUE THREAD

**Issue by Steamroller-Pipeline-Supervisor** [kamranahmedse/developer-roadmap#5953]
### What is the URL where the issue is happening

https://roadmap.sh/r/pipeline-td

### What browsers are you seeing the problem on?

Chrome

### Describe the Bug

I can't seem to add content to any of the nodes, when I do and save it does not save.
Creating new nodes seems to work fine, but any content added to any node does not save.

There are no errors or warning, just can't save content.

Create node -> Add content -> Save Roadmap

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by dansholds** [comment]
Hey @Steamroller-Pipeline-Supervisor thanks for reporting this, I can't seem to replicate this as you've described, can you check my screen recording and let me know if it matches your behaviour?

https://github.com/kamranahmedse/developer-roadmap/assets/25537601/fbff121b-bbf7-4cf1-85c2-3e2f926c9285

**Comment by dansholds** [comment]
Closing due to no response to issue or email, feel free to re-open is issue persists.

**Comment by ahofmeister** [comment]
We have kind of the same problem. 

We create content and a link, save it and all works. We reopen the roadmap, open the content and links sections, edit the content, click on Live View and the content is lost.
