### ISSUE TITLE
Allow cloning of existing roadmaps

### ISSUE THREAD

**Issue by LukeBallantine** [kamranahmedse/developer-roadmap#5954]
### Feature Description

I love the feature that allows you to create your own roadmaps when you have an account. 
What would be amazing is allowing users to clone an existing roadmap and make tweaks to it. 
This would be great for teams that want to take an existing roadmap (eg. Frontend) and remove parts that might not be applicable to their toolstack, and maybe add a few additional things. 

roadmap.sh is amazing. I love this site :)

**Comment by dansholds** [comment]
Hey, @LukeBallantine Thanks for taking the time to raise this!

We are currently in the process of moving _all_ roadmaps to the new editor system, but with new roadmaps such as Product Manager, iOS, and Terraform, you can do this via the teams' feature (see my video!)

Is this what you meant?


https://github.com/kamranahmedse/developer-roadmap/assets/25537601/b179bb73-8e52-43fd-b2c0-bf7ae3eebe80

**Comment by dansholds** [comment]
Feel free to re-open if this isn't what you want 😄

**Comment by guiwb** [comment]
@dansholds, I was playing with the functionality, and I noticed that the clone doesn't keep the description and links of the cards, is there any way to preserve this information?
