### ISSUE TITLE
Missing state managers like Redux, Mobx, Zustand etc.

### ISSUE THREAD

**Issue by backr1** [kamranahmedse/developer-roadmap#5955]
### Roadmap URL

https://roadmap.sh/frontend

### Suggestions

Please add state managers as being important part of actual FE stack, thanks!

**Comment by kamranahmedse** [comment]
Frontend roadmap doesn't focus on one framework and we didn't want to convolute it by mentioning all the state management solutions for all the frameworks. These are mentioned on the react roadmap though.
