### ISSUE TITLE
More Detailed Syllabus in dropdowns

### ISSUE THREAD

**Issue by roneya** [kamranahmedse/developer-roadmap#5959]
### Feature Description

https://roadmap.sh/ai-data-scientist
In this road map we can have more detailed syllabus of Hypothesis testing: All types of test T test, F test etc. Because this field is not directly related with computer science and will help ppl to study more accurately.

**Comment by dansholds** [comment]
Hey @roneya feel free to submit another issue detailing what you would like/think should be added and we will review it and consider it 😄
