### ISSUE TITLE
There is a problem with the Discord link invitation.

### ISSUE THREAD

**Issue by whoismtrx** [kamranahmedse/developer-roadmap#5965]
### Detailed Description

When attempting to join the Discord server using the buttons on the new issue template, I encountered an issue. After being redirected to Discord, clicking the join button resulted in the error message: 'Whoops... Unable to accept invite'."

https://github.com/kamranahmedse/developer-roadmap/assets/94763545/83525f5e-3ae9-47c9-9014-08e27774ae74

**Comment by dansholds** [comment]
@whoismtrx try again

**Comment by whoismtrx** [comment]
It's working
