### ISSUE TITLE
Add new videos on Higher-Order Components (HOCs) to the React Roadmap

### ISSUE THREAD

**Issue by FarzadMohtasham** [kamranahmedse/developer-roadmap#5968]
### Roadmap URL

https://roadmap.sh/react

### Suggestions

In the React roadmap, I suggest replacing the video [Learn React Higher Order Component (HOC) in 10 Minutes](https://youtu.be/J5P0q7EROfw?si=-8s5h1b0mZSGVgLt) with the following three videos:

[ReactJS Tutorial - 34 - Higher Order Components (Part 1)](https://www.youtube.com/watch?v=B6aNv8nkUSw)
[ReactJS Tutorial - 34 - Higher Order Components (Part 2)](https://www.youtube.com/watch?v=rsBQj6X7UK8)
[ReactJS Tutorial - 34 - Higher Order Components (Part 3)](https://www.youtube.com/watch?v=l8V59zIdBXU)
These three videos provide a clearer and more comprehensive explanation, making them more useful overall.

![image_2024-06-29_21-09-39](https://github.com/kamranahmedse/developer-roadmap/assets/48632860/9af12464-f465-4700-973c-92ee910bded7)

**Comment by dansholds** [comment]
Open a PR to add these to the roadmap, please ref our contribution guide when doing so to ensure correct formatting!

https://github.com/kamranahmedse/developer-roadmap/blob/master/contributing.md
