### ISSUE TITLE
Add viem to the blockchain dApp libraries

### ISSUE THREAD

**Issue by BANOnotIT** [kamranahmedse/developer-roadmap#5975]
### Roadmap URL

https://roadmap.sh/blockchain

### Suggestions

viem.sh is a great library with subjectively better DX then ethers and much smallar foorprint on bundle size.

**Comment by dansholds** [comment]
We're not adding new topics and subtopics to existing roadmap atm until the migration from the old editor the new one is complete, in the mean time I suggest you open a PR adding a link to viem either in the `Client Libraries` topic or even in the ethers.js sub-topic if you believe it's a close alternative to it.
