### ISSUE TITLE
Change order of oracles and smart contracts in blockchain roadmap

### ISSUE THREAD

**Issue by BANOnotIT** [kamranahmedse/developer-roadmap#5976]
### What is the title of the roadmap you are submitting?

https://roadmap.sh/blockchain

### Roadmap Link

Oracles as a topic are heavily influenced by smart contract limitations. There's no point in learning oracles before smart contracts since every resource will mention smart contracts anyway.

**Comment by dansholds** [comment]
Given the sheer size of the smart-contract section on the roadmap this wouldn't be feasible and would require a complete re-design of the roadmap. 

Feel free to submit a PR adding copy to the main topic in Oracles where you suggest they learn Smart Search first.
