### ISSUE TITLE
The maps are not being updated on the dashboard

### ISSUE THREAD

**Issue by VisShon** [kamranahmedse/developer-roadmap#5977]
### What is the URL where the issue is happening

https://roadmap.sh/

### What browsers are you seeing the problem on?

Chrome

### Describe the Bug

I have completed api design roadmap but on the dashboard the progress shown is 0

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by VisShon** [comment]
<img width="871" alt="Screenshot 2024-06-30 at 6 15 14 AM" src="https://github.com/kamranahmedse/developer-roadmap/assets/88622653/dcd89bb3-68e0-4584-96be-8fbb583c900d">
Here as you can see api design progress is 0 but I have completed the roadmap
<img width="1163" alt="Screenshot 2024-06-30 at 6 15 50 AM" src="https://github.com/kamranahmedse/developer-roadmap/assets/88622653/9ae33e84-7a30-4cdd-b9c6-e9cad2f6fddc">

**Comment by kamranahmedse** [comment]
This has been fixed. Thank you for reporting.
