### ISSUE TITLE
Port Numbers in network protocols

### ISSUE THREAD

**Issue by DevangRaul** [kamranahmedse/developer-roadmap#5978]
### Roadmap URL

https://roadmap.sh/cyber-security

### Suggestions

Port numbers should be added in the network protocol section like port 20 and 21 is used for ftp and etc.

**Comment by dansholds** [comment]
Open a PR adding the ports to the protocols listed please.

If you're unsure how, please reference our contribution guide: https://github.com/kamranahmedse/developer-roadmap/blob/master/contributing.md
