### ISSUE TITLE
Add Web Designer roadmap

### ISSUE THREAD

**Issue by edwincelini** [kamranahmedse/developer-roadmap#598]

**Comment by mirorauhala** [comment]
Why limit to only web design? There are a lot of designers for mobile apps and desktop apps as well. Maybe design in general. A lot of design stuff overlaps no matter the device you design for.

**Comment by edwincelini** [comment]
There isn’t limit, web design is about desktop and mobile too.

**Comment by cryptographicfool** [comment]
User interface and user experience designer would be a better term to use perhaps? However I think it might be beyond the scope of the dev roadmap and would require a separate repo/document of itself.

**Comment by Ronkiro** [comment]
> User interface and user experience designer would be a better term to use perhaps? However I think it might be beyond the scope of the dev roadmap and would require a separate repo/document of itself.

Agreed, anyone with a better design knowledge should start it.
I volunteer myself to be a collaborator, but i have no much knowledge about designing, except what i learnt inside the dev world.

**Comment by ramtinazimi** [comment]
Someone has already created a roadmap for this:
https://github.com/togiberlin/ui-ux-designer-roadmap
Maybe he can be asked for permission to copy his roadmap and add it to the
repository.



<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Virenfrei.
www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

**Comment by cryptographicfool** [comment]
> Someone has already created a roadmap for this: https://github.com/togiberlin/ui-ux-designer-roadmap Maybe he can be asked for permission to copy his roadmap and add it to the repository.

Thanks for sharing. That seems like a pretty solid resource. I studied design a while back(did not specialize in ux/ui though) and a everything they have on there is spot on.

That repository needs to be more popular.
