### ISSUE TITLE
Add Argon2 to the Backend Roadmap

### ISSUE THREAD

**Issue by david-slatinek** [kamranahmedse/developer-roadmap#5980]
### Roadmap URL

https://roadmap.sh/backend

### Suggestions

[Argon2](https://github.com/P-H-C/phc-winner-argon2) is a secure password hashing algorithm recommended by [OWASP](https://cheatsheetseries.owasp.org/cheatsheets/Password_Storage_Cheat_Sheet.html). It is also a winner of the [Password Hashing Competition](https://www.password-hashing.net/).

I propose integrating Argon2 into the project for enhanced password security.

Further references:
- [Wikipedia](https://en.wikipedia.org/wiki/Argon2)
- [RFC](https://datatracker.ietf.org/doc/html/rfc9106)

**Comment by dansholds** [comment]
Feel free to open a PR adding a link to Argon2 in the Web Security topic.

If you're unsure how, please ref this guide - https://github.com/kamranahmedse/developer-roadmap/blob/master/contributing.md
