### ISSUE TITLE
Article to understand 3 Trees and Keys in Flutter

### ISSUE THREAD

**Issue by MJ04-20** [kamranahmedse/developer-roadmap#5987]
### Feature Description

In the Flutter Developer Roadmap we see no resource for the topic - 3 Trees.
I'd like to submit an article to be put in here. 
Link - [Flutter Internals](https://medium.com/@subroto.2003/a-guide-to-flutter-internals-ce8d64d01c50)
I request you to check it. The article received a very warm response from both beginners and experienced flutter devs, I believe this can be helpful for anyone starting out with flutter.
@kamranahmedse

**Comment by dansholds** [comment]
Article looks great, please submit this as a PR.
