### ISSUE TITLE
A changing must be made underneath of the Data Visualization

### ISSUE THREAD

**Issue by AmiraliToori** [kamranahmedse/developer-roadmap#5988]
### Roadmap URL

https://roadmap.sh/data-analyst

### Suggestions

ggplot2 is not a Python library and is a R package for Data visualization, the place of `ggplot2` must have been changed to another subcategory such as 'R libraries'.

![image](https://github.com/kamranahmedse/developer-roadmap/assets/103496001/85947953-7761-4b0f-935a-6d09bb0a8cfa)

**Comment by dansholds** [comment]
@AmiraliToori this is now resolved, the libraries listed are now longer listed as specific language libs
<img width="331" alt="Screenshot 2024-07-08 at 10 29 24" src="https://github.com/kamranahmedse/developer-roadmap/assets/25537601/e9d76f96-0b2f-4ce6-8d6c-e6b6d52d673a">
