### ISSUE TITLE
Frontend - add state management

### ISSUE THREAD

**Issue by fahrulalwan** [kamranahmedse/developer-roadmap#599]
as far as i know, some other state management for angular are good to learn tho. they based on **ngrx** they are:

- **NGXS**
- **Akita**

Akita is not only for angular but it can also use in **react** & **vue**.

or, in other hand, maybe you should add new section for learning state management since it quite difficult to learn (IMHO).

**Comment by kamranahmedse** [comment]
Thank you for suggesting but as [mentioned in the contribution docs](https://github.com/kamranahmedse/developer-roadmap/blob/master/contributing.md#guidelines) we can't add that.
