### ISSUE TITLE
Button unclickable

### ISSUE THREAD

**Issue by wmorgue** [kamranahmedse/developer-roadmap#5991]
### What is the URL where the issue is happening

Private roadmap

### What browsers are you seeing the problem on?

Safari

### Describe the Bug

Button with content & links unclickable. Can't see a content inside button and sometimes button just disappear 🫠
For example, Topic node is clickable.

https://github.com/kamranahmedse/developer-roadmap/assets/24982084/232cfe15-79d0-47e0-b3ee-7f1b85b373dd

### Participation

- [X] I am willing to submit a pull request for this issue.

**Comment by wmorgue** [comment]
Console is empty, nothing to see.

**Comment by dansholds** [comment]
Can you share a link to the roadmap please @wmorgue

**Comment by wmorgue** [comment]
@dansholds link — https://roadmap.sh/r?id=667d14eb2028c2d8189ac8de

Try with `Layout fundamentals`, both of them.

<img width="507" alt="Screenshot 2024-07-01 at 13 46 08" src="https://github.com/kamranahmedse/developer-roadmap/assets/24982084/73843c81-425c-47c9-ba4e-0b6b35782e7c">

**Comment by arikchakma** [comment]
Ah, that's a mistake, you shouldn't add content and links inside a button. For content, you have to use a topic node or subtopic node. Button is for external links!
