### ISSUE TITLE
Need project management tools 

### ISSUE THREAD

**Issue by mehmetsoylucom** [kamranahmedse/developer-roadmap#6]
Pretty good repo. I have some ideas.

Maps need for project management tools. Redmine, Jira, Trello etc. 

I think you can split framework for project sizes. Silex and sinatra for small or Symfony/Rails for large environment frameworks. 

You can add crystal-lang for ruby side. 

System management node will be good. Monitoring ( nagios), profiling,  cloud systems ( openstack )...

Take care...

**Comment by Thithi32** [comment]
+1

**Comment by kamranahmedse** [comment]
Project management tools, I don't think one needs to learn them specifically. And adding them to "developer roadmap" will just convolute it. For the rest of stuff, I added some stuff except crsytal lang, sinatra which will be added in next release.

Thank you.
