### ISSUE TITLE
Let's create a roadmap for game developers

### ISSUE THREAD

**Issue by hellpirat** [kamranahmedse/developer-roadmap#60]
I think its will be interesting :)

**Comment by theanatar** [comment]
YES!!! YES!!! YES!!!

**Comment by AffanIndo** [comment]
I think this repository is for core web development.. If you want to create something off-topic, I suggest you create a new repository

**Comment by ValentinNikolaev** [comment]
https://github.com/miloyip/game-programmer

**Comment by kamranahmedse** [comment]
Feel free to create a PR if anyone is up for it. But the repository focuses on "web developer", so closing it for being irrelevant.

Thanks though.
