### ISSUE TITLE
Add essential Python concepts and tools to roadmap

### ISSUE THREAD

**Issue by GuilhermeCAz** [kamranahmedse/developer-roadmap#6002]
### Roadmap URL

https://roadmap.sh/python

### Suggestions

Python Developer roadmap is lacking key concepts and tools. I made a list of a few of them which, in my opinion, should be known by all python developers, i.e. I think they belong in the Python Developer roadmap instead of Role-based roadmaps.

### Project Configuration and Dependency Management
- [pyproject.toml file](https://packaging.python.org/en/latest/guides/writing-pyproject-toml/)
- [pipenv](https://pipenv.pypa.io/en/latest/)
- [virtualenv](https://virtualenv.pypa.io/en/latest/)
- [pyenv](https://github.com/pyenv/pyenv)
- [uv](https://github.com/astral-sh/uv)

### Static Typing
- [pep 484 - type hints](https://peps.python.org/pep-0484/)
- [static typing with python](https://typing.readthedocs.io/en/latest/index.html)
- [pydantic](https://docs.pydantic.dev/latest/)

### Type Checkers
- [mypy](https://mypy-lang.org/)
- [pyright](https://microsoft.github.io/pyright/)
- [pyre](https://pyre-check.org/)

### Code Formatting
- [ruff](https://docs.astral.sh/ruff/)
- [black](https://black.readthedocs.io/en/stable/)
- [yapf](https://github.com/google/yapf)

### Documentation
- [sphinx](https://www.sphinx-doc.org/en/master/)

### Testing
- [tox](https://tox.wiki/en/)

### Other
Some important modules might also deserve a subtopic. Here are a few:
- [requests](https://docs.python-requests.org/en/latest/)
- [pathlib](https://docs.python.org/3/library/pathlib.html)
- [asyncio](https://docs.python.org/3/library/asyncio.html)
- [typing](https://docs.python.org/3/library/typing.html)
- [dataclasses](https://docs.python.org/3/library/dataclasses.html)
- [python-dotenv](https://pypi.org/project/python-dotenv/)
- [numpy](https://numpy.org/doc/stable/)
- [pandas](https://pandas.pydata.org/docs/) vs [polars](https://github.com/pola-rs/polars)

**Comment by kamranahmedse** [comment]
New version of the Python roadmap is live. Let us know if you have any feedback. Thank you!
