### ISSUE TITLE
Cannot save roadmaps

### ISSUE THREAD

**Issue by abdadhim** [kamranahmedse/developer-roadmap#6005]
### What is the URL where the issue is happening

https://roadmap.sh/

### Describe the Bug

When I tried to click the Bookmark symbol on [Roadmap.sh](https://roadmap.sh/) or [API Design](https://roadmap.sh/api-design), it always showed the message "failed to update favorite status" at the bottom. For some reason, it only works for [Backend Developer Roadmap](https://roadmap.sh/backend).

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by dansholds** [comment]
Confirmed, I can un-save and re-save already saved roadmaps but not ones I have not saved before.

@arikchakma any thoughts?

<img width="874" alt="Screenshot 2024-07-02 at 09 03 47" src="https://github.com/kamranahmedse/developer-roadmap/assets/25537601/0045b6c6-ff5e-47ab-989f-9487b007c598">

**Comment by arikchakma** [comment]
Let me have a look

**Comment by arikchakma** [comment]
I have create a PR in the API for the fix, it will resolve this issue.
