### ISSUE TITLE
Center Text on Roadmaps Elements to improve readability.

### ISSUE THREAD

**Issue by KremaKanaria** [kamranahmedse/developer-roadmap#6012]
### Detailed Description

When any concept in a Roadmap is open: There is only the option to read the information at the right side of the screen, I think it's better to center that, maybe a centered pop-up or maybe just to give the option to change it.

Thank you for this cool tool.

![image](https://github.com/kamranahmedse/developer-roadmap/assets/70713726/d69db90c-ec41-4920-9f7d-5eaa9e11ac43)

**Comment by dansholds** [comment]
@KremaKanaria this is an interesting concept, we will discuss it internally.

Which such a small team items like this as "luxury" items that realistically won't be tackled for a while, so feel free to join our discord at https://roadmap.sh/discord to keep up to date with new features!

**Comment by KremaKanaria** [comment]
thank you for taking it into account!
