### ISSUE TITLE
GOF Design Patterns - Topic Not Found - Backend Roadmap

### ISSUE THREAD

**Issue by NemesisLW** [kamranahmedse/developer-roadmap#6016]
### Roadmap URL

https://roadmap.sh/backend

### Suggestions

The GoF (Gang of Four) Design Patterns are a collection of 23 fundamental software design patterns that provide solutions to common problems in object-oriented programming. These patterns, first published in 1994 by Erich Gamma, Richard Helm, Ralph Johnson, and John Vlissides, have become a cornerstone of software development.

The patterns are organized into three categories:

- Creational Patterns (e.g., Singleton, Factory)
- Structural Patterns (e.g., Adapter, Bridge)
- Behavioral Patterns (e.g., Observer, Strategy)

GoF Design Patterns promote flexible, maintainable, and scalable software design by providing proven solutions to common challenges in software development. Understanding these patterns is essential for any backend developer or software architect.

Visit the following resources to learn more:
[@opensource@Design Patterns for Humans](https://github.com/kamranahmedse/design-patterns-for-humans)
[@article@GOF design patterns](https://springframework.guru/gang-of-four-design-patterns/)
[@article@Design Patterns](https://refactoring.guru/design-patterns)

**Comment by NemesisLW** [comment]
Found a typo in the naming markdown containing the `GOF Design Patterns`. Created #6017 to fix this issue.

**Comment by dansholds** [comment]
**GOF** is present in multiple locations already

**Comp Sci** - https://github.com/kamranahmedse/developer-roadmap/blob/72cc28a4363290b9a72475365e1daabf81819ecf/src/data/roadmaps/computer-science/content/111-design-patterns/100-gof-design-patterns.md?plain=1

**Backend** - https://github.com/kamranahmedse/developer-roadmap/blob/72cc28a4363290b9a72475365e1daabf81819ecf/src/data/roadmaps/backend/content/god-design-patterns%406XIWO0MoE-ySl4qh_ihXa.md?plain=1#L10

**Design Patterns for Humans Guide** - https://github.com/kamranahmedse/developer-roadmap/blob/72cc28a4363290b9a72475365e1daabf81819ecf/src/data/guides/design-patterns-for-humans.md?plain=1#L26

**Software Architect** - https://github.com/kamranahmedse/developer-roadmap/blob/72cc28a4363290b9a72475365e1daabf81819ecf/src/data/roadmaps/software-architect/content/102-important-skills/100-design-and-architecture.md?plain=1#L3

**Software Design Architecture** - https://github.com/kamranahmedse/developer-roadmap/blob/72cc28a4363290b9a72475365e1daabf81819ecf/src/data/roadmaps/software-design-architecture/content/104-design-patterns/100-gof-design-patterns.md?plain=1

**Comment by dansholds** [comment]
@NemesisLW I see that you're saying the content was not found due to a typo in the md file.

We'll fix that.
