### ISSUE TITLE
New Language Suggestion

### ISSUE THREAD

**Issue by T4RUNN4** [kamranahmedse/developer-roadmap#6019]
### Roadmap URL

https://roadmap.sh/cyber-security

### Suggestions

The roadmap is awesome. But if you could add "Bash" language in the map it would be more great I think.

**Comment by dansholds** [comment]
Bash is at the bottom of the roadmap in the "Programming Skill & Knowledge" topic.

Even though technically Bash is not a programming language but a Command Language ☝️🤓 

<img width="740" alt="Screenshot 2024-07-03 at 14 16 39" src="https://github.com/kamranahmedse/developer-roadmap/assets/25537601/7ea1c88d-a056-4187-8234-8dff23e4ffbd">

**Comment by T4RUNN4** [comment]
Nice! It didn't show mine due to a screen size issue 🤧
