### ISSUE TITLE
Topic not found for Solr in backend roadmap

### ISSUE THREAD

**Issue by AlexPetul** [kamranahmedse/developer-roadmap#6033]
### What is the URL where the issue is happening

https://roadmap.sh/backend

### What browsers are you seeing the problem on?

Firefox, Chrome, Safari, Microsoft Edge

### Describe the Bug

When I click on Solr I get an error "Topic not found"

### Output from browser console (if any)

Request: https://roadmap.sh/backend/solr@iN_1EuIwCx_7lRBw1Io4U
Response: 404

However, on github I can see this file: /src/data/roadmaps/backend/content/**solo@iN_1EuIwCx_7lRBw1Io4U.md** 
Guess that's a typo error :)

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by dansholds** [comment]
@kamranahmedse the Solr node doesn't exist in the `backend.json file`
