### ISSUE TITLE
Add OWASP Top 10

### ISSUE THREAD

**Issue by Pegase745** [kamranahmedse/developer-roadmap#604]
I don't seem to find web apps security risks in the roadmap. WDYT ? 
https://www.owasp.org/index.php/Category:OWASP_Top_Ten_2017_Project

**Comment by Ronkiro** [comment]
I don't think front end area is a good place for this, but for sure security frameworks MUST be quoted at the "ANY"s place. As it's fundamental for any developer.

**Comment by kamranahmedse** [comment]
This has been fixed and will be published in the coming release. Thank you!
