### ISSUE TITLE
Backend: no experience in UI at the "9. Practical Time"

### ISSUE THREAD

**Issue by sur0g** [kamranahmedse/developer-roadmap#606]
I'm currently trying to develop a personal roadmap for a trainee. So I came to the issue when the roadmap suggests us to make a blog with registration etc. The problem is that at this point we don't have expirience in UI at all. All we know is CLI. 
I suggest adding some brief frontend requirements to the [Introduction](https://github.com/kamranahmedse/developer-roadmap#introduction) section. Any thoughts?

**Comment by kamranahmedse** [comment]
This has been fixed and will be published in the coming release. Thank you 🙏
