### ISSUE TITLE
Case Studies in Positioning for Product Managers

### ISSUE THREAD

**Issue by anjanpandey** [kamranahmedse/developer-roadmap#6074]
### What is the URL where the issue is happening

https://roadmap.sh/product-manager

### What browsers are you seeing the problem on?

Safari

### Describe the Bug

Open the 'Product Manager' roadmap
Click on 'Case Studies' under 'Defining & Communicating,' which should open a right-side menu 
Click on 'Youtube' to further explore the topic, which opens a youtube on a new tab
**Notice it searches for 'case studies in positioning for product managers for product manager' instead of 'case studies in positioning for product managers'**

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by dansholds** [comment]
will be fixed by https://github.com/kamranahmedse/developer-roadmap/pull/6096
