### ISSUE TITLE
Request to Add 'Pendo' Inside Analytics Tool in 'Product Manager Roadmap'

### ISSUE THREAD

**Issue by anjanpandey** [kamranahmedse/developer-roadmap#6075]
### Feature Description

Pendo is a very popular analytics tool. Several companies have started adopting Pendo for product-led growth.

**Comment by dansholds** [comment]
@anjanpandey despite it being popular we try to stay away from adding content to the roadmap that is not accessible, Pendo appears hidden behind sales calls with no instantly accessible free trial or anything the like.
