### ISSUE TITLE
Amplitude as an Analytical Tool for Product Managers

### ISSUE THREAD

**Issue by anjanpandey** [kamranahmedse/developer-roadmap#6076]
### What is the URL where the issue is happening

https://roadmap.sh/product-manager

### What browsers are you seeing the problem on?

Safari

### Describe the Bug

Open the 'Product Manager' roadmap
Click on 'Amplitude' under 'Analytics Tool,' which should open a right-side menu
Click on 'Youtube' to further explore the topic, which opens a youtube on a new tab
Notice it searches for 'amplitude as an analytical tool for product managers for product manager' instead of 'amplitude as an analytical tool for product managers'

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by dansholds** [comment]
If this is a bug on all topics of the roadmap lets just keep it to one issue.

**Comment by dansholds** [comment]
Will be fixed by - https://github.com/kamranahmedse/developer-roadmap/pull/6096
