### ISSUE TITLE
Request to Make a Roadmap Component a Link in Downloaded PDF Version 

### ISSUE THREAD

**Issue by anjanpandey** [kamranahmedse/developer-roadmap#6077]
### Feature Description

I downloaded a product manager roadmap as a PDF. However, these elements or components are read-only and unclickable. 

To improve the experience, **can we please make each element a clickable link that redirects users to a YouTube video or an article about the topic?**

**Comment by kamranahmedse** [comment]
Duplicate https://github.com/kamranahmedse/developer-roadmap/issues/6092
