### ISSUE TITLE
Improve 'Start Here' or 'Get Started' Experience

### ISSUE THREAD

**Issue by anjanpandey** [kamranahmedse/developer-roadmap#6078]
### Detailed Description

The onboarding experience or start here page should depend on the 'Headline' inside the 'Profile' page. It should prioritize a roadmap related to my headline/role. 

In case the headline is empty, then it should suggest users fill out the headline to see relevant roadmaps. Currently, I have to scroll all the way down to get to the roadmap that is relevant to my role.  

Users should still have options to explore other roadmaps, but priority should be given to the roadmaps associated with their role.

**Comment by dansholds** [comment]
@anjanpandey we have a potential redesign of the home/landing page on our internal roadmap, so items like this will be solved then 😄 

If you're not already, you can join our Discord to be updated on things like this https://roadmap.sh/discord
