### ISSUE TITLE
Backend or frontend choice vs JavaScript

### ISSUE THREAD

**Issue by andrisi** [kamranahmedse/developer-roadmap#608]
Failing to mention that choosing any other language than JavaScript kills their easy route to full stack development is problematic. Also, Nodejs is not a language.

**Comment by Ronkiro** [comment]
I never noticed this.
Maybe add Javascript/HTML/CSS to "Required for any path"?

**Comment by kamranahmedse** [comment]
This has been fixed and will be published in the coming release. Thank you 🙏
