### ISSUE TITLE
Why there is no DB and Redis in a DevOps roadmap

### ISSUE THREAD

**Issue by EndlessParadox1** [kamranahmedse/developer-roadmap#6084]
### Roadmap URL

https://roadmap.sh/devops

### Suggestions

As I know, every SRE will need knowledge about these

**Comment by kenshanta** [comment]
You can always generate your own custom roadmap with the help of AI.

Here for example i have created my custom [Redis and Node.js roadmap](https://roadmap.sh/r/redis-master-with-nodejs) that im still working on to improve.

**Comment by dansholds** [comment]
Mainly because we have entire roadmaps dedicated to databases.
