### ISSUE TITLE
Adding console.* functions to the Node.js

### ISSUE THREAD

**Issue by AbdallahEssamGaber** [kamranahmedse/developer-roadmap#6085]
### Feature Description

In the Node.js roadmap, within the Command Line Apps node, there is a nested node called Printing Output. This section covers various aspects of outputting information, including the use of `console.*` functions. I propose creating a new node directly following Printing Output to comprehensively explore these essential `console.*` functions. Placing it after the `101-process.stderr` node would provide a logical progression in understanding Node.js output functionalities.

I've already drafted a Markdown file for this proposed node, serving as inspiration:

```
# console Functions

Node.js provides a variety of console functions that are essential for debugging and logging within your applications. These functions allow you to output messages to the terminal, aiding in development and troubleshooting processes. Here are some of the key console functions:
- **console.log**: Outputs a message to the console.
- **console.error**: Outputs an error message to the console.
- **console.warn**: Outputs a warning message to the console.
- **console.info**: Outputs an informational message to the console.
- **console.table**: Displays tabular data as a table.
- **console.time** and **console.timeEnd**: Measures the time taken by a block of code.

Visit the following resources to learn more:

- [@official@Node.js Console](https://nodejs.org/api/console.html)
```

**Comment by dansholds** [comment]
@AbdallahEssamGaber considering that the `Printing Output` is really lacking is copy and any links I would suggest that you open a PR to add this content into that section.

Don't add it word for word but rather adapt it to that section and include the link 👍
