### ISSUE TITLE
Right-clicking the checkbox marks the checkbox as done but doesn't mark the topic as done 

### ISSUE THREAD

**Issue by KawanJ** [kamranahmedse/developer-roadmap#6090]
### What is the URL where the issue is happening

https://roadmap.sh/best-practices/frontend-performance

### What browsers are you seeing the problem on?

Chrome

### Describe the Bug

Right clicking the checkboxes on **_best-practices_** roadmaps only marks the checkbox as done and does not strike off the topic name.

It also doesn't update the progress analytics on the top of the page, it only updates the progress analytics box on the bottom of the page

Ref Image: 
![image](https://github.com/kamranahmedse/developer-roadmap/assets/79013287/f03b2d19-f7b8-4af3-9733-a6243d9fc964)

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by dansholds** [comment]
Interesting, I'm able to "complete" it, but if I start to uncheck and recheck some boxes with right click it'll put me in a weird state where I'm "deleting" my progress 🤔 

What do you think @arikchakma ?

<img width="1018" alt="Screenshot 2024-07-08 at 15 18 34" src="https://github.com/kamranahmedse/developer-roadmap/assets/25537601/ac436fd9-a036-4293-a288-510833b15dbd">
<img width="313" alt="Screenshot 2024-07-08 at 15 18 56" src="https://github.com/kamranahmedse/developer-roadmap/assets/25537601/02f0b412-2964-4fcd-addf-03f7eb2dfe2d">

**Comment by arikchakma** [comment]
Let me have a look

**Comment by dansholds** [comment]
> Let me have a look

Happy to hop on a slack call and show you if it helps 👍

**Comment by arikchakma** [comment]
I have found the issue @dansholds, Thank you for letting me know. I am looking for a fix.
