### ISSUE TITLE
[feat] Downloading a Roadmap should contain all topics for the given Roadmap

### ISSUE THREAD

**Issue by ianmobbs** [kamranahmedse/developer-roadmap#6092]
### Feature Description

For example, when clicking the Roadmap [here](https://roadmap.sh/cpp) - in addition to downloading the roadmap itself, it would be great if the content of each topic was a part of the PDF.

**Comment by kamranahmedse** [comment]
Thank you for the feature request. I am going to add this to our backlog and close it for now as it will require a significant implementation effort and is not one of our top priorities at the moment.
