### ISSUE TITLE
Product Manager Roadmap needs dramatic improvement

### ISSUE THREAD

**Issue by brooksryan** [kamranahmedse/developer-roadmap#6105]
### Roadmap URL

https://roadmap.sh/product-manager

### Suggestions

Critical sections missing:

- Business Management/ Business Strategy Planning
- - needs topics about revenue/cost structure/profit/COGS/CAC
- Technology understanding
- - Needs to understand technically at least at a high level how Frontends/Backends/APIs/Databases work
- - Should be a prereq for product requirements

Other hard skills missing too.

**Comment by dansholds** [comment]
From my experience as a Product Manager, I would say that Business Management/ Business Strategy Planning, revenue/cost structure/profit/COGS/CAC are all on the Project side rather than the Product.

**Comment by dansholds** [comment]
@brooksryan This is a community driven project so I'm more than happy to take your thoughts and implement them into the roadmap 👍

**Comment by aheermohsinse** [comment]
Good, I have shared my initial feedback here: https://github.com/kamranahmedse/developer-roadmap/issues/6110

**Comment by dansholds** [comment]
Closing in favour of the more comprehensive #6110
