### ISSUE TITLE
Generate this Graph from using a Graph ML

### ISSUE THREAD

**Issue by azbarcea** [kamranahmedse/developer-roadmap#612]
See arbor.js for inspiration or a mindmap.

Great idea!

**Comment by Ronkiro** [comment]
I think that's overkill, [for arbor.js] it has nice animation but doesn't shows all the contents at once. For bigger graphs, this may get confusing.

**Comment by azbarcea** [comment]
I understand and agree with you. The idea is to use something, data driven (not UI based) and generate the graph based on that ...

**Comment by s14k51** [comment]
I agree with @Ronkiro arbor.js does not show full info at a glance, but I will leave it up to @kamranahmedse to decide.

**Comment by s14k51** [comment]
Also, you would have to take multiple screenshots (as opposed to a single picture) for one path.

**Comment by kamranahmedse** [comment]
Thank you for the suggestion. I have been working on something that would help me convert these roadmaps to textual form and help the contributions easier. It will probably take sometime but will be released sooner after the 2020 update of the roadmaps. 

![snapper-4](https://user-images.githubusercontent.com/4921183/71748275-6cdd5d80-2e8b-11ea-9c39-b8b5cdea1526.gif)

You can track the progress for this here or on twitter @kamranahmedse 🙏
