### ISSUE TITLE
The pdf download does not match the map on the website.

### ISSUE THREAD

**Issue by icorneli** [kamranahmedse/developer-roadmap#6127]
### What is the URL where the issue is happening

https://roadmap.sh/android

### What browsers are you seeing the problem on?

Other

### Describe the Bug

The pdf download does not match the map on the website.

### Participation

- [X] I am willing to submit a pull request for this issue.

**Comment by kamranahmedse** [comment]
They look different but the content is same. We are in the process of recreating all our roadmaps. This will be tackled once we are done.
