### ISSUE TITLE
React Developer Roadmap recommends create-react-app

### ISSUE THREAD

**Issue by JusticeMatthew** [kamranahmedse/developer-roadmap#6128]
### Roadmap URL

https://roadmap.sh/react

### Suggestions

The React roadmap still recommends learning `create-react-app` which has not been the recommended solution for quite some time.

Per the React docs here: https://react.dev/learn/start-a-new-react-project

The recommended solution for new projects is using a UI framework, with the recommended framework being Next js. 
The docs additionally state that to create a project without a UI framework or to add react to an existing project you would merely install `react` and `react-dom` with your chosen package manager.

No mention of CRA that I could find

**Comment by kamranahmedse** [comment]
This has been fixed and will be published in the coming release. Thank you!
