### ISSUE TITLE
Network Roadmap ?

### ISSUE THREAD

**Issue by amirbagh75** [kamranahmedse/developer-roadmap#613]
can anyone make a network roadmap for beginners?

**Comment by amirbagh75** [comment]
no one ?

**Comment by pmverma** [comment]
I haven't seen any network people using GitHub. IMO, this issue has less chance to get attention.

**Comment by ThorgalAegirsson** [comment]
There are certain curricula from various networking equipment manufacturers that can help you learn from basics to very advanced level. Plus they provide, if you wish to follow, materials and courses. Personally I would recommend Cisco Networking Academy. They have a great route from fundamentals to very advanced knowledge. You can find a great deal of resources online for free should you want to give it a try

**Comment by Ronkiro** [comment]
There are some "awesome" lists

https://github.com/facyber/awesome-networking

**Comment by amirbagh75** [comment]
> There are some "awesome" lists
> 
> https://github.com/facyber/awesome-networking

tnx !

**Comment by cyberbob61** [comment]
> I haven't seen any network people using GitHub. IMO, this issue has less chance to get attention.

Haha. I'm a network engineer with 10Y of experience, I think I could try to help you with the roadmap.

**Comment by kamranahmedse** [comment]
New roadmap requests are being tracked through [roadmap.sh](https://github.com/kamranahmedse/roadmap.sh). Thank you!
