### ISSUE TITLE
Unticking bulletpoints doesn't reset progression

### ISSUE THREAD

**Issue by sinux-l5d** [kamranahmedse/developer-roadmap#6130]
### What is the URL where the issue is happening

https://roadmap.sh/ai-data-scientist

### What browsers are you seeing the problem on?

Chrome

### Describe the Bug

Hello,
I missclicked on the following box, then unticked it : 
![image](https://github.com/kamranahmedse/developer-roadmap/assets/22861912/c695578b-bf29-4d64-b649-7cabfdb42f56)
And on my profile it now shows the ai data scientist roadmap with a 0% progress : 
![image](https://github.com/kamranahmedse/developer-roadmap/assets/22861912/7c55e476-7ec3-4fc3-b80c-b3bf0e6ac03c)
  

### Participation

- [X] I am willing to submit a pull request for this issue.

**Comment by kamranahmedse** [comment]
This should be fine now. Can you please verify?

**Comment by sinux-l5d** [comment]
Hello @kamranahmedse,
It's still visible on my profile : https://roadmap.sh/u/sinuxl5d
