### ISSUE TITLE
Ethical Hacking

### ISSUE THREAD

**Issue by afzal-n** [kamranahmedse/developer-roadmap#6134]
### What is the title of the roadmap you are submitting?

Roadmap to learn Ethical Hacking

### Roadmap Link

https://roadmap.sh/r/ethical-hacking-yyvh9

**Comment by dansholds** [comment]
@afzal-n what is the purpose of this issue? The roadmap you created looks very nice and you can now submit your roadmap to appear in the community board! https://roadmap.sh/community
