### ISSUE TITLE
Edit Profile URL field validation max char length manually capped at 10, but allows pasting of up to 20

### ISSUE THREAD

**Issue by KaylumSnape** [kamranahmedse/developer-roadmap#6139]
### What is the URL where the issue is happening

https://roadmap.sh/account/update-profile

### Describe the Bug

While editing the users profile, Profile URL field, the user is unable to manually enter more than 10 characters, however if I copy a string of 20 characters that is valid.

I have saved a Profile URL of 11 characters.

If I paste more than 20 chars, I get the validation error message:
<img width="447" alt="image" src="https://github.com/user-attachments/assets/1a9eaeb7-21d2-4435-a35e-0ee4bb659914">

These rules do not match up, I am unsure witch is the correct intended length, most likely 20.

Also, should the validation message refer to the field as "username" when it is displayed to the user as "Profile URL"? This may also need updating.

### Output from browser console (if any)

https://roadmap.sh/api/v1-check-is-unique-username

{
    "status": 400,
    "message": "username length must be less than or equal to 20 characters long",
    "errors": [
        {
            "message": "username length must be less than or equal to 20 characters long",
            "location": "username"
        }
    ]
}

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by dansholds** [comment]
Pretty valid.

@kamranahmedse  @arikchakma for your awareness.

**Comment by arikchakma** [comment]
Let me fix the frontend

**Comment by EzioTheDeadPoet** [comment]
Hi not sure why this change was made to limit the characters to 10 instead of 20 but because of that I can't open my profile anymore unless I change my username again. 

Any plans to increase that limit again ?
