### ISSUE TITLE
Software QA Roadmap

### ISSUE THREAD

**Issue by Chaibizi** [kamranahmedse/developer-roadmap#614]
Can you create a roadmap for Software QA?

**Comment by gstvinf** [comment]
Yeah, I'd love to see it!

**Comment by brandon-kyle-bailey** [comment]
seconded, this is an awesome idea

**Comment by AyranAndrade** [comment]
Brilliant idea!

**Comment by iracarus** [comment]
That would be great

**Comment by deXbeulah** [comment]
I vote this.

**Comment by alohasick** [comment]
voting for this!

**Comment by ChaosGod** [comment]
Great idea!

**Comment by artur-v** [comment]
I would love that roadmap

**Comment by epoxitwork** [comment]
+1

**Comment by suhas263** [comment]
That's a good one! Would love to see it as well!

**Comment by kamranahmedse** [comment]
This is now being tracked through [roadmap.sh](https://github.com/kamranahmedse/roadmap.sh). Thank you!
