### ISSUE TITLE
web-draw repository is gone

### ISSUE THREAD

**Issue by huminghui** [kamranahmedse/developer-roadmap#6144]
### Detailed Description

when i run npm run generate-renderer,i get the message "Cloning to '.temp/web-draw'...
ERROR: Repository not found.
Fatal error: Unable to read remote repository.
Please make sure you have the correct access rights and that the repository exists."

**Comment by dansholds** [comment]
Thanks because it's a private repository containing the inner workings of our editor which is not currently opensource 👍

**Comment by huminghui** [comment]
> Thanks because it's a private repository containing the inner workings of our editor which is not currently opensource 👍

Thank you for your reply。

**Comment by makerGeek** [comment]
Hi @dansholds 
Thanks for your reply.

Does that mean that one can't run a functional instance of roadmap ?
Or is there a pluggable alternative of the web-draw dependency ?

**Comment by ignaciocabeza** [comment]
Hi @dansholds.

Do you think this text below is out-to-date and it should be updated?

<img width="821" alt="image" src="https://github.com/user-attachments/assets/698de2a9-70bc-4226-87cb-66e0a4942ee1">

Source: https://roadmap.sh/about

**Comment by parsa-xy** [comment]
If this project is truly open-source, why are there hidden restrictions? @kamranahmedse @dansholds 
This seems contradictory to GitHub's guidelines for open-source projects. Please provide a clear explanation or address this issue promptly, thanks.

**Comment by jiteshgolecha** [comment]
@dansholds Your statement states that roadmap.sh is not open-source.
