### ISSUE TITLE
Incorrect title on Frontend Roadmap

### ISSUE THREAD

**Issue by DevPacoLuna** [kamranahmedse/developer-roadmap#6146]
### What is the URL where the issue is happening

https://roadmap.sh/frontend

### What browsers are you seeing the problem on?

Chrome

### Describe the Bug

It has to be "Remix" instead of "react-router"
<img width="1393" alt="Captura de pantalla 2024-07-14 a la(s) 3 30 16 p m" src="https://github.com/user-attachments/assets/457d4189-2e44-4649-87e6-6748b3fddfa4">
<img width="390" alt="image" src="https://github.com/user-attachments/assets/df81e78c-fb89-4d95-9bb1-5d582c2f2736">

### Participation

- [x] I am willing to submit a pull request for this issue.

**Comment by kamranahmedse** [comment]
[This is intentional](https://remix.run/blog/merging-remix-and-react-router)
