### ISSUE TITLE
Add Terragrunt

### ISSUE THREAD

**Issue by BlackRegis** [kamranahmedse/developer-roadmap#6149]
### Roadmap URL

https://roadmap.sh/devops

### Suggestions

We should add terragrunt next to terraform, because terraform alone is not enough for complex environments where multienvironement / miltiregion / milticompte are involved on aws for example.

**Comment by dansholds** [comment]
@BlackRegis Terragrunt features in the Terraform roadmap, theres no need to add it here.

**Comment by BlackRegis** [comment]
Ah ok! undertood!

Thanks
