### ISSUE TITLE
Misclassification for Impact of Change

### ISSUE THREAD

**Issue by tyler-lee** [kamranahmedse/developer-roadmap#6156]
### What is the URL where the issue is happening

https://roadmap.sh/best-practices/code-review

### What browsers are you seeing the problem on?

Chrome, Safari, Other

### Describe the Bug

According to the content, Impact of Change should be cataloged into Reviewer part.

![image](https://github.com/user-attachments/assets/fe2d06a5-7bc7-45a0-8928-14eceeb33937)

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by kamranahmedse** [comment]
Thank you for reporting. Feel free to submit a PR.

**Comment by dansholds** [comment]
@tyler-lee I wouldn't say its in the wrong place, rather the copy should be changed to say "As the author" 👍
