### ISSUE TITLE
The topic “Testing Techniques” is not linked to any other topic 

### ISSUE THREAD

**Issue by rebfaro** [kamranahmedse/developer-roadmap#6159]
### Detailed Description

![Screenshot 2024-07-16 at 21 21 45](https://github.com/user-attachments/assets/7a9b0f52-0c53-4de7-af87-2072fa9ea772)

**Comment by kamranahmedse** [comment]
This is tied to "Learn the Fundamentals". We will fix it in the next release. Thank you for reporting.
