### ISSUE TITLE
SQS

### ISSUE THREAD

**Issue by AbdulrahmanAlsanaani** [kamranahmedse/developer-roadmap#6166]
### Roadmap URL

https://roadmap.sh/best-practices/aws

### Suggestions

Amazon Simple Queue Service (SQS) is a fully managed message queuing service provided by Amazon Web Services (AWS). It enables the decoupling and scaling of microservices, distributed systems, and serverless applications by allowing components to communicate asynchronously.

**Comment by dansholds** [comment]
This issue is just stating what SQS
