### ISSUE TITLE
[Rust] Update GUI Development (Druid is no longer maintained)

### ISSUE THREAD

**Issue by GabrielCoelho** [kamranahmedse/developer-roadmap#6169]
### Roadmap URL

https://roadmap.sh/rust

### Suggestions

There's plenty GUIs in rust that could be implemented on the "Gui Development" Area
- Xilem
- Dioxus
- Tauri

**Comment by dansholds** [comment]
@GabrielCoelho I've raised a PR to replace with Tauri.
