### ISSUE TITLE
I am curious how to draw this picture? What tool should I use?

### ISSUE THREAD

**Issue by gd4Ark** [kamranahmedse/developer-roadmap#617]
I am curious how to draw this picture? What tool should I use?

**Comment by gd4Ark** [comment]
Ok, I got the answer at the following link
https://github.com/kamranahmedse/developer-roadmap/blob/master/contributing.md#how-are-these-roadmaps-made

**Comment by VladAdGad** [comment]
404

**Comment by barhouum7** [comment]
@VladAdGad 
https://github.com/kamranahmedse/developer-roadmap/blob/master/CONTRIBUTING.md#how-are-these-roadmaps-made
