### ISSUE TITLE
Typo in the framework title

### ISSUE THREAD

**Issue by ariear** [kamranahmedse/developer-roadmap#6172]
### Roadmap URL

https://roadmap.sh/frontend

### Suggestions

In the react-router title, this should be replaced with Remix
![Screenshot 2024-07-18 092046](https://github.com/user-attachments/assets/bc694e02-c70b-4c1d-997b-5783582da623)
![Screenshot 2024-07-18 092101](https://github.com/user-attachments/assets/4237eb36-c0a9-44c4-bedf-74d85d05acbc)

**Comment by kamranahmedse** [comment]
This is intentional
https://github.com/kamranahmedse/developer-roadmap/issues/6146
https://github.com/kamranahmedse/developer-roadmap/pull/6160
https://github.com/kamranahmedse/developer-roadmap/pull/6027

**Comment by luv1327** [comment]
Okay!
