### ISSUE TITLE
Logged in user sees register yourself message and redirects to signup page and back to dashboard 

### ISSUE THREAD

**Issue by luv1327** [kamranahmedse/developer-roadmap#6175]
### Detailed Description

If the user is already logged in, instead of asking them to register and redirecting them to the login page, we can write Continue Your Journey Keep Growing.

https://github.com/user-attachments/assets/d7908d68-2818-49ff-84b9-39a946c2bd3f

**Comment by kamranahmedse** [comment]
We are planning a redesign soon, we will think about this then. Closing it for now since it's a non-issue.
