### ISSUE TITLE
Too many coursera courses on AI and Data Scientist

### ISSUE THREAD

**Issue by Subdev514** [kamranahmedse/developer-roadmap#6180]
### Roadmap URL

https://roadmap.sh/ai-data-scientist

### Suggestions

Due to the recent change in coursera's policy due to which you can now no longer get 100% full financial aid on a course i think its worth while to review the [AI and Data Scientist roadmap](https://roadmap.sh/ai-data-scientist) again and add alternative free recourses or remove a few of the topics for better courses as i would argue there is a very big mass of people who do not want to pay or simply cant afford courses provided by coursera on a 90% discount including me

**Comment by kamranahmedse** [comment]
Thank you for bringing this to our attention @Subdev514. The roadmap was actually [submitted by Careem's AI & Data engineering team](https://docs.google.com/spreadsheets/d/1C9BSXdwXDpmT-FbSvp2rCIgPTuM5ef0y9Y0KtjeCOF8/edit?gid=0#gid=0). It is more course oriented and is using Coursera unfortunately. We will put it in our backlog and see what we can do to include other resources.
