### ISSUE TITLE
Add Plotly Dash to the Python frameworks.

### ISSUE THREAD

**Issue by omnicoder9** [kamranahmedse/developer-roadmap#6183]
### Roadmap URL

https://roadmap.sh/python

### Suggestions

Add a node for Plotly Dash under "Learn a Framework" and "Synchronous" in the Python roadmap.  Plotly Dash is a Python front end framework with functionality for data visualization.  https://dash.plotly.com/.  It also has its own UI component library, Dash Bootstrap Components.  https://dash-bootstrap-components.opensource.faculty.ai/

**Comment by kamranahmedse** [comment]
This has been fixed and will be published in the coming release today. Thank you!
