### ISSUE TITLE
The content of Dual Process Theory is a duplicate of the content in Spectrum of Thinking Interventions

### ISSUE THREAD

**Issue by winsatid62** [kamranahmedse/developer-roadmap#6186]
### What is the URL where the issue is happening

https://roadmap.sh/ux-design

### What browsers are you seeing the problem on?

Other

### Describe the Bug

When I bring up the content for Dual Process Theory, it shows content that looks like a replica of the one from Spectrum of Thinking Interventions.

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by kamranahmedse** [comment]
This has been fixed. Thank you!
