### ISSUE TITLE
Including NumPy into the official roadmap of data analyst

### ISSUE THREAD

**Issue by gappeah** [kamranahmedse/developer-roadmap#6187]
### Roadmap URL

https://roadmap.sh/data-analyst

### Suggestions

The data analyst roadmap is missing NumPy. NumPy, particularly with Python, is often used in data analysis alongside Pandas (which is already present in the data manipulation section of the roadmap). I would like to see NumPy added as a module, as I have seen, for example, the 'Data Analysis with Python Certification' and W3Schools make direct references to NumPy alongside Pandas, Matplotlib, and Seaborn to process and visualise data.

For resources, I recommend these resources to add
https://www.freecodecamp.org/learn/data-analysis-with-python/
https://www.w3schools.com/python/numpy/default.asp
https://www.youtube.com/watch?v=QUT1VHiLmmI&pp=ygUFbnVtcHk%3D
https://www.youtube.com/watch?v=4c_mwnYdbhQ&pp=ygUFbnVtcHk%3D
https://www.youtube.com/watch?v=9JUAPgtkKpI&pp=ygUFbnVtcHk%3D

**Comment by dansholds** [comment]
added to the internal backlog.
