### ISSUE TITLE
Split "Other Types" into "Top Types" and "Bottom Types"

### ISSUE THREAD

**Issue by bennycode** [kamranahmedse/developer-roadmap#6189]
### Roadmap URL

https://roadmap.sh/typescript

### Suggestions

At the moment, `any`, `object`, `unknown` and `never` are part of a group called "Other Types".

According to the TypeScript documentation, `unknown` and `any` are actually "Top Types": https://www.typescriptlang.org/docs/handbook/release-notes/typescript-3-0.html#new-unknown-top-type

The `never` type can be classified as "Bottom Type": https://en.wikipedia.org/wiki/Bottom_type#In_programming_languages

**Comment by loralridz** [comment]
@bennycode Question about this; are we expecting two new blocks( Top Types, Bottom Types) and in the Other Types, we'll only have object. is that right?
If so, can i work on this

**Comment by bennycode** [comment]
Hi @loralridz, it needs indeed two more blocks (Top Types & Bottom Types). The `object` type can then be put into the "Object Types" box. Array is already listed in "Object Types" and according to MDN arrays are objects so it makes sense to put `object` into the same category as `Array`:

> [Arrays](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array) are regular objects for which there is a particular relationship between integer-keyed properties and the length property.

Source: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Data_structures#indexed_collections_arrays_and_typed_arrays

Or was there a reason that "object" has been seperated from the "Object Types"?

**Comment by kamranahmedse** [comment]
This has been fixed. Thank you for reporting @bennycode!
