### ISSUE TITLE
Active 'react-testing-library' instead of 'enzyme'

### ISSUE THREAD

**Issue by ifndefdeadmau5** [kamranahmedse/developer-roadmap#619]
From react [docs](https://reactjs.org/docs/test-utils.html)

> Note:
> We recommend using React Testing Library which is designed to enable and encourage writing tests that use your components as the end users do.
> Alternatively, Airbnb has released a testing utility called Enzyme, which makes it easy to assert, manipulate, and traverse your React Components’ output.

**Comment by Ronkiro** [comment]
I think that Enzyme is more popular. But i would for sure consider adding React-Testing_Library as an alternative method.

**Comment by kamranahmedse** [comment]
This has been fixed and will be published in the next release. Thank you 🙏
