### ISSUE TITLE
Progress bar regarding the 'Prompt Engineering Roadmap' is 'impossible' to complete due to 'hidden' 'clickable-group'

### ISSUE THREAD

**Issue by hashiiyama** [kamranahmedse/developer-roadmap#6191]
### What is the URL where the issue is happening

https://roadmap.sh/prompt-engineering

### What browsers are you seeing the problem on?

Other

### Describe the Bug

The bug comes from the fact that the 'progress bar' is considering 'hidden' 'clickable-group'. Meaning that if you 'mark complete' every 'clickable-group', you won't be able to have 100% progress bar, it will instead be stuck at '86%' displaying '51 of 59' completed. 

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by kamranahmedse** [comment]
Thank you for reporting, we are currently revamping all the roadmaps. This will be fixed soon.
