### ISSUE TITLE
Angular Roadmap

### ISSUE THREAD

**Issue by jdegand** [kamranahmedse/developer-roadmap#6192]
### Roadmap URL

https://roadmap.sh/angular

### Suggestions

- The `Angularjs` vs `Angular` distinction is no longer relevant and can be removed.
- RxJS Marble diagrams are not really relevant anymore either.  RxJS is being diminished in modern Angular and it may be wise to shrink that section as well.  
- The `Inject` function can covered in the `Dependency Injection` section.
- `Validators` can be added to the `Create a custom__` section.
- Signals need to be added to the `What are__` section. 
- The new template syntax is not covered.   `@for`, `@let`, `@defer` and more.  
- [Analog](https://analogjs.org/) can be added to the SSR section.  `Angular Universal` is renamed to `SSR`.   `Scully` is kind of outdated although an update is being worked on, it seems to be far away so I think it can removed.  It would not be productive to learn it now.
- There are plenty of state management libraries that can be added.

**Comment by kamranahmedse** [comment]
Thank you @jdegand -- that's really helpful. What state management libraries would you recommend mentioning?

I am redrawing all the roadmaps at the moment and will prioritize it for this week.

**Comment by jdegand** [comment]
I would look at adding TanStack Query, as that can be enough in a smaller app to replace a heavier solution like NgRx.  Plus, it has portability to other frameworks so a learner would get value by learning that.

**Comment by jdegand** [comment]
From the Angular CLI, you could also draw a connection to `Monorepos` and `Nx`.  Vercel Turbo also works, but the example app has not been merged yet.  Nx is really the best option and the most important.

**Comment by dansholds** [comment]
set to "reviewed" so we don't miss it @kamranahmedse 🤙

**Comment by dansholds** [comment]
@jdegand I'm rewriting the roadmap as we speak, are you available to validate changes?

**Comment by jdegand** [comment]
@dansholds I'll review the PR and/or you can add any questions here.

**Comment by dansholds** [comment]
> @dansholds I'll review the PR and/or you can add any questions here.    

I've just had it reviewed by two core members of Angular 👍

I've added/removed all your suggestions too 🤙

**Comment by kamranahmedse** [comment]
Revised version of Angular roadmap is live. Thank you for the feedback @jdegand - super helpful!
