### ISSUE TITLE
Duplicate Search Results

### ISSUE THREAD

**Issue by fellalli** [kamranahmedse/developer-roadmap#6193]
### What is the URL where the issue is happening

https://roadmap.sh/

### What browsers are you seeing the problem on?

Firefox, Chrome, Microsoft Edge, Other

### Describe the Bug

Certain roadmaps, including `Code Review`, `Backend`, `Node.js`, and `React`, appear multiple times when the same term is searched repeatedly.

https://github.com/user-attachments/assets/cc77257f-8920-454f-8720-3df24ef665cf

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by dansholds** [comment]
Lol thanks @fellalli 😂 

@kamranahmedse

**Comment by mr-loop-1** [comment]
I got the issue and will raise a fix
