### ISSUE TITLE
Frontend Developer - CSS Preprocessors - ARTICLE Why Use Preprocessors? - link doesn't work

### ISSUE THREAD

**Issue by Pagas15** [kamranahmedse/developer-roadmap#6194]
### What is the URL where the issue is happening

https://roadmap.sh/frontend

### Describe the Bug

Frontend Developer - CSS Preprocessors - ARTICLE Why Use Preprocessors? - link doesn't work

### Output from browser console (if any)

Google chrome 

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by dansholds** [comment]
@Pagas15 I have fixed this but in future remember that you can open a PR to remove or adds links yourself, it helps us out and is good practice!
