### ISSUE TITLE
Readability

### ISSUE THREAD

**Issue by edusher** [kamranahmedse/developer-roadmap#6198]
### Feature Description

It would be nice to see an option to view the explanation of each topic in either full-screen or in at least a larger window than the one that currently only pops out a little bit from the right. This would really help readability and would increase the rate at which I could go through each topic!

**Comment by dansholds** [comment]
This is a perfectly valid request and one that has been requested before, we are a small team with a lot to do before we hit requests like this, but I'll leave this open so we keep it in mind!

**Comment by noobyco** [comment]
I was thinking that maybe we could make this feature possible if there is nothing to finish first. How about making it 80% width and height almost filling the screen with an option to go full screen? A little odd-on to that is to add a shortcut (ESC) to close out of the full screen, one more time (ESC) will close that explanation. Or this shortcut thing can be put into a separate issue all together.
