### ISSUE TITLE
Add C language in the DSA roadmap

### ISSUE THREAD

**Issue by PaulaSelim** [kamranahmedse/developer-roadmap#6205]
### Detailed Description

Please add the C language in the data structures and algorithms roadmap as it a must choice for people who want to branch in Embedded Systems.

**Comment by dansholds** [comment]
@paulakhalil Sure this makes sense :)

We can add this when we migrate the roadmap to the new editor (so I'll leave open for now but add a tag)

**Comment by HUN-sp** [comment]
@kamranahmedse  Assign this issue to me
Implementing this update will align the curriculum with industry needs and enhance learning outcomes.

**Comment by harshitadubey1203** [comment]
Can you please assign this to me

**Comment by dansholds** [comment]
The roadmap already suggests 8 languages which is enough.
