### ISSUE TITLE
Linux roadmap: add sed command section to text processing

### ISSUE THREAD

**Issue by Hanimir-san** [kamranahmedse/developer-roadmap#6207]
### Roadmap URL

https://roadmap.sh/linux

### Suggestions

Hi! I thought it might be worth adding the command "sed" to the Linux roadmap text processing section. It's mentioned in the section introduction, but there's no individual topic for it.

**Comment by dansholds** [comment]
Sed certainly deserves it's own topic, I'll add it shortly :)

**Comment by VANSH3104** [comment]
@dansholds I am interested in solving this issue can you explain this to me do we need to integrate sed or make a different topic out of it

**Comment by VANSH3104** [comment]
@Hanimir-san I added sed to the Linux roadmap I also tested it too it works perfectly and I also add documentation too

**Comment by VANSH3104** [comment]
@dansholds, could you please clarify what I might have missed here? The issue suggests adding a new node for 'sed' to the Linux roadmap. Should I submit an issue for this first, or is there already a discussion in progress?
