### ISSUE TITLE
Add Sentry as Application Monitoring Tool

### ISSUE THREAD

**Issue by ingcarlosperez** [kamranahmedse/developer-roadmap#6209]
### Roadmap URL

https://roadmap.sh/devops

### Suggestions

Sentry provides real-time error tracking and performance monitoring, enabling teams to quickly identify, diagnose, and resolve issues.

**Comment by dansholds** [comment]
@ingcarlosperez I agree and I'll get to this when I can 👍

**Comment by esterfania** [comment]
Can I help with this?

**Comment by dansholds** [comment]
This will be done on the next iteration of the roadmap
