### ISSUE TITLE
Web Security for Frontend

### ISSUE THREAD

**Issue by Ayman97** [kamranahmedse/developer-roadmap#621]
I think learning Web security as a Frontend Develo
per / Engineer will be valuable.

**Comment by LuanMaik** [comment]
I think that CSP (Content Security Policy) could be important to frontend security

**Comment by s14k51** [comment]
Owasp rules/standards can go to both front end and back end roadmaps.

**Comment by Ayman97** [comment]
@s14k51 Yes, Owasp rules will be beneficial for both frontend & backend.

**Comment by kamranahmedse** [comment]
This has been fixed and will be published in the coming update. Thank you 🙏
