### ISSUE TITLE
Add GTFOBins/Wadcoms

### ISSUE THREAD

**Issue by ExitEject** [kamranahmedse/developer-roadmap#6210]
### Roadmap URL

https://roadmap.sh/cyber-security

### Suggestions

Near LOLBAS you can add GTFOBINS and wadcoms
https://gtfobins.github.io/ (linux unintended tool usage)
https://wadcoms.github.io/ (abusing AD)
https://www.loobins.io/binaries/ (abusing macos)

**Comment by dansholds** [comment]
@ExitEject I've added WADCOMS and GTFOBINS, could only fit two.
