### ISSUE TITLE
Adding GCP Roadmap

### ISSUE THREAD

**Issue by dianaartiom** [kamranahmedse/developer-roadmap#6213]
### Feature Description

As a ML Engineer I would like to have a GCP Roadmap so that I can can skill up and become fluent in GCP Infrastructure. 

Thank you, much apprecciated 🙏

**Comment by kamranahmedse** [comment]
We are now closing any issues requesting new roadmap requests to clean up the issues. 

However, this doesn't mean that the requested roadmap won't be added to the website. We are putting it in the backlog and will add it to the website depending on how it ranks in the backlog or sooner if we find someone interested in adding that roadmap. Thank you for the request though! 🙏
