### ISSUE TITLE
Cyber Security roadmap

### ISSUE THREAD

**Issue by lucasmori** [kamranahmedse/developer-roadmap#624]
Can be very awesome create a roadmap for cyber security beginners.

**Comment by soyrichidev** [comment]
I can provide a path but someone with more expertise than me could help improving it, also drawing a nice map ;)

**Comment by KadonWills** [comment]
Sounds cool, looking foward to an eventual cyber security roadmap : )

**Comment by lucasmori** [comment]
Sounds good to me, we can wait for more people to interact with this Issue.

**Comment by tetsu5555** [comment]
Sounds very good.
I don't know where to start to learn cyber security, looking forward to an cyber security load map 👍

**Comment by mrkinix** [comment]
> I can provide a path but someone with more expertise than me could help improving it, also drawing a nice map ;)

Could you provide your path?

**Comment by kamranahmedse** [comment]
New roadmap requests are being tracked through [roadmap.sh](https://github.com/kamranahmedse/roadmap.sh). Thank you!

@soyrichidev can you possibly list down the bulleted list of items that you have in the textual form and submit? I will add it to the roadmaps and then can be iterated upon by the community.

**Comment by 0x7EVEN** [comment]
I can contribute as well
