### ISSUE TITLE
Misalignment of 'Made with Developer' Text in Footer Section

### ISSUE THREAD

**Issue by Jash2606** [kamranahmedse/developer-roadmap#6243]
### Description:
The alignment of the "Made with Developer" text in the footer section is not consistent with the rest of the footer elements. This causes the footer to appear visually unbalanced and unprofessional.

#### Actual Behavior:
The "Made with Developer" text is misaligned, leading to a disorganized appearance in the footer section.
![Screenshot 2024-07-26 221535](https://github.com/user-attachments/assets/1bf8c940-168d-4d82-bf30-722ba71f9879)

#### Expected Behavior:
The "Made with Developer" text should be properly aligned with other elements in the footer to ensure a cohesive and visually appealing layout.

**Comment by kamranahmedse** [comment]
I don't see anything wrong with the alignment. Thank you for the PR though.
