### ISSUE TITLE
Sass, not SASS

### ISSUE THREAD

**Issue by TheJaredWilcurt** [kamranahmedse/developer-roadmap#625]
Sass has officially never been all caps. Similar to how npm is never NPM.

**Comment by SuperQ** [comment]
Usually it's ["SaaS"](https://en.wikipedia.org/wiki/Software_as_a_service).

**Comment by TheJaredWilcurt** [comment]
@SuperQ This is not related to "Software as a Service".

[https:///Sass-Lang.com](https://sass-lang.com)

**Comment by Ronkiro** [comment]
@kamranahmedse I created a PR to solve this issue.
Please consider checking it :)

**Comment by kamranahmedse** [comment]
This has been fixed and will be published in the next release. Thank you!
