### ISSUE TITLE
Missing content for API Design roadmap

### ISSUE THREAD

**Issue by DazSanchez** [kamranahmedse/developer-roadmap#6254]
### What is the URL where the issue is happening

https://roadmap.sh/api-design

### What browsers are you seeing the problem on?

Firefox

### Describe the Bug

The `Building JSON / RESTful APIs > Rate Limiting` topic is missing, detail page returns "Topic not found", HTTP request returns 404.

The links for `API Security Best Practices` and `API Performance Best Practices` point to the same `https://roadmap.sh/api-design` url.

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by dansholds** [comment]
Linked PR will solve this
