### ISSUE TITLE
QA Email Technologies vs testing

### ISSUE THREAD

**Issue by sclayman** [kamranahmedse/developer-roadmap#6255]
### Roadmap URL

https://roadmap.sh/qa

### Suggestions

Would be good to split these out to email technologies vs testing kind of like we do for Front End. SMTP and email headers are both important topics for QA to understand when dealing with email testing

**Comment by Ris345** [comment]
Hello! I am interested in taking up this issue, however I don't see anything render on the /qa page when I go there on my machine. Is there a configuration that I need to fix in-order to achieve that. Thanks!

**Comment by dansholds** [comment]
It's ok as it is for now but can be looked at on the next iteration
