### ISSUE TITLE
Flutter section issue

### ISSUE THREAD

**Issue by kypanz** [kamranahmedse/developer-roadmap#6259]
### Roadmap URL

https://roadmap.sh/flutter

### Suggestions

Hello guys, first at all let me say thanks for all this roadmaps, are very interesting and i use to learn on my free time

I am here to mentioned a section of flutter that not works fine, i hope this info can be useful, thanks for read and have a nice day

Name section :  3 Trees

Image reference : 
![image](https://github.com/user-attachments/assets/cf2037ed-032c-4806-aa52-1ee50a98e541)

Output : 
![image](https://github.com/user-attachments/assets/f2951ff7-868c-4b4a-8ef6-e827a788f5e4)

**Comment by pyoneerC** [comment]
The [file](https://github.com/kamranahmedse/developer-roadmap/blob/7643cca066b6282ea8994745f2d589db88b975f5/src/data/roadmaps/flutter/content/116-flutter-internals/3-trees.md?plain=1) does exist.

```
23:27:26 [WARN] [router] A `getStaticPaths()` route pattern was matched, but no matching static path was found for requested path `/flutter/flutter-internals/3-trees`.

Possible dynamic routes being matched: src/pages/[roadmapId]/[...topicId].astro.
23:27:26 [404] /flutter/flutter-internals/3-trees 10ms
```

@kamranahmedse

**Comment by kypanz** [comment]
i see, i am not sure what can be happend, here is what i get on the networks tab, i hope can be useful : 

![image](https://github.com/user-attachments/assets/a663222f-9e6e-4b7f-89c9-fe31a15ac488)

**Comment by dansholds** [comment]
This has been fixed, thanks for raising.
