### ISSUE TITLE
AI Generated Content should be labelled

### ISSUE THREAD

**Issue by captn3m0** [kamranahmedse/developer-roadmap#6266]
### What is the URL where the issue is happening

https://roadmap.sh

### Describe the Bug

A lot of roadmap content is AI-generated, and should be marked as such. The content-generation script is documented in the scripts directory https://github.com/kamranahmedse/developer-roadmap/tree/master/scripts#roadmap-contentcjs

> Currently, for any new roadmaps that we add, we do create the interactive roadmap but we end up leaving the content empty in the roadmap till we get time to fill it up manually.

> This script populates all the content files with some minimal content from OpenAI so that the users visiting the website have something to read in the interactive roadmap till we get time to fill it up manually.

But the content that has been generated in the past using this script is not labelled as AI generated, neither do the commits carry any attribution information about this.

At this point, roughly the majority of the content in the roadmaps is AI generated, and the footer also should be updated to reflect the reality:

> Community created roadmaps, articles, resources and journeys to help you choose your path and grow in your career. 

While a lot of the content is community-created, the vast majority is not, and the site should reflect this accurately.

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by dansholds** [comment]
We no longer use that approach on new roadmaps, new roadmaps ship empty.

We are currently going back through old roadmaps and removing content injected with that approach.

**Comment by captn3m0** [comment]
Could the old roadmaps where this approach was used be labelled as such in that case? I'm happy to file a PR setting the appropriate front-matter if there's a list of such roadmaps/files.

**Comment by dansholds** [comment]
> Could the old roadmaps where this approach was used be labelled as such in that case? I'm happy to file a PR setting the appropriate front-matter if there's a list of such roadmaps/files.

For what purpose and to what end? We're not going to dedicate the engineering time to do this when we're currently in the long process of improving/upgrading existing roadmaps.
