### ISSUE TITLE
Blocking custom fonts breaks roadmap rendering

### ISSUE THREAD

**Issue by captn3m0** [kamranahmedse/developer-roadmap#6268]
### What is the URL where the issue is happening

https://roadmap.sh/android

### What browsers are you seeing the problem on?

Firefox, Chrome, Safari, Microsoft Edge, Other

### Describe the Bug

If your browser refuses custom fonts, for accessibility or other reasons, the browser does not render the roadmap, and it keeps loading forever with no error message shown to the user.

The roadmap should be rendered in a fallback websafe font.

Screenshot:

![image](https://github.com/user-attachments/assets/d1125d2e-2717-4f20-b0c3-491f42eef3e1)

A simple way to test the issue is to disable remote fonts via uBlock Origin:

![image](https://github.com/user-attachments/assets/a54c17a6-5a7f-4304-a7d8-b24492851400)

or to disable custom fonts in the browser settings (firefox screenshot):

![image](https://github.com/user-attachments/assets/c4dfc226-94ba-4e18-9fa5-15b151317b06)

### Output from browser console (if any)

```
Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://fonts.gstatic.com/s/balsamiqsans/v3/P5sEzZiAbNrN8SB3lQQX7Pncwd4XIA.woff2. (Reason: CORS request did not succeed). Status code: (null).

downloadable font: download failed (font-family: "balsamiq" style:normal weight:400 stretch:100 src index:0): bad URI or cross-site access not allowed source: https://fonts.gstatic.com/s/balsamiqsans/v3/P5sEzZiAbNrN8SB3lQQX7Pncwd4XIA.woff2
Uncaught (in promise) DOMException: A network error occurred. [EditorRoadmap.BWTIbhKV.js:1:1176](https://roadmap.sh/_astro/EditorRoadmap.BWTIbhKV.js)
    $</</< https://roadmap.sh/_astro/EditorRoadmap.BWTIbhKV.js:1
    AsyncFunctionThrow self-hosted:808
    (Async: async)
    $</< https://roadmap.sh/_astro/EditorRoadmap.BWTIbhKV.js:1
    br https://roadmap.sh/_astro/index.D-zlsnuI.js:24
    Yn https://roadmap.sh/_astro/index.D-zlsnuI.js:24
    wf https://roadmap.sh/_astro/index.D-zlsnuI.js:24
    E https://roadmap.sh/_astro/index.D-zlsnuI.js:9
    rt https://roadmap.sh/_astro/index.D-zlsnuI.js:9
    (Async: EventHandlerNonNull)
    <anonymous> https://roadmap.sh/_astro/index.D-zlsnuI.js:9
    <anonymous> https://roadmap.sh/_astro/index.D-zlsnuI.js:9
```

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by kamranahmedse** [comment]
I am not sure there is a fix for this. Roadmap renderer specifically uses Balsamiq font in order to calculate the dimensions and draw the roadmap, picking a fallback font is going to cause render issues. Closing it as a low priority item -- we will tackle this if more people report this issue. Thank you though!
