### ISSUE TITLE
Introduction of Sliver Widgets as part of flutter widgets

### ISSUE THREAD

**Issue by josephwatunu123** [kamranahmedse/developer-roadmap#6269]
### Roadmap URL

https://roadmap.sh/flutter

### Suggestions

I believe dedicating a topic soley for people to learn sliver widgets as they learn dart widgets is important. This is because after going deep into the roadmap, I had to return to widgets to learn slivers, which became a bit confusing. Slivers are useful for complex scrolls when using dart, compared to single child scroll among others.

**Comment by dakshvasudev** [comment]
Can it be assigned to me ?

**Comment by dansholds** [comment]
This can be added on the next iteration of the roadmap.
