### ISSUE TITLE
Cyber Security roadmap: text not wrapping itself 

### ISSUE THREAD

**Issue by Jakub768** [kamranahmedse/developer-roadmap#6277]
### Roadmap URL

https://roadmap.sh/cyber-security

### Suggestions

the text does not fit into the box so I think it is better to just say "Programming skills" rather than "Programming skills (Optional but Recommended)"

![image](https://github.com/user-attachments/assets/cf810c80-a7ce-4552-8078-680a36b13336)

**Comment by kamranahmedse** [comment]
This has been fixed and will be published in the coming release. Thank you!
