### ISSUE TITLE
SVG Icons for frontend roadmap

### ISSUE THREAD

**Issue by dujuanxian** [kamranahmedse/developer-roadmap#628]
SVG Icons VS Font Icons are common tech skills required for most of frontend project.

**Comment by sahumanika** [comment]
SVG is the best solution as compared to others.  It's vector file and works for all browsers. It solves my issue with jpg or png specially in retina browser.

**Comment by Muhammad-Atif-Ch** [comment]
okkk

**Comment by kamranahmedse** [comment]
I don't think icons specifically have any place in the roadmap but yes SVG has been added and will be published in the next release. Thank you!
