### ISSUE TITLE
Docker in full stack roadmap

### ISSUE THREAD

**Issue by Poitew** [kamranahmedse/developer-roadmap#6286]
### Roadmap URL

https://roadmap.sh/full-stack

### Suggestions

As the title suggest I think that there should be a Docker topic in the full stack roadmap, specifically before the aws topic.
And because of this, ECS (Elastic Container Service) should be added to the aws topics.
Why you ask? Because docker is the most used DevOps tool ( not counting Git / GitHub )

**Comment by kamranahmedse** [comment]
Full-stack roadmap is intentionally kept beginner friendly and doesn't mention everything. That's the reason why we link to Frontend and Backend roadmaps.
