### ISSUE TITLE
Missing topics in MongoDB roadmap under "Scaling MongoDB"

### ISSUE THREAD

**Issue by Lincoln-GR** [kamranahmedse/developer-roadmap#6289]
### Roadmap URL

https://roadmap.sh/mongodb

### Suggestions

Following topics are missing:
* Replicasets
* Shared clusters
* Tuning configuration
* Indexing
* Query optimization

**Comment by dansholds** [comment]
For others awareness, this is not that the topics are absent from the roadmap, but rather the literal "Topic not found" error.

**Comment by dansholds** [comment]
@kamranahmedse one for when mongodb roadmap is migrated to the new editor - the topics under "Scaling MongoDB" don't exist i.e. the files don't exist, "Scaling MongoDB" is a single md files rather than a dir of files.

**Comment by dansholds** [comment]
Added to internal roadmap, closing.
