### ISSUE TITLE
Add Examples to Distinguish Query Parameters and Path Parameters in API Design Module

### ISSUE THREAD

**Issue by saeidalz13** [kamranahmedse/developer-roadmap#6293]
### Roadmap URL

https://roadmap.sh/api-design

### Suggestions

I started reading the "api-design" roadmap and in `URL, Query & Path Parameters` module, I realized that a simple example could be useful to distinguish `URL`, `query parameters` and `path parameters`.

Proposed Examples:

## URL
```bash
https://someurl.com
```
This is a random URL which includes the protocol (HTTPS) as well as the domain name `(someurl.com)`.

## Path Parameter
```bash
https://someurl.com/:id
```
Here `:id` is a path parameter. It is part of the URL path and typically used to identify a specific resource.

## Query Parameter
```bash
https://someurl.com/books?genre=fiction&origin=Canada
```
In this case, `genre` and `origin` are query parameters. They appear after the `?` in the URL and are usually used to filter or sort the resources returned by the API.

**Comment by dansholds** [comment]
Feel free to submit a PR to the relevant topic content to remediate this! 😄

**Comment by saeidalz13** [comment]
Alright sweet! Thanks
