### ISSUE TITLE
Do you know where your food . . . I mean compute . . . comes from?

### ISSUE THREAD

**Issue by joecupano** [kamranahmedse/developer-roadmap#632]
It is interesting how much abstraction has grown between the developer and the underlying hardware their code is running on. Much of it was necessary to get to where we are today. But have we reached an inflection point where there is so much cruft in the layers of abstraction that we have created more problems (not just security) than we can cope with plus a "too big to fail" mentality creeping in?

While may not be in the scope of a web developer, perhaps a parking lot should be created for all the dependencies a web developer has outside of their scope especially with on-premise, hybrid, and multi-cloud environments.

**Comment by CharlyJazz** [comment]
Good point.

**Comment by kamranahmedse** [comment]
I have been thinking about it and I believe this year's release will cover that 🙏
