### ISSUE TITLE
Add knowledge of some things into backend roadmap

### ISSUE THREAD

**Issue by Sergei-vb** [kamranahmedse/developer-roadmap#633]
It'd be cool if you added knowledge of:
* async code 
* bash scripts 
* CRON jobs
* also base knowledge of JS, html, css

--> into backend roadmap

**Comment by Ronkiro** [comment]
About the JS Quote #608

**Comment by kamranahmedse** [comment]
This has been fixed and will be published in the coming release. Thank you 🙏
