### ISSUE TITLE
Testing mindset -> QA mindset

### ISSUE THREAD

**Issue by 403-html** [kamranahmedse/developer-roadmap#6331]
### Roadmap URL

https://roadmap.sh/qa

### Suggestions

As we know testing is just part of quality assurance topic. And the roadmaps itself is for quality assurance engineer, not manual tester.  
 

![image](https://github.com/user-attachments/assets/e836ac91-d015-48ab-84de-e32a11f495dc)

Overall, the description seems to focus heavily on a "reactive" mindset, but it would be more beneficial to adopt a holistic and proactive approach to quality.

While resources like ISTQB offer useful guidance, they often expect an unrealistic level of perfect alignment and adherence. Real-world QA should consider the human element, understanding that mistakes are bound to happen, and instead of aiming to "100% prevent them", the focus should be on designing processes to minimize their impact. It's important to view defects as opportunities for growth rather than blaming developers.

The idea that QAs are the sole core of finding defects is misleading, as testing can also be done by developers or project managers. The "Tester Mindset" section needs a significant overhaul. As a Quality Assurance Engineer, your role is to advocate for quality throughout the software development lifecycle, creating an environment where everyone can do their best work, especially during critical moments like a hotfix. If you notice a teammate deeply focused, offering to bring them a coffee can be a simple yet supportive gesture to help them maintain their concentration.

From my point of view "Testing mindset" should be redone. I can try and write something up.

**Comment by kamranahmedse** [comment]
Feel free to submit a PR. Thank you!
