### ISSUE TITLE
Maven before gradle

### ISSUE THREAD

**Issue by grigoryan-m** [kamranahmedse/developer-roadmap#6334]
### Roadmap URL

https://roadmap.sh/java

### Suggestions

Hello, I'm learning java now and gradle is very hard for me, but maven was pretty easy. after I learn maven, gradle became much easier, so I suggest to move Maven in front of the Gradle.

**Comment by jdegand** [comment]
Popularity wise, Maven is first.  [See here for more](https://betterprojectsfaster.com/guide/java-full-stack-report-2023-01/build/#:~:text=Popularity%20trend%3A%20Maven%20is%202.5,build%20heavily%2C%20then%20use%20Gradle).

**Comment by dansholds** [comment]
Gradle Maven and Ant are not in a specific order, they're all single subtopics.
