### ISSUE TITLE
Web scraping Roadmap

### ISSUE THREAD

**Issue by giorgi1517** [kamranahmedse/developer-roadmap#634]
I am not sure if it is front or back i consider it a totally different thing which deserves attention and some facts about it should be shared in roadmap

**Comment by kamranahmedse** [comment]
That doesn't require a roadmap :) 
Just google how to scrape in the language of your choice.

**Comment by noviluni** [comment]
@kamranahmedse I think you are underestimating this, as it's not easy to learn how to scrape properly.

@giorgiberia  
To learn to scrape you need to learn some web technologies as HTTP protocol (+ how headers, cookies, User-Agents, etc. work), CSS and XPATH selectors, JavaScript and JSON, RegEx, how to properly use proxies (proxy rotation), etc. and finally you should learn some language with/or without a framework (as Python + Scrapy).
