### ISSUE TITLE
Broken link in Kubernetes Roadmap in "Deploying Your First Application" section

### ISSUE THREAD

**Issue by Brain2life** [kamranahmedse/developer-roadmap#6343]
### What is the URL where the issue is happening

https://roadmap.sh/kubernetes

### What browsers are you seeing the problem on?

Chrome

### Describe the Bug

The link to the following article is broken: https://www.weave.works/blog/deploying-an-application-on-kubernetes-from-a-to-z

![broken_link_k8s-2](https://github.com/user-attachments/assets/60de0208-e817-43b5-a133-e6622eb59d8f)

![broken_link_k8s](https://github.com/user-attachments/assets/d3b101e1-dd1c-49e2-9e1f-bca8c4b75b94)

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by kamranahmedse** [comment]
Thank you, feel free to submit a PR for this.
