### ISSUE TITLE
Linters and formatters: add Biome

### ISSUE THREAD

**Issue by Romej** [kamranahmedse/developer-roadmap#6345]
### Roadmap URL

https://roadmap.sh/frontend

### Suggestions

There's more than eslint and prettier, biome is a worthy alternative to display.

https://biomejs.dev/

**Comment by kamranahmedse** [comment]
Thank you for opening the issue. We don't want to convolute the roadmap by mentioning every available option and are just focusing on what is the most relevant item that you would pick today and the mentioned item doesn't conform to that. 

This has also been [mentioned in the contribution docs](https://github.com/kamranahmedse/developer-roadmap/blob/master/contributing.md). 
Thank you for your suggestion though 🙏

**Comment by gustavocadev** [comment]
Biome ought to be included; otherwise, the roadmap lacks integrity in selecting the best tools.
