### ISSUE TITLE
Make the road maps more printer friendly

### ISSUE THREAD

**Issue by TalaatHarb** [kamranahmedse/developer-roadmap#635]
Imagine you want to hang those on your desk or hand them in lectures, it is hard to get them printed because there is no clear places to split them to pages and they sure don't fit in standard paper size.

It would be useful and it might even cause them to get more popular.

**Comment by kamranahmedse** [comment]
This has been resolved. You may find the printable PDFs through the links below:

- [Frontend Roadmap](https://roadmap.sh/static/roadmaps/pdf/frontend.pdf)
- [Backend Roadmap](https://roadmap.sh/static/roadmaps/pdf/backend.pdf)
- [DevOps Roadmap](https://roadmap.sh/static/roadmaps/pdf/devops.pdf)

**Comment by TalaatHarb** [comment]
The links are offline, 404

**Comment by Ayman97** [comment]
Please fix the links @kamranahmedse

**Comment by kamranahmedse** [comment]
Take it [from the repository](https://github.com/kamranahmedse/developer-roadmap) please. There are "Download PDF" buttons on top of each roadmap.
