### ISSUE TITLE
Change color of Tick for alternative option items.

### ISSUE THREAD

**Issue by KarthikSiddarth** [kamranahmedse/developer-roadmap#637]
#### What roadmap is this issue about?

- [ ] Frontend Roadmap
- [ ] Backend Roadmap
- [ ] DevOps Roadmap
- [x] All Roadmaps

#### What is this issue about?

- [ ] Discussion for a pull request I would want to open.
- [ ] Addition of a new item
- [ ] Removal of some existing item
- [ ] Changing in arrangement
- [x] General suggestion
- [ ] Sharing an Idea
- [ ] Something else

#### Please acknowledge the below listed

- [x] This is not a duplicate issue. I have searched and there is no existing issue for this.
- [x] I understand that these roadmaps are highly opinionated. The purpose is to not to include everything out there in these roadmaps but to have everything that is most relevant today comparing to the other options listed.
- [x] I have read the [contribution docs](../contributing.md) before opening this issue.

#### Enter the details about the issue here

Use of Red tick generally means ***do not use*** or ***not recommended***, here it is used to mention that the item is alternative options, my opinion is, people are used former type, so please consider changing the color of the Tick for items that are alternative options.

**Comment by kamranahmedse** [comment]
This has been fixed. Thank you for reporting!
