### ISSUE TITLE
Platform Engineering Road Map

### ISSUE THREAD

**Issue by eilonash92** [kamranahmedse/developer-roadmap#6401]
### Feature Description

Seems like Platform Engineering Road Map is missing.

Is there any plan to add it? If not, is there anyone from the community that works on it?
If not, I will start

**Comment by kamranahmedse** [comment]
@eilonash92 we do have it in our backlog but I am not sure when we will be launching it. Feel free to come up with something and we will see if we can publish it. Thank you!
