### ISSUE TITLE
Exceptions & exception handling

### ISSUE THREAD

**Issue by ArchitPant** [kamranahmedse/developer-roadmap#6404]
### Roadmap URL

https://roadmap.sh/python

### Suggestions

Can add exceptions and my opinion to make a new roadmap detailed on python 
From basic to intermidate to advanced

**Comment by kamranahmedse** [comment]
<img width="625" alt="image" src="https://github.com/user-attachments/assets/8ddb88c9-d7d4-4529-8e48-d7b13ea88af2">

We already have exceptions. And this does cover the topics from beginner to advanced
