### ISSUE TITLE
Height overflow hidding problem on Draw Roadmap

### ISSUE THREAD

**Issue by erensarac** [kamranahmedse/developer-roadmap#6411]
### What is the URL where the issue is happening

https://draw.roadmap.sh/**

### What browsers are you seeing the problem on?

Chrome, Other

### Describe the Bug

I'm using a 1366x768 monitor, which is the most common size for older devices. On my device, I can't see the Resource Button, Section components, and Submit Feedback button on the left components list. The issue could be due to overflow hiding depending on the list height. I'm using zoom-out to see the Resource Button, Section components, and Submit Feedback button on this list. We need a overflow scroll when the list height exceeds the device height for those using a 1366x768 monitor like mine. I can submit a pull request for this issue.

### I tested on this browsers using Windows 11
- Arc Version 127.0.6533.89
- Chromium Version 124.0.6328.0
- Chrome Version 127.0.6533.100

### Images
![1366x768 (2) ](https://github.com/user-attachments/assets/312586bd-bb56-476a-bd60-e620ed459aba)
![1366x768](https://github.com/user-attachments/assets/48306776-600a-48a2-b9a4-b1c2744c7cbc)

### Participation

- [X] I am willing to submit a pull request for this issue.

**Comment by arikchakma** [comment]
I will fix it soon, thank you for letting us know.
