### ISSUE TITLE
OAuth (4) password grant flow typo

### ISSUE THREAD

**Issue by Sean1127** [kamranahmedse/developer-roadmap#6423]
### What is the URL where the issue is happening

https://roadmap.sh/guides/oauth

### What browsers are you seeing the problem on?

Chrome

### Describe the Bug

In the png guide
### 4 Password Grant Flow

> Similar to the "Authorization Code Grant Flow" but user enters the credentials owned by **the the authorization server instead of the app.**

should be

> Similar to the "Authorization Code Grant Flow" but user enters the credentials owned by **the app instead of the authorization server.**

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by kamranahmedse** [comment]
Feel free to submit a PR. Thank you!
