### ISSUE TITLE
change URL in update sharing settings while inviting friends

### ISSUE THREAD

**Issue by satvikb-technovert** [kamranahmedse/developer-roadmap#6426]
### What is the URL where the issue is happening

https://draw.roadmap.sh/<id>

### What browsers are you seeing the problem on?

Chrome, Other

### Steps
1. Create a new roadmap
2. click on Update Sharing settings
3. Chose only friends in the pop up
4. When there are no friends the there is a link that says "Invite your friends to share roadmaps with."
5. Click on the Link

### Fix
The current URL is pointing to "https://draw.roadmap.sh/account/friends".
The URL needs to be changed to "https://roadmap.sh/account/friends" by removing the "draw" cname in the url.

### Participation

- [X] I am willing to submit a pull request for this issue.

**Comment by kamranahmedse** [comment]
This has been fixed. Thank you for reporting.
