### ISSUE TITLE
Request: Gen AI tool to summarize and score own/official roadmaps and to be displayed to each person GitHub/{user} 

### ISSUE THREAD

**Issue by iPoetDev** [kamranahmedse/developer-roadmap#6441]
### Feature Description

AI to generate custom, (speculative) roadmaps for Roadmaps.sh is great.

Request the AI or internal logic to inspect the own roadmaps, (say take 15 and summarise into one) and give a single or two roadmaps where there is a progress score over a certain threshold, and to x level of depth. This can be automate to update when a dependant road map updates.

Else this has to be manual on a customised one. 

Use case: To display on each person GitHub Profile and be useful for hiring managers, peers and or non-technical browsers of a GitHub profile from Roadmap.sh. Then sub and child official roadmaps linked of this generated AI summary roadmap.

(Checked all issues)

**Comment by iPoetDev** [comment]
I tried on my own profile. Works on large screen, do not for mobile viewing. There is a funky edge way of making such responsive by embedding into foreignObject element in SVG but for most this is too edge/innovative.

https://github.com/iPoetDev

**Comment by kamranahmedse** [comment]
Thank you, these are some nice ideas. I am going to close this issue and put it in the backlog for when we have some capacity to pick this up.

**Comment by iPoetDev** [comment]
Thank you.

I updated/remove the old card based views on my GitHub profile. I now use sheilds.io as a vertical layout as its is better on mobile.
