### ISSUE TITLE
Improvement suggestion! -Analyze web security!

### ISSUE THREAD

**Issue by Guillerbr** [kamranahmedse/developer-roadmap#646]
#### What roadmap is this issue about?

- [ ] Frontend Roadmap
- [ ] Backend Roadmap
- [ ] DevOps Roadmap
- [X] All Roadmaps

#### What is this issue about?

- [ ] Discussion for a pull request I would want to open.
- [X] Addition of a new item
- [ ] Removal of some existing item
- [ ] Changing in arrangement
- [ ] General suggestion
- [ ] Sharing an Idea
- [ ] Something else

#### Please acknowledge the below listed

- [X] This is not a duplicate issue. I have searched and there is no existing issue for this.
- [ ] I understand that these roadmaps are highly opinionated. The purpose is to not to include everything out there in these roadmaps but to have everything that is most relevant today comparing to the other options listed.
- [ ] I have read the [contribution docs](../contributing.md) before opening this issue.

Add a roadmap to the web security area.
In the same model as the previous ones, focusing on security for web applications, pentest and vulnerability analyzes and tools.

**Comment by kamranahmedse** [comment]
We already have a request for that logged in https://github.com/kamranahmedse/roadmap.sh/issues/36.

Would you be up for the contribution? It doesn't have to be visual, just [prepare the textual format](https://github.com/kamranahmedse/roadmap.sh/blob/master/contributing/roadmap.md) and we will do the rest.
