### ISSUE TITLE
DIscord Invite Link Expired

### ISSUE THREAD

**Issue by hchasens** [kamranahmedse/developer-roadmap#6463]
### What is the URL where the issue is happening

https://roadmap.sh/

### What browsers are you seeing the problem on?

Chrome

### Describe the Bug

Links to join the discord server from both github and roadmap.sh are expired. 

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by hchasens** [comment]
I believe this is an outage on discord's side as it's working now.

**Comment by dansholds** [comment]
Haha we refreshed it anyway!
