### ISSUE TITLE
nee (need)

### ISSUE THREAD

**Issue by sheralimuzaffarov** [kamranahmedse/developer-roadmap#648]
#### What roadmap is this issue about?

- [x] Frontend Roadmap
- [ ] Backend Roadmap
- [ ] DevOps Roadmap
- [ ] All Roadmaps

#### What is this issue about?

- [ ] Discussion for a pull request I would want to open.
- [ ] Addition of a new item
- [ ] Removal of some existing item
- [ ] Changing in arrangement
- [ ] General suggestion
- [ ] Sharing an Idea
- [x] Something else

#### Please acknowledge the below listed

- [x] This is not a duplicate issue. I have searched and there is no existing issue for this.
- [x] I understand that these roadmaps are highly opinionated. The purpose is to not to include everything out there in these roadmaps but to have everything that is most relevant today comparing to the other options listed.
- [x] I have read the [contribution docs](../contributing.md) before opening this issue.

#### Enter the details about the issue here

![Снимок](https://user-images.githubusercontent.com/35257303/73713653-f9e83080-472f-11ea-80c2-0c02de9d4ad2.PNG)

**Comment by AmeerTaweel** [comment]
I checked `src/frontend-map.json` and **"need"** is spelled correctly there. Please just update the image.

**Comment by kamranahmedse** [comment]
This has been fixed and will be published in the coming release. Thank you 🙏
