### ISSUE TITLE
Not rendering reference items when items are between two text

### ISSUE THREAD

**Issue by FarzadMohtasham** [kamranahmedse/developer-roadmap#6481]
### What is the URL where the issue is happening

https://roadmap.sh/react

### What browsers are you seeing the problem on?

Chrome

### Describe the Bug

I submitted a PR last week and I added Next.js and Remix.js contents to React roadmap (framework section), Today I noticed that after putting contents like article-video and others between text, render engine not adding badge to them!

You can check the below screenshot

![image](https://github.com/user-attachments/assets/8b550997-034d-4660-a20e-2114b62b1736)

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by FarzadMohtasham** [comment]
@kamranahmedse I wanted to fix this problem, But shows me: Private Component
Renderer is a private component. If you are a collaborator and have access to it. Run the following command:

![image](https://github.com/user-attachments/assets/57e5b3a5-80ae-4602-b283-8008cc11a868)

**Comment by kamranahmedse** [comment]
Fixed in https://github.com/kamranahmedse/developer-roadmap/commit/8d0a1db711cbabb6bb0917cd44f93a92d4f8b0d4
