### ISSUE TITLE
Homebanking API

### ISSUE THREAD

**Issue by fedeval98** [kamranahmedse/developer-roadmap#6495]
### What Roadmap is this project for?

Backend Roadmap

### Project Difficulty

Advanced

### Add Project Details

# Project Overview

You are required to build a RESTful Homebanking API that supports user and admin login, secure management of customer data, loans, bank accounts, and credit cards. The API will connect to an SQL database for storing user information, loans, credit cards, and associated accounts. It should include a built-in payment gateway that can interface with other applications. The API will allow users to download or receive their account statements via email in PDF format. Additionally, it must implement robust error handling, security measures, and user activity logging.

### RESTful API Design
- **Resource-Based Architecture:** Design the API to expose resources such as Users, Accounts, Loans, and Credit Cards as endpoints following REST principles.
- **HTTP Methods:** Use appropriate HTTP methods (GET, POST, PUT, DELETE) for each operation (e.g., GET for reading data, POST for creating resources).
- **Status Codes:** Return appropriate HTTP status codes to indicate the success or failure of operations (e.g., 200 for success, 404 for not found, 500 for server error).
- **URL Structure:** Design a clear and intuitive URL structure for accessing resources (e.g., `/users/{id}/accounts`, `/loans/{id}`).

### User and Admin Management
- **User Roles:** Implement different roles for users and administrators, each with specific permissions.
- **User Registration:** Provide functionality for user registration, including validation of user information.
- **Login System:** Implement a secure login system for both users and administrators.
- **Password Recovery:** Allow users to recover their passwords via a one-time-use email link that permits the user to set a new password.

### Security
- **Encryption:** Use encryption for sensitive data (e.g., passwords, credit card information).
- **Input Validation:** Ensure all inputs are validated to prevent SQL injection, cross-site scripting (XSS), and other common security threats.
- **Activity Monitoring:** Track user activities such as login attempts, transactions, and profile changes.

### Customer Management
- **Customer CRUD Operations:** Allow administrators to create, modify, and delete customer profiles. Deleted customers should not be removed from the database but marked as inactive or archived.
- **Loan Management:**
  - **Loan Application:** Users can apply for loans, but cannot apply for the same loan more than once if the previous one is unpaid.
  - **Loan CRUD Operations:** Administrators can create, modify, and delete loan offers.
- **Bank Account Management:**
  - **Account Creation:** Users can create up to three bank accounts.
  - **Account Deletion:** Users can delete bank accounts, but the data should not be permanently removed from the database.

### Credit Card Management
- **Credit Card Creation:** Users can create credit cards, which must generate unique card numbers and have an expiration date of 5 years from the creation date.
- **Card Management:** Allow users and admins to manage cards, including viewing details and deactivating them. Deleted cards should remain in the database but marked as inactive.

### Transactions and Payments
- **Internal Transfers:** Users can transfer money between their accounts or to other users' accounts. These transfers should be reflected in a user activity panel, categorized as either debit or credit.
- **Payment Gateway:** Implement a proprietary payment gateway that allows for secure transactions and can connect with external applications.

### Database Integration
- **SQL Database:** The API should connect to an SQL database to store user information, loans, accounts, and credit cards.
- **Data Persistence:** Ensure that all user and transaction data are stored securely and efficiently.

### Reporting and Notifications
- **Account Statements:** Users can download or receive their account statements as PDFs, either through direct download or via email.
- **Notifications:** Implement email notifications for important actions, such as successful transactions, account changes, or loan approvals.

### Logging and Error Handling
- **Error Handling:** Implement comprehensive error handling throughout the API, ensuring that users receive meaningful error messages without exposing sensitive information.
- **Logging:** Log all significant activities, including login attempts, transactions, and administrative actions.

## Constraints and Considerations
- **RESTful Compliance:** Ensure that the API follows REST principles, including statelessness, proper use of HTTP methods, and appropriate status codes.
- **User Experience:** The API should be user-friendly and provide clear instructions for usage.
- **Performance:** Ensure that the API handles large numbers of users and transactions efficiently.
- **Cross-Platform Compatibility:** The API should be compatible with various operating systems, including Windows, Linux, and macOS.
- **Documentation:** Provide well-organized and detailed documentation, including a user manual and API documentation for the payment gateway.

##

Working on this project will help you gain a deeper understanding of RESTful API design, database management systems, user authentication, and secure transaction handling. You will also learn about PDF generation, email integration, and error handling in complex systems. This project will enhance your skills in programming, API development, database management, and system security, preparing you for real-world challenges in Backend development.

##

My own repository as Example, the project used: 
Language: Java 17 
Framework: Spring boot 3.2.0
Build Tool: Gradle - Groovy
Data Base: PostgreSQL
Mail Sender: Spring boot Mail.
PDF: Apache PDFBox.
Security: Spring Security

https://github.com/fedeval98/Homebanking

As of today, August 11, 2024, I am working on the documentation for my API.

**Comment by XAGASKII101** [comment]
Can we have more of this

**Comment by kamranahmedse** [comment]
Thank you, we will look into this.
