### ISSUE TITLE
Incorrect scaling of the profile avatar in the wide card and profile activity page

### ISSUE THREAD

**Issue by Steindvart** [kamranahmedse/developer-roadmap#6503]
### What is the URL where the issue is happening

https://roadmap.sh/card/wide/65545e1968ca60261330fe9a?variant=dark

### What browsers are you seeing the problem on?

- Chrome (Brave browser)

### Describe the Bug

The profile avatar in the wide card is greatly compressed, instead of zooming in. It doesn't look good.

For example: https://roadmap.sh/card/wide/65545e1968ca60261330fe9a?variant=dark

#### Screenshots
![image](https://github.com/user-attachments/assets/f208b06b-28a5-49cc-869b-c3d07cea6bf3)
![image](https://github.com/user-attachments/assets/634c2331-e7d5-4b73-a86c-46b49c8dd863)

### Expected behavior
The avatar in wide card is expected to scale as it does in the profile picture.

#### Screenshots
![image](https://github.com/user-attachments/assets/81cdf6a3-d683-45b0-9140-c24e13bf4a6b)

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by Steindvart** [comment]
Also, I found the same behavior of profile picture in page with profile activity table (like in GitHub).

- URL: https://roadmap.sh/u/steindvart

![image](https://github.com/user-attachments/assets/b1428238-e704-4993-9405-8b7abbbcd0ef)
![image](https://github.com/user-attachments/assets/b4da0003-4695-4af8-b2b9-64acfcd540f3)

**Comment by kamranahmedse** [comment]
@arikchakma can you please have a look at this?

**Comment by arikchakma** [comment]
Sure I will have a look

**Comment by afzalimdad9** [comment]
I've submitted a fix for this issue in [PR #6778](https://github.com/kamranahmedse/developer-roadmap/pull/6778). The pull request addresses the incorrect scaling of the profile avatar in the wide card and profile activity page. Please review it when you have a chance. Thanks!

**Comment by arikchakma** [comment]
@Steindvart Please use a square image (400X400) so it doesn't compress.
