### ISSUE TITLE
Change Skill Profile - Profile URL 

### ISSUE THREAD

**Issue by Veronika181** [kamranahmedse/developer-roadmap#6507]
### What is the URL where the issue is happening

https://roadmap.sh/account/update-profile

### What browsers are you seeing the problem on?

Safari

### Describe the Bug

I'm experiencing an issue when trying to update my profile on the road.sh platform. Specifically, when I try to add a URL to my profile by copying and pasting, it doesn't work. If I manually enter a name instead, I get an error message that says, "Problem loading user!"

I also tried clearing my browser's cache by selecting "Empty Cache" in Safari, but the problem persists.

### Participation

- [X] I am willing to submit a pull request for this issue.

**Comment by kamranahmedse** [comment]
Thank you for reporting, it seems to be working fine for me. Could you please share a video recording? Also if you could share any logs from console/network tab response?

**Comment by Veronika181** [comment]
I'm sending the recording.However, I don't know where to find the URL for the user's profile on [roadmap.sh/u/.](http://roadmap.sh/u/.%22)"

Uploading Screen Recording 2024-08-12 at 11.36.10.mov…

**Comment by Veronika181** [comment]
Yes, I tried that too, and when I fill out the first profile, save my profile and then fill in the URL, it says "website must be a valid uri".
