### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by CJCODESgit** [kamranahmedse/developer-roadmap#6510]
### What is the URL where the issue is happening

https://roadmap.sh/blockchain

### What browsers are you seeing the problem on?

Chrome

### Describe the Bug

It shows a blank screen if a team member tries to visit the roadmap

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by kamranahmedse** [comment]
Was it an old team? We have had a major revamp on the older roadmaps (they are now redrawn using our own editor). Can you remove the roadmap and add it to your team again? This should fix the issue.

**Comment by CJCODESgit** [comment]
It is a new team, i removed it and added it again, it is showing the roadmap but we can't access the learning materials, shows a blank space when you try to access learning materials

**Comment by CJCODESgit** [comment]
![Screenshot 2024-08-12 213018](https://github.com/user-attachments/assets/adbcd7ca-cf09-406c-bd6a-548a08c6e83c)
this is what it shows
