### ISSUE TITLE
When Using Template, the details of each step is not there

### ISSUE THREAD

**Issue by albeniraouf** [kamranahmedse/developer-roadmap#6511]
### What is the URL where the issue is happening

https://roadmap.sh/r/angular-hqfaf

### What browsers are you seeing the problem on?

Chrome, Microsoft Edge

### Describe the Bug

Opened Teams
Added new roadmap for angular from templates
the one created inside team has no details except the graph
as this  
![image](https://github.com/user-attachments/assets/9036ae34-2b25-426d-9de8-f8a76db56164)
but on the https://roadmap.sh/angular there are details there
![image](https://github.com/user-attachments/assets/fea75ac4-1158-41f4-8256-1906b3e66b91)

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by kamranahmedse** [comment]
We just implemented this feature yesterday. You should be able to copy roadmap content when adding team roadmap.
