### ISSUE TITLE
Skill title is hidden

### ISSUE THREAD

**Issue by brodriro** [kamranahmedse/developer-roadmap#6522]
### What is the URL where the issue is happening

https://roadmap.sh/android
https://roadmap.sh/full-stack
https://roadmap.sh/javascript

### What browsers are you seeing the problem on?

Chrome, Safari, Microsoft Edge

### Describe the Bug

Hi, currently the skill title is the same color as the container when the status is "Done".
![image](https://github.com/user-attachments/assets/5aff6481-cf38-4414-974d-9e4d0141b7d3)

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by castle2668** [comment]
this also happened in React Developer Roadmap (https://roadmap.sh/react)
