### ISSUE TITLE
Ngrx and not Ngr

### ISSUE THREAD

**Issue by daveBlue854** [kamranahmedse/developer-roadmap#653]
- [x] Frontend Roadmap
- [ ] Backend Roadmap
- [ ] DevOps Roadmap
- [ ] All Roadmaps

- [ ] Discussion for a pull request I would want to open.
- [ ] Addition of a new item
- [ ] Removal of some existing item
- [ ] Changing in arrangement
- [ ] General suggestion
- [ ] Sharing an Idea
- [x] Something else

- [x] This is not a duplicate issue. I have searched and there is no existing issue for this.
- [x] I understand that these roadmaps are highly opinionated. The purpose is to not to include everything out there in these roadmaps but to have everything that is most relevant today comparing to the other options listed.
- [x] I have read the [contribution docs](../contributing.md) before opening this issue.

In the frontend graph under Angular there is a square saying ngr, shouldn't it say ngrx??

**Comment by rafsanulhasan** [comment]
it should be ngRx instead of Ngrx

**Comment by kamranahmedse** [comment]
This has been fixed and will be published in the coming release. Thank you 🙏
