### ISSUE TITLE
update status 

### ISSUE THREAD

**Issue by ghost** [kamranahmedse/developer-roadmap#6534]
### What is the URL where the issue is happening

https://roadmap.sh/typescript

### What browsers are you seeing the problem on?

Chrome

### Describe the Bug

When we set the status to done, instead of drawing a line on it and displaying the text, the entire text color turns gray and nothing is displayed

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by fellalli** [comment]
Do you use a browser extensions that could cause that?

**Comment by siamonas** [comment]
This is probably already fixed. See Discord discussion [here](https://discord.com/channels/650223386039156756/1109830135256993834/1272830608833384514).
