### ISSUE TITLE
TOPIC NOT FOUND: INSERT AND DELETE

### ISSUE THREAD

**Issue by Hanzlah10** [kamranahmedse/developer-roadmap#6548]
### What is the URL where the issue is happening

https://roadmap.sh/sql

### What browsers are you seeing the problem on?

Firefox

### Describe the Bug

WHEN CLICKED INSERT OR DELETE PRESENT IN STATEMENTS IT SAYS TOPIC NOT FOUND

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by chibuike-19** [comment]
Would love to work on this issue, is it still open? @Hanzlah10
