### ISSUE TITLE
Add a more detailed video on java roadmap: "How JVM works?" step

### ISSUE THREAD

**Issue by Patzi275** [kamranahmedse/developer-roadmap#6552]
### Roadmap URL

https://roadmap.sh/java

### Suggestions

[[ JVM Architecture ]](https://www.youtube.com/watch?v=QHIWkwxs0AI)

I'd like to suggest adding this video resource to the Java roadmap on the step "How jvm works". 
This 8 minutes video by BigDataELearning covers the following topics in depth: class Loader, runtime data area, and execution engine system and process . 
It is particularly useful for beginners developers.

**Comment by kamranahmedse** [comment]
Feel free to submit a PR. Thank you!
