### ISSUE TITLE
[Topic Not Found] DevOps Roadmap

### ISSUE THREAD

**Issue by jd-apprentice** [kamranahmedse/developer-roadmap#6561]
### What is the URL where the issue is happening

https://roadmap.sh/devops

### What browsers are you seeing the problem on?

Firefox

### Describe the Bug

Inside the DevOps roadmap in the `Application Monitoring` there is a link that is not working.

![image](https://github.com/user-attachments/assets/521e409e-204b-4615-8c1d-77480fea03fb)

This happens when you `Click` the `datadog` one.

### Output from browser console (if any)

![image](https://github.com/user-attachments/assets/be549d83-b563-4b73-8258-db1419813d43)

### Participation

- [X] I am willing to submit a pull request for this issue.

**Comment by kamranahmedse** [comment]
Fixed in https://github.com/kamranahmedse/developer-roadmap/commit/c2f91b5dba1103fa347a346e8777483cc30b5aca
