### ISSUE TITLE
Additions to Blockchain Roadmap.

### ISSUE THREAD

**Issue by cromewar** [kamranahmedse/developer-roadmap#6577]
### Roadmap URL

https://roadmap.sh/blockchain

### Suggestions

I would like to see Cyfrin Updraft Included under some of the nodes. Updraft is a leading education platform for smart contract developers and security researchers, and all the content on Updraft is free. 

Addition no nodes:
Basic Blockchain Knowledge: @video https://updraft.cyfrin.io/courses/blockchain-basics
Smart Contracts: @video https://updraft.cyfrin.io/courses/solidity
Smart Contract  Frameworks/Foundry: @video https://updraft.cyfrin.io/courses/foundry & https://updraft.cyfrin.io/courses/advanced-foundry
Security: @video https://updraft.cyfrin.io/courses/security & https://updraft.cyfrin.io/courses/formal-verification

Under Security/Tools, add a new Node: Aderyn, a rust-based open-source static analyzer tool: https://github.com/Cyfrin/aderyn

**Comment by kamranahmedse** [comment]
Thank you, we will add that.
