### ISSUE TITLE
Chrome 80 & SameSite & cookie

### ISSUE THREAD

**Issue by xgqfrms** [kamranahmedse/developer-roadmap#658]
# Chrome 80 & SameSite & cookie

> maybe will cause many website crashed, which not update there codes

![image](https://user-images.githubusercontent.com/7291672/75260360-77c9c400-5824-11ea-82d0-1f337176f26e.png)

#### What roadmap is this issue about?

- [x] Frontend Roadmap
- [ ] Backend Roadmap
- [ ] DevOps Roadmap
- [ ] All Roadmaps

#### What is this issue about?

- [ ] Discussion for a pull request I would want to open.
- [x] Addition of a new item
- [ ] Removal of some existing item
- [ ] Changing in arrangement
- [ ] General suggestion
- [ ] Sharing an Idea
- [ ] Something else

#### Please acknowledge the below listed

- [x] This is not a duplicate issue. I have searched and there is no existing issue for this.
- [x] I understand that these roadmaps are highly opinionated. The purpose is to not to include everything out there in these roadmaps but to have everything that is most relevant today comparing to the other options listed.
- [x] I have read the [contribution docs](../contributing.md) before opening this issue.

## refs: 

https://developers.google.com/web/updates/2019/12/devtools

https://auth0.com/blog/browser-behavior-changes-what-developers-need-to-know/

**Comment by kamranahmedse** [comment]
Thank you for reporting but this warning on [roadmap.sh](https://roadmap.sh) is being thrown by codefund and we can't do anything about it. I will report it to them, thank you for letting us know.
