### ISSUE TITLE
[Suggestion] Flutter - accessibility section

### ISSUE THREAD

**Issue by psstoyanov** [kamranahmedse/developer-roadmap#6582]
### Roadmap URL

https://roadmap.sh/flutter

### Suggestions

Hello there!

I believe it would be very helpful to add an accessibility section in the roadmap.

It can make a world of difference for visually impaired and/or people with motor control difficulties with just a few small adjustments in the layout design. 

Adding semantics for screen reader context is nice and easy to do.

A few more complex scenarios would be form validations, loading states, error prompts, async actions, etc. They do take time and effort but ultimately, they expand the reach of the application and can drastically improve the quality of the product in the long run.

**Comment by dansholds** [comment]
To clarify, are we talking adding a section to the flutter roadmap that goes over accessibility or are we talking about making the roadmap.sh website more accessible?

**Comment by psstoyanov** [comment]
A section to the Flutter roadmap that goes over accessibility 👍

I haven't thought about the accessibility of the website itself thus far 🙂

**Comment by FatumaA** [comment]
Interested in taking this up when the node is added!

**Comment by dansholds** [comment]
This can be added when the Flutter roadmap is migrated.
