### ISSUE TITLE
Pull Request from GitHub bot and keeping fork in sync

### ISSUE THREAD

**Issue by jdegand** [kamranahmedse/developer-roadmap#6590]
### Detailed Description

I synced my fork and then I noticed a PR for `/chore/update-content-json`.  After I merged the PR,  my fork is ahead of `master` although the content is the same.  I can make PRs, but there will be extra commits on each PR.  I am debating undoing the PR.  What command should I run and how can I fix this?  I tried resetting `head`, but that did not work.

**Comment by kamranahmedse** [comment]
Either revert the last commit using hard reset on your local and force push to your fork

```
git reset --hard HEAD^
git push origin master --force
```

Or delete and recreate a fork maybe?

**Comment by jdegand** [comment]
Thanks that worked.  The `reset --soft` I used didn't go far enough back in the history.
