### ISSUE TITLE
Missing CITATION.cff on GitHub Roadmap

### ISSUE THREAD

**Issue by juanpflores** [kamranahmedse/developer-roadmap#6595]
### Roadmap URL

https://roadmap.sh/git-github

### Suggestions

Can we add `CITATION files` in the docs section of the Git and GitHub roadmap? Would really help for people that are making open science projects 😉 

![Image](https://github.com/user-attachments/assets/02b936b8-16e5-4b62-bdbd-e6289e93b77c)

- [GitHub Docs](https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/about-citation-files)

**Comment by kamranahmedse** [comment]
This has been added. Thank you for reporting 🙏
