### ISSUE TITLE
Design roadmap dark patterns

### ISSUE THREAD

**Issue by VisShon** [kamranahmedse/developer-roadmap#6598]
### Roadmap URL

https://roadmap.sh/ux-design

### Suggestions

https://hallofshame.design/collection/

**Comment by dansholds** [comment]
Whats the purpose of this issue? You've just added a single link with no explanation?

**Comment by VisShon** [comment]
lemme add some content too then

**Comment by dansholds** [comment]
I understood what you meant a while after this 😅
