### ISSUE TITLE
Add Forecasting: Principles and Practice & Introduction to Statistical Learning

### ISSUE THREAD

**Issue by neilmartindev** [kamranahmedse/developer-roadmap#6604]
### Roadmap URL

https://roadmap.sh/ai-data-scientist

### Suggestions

Hello, the following free material Forecasting: Principles and Practice from Monash University in Australia provides in-depth material for learning the basics of statistics and is widely recommended on Reddit: https://otexts.com/fpp3/

For machine learning, Introduction to Statistical Learning: https://www.statlearning.com/ is also well regarded and provides the student with a good base of machine learning concepts and application in either R or Python.

**Comment by dansholds** [comment]
Feel free to submit a PR to add these.
