### ISSUE TITLE
discord invite link not working

### ISSUE THREAD

**Issue by arimtiaz** [kamranahmedse/developer-roadmap#6610]
### What is the URL where the issue is happening

https://discord.com/invite/ZrSpJ8zH

### Describe the Bug

discord invite link isnt working

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by kamranahmedse** [comment]
It seems to be working fine for me. What error do you get?

**Comment by siamonas** [comment]
I'm experiencing the same error. 
![Screenshot_20240817_005547_Discord.jpg](https://github.com/user-attachments/assets/138e8b9d-f277-4a59-93df-1b2b909b45c6)

**Comment by kamranahmedse** [comment]
That's strange, the URL was set to "Never expire". I have fixed this in https://github.com/kamranahmedse/developer-roadmap/commit/ec06adb01a44b0a281dd8370a838c58b4265ca7a — @arimtiaz [you can use this url](https://discord.gg/GBY7zEc3uB),

**Comment by arimtiaz** [comment]
its the same error. 
<img width="1503" alt="Screenshot 2024-08-17 at 11 07 34 AM" src="https://github.com/user-attachments/assets/4c4a34d0-bb13-4a1c-8883-0eaea88e648c">

**Comment by siamonas** [comment]
@kamranahmedse I am following this Reddit and apparently 'Discord invites being expired' is a common issue.

A user claims to have solved this [here](https://www.reddit.com/r/discordapp/s/Co684oHmzA).
