### ISSUE TITLE
Community and AI Roadmaps bookmark feature same as official roadmaps

### ISSUE THREAD

**Issue by ddipayan00** [kamranahmedse/developer-roadmap#6622]
### Feature Description

User should be able to download Community Roadmaps and bookmark them in a separate community roadmaps space

User should be able to bookmark AI Roadmaps in a separate community roadmaps space

For Community and AI Roadmaps add one dedicated bookmark button

**Comment by kamranahmedse** [comment]
I am closing it since it is not a high priority feature at the moment. We will do it once we redesign these pages.
