### ISSUE TITLE
Frameworks for Backend

### ISSUE THREAD

**Issue by meh9184** [kamranahmedse/developer-roadmap#663]
#### What roadmap is this issue about?

- [ ] Frontend Roadmap
- [x] Backend Roadmap
- [ ] DevOps Roadmap
- [ ] All Roadmaps

#### What is this issue about?

- [ ] Discussion for a pull request I would want to open.
- [x] Addition of a new item
- [ ] Removal of some existing item
- [ ] Changing in arrangement
- [ ] General suggestion
- [ ] Sharing an Idea
- [ ] Something else

#### Please acknowledge the below listed

- [x] This is not a duplicate issue. I have searched and there is no existing issue for this.
- [x] I understand that these roadmaps are highly opinionated. The purpose is to not to include everything out there in these roadmaps but to have everything that is most relevant today comparing to the other options listed.
- [x] I have read the [contribution docs](../contributing.md) before opening this issue.

#### Enter the details about the issue here

Just my personal opinion! What do you think of adding paths to backend frameworks like express, django, rails, laravel, spring after "learn a language" component in backend?

**Comment by varlevi** [comment]
I agree that these would be good to add, but maybe a little farther on in the roadmap. Maybe after Databases and APIs?

**Comment by coldSeattle** [comment]
I thinking it would be good and maybe add some new ways for front-end and back-end delevopers and get other users make themselves choose more currently.
Maybe for front-end developers like front-end developers(React(deep dive roadmap..), ...)

**Comment by varlevi** [comment]
@coldSeattle - sounds like a good idea, maybe open a new issue?

**Comment by coldSeattle** [comment]
Why not?!) Already created!)

**Comment by varlevi** [comment]
@coldSeattle - Looks good!

**Comment by coldSeattle** [comment]
Thanks!

**Comment by coldSeattle** [comment]
Also you can follow me if you like what i am done and gonna doing:)

**Comment by varlevi** [comment]
@coldSeattle - I perfer to check out people's work before following them. I'll make that decision when I see your work, notyour comments on another project's issue.

**Comment by meh9184** [comment]
Thanks for good ideas! I'll close this issue, and hope your new created issue well process!!
