### ISSUE TITLE
Node telling people how to make games at the beggining of the gamedev roadmap.

### ISSUE THREAD

**Issue by pyoneerC** [kamranahmedse/developer-roadmap#6651]
### Feature Description

I've seen countless people that don't know how to start a project properly. They dismiss the importance of a good greybox for getting feedback. The majority of hobbist and students just grab a ton of 8k assets from the marketplace and end up ditching the project because ofchanging requirements. It's time this come to an end. That's why i suggest putting this at the very beggining of the roadmap, teaching people that games are akin to a cake: you start with the flour, the eggs, taste it, gather feedback, takes a lot of time and it's very rewarding at the end, and you present a slice of that cake to publishers and investors (thats why its called a vertical slice). You don't start with the chocolate chips and the sprinkles, because the cake will eventually collapse as it has no base. Seriously. Game development is hard, but it's even harder when you do the steps in reverse. Thanks for reading and I ask you to add this asap. People spend a lot of time gathering the sprinkles and end up ditching the project. This advice is key for gamedevs. Thanks everyone and please express your thoughts below on this proposal

**Comment by kamranahmedse** [comment]
The game developer roadmap we have is a more theoretical one. We are planning on roadmaps for "Unity3D", "Unreal Engine" etc and will add these things to that roadmap. Thank you for suggestion!
