### ISSUE TITLE
Questions Regarding Community Standards

### ISSUE THREAD

**Issue by offensive-vk** [kamranahmedse/developer-roadmap#6662]
### Detailed Description

# Two Points Left :
![image](https://github.com/user-attachments/assets/c819f27c-9081-4530-bd4a-62e88145ede0)

Why there is no Security Policy and a PR Template for this Repo?
*I mean there should be one, right?*

**Comment by kamranahmedse** [comment]
We will look into adding those. Thank you for pointing it out.
