### ISSUE TITLE
Topic Not Found - MongoDB

### ISSUE THREAD

**Issue by offensive-vk** [kamranahmedse/developer-roadmap#6663]
### What is the URL where the issue is happening

https://roadmap.sh/mongodb

### What browsers are you seeing the problem on?

Chrome

### Describe the Bug

Topic is not found or unreachable in MongoDB Roadmap.
See clip below

https://github.com/user-attachments/assets/e197ee05-c710-41e5-ac82-93717891f590

:

and more:
![image](https://github.com/user-attachments/assets/26c64cf5-20b7-46d4-9c1f-faa7415fdb34)

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by kenshanta** [comment]
This is a replica of an older(still ongoing) [issue](https://github.com/kamranahmedse/developer-roadmap/issues/6289).

Please close it
