### ISSUE TITLE
Content and Links keep being deleted even after the 'Save Roadmap' is clicked

### ISSUE THREAD

**Issue by yeab-dev** [kamranahmedse/developer-roadmap#6671]
### What is the URL where the issue is happening?

https://roadmap.sh/r/dart-swb7z

### What browsers are you seeing the problem on?

Thorium on Arch Craft (Linux)

### Describe the Bug

I was creating a roadmap for the dart programming language. I created a subtopic called data types and values under the topic Syntax Basics and added some content and a link to it. After saving what I wrote I visited some websites and when I return to the tab of my roadmap the content is gone. It happened twice and both times after creating a link.

**Comment by kamranahmedse** [comment]
@yeab-dev could you please record and share a video? I have been using the editor on daily basis and it never happened to me

**Comment by ahofmeister** [comment]
Just btw I can confirm the same using Arc Browser (if this helps).

**Comment by ahofmeister** [comment]
[Screen Recording 2024-08-15 at 12.50.16.zip](https://github.com/user-attachments/files/16658874/Screen.Recording.2024-08-15.at.12.50.16.zip)

Here is a screen recording. I had to zip it, because its size is bigger than the allowed size for GitHub (10 MB).

**Comment by arikchakma** [comment]
@ahofmeister @yeab-dev could you please have a look, and let me know.

**Comment by yeab-dev** [comment]
Okay thank you I think It's gone now It's working.

**Comment by arikchakma** [comment]
> It seems fixed, yes. Can you please point me to the commit/PR? Really curious what the issue was. :)

Unfortunately, that repo is private, it was an issue with form validation. We were sending empty content initially that's why.

**Comment by ahofmeister** [comment]
@arikchakma I see! Did not know, that it is private. That explains why so many issues are just resolved without linking anything. Thanks for clarifying that! :)
