### ISSUE TITLE
What does "I wouldn't recommend" mean?

### ISSUE THREAD

**Issue by anticafe** [kamranahmedse/developer-roadmap#668]
#### What roadmap is this issue about?

- [ ] Frontend Roadmap
- [ ] Backend Roadmap
- [ ] DevOps Roadmap
- [x] All Roadmaps

#### What is this issue about?

- [ ] Discussion for a pull request I would want to open.
- [ ] Addition of a new item
- [ ] Removal of some existing item
- [ ] Changing in arrangement
- [x] General suggestion
- [ ] Sharing an Idea
- [ ] Something else

#### Please acknowledge the below listed

- [x] This is not a duplicate issue. I have searched and there is no existing issue for this.
- [x] I understand that these roadmaps are highly opinionated. The purpose is to not to include everything out there in these roadmaps but to have everything that is most relevant today comparing to the other options listed.
- [x] I have read the [contribution docs](../contributing.md) before opening this issue.

#### Enter the details about the issue here
I not sure about the meaning of "I wouldn't recommend". Does it mean these technologies is about to deprecated? Or it's not necessary to learn about it the current roadmap? Or you just don't think it's important?

I think you should add a clarification in the README about the meaning of this sentence, in order not to make readers confused.

Thank you for creating a great roadmap like this.

**Comment by kamranahmedse** [comment]
Hey @anticafe – it is just based on my personal opinion. They are not necessarily deprecated or anything, it's just that I think there are better options that are more in demand as compared to the ones listed. I will clarify that better in the readme. Thanks!
