### ISSUE TITLE
Git & GitHub: Consider replacing (or just adding) `git filter-branch` with `git filter-repo`

### ISSUE THREAD

**Issue by siamonas** [kamranahmedse/developer-roadmap#6723]
### Roadmap URL

https://roadmap.sh/git-github

### Suggestion
I would like to suggest updating the Git & GitHub roadmap by replacing the subtopic on `git filter-branch` with `git filter-repo`. The `git filter-branch` command is known to be error-prone and has performance issues when handling large repositories. The Git project itself discourages its use, promoting `git filter-repo` as a more powerful, safer, and faster alternative for rewriting history.

### Caveat
However, there is one caveat: `git filter-repo` is not natively installed with Git, unlike git filter-branch. Instead, it is a Python script that needs to be installed separately. Fortunately, it can be easily installed via popular package managers.

### Proposed Changes
- Replace the existing section on `git filter-branch` with guidance and examples using `git filter-repo`.

Supporting Information
- `git filter-repo` GitHub [repository](https://github.com/newren/git-filter-repo)
- `git filter-repo` is actively promoted by the Git project as the recommended alternative to git filter-branch.

This update will help ensure that learners and developers use modern and more reliable tools for repository filtering and history rewriting tasks.

**Comment by dansholds** [comment]
FYI you have the ability to do this change yourself in a PR
