### ISSUE TITLE
Python Developer Roadmap -> Decorators

### ISSUE THREAD

**Issue by LakshX413** [kamranahmedse/developer-roadmap#6727]
### Detailed Description

Not an issue, but a suggestion. The [video](https://www.youtube.com/watch?v=FXUUSfJO_J4) that you have linked for decorators is a bit complicated for newbies.
I found [this](https://www.youtube.com/watch?v=r7Dtus7N4pI) video to be much more newbie friendly explanation of decorators and also covered the same content as your existing video. Suggestion is to replace your old video with this video.

Note - I am not affiliated to Kite in any capacity, just learning Python.

**Comment by dansholds** [comment]
Hey @LakshX413, totally not a bot just SUPER fast, You can open a PR to swap these videos out yourself! 🤙

**Comment by LakshX413** [comment]
That is SUPER fast. Guide me on PR please.
