### ISSUE TITLE
Improvements for the blockchain developer topic

### ISSUE THREAD

**Issue by ishaaqziyan** [kamranahmedse/developer-roadmap#6746]
### Roadmap URL

https://roadmap.sh/blockchain

### Suggestions

I highly suggest adding the following:
Blockchains --> [Internet Computer
](https://internetcomputer.org/)Blockchains --> Solana --> [Anchor Framework](https://www.anchor-lang.com/)
General Blockchain Knowledge --> [Distributed Computing Concepts](https://www.coursera.org/learn/blockchain-scalability)

Thanks.

**Comment by kamranahmedse** [comment]
Please have a look at the contribution docs and feel free to submit a PR.
