### ISSUE TITLE
Roadmap: Data Engineering

### ISSUE THREAD

**Issue by khushalt** [kamranahmedse/developer-roadmap#6755]
### Feature Description

Can we add a Detailed roadmap for Data Engineering

**Comment by kamranahmedse** [comment]
We are now closing any issues requesting new roadmap requests to clean up the issues. 

However, this doesn't mean that the requested roadmap won't be added to the website. We are putting it in the backlog and will add it to the website depending on how it ranks in the backlog or sooner if we find someone interested in adding that roadmap. Thank you for the request though! 🙏

**Comment by matheustecchio** [comment]
I would love to see it. @kamranahmedse

**Comment by pedroarthuralvesdeoliveira** [comment]
Any updates on this?
