### ISSUE TITLE
SQL Roadmap: duplicate nodes for the same topics. (select, update, delete, insert) 

### ISSUE THREAD

**Issue by kenshanta** [kamranahmedse/developer-roadmap#6762]
### Roadmap URL

https://roadmap.sh/sql

### Suggestions

<img width="971" alt="Screenshot 2024-08-22 at 11 55 37 PM" src="https://github.com/user-attachments/assets/b80c2add-a6fc-4878-bc9d-73787edf168c">

The ones on the top teft corner under "Statements" are empty. And i believe should be removed since they are covered on the bottom right section

**Comment by kamranahmedse** [comment]
It's not a bug, we need to fill them up. Also, no need to delete since both are talking about them in different contexts.

**Comment by kenshanta** [comment]
Even after some research, I still i don't understand the difference between them in the contexts of `DML` and as `Basic SQL Syntax`?

As a fellow user of the roadmap and it's resources, I'd like to get to the bottom of this discrepancy so the nodes can be filled with the proper information.
_FYI_ @kamranahmedse 
 
Thanks in advance! 🍻
