### ISSUE TITLE
Quant Roadmap - General

### ISSUE THREAD

**Issue by Quant-Questions** [kamranahmedse/developer-roadmap#6763]
### What is the title of the roadmap you are submitting?

Quant Researcher/Trader/Developer

### Roadmap Link

https://roadmap.sh/r/everything-you-need-to-know-to-become-a-quant-researcher

Note: This is a generic roadmap, will continue updating and adding more resources to best help users -- got some good traction and people on reddit really seemed to like it so submitting it here too.

**Comment by kamranahmedse** [comment]
Thank you for sharing it with us. I will put it in the backlog and we will take a look.

**Comment by Quant-Questions** [comment]
Hey Kamran,

Just curious what can i do to get the roadmap approved?
Also is there any other way I can make it so that others can see the
roadmap publicly if not this way?
