### ISSUE TITLE
Missing Tag Style in JS roadmap 'Error Objects' content

### ISSUE THREAD

**Issue by iliAsghar** [kamranahmedse/developer-roadmap#6770]
### What is the URL where the issue is happening

https://roadmap.sh/javascript

### What browsers are you seeing the problem on?

Microsoft Edge

### Describe the Bug

In the 'Error Objects' block of JS roadmap, the related links are not at the end of the content, which results in them not having proper styling (I think).

here's the screenshot I took ( Microsoft edge) : 
![image](https://github.com/user-attachments/assets/4d0cf453-c85b-47bf-8eb8-46c8bebec26a)

### Participation

- [X] I am willing to submit a pull request for this issue.

**Comment by offensive-vk** [comment]
I see, its happening in chrome and brave too.

**Comment by offensive-vk** [comment]
## oi @iliAsghar,  
You may now be able to see the content clearly. 🤗
*Keep moving forward and learning with roadmap.sh.*

![image](https://github.com/user-attachments/assets/fadec86f-2db9-41c7-91f6-cab2fa393302)

## Happy Coding !
