### ISSUE TITLE
Replace "Component Life Cycle" References with Functional Components

### ISSUE THREAD

**Issue by iamdejan** [kamranahmedse/developer-roadmap#6771]
### Roadmap URL

https://roadmap.sh/react

### Suggestions

The existing references to learn component lifecycles are outdated, because they refer to old paradigm of class component. I've found a new reference which explains the component lifecycles for functional components.

New references:
- [React component lifecycle: React lifecycle methods & hooks](https://tsh.io/blog/react-component-lifecycle-methods-vs-hooks/)
- [The React lifecycle: methods and hooks explained](https://retool.com/blog/the-react-lifecycle-methods-and-hooks-explained#react-hooks-and-the-component-lifecycle)
- [React Lifecycle: Methods & Hooks In Detail](https://www.bairesdev.com/blog/react-lifecycle-methods-hooks/)

Do let me know if these are not a 100% replacement for the existing references.

**Comment by Agnish1611** [comment]
Hey, I would like to work on this issue. PLease assign it to me.

**Comment by VANSH3104** [comment]
@iamdejan first URL is not working

**Comment by iamdejan** [comment]
> @iamdejan first URL is not working

@VANSH3104 Which one is it? The "React component lifecycle: React lifecycle methods & hooks" one? I can open it just fine.
<img width="1512" alt="image" src="https://github.com/user-attachments/assets/4c1687db-bc22-4f44-8641-004ce8af8a10">

**Comment by devXpraAddy** [comment]
hey, i would like to work on this issue pls assign me this

**Comment by dansholds** [comment]
Content links have been added, it's also important to remember that just because something is outdated, it doesn't mean it should be removed as it will still exist in the wild.
