### ISSUE TITLE
Typo in JavaScript roadmap

### ISSUE THREAD

**Issue by kauajuno** [kamranahmedse/developer-roadmap#6773]
### What is the URL where the issue is happening

https://roadmap.sh/javascript

### Describe the Bug

Unary operators topic is listed as unary opeartors.
![image](https://github.com/user-attachments/assets/e214ee93-153d-4b23-b024-96e80d26607d)

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by afzalimdad9** [comment]
Hi everyone,

I've submitted a pull request (#6774) that addresses the typo in the JavaScript roadmap, correcting "Unary Opeartors" to "Unary Operators." Please review it at your convenience.

Thank you!

**Comment by kamranahmedse** [comment]
Thank you @afzalimdad9 for the PR!
