### ISSUE TITLE
[DevOps Roadmap]: Azure DevOps as CI/Cd Tool

### ISSUE THREAD

**Issue by kolosovpetro** [kamranahmedse/developer-roadmap#6782]
### Roadmap URL

https://roadmap.sh/devops

### Suggestions

Azure DevOps is a popular and widely used CI/CD tool, suggest to add it to CI/CD section

![image](https://github.com/user-attachments/assets/aebb3316-0f42-45f7-8ad2-f60459f1ef02)

**Comment by dansholds** [comment]
We have added this to our internal roadmap.
