### ISSUE TITLE
Missing Android roadmap topic - Android NDK (Native development kit)

### ISSUE THREAD

**Issue by github-monke** [kamranahmedse/developer-roadmap#6793]
### Roadmap URL

https://roadmap.sh/android

### Suggestions

Roadmap should include a node for the Android NDK.  
https://developer.android.com/ndk/  
Important for performance intensive applications. Such as video games.

**Comment by dansholds** [comment]
Where would you suggest this be placed?

**Comment by github-monke** [comment]
Perhaps something like this? https://roadmap.sh/r?id=66edd694e80161c4cbc8a1c8

![Screenshot_20240921_004500](https://github.com/user-attachments/assets/c06c2f87-36c9-4ca4-8d1a-6f0301472184)

The subtopics are for the most part covered by the NDK documentation itself: https://developer.android.com/ndk/guides

**Comment by dansholds** [comment]
CC @kamranahmedse I can give this a shot but you're far more skilled in the drawing aspect than I am 😅

**Comment by dansholds** [comment]
Added to our internal task list.
