### ISSUE TITLE
Theme

### ISSUE THREAD

**Issue by KhurshidShod** [kamranahmedse/developer-roadmap#6794]
### Feature Description

Hi roadmap.sh team. I really love this website since it helps me to manage my time and everything in the way of learning frontend development. But it would great if you add dark theme in a single roadmap page. I think that everyone would prefer to work or read in dark theme and everyone likes it I hope.

**Comment by theChandrayMurmu** [comment]
Reading through the documentation as we progress our learning curve for long hours will surely strain our eyes, I agree with @KhurshidShod [feature](https://github.com/kamranahmedse/developer-roadmap/issues/new/choose) request—most developers love "dark mode" like most of us here. Even I would love to see the dark mode on the website.

---
![roadmap](https://github.com/user-attachments/assets/f5a337a3-c05b-4b44-8d18-0c7e6844cf7b)

I see that the website uses the **Tailwind UI Framework** so it shouldn't be hard to implement.
Tailwind Documentation: https://tailwindcss.com/docs/dark-mode

**Comment by Rach1507** [comment]
Hi , I would like to work on this !

**Comment by darthwalsh** [comment]
If it helps, I came across a [homepage redesign in dark mode post](https://dribbble.com/shots/11523222-roadmap-sh-dark-mode) by @kamranahmedse  (not sure if anything from 4 years ago is still relevant, though)

**Comment by KhurshidShod** [comment]
Looks great 👍

**Comment by dansholds** [comment]
We will take the request and discuss it internally 👍
