### ISSUE TITLE
Please add CMS Bitrix

### ISSUE THREAD

**Issue by rivetweb** [kamranahmedse/developer-roadmap#68]
https://dev.1c-bitrix.ru/learning/course/?COURSE_ID=43&CHAPTER_ID=04607&LESSON_PATH=3913.4607

Bitrix Framework is a PHP-based platform for developing Web applications. On this platform, 1C-Bitrix created two popular products: "1C-Bitrix: Site Management" and "1C-Bitrix: Corporate Portal."

https://dev.1c-bitrix.ru/learning/course/?COURSE_ID=43&CHAPTER_ID=03635

**Comment by lex111** [comment]
What for? I do not think that it needs to be added, because:
- It does not enjoy worldwide popularity, like Symfony
- Although there is support for PHP 7, but can not be called modern and good, again like Symfony

In this case, it is better to add, for example, Yii2.

**Comment by rivetweb** [comment]
bitrix24 which used worldwide - written in Bitrix Framework
https://www.bitrix24.com/online-domains-map

**Comment by lex111** [comment]
@rivetweb well, it shows the use of Bitrix24, i.e. CRM, and not as such a Bitrix framework (although of course it's CRM is done on this framework, but these are different things). And the more so it's a paid product, and the map shows mostly free tools.

**Comment by lex111** [comment]
And here is the answer of the author of the repository @kamranahmedse:

> I know there are many good frameworks (phalcon, yii, zend etc) out there which are missing but I intentionally included only the comparatively popular (and most demanded) ones.

https://github.com/kamranahmedse/developer-roadmap/pull/59#issuecomment-289256705

@rivetweb therefore, it is better to close this issue.
