### ISSUE TITLE
Test Automation Foundation for developing automated tests for WEB/API/Mobile & Desktop with different progrsmming languages.

### ISSUE THREAD

**Issue by rgroetz2** [kamranahmedse/developer-roadmap#6805]
### What is the title of the roadmap you are submitting?

Roadmap to learn Test Automation for Web/Api/Mobile & Desktop.

### Roadmap Link

Link to roadmap: https://roadmap.sh/r/pi-tribe-athena-test-automation

Unfortunately, the link has the name from the initial name (pi-tribe-athena-test-automation). I did not found the possibility to change that. 

This is the first version to get all the necessary files into the repo. in the next steps the roadmap will be extended with additional test automation basic stuff and stuff for different adapters (Web/Api/Mobile/Desktop,...) with different frameworks (Selenium, Playwright, RobotFramework...) and programming languages (Java, JavaScript, Python...).

**Comment by dansholds** [comment]
This roadmap is restricted and cannot be viewed
