### ISSUE TITLE
missing space between "datastructure" in Heap Sort(Data Structure and Algorithm roadmap)

### ISSUE THREAD

**Issue by zhougangjie** [kamranahmedse/developer-roadmap#6809]
### Detailed Description

In Data Structure and Algorithm roadmap, there is a sentence "**It utilizes a datastructure known as a ‘binary heap’,** , it seems that a space is needed between **_datastructure_**

**Comment by afzalimdad9** [comment]
I've created PR #6810 to address the issue with the missing space between "data" and "structure" in the Heap Sort section of the Data Structure and Algorithm roadmap. This fixes the typo in the sentence, ensuring correct terminology is used. Please review and merge when possible. Thanks!
