### ISSUE TITLE
Broken "Black" subtopic on Python roadmap

### ISSUE THREAD

**Issue by prepin** [kamranahmedse/developer-roadmap#6811]
### What is the URL where the issue is happening

https://roadmap.sh/python

### Describe the Bug

**Bug:**
When attempting to access the "Black" node under the Code Formatting subtopic on the Python roadmap page, the page displays a "Topic not found" error instead of the expected content.

**Probable cause:**
The black.md file in the roadmaps/python/content directory appears to be missing an ID in its name, which might be causing the issue.

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by dansholds** [comment]
@prepin All done, the issue here was that the black subtopic file was just called `black.md` instead of `black@[id].md` which caused the issue.
