### ISSUE TITLE
Projects for Teams

### ISSUE THREAD

**Issue by wesleycoder** [kamranahmedse/developer-roadmap#6815]
### Feature Description

The Projects features are great and I like the idea of having Projects for teams to engage the team on custom challenges.

**Comment by dansholds** [comment]
You can of course collaborate on the existing projects together, as a team, on GitHub but I assume that what you're after is the ability to submit a project as a team?

You could still do this by all submitting the same repo link that you collaborated in until this potentially becomes a feature.

**Comment by wesleycoder** [comment]
Yes! That's what I meant, thanks for the recommendation, this might work, I'll refer it to my team, thanks.
