### ISSUE TITLE
TDD missing in Software Design Architecture

### ISSUE THREAD

**Issue by shaxaaa** [kamranahmedse/developer-roadmap#6828]
### Roadmap URL

https://roadmap.sh/software-design-architecture

### Suggestions

We are missing the TDD (Test Driven Design) though I'm not sure where exactly to put it.

**Comment by dansholds** [comment]
![Screenshot 2024-09-16 at 12 51 13](https://github.com/user-attachments/assets/3ea803e3-d482-458a-b760-aa5e792d3dcd)

Testing is covered in the prerequisite roadmap "Backend"
