### ISSUE TITLE
Clicking on block: Topic not found.

### ISSUE THREAD

**Issue by AyushmanOfficial** [kamranahmedse/developer-roadmap#6837]
### What is the URL where the issue is happening

https://roadmap.sh/flutter

### What browsers are you seeing the problem on?

Firefox, Chrome

### Describe the Bug

In this roadmap if i click on the 3 trees block inside flutter internals it says topic not found so i can't update the status

### Output from browser console (if any)

Opening the console in chrome devtools or firefox it says 

```
flutter/flutter-internals/3-trees:1 
        
        
       Failed to load resource: the server responded with a status of 404 ()
```

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by Drex72** [comment]
I see, its happening in chrome 
I'll work on it and what i can do.
Thanks for pointing it out 🙌

**Comment by AyushmanOfficial** [comment]
Feels good creating my first github issue and seeing it resolve so fast!

**Comment by AyushmanOfficial** [comment]
Feels good creating my first github issue and seeing it resolve so fast! :heart:
