### ISSUE TITLE
Machine Learning Developer Roadmap

### ISSUE THREAD

**Issue by moritzWa** [kamranahmedse/developer-roadmap#684]
#### What roadmap is this issue about?

- [ ] Frontend Roadmap
- [ ] Backend Roadmap
- [ ] DevOps Roadmap
- [x] All Roadmaps

#### What is this issue about?

- [ ] Discussion for a pull request I would want to open.
- [ ] Addition of a new item
- [ ] Removal of some existing item
- [ ] Changing in arrangement
- [ ] General suggestion
- [x] Sharing an Idea
- [ ] Something else

#### Please acknowledge the below listed

- [x] This is not a duplicate issue. I have searched and there is no existing issue for this.
- [x] I understand that these roadmaps are highly opinionated. The purpose is to not to include everything out there in these roadmaps but to have everything that is most relevant today comparing to the other options listed.
- [x] I have read the [contribution docs](../contributing.md) before opening this issue.

#### Enter the details about the issue here

I would love to have an overview which mathematical concept I need to grasps and what libraries exist etc.
I think levering Machine Learning as a Web-, Backend-, and Frontend Developer will become more common.

**Comment by exequielrafaela** [comment]
@codeuniversity / @moritzWa / @kamranahmedse 

I've recently seen @chris-chris has done an outstanding, Open Source :heart: :ledger: MIT licensed, [Machine Learning Engineer Roadmap - 2020](https://github.com/chris-chris/ml-engineer-roadmap). May be it can be taken as reference or even considering joining efforts to release this Roadmap at https://roadmap.sh/  

Thanks everyone for this great initiatives :100:

**Comment by kamranahmedse** [comment]
We are now closing any issues requesting new roadmap requests to clean up the issues. 

However, this doesn't mean that the requested roadmap won't be added to the website. We are putting it in the backlog and will add it to the website depending on how it ranks in the backlog or sooner if we find someone interested in adding that roadmap. Thank you for the request though! 🙏
