### ISSUE TITLE
Intro to Linux link is no longer working

### ISSUE THREAD

**Issue by lh-sc** [kamranahmedse/developer-roadmap#6840]
### What is the URL where the issue is happening

https://roadmap.sh/linux

### What browsers are you seeing the problem on?

Safari

### Describe the Bug

The following link is unavailable: https://www.linkedin.com/pulse/intro-linux-fundamentals-what-hillary-nyakundi-4u7af/

It's found here: Navigation basics > Article > Intro do Linux [[https://www.linkedin.com/pulse/intro-linux-fundamentals-what-hillary-nyakundi-4u7af/] 

### Output from browser console (if any)

Simple error messages stating that the page is no longer available. 

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by kenshanta** [comment]
I tried on the macbook running brave-browser(based on chromium) and the link is working.

Maybe retry with VPN?

**Comment by lh-sc** [comment]
Appreciate your taking your time to check it.
