### ISSUE TITLE
Adding style_guides.md documentation.

### ISSUE THREAD

**Issue by kenshanta** [kamranahmedse/developer-roadmap#6858]
### Detailed Description

It would be nice for the `contributing.md` to have a link pointing at some style guides file, as mentioned in the "Not So Good" contributions' section.

[contributing.md](https://github.com/kamranahmedse/developer-roadmap/blob/master/contributing.md)
<img width="1401" alt="Screenshot 2024-08-28 at 1 33 33 PM" src="https://github.com/user-attachments/assets/b02aeb11-79fe-4f5d-a7bd-8bce8066da62">

**Comment by dansholds** [comment]
It exists at in the Contribution guide.

<img width="1054" alt="Screenshot 2024-08-28 at 13 18 47" src="https://github.com/user-attachments/assets/1c92b314-4f94-4cf4-a7ac-92e368b63ae0">
