### ISSUE TITLE
12 Factor Apps and Service Mesh

### ISSUE THREAD

**Issue by sridharpandu** [kamranahmedse/developer-roadmap#686]
#### What roadmap is this issue about?

- [ ] Frontend Roadmap
- [ X] Backend Roadmap
- [ ] DevOps Roadmap
- [ ] All Roadmaps

#### What is this issue about?

- [ ] Discussion for a pull request I would want to open.
- [ X] Addition of a new item
- [ ] Removal of some existing item
- [ ] Changing in arrangement
- [ ] General suggestion
- [ ] Sharing an Idea
- [ ] Something else

#### Please acknowledge the below listed

- [ X] This is not a duplicate issue. I have searched and there is no existing issue for this.
- [ X] I understand that these roadmaps are highly opinionated. The purpose is to not to include everything out there in these roadmaps but to have everything that is most relevant today comparing to the other options listed.
- [ X] I have read the [contribution docs](../contributing.md) before opening this issue.

#### Enter the details about the issue here

I would suggest that we include the following 

1. Twelve Factor Apps (https://12factor.net/)
2. Service Mesh (https://www.nginx.com/blog/what-is-a-service-mesh/)

These are higly scalable architectures and enterprises are adopting it gradually.

**Comment by sridharpandu** [comment]
I see that service mesh already finds a mention in the Back end roadmap

**Comment by tonnoz** [comment]
Less known but another possible add: https://3factor.app/

**Comment by kamranahmedse** [comment]
This has been fixed and will be published in the coming release. Thank you 🙏
