### ISSUE TITLE
Unresponsive Menu in Firefox

### ISSUE THREAD

**Issue by 7ze** [kamranahmedse/developer-roadmap#6861]
### What is the URL where the issue is happening

https://roadmap.sh/roadmaps

### What browsers are you seeing the problem on?

Firefox

### Describe the Bug

The toggle menu on the left which gives the selections `All Roadmaps`, `Absolute Beginners`, `Web Development` and the rest stops working and becomes unresponsive after you open any roadmap and navigate back to the previous page using browser's back button.

**Note:** So far this seems only a problem in Firefox(129.0.2), and I tried in Edge but it seems to work alright. I am not sure if this is the problem with this app or its underlying framework, or a browser specific problem.

### Participation

- [X] I am willing to submit a pull request for this issue.

**Comment by dansholds** [comment]
closing as attached PR is merged.
