### ISSUE TITLE
Cybersecurity roadmap updates

### ISSUE THREAD

**Issue by khiz3r9** [kamranahmedse/developer-roadmap#6868]
### Roadmap URL

https://roadmap.sh/cyber-security

### Suggestions

# CTF Section updates:

- Add https://ctftime.org/ since it shows a updated list of all current and future CTF’s.

# Beginner Certification updates:

- Possibly remove CompTIA A+, Linux+ and CCNA considering that they aren’t directly related to cybersecurity but are a plus point to have. (Either have to edit the content to specify that or remove them, let me know if I should open a PR for that)

**Comment by khiz3r9** [comment]
# Advanced Certifications:

- Add PNPT by TCM Security.
- Add PWPT by TCM Security.
- Add CPTS by HTB.
- Add CBBH by HTB.
- Add CDSA by HTB.
- Add CWEE by HTB.

The certifications I listed above are not the **most** industry/HR recognized at the moment but do require rigorous testing and skills to prove to obtain them.

**Comment by khiz3r9** [comment]
# Fundamental IT Skills:

### Subsection with wireless communication technologies (NFC, WIFI…)

- Make Radio a section and add a few wireless technologies in it accordingly.
- Add RFID
- Add Cellular Networks
- Possibly add a few lesser known ones such as Zigbee, Z-wave, LoRa, WiGig, UWB. (Not really that important but for the sake of completion)

**Comment by khiz3r9** [comment]
# Common Attacks

- Add File Inclusion
- Rename “DoS vs DDoS” to “DDoS” and write inside as content about the differences, since that is how it is commonly referred.
- Add Broken Access Control (From OWASP Top 10)
- Add SSRF (From OWASP Top 10)
- Add Broken Access Control

**Comment by dansholds** [comment]
I have noted this all down in our backlog.
