### ISSUE TITLE
[BACKEND] Add Session Management

### ISSUE THREAD

**Issue by Asac2142** [kamranahmedse/developer-roadmap#6870]
### Roadmap URL

https://roadmap.sh/backend

### Suggestions

Besides knowing what is authentication/authorization, the types of it, how to handle it in your web service, etc... I think it should also add the topic for Session Management, what is SM, how to implement it, types of SM? 

I am someone who is learning backend, and I am not sure if SM is something relevant. I think it is an important topic to be learned.

**Comment by dansholds** [comment]
added to our internal board
