### ISSUE TITLE
Wrong markdown in Docker Roadmap - Union Filesystems' content

### ISSUE THREAD

**Issue by split-sec** [kamranahmedse/developer-roadmap#6877]
### Detailed Description

![image](https://github.com/user-attachments/assets/7cb8dfca-ad3b-4eb9-a253-327ac0ba4281)

[Docker Roadmap](https://roadmap.sh/docker)

Markdown intended to display the suggested resources is not valid and looks weird.

**Comment by split-sec** [comment]
![image](https://github.com/user-attachments/assets/9dc82f61-6c69-4a8c-a860-97d39f1e2405)

Looks fine now

**Comment by kenshanta** [comment]
If completed, close the issue please
