### ISSUE TITLE
AR Developer Roadmap

### ISSUE THREAD

**Issue by moritzWa** [kamranahmedse/developer-roadmap#688]
#### What roadmap is this issue about?

- [ ] Frontend Roadmap
- [ ] Backend Roadmap
- [ ] DevOps Roadmap
- [x] All Roadmaps

#### What is this issue about?

- [ ] Discussion for a pull request I would want to open.
- [ ] Addition of a new item
- [ ] Removal of some existing item
- [ ] Changing in arrangement
- [ ] General suggestion
- [x] Sharing an Idea
- [ ] Something else

#### Please acknowledge the below listed

- [x] This is not a duplicate issue. I have searched and there is no existing issue for this.
- [x] I understand that these roadmaps are highly opinionated. The purpose is to not to include everything out there in these roadmaps but to have everything that is most relevant today comparing to the other options listed.
- [x] I have read the [contribution docs](../contributing.md) before opening this issue.

#### Enter the details about the issue here

I would love to have an overview what are the common languages, what libraries exist etc.
I also think using AR Technologies Web-, Backend-, and Frontend Developer will become more common since in a few years the smartphone technologies will be even better and many people will be wearing smart glasses from Apple and co.  

There are already some Google searches [on this](https://www.google.com/search?sxsrf=ALeKk01m33M70d5TG4pRc_lhgs4oQrUI9Q%3A1585936786709&ei=knmHXp_rKsGhkwWE9LH4Cg&q=how+to+become+a+AR+Developer+Roadmap&oq=how+to+become+a+AR+Developer+Roadmap&gs_lcp=CgZwc3ktYWIQAzoECCMQJ1DjSFiDXmCIZGgBcAB4AIABkwGIAZkIkgEEMTYuMZgBAKABAaoBB2d3cy13aXo&sclient=psy-ab&ved=0ahUKEwif_Lr26szoAhXB0KQKHQR6DK8Q4dUDCAs&uact=5)

**Comment by alatella87** [comment]
+1

**Comment by maniac-tech** [comment]
I have previously worked on AR Projects for a while, I can help with the commonly used Tools and SDKs.

**Comment by soulhi9988** [comment]
> #### What roadmap is this issue about?
> 
> 
> 
> - [ ] Frontend Roadmap
> 
> - [ ] Backend Roadmap
> 
> - [ ] DevOps Roadmap
> 
> - [ ] All Roadmaps
> 
> 
> 
> #### What is this issue about?
> 
> 
> 
> - [ ] Discussion for a pull request I would want to open.
> 
> - [ ] Addition of a new item
> 
> - [ ] Removal of some existing item
> 
> - [ ] Changing in arrangement
> 
> - [x]General suggestion
> 
> - []Sharing an Idea
> 
> - [ ] Something else
> 
> 
> 
> #### Please acknowledge the below listed
> 
> 
> 
> - [ ]This is not a duplicate issue. I have searched and there is no existing issue for this.
> 
> - [ ]I understand that these roadmaps are highly opinionated. The purpose is to not to include everything out there in these roadmaps but to have everything that is most relevant today comparing to the other options listed.
> 
> - [ ] I have read the [contribution docs](../contributing.md) before opening this issue.
> 
> 
> 
> 
> 
> #### Enter the details about the issue here
> 
> 
> 
> I would love to have an overview what are the common languages, what libraries exist etc.
> 
> I also think using AR Technologies Web-, Backend-, and Frontend Developer will become more common since in a few years the smartphone technologies will be even better and many people will be wearing smart glasses from Apple and co.  
> 
> 
> 
> There are already some Google searches [on this](https://www.google.com/search?sxsrf=ALeKk01m33M70d5TG4pRc_lhgs4oQrUI9Q%3A1585936786709&ei=knmHXp_rKsGhkwWE9LH4Cg&q=how+to+become+a+AR+Developer+Roadmap&oq=how+to+become+a+AR+Developer+Roadmap&gs_lcp=CgZwc3ktYWIQAzoECCMQJ1DjSFiDXmCIZGgBcAB4AIABkwGIAZkIkgEEMTYuMZgBAKABAaoBB2d3cy13aXo&sclient=psy-ab&ved=0ahUKEwif_Lr26szoAhXB0KQKHQR6DK8Q4dUDCAs&uact=5)

**Comment by john-raymon** [comment]
+ 1
