### ISSUE TITLE
Add estimated time per roadmap

### ISSUE THREAD

**Issue by almagashi** [kamranahmedse/developer-roadmap#6880]
### Feature Description

When someone overviews a roadmap, provide estimated time for getting to the end of the road (i.e. 6 months at 10h/week). Even better so, provide the option for adding pace as a variable (for users to input), and calculate how many months or weeks that would take based on the pace (i.e. if roadmap_total = 100h, input_pace = 10 h / week, then result = 10 weeks).

**Comment by dansholds** [comment]
An outright time would not work as learning pace is really subjective but the whole "how many hours per X do you want to study?" could be an interesting concept, we will add it to our internal boards but just be aware that these kind of "nice to haves" are not an immediate priority for us atm.
