### ISSUE TITLE
Application security in Cybersecurity

### ISSUE THREAD

**Issue by sergiomarotco** [kamranahmedse/developer-roadmap#6900]
### Feature Description

Repo does not have info about: SSDLC, instruments like SAST, SCA, DAST, secret findnding, fizzing, IaaC security…

**Comment by sergiomarotco** [comment]
could you create a template of the empty page structure? and we would fill it in

**Comment by dansholds** [comment]
> could you create a template of the empty page structure? and we would fill it in

Content structure is in the contribution guide - https://github.com/kamranahmedse/developer-roadmap/blob/master/contributing.md 

I have added this to our internal board so it will be implemented on the next iteration of the roadmap 👍🏻
