### ISSUE TITLE
Adding some topics in cpp

### ISSUE THREAD

**Issue by Qas67** [kamranahmedse/developer-roadmap#6905]
### Roadmap URL

https://roadmap.sh/cpp

### Suggestions

I would like to add some topics to the cpp roadmap which are:-

**Function pointers in the pointers and References section**

**Comment by dansholds** [comment]
![Screenshot 2024-09-16 at 12 38 44](https://github.com/user-attachments/assets/15fef98f-73f9-4480-9338-b1e6c1452980)

This is already present.
