### ISSUE TITLE
License issue

### ISSUE THREAD

**Issue by Nax** [kamranahmedse/developer-roadmap#692]
#### What roadmap is this issue about?

- [ ] Frontend Roadmap
- [ ] Backend Roadmap
- [ ] DevOps Roadmap
- [x] All Roadmaps

#### What is this issue about?

- [ ] Discussion for a pull request I would want to open.
- [ ] Addition of a new item
- [ ] Removal of some existing item
- [ ] Changing in arrangement
- [ ] General suggestion
- [ ] Sharing an Idea
- [x] Something else

#### Please acknowledge the below listed

- [x] This is not a duplicate issue. I have searched and there is no existing issue for this.
- [x] I understand that these roadmaps are highly opinionated. The purpose is to not to include everything out there in these roadmaps but to have everything that is most relevant today comparing to the other options listed.
- [x] I have read the [contribution docs](../contributing.md) before opening this issue.

#### Enter the details about the issue here

This project's license is a mess.

1) The current license is, in effect, not `CC BY-NC-ND 3.0` at all, as the additional restrictions are completely contradictory with the base `CC BY-NC-ND 3.0` license. It makes it really hard to interpret the license correctly. That's exactly why most people use standard licenses in the first place.

2) The additional clauses are mostly irrelevant anyway since the project used to be `CC BY-NC-ND 3.0`, so it's possible to distribute at least the older version without abiding by any of the additional clauses.

3) This project has 35 collaborators, but it's license changed. It seems like the other collaborators still hold copyright over their contribution, since they did not, as far as I know, sign any document stating otherwise, so it's not clear how this license change can be considered legal.

4) CC BY-NC-ND 3.0 (and, presumably, the odd modified version as well) is an extremely poor choice of a license for this kind of project in the first place, since it doesn't seem possible to even contribute without a license violation, as submitting a pull request certainly sounds like distributing a modified or derived work to me.

5) CC BY-NC-ND 3.0 (and, presumably, the odd modified version as well) requires copyright attribution, but only a single name/copyright notice is present. There should be 34 more.

Please clarify this whole situation.

**Comment by kamranahmedse** [comment]
Thanks, @Nax for the concern.

I am not a lawyer, neither did I hire a lawyer to handle the licensing for the repository. The sole purpose of having the one that I have is to mainly avoid the misuse that I noticed. The TL;DR for the license is "free for personal use, can't be used for commercial purposes, can't be modified and distributed". Regarding the "people use standard licenses", yes people do that but people also don't do that if they don't see them fit for their use case. 

I have updated the license to clarify that better. Thank you!

**Comment by Nax** [comment]
This does not solve the issue at all. You can't unilateraly change the license once there is more than one copyright holder, and the other holders are not credited.

**Comment by kamranahmedse** [comment]
I am sure you probably already know what NC and ND mean in the license; **Non-Commercial**, **Non Derivatives**. Lots of people *were* misusing these roadmaps and promoting affiliate links and their courses with the inferior quality so although not the proper violation of but the "misuse" was there for sure. 

As far as your concerns about the license change, I am perfectly aware of how these license changes work. Everything prior to the 2019 launch is still licensed under CC-BY-NC-ND which means people can still use it given that they comply with the CC-BY-NC-ND terms; any new releases of the roadmap are no more licensed by CC-BY-NC-ND and are licensed under the new license that is available in the repository.
