### ISSUE TITLE
The progress of the profile roadmaps on the main roadmaps page.

### ISSUE THREAD

**Issue by Steindvart** [kamranahmedse/developer-roadmap#6933]
### Feature Description

Now we have information about the progress of the roadmaps on the profile page, in activity section.

![image](https://github.com/user-attachments/assets/498a0866-0384-4325-af2d-eed0a92c70c7)

It would be great to make a similar progress display on the main page of roadmaps. Now it's just a list of roadmaps with their names, without any information about their passage, completion.

![image](https://github.com/user-attachments/assets/6c1c79c0-034c-4b65-9cd1-704c480b6137)

### Benefits

Such a feature will allow everyone to better understand their global progress: what has already been studied and what needs to be studied, which "points of interest" have not yet been closed and where it is worth growing.

This will work especially well with grouping roadmaps by topic. For example, instead of making separate progress on "Frontend", I will also see that this roadmap is located in the "Web development" section and that there are related topics, for example "GraphQL", that I can study in order to develop not just as a "Frontend developer", but a broader specialist in web development.

**Comment by dansholds** [comment]
This issue is no longer relevant due to the home page change.
