### ISSUE TITLE
Are comments in the codebase allowed?

### ISSUE THREAD

**Issue by kenshanta** [kamranahmedse/developer-roadmap#6934]
### Detailed Description

Types of comments include:
- Explanation
- Tech-debt/Reminder
- Sectioning
- Documentation
- Legal/Licensing

[Latest Related PR](https://github.com/kamranahmedse/developer-roadmap/pull/6931)

**Comment by fellalli** [comment]
I'd say no for markdown files; Just useless data that we sent to the clients

**Comment by dansholds** [comment]
@kenshanta agreed with what @fellalli has said, adding comments to the MD files (such as your example) is pointless.

Adding comments to _actual_ code is valuable of course 🤙

**Comment by kenshanta** [comment]
> Adding comments to _actual_ code is valuable of course 🤙

I'd say, comments can almost always be - both from the reader and author's side - narrowed down to one single category: _unfinished_

Regardless, there are always special cases, right?

**Comment by dansholds** [comment]
It's also a good way of documenting in places that a README can't quite capture too, like specific behavior of certain functions etc, it's also good for marking areas that can be customized such as in boilerplates etc
