### ISSUE TITLE
Reused shared topic cards in different maps

### ISSUE THREAD

**Issue by Steindvart** [kamranahmedse/developer-roadmap#6935]
### Problem
Many roadmaps have overlapping topic cards that describe the same thing, but just in different roadmaps. For example, it can be Git, Internet (HTTP, DNS, etc), Databases (MySQL, PostgreSQL), and so on.

Because of this, the following problems arise:
1. Duplicate content. And as a result, there are difficulties with support and improvement, since you have to look for all the places where this content is duplicated.
2. The need to "click done" the topics you've covered every time in the new roadmaps you've started.

A similar problem was mentioned in:
- #3842 

### Suggestion
Make a mechanism for creating and linking shared topic-cards. So that it would be possible to create one card, for example about Git, and when added to a many roadmaps, it would be the same for everyone. Accordingly, the changes in this map were also displayed on all road maps where it is used.

I understand that this feature can be difficult to implement into an existing architecture. But, for the future development of the platform, I think this feature is an important thing to strive for.

**Comment by dansholds** [comment]
This is a valid request but will take a backseat to other priorities given that the impact is so low (you mentioned at least 50% of the impact is on the maintainers), we will add it to our internal roadmap though.
