### ISSUE TITLE
Transparency of Open Source Claims

### ISSUE THREAD

**Issue by parsa-xy** [kamranahmedse/developer-roadmap#6941]
### Detailed Description

I'm a learner who frequently uses GitHub to explore and learn from open-source projects. I recently started exploring roadmap.sh because it claims to be fully open source. However, I discovered that the roadmap editor, a core part of the platform, is housed in a private repository.

This inconsistency between the open-source claim and the reality of private code is disappointing. When a project presents itself as fully open source, it attracts a community eager to learn, contribute, and improve the platform. However, making essential parts of the code private after gaining community trust feels misleading and raises concerns about transparency.

Could the team clarify why this key part of the project is private despite the open-source claim? As someone who values learning and open collaboration, I believe it's crucial for the community to have clear and honest communication about what is truly open source.

**Comment by dansholds** [comment]
Hey @parsa-xy, thanks for taking the time to make this detailed post!

The team have addressed this before in this issue here - https://github.com/kamranahmedse/developer-roadmap/issues/3332

Hope this helps!

**Comment by parsa-xy** [comment]
Thanks for sharing @dansholds, but this doesn't really address the issue. It seems like you're avoiding the core problem. I understand that roadmaps can be used in various ways, but that’s not a justification for hiding the platform's functionality while claiming it's open source. Open source is about transparency, learning, and contribution, yet your project keeps essential parts hidden, which feels like an abuse of the community’s trust. I'm interested in understanding how the editor works and its architecture, not the roadmap content itself. This approach of using the community to grow your website without giving back is concerning and feels like a misuse of GitHub's purpose.

**Comment by dansholds** [comment]
Accusing this small and extremely dedicated team of abusing the community we have built over the last 7 years when we have provided free education to millions of develops around the world is _very_ disappointing.

Kamran was very clear about the reasons for keeping the editor private and this is a common practice of many an open-source and open-core project.

The only place we state that we are 100% open-source is on the about page, which admittedly shouldn't exist anymore as it's years old at this point, as can be seen by the fact that Kamran's personal email is on it. This version of the About page also pre-dates the editor, so the claim was accurate at the time.

To remedy this situation we will be removing the About page entirely.

I'm sorry you felt so offended by this situation and hopefully we can all move past it.

**Comment by parsa-xy** [comment]
Thank you for providing valuable educational resources @dansholds —that’s exactly why your community has grown. However, GitHub is primarily for developers to learn from code, not just roadmaps. Many, including myself, have invested time in your project, only to find that the core functionality is in a private repo. This should be clearly mentioned in the README.

It's like creating a product, asking for help to improve it, claiming it's open source, and then hiding the key components. I’m not interested in the content; I’m keen to understand how your roadmap editor works and its architecture for my personal knowledge.

**Comment by dansholds** [comment]
"This should be clearly mentioned in the README."

Then that's the action we shall take.

**Comment by parsa-xy** [comment]
Thank you for agreeing to update the README @dansholds. It’s crucial to avoid misleading others in the future. Given the time I’ve invested without knowing about the private code, could you at least provide some details about the technology stack your roadmap editor uses? Understanding the functionality, not the content, would greatly benefit learners like me. Perhaps a simple example or a hint about the underlying architecture would be helpful.
