### ISSUE TITLE
[GitHub]: Some avatars missing in _Contributors_ section 

### ISSUE THREAD

**Issue by kenshanta** [kamranahmedse/developer-roadmap#6959]
### Detailed Description

Noticed i was swaying in the top 100 list the past week and my avatar never showed up.

currently im at 57th and should be somewhere here:

![Screenshot_20240902-115616](https://github.com/user-attachments/assets/2dcd0965-4b3a-4cdf-b0e5-aaeaf90cabfc)

 Other users also have the same issue.

### Possible Causes:
- Image format

I would like to reach out to contributors whom are facing the same issue so we could resolve it.

**Comment by kamranahmedse** [comment]
This is automatically [loaded from this URL](https://contrib.rocks/image?repo=kamranahmedse/developer-roadmap). I do see you in the [list of contributors in the image](https://contrib.rocks/image?repo=kamranahmedse/developer-roadmap) it should load. GitHub readme has some sort of caching -- this will automatically update hopefully in the next few hours.
