### ISSUE TITLE
Conditional expressions are not really even mentioned

### ISSUE THREAD

**Issue by alessandrobaldazzi** [kamranahmedse/developer-roadmap#6962]
### Roadmap URL

https://roadmap.sh/sql

### Suggestions

Conditional expressions and statements are not really dived into, but they are a blessing to obtain simple, easy-to-read solutions and to manage nulls.
The main ones I would add are the IF function and the IFNULL functions, but really there is so much that can be useful and it's not really mentioned.

For reference, I think these two links give quite the good list:
https://medium.com/@ejirogabriell2019/conditional-statements-logic-and-expression-in-sql-understanding-the-differences-451ec183c81a
https://www.geeksforgeeks.org/sql-conditional-expressions/

**Comment by dansholds** [comment]
@alessandrobaldazzi we currently have just these conditional statements, I can add a few more to this section if you think its required?

![Screenshot 2024-09-09 at 16 08 19](https://github.com/user-attachments/assets/dc518485-d312-4307-bb25-459ed0a58db1)

**Comment by alessandrobaldazzi** [comment]
Yeah, I think a bit more insight on the argument would be great.
If there were both a simpler and a more complex roadmap like for other topics I think it could be avoided in the simpler one, but as it is right now it could help.

**Comment by dansholds** [comment]
Added this to our internal list.
