### ISSUE TITLE
Docker Roadmap - Tags are not displayed properly

### ISSUE THREAD

**Issue by split-sec** [kamranahmedse/developer-roadmap#6966]
### Detailed Description

![image](https://github.com/user-attachments/assets/c66796e2-59a0-48bb-af2b-d1b153abb2b8)

There are these issues in 3 parts in Docker Roadmap - Installation / Setup, Bind mounts, Union Filesystems.

I believe that the issue is due to the fullstop added at the end of each line.

**Comment by fellalli** [comment]
Same issue for *roadmap.sh/cpp -> Setting up your Environment*. I suppose that resources are currently only detected correctly 
 when there is no additional text in the same line.
