### ISSUE TITLE
Exact match on email verification

### ISSUE THREAD

**Issue by rasoulbsd** [kamranahmedse/developer-roadmap#6971]
### What is the URL where the issue is happening

https://roadmap.sh/team/members

### What browsers are you seeing the problem on?

Chrome

### Describe the Bug

I have invited my friend to my team. I typed my friend's email starting with Captial letter and he revieves the email but he can not access the team. Also, they are considered two different accounts for same email and it must become lowerCased, before ckecking I think. I couldn't find the responding code for that.

### Participation

- [X] I am willing to submit a pull request for this issue.

**Comment by kamranahmedse** [comment]
@arikchakma can you please look into this (also, let's verify to make sure that this isn't happening anywhere else)

**Comment by bdrake300** [comment]
Wrong

**Comment by arikchakma** [comment]
@bdrake300 Sorry?

**Comment by kamranahmedse** [comment]
@rasoulbsd it should be fine now. Let us know if you still face any issues.

**Comment by rasoulbsd** [comment]
@kamranahmedse  I tested it and it seems to be resolved.
Thanks for the support and the great platform.
