### ISSUE TITLE
Duplicated Link on Backend Roadmap

### ISSUE THREAD

**Issue by MacMacky** [kamranahmedse/developer-roadmap#6979]
### Detailed Description

![duplicated links](https://github.com/user-attachments/assets/deadbac5-5212-4344-b332-4a763375cdeb)

The two links `What is an ORM ...` redirects to the same stackoverflow question, but the other one is the answer

**Comment by fellalli** [comment]
@MacMacky let's remove the first link to the question and keep the link to the actual answer. You can open a PR yourself for the change! 🚀

**Comment by dansholds** [comment]
Is the correct answer ☝️

If we see something like this that's an easy fix it's best to submit a PR rather than an issue 🤙
