### ISSUE TITLE
Token/Blockchain Engineer Roadmap

### ISSUE THREAD

**Issue by moritzWa** [kamranahmedse/developer-roadmap#699]
#### What roadmap is this issue about?

- [ ] Frontend Roadmap
- [ ] Backend Roadmap
- [ ] DevOps Roadmap
- [x] All Roadmaps

#### What is this issue about?

- [ ] Discussion for a pull request I would want to open.
- [ ] Addition of a new item
- [ ] Removal of some existing item
- [ ] Changing in arrangement
- [ ] General suggestion
- [x] Sharing an Idea
- [ ] Something else

#### Please acknowledge the below listed

- [x] This is not a duplicate issue. I have searched and there is no existing issue for this.
- [x] I understand that these roadmaps are highly opinionated. The purpose is to not to include everything out there in these roadmaps but to have everything that is most relevant today comparing to the other options listed.
- [x] I have read the [contribution docs](../contributing.md) before opening this issue.

#### Enter the details about the issue here

I would love to have an overview of the technologies, languages and co. used in this field. 
Especially  because this is such a new and exciting field I think it could be valuable to have this kind of overview and help engineers to transition in this field. 

There is actually already a great project that has aggregated those here: https://github.com/protofire/blockchain-learning-path, but it lacks the visual representation I like abut the "kamranahmedse/developer-roadmap project"

Here is another relevant list with educational material for token engineers: http://tokenengineering.wikidot.com/

**Comment by iamdeepakvishwa** [comment]
@moritzWa The repo you have suggested all of them are for development of public blockchain or using public Dapp .
It's time to update about private dapp development

**Comment by danielgruesso** [comment]
@kamranahmedse this looks good to close.
