### ISSUE TITLE
Ansible Playbook for Server Hardening following Redhat Guidelines 

### ISSUE THREAD

**Issue by dev-oops007** [kamranahmedse/developer-roadmap#6995]
### What Roadmap is this project for?

DevOPS

### Project Difficulty

Intermediate

### Add Project Details

Create a Ansible pLaybook for Linux server hardening following the Redhat server hardening guidelines.
check on local or remotely .

**Comment by dansholds** [comment]
@dev-oops007 Thanks for putting in the time to write this project out!

It could do with some more content such as as requirements etc (please check the existing projects in other roadmaps to get a feel for what I mean!)

**Comment by dev-oops007** [comment]
Sure,
