### ISSUE TITLE
problem in contributing

### ISSUE THREAD

**Issue by hussamkhatib** [kamranahmedse/developer-roadmap#700]
#### Enter the details about the issue here

i want to contribute to this project,can youplease explain the second step this says
 "Open Balsamiq, click Project > Import > Mockup JSON,"
do we have to download Balasmiq in desktop ? i cant find project tab anyywhere

**Comment by kamranahmedse** [comment]
Hey @hussamkhatib, Yes it requires you to have [Balsamiq](https://balsamiq.com/wireframes/desktop/) installed.
