### ISSUE TITLE
Topic not found

### ISSUE THREAD

**Issue by brodriro** [kamranahmedse/developer-roadmap#7013]
### What is the URL where the issue is happening

https://roadmap.sh/software-architect

### What browsers are you seeing the problem on?

Firefox

### Describe the Bug

Clicking on **Functional Programming** displays "Topic not found".

![image](https://github.com/user-attachments/assets/1477139e-8df7-4887-849e-be157059bd43)

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by kenshanta** [comment]
did you check the browser network tab in the console? 
It would be useful to see the `404` request in order to debug
