### ISSUE TITLE
Associate projects with a specific level or stage on the Roadmap 

### ISSUE THREAD

**Issue by yeab-dev** [kamranahmedse/developer-roadmap#7038]
### Feature Description

I really appreciate what your're doing. roadmap.sh is really helping me on my career goals. keep up the good work. 

I'm suggesting that to associate the projects with the topic using the same UI of the  roadmap.  I've attached a screenshot of design to clarify the idea.
![Screenshot_2024-09-08-15-19-44_1920x1080](https://github.com/user-attachments/assets/54aed68f-38fb-464f-a0f8-49db89e750b3)

**Comment by dansholds** [comment]
We have plans for this or a simple feature in our roadmap, but thanks for raising.
