### ISSUE TITLE
Reminder / Post-it on roadmaps for local uses

### ISSUE THREAD

**Issue by Gougouli69** [kamranahmedse/developer-roadmap#7041]
### What Roadmap is this project for?

All

### Project Difficulty

Beginner

### Add Project Details

I was reading the Product Manager roadmap and I saw some difficult terms, and methods that I didn't knew. My work method is easy:
- 1st time: I read all the roadmap
- 2nd time: I identify difficult terms and I googlize them
Can you add a feature which allow us to highlight some words in a post-it ? It's like a cheat sheet, a summary after all read.
We will can save the words that we think important for us.

For example, I'm reading an article about SCAMPER. 
![image](https://github.com/user-attachments/assets/89ed811f-b261-44c4-bd48-c5080c284648)
I think I should look on Goole what it's meaning. So I add this term at my list for check later what it means.

I'm avaible if you have any question.

Best regards.
Greg.

**Comment by dansholds** [comment]
Triaged as a feature request.

**Comment by dansholds** [comment]
we are planning to expand on our community focused features in the future, so this could potentially fall under that, we will take note 👍
