### ISSUE TITLE
I can't see the specific roadmaps except C++

### ISSUE THREAD

**Issue by wyh5768** [kamranahmedse/developer-roadmap#7042]
### Roadmap URL

http://roadmap.sh

### Suggestions

Just like what the title say.

**Comment by kamranahmedse** [comment]
Can you please share some more details any screenshots or screen recording? What do you mean by not see? Is there any error in the console.

**Comment by wyh5768** [comment]
<img width="1280" alt="1" src="https://github.com/user-attachments/assets/a8aa3148-d83f-4d04-8802-796ad9e26bcd">
<img width="1280" alt="2" src="https://github.com/user-attachments/assets/c393a5ea-7d6e-44ce-8ad6-2c1fea28e2eb">
<img width="1280" alt="3" src="https://github.com/user-attachments/assets/92a9fc10-7a00-4ce4-95c9-06a59605aa83">
Just like this.I want to check if there is more information about the specific roadmap,but there is nothing,I just can see a pdf here,it is like this originally?Please help me,I want to learn more if can.

**Comment by wyh5768** [comment]
![Uploading 4.jpg…]()

**Comment by wyh5768** [comment]
![4](https://github.com/user-attachments/assets/c12d3ae1-3e5b-4b8c-a160-c4250c546ec9)
