### ISSUE TITLE
Generate PDF from roadmaps

### ISSUE THREAD

**Issue by Gougouli69** [kamranahmedse/developer-roadmap#7046]
### What Roadmap is this project for?

All

### Project Difficulty

Intermediate

### Add Project Details

I spent the whole day on the screens, and I might as well tell you that in the end, it's a bit tiring, especially for the eyes.

So I was wondering: wouldn't it be possible to generate a PDF from a roadmap so that it could be read on Kindle-style tablets?

I remain at your disposal.

Best regards,
Greg

**Comment by dansholds** [comment]
Hey @Gougouli69 

Thanks for raising the issue, every roadmap has a Download button at the top that allows it to be downloaded as a PDF

![Screenshot 2024-09-09 at 15 02 03](https://github.com/user-attachments/assets/1c05297f-4c43-4a29-a97b-6f3237e735b2)

**Comment by Gougouli69** [comment]
Hello @dansholds ,
I will try to be clearer. If you click on the current download button, it just download the roadmap without the text. I would like to download the roadmap with the text to allow me to read offline .
I've added a few images to help you understand me

![Capture d’écran 2024-09-10 212903](https://github.com/user-attachments/assets/a6e6eff9-6a0c-49e1-b212-00a64fbf2786)
![Capture d’écran 2024-09-10 212932](https://github.com/user-attachments/assets/a301411d-3cbd-4854-b638-ee87f3259b22)
![Download_schem](https://github.com/user-attachments/assets/066dd096-35ee-49e6-813e-226f1f6288e2)

Thanks.
