### ISSUE TITLE
I would add CAPEC as a framework

### ISSUE THREAD

**Issue by sebherv** [kamranahmedse/developer-roadmap#7057]
### Roadmap URL

https://roadmap.sh/cyber-security

### Suggestions

I would add the Mitre CAPEC framework in addition to the mitre att&ck framwork because they do not model the same abstraction level.
See https://capec.mitre.org/about/attack_comparison.html for further details

**Comment by dansholds** [comment]
I would suggest you open a PR to add this link to a relevant topic as adding more nodes at this point would be overkill due to the 300+ topics already present.
