### ISSUE TITLE
game developer roadmap removal of python and assembly , addition of gd script and replace native with bevy

### ISSUE THREAD

**Issue by ghost** [kamranahmedse/developer-roadmap#7068]
### Roadmap URL

https://roadmap.sh/game-developer

### Suggestions

godot can use c++ , c# as well as gd script also unity and unreal engins can use c++ and c# so i want the roadmap to add gdscript and explicitly write "" it is only for godot as it is made for the engine specifically with strong error detection and easy to learn just like py but you can also use c++ or c# "" and mark it optional to learn also if you are adding rust as lang then also add bevy which is a rust gaming engine {getting popular} also remove python as it has no use in gaming except making snake games using pygame lib also no need for assembly in writing code for games and replace native with bevy , i never heard of it before and nothing found on google as well except its some react lib or something 
![Screenshot_20240911_000505](https://github.com/user-attachments/assets/f4a09b8f-8796-4e99-92cf-ebc19cce5d6a)

**Comment by legionguy** [comment]
what about other stuff , whats the use of python in game dev @dansholds also no addition of bevy , whats the use of learning rust then

**Comment by legionguy** [comment]
i was not being rude . anyways bad for the project
