### ISSUE TITLE
Wrong Link Redirect

### ISSUE THREAD

**Issue by Poitew** [kamranahmedse/developer-roadmap#7080]
### What is the URL where the issue is happening

https://roadmap.sh/projects/basic-dockerfile

### What browsers are you seeing the problem on?

Firefox

### Describe the Bug

When you enter the **Basic Dockerfile** project through the Docker roadmap, and hit the **Back to Projects** button you get to the DevOps roadmap

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by dansholds** [comment]
Just checked this out and it seems to happen for all projects that are on more than one roadmap.

**Comment by dansholds** [comment]
![Screenshot 2024-09-11 at 16 23 47](https://github.com/user-attachments/assets/6aae424a-32b1-4f11-a3eb-1ba7f5081e01)

The "return to projects" seems always to default to the first roadmap in the list.

This was confirmed in a local test where I moved the ordering of roadmaps in the list.

@kamranahmedse FYI

**Comment by Poitew** [comment]
True, when going back from the **Expense Tracker** from the Python Roamap it takes you back to the Backend roadmap.
At first I thought there were individual projects for each roadmap even if the projects were the same, so this problem was just a small wrong link on the Docker roadmap. I guess it was not.

**Comment by dansholds** [comment]
We're going to take a look at the overall behaviour :)

**Comment by dansholds** [comment]
This issue has been superceded by the new (last Friday) feature of https://roadmap.sh/projects
