### ISSUE TITLE
[feat-req]: Adding Contributors Section For Each Roadmap

### ISSUE THREAD

**Issue by kenshanta** [kamranahmedse/developer-roadmap#7090]
### Feature Description

Would be nice to see the contributors - or top 5 - for a specific roadmap that is being learned from. 
A good portion of the project traffic is thanks to beginner/intermediates aiming to find a path to follow, having the author(s) revealed in a pre-footer section would be nice.

_On a side note i would also request a Discussions/Comments & Likes/Reactions to each roadmap_

**Comment by dansholds** [comment]
All contributors are currently listed on GitHub and we are currently working on plans for leaderboards etc that could be used to show this information.
