### ISSUE TITLE
[feat-req]: Discussions/Comments & Likes/Reactions For each Roadmap

### ISSUE THREAD

**Issue by kenshanta** [kamranahmedse/developer-roadmap#7091]
### Feature Description

As previously mentioned and loosely based on issue #7090 

Would be nice to have a classic ol' comments and reactions under each roadmap so there would be a better sense of community rather than discord that not all users are active on (i.e myself)

**Comment by dansholds** [comment]
We are planning to expand on our community related features in the future, which could potentially tackle this.
