### ISSUE TITLE
add pgAgroal to pgBouncer Alternatives

### ISSUE THREAD

**Issue by diego-stori** [kamranahmedse/developer-roadmap#7096]
### Roadmap URL

https://roadmap.sh/postgresql-dba

### Suggestions

Please, next to "connection pooling" in the box "pgBouncer alternatives" add [pgAgroal](https://github.com/agroal/pgagroal)

**Comment by dansholds** [comment]
Please submit a PR to add this to the pgBouncer alternatives topic.
