### ISSUE TITLE
Login & Sign up button visible issue if we attempt login from two different tabs

### ISSUE THREAD

**Issue by salmantec** [kamranahmedse/developer-roadmap#7098]
### What is the URL where the issue is happening

https://roadmap.sh

### What browsers are you seeing the problem on?

Safari

## Steps to reproduce the bug:

1. I opened `roadmap.sh` website in two different tabs of same browser (Safari)
2. In tab1, I clicked **login** button and logged in after entering my email and password. Landed the home page (_Which is correct behaviour_)

<img width="900" alt="Screenshot 2024-09-12 at 11 21 00 PM" src="https://github.com/user-attachments/assets/0ea3e085-2d3c-4c6e-b7e6-c60decab144c">

3. Then, I went to tab2 and clicked somewhere in the screen and I could see the **account / teams** button along with **login** and **Signup**. Also I could see the dropdown values

<img width="797" alt="Screenshot 2024-09-12 at 11 08 17 PM" src="https://github.com/user-attachments/assets/9ee4e91d-f308-48ac-bc64-ff380262c27a">

<img width="771" alt="Screenshot 2024-09-12 at 11 09 05 PM" src="https://github.com/user-attachments/assets/7cbf6c8e-13ca-4e25-bf1d-0c67283b3515">

4. I refreshed the screen in tab2 and then **login** and **sign up** button were gone. Then I clicked **logout** in tab2 and came back to tab1 and again clicked somewhere in the screen. Could see this screen

<img width="1063" alt="Screenshot 2024-09-12 at 11 15 12 PM" src="https://github.com/user-attachments/assets/4e32706a-b269-4460-a1aa-e55ecde20429">

**Comment by dansholds** [comment]
@arikchakma

**Comment by arikchakma** [comment]
That's the correct behaviour right now. If you logged in from one tab you need to refresh the other tab in-order to get the access.
