### ISSUE TITLE
Exercises

### ISSUE THREAD

**Issue by JanKIeloch** [kamranahmedse/developer-roadmap#7101]
### Feature Description

As C++ student I would like to practice concepts I learnt while walking through C++ roadmap.

It would be nice if you provide some exercices for concepts explained 
or
provide links to pages where I can practice concepts learnt.

**Comment by sketchycarder** [comment]
Yo big man! Please I need your help on this I’m new, please respond. Do you know how to get past this 
![Uploading image.jpg…]()

**Comment by dansholds** [comment]
We are aiming to add projects to all roadmaps over time, but this will take time.
