### ISSUE TITLE
Sleuth tool is no longer used by Spring since SpringBoot 3

### ISSUE THREAD

**Issue by Numichi** [kamranahmedse/developer-roadmap#7117]
### Roadmap URL

https://roadmap.sh/spring-boot

### Suggestions

https://spring.io/projects/spring-cloud-sleuth

> Spring Cloud Sleuth’s last minor version is 3.1. You can check the [3.1.x](https://github.com/spring-cloud/spring-cloud-sleuth/tree/3.1.x) branch for the latest commits. The core of this project got moved to [Micrometer Tracing](https://micrometer.io/docs/tracing) project and the instrumentations will be moved to [Micrometer](https://micrometer.io/) and all respective projects (no longer all instrumentations will be done in a single repository).

**Comment by dansholds** [comment]
Feel free to submit a PR that remediates the copy within the topic.
