### ISSUE TITLE
Added Polish

### ISSUE THREAD

**Issue by mbiesiad** [kamranahmedse/developer-roadmap#712]
Hi. Referring to #711 [PR](https://github.com/kamranahmedse/developer-roadmap/pull/711)

Finished translations for intro, backend, frontend & DevOps roadmaps 🚀 

Best wishes

**Comment by mbiesiad** [comment]
Merged to master. Issue could be closed

**Comment by Timur604** [comment]
Hocam sizi severek takip ediyoruz

iPhone’umdan gönderildi

Michal <notifications@github.com<mailto:notifications@github.com>> şunları yazdı (11 Tem 2020 18:06):


Closed #712<https://github.com/kamranahmedse/developer-roadmap/issues/712>.
