### ISSUE TITLE
Add CryptoZombies for Solidity Practice

### ISSUE THREAD

**Issue by Muhammad-Tayyab-Bhutto** [kamranahmedse/developer-roadmap#7123]
### Roadmap URL

https://roadmap.sh/blockchain

### Suggestions

I would suggest adding CryptoZombies (https://cryptozombies.io/) as a recommended resource for those learning Solidity and smart contract development. CryptoZombies is an interactive, game-based tutorial that teaches Solidity and Ethereum development in a fun and engaging way. It provides a step-by-step guide, making it easier for beginners to grasp blockchain concepts while building their own decentralized applications.

Including it in the Blockchain Developer roadmap under "Solidity Practice" or "Smart Contract Development" would give learners a practical tool to solidify their knowledge.

**Comment by dansholds** [comment]
Closing as you have opened a PR
