### ISSUE TITLE
Pre-populating email address from login page to reset password page, and include the user's name in mails.

### ISSUE THREAD

**Issue by salmantec** [kamranahmedse/developer-roadmap#7126]
### Feature Description

Hey, I have couple of `nice to have` suggestions and sharing here, but not mandatory. 

1. **Pre populating email address from login page to reset password page:**

    - If I enter my mail address in `login page` and click the `Reset your password` link, the next page will ask me to enter my email address once again.
    - In this scenario, If we pre populate the mail address from `login page` to `Reset your password` page, this may reduce users effort to type it again.

<img width="908" alt="Screenshot 2024-09-12 at 10 43 52 PM" src="https://github.com/user-attachments/assets/b0681f9f-9b56-46db-8220-1b731d96c517">

2. **Mails with user's full name after sign up**

    - I have recently signed up in roadmap.sh and during sign up process I entered my full name. Then got a verification mail. I feel if we show the user's full name in the mail to greet them, it would be really feel good (from user perspective)

<img width="1175" alt="Screenshot 2024-09-12 at 10 52 36 PM" src="https://github.com/user-attachments/assets/73f2cf55-2683-4cb8-943d-0e706b8b9a51">

**Comment by dansholds** [comment]
Hey thanks for the suggestion but the prepopulating of an email address is not really required nor recommened.
