### ISSUE TITLE
Progress skill 

### ISSUE THREAD

**Issue by brodriro** [kamranahmedse/developer-roadmap#7128]
### What is the URL where the issue is happening

https://roadmap.sh/android

### What browsers are you seeing the problem on?

Firefox

### Describe the Bug

The progress counter is not considering the skipped skills.

![image](https://github.com/user-attachments/assets/25c2fd34-43b2-4ae7-952a-4f6343b352e8)

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by arikchakma** [comment]
@brodriro Can you try clearing the local storage?

**Comment by arikchakma** [comment]
@brodriro Can you please check now?

**Comment by brodriro** [comment]
It works
