### ISSUE TITLE
Dedicated Option To Find Saved Roadmaps

### ISSUE THREAD

**Issue by monark04** [kamranahmedse/developer-roadmap#7132]
### Detailed Description

I find it is hard to navigate to saved roadmaps. Every time i have to see all roadmaps. I may be great if user gets option to see only their saved maps specifically as old version.

**Comment by kamranahmedse** [comment]
<img width="425" alt="image" src="https://github.com/user-attachments/assets/a02ee7c4-b880-4537-adb1-a1235b2fc5a7">

Projects _are_ there on the new dashboard. Does that work or do you mean something else?
