### ISSUE TITLE
Replace the Vue.js Crash Course link with a new version of a course

### ISSUE THREAD

**Issue by konstaku** [kamranahmedse/developer-roadmap#7139]
### Roadmap URL

https://roadmap.sh/frontend

### Suggestions

The current link in Vue.js to the [Vue.js Crash Course](https://www.youtube.com/watch?v=qZXt1Aom3Cs) is leading to a video from 2021, while there is already a newer and updated version on the same youtube channel:

I suggesting replacing the link with a link to a newer version of the video: https://www.youtube.com/watch?v=VeNfHj6MhgA

**Comment by dansholds** [comment]
You can open a PR yourself to replace the link, if you're not comfortable doing this then let me know and I can do it
