### ISSUE TITLE
For some general IT command knowledge 

### ISSUE THREAD

**Issue by maul41** [kamranahmedse/developer-roadmap#7143]
### Roadmap URL

https://roadmap.sh/cyber-security

### Suggestions

Just a general addition of a site that contains multiple man references within a single location.

https://ss64.com/

Covers the majority of rudimentary binaries that might aid tech/cyber folks out in the field

**Comment by maul41** [comment]
Can this site be added as a reference to the Common Command section

**Comment by dansholds** [comment]
@maul41 you can open a PR to add this link yourself, are you comfortable doing this?
