### ISSUE TITLE
Javascript (or TypeScript) missing on "pick up language" path of Computer Science roadmap

### ISSUE THREAD

**Issue by jeyhunjeyhunzade** [kamranahmedse/developer-roadmap#7150]
### Roadmap URL

https://roadmap.sh/computer-science

### Suggestions

I would like to see JavaScript or TypeScript on the "pick up language" path of  Computer Science roadmap, just because with these languages can also be studied.

**Comment by dansholds** [comment]
IMO the 7 languages that we have listed are enough
