### ISSUE TITLE
Interactive Quiz App

### ISSUE THREAD

**Issue by Yashi-Singh-9** [kamranahmedse/developer-roadmap#7160]
### What Roadmap is this project for?

Frontend Roadmap

### Project Difficulty

Beginner

### Add Project Details

You are required to build an interactive quiz app using HTML, CSS, and JavaScript. The app should present users with a series of multiple-choice questions. After each question, the app should provide immediate feedback on whether the selected answer is correct or incorrect. At the end of the quiz, users should see their total score and be able to review the questions they answered incorrectly. The app should include features such as a timer for each question and a progress bar showing how many questions have been completed. Ensure the app is fully responsive and has a clean, user-friendly interface. This project will help you practice creating dynamic content, managing state, and improving user experience.

**Comment by akash-kanar** [comment]
Can you please assign this issue to me ?

**Comment by Ashu1823** [comment]
Intrested to work on this.

**Comment by akash-kanar** [comment]
can you please assign this task to me ? @Yashi-Singh-9

**Comment by dansholds** [comment]
Added to this PR - https://github.com/kamranahmedse/developer-roadmap/pull/7509
