### ISSUE TITLE
Adding Links to other roadmaps.

### ISSUE THREAD

**Issue by mixelectronico** [kamranahmedse/developer-roadmap#7162]
### Feature Description

I would like to sugest you to add some links to other roadmaps when the main content of a roadmap contains another roadmap.

For example, GIT and GITHUB have an individual roadmap but also in several roarmaps like for example FrontEnd or BackEnd have also GIT and GITHUB inside. Maybe a good idea is to put a link into the overlay wich has a description of the GIT and GITHUB tag. This can be applied to other technologies as well of course.

I think this can be something very useful to those who likes to navigate among roadmaps. also you can put a progress percentage of the technology below the tag in order to see how much of the tag's technology you are mastering.

that's it! Hope this can be useful for you as an idea, maybe I can help you.

I'm spanish native speaker but I guess I can do something in english as well.

Have a nice day!

David Mix

**Comment by kenshanta** [comment]
If I understood you correctly, you're referring to a feature that already exists. Having a roadmap link within one of the topics. 
 - [frontend-roadmap](https://roadmap.sh/frontend)

Example:
![Screenshot 2024-09-19 at 10 13 49 AM](https://github.com/user-attachments/assets/c4b902dd-4066-4069-a254-914d6816121c)

### is this what you mean?

**Comment by dansholds** [comment]
![Screenshot 2024-09-20 at 09 50 50](https://github.com/user-attachments/assets/ef899223-ff0b-425f-9681-365f890cd5e7)

@mixelectronico thanks for raising this.

We already have these blue buttons in roadmaps that directly link to other roadmaps, as well as as "in topic" link to any relevant roadmaps, as mentioned by @kenshanta 🤙🏻

**Comment by mixelectronico** [comment]
Nice!... Sorry to don't reply before, but yes, i'll be letting you know if I see some tabs or topics without links in order to put it now that I learnt how to submitt Issues. 😄 Have a nice time!

David Mix
