### ISSUE TITLE
Add new resource at "Internet - What is hosting?"

### ISSUE THREAD

**Issue by ZlatanCN** [kamranahmedse/developer-roadmap#7166]
### Roadmap URL

https://roadmap.sh/frontend

### Suggestions

At "Internet - What is hosting?", I wish to add this article called [Hostinger - What is web hosting?](https://www.hostinger.com/tutorials/what-is-web-hosting/). It has clearly explained all the details

**Comment by kenshanta** [comment]
@ZlatanCN you can append the article to the pre-existing list of resources by creating a PR.

It would be nice to have an article or documentation for the readers out there, as all the provided resources on this topic are videos.

Question is, will you take the initiative or shall I? 👀

**Comment by ZlatanCN** [comment]
> @ZlatanCN you can append the article to the pre-existing list of resources by creating a PR. Tho please make sure to follow the [contributions guide](https://github.com/kamranahmedse/developer-roadmap/blob/master/contributing.md)
> 
> It would be nice to have an article or documentation for the readers out there, as all the provided resources on this topic are videos.
> 
> Question is, will you take the initiative or shall I? 👀

@kenshanta Thank you for your reply!, I'm so glad to be a contributor and I'll offer the PR myself. Thanks again!
