### ISSUE TITLE
Page not found for SQL Server Indexed resource

### ISSUE THREAD

**Issue by TheBigBaldHead** [kamranahmedse/developer-roadmap#7169]
### Detailed Description

The [first link](https://www.sqlservercentral.com/articles/sql-server-indexes) mentioned at the node Managing Indexes in the SQL Roadmap runs into 404 Page not found error!

**Comment by fellalli** [comment]
@TheBigBaldHead you can open a PR to remove or replace the link :)

The URL did probably change to [this](https://www.sqlservercentral.com/articles/introduction-to-indexes).
