### ISSUE TITLE
Storybook

### ISSUE THREAD

**Issue by Samy0412** [kamranahmedse/developer-roadmap#7183]
### Roadmap URL

https://roadmap.sh/frontend

### Suggestions

Hello, I love your project, thank you so much for making this! I wished it existed when I started learning how to code!
We are going to start a new project from scratch and I am focusing on the front end, I was looking for best practices around developing react components in isolation at the start of a project, especially when you are a very small team (we have used storybook in the past, but we still find it heavy). I can see subject around testing (which is already a complex subject), but we still need to have a way to visualize our components when building them, and I wish I could get more information about this subject. Thank you!

**Comment by dansholds** [comment]
I feel this would be better as a real-time chat in Discord, come join us - https://roadmap.sh/discord
