### ISSUE TITLE
adding project recommendation to roadmaps

### ISSUE THREAD

**Issue by azhoosein** [kamranahmedse/developer-roadmap#7192]
### Roadmap URL

https://roadmap.sh/frontend

### Suggestions

the roadmap should have a branch to show when to start a project. for example, in the fronted roadmap after the first CSS branch, there should be another branch that leads to the https://roadmap.sh/projects/single-page-cv project. this would allow beginners to know when they should be capable to complete the listed projects.

**Comment by dansholds** [comment]
We do this on the full-stack roadmap and we do have plans to integrate projects more in the roadmaps 🤙🏻
