### ISSUE TITLE
Let's create a roadmap for Data Engineer!

### ISSUE THREAD

**Issue by p2227** [kamranahmedse/developer-roadmap#72]

**Comment by saisankargochhayat** [comment]
Yeah this would be good idea . I think it holds great significance in 2017.

**Comment by hqhung2506** [comment]
Agreed.

**Comment by marceloogeda** [comment]
Good thinking!

**Comment by kamranahmedse** [comment]
Feel free to create a PR if anyone is up for it. But the repository focuses on "web developer", so closing it for being irrelevant.

Thanks though.
