### ISSUE TITLE
Project Completed Marked

### ISSUE THREAD

**Issue by Ekefrancisokechukwu** [kamranahmedse/developer-roadmap#7200]
### Feature Description

I would like to suggest that if I have a submitted or finished  project.
  Then I navigate  back to all projects page  for the completed project to be marked as completed or submitted so that I will know projects that I have worked on or submitted for 
  
Thank you

**Comment by dansholds** [comment]
![Screenshot 2024-09-23 at 11 27 27](https://github.com/user-attachments/assets/4f8077a2-2e60-4d85-a360-176593d7a96d)

Something like this? Green for complete and yellow for in progress?

**Comment by Ekefrancisokechukwu** [comment]
Yes, does it already exists or this what the UI would look like

**Comment by dansholds** [comment]
it does not exist, I simply did a mockup 😄

**Comment by Ekefrancisokechukwu** [comment]
oo alright ,
will we be  getting the update?
