### ISSUE TITLE
Make versions for each roadmap

### ISSUE THREAD

**Issue by benianus** [kamranahmedse/developer-roadmap#7204]
### Roadmap URL

https://roadmap.sh/

### Suggestions

I suggest dividing each roadmap to level as you already do in the backend and front end 
what junior should learn, what mid should learn ...etc
if you put everything in one roadmap the beginner will be distracted and it will cause the dumping of information
I hope you take into consideration graduation of information and the best timing to get it

**Comment by dansholds** [comment]
You appear to be suggesting that we create a "beginner-friendly" version of all 50+ roadmaps? is that correct?

**Comment by dansholds** [comment]
Unfortunately we won't be doing this, at least not in the near future, current tasks take priority over luxury items like this.
