### ISSUE TITLE
Missing Topics 

### ISSUE THREAD

**Issue by argaderuchika** [kamranahmedse/developer-roadmap#7215]
### Roadmap URL

https://roadmap.sh/datastructures-and-algorithms

### Suggestions

Data Structure String is missing

**Comment by hahaenla100** [comment]
这是来自QQ邮箱的假期自动回复邮件。您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by dansholds** [comment]
Elaborate, where would you like to see this added and in what format?

Can it be added as copy & text to an existing topic?

**Comment by argaderuchika** [comment]
Yes we can add it to existing topics where data structures are mentioned,
we can add it along with arrays, stacks, queues

**Comment by dansholds** [comment]
I've added this to our internal tasks
