### ISSUE TITLE
Add packer to terraform roadmap

### ISSUE THREAD

**Issue by ms4720** [kamranahmedse/developer-roadmap#7216]
### Roadmap URL

https://roadmap.sh/terraform

### Suggestions

Packer should be added to the terraform roadmap, or perhaps devops.  It is a tool  to build images using a configuration tool like ansible

**Comment by dansholds** [comment]
definitely not the TF roadmap, potentially the DevOps roadmap but you need to ask the question of "does adding Packer add anything to the roadmap aside from telling people about that specific tool?"

**Comment by ms4720** [comment]
How to use ansible to build a Bootable server image in a IAC manner.  I think that is a missing process step in the IAC path for infrastructure
