### ISSUE TITLE
Add GraphQL to Back End Path

### ISSUE THREAD

**Issue by kosantosbik** [kamranahmedse/developer-roadmap#722]
#### What roadmap is this issue about?

- [ ] Frontend Roadmap
- [X] Backend Roadmap
- [ ] DevOps Roadmap
- [ ] All Roadmaps

#### What is this issue about?

- [X] Discussion for a pull request I would want to open.
- [X] Addition of a new item
- [ ] Removal of some existing item
- [ ] Changing in arrangement
- [ ] General suggestion
- [ ] Sharing an Idea
- [ ] Something else

#### Please acknowledge the below listed

- [X] This is not a duplicate issue. I have searched and there is no existing issue for this.
- [X] I understand that these roadmaps are highly opinionated. The purpose is to not to include everything out there in these roadmaps but to have everything that is most relevant today comparing to the other options listed.
- [X] I have read the [contribution docs](../contributing.md) before opening this issue.

#### Enter the details about the issue here

GraphQL is the next REST. New developers should be aware of that.

**Comment by kamranahmedse** [comment]
We already have that in the backend path near the end

![image](https://user-images.githubusercontent.com/4921183/104088225-a30fa300-527e-11eb-83fb-7611a6fce942.png)
