### ISSUE TITLE
DevOps roadmap: Provisioning opens information drawer with Prometheus

### ISSUE THREAD

**Issue by JSC500** [kamranahmedse/developer-roadmap#7230]
### Roadmap URL

https://roadmap.sh/devops

### Suggestions

**Steps to reproduce:**
1. Open https://roadmap.sh/devops
2. Click on the yellow "Provisioning" card
3. Drawer with the explanation for "Prometheus" comes up

**Expected behaviour:**
The drawer contains the explanation for "Provisioning"

**Comment by dansholds** [comment]
Interesting, its using the correct ID for the `provisioning` file in the JSON, I'll have a look.
