### ISSUE TITLE
Git like version control for Official, Community and AI Roadmaps/Projects in UI/CLI

### ISSUE THREAD

**Issue by ddipayan00** [kamranahmedse/developer-roadmap#7231]
### Feature Description

It will be more useful if we get **git** like version control for **Official**, **Community** and **AI** Roadmaps/Projects in **Roadmap.sh UI/CLI**. 

**Maintained** by and **merge** request approved by roadmap **owner**
and updated by we **developers/contributors** for updated accurate information.

Got this idea from this site : https://www.getbild.com/blog/version-control-for-hardware-development

**Comment by dansholds** [comment]
Official Roadmaps are in version control, you can find them all at `src/data/roadmaps`.

As for the rest, that would cause significant bloat to the project given that we have hundreds of thousands of AI roadmaps at this point.
