### ISSUE TITLE
re-order rust roadmap

### ISSUE THREAD

**Issue by PaneradFisk** [kamranahmedse/developer-roadmap#7232]
### Roadmap URL

https://roadmap.sh/rust

### Suggestions

The current roadmap goes into a bunch of different ecosystems and libraries before covering testing, debugging and documenting...  
No matter what ecosystem or library you're working with, knowing how to properly test, debug and document what you're doing should come first? 
I look at the roadmap as a whole before starting as I knew a bunch of stuff beforehand, but if I were to start from the beginning, knowing how to debug my code is waaay more important at any stage, than knowing how to use a 3rd party framework for building webapps.  

Since the developers of rust are so freaking awesome that they even include proper tools to do all of the above I can't understand how knowing about game development using Bevy would be higher on the list.

**Comment by dansholds** [comment]
Hey PaneradFisk, thanks for taking the time to write this!

While I understand where you're coming from, testing is not typically the first place that new learners will start when starting their software development journey, an introduction to the language followed by basic syntax (which usually results in a "Hello World!") is typically the approach and an approach is done by the majority of learning platforms 😃 

Doing this for the Rust roadmap would also mean doing it across the board for all roadmaps, which would be quite disruptive, I hope you understand 🙏🏻

**Comment by Hriishikeshh** [comment]
hey i would love to contribute on this issue
please assign it to me 
also help me with hacktoberfest2024 tag if possible
