### ISSUE TITLE
A small suggestion = Adding Beginner, Intermediate, Advanced option pannel for every roadmaps. 

### ISSUE THREAD

**Issue by albindavidc** [kamranahmedse/developer-roadmap#7235]
### Feature Description

Hello,
I'm a great fan of your open source contribution. I would like to suggest a small change that could help everyone in any stage of their career with our applicaiton. It would be a real plus point and it will be a real help to the beginners/intermediate/advanced level users to navigate through the roadmap. If we have an option in the top pannel to navigate through the different stages of roadmap. It will help everyone to look into it step by step. Rather than going though the entire roadmap. That may seem little exhausting. We know that some of the people are learning some thing for the time pass / just for a hobby. right ! And one more thing. It would be a great option if we have a option to widen the content to either sides. So i hope this update can help everyone. And I hope i made myself clear. Thank for your wonderful work out there. I'm looking forward to hear from you soon. 

Your Faithfully,
Albin David C

**Comment by dansholds** [comment]
Hey Albin, thanks for taking the time to write all of this!

For your main point, we have a "Beginner" version of 5 of our roadmaps at this point, and could potentially expand upon that, but splitting each roadmap into three pieces would be very time consuming and could potentially interrupt the flow of people who prefer to see the whole journey!

As for your comment "It would be a great option if we have a option to widen the content to either sides", are you referring to the sidedrawers?

**Comment by albindavidc** [comment]
I hope you have used the notion. In that we can widen the content area
right.. that's what I meant

**Comment by dansholds** [comment]
We will add the second ask to our internal roadmap but it's quite unlikely that we will (at this time) separate every roadmap into multiple roadmaps based on difficulty

**Comment by albindavidc** [comment]
Hello, 
Actually i don't mean to make it sepearte rather, we can give a sperate a dedicated tab for each difficulty level and let the AI do the creation according to the difficulty.
Any ways thank you for hearing out.
