### ISSUE TITLE
Course links don't work at Data Science roadmap

### ISSUE THREAD

**Issue by KuznetsLex** [kamranahmedse/developer-roadmap#7244]
### What is the URL where the issue is happening

https://roadmap.sh/ai-data-scientist

### What browsers are you seeing the problem on?

Chrome

### Describe the Bug

Mathematics -> Linear Algebra, Calculus, Mathematical Analysis -> Mathematics for Machine Learning -> Courses. Button tries to redirect me to resource, but fails. This happens with all "Courses" buttons on this page.

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by dansholds** [comment]
I can't replicate this issue on my end, can you share any console insights that might show the issue?
