### ISSUE TITLE
Add `find` utliity in linux roadmap 

### ISSUE THREAD

**Issue by ShreyasSubhedar** [kamranahmedse/developer-roadmap#7249]
### Roadmap URL

https://roadmap.sh/linux

### Suggestions

In the text processing section all the mentioned child utilities such as awk, grep, etc. I belive `find` is another utility that helps a lot while writing automation scripts in linux.
it become essential to have knowledge on how to use `find` in order to filter out 1000s of files to get the exact file and apply changes to it.

**Comment by ShreyasSubhedar** [comment]
I think, it will be  good to place `find` under `Working with Files Section` as well 😃

**Comment by dansholds** [comment]
added to internal board.
