### ISSUE TITLE
Leaderboard for Top Contributors.

### ISSUE THREAD

**Issue by offensive-vk** [kamranahmedse/developer-roadmap#7251]
### Feature Description

How about we also get to see a leaderboard or top users that are contributing to `Roadmap.sh` like in a weekly, monthly and overall type. Shoutout to First time / new contributors and more!

**Comment by kamranahmedse** [comment]
Good idea, we will pick it up soon.

**Comment by dansholds** [comment]
Closing as it's on our board.
