### ISSUE TITLE
Add Eloquent JS free book to learn javascript

### ISSUE THREAD

**Issue by StomperHK** [kamranahmedse/developer-roadmap#7254]
### Roadmap URL

https://roadmap.sh/frontend

### Suggestions

Add Eloquent JS free book to learn javascript, its a good and free book to master javascript.

**Comment by offensive-vk** [comment]
Do you want the book?

**Comment by dansholds** [comment]
You can add the link to the book in a PR if its a free online resource.

**Comment by StomperHK** [comment]
https://eloquentjavascript.net/
