### ISSUE TITLE
[feat] Integrate Jupyter notebooks

### ISSUE THREAD

**Issue by silopolis-dst** [kamranahmedse/developer-roadmap#7258]
### Feature Description

These bring many interesting features to build dynamic/interactive learning contents that could add to this already fantastic platform.
Where and how to integrate them, in roadmaps, projects, or else, this I leave to you UX geniuses as I appreciate your way...

Thank yall for your work and contribution to our joyful education :pray:

**Comment by dansholds** [comment]
This is not something that is on our radar currently but who knows what the future holds.
