### ISSUE TITLE
The definition provided for "EPA" in the Game Developer Roadmap does not define the term.

### ISSUE THREAD

**Issue by ObliquePixel** [kamranahmedse/developer-roadmap#7259]
### Detailed Description

The current definition of "EPA" in the Game Developer Roadmap (under Game Physics -> Collision Detection -> Narrow Phase -> Intersection) is:

> The EPA, also known as the Environmental Protection Agency, is not typically related to game development or the concept of intersection within this context. However, in game development, EPA might refer to an ‘Event-driven Process chain Architecture’ or some other game-specific acronym. In this domain, different terminologies and acronyms are often used to express complex architectures, designs, or functionalities. If you have encountered EPA in a game development context, it might be best to refer to the specific documentation or guide where it was described for a better understanding. Understanding the context is key to untangle the meaning of such abbreviations.

This paragraph provides no clear or concise definition of "EPA" (outside of the obviously incorrect "Environmental Protection Agency").  "Event-driven Process chain Architecture" also does not match the context in the roadmap; this is a term from business process modeling, not collision detection in game programming (source: https://en.wikipedia.org/wiki/Event-driven_process_chain). 

In fact, the current definition appears to be an AI-generated attempt to define "EPA" which tells the user to search for documentation to help define the term - which is generally considered a bad way of defining technical terminology.

A cursory Google search, shows that EPA is most likely referring to the "Expanding Polytype Algorithm". 

See the following for more information:

- https://winter.dev/articles/epa-algorithm
- https://dyn4j.org/2010/05/epa-expanding-polytope-algorithm/

**Comment by dansholds** [comment]
Please submit a PR to rectify this rather than an Issue.
