### ISSUE TITLE
The crashcourse unter the point "What is HTTP" is in hindi

### ISSUE THREAD

**Issue by Nyhmus** [kamranahmedse/developer-roadmap#7260]
### Roadmap URL

https://roadmap.sh/frontend

### Suggestions

The crashcourse unter the point "HTTP Crash Course" is in hindi, would be better to change it to an english crashcoursevideo.
Thanks

**Comment by motuncoded** [comment]
Good morning, can I work on the issue;

**Comment by dansholds** [comment]
> Good morning, can I work on the issue;

Just submit a PR to remove it.

**Comment by Nyhmus** [comment]
Hey, saw it was closed and looked for the PR and that one got rejected.
So the issue still exists.
I would suggest to switch the video back to the old one?
Old Video Link: https://www.youtube.com/watch?v=iYM2zFP3Zn0
Or another crashcourse video, because the videos as such are really helpfull from time to time.

**Comment by dansholds** [comment]
Since the OP doesn't want to open a PR to fix, I'll do it myself.
