### ISSUE TITLE
Android / Jetpack Compose subbranches

### ISSUE THREAD

**Issue by NirvanaDogra** [kamranahmedse/developer-roadmap#7266]
### Roadmap URL

https://roadmap.sh/android

### Layout:
- Box
-  Column
-  Row
-  BoxWithConstraints
- Spacer
-  ConstraintLayout
- Lazy lists

### Layout Modifiers: 
Size Modifiers
- size
- fillMaxSize/Width/Height
- requiredSize

Spacing Modifiers
- padding
- offset

Appearance Modifiers
- background
- border
- clip

Interaction Modifiers
- aspectRatio
- weight

Positioning Modifiers
- align
- matchParentSize

### Components
- Scaffold
- App bars
- Button
- Floating action button
- Card
- Chip
- Dialog
- Progress indicators
- Slider
- Switch
- Checkbox
- Badges
- Bottom sheets
- Navigation drawer
- Time pickers
- Date pickers
- Snackbar
- Divider
- Lists and grids

**Comment by dansholds** [comment]
What exactly is the context here?

**Comment by NirvanaDogra** [comment]
<img width="609" alt="image" src="https://github.com/user-attachments/assets/f9068517-1be2-4e5c-872d-25b9108449dd">


This is no longer a standard for creating Android layouts.  We use Jetpack Compose as the default way of making Android layouts. Jetpack compose has a completely different way of doing UI elements.  In the comment above I am trying to suggest sub-branches under Jetpack Compose similar to the one show in the image.

**Comment by jay-prakash001** [comment]
Hello everyone, Is there any help needed as i am android app developer with kotlin and jetpack compose. I am looking to help and gain some learning.

**Comment by jay-prakash001** [comment]
There is no projects are included in the android development roadmap, can i raise an issue and add them containing tech stacks used for the project, project difficulty level and resources to follow?

**Comment by dansholds** [comment]
> There is no projects are included in the android development roadmap, can i raise an issue and add them containing tech stacks used for the project, project difficulty level and resources to follow?

You can raise project issues yes
