### ISSUE TITLE
Software or Technical Architect Roadmap

### ISSUE THREAD

**Issue by rpmansion** [kamranahmedse/developer-roadmap#727]
#### What roadmap is this issue about?

- [ ] Frontend Roadmap
- [ ] Backend Roadmap
- [ ] DevOps Roadmap
- [x] All Roadmaps

#### What is this issue about?

- [ ] Discussion for a pull request I would want to open.
- [ ] Addition of a new item
- [ ] Removal of some existing item
- [ ] Changing in arrangement
- [ ] General suggestion
- [x] Sharing an Idea
- [ ] Something else

#### Please acknowledge the below listed

- [x] This is not a duplicate issue. I have searched and there is no existing issue for this.
- [x] I understand that these roadmaps are highly opinionated. The purpose is to not to include everything out there in these roadmaps but to have everything that is most relevant today comparing to the other options listed.
- [x] I have read the [contribution docs](../contributing.md) before opening this issue.

#### Enter the details about the issue here
I would love to see an overview roadmap for someone wanting to be a Software Architect/Technical Architect. What are the concepts the designation needs to grasp/apply to achieving their goal to be one.

**Comment by edisonpebojots** [comment]
[Software Architect Roadmap](https://github.com/AlaaAttya/software-architect-roadmap)

**Comment by rpmansion** [comment]
> [Software Architect Roadmap](https://github.com/AlaaAttya/software-architect-roadmap)

Looks good. It would be nice if this will be added here. :)

**Comment by lolptdr** [comment]
This one should be good to complement: https://github.com/donnemartin/system-design-primer

**Comment by ild0tt0re** [comment]
I found this 
https://github.com/stemmlerjs/software-design-and-architecture-roadmap
Inspired by web developer roadmap

**Comment by kamranahmedse** [comment]
We now have two roadmaps covering that [Software Architect](https://roadmap.sh/software-architect) and [Software Design and Architecture](https://roadmap.sh/software-design-architecture).
