### ISSUE TITLE
Cybersecurity Roadmap changes

### ISSUE THREAD

**Issue by ozymahdias** [kamranahmedse/developer-roadmap#7274]
### Roadmap URL

https://roadmap.sh/cyber-security

### Suggestions

Hey there,

There are a lot of things that are missing. I suggest adding definitions for SOC, CERT, MSSP, and other security units that a company might have.

Also, there are no definitions for WAF (Web Application Firewall), UTM (Unified Threat Management), XDR (Extended Detection and Response—there is EDR, but it's worth mentioning XDR), and defining DPI (Deep Packet Inspection) may be useful.

In the certificate section, I think OffSec should be included as an alternative to SANS.

I also believe that knowing companies that provide security solutions is crucial for newcomers. I recommend adding Fortinet, Splunk, Juniper, Palo Alto, Sophos, SolarWinds, and CrowdStrike.

**Comment by dansholds** [comment]
I'll add this to our internal board but I urge you to try and fit these topics into existing ones with a PR as the roadmap is already over 300+ topics at this point
