### ISSUE TITLE
"sync" package in goland developer's roadmap

### ISSUE THREAD

**Issue by AmirMahdyJebreily** [kamranahmedse/developer-roadmap#7275]
### Roadmap URL

https://roadmap.sh/golang

### Suggestions

Hello there, 
The sync package is one of the most useful packages in the field of synchronization and provides a series of types and functions to synchronize and control simultaneous access to shared data includes `Mutex`, `WaitGroup`, `RWMutex`, `Once` and etc...   
In the "Going Deeper" topic, you have included "Mutex", while you have not included "WaitGroup", which is used a lot. I suggest that you consider an item for "sync" and replace the "Mutex" item!

for more information about the "sync" package you can see this links : 
https://pkg.go.dev/sync
https://golang.withcodeexample.com/blog/synchronization-primitives-sync-package-go/
https://medium.com/@asgrr/golang-sync-4787b18fee41

**Comment by dansholds** [comment]
Added to internal board.
