### ISSUE TITLE
Reset progress button if i need to revise all topics again 

### ISSUE THREAD

**Issue by Temsaah** [kamranahmedse/developer-roadmap#7286]
### Feature Description

A reset button for each roadmap to reset the whole progress of each topic in the roadmap , if i need to revise the roadmap again

**Comment by DThiwanka** [comment]
Add Me

**Comment by dansholds** [comment]
![Screenshot 2024-10-01 at 14 19 41](https://github.com/user-attachments/assets/3963f7d8-a52e-4cee-9eb7-356add37fd69)

This feature exists

**Comment by Temsaah** [comment]
> This feature exists

tysm that is what i was looking for , i thought it make more sense for this to exist at each roadmap ui like here
![image](https://github.com/user-attachments/assets/d366cf98-8ec0-445b-956b-184e7f4639a0)

**Comment by Tejas-Sharma-dev** [comment]
since the feature already present, @dansholds please close the issue.
