### ISSUE TITLE
Improve readability of "Done" and "Skipped" items by reducing line-through thickness

### ISSUE THREAD

**Issue by faisalmh4045** [kamranahmedse/developer-roadmap#7287]
### Detailed Description

I’ve noticed that when an item is marked as "Done" or "Skipped," the line-through applied to the text is a bit thick, making the text harder to read. I want to suggest reducing the `text-decoration-thickness` to improve readability. This adjustment would enhance clarity while still clearly indicating the item's status.

**Comment by papali1305** [comment]
Hello sir , i can solve this issue

**Comment by developer-mohitsoni** [comment]
Hi @faisalmh4045, could you attach an image of the problem you're facing?

**Comment by papali1305** [comment]
yes sir it will be very help full if u attach the image

**Comment by faisalmh4045** [comment]
Hi @developer-mohitsoni, I’ve attached an image below to highlight the issue.
![Group 1 (1)](https://github.com/user-attachments/assets/0c8a287c-118d-4ab1-a0a1-e1faf29d7e41)

As you can see, for the "Done" and "Skipped" topics (highlighted with red arrows), the text is styled with a line-through. However, due to the thickness of the line, the text becomes a bit difficult to read.

**Comment by developer-mohitsoni** [comment]
Hi @faisalmh4045, I've already forked the repository and would like to work on this issue. However, I encountered this message while running the project live:

![Screenshot 2024-10-01 212615](https://github.com/user-attachments/assets/5d2bcc34-46db-4e0a-b5a2-1f21abb9301f)

![Screenshot 2024-10-01 212723](https://github.com/user-attachments/assets/a82d8e3c-ae65-456b-ad54-d7915e30b9a8)

**Comment by kamranahmedse** [comment]
Thank you for your suggestion but this is intentional.
