### ISSUE TITLE
The  simon says game using only html,css,and js

### ISSUE THREAD

**Issue by kenzo0p** [kamranahmedse/developer-roadmap#7288]
`###` What Roadmap is this project for?

Frontend Roadmap

### Project Difficulty

Intermediate

### Add Project Details

What is this project about?
    The **Simon Says Game** is an interactive memory game built using HTML, CSS, and JavaScript. The game challenges the player 
    to memorize and repeat a sequence of colored lights and sounds. As the player progresses, the sequence gets longer and 
    more difficult, testing their memory and attention to detail. This project demonstrates core web development concepts such 
    as DOM manipulation, event handling.
    [I already work on this project if you want link i will provide you .]

Skills this Project Covers
HTML, CSS, JavaScript, DOM Manipulation, Event Handling, Responsive Design, Game Logic

Requirements
Game Layout:
 -The game features four color buttons (red, green, blue, yellow) displayed on the screen in a grid format.
 -Press any key on keyboard to start the game or you can add button to start the game .
 - when you win one level you should go next level that level should be shown .
 - and when you failed to remeber the pattern you should go back to level 1st with msg pattern was wrong in red color with red -background for 2 or three second 
 

- checkout the image for design (that states its like a **junior level mini-project**)
![Screenshot 2024-10-01 201414](https://github.com/user-attachments/assets/5ed745fa-f71b-43f6-9f7f-79445fffeb6a)
![Screenshot 2024-10-01 201430](https://github.com/user-attachments/assets/a4ad7163-aa90-4b5f-87ff-78a7de310b5e)

**Comment by Bornin112004** [comment]
i would like to work on this

**Comment by fiopefoluwa** [comment]
I would like to work on this, new to open source

**Comment by Himanshuwadhwa1** [comment]
@kenzo0p  I would like to contribute on this project! I have already worked on this type of project here is the live link [https://the-simon-game-coral.vercel.app/](url) 
As I’m new here, I would appreciate any guidance you can provide.

Thank you!

**Comment by Deepikakolli4** [comment]
@kenzo0p 
would like to contribute on this project! I have already built it using html,css,js.

**Comment by dasakash26** [comment]
I want to work on this.

**Comment by dansholds** [comment]
This is not something that anyone can work on, when it comes time to add new projects, we will.

**Comment by Meetpidev** [comment]
@kenzo0p I would like to contribute on this project!

**Comment by Rishi-k-s** [comment]
@dansholds That is a great initiative

**Comment by spriyanshucoder** [comment]
I would like to contribute on this project!

**Comment by dansholds** [comment]
> @dansholds so can i pull request for adding the project as i already made it as a part of hactoberfest

No

**Comment by dansholds** [comment]
> @dansholds so can i pull request for adding the project as i already made it as a part of hactoberfest

The guidelines for hacktoberfest contributions are very clear, so please refer back to them.

**Comment by dansholds** [comment]
Add memory game to this pr - https://github.com/kamranahmedse/developer-roadmap/pull/7509

(its not really simon says as simon says aims to trick the user into **not** doing something)
