### ISSUE TITLE
Recommendations for a printing and presentations

### ISSUE THREAD

**Issue by corewarrior** [kamranahmedse/developer-roadmap#730]
#### What roadmap is this issue about?

- [ ] Frontend Roadmap
- [ ] Backend Roadmap
- [ ] DevOps Roadmap
- [X ] All Roadmaps

#### What is this issue about?

- [ ] Discussion for a pull request I would want to open.
- [ ] Addition of a new item
- [ ] Removal of some existing item
- [ ] Changing in arrangement
- [X] General suggestion
- [ ] Sharing an Idea
- [ ] Something else

#### Please acknowledge the below listed

- [X] This is not a duplicate issue. I have searched and there is no existing issue for this.
- [ ] I understand that these roadmaps are highly opinionated. The purpose is to not to include everything out there in these roadmaps but to have everything that is most relevant today comparing to the other options listed.
- [X] I have read the [contribution docs](../contributing.md) before opening this issue.

#### Enter the details about the issue here
Kamran I love your work but there are two things that would make it perfect and much more useful.
* use two entirely different symbols for Personal Recommendation and Alternative Recommendation. If you print a roadmap on a standard laser printer the symbols look very similar in color which obscures your recommendations.
* Put a little more space in the diagrams so they can be cleanly printed in pieces for training purposes, either for slide presentations or for a handout.

Thanks again for your great work!

**Comment by ironman1987** [comment]
this issue very good!

**Comment by kamranahmedse** [comment]
Thank you for the kind words. Can you please try with the updated version of the roadmaps? You can find the PDFs at https://roadmap.sh/pdfs
