### ISSUE TITLE
adding GitHub Actions to CI/CD skillset

### ISSUE THREAD

**Issue by mzarycki11** [kamranahmedse/developer-roadmap#7300]
### Roadmap URL

https://roadmap.sh/qa

### Suggestions

I would like to add GitHub Actions to the CI/CD skillset for QA

**Comment by omdhede** [comment]
can you provide some more detail?
Do you want to update this part of the CI/CD skillset with a walkthrough for GitHub Actions?

<img width="601" alt="Screenshot 2024-10-03 at 3 02 03 PM" src="https://github.com/user-attachments/assets/0ce470af-0014-4d6b-9d9c-162276627b5d">

**Comment by neerajmanivarnan** [comment]
I would love to work on this issue.Could you please assign this to me?

**Comment by omdhede** [comment]
> I would love to work on this issue.Could you please assign this to me?

> If I am not wrong , he is asking to add github actions as a skill set to the CI/CD step in QA section.

I am already working on it!

**Comment by dansholds** [comment]
Having more than 8 CICD providers on the QA roadmap is overkill.
