### ISSUE TITLE
Position of the Navigation Bar

### ISSUE THREAD

**Issue by Jils31** [kamranahmedse/developer-roadmap#7302]
### Feature Description

As an user scroll down the page the navigation bar scroll alongs and if someone wants to access the feature of the navigation bar from the end of the page he/she may not able to.

https://github.com/user-attachments/assets/8401faad-ed44-4f02-915c-7f899f9160e8

I would like to work on this issue

**Comment by VANSH3104** [comment]
@Jils31  can you explain the issue properly I want to work on it

**Comment by Jils31** [comment]
The position of the navigation bar is not fixed thus if this feature is added in the page then user will access all the links from any section of the page

**Comment by VANSH3104** [comment]
@Jils31  can you assigned this issue to me

**Comment by Epik-Whale463** [comment]
I have fixed the issue , please assign the issue to me , I am ready to send **pr**

**Comment by offensive-vk** [comment]
Actually @dansholds , i forgot to invite you to the discussion 😅

Have a look: https://github.com/kamranahmedse/developer-roadmap/pull/7304

**Comment by kamranahmedse** [comment]
We will be redesigning the navigation soon so it doesn't make sense to change this now. Thank you for the suggestion though.
