### ISSUE TITLE
Better colors for In Progress topics

### ISSUE THREAD

**Issue by Lau-San** [kamranahmedse/developer-roadmap#7303]
### Feature Description

Right now I think Completed and In Progress topics look too similar, which can make it hard to differenciate them.

![image](https://github.com/user-attachments/assets/61156f8e-8cf6-4df3-8d62-da6bdc2d515a)

So maybe the In Progress topics could have a bolder color to make it easier to visualize?

**Comment by akshaywakhare** [comment]
Hi, I'd like to fix this, could you assign this to me

**Comment by Rishikesh63** [comment]
@Lau-San  i would like to solve it can you please assign me

**Comment by Lau-San** [comment]
> @Lau-San i would like to solve it can you please assign me

If you're asking me to assign this to you, I don't think I have the permissons for that.

**Comment by Meetpidev** [comment]
Hi, I'd like to fix this, could you assign this to me?

**Comment by Stranger1298** [comment]
Please assign this issue to me

**Comment by Mohitpanjikar** [comment]
Hey, I would love to work on this feature. Has it been assigned to someone, or should I start working on it?

**Comment by SamPrinceFranklin** [comment]
I'd love to work on this! I think it's a great idea to improve the visual distinction between "Completed" and "In Progress" topics. It would definitely make the interface easier to understand at a glance. Do you have any specific colors in mind, or would you like me to experiment with some options?

**Comment by Lau-San** [comment]
I was thinking something like green since I don't think it's being used anywhere else on the roadmaps, but you can try other things if you have a better idea

**Comment by dansholds** [comment]
This isn't a priority feature at this time, but we may revisit in the future.
