### ISSUE TITLE
Topic is missing.

### ISSUE THREAD

**Issue by sharma-creator** [kamranahmedse/developer-roadmap#7312]
### Roadmap URL

https://roadmap.sh/python

### Suggestions

String topic is not available and if it is a sub part of any topic it should be studied before starting Data Structures.

**Comment by adityaj2206** [comment]
please assign this issue to me

**Comment by sharma-creator** [comment]
**String** Topic is missing as it contains a lot of operations and inbuilt functions and substrings.

**Comment by AustinD123** [comment]
please assign this issue to me

**Comment by sharma-creator** [comment]
> please assign this issue to me

I don't have permission to do so.

**Comment by dansholds** [comment]
It's not getting assigned to anyone, new nodes cannot be added by contributors.

I've added it to the internal board and it will be tackled soon.
