### ISSUE TITLE
Shortcuts for easy navigation and action.

### ISSUE THREAD

**Issue by noobyco** [kamranahmedse/developer-roadmap#7316]
### Feature Description

We should consider significant pages of the website to navigate through shortcut keys, likewise for the actions. I have provided a sample navigation and action shortcut list at the end.

### 1. Command pallet (VSCode-like)

![image](https://github.com/user-attachments/assets/9588775f-cba4-4bc5-b280-89288c9cd49d)

### 2. Shortcuts panel (Twitter-like)
![image](https://github.com/user-attachments/assets/53ec31f6-c554-4a4a-b3d1-814741ebf5d8)

<br>

If we choose to go with the command pallet we don't need to map each command with shortcut keys whereas for the shortcuts panel, we do. Here is the list of sample shortcut keys and actions.

| Navigation | Nav-shortcut-key |
|--------|--------|
|Homepage https://roadmap.sh/ | g+h |
| Official Roadmap https://roadmap.sh/roadmaps | g+o |
| Projects https://roadmap.sh/projects | g+p |
| Best Practice https://roadmap.sh/projects | g+b |
| Questions https://roadmap.sh/projects | g+q |
| Guide https://roadmap.sh/guides | g+x |
| Videos https://www.youtube.com/@roadmapsh | g+v |
| Shop https://cottonbureau.com/people/roadmapsh | g+s |
| Advertise https://roadmap.sh/advertise | g+a |
| Teams https://roadmap.sh/teams | g+t |
| Account https://roadmap.sh/account | a | 
| My profile https://roadmap.sh/account/update-profile | p | 

| Actions | Action-shortcut-key |
|--------|--------|
|  New roadmap <br> ![Untitled-2024-01-19-2003](https://github.com/user-attachments/assets/2f10d80f-2298-4583-846f-ba1ba4e1b7d2) | r | 

- Please don't consider it as a final list. We can add more in the future :)

**Comment by dansholds** [comment]
This is a luxury feature and not one that we will be considered atm.

**Comment by noobyco** [comment]
Sure thanks for the confirmation.
