### ISSUE TITLE
Add Higher Order Function in Function category in JavaScript roadmap

### ISSUE THREAD

**Issue by UdaySharmaGitHub** [kamranahmedse/developer-roadmap#7326]
### Roadmap URL

https://roadmap.sh/javascript

### Suggestions

Add Higher Order Function in Function category in JavaScript roadmap.
![image](https://github.com/user-attachments/assets/44164f1a-3647-403b-85ec-a81620d8c97b)

**Comment by 0PrashantYadav0** [comment]
I would like to work on this issue please assign this to me

**Comment by wizaye** [comment]
Sound's Intresting! could you pleaseassign this to me

**Comment by Mang0codes** [comment]
hii.. since Renderer is a private component I cannot see the changes I am making also the id for each topic/sub-topic is it randomly generated??

**Comment by dansholds** [comment]
added to internal backlog.
