### ISSUE TITLE
Numbered Topics

### ISSUE THREAD

**Issue by glamorous-chi** [kamranahmedse/developer-roadmap#7328]
### Feature Description

I think it will be useful to add numbers to the topics in yellow rather than having to trace the blue line to find the next topic to focus on, it will help in making the roadmap less confusing and prevent derailment.

**Comment by pragyananda** [comment]
can I work on this under Hacktoberfest?

**Comment by molxno** [comment]
Hi! @glamorous-chi please asign me this feature :)

**Comment by dansholds** [comment]
For now, the blue line does it's job and this isn't a priority feature.
