### ISSUE TITLE
Add Serverless Frameworks on AWS Roadmap

### ISSUE THREAD

**Issue by mecoxeco** [kamranahmedse/developer-roadmap#7335]
### Roadmap URL

https://roadmap.sh/aws

### Suggestions

My suggestion is basically to add serverless development frameworks as a topic at the end of the roadmap, such as the Serverless Framework and SST, It would be interesting to mention them as they deal directly with Amazon's CDK

Serverless -> https://www.serverless.com
SST/ion -> https://sst.dev

**Comment by PrajwalArali** [comment]
Please assign me, I want to work on this.

**Comment by yashs33244** [comment]
I can do this, Please assign me this task..

**Comment by dansholds** [comment]
The AWS roadmap is specifically for AWS not tools that use AWS, otherwise that would be a significant amount of tools!
