### ISSUE TITLE
Feedbacks

### ISSUE THREAD

**Issue by Theprodutgenius** [kamranahmedse/developer-roadmap#7338]
### Detailed Description

Hi there, i think adding little arrows to show which topic is next would really help in simplifying roadmaps and enable easier navigation of what topic to take next when reading, going through or studying. Hope you find this helpful. Thanks

**Comment by Harshbansal8705** [comment]
I just checked the feature is already there. The person creating roadmap just needs to add arrows while creating the roadmap.
