### ISSUE TITLE
Tools used to develop the site

### ISSUE THREAD

**Issue by mpara0** [kamranahmedse/developer-roadmap#734]
#### What roadmap is this issue about?

- [X] Frontend Roadmap
- [ ] Backend Roadmap
- [ ] DevOps Roadmap
- [ ] All Roadmaps

#### What is this issue about?

- [ ] Discussion for a pull request I would want to open.
- [ ] Addition of a new item
- [ ] Removal of some existing item
- [ ] Changing in arrangement
- [ ] General suggestion
- [ ] Sharing an Idea
- [X] Something else

#### Please acknowledge the below listed

- [X] This is not a duplicate issue. I have searched and there is no existing issue for this.
- [X] I understand that these roadmaps are highly opinionated. The purpose is to not to include everything out there in these roadmaps but to have everything that is most relevant today comparing to the other options listed.
- [X] I have read the [contribution docs](../contributing.md) before opening this issue.

#### Enter the details about the issue here

Just out of curiosity, what tools and frameworks did you use to the develop the site? I really like how simplistic the UI is and how well put together the site is. I was going through the files for this repository and noticed that it is predominantly markdown files.

I'm only asking this because my friend and I want to develop a resource guide and we initially thought of going with reactJS but this site is very appealing and interactive with its users

**Comment by mwmichael** [comment]
Hi Monika, 

Kamran has written a couple tweets which probably satisfies your question.

https://twitter.com/kamranahmedse/status/1261601454885949442

"The question I get asked the most on the infographics I post is "Which tool did you use to make these". It doesn't matter what tool you use, the content matters.

Someone hungry doesn't care how the food is served, they just care about the food. People are hungry for the content.

As far as tools are considered, I normally use

https://balsamiq.com/
 
https://www.figma.com

https://excalidraw.com/
"

**Comment by kamranahmedse** [comment]
Yes, the diagrams are made with a mix of these tools mentioned by @mwmichael (thanks :))

As for the website, it's a static site generated using Next.js SSG and uses Bootstrap.
