### ISSUE TITLE
Suggestion About Link Tags

### ISSUE THREAD

**Issue by offensive-vk** [kamranahmedse/developer-roadmap#7342]
### Feature Description

I believe the current label for the `@opensource` link types, which currently points to `GitHub`, is overly specific. While GitHub is a popular platform for open-source projects, it's not the only one available. 

To promote a more inclusive approach, I suggest changing the label to "Opensource" instead.
Other way is that, we create seperate labels for each platforms (popular ones) i.e. Gitlab, Bitbucket, etc., then add them accordingly.

**Comment by offensive-vk** [comment]
What do you think @arikchakma ?

**Comment by arikchakma** [comment]
> What do you think @arikchakma ?

I agree, we will discuss it internally.

**Comment by VANSH3104** [comment]
@arikchakma @offensive-vk I like to work on this also

**Comment by arikchakma** [comment]
> @arikchakma @offensive-vk I like to work on this also

Thank you for showing your interest but we are almost there. I am going to open the PR in a few minutes.
