### ISSUE TITLE
Link Tag is not Rendering.

### ISSUE THREAD

**Issue by offensive-vk** [kamranahmedse/developer-roadmap#7343]
### What is the URL where the issue is happening

https://roadmap.sh/backend

### What browsers are you seeing the problem on?

Chrome

### Describe the Bug

The `@opensource` tag is not loading in `bcrypt` topic in Backend Roadmap.

## After opening devtools:
![image](https://github.com/user-attachments/assets/7d9830c2-3d9a-4381-bc1a-279e1d48db73)

### Output from browser console (if any)

![image](https://github.com/user-attachments/assets/51e3c254-5c21-496d-ba7b-fcb3adfded1d)

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by arikchakma** [comment]
It's in a wrong format that's why. It should be a GitHub/GitLab link.
