### ISSUE TITLE
Suggestion About Leaderboards

### ISSUE THREAD

**Issue by offensive-vk** [kamranahmedse/developer-roadmap#7355]
### Feature Description

Dear Maintainers,

I'd like to suggest a small change in *github leaderboard* ranking system on https://roadmap.sh/leaderboard that should primarily focuses on the number of merged pull requests (PRs) rather than simply the number of opened PRs. 

As a result, the final outcome of the pr can vary upon the changes it introduces.

This approach would better reflect the actual contributions made to the project and provide a more accurate measure of a user's contributions.

**Comment by arikchakma** [comment]
This leaderboard is based on closed PRs not opened PR count. You can have a look the [GitHub API for more details](https://docs.github.com/en/rest/pulls/pulls?apiVersion=2022-11-28#list-pull-requests).
