### ISSUE TITLE
Add - Copy 'official roadmap' into private editor space for Content submissions. 

### ISSUE THREAD

**Issue by iPoetDev** [kamranahmedse/developer-roadmap#7358]
# Feature Description

A copy button, next to the Suggest Changes, so to create copied of official roadmaps in the private roadmap editors. 

This would have the impact of a more visual roadmap content creation workflow by utilizing the member's private roadmap editor as an official roadmap content editor, prior to submitting 'Suggested Changes' and allows less technical/skill set users and regular contributors to submit content and update existing content. 

## Overview
- Copying 'Official Roadmaps' into each member account's roadmap editor with a button.
- As content contributors, the newly updated `Contributing.md` suggest the following
  1. New Roadmaps: request that an interactive roadmap using your own roadmap editor and link to that roadmap to an issue
  2. Adding or Removing Nodes — requires opening an issue
  3. Adding Content — suggests adding content directly to the ['scr/data/roadmaps`](https://github.com/kamranahmedse/developer-roadmap/tree/master/src/data/roadmaps)

### Proposals Why

To copy an existing roadmap, to own editor, would allow first time issue contributors and repeat contributors to be more effective with adding content without always delving and understanding the content data structures and codebase.

A copied official roadmap could, while put under restrictions, serve as a private editing space for CRUD changes to 'official roadmaps', particularly when their content is sparse.

A final candidate roadmap to linked to an issue (as above), would/could simplify content review and approval by being visual and ease the contribution workflow.

The contributor or any user can have a custom roadmap of the official for their own annotations and notes.

> ### Hacktober 2024
> - As an idea contributor, I do not have the react or javascript skills to implement.
> - As a content contributor, who wishs to add content, I would rather copy an existing roadmap into my roadmap editor, so that I do not have to manually recreate the roadmap so I can create the new content in a private space.

### Functional requirements

- Put a copy into own roadmap button on each 'Official Roadmap'
- Only display a copy button if the user is an account member.
- Restrict the copying to one way, and one time per roadmap/per user
- Restrict the republications of these copied roadmaps so not to cross purpose the official roadmaps

### Non-functional requirements

- Provide a quality control plane for reviewing content contributor's contributions in a more human-readable/final product view.
- Prevent low quality versions of the roadmap being made public by classifying such copies as (internal review only) or (private use only).

### User Story
As a (first time | regular) content contributor, who wishes to add content to official roadmaps,
I would rather copy an existing official roadmap into my roadmap editor,
So that I do not have to manually recreate the roadmap 
  AND so I can create the new content in a private space to develop the content on platform.

## Acceptance Criteria
- Given I copy the official roadmap, when I want to edit and develop content, then I can add content and links via the visual roadmap editor.

## Related | Similar Issues
- Jan 4 2024 : Copy the content and links during creating own version of a roadmap #4976

**Comment by Hriishikeshh** [comment]
hey i would love to contribute on this issue
please assign it to me 
also help me with hacktoberfest2024 tag if possible

**Comment by dansholds** [comment]
@iPoetDev we will but this on the back burner, it's a good idea but involved a significant amount of time to implement.

**Comment by iPoetDev** [comment]
Understood.

Just saying, as I spent 2 days replicating a copy of AI Engineer into a custom roadmap and it morphed into a different version instead of a identical replica.

Also it would help with content reviewing for existing content (content maintenance,,), and several days porting the contents for editing into another platform (Notion) so edits to current contents that may be 18 Months out of date be reviewed, edited, and consistently maintained.

So this lack of a copy function is a bottlenecks to more efficient content maintenance and content reviewing on PR.

Out of date content is an aclumination risk of being out dated or less relevance, particularly in highly dynamic content domains for AI / ML etc
