### ISSUE TITLE
Algorithms?

### ISSUE THREAD

**Issue by cjmz** [kamranahmedse/developer-roadmap#736]
Hi y’all, I hope everyone here are well with all these things happening in the world.

I just wanna ask why I found nothing about algorithm in back end developer roadmap...

I’ve been working as backend about 5 years and nowadays I see algorithms as the most relevant subject to get a job in a relevant tech company, at least where I live (Brazil).

**Comment by kamranahmedse** [comment]
Hey, thank you for opening. It is listed in the ["Required for any path" section ](https://github.com/kamranahmedse/developer-roadmap#introduction)
