### ISSUE TITLE
Status feature

### ISSUE THREAD

**Issue by rkumarkravi** [kamranahmedse/developer-roadmap#7361]
### What Roadmap is this project for?

Frontend Roadmap

### Project Difficulty

Advanced

### Add Project Details

You are required to build a "Story" feature similar to those found in popular social media platforms like Instagram and WhatsApp. The goal is to allow users to post short, ephemeral content that disappears after 24 hours. This content can include images, text, videos, and links, and can be viewed by followers or contacts through an interactive and visually appealing interface.

**User Interface (UI)**:
   - Design a vertical or horizontal story bar at the top of the app or a dedicated tab, showing round profile pictures or thumbnails of users who have posted stories.
   - When a user taps on a profile picture, the corresponding story content should display in full-screen mode.
   - Include a progress bar at the top of the screen to indicate the duration of each story being viewed.
   - Users should be able to swipe left or right to switch between stories, and tap to move forward within the current story.
   - Provide the ability for users to reply to or react to stories through direct messages.
   
For a sample image, imagine a screen with a series of round profile pictures aligned horizontally at the top, representing different users’ stories. Below that, a story is displayed in full-screen, showing an image with a caption at the bottom and swipe indicators. A progress bar runs across the top, representing the time left for the current story.

![image](https://github.com/user-attachments/assets/94b06143-ccb3-4853-bd87-c93cd5094a72)
![image](https://github.com/user-attachments/assets/2b9ee0df-5fda-4d1d-8546-d676d209dcdc)

**Comment by Radha2786** [comment]
Hi @rkumarkravi , can you assign this task to me

**Comment by dansholds** [comment]
> Hi @rkumarkravi , can you assign this task to me

This is not a task, this is a request to add a project to the platform.

**Comment by Hriishikeshh** [comment]
hey i would love to contribute on this issue
please assign it to me 
also help me with hacktoberfest2024 tag if possible

**Comment by dansholds** [comment]
Added to this pr - https://github.com/kamranahmedse/developer-roadmap/pull/7509

adjusted to account for the fact that it shouldn't include backend work.
