### ISSUE TITLE
Scroll Back to Top Button on Roadmap Pages

### ISSUE THREAD

**Issue by sanjesh17** [kamranahmedse/developer-roadmap#7381]
### Feature Description

Add a "Scroll Back to Top" button to the Roadmap pages. The button will appear when users scroll down and smoothly bring them back to the top with a single click. This will improve the overall user experience by making navigation easier on long pages. It should be positioned in the lower-right corner for easy access and should be responsive on both desktop and mobile devices. The design should be minimalistic to blend seamlessly with the existing layout and theme of the pages.

**Comment by devXpraAddy** [comment]
hey, can you assign me this i want to work on this issue

**Comment by offensive-vk** [comment]
No assignment is required, just start working on this feature and submit a PR. Also please refrain from pinging maintainers.

**Comment by nirmitsaini1024** [comment]
@offensive-vk Please Review. 

https://github.com/user-attachments/assets/e1dccf2a-d837-4872-8747-88b1c326e4f3

**Comment by offensive-vk** [comment]
Does it also work outside of a roadmap? Like other parts of the site.

**Comment by devXpraAddy** [comment]
Please review

https://github.com/user-attachments/assets/e4f7fb5c-6714-4d52-ae74-bd0fa060cc6e

**Comment by nirmitsaini1024** [comment]
@offensive-vk yes it works on other pages as well.

**Comment by offensive-vk** [comment]
cc @arikchakma

**Comment by dandrok** [comment]
It looks like this feature is no longer needed?

> We're working on refactoring this, so there's no need to do that. Please wait for approval before you start working on such changes. Thanks though!

**Comment by arikchakma** [comment]
Thank you for raising the issue. Yeah, we are in the process of refactoring the app.
