### ISSUE TITLE
Scroll To Top Button

### ISSUE THREAD

**Issue by sp9324** [kamranahmedse/developer-roadmap#7383]
### Feature Description

Issue: To add a scroll to top button so that user can navigate pages easily. The pages are quite long, which makes it difficult to navigate using scrollbar.
Please assign this issue to me, @kamran

Preview:
https://github.com/user-attachments/assets/b3519dc6-782c-40d1-b286-bd8a970a693a

**Comment by kamranahmedse** [comment]
We will be redesigning the whole thing soon so there is no need for this. Thank you for the suggestion though.
