### ISSUE TITLE
ANIMATIONS LIBRARIES

### ISSUE THREAD

**Issue by PriyamUttam-Dev** [kamranahmedse/developer-roadmap#7385]
### What is the title of the roadmap you are submitting?

Animation Libraries for Front-end Developement using js

### Roadmap Link

You can learn to implement 3d animations on your websites using three.js
https://roadmap.sh/ai/creative-web-development-using-css-gsap-and-threejs
https://threejs.org/
https://roadmap.sh/ai/threejs-mastery-bm1om
You can learn gsap for more easier implementation of animations on your front end project 
learn from this documentation
https://gsap.com/
https://roadmap.sh/ai/gsap-3d-animation

**Comment by dansholds** [comment]
Makes sense, I'll add it to the internal board.

**Comment by PriyamUttam-Dev** [comment]
Thanks for considering this!!
