### ISSUE TITLE
Suggestions: Add topic 'RAFT' into Computer Science roadmap

### ISSUE THREAD

**Issue by sergey-belikov** [kamranahmedse/developer-roadmap#7392]
### Roadmap URL

https://roadmap.sh/computer-science

### Suggestions

# RAFT

**Raft** is a [consensus](https://en.wikipedia.org/wiki/Consensus_(computer_science)) algorithm designed as an alternative to the [Paxos](https://en.wikipedia.org/wiki/Paxos_(computer_science)) family of algorithms.

**Raft** offers a generic way to distribute a [state machine](https://en.wikipedia.org/wiki/Finite-state_machine) across a [cluster](https://en.wikipedia.org/wiki/Computer_cluster) of computing systems, ensuring that each node in the cluster agrees upon the same series of state transitions.

Raft is not a [Byzantine fault](https://en.wikipedia.org/wiki/Byzantine_fault) tolerant (BFT) algorithm; the nodes trust the elected leader.

Visit the following resources to learn more:
- [The Raft Consensus Algorithm](https://raft.github.io/)
- [Raft Consensus Algorithm](https://www.geeksforgeeks.org/raft-consensus-algorithm/)
- [WIKI - Raft (algorithm)](https://en.wikipedia.org/wiki/Raft_(algorithm))

**Comment by ParvathySajayan** [comment]
Can I solve this issue?

**Comment by sergey-belikov** [comment]
> Can I solve this issue?

Yes, sure.

**Comment by dansholds** [comment]
> Can I solve this issue?

This is a request to add a project to roadmap.sh/projects. Please understand the circumstances of the issue before asking for it to be assigned to you for completion.

**Comment by dansholds** [comment]
added to internal board
