### ISSUE TITLE
Strings topic missing in the python roadmap

### ISSUE THREAD

**Issue by Asjdnnc** [kamranahmedse/developer-roadmap#7393]
### Roadmap URL

https://roadmap.sh/python

### Suggestions

Please include Strings as a topic in the Data Structures & Algorithms section, as they play a crucial role in DSA and are an important concept for problem-solving.

**Comment by Asjdnnc** [comment]
@kamranahmedse please assign this issue to me

**Comment by dansholds** [comment]
This has been requested multiple times (check issues before you create new ones.)

This is in our backlog to complete.
