### ISSUE TITLE
deprecated link\not reachable site

### ISSUE THREAD

**Issue by Paschroeder** [kamranahmedse/developer-roadmap#7395]
### Roadmap URL

https://roadmap.sh/software-architect

### Suggestions

In the first topic: What is Software Architecture the following link could be replaced because the site is not reachable anymore.
Mabye this blog post is like the on ebefore?
https://wezom.com/blog/what-is-architecture-in-software-engineering

**Comment by dansholds** [comment]
Please submit a PR for this, not an issue, you can action this yourself.

**Comment by Paschroeder** [comment]
i tried but i do not have rigths to push a branch.

**Comment by Paschroeder** [comment]
> i tried but i do not have rigths to push a branch.

all good i figured out how to contribute. sry is my first time. :)

**Comment by dansholds** [comment]
> > i tried but i do not have rigths to push a branch.
> 
> all good i figured out how to contribute. sry is my first time. :)

No worries, glad you figured it out.
