### ISSUE TITLE
Track progress

### ISSUE THREAD

**Issue by iamsyg** [kamranahmedse/developer-roadmap#7405]
### Feature detail

We can add a page where users can track their learning progress on a roadmap they're following by marking their progress on the tech stack.

### Benefits

**Improved User Engagement:**

- Motivation: Seeing progress visually keeps users motivated as they complete tasks or modules.
- Goal-Oriented Learning: Users can set goals and stay committed by tracking their progress step by step.

**Personalization:**

- Customized Experience: Users can follow their own learning roadmap, which can be tailored to their skill level and goals.

**Increased Accountability:**

- Progress Feedback: Users are more likely to stay on track when they can see their progress and how much remains.
- Task Completion: Users can check off completed tasks, helping them stay organized and accountable.

**Comment by kamranahmedse** [comment]
We already have progress tracking on roadmaps

<img width="1080" alt="image" src="https://github.com/user-attachments/assets/23a8427f-ccd0-4ad1-af38-5c074c6fe3e6">

Do you mean something else?
