### ISSUE TITLE
Broken Link on React Roadmap > Component Life Cycle

### ISSUE THREAD

**Issue by belikedeep** [kamranahmedse/developer-roadmap#7407]
### What is the URL where the issue is happening

https://roadmap.sh/react

### Describe the Bug

The link to official resource to [Lifecycle of Reactive Effects](https://react.dev/learn/lifecycle-of-reactive-effectsv) is invalid/broken

![Screenshot from 2024-10-09 19-24-03](https://github.com/user-attachments/assets/369a711c-03a0-4dd4-96b4-3f32b5148f52)

It's a typo.........ig at the end  ....reactive-effects rather than effectsv.

### Participation

- [X] I am willing to submit a pull request for this issue.

**Comment by offensive-vk** [comment]
What's the status here? @belikedeep

**Comment by nitesh2920** [comment]
can I work on this issue ? @offensive-vk

**Comment by offensive-vk** [comment]
Sure buddy

**Comment by nitesh2920** [comment]
> Sure buddy 

I have to change the link in md first ?

**Comment by offensive-vk** [comment]
Yeah, find the source markdown file for that topic and then fix it.

Watch out for any other bugs too.

**Comment by belikedeep** [comment]
Fixed
