### ISSUE TITLE
Add more information for each topic and make the roadmap look easier and efficient

### ISSUE THREAD

**Issue by Shravani-A-Kulkarni** [kamranahmedse/developer-roadmap#7408]
### Feature Description

We should add more description and links to help users find the resources and learn from best platforms. Also the roadmap should look easier for a user to see and start learning according to it . For example the types of ML and its Algorithms should be right in front of it ,rather than placed down previously

**Comment by offensive-vk** [comment]
Let's say, if you had power to do the same, which roadmap would you start with? @Shravani-A-Kulkarni

**Comment by Shravani-A-Kulkarni** [comment]
Data analyst
