### ISSUE TITLE
Calculator CLI Program

### ISSUE THREAD

**Issue by coderSaptak** [kamranahmedse/developer-roadmap#7409]
### What Roadmap is this project for?

Python

### Project Difficulty

Beginner

### **Calculator CLI Program**

You are given a Python command-line interface (CLI) calculator program that performs basic arithmetic operations such as addition, subtraction, multiplication, and division. The program allows users to:

*   Add two numbers
*   Subtract one number from another
*   Multiply two numbers
*   Divide one number by another (except by zero)

The program continues to prompt the user for input until they decide to exit by pressing 'Q' or 'q'. The application handles errors gracefully, ensuring that invalid inputs do not crash the program.

### **Question:**

1.  **Functionality Testing:**
    
    *   Run the Calculator CLI program and test it by performing the following actions:
        1.  Add two numbers, e.g., 5 and 3.
        2.  Subtract 3 from 5.
        3.  Multiply 4 and 7.
        4.  Divide 8 by 2.
        5.  Attempt to divide by zero.
        6.  Quit the application using 'Q' or 'q'.

2.  **Error Handling:**
    
    *   Describe how the program handles invalid inputs, such as entering non-numeric values when prompted for numbers.
    *   What feedback does the program provide when the user attempts to divide by zero?

3.  **Feature Suggestion:**
    
    *   Suggest one additional feature that could be implemented in the Calculator CLI to enhance its usability, such as the ability to perform calculations with more than two numbers or to support additional mathematical operations (e.g., exponentiation, square roots).

**Comment by kamranahmedse** [comment]
Thanks, we will consider it when we get to it.
