### ISSUE TITLE
Build your own Docker

### ISSUE THREAD

**Issue by Aniket7250** [kamranahmedse/developer-roadmap#7411]
### What Roadmap is this project for?

DevOps Roadmap

### Project Difficulty

Intermediate

### Add Project Details

Build your own docker and image registry. And you should be able to run images and perform commands that are used by Docker

**Comment by dansholds** [comment]
Can you do this?

**Comment by ARUNPARMAL** [comment]
Hey I am interested to do so if no one is working i would like to take this issue

**Comment by dansholds** [comment]
> Hey I am interested to do so if no one is working i would like to take this issue

This is not an issue you can "take" it's a suggestion of a project to add.
