### ISSUE TITLE
Log File Integrity Checker

### ISSUE THREAD

**Issue by jaromtia** [kamranahmedse/developer-roadmap#7431]
### What Roadmap is this project for?

Cyber Security Expert

### Project Difficulty

Beginner

## What is this project about?

Verify the integrity of system or application log files to detect tampering.

## Skills this Project Covers

In this project, you will develop a tool that verifies the integrity of log files to detect tampering. This project will help you understand file integrity monitoring, hashing techniques, and log analysis

## Requirements

The application should:

- Accept a directory of log files as input.
- Calculate cryptographic hashes (e.g., SHA-256) for each log file.
- Compare the hashes with previously stored hashes to check for tampering.
- Report any discrepancies in file integrity

Example output:
```bash
- Log file: /var/log/syslog
- Status: Modified (Hash mismatch)

- Log file: /var/log/auth.log
- Status: Unmodified
```

Handle errors gracefully, such as permission issues or missing log files.
Use any language of your choice to build the tool

---
Advanced version:
- Implement real-time monitoring and alerting for log tampering.
- Add the ability to store hashes securely
- Include logging of the detection events for audit purposes

**Comment by Hriishikeshh** [comment]
hey i would love to contribute on this issue
please assign it to me 
also help me with hacktoberfest2024 tag if possible

**Comment by dansholds** [comment]
Adding in the following PR - https://github.com/kamranahmedse/developer-roadmap/pull/7509
