### ISSUE TITLE
Password Strength Checker

### ISSUE THREAD

**Issue by jaromtia** [kamranahmedse/developer-roadmap#7432]
### What Roadmap is this project for?

Cyber Security Expert

### Project Difficulty

Beginner

## What is this project about?

Build a command-line tool to evaluate the security of user passwords. In this project you will create a simple tool that analyzes the strength of a password based on multiple factors

## Skills this Project Covers

This project will help you gain practical experience in encryption, hashing techniques, and password security.

## Requirements

The application should accept a password as an argument and return a security score based on factors such as:

- Length of the password.
- Use of special characters, numbers, and mixed case.
- Detection of dictionary words or common password patterns (e.g., "password123").

- Example output:

```
- Password: P@ssw0rd2024
- Strength: Weak
- Reason: Contains common patterns, too short.
```
You should write the tool in a language of your choice and avoid using external libraries or frameworks that do the password checking for you.

Handle errors such as missing input or invalid characters gracefully.
---
Advanced Version

- Add support for checking passwords against a local or online breach database (e.g., using the HaveIBeenPwned API).
- Include features for generating secure passwords based on user preferences (e.g., length, inclusion of special characters).

**Comment by VaibhavVermaa16** [comment]
Hello @jaromtia , I would like to work on this tool please assign it to me.

**Comment by dansholds** [comment]
> Hello @jaromtia , I would like to work on this tool please assign it to me.

Please understand the context of issues before commenting on them.

@jaromtia This is a good project however _creating_ applications does not fall under the Cyber Security roadmap.
