### ISSUE TITLE
Translation to other languages

### ISSUE THREAD

**Issue by lucaschain** [kamranahmedse/developer-roadmap#744]
Hello, I love this repository and I recommend it to a lot of people, mainly beginners. Some of them can't read in english and it's very frustrating for me being unable to provide this quality of content for them in our native language (PT-br).

My question is: how can I contribute with this repository with translations? Is there a official way to do that? Or may I fork the project (leaving the canonical references) and just go on?

Sorry if this was answered here before or if it's present in any docs, I've searched for it and found nothing

Thank you anyway for this initiative and have a great day

**Comment by ahmedsserag** [comment]
Hey @lucaschain , @kamranahmedse 
I'm an Egyptian Web Developer. and this repository really helped me, it is very similar to my plan about develop my web programming skills.
I'm very excited to help you to translation this repository to my first language "Arabic". I'm sure this will help many beginners from the Arab World.
email: ahmedserag400@gmail.com

**Comment by joaogutierrre** [comment]
Hello everybody @lucaschain 
I'm pleased to see Brazilian developers around this hub. This repo is realy worth translating to PT-BR. If you're planning on translating this by yourself, I would love to volunteer and help in this process. You can get in touch with me on gutierrejoao@gmail.com or you can send me a message on my linkedin profile indexed on the github profile. This is a great initiative! Let's do it!

**Comment by wellingtonmota13** [comment]
I would love to help translate this content as well... @joaogutierrre @lucaschain 
Let's get in touch and make this happen

**Comment by kamranahmedse** [comment]
Thanks guys, we [already have translations for most of the languages](https://github.com/kamranahmedse/developer-roadmap/tree/master/translations), feel free to report if you find any discrepancies in the translation. 

* @ahmedsserag [Arabic translation is here](https://github.com/kamranahmedse/developer-roadmap/tree/master/translations/arabic)
* @lucaschain @joaogutierrre [Portuguese](https://github.com/kamranahmedse/developer-roadmap/tree/master/translations/portuguese)
