### ISSUE TITLE
Streak count is not working well

### ISSUE THREAD

**Issue by tsukitaro** [kamranahmedse/developer-roadmap#7444]
### What is the URL where the issue is happening

https://roadmap.sh

### What browsers are you seeing the problem on?

Microsoft Edge

### Describe the Bug

the days count is not working well, i had ten days and I login yesterday and stay some time, update some proccess but today I wake up with the streak broke 

![image](https://github.com/user-attachments/assets/af498ead-b71f-4026-8a9e-0c414f11a154)

Note: as a idea, maybe is better improve the description 
![image](https://github.com/user-attachments/assets/a30a1913-dd85-4a4d-8ff6-00f9d4e1ec4e)
there is not some description that tell us how to work these feature 

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by Malay207** [comment]
I would love to contribute to this issue for Hacktoberfest! Could you please assign it to me?

**Comment by dansholds** [comment]
Given the current leaderboard I would not say this is a bug but rather an unlucky situation for you.

https://roadmap.sh/leaderboard

We can still have a look to see if it was a systematic issue but chances are that you unintentionally skipped a day (especially as your screenshot shows you to be on day 2 not day 1 i.e. it didn't "break" yesterday)
