### ISSUE TITLE
Suggestion: add Scss in React RoadMap

### ISSUE THREAD

**Issue by anay-208** [kamranahmedse/developer-roadmap#7453]
### Roadmap URL

https://roadmap.sh/react

### Suggestions

In the node of writing CSS, [sass](https://sass-lang.com/) is also a good alternative.

I recommend adding that, as I realised I'd have saved so much lines of code if I use it!

**Comment by anay-208** [comment]
I also wanted hackertobefest contribution, so I'll create a pr for it

**Comment by anay-208** [comment]
Just to confirm, Can I create a PR for it, because of the fact that there is a specific option for "community roadmaps"

**Comment by dansholds** [comment]
It's a little out of scope for the React roadmap, it exists in the FE one.
