### ISSUE TITLE
Cyber-Security/Router wrong content

### ISSUE THREAD

**Issue by krankkkk** [kamranahmedse/developer-roadmap#7460]
### Detailed Description

The content for `Router` seems to be a copy&paste from S3. 

## Content in Question:

>Amazon Simple Storage Service (S3) is a scalable, object-based cloud storage service provided by AWS. It allows users to store and retrieve large amounts of data, such as files, backups, or media content, with high durability and availability. S3 is designed for flexibility, enabling users to access data from anywhere via the internet while offering security features like encryption and access controls. It is widely used for data storage, content distribution, disaster recovery, and big data analytics, providing cost-effective, scalable storage for a variety of applications.

**Comment by kabeer05** [comment]
Can I create a PR for this?

**Comment by offensive-vk** [comment]
Have a look at this: https://github.com/kamranahmedse/developer-roadmap/blob/master/contributing.md#hacktoberfest-contributions

**Comment by kabeer05** [comment]
I see but its not just a single link modification as mentioned, its the whole content being updated or so I thought.
