### ISSUE TITLE
A tag for books

### ISSUE THREAD

**Issue by Jvfzago** [kamranahmedse/developer-roadmap#7466]
### Feature Description

Some roadmaps have links for amazon books tagged as article. It would be useful to have a tag for books. Since usually an article is just some pages wide, a book is very large resource and often is paid, not bad, but different from an article.

**Comment by swaparup36** [comment]
Hello, @Jvfzago Please assign me this issue.

**Comment by dansholds** [comment]
This is not a priority item right now

**Comment by Kerrick** [comment]
Would you accept a PR for this one? I'd be willing to implement, but only if the PR has a chance of being merged.
