### ISSUE TITLE
simple to-do list app

### ISSUE THREAD

**Issue by Abdullahi-abdiaziz** [kamranahmedse/developer-roadmap#7470]
### What Roadmap is this project for?

React Roadmap

### Project Difficulty

Beginner

### Add Project Details

You are required to build  a basic to-do list application where users can add, mark as complete, and delete tasks.

### Requirements:

1.**Task Input:**

- Create a form with an input field and a button.

- When the user types a task in the input field and clicks the button, the task should be added to the to-do list.

**_Hint_**: Use the `useState` hook to store the text from the input field. When the user clicks the "Add" button, update the list of tasks in your state.

2. **Displaying Tasks:** 

- Display the list of tasks added by the user below the input form.
- Each task should have a checkbox next to it to mark it as completed.

**_Hint_**: Use the `.map()` method to loop through your list of tasks stored in state and return a `JSX `element (e.g., a `<li> `or `<div>`) for each task.

3. **Mark Task as Completed**:

- When the user checks the checkbox next to a task, 
- the task should visually update (e.g., be crossed out or change color) to show that it’s completed.

**_Hint_**: Each task can have a completed property in your state (either true or false). Use conditional rendering (ternary operator) in your `JSX` to apply a different style (like a line-through or a class) based on this value.

5. **Deleting Tasks:**

- Add a button next to each task that allows the user to delete the task from the list.

**_Hint_**: Use the `filter()` method on the list of tasks in state to return a new array without the task that was deleted. Then, update the state with this new array.

 ### Bonus Features (Optional):

1. **Persist Data:** Store the tasks in `localStorage` so that they remain even if the user refreshes the page.

**_Hint_**: Use `localStorage.setItem` to save the tasks and `localStorage.getItem` to load them when the app starts. You can manage this with the `useEffect` hook in React to run on the first render and when the list of tasks changes.

2. **Task Filtering**: Add a feature to filter tasks by "All," "Completed," or "Incomplete."

_**Hint**_: Create buttons or a dropdown to let the user select "All," "Completed," or "Incomplete." Use a condition inside .map() to filter tasks based on the selected filter before rendering.

**Comment by dansholds** [comment]
This project already exists and can be given the react tag if needed.
