### ISSUE TITLE
Threat Modelling and GRC

### ISSUE THREAD

**Issue by grubbyone** [kamranahmedse/developer-roadmap#7478]
### Roadmap URL

https://roadmap.sh/cyber-security

### Suggestions

Just wondering for the Cyber Security skills roadmap if Governance Risk and Compliance topics should appear. Such as performing risk assessments, creating policies and tracking compliance to standards should feature. Lastly linked to this Threat Modelling as a skill and process too?

**Comment by dansholds** [comment]
IMO that is the responsibility of the leadership team rather than the operator themselves.
