### ISSUE TITLE
Typo in Libr(~a~)eOffice suite name.

### ISSUE THREAD

**Issue by bartgalicki** [kamranahmedse/developer-roadmap#7481]
### What is the URL where the issue is happening

https://roadmap.sh/cyber-security

### What browsers are you seeing the problem on?

Firefox, Chrome, Safari, Microsoft Edge

### Describe the Bug

![image](https://github.com/user-attachments/assets/f362d7b4-bff0-46ca-a2e7-d4e530e647c2)

### Participation

- [X] I am willing to submit a pull request for this issue.

**Comment by dansholds** [comment]
No?

https://www.libreoffice.org/
