### ISSUE TITLE
Add Functional Languages to back-end.

### ISSUE THREAD

**Issue by rpz-harode** [kamranahmedse/developer-roadmap#75]
Functional languages are designed for building scalable and maintable application.
Functional languages should be mentioned and and then classified into 4 major languages **Elixir , Scala , Clojure , haskell .**

**Comment by kamranahmedse** [comment]
They fall into different paradigm and I wasn't focusing on them for now. I may update it later on to add those but I think it is fine for now.

**Comment by rpz-harode** [comment]
But this roadmap will never be complete without the functional language. Functional languages might fall into different paradigm but this is really important for web-development.
