### ISSUE TITLE
Design Patterns with C# language

### ISSUE THREAD

**Issue by JessicaNathany** [kamranahmedse/developer-roadmap#7511]
### What Roadmap is this project for?

Backend roadmap

### Project Intermediate Advanced

Beginner

### Add Project Details

Project ideas to train programming

https://github.com/cafedebug/lista-apis-dotnet-colaborativa

**Comment by dansholds** [comment]
Hey @JessicaNathany thanks for the suggestion but we only take content in the English language, as per our contribution docs.

**Comment by JessicaNathany** [comment]
Oh yeh, sorry. I'll translate then content for you


Atenciosamente





Em qui., 17 de out. de 2024 às 09:28, dsh ***@***.***>
escreveu:
