### ISSUE TITLE
Day/Night Mode Toggle

### ISSUE THREAD

**Issue by VK-1662004** [kamranahmedse/developer-roadmap#7514]
### Feature Description

Hi! I noticed that the site currently doesn't offer a day/night mode toggle. It would be great to add this feature to improve accessibility and user experience, allowing users to switch between light and dark themes. I'd be happy to contribute by implementing it using CSS and JavaScript. Let me assign this task!

Thanks!

**Comment by dansholds** [comment]
This has been requested a few times already (check the issues, both open and closed before submitting one) and it's not a priority for us right now but has been added to our backlog.
