### ISSUE TITLE
Suggestions: Add topic 'pipelines' into Computer Science Roadmap under 'processes and threads' and change the topic name `processes and threads` to `operating systems`

### ISSUE THREAD

**Issue by Debajyati** [kamranahmedse/developer-roadmap#7515]
# Roadmap URL

https://roadmap.sh/computer-science

# Suggestions

## Pipelines
Pipelining is one of the most crucial concepts of operating systems. It must be a part of the section `processes and threads`. 

[Pipeline](https://en.wikipedia.org/wiki/Pipeline_(Unix)) is a technique used to allow multiple processes or threads to work on separate stages of a computation [concurrently](https://en.wikipedia.org/wiki/Concurrency_(computer_science)).

I know [roadmap.sh](https://roadmap.sh) is not the place for dumping as many as topics in a roadmap, and I think learning pipelines is a must for someone aspiring to be proficient in computer science. So this is why I think it must be there.

If one is a seasoned node.js developer then he/she is largely familiar with streams and have used the `stream.pipeline` method many times. The person is applying the concept of pipelines knowing or unknowingly. But presence of knowledge is always an advantage. 

### Relevant Free Resources to learn Pipelines
[GeeksforGeeks Article on piping in node.js](https://www.geeksforgeeks.org/what-is-piping-in-node-js/)
[Medium Article discussing pipes as a way for IPC in C language](https://medium.com/@show981111/what-is-pipe-in-os-424cfc65532f)
[Medium Article on using Pipelines in Unix-like Systems](https://medium.com/@omimouni33/pipex-the-42-project-understanding-pipelines-in-c-71984b3f2103#:~:text=Pipelines%20serve%20as%20a%20cornerstone,become%20the%20input%20of%20another.)
[Communicating between processes (using pipes) in C (YT video)](https://youtu.be/Mqb2dVRe0uo?si=WUbRI8YPyEBTxyF0)

## Extra Suggestions
Also I think that the name of the section/topic `processes and threads` should be `operating systems` NOT `processes and threads`.
It includes semaphores, mutexes and memory management which are outside the scope of just processes and threads. They are part of the greater area of Computer Science called `Operating Systems`.

**Comment by dansholds** [comment]
We will take this into consideration.
