### ISSUE TITLE
Garbage Collector for Python

### ISSUE THREAD

**Issue by anthonyleier** [kamranahmedse/developer-roadmap#7517]
### Roadmap URL

https://roadmap.sh/python

### Suggestions

I think topics about Garbage Collector are very important to becoming a Python developer. Topics about heap, stack, immutable and mutable objects, gc module, reference counting, cProfiling and memory_profiler.

**Comment by dansholds** [comment]
<img width="335" alt="Screenshot 2024-10-18 at 11 25 04" src="https://github.com/user-attachments/assets/d00b2ae5-9920-472f-9b0f-1ad47c3dab18">

FYI we do have a subtopic on Heaps, Stacks and Queues

**Comment by anthonyleier** [comment]
Yes, but not in the context of memory allocation. My suggestion is on topics related to memory management.

Something like this:

![image](https://github.com/user-attachments/assets/e400a09f-08bf-49f7-97cf-23a0ee816e31)

https://medium.com/@usmananwaar_de/memory-management-in-python-concept-of-heap-stack-garbage-collector-reference-counter-gil-4f133171db4

**Comment by dansholds** [comment]
Sure, I'll add it to the backlog.

**Comment by dansholds** [comment]
This will be tackled in the next iteration of the roadmap.
