### ISSUE TITLE
Astro as SSR Framework for Angular

### ISSUE THREAD

**Issue by WanielDeiss** [kamranahmedse/developer-roadmap#7522]
### What Roadmap is this project for?

Frontend Roadmap

### Project Difficulty

Advanced

### Add Project Details

The SSR > Angular branch is unfortunately empty; here, [Analog](https://analogjs.org/) is the corresponding framework. Theoretically, [NestJS](https://nestjs.com/) could also be used, but it offers more and is more of a complete backend.

**Comment by dansholds** [comment]
All topics on the frontend are populated with text and links so I'm not sure what you're saying here?

You've also submitted this issue as a project request so please refer to the contribution guidelines - https://github.com/kamranahmedse/developer-roadmap/blob/master/contributing.md
