### ISSUE TITLE
Card not updating on github profile readme

### ISSUE THREAD

**Issue by studentiyot** [kamranahmedse/developer-roadmap#7537]
### What is the URL where the issue is happening

https://roadmap.sh/card/wide/665f7a0cb998f3b3c7a9543f?variant=light&roadmaps=frontend

### What browsers are you seeing the problem on?

Firefox, Chrome, Safari

### Describe the Bug

(This is reopening #5007)

The main problem is that the API used in the GitHub profile does not update: `https://roadmap.sh/card/wide/665f7a0cb998f3b3c7a9543f?variant=light&roadmaps=frontend.` The roadmap.sh dashboard updates just fine. 

Unlike the dashboard—after updating the roadmap—the card widget can be sketchy about updating on `https://roadmap.sh/account/road-card.` The light/dark and tall/wide settings are not sticky (unclear if it's meant to be?) The progress here will sometimes update, but often not. But I'm most concerned about the badge on GitHub. My example and screen snapz don't reflect my actual progress as I'm less likely to visit and update when I can't get the embed to function. This is my second attempt to get this operation to work.

In addition to hard refreshes in all browsers, I've attempted the techniques given in #5007, specifically regarding cache (with my user info):
> You can add `https://api.roadmap.sh/v1-badge/wide/64b17cfa5f038d81eeb3ec57?variant=dark&t=1704802165428`, it'll not hit the cache.

[GitHub profile page](https://github.com/studentiyot/studentiyot)

### Dashboard
<img width="832" alt="Screenshot 2024-10-19 at 5 57 35 PM" src="https://github.com/user-attachments/assets/9a111b11-7492-4223-9c56-df6d028491bf">

### GitHub Profile
<img width="560" alt="Screenshot 2024-10-19 at 6 04 34 PM" src="https://github.com/user-attachments/assets/62a0f297-5577-4df5-a73c-8f1cef118ec6">

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by dansholds** [comment]
@arikchakma fyi

**Comment by arikchakma** [comment]
We are aware of this issue, GitHub caches the image response that's why.

**Comment by studentiyot** [comment]
> We are aware of this issue, GitHub caches the image response that's why.

Thank you for the reply. Can you provide a little more color? Does this mean forever caching? I don't understand. I've gone months without the badge updating. Does this mean the badge is functionally useless on GitHub? Is there documentation so that I can understand better?

I apologize; my knowledge is limited, so I can't inquire more expressively.

**Comment by arikchakma** [comment]
> > We are aware of this issue, GitHub caches the image response that's why.
> 
> Thank you for the reply. Can you provide a little more color? Does this mean forever caching? I don't understand. I've gone months without the badge updating. Does this mean the badge is functionally useless on GitHub? Is there documentation so that I can understand better?
> 
> I apologize; my knowledge is limited, so I can't inquire more expressively.

Can you please elaborate on what you mean by color?

I can give you an idea of bypassing caching. I don't know if there are any simplified ways. So what you can do is you can prepare a CRON [GitHub Actions](https://docs.github.com/en/actions), to append a unique string (`Date.now()`) as a query param in the link. It will invalidate the cache as GitHub treats that as a new image.

I hope this will help. Let me know if you need any other help.

**Comment by studentiyot** [comment]
Thank you!

I spent a good chunk of yesterday working with ChatGPT to prepare a CRON in a YAML file, Action. It ultimately ended up in the same place (as just loading the README.md). But I'll take your query param idea and run with it—see if "we" can tweak it to update.

> Can you please elaborate on what you mean by color?
Simply elaborating, as you have. It would be super helpful to have documentation. From the feedback you've given, my searches are yielding broader results—which may prove fruitful. At least understanding the source of the issue and that it isn't simple makes me feel less dumb; less crazy. 🤪

**Comment by arikchakma** [comment]
Sure, we will keep that in mind. Thank you for the feedback.

**Comment by pratil** [comment]
I have another image that gets refreshed suitably, but only the roadmap.sh one is not updating for now have updated it with a dummy query param, but I wanted to know why it is working for this link: https://api.daily.dev/devcards/v2/h6eKSxEhDIWkwVZvOK49N.png?type=wide&r=eoh
