### ISSUE TITLE
Adding Flutter based mobile automation tools

### ISSUE THREAD

**Issue by MrRahulR** [kamranahmedse/developer-roadmap#7540]
### Detailed Description

Flutter mobile app also supports [Maestro](https://maestro.mobile.dev/) and [Patrol](https://patrol.leancode.co/) as the automation tools for Flutter based apps, which can be also added for the Mobile Automation tools section.

**Comment by dansholds** [comment]
Theres no need to create new nodes for these two tools as they can be added as links to the relvant testing topic i.e. unit testing, widget testing etc.
