### ISSUE TITLE
Issues with roadmap identification

### ISSUE THREAD

**Issue by WJNX02** [kamranahmedse/developer-roadmap#7556]
### Feature Description

Hello,

My suggestion is some sort of legend for the roadmap, as i shared it with my boss and he did not seem to understand the different colors,

For example. He thought that the uncrossed items were done and the crossed items had to be done. And not the other way around.

Another solution might be instead of crossing the 'done' items, instead make them green or something like that. Or add a check after the crossed line.

**Comment by dansholds** [comment]
We have a legend on some roadmaps for showing what the purple and green ticks mean so this seems like a valid request. I'll get back to you on this!

**Comment by WJNX02** [comment]
Amazing, i'm talking about the Cybersecurity one.

**Comment by dansholds** [comment]
Added this to our internal roadmap.
