### ISSUE TITLE
Enhance: Content/Topic: Date Modified (Text), Date Last Accessed (Link)

### ISSUE THREAD

**Issue by iPoetDev** [kamranahmedse/developer-roadmap#7565]
### Feature Description

Content Editing: Recency, Accuracy and Relevancy

- Adding date last modified for Content / Text Description visibly to topic node's content
- Adding Resource Link date last accessed, next to the link.

- Adding date `last <modified|accessed>` enhances trust (or lowers it if not recent), by giving the user the option to judge recency, accuracy, and relevancy of the content in a topic/sub-topic in a pop out.

- It can be light grey.
- It can be taken from SEO metadata or CI build date of latest commit.
- It could simulate more content updates if content/topic looks out of date.

### Further Development

- Could seed versioning and version history.

**Comment by dansholds** [comment]
While the idea sounds good, it also sounds like a footgun for such a small team.

Although I do like the "It could simulate (reading as stimulate) more content updates if content/topic looks out of date."

**Comment by iPoetDev** [comment]
Okay, understood. I am just surfacing some challenges in “complete roadmap” content upgrading and proofing, and the first that I came across was time / ageing of content in fast moving domains like AI, as a feature enhancement

By the way, you have a last modified date value, buried in the markdown file, in the folder `src/data/(Roadmap)/<roadmap>.md`

**Comment by brambhattabhishek** [comment]
Hi! I’d like to work on this issue. Could you please assign it to me?

**Comment by dansholds** [comment]
> Hi! I’d like to work on this issue. Could you please assign it to me?
> 
> 

This is not something that can be developed by the community. Community contribute is typically via adding content and links to topics, please see the contribution guides.

**Comment by dansholds** [comment]
> Okay, understood. I am just surfacing some challenges in “complete roadmap” content upgrading and proofing, and the first that I came across was time / ageing of content in fast moving domains like AI, as a feature enhancement
> 
> By the way, you have a last modified date value, buried in the markdown file, in the folder `src/data/(Roadmap)/<roadmap>.md`

True but this is not accurate as you can see the data on the prompt-engineering roadmap is 2023
