### ISSUE TITLE
Rename Go Roadmap to Go

### ISSUE THREAD

**Issue by ayushpandey8439** [kamranahmedse/developer-roadmap#7566]
### Detailed Description

In the road-map exploration, every other road-map except Go is labelled with just the name of the tech stack or the language. Can Go road-map be renamed to Go?

**Comment by dansholds** [comment]
![Screenshot 2024-10-24 at 11 57 18](https://github.com/user-attachments/assets/162f1041-374b-47b9-8f9d-a1ef7b303e37)

It is?

**Comment by ayushpandey8439** [comment]
You're right. After logging in, it shows up as Go. But without login, it is displayed as Go Roadmap. 

<img width="872" alt="Screenshot 2024-10-24 at 13 28 43" src="https://github.com/user-attachments/assets/86897662-8968-4deb-937f-89afb04ff49d">

**Comment by arikchakma** [comment]
It's on purpose due to SEO issues. I appreciate your concern.
