### ISSUE TITLE
Project for python

### ISSUE THREAD

**Issue by RijanDhakal** [kamranahmedse/developer-roadmap#7568]
### Feature Description

Adding a "Jarvis" Type Voice assistant in the project will be benificial also to make it harder , we can make "JARVIS" / desktop assistant control our home aapliences through integration with aurdino

**Comment by dansholds** [comment]
This is a little out of scope, especially as it requires the user to own an arduino or pi

**Comment by RijanDhakal** [comment]
it will give practical knowledge .
