### ISSUE TITLE
Submit the Git URL for project submission

### ISSUE THREAD

**Issue by raza001** [kamranahmedse/developer-roadmap#7569]
### What is the URL where the issue is happening

https://roadmap.sh/projects/server-stats

### What browsers are you seeing the problem on?

Other

### Describe the Bug

i can't submit the solution
https://github.com/raza001/Server-pro
but my repo is public and open for all 

### Participation

- [x] I am willing to submit a pull request for this issue.

**Comment by brambhattabhishek** [comment]
Hi! I’d like to work on this issue. Could you please assign it to me?

**Comment by dansholds** [comment]
<img width="534" alt="Screenshot 2024-10-25 at 08 15 36" src="https://github.com/user-attachments/assets/39869f8b-20fc-403f-b920-ad4fbf93db1a">

Interesting, I was able to submit yours successfully!

Can you check the console log in the browser to see if anything is stopping you?

**Comment by dansholds** [comment]
> Hi! I’d like to work on this issue. Could you please assign it to me?
> 
> 

This is not something that can be developed by the community. Community contribute is typically via adding content and links to topics, please see the contribution guides.

**Comment by dansholds** [comment]
Closing due to no response from auther, adding the project worked for so theres no signs of a programmatic issue.

**Comment by GRACENOBLE** [comment]
![Screenshot from 2024-11-03 07-58-41](https://github.com/user-attachments/assets/c476f77b-6f6d-4a14-801e-34fc2028786c)

**Comment by GRACENOBLE** [comment]
![image](https://github.com/user-attachments/assets/a066f487-81cf-4ceb-a5da-985e7713acbc)
![image](https://github.com/user-attachments/assets/eeb03f7b-9359-4f47-840b-8cc8f62e3b9e)
I cannot submit mine
