### ISSUE TITLE
Weather App

### ISSUE THREAD

**Issue by RichardLechko** [kamranahmedse/developer-roadmap#7572]
### What Roadmap is this project for?

Frontend Roadmap

### Project Difficulty

Intermediate

### Add Project Details

I think a really cool project to add would be a weather app! Get an API Key from OpenWeatherMap, it is free and easy to use.

One of the already existing intermediate projects, "GitHub Random Repository", focuses on API Integration, but I think there should be more projects on using API's. A weather app is super basic and can definitely help strengthen peoples skills.

**Comment by fellalli** [comment]
Something like https://github.com/kamranahmedse/developer-roadmap/pull/7509/commits/1e07a489e841945b6f20e6df66cce6eeef5cfd3a?

**Comment by dansholds** [comment]
@RichardLechko Thanks for submitting this but this already exists in a PR and is an active project in the backend section 🤙🏻
