### ISSUE TITLE
Expense Tracker

### ISSUE THREAD

**Issue by Adyanth-212** [kamranahmedse/developer-roadmap#7577]
### What Roadmap is this project for?

Python Roadmap

### Project Difficulty

Beginner

### Add Project Details

You are required to build a simple expense tracker
https://github.com/Adyanth-212/Small-Beginner-Projects.git

**Comment by brambhattabhishek** [comment]
Hi! I’d like to work on this issue. Could you please assign it to me?

**Comment by dansholds** [comment]
> Hi! I’d like to work on this issue. Could you please assign it to me?
> 
> 

This is not something that can be developed by the community. Community contribute is typically via adding content and links to topics, please see the contribution guides.

**Comment by dansholds** [comment]
@Adyanth-212 This already exists - https://roadmap.sh/projects/expense-tracker
