### ISSUE TITLE
Software Architect Roadmap - Remove Trello from Tools menu

### ISSUE THREAD

**Issue by salmantec** [kamranahmedse/developer-roadmap#7597]
### What is the URL where the issue is happening

https://roadmap.sh/software-architect

### What browsers are you seeing the problem on?

Firefox, Chrome, Safari

### Steps to reproduce:

1. Go to https://roadmap.sh/software-architect roadmap
2. Scroll down to `Tools` menu (next to `Patterns & Design Principles`)
3. You could see both `Trello` and `Atlassian Tools`
4. As `Trello` is one of the products of **Atlassian** company. Since we already mentioned `Atlassian Tools`, we can remove `Trello`.

<img width="1443" alt="Screenshot 2024-10-26 at 6 55 43 PM" src="https://github.com/user-attachments/assets/08941cc3-3e44-491d-9302-93ab971343c5">

![Screenshot 2024-10-26 at 7 21 47 PM](https://github.com/user-attachments/assets/6df32720-c383-4073-baf2-caf2a78a4262)

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by An525ish** [comment]
hey I'd like contribute to this issue @salmantec

**Comment by salmantec** [comment]
> hey I'd like contribute to this issue @salmantec

Yeah, please go ahead @An525ish after getting confirmation from @dansholds .

**Comment by An525ish** [comment]
Hey @salmantec, could you please guide me on how to make changes here? The JSON files are automatically generated, and the Markdown files only contain a description of Trello. How can I remove that specific node? Thank you!

**Comment by arikchakma** [comment]
We will note this and update the roadmap accordingly in the next iteration. Thank you for opening the issue.
