### ISSUE TITLE
Lets make one for Data Science! 

### ISSUE THREAD

**Issue by DataFighter** [kamranahmedse/developer-roadmap#76]
I feel like this is relevant enough to be its own thing. To some extent, it could be a function of backend engineering but a lot of data science does involve plotting as well.

**Comment by ricalanis** [comment]
I'm in!

**Comment by kamranahmedse** [comment]
Feel free to create a PR if anyone is up for it. But the repository focuses on "web developer", so closing it for being irrelevant.

Thanks though.
