### ISSUE TITLE
roadmap/cyber-security: SSL vs TLS

### ISSUE THREAD

**Issue by bartgalicki** [kamranahmedse/developer-roadmap#7601]
### Roadmap URL

https://roadmap.sh/cyber-security

### Suggestions

There are three versions of the document and 2 of them actually describe SSL and TLS, but the last one is about SSO.
The last one (wrong) is published currently
![image](https://github.com/user-attachments/assets/64e7a2d5-a394-49a5-ba50-fed01b8f196b)

Do this roadmap need two separate sections dedicated for TLS/SSL? 

<img width="351" alt="image" src="https://github.com/user-attachments/assets/a1a9fdc6-447d-464b-9207-5b7aebe19c0d">

<img width="264" alt="image" src="https://github.com/user-attachments/assets/cc9c415d-002e-405e-a931-0799115b611b">

**Comment by dansholds** [comment]
Hey @bartgalicki I have just merged a change to update the SSO copy from the SSL/TLS file, not sure why it was that way!

As for your question around having multiple SSL related topics, the intent is that they will show SSL in different contexts, but this might not always be the case, in which case feel free to submit a PR updating the copy to reflect its parent topic!

🤙🏻
