### ISSUE TITLE
The created custom roadmap is not displayed in the list of custom roadmaps

### ISSUE THREAD

**Issue by Steindvart** [kamranahmedse/developer-roadmap#7604]
### What is the URL where the issue is happening

https://roadmap.sh/r/c-extended

### What browsers are you seeing the problem on?

Chrome

### Describe the Bug

I have started working on my own version of the official c++ roadmap. The part is already ready, and I have posted it in the public domain: https://roadmap.sh/r/c-extended.

It is available via the link, but for some reason, after a long period of time (1-2 weeks), it does not appear in the list of user roadmaps. 

![image](https://github.com/user-attachments/assets/287cece3-3167-4249-bc3d-5a9f051e0156)

Perhaps this is not a mistake and some kind of separate agreement is needed to get into this list.

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by shivam-bhushan** [comment]
It is working for me 
![1c60123adb535120f45651ae47ed76fe](https://github.com/user-attachments/assets/4cbd1938-bfaf-463c-af78-9f4556df8b39)

**Comment by An525ish** [comment]
I'd like to work on this

**Comment by arikchakma** [comment]
Not all roadmaps are visible in the showcase, we have to approve them.

Thank you for opening the issue.

**Comment by Steindvart** [comment]
@An525ish 

> I'd like to work on this

I am currently finalizing the map structure. In general, I already have it ready. Just need to draw it all beautifully in the form of blocks.

Will definitely need help filling out the cards. I will be glad for any help with this as soon as I finish with the structure! :)

**Comment by Steindvart** [comment]
@arikchakma 

> Not all roadmaps are visible in the showcase, we have to approve them.
> 
> Thank you for opening the issue.

I would be very grateful if this my roadmap could be included in general list of community roadmaps. 

It seems to me that it is very good and useful both for studying C++ in general and in preparing for interviews - in order to understand the landscape of your knowledge of C++.

I admit, I hope that this map (in a complete form) will replace the current official C++ roadmap. Since the current official C++ roadmap, in my opinion, has a number of problems that I have tried to close in my expanded and revised version of the roadmap.

**Comment by arikchakma** [comment]
> I would be very grateful if this my roadmap could be included in general list of community roadmaps.

Again we will discuss it internally, and let you know. You will see it on the public page if we approve it. Thank you for your understanding.

**Comment by arikchakma** [comment]
@Steindvart 

You should open an issue with the roadmap link you would like us to include on that page. We will review your roadmap and include it there if it makes sense.

In the case of official roadmaps such as the C++ roadmap, you can open an issue with improvements or your custom roadmap link so that we can improve the official roadmap with your feedback and help others as well.

Thank you
