### ISSUE TITLE
improving official roadmap that save personally for that user only

### ISSUE THREAD

**Issue by Akkiraj1234** [kamranahmedse/developer-roadmap#7606]
### Feature Description

A way to add more topics in official roadmap , that save personally for each user only the changes for example i wanna add some more topic in python that i have learned to show on the raodmap but i cant.                                                                by adding that we can improve offical roadmap and add more thing not be able to delete offical roadmap topics but can be able to add more thing we learned on the topic.

**Comment by dansholds** [comment]
We are bringing back the ability for users to fork official roadmaps and edit them for personal use, which will satisfy this request 👍🏻

**Comment by Deshdeepak1** [comment]
till when can we expect this?

**Comment by tkeyes25** [comment]
Is there an update on this? This feature would be a game changer ...

**Comment by dansholds** [comment]
> Is there an update on this? This feature would be a game changer ... @dansholds 

I don't work here brother sorry

**Comment by program-om** [comment]
I was very surprised that this feature does not already exist! I hope it will come out soon
