### ISSUE TITLE
Doc Clarity (Linux): Proc Priorities Under Process Management

### ISSUE THREAD

**Issue by sukalaper** [kamranahmedse/developer-roadmap#7608]
### Feature Description
![Screenshot_2024_1027_231858](https://github.com/user-attachments/assets/028296b4-6348-4c40-8622-b55bde5c0909)

When using the command:

`ps -eo pid,pri,user`

The output may look like this:

```
PID  PRI  USER
 4843  29  u0_a256
21500  29  u0_a256
21548  29  u0_a256
```

This output can be confusing, especially for new users (I), as it only displays the PID, priority, and user without information about the running programs.

Therefore, I propose adding the `comm` column at the end of the command, so that it becomes:

`ps -eo pid,pri,user,comm`

With the expected output as follows:

```
PID  PRI  USER      COMMAND
 5303  29  u0_a256  ps
21500  29  u0_a256  com.termux
21548  29  u0_a256  /data/data/com.termux/files/usr/bin/bash
```

With this addition, users, especially beginners (I), will be able to understand more easily which programs are running based on the displayed PIDs, thus enhancing the clarity and usability of this command.

Sorry for the bad english, if I misplaced the labels, please let me know.

**Comment by fellalli** [comment]
Epic! Feel free to open a PR :rocket:

**Comment by ebcq** [comment]
> > Epic! Feel free to open a PR 🚀
> 
> Is it OK to do a pull request for this?

Sure :)
