### ISSUE TITLE
Javascript Roadmap: Merge 'Comparison Operators' and 'Relational Operators'

### ISSUE THREAD

**Issue by sergiocast97** [kamranahmedse/developer-roadmap#7609]
### Roadmap URL

https://roadmap.sh/javascript

### Suggestions

On the Javascript roadmap, there's a topic for 'Relational Operators' and another one for 'Comparison Operators', but it's stated that the names are synonyms - which means either one of them are redundant. Therefore, it might be a good idea to merge both topics, joining the resource links in one list.

**Comment by dansholds** [comment]
PR is in for this, thanks for the request.
