### ISSUE TITLE
Python roadmap - Would be great if we add Poetry and Conda under `Environments` section

### ISSUE THREAD

**Issue by salmantec** [kamranahmedse/developer-roadmap#7612]
### Roadmap URL

https://roadmap.sh/python

### Suggestions

Under `Environments` in **Python** roadmap, IMO, we can add **Poetry** and **Conda** as well. As these two are providing package management and virtual environment supports too.

<img width="1396" alt="Screenshot 2024-10-28 at 11 45 14 AM" src="https://github.com/user-attachments/assets/b7451b59-b63b-4d9a-bfca-298e29be03a4">

### Benefits:
Lets say, for ex, instead of using **venv** for creating virtual environment and using **pip** for package management, Users can try with **Poetry** / **Conda** for both the use cases.

### Links FYR:
[Conda](https://docs.conda.io/projects/conda/en/latest/user-guide/getting-started.html#creating-environments)
[Poetry](https://python-poetry.org/docs/basic-usage/#activating-the-virtual-environment)

**Comment by dansholds** [comment]
Nodes for Poetry and Conda already exist in the package manager section, and the links provided in those topics mention what you've suggested.

Thanks for taking the time though!
