### ISSUE TITLE
Roadmap home screen change - Move PostgreSQL to skill-based section

### ISSUE THREAD

**Issue by salmantec** [kamranahmedse/developer-roadmap#7615]
### Roadmap URL

https://roadmap.sh/

### Suggestions

Currently `PostgreSQL` placed under **Role** based section, but it should actually place under **Skill** based section as it is a skill related DB. And couple of other DB related technologies like **MongoDB** and **Redis** already placed under **Skill-based** section.

![Screenshot 2024-10-28 at 2 52 45 PM](https://github.com/user-attachments/assets/3a3ac2ef-6efc-45cb-92ee-5779b844db25)

**Comment by dansholds** [comment]
Hey @salmantec! I totally get what you mean, and I even just made the changes locally until I realised that this particular roadmap is actually for the _role_ of "Database Administrator" using Postgresql, which means it is in the right area!

**Comment by salmantec** [comment]
> Hey @salmantec! I totally get what you mean, and I even just made the changes locally until I realised that this particular roadmap is actually for the _role_ of "Database Administrator" using Postgresql, which means it is in the right area!

Thanks @dansholds !
