### ISSUE TITLE
Important or recommended references

### ISSUE THREAD

**Issue by diego-gv** [kamranahmedse/developer-roadmap#762]
#### What roadmap is this issue about?

- [ ] Frontend Roadmap
- [ ] Backend Roadmap
- [ ] DevOps Roadmap
- [x] All Roadmaps

#### What is this issue about?

- [ ] Discussion for a pull request I would want to open.
- [ ] Addition of a new item
- [ ] Removal of some existing item
- [ ] Changing in arrangement
- [x] General suggestion
- [x] Sharing an Idea
- [ ] Something else

#### Please acknowledge the below listed

- [x] This is not a duplicate issue. I have searched and there is no existing issue for this.
- [x] I understand that these roadmaps are highly opinionated. The purpose is to not to include everything out there in these roadmaps but to have everything that is most relevant today comparing to the other options listed.
- [x] I have read the [contribution docs](../contributing.md) before opening this issue.

#### Enter the details about the issue here

It would be good to include some important references or links in the roadmaps. A silly example, in the backend roadmap, that there is a link to the Mozilla developer page in the HTML/CSS cards to indicate that it is a good place to get the necessary information.

Some cards seem somewhat ambiguous as to the depth of knowledge indicated.

**Comment by kamranahmedse** [comment]
Roadmaps are being made interactive and resources are being added. You can click through the frontend and backend roadmaps to access the links. Thank you for reporting 🙏
