### ISSUE TITLE
Better course for mathematics for machine learning

### ISSUE THREAD

**Issue by akshathdubey** [kamranahmedse/developer-roadmap#7620]
### Roadmap URL

https://roadmap.sh/ai-data-scientist

### Suggestions

I believe instead of the Imperial College Mathematics course, this deeplearning.ai course would be a better option for learning:
[Mathematics for Machine Learning and Data Science Specialization](https://www.coursera.org/specializations/mathematics-for-machine-learning-and-data-science)

Your feedback would be very appreciated.

**Comment by dansholds** [comment]
The existing course has a huge amount of social proof with the reviews and others items but we will have a look into it.

Thanks for the suggestion!
