### ISSUE TITLE
Deprecated

### ISSUE THREAD

**Issue by YorgiAlejandro** [kamranahmedse/developer-roadmap#7626]
### Roadmap URL

https://roadmap.sh/ios

### Suggestions

As an iOS Developer is not absolutely necessary to learn UIKit, are different roadmaps, and is not necessary Objective-C and need knowledge about appStore.

**Comment by fellalli** [comment]
I think it’s fine to mention Objective-C since it’s still fully supported and not deprecated. The roadmap also explicitly recommends going with Swift.

**Comment by dansholds** [comment]
The point of the roadmaps is to give a guided journey through the generally accepted tools, ideas, and requirements of a language or role, we are not saying UIKit is absolutely required.

@fellalli's points also stand.
