### ISSUE TITLE
Wifi singanal crecker

### ISSUE THREAD

**Issue by Rdxsh** [kamranahmedse/developer-roadmap#7630]
### What is the URL where the issue is happening

Some hack project 

### What browsers are you seeing the problem on?

Firefox, Chrome, Microsoft Edge

### Output from browser console (if any)

[``](

1. > ### **url**

)

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by fellalli** [comment]
Please use templates correctly and provide information

**Comment by dansholds** [comment]
If I could decode this request and assume you're asking us to add a WiFi cracking project, we will not be doing that I'm afraid 😂
