### ISSUE TITLE
React Native: Legacy Native Modules are deprecated

### ISSUE THREAD

**Issue by masoud-msk** [kamranahmedse/developer-roadmap#7635]
### Roadmap URL

https://roadmap.sh/react-native

### Suggestions

With the introduction of the New Architecture, the legacy Native Modules are deprecated. Also related pages in the docs are moved to a legacy section which also changed their URLs; thus the article links in to in the roadmap are now broken.
[![image](https://github.com/user-attachments/assets/3a1d2f06-2895-4b79-916c-498e37547ad8)](https://reactnative.dev/docs/native-platform)

Current roadmap structure:
- Using Native Modules
  - For iOS
  - For Android

Suggested replacement:
- Native Development
  - Android & iOS Modules
  - Cross-Platform Native Modules (C++)
  - Native Components

New node names reflect sections in the updated and current [React Native documentation](https://reactnative.dev/docs/native-platform)
![image](https://github.com/user-attachments/assets/2d704c17-2d9f-4021-ac68-dd960d7a2837)

I proposed changes to this topic [in this PR](https://github.com/kamranahmedse/developer-roadmap/pull/7594).

**Comment by masoud-msk** [comment]
Added more details to the suggestion.
@dansholds @fellalli

**Comment by dansholds** [comment]
This can be tackled when the roadmap is moved over to the new editor.
