### ISSUE TITLE
AR/VR development

### ISSUE THREAD

**Issue by vedpawar2254** [kamranahmedse/developer-roadmap#7641]
### What is the title of the roadmap you are submitting?

AR/VR development

### Roadmap Link

https://roadmap.sh/r/arvr-development-6b9od

**Comment by vedpawar2254** [comment]
Please consider for hactober2024

**Comment by dansholds** [comment]
@vedpawar2254 as per our Contribution Guide, the only items we were accepting for Hacktoberfest was topic links and content.

This roadmap also isn't very thorough so if you improve it (take a look at some of the ones on https://roadmap.sh/community) then we can potentially add it there.
