### ISSUE TITLE
Build your own GIT

### ISSUE THREAD

**Issue by MuhammaduBarry** [kamranahmedse/developer-roadmap#7642]
### What Roadmap is this project for?

Backend Roadmap

### Project Difficulty

Advanced

### Add Project Details

You are required to build your own GIT version control to maintain the state of your projects, it should have most of the core utility functions that git has and many more.

**Comment by MuhammaduBarry** [comment]
just food for thought 🍔, im a beginner btw.

**Comment by dansholds** [comment]
This is quite out of scope for a roadmap project I'm afraid, while the idea is cool, asking people to rebuild git from the ground up is excessive haha
