### ISSUE TITLE
Add C++23 to C++ Roadmap

### ISSUE THREAD

**Issue by fellalli** [kamranahmedse/developer-roadmap#7644]
### Roadmap URL

https://roadmap.sh/cpp

### Suggestions

We need a new node for C++23.

![cpp](https://github.com/user-attachments/assets/67459f20-f0e7-4de5-923d-03918a3f48ef)

**Comment by dansholds** [comment]
I agree, super important:

'[Named universal character escapes](https://en.cppreference.com/w/cpp/language/escape#Named_universal_character_escapes), e.g. "\N{CAT FACE}" for "🐱"'

**Comment by dansholds** [comment]
Added to our internal list of additions.
