### ISSUE TITLE
Projects filters (`Beginner`, `Intermediate`, `Advanced`) are  not working properly, If I go to project details page and come back

### ISSUE THREAD

**Issue by salmantec** [kamranahmedse/developer-roadmap#7647]
### What is the URL where the issue is happening

https://roadmap.sh/backend/projects

### What browsers are you seeing the problem on?

Firefox, Chrome, Safari

### Steps to reproduce the bug:

1. Go to any of the tech stack's projects section. For eg, Python (https://roadmap.sh/backend/projects)
2. It will take you to the project details screen If you select any of the project, after applying `Beginner` filter.
3. You could see `Back to Projects` in top left corner and click it.
4. It will take you back to the projects section without applying that beginner filter.
5. But it should apply that filter as I earlier applied that filter

![Screenshot 2024-10-31 at 10 33 41 PM](https://github.com/user-attachments/assets/f63fb160-accf-4740-bdee-f4fb5dea6fc3)

![Screenshot 2024-10-31 at 10 34 11 PM](https://github.com/user-attachments/assets/4902b0d3-04be-4450-a3f1-a20c3d16189e)

![Screenshot 2024-10-31 at 10 36 16 PM](https://github.com/user-attachments/assets/554a524a-f647-4acf-8be9-a7d37900266a)

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by fellalli** [comment]
I noticed that as well. The issue is that the `Back to Projects` button always redirects to https://roadmap.sh/backend/projects, even when coming from a different roadmap (e.g., https://roadmap.sh/cpp/projects).

@arikchakma, this could be interesting for you :smile:

**Comment by arikchakma** [comment]
I will look for a solution for it but currently, it's intentional.
