### ISSUE TITLE
Polars - Need to include it in Data related roadmaps like Data Analyst

### ISSUE THREAD

**Issue by salmantec** [kamranahmedse/developer-roadmap#7648]
### Roadmap URL

https://roadmap.sh/data-analyst

### Suggestions

- Need to include Polars (https://github.com/pola-rs/polars/) in all Data related roadmaps like Data Analyst and wherever we have Pandas
- As it has fast growing community and competes with Pandas as data manipulation library.

**Comment by dansholds** [comment]
The aim isn't to include every tool within a certain usecase, if we did that, the roadmaps would never end!

**Comment by salmantec** [comment]
> The aim isn't to include every tool within a certain usecase, if we did that, the roadmaps would never end!

Hi @dansholds I agree with your point, but we have to show varieties to users (I believe that's why we have many branches from each nodes in our site - Attached one example (python) screenshot below FYR) and we can include popular ones in our roadmap.sh site. I would suggest to add `Polars` instead of `Dplyr`, which is becoming more popular one.

### Many tools screenshot FYR:

<img width="1152" alt="Screenshot 2024-11-01 at 10 26 50 PM" src="https://github.com/user-attachments/assets/17725c91-e180-437a-a1a3-d7c6354fa525">


### Github comparison b/w `Polars` and `Dplyr`:

<img width="1494" alt="Screenshot 2024-11-01 at 10 18 43 PM" src="https://github.com/user-attachments/assets/61308cd8-836c-4a72-aeca-a964eb5e6708">

<img width="1493" alt="Screenshot 2024-11-01 at 10 19 12 PM" src="https://github.com/user-attachments/assets/85742b40-cffe-4e42-9c56-96da8ec1e958">
