### ISSUE TITLE
Text overlapping issue in Data Analyst screen only in Firefox and Safari browser

### ISSUE THREAD

**Issue by salmantec** [kamranahmedse/developer-roadmap#7658]
### What is the URL where the issue is happening

https://roadmap.sh/data-analyst

### What browsers are you seeing the problem on?

Firefox, Safari

### Steps to reproduce the bug:

1. Go to `Data Analyst` roadmap, scroll down to end of the page
2. You could see text overlapping issue in `Building a portfolio project` section (Attached screenshot FYR).
3. It's happening in Firefox and Safari browsers only (Working properly in Chrome browser).

<img width="1074" alt="Screenshot 2024-11-01 at 10 34 59 PM" src="https://github.com/user-attachments/assets/3b115f35-a5fd-4cbb-aab9-0ec1cd8d549a">

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by srikary12** [comment]
Will fix it

**Comment by dansholds** [comment]
@arikchakma

**Comment by arikchakma** [comment]
Resolved 🚀
