### ISSUE TITLE
Software Architect roadmap - Need to include mobile development related languages

### ISSUE THREAD

**Issue by salmantec** [kamranahmedse/developer-roadmap#7659]
### Roadmap URL

https://roadmap.sh/software-architect

### Suggestions

We have mentioned only `Web` related frameworks like `React, Vue, Angular` in Software Architect roadmap. We should include couple of mobile related framework / languages as well like `React Native, Flutter, Swift`, as we mentioned `Web, Mobile` in the node title

<img width="1051" alt="Screenshot 2024-11-01 at 10 42 14 PM" src="https://github.com/user-attachments/assets/f97f7f4e-be96-4dfa-8853-d3b0418b8f42">

**Comment by dansholds** [comment]
This can be tackled on the next interation of the roadmap
