### ISSUE TITLE
Popup should disappear when moving cursor from that menu title

### ISSUE THREAD

**Issue by salmantec** [kamranahmedse/developer-roadmap#7661]
### What is the URL where the issue is happening

https://roadmap.sh

### What browsers are you seeing the problem on?

Firefox, Chrome, Safari

### Steps to reproduce the bug:

1. Go to roadmap Home Screen (https://roadmap.sh). Use your mouse (cursor) to hover the navbar menu items.
2. Popup is not disappearing if I move the mouse out of the menu item. (Attached screen recording FYR)

https://github.com/user-attachments/assets/feac1448-c1eb-4ba5-9c9c-065a360ce600

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by arikchakma** [comment]
@salmantec It's intentional, and we're aware of it. We are working on a new version and will fix all of these.

I appreciate your concern.

**Comment by salmantec** [comment]
> @salmantec It's intentional, and we're aware of it. We are working on a new version and will fix all of these.
> 
> I appreciate your concern.

Thanks for the update @arikchakma.
