### ISSUE TITLE
Human resource management system

### ISSUE THREAD

**Issue by ibnshehmolo** [kamranahmedse/developer-roadmap#7662]
### What Roadmap is this project for?

front end

### Project Difficulty

Beginner

### Add Project Details

my project should be easy to use and also not complicated

**Comment by fellalli** [comment]
Hi @ibnshehmolo, what are the requirements for the HR management system? Whats the purpose?

**Comment by dansholds** [comment]
This is 100% _not_ a beginner project 😂 

Lets look at adding some more details to this and maybe we can make it work.
