### ISSUE TITLE
Cannot submit Solution URL

### ISSUE THREAD

**Issue by GRACENOBLE** [kamranahmedse/developer-roadmap#7663]
### What is the URL where the issue is happening

https://roadmap.sh/projects/task-tracker

### What browsers are you seeing the problem on?

Firefox, Chrome

### Describe the Bug

In both mozilla and chrome, when i paste my project URL, roadmap.sh cannot seem to find my repository despite it being public and existing

### Output from browser console (if any)

![image](https://github.com/user-attachments/assets/de4cff54-4497-4791-a4e1-d5076da3e05f)

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by arikchakma** [comment]
I have seen your repo, please add the project URL in the `readme` file to submit.

**Comment by GRACENOBLE** [comment]
I have been trying for a while but i have had no success
![image](https://github.com/user-attachments/assets/f6599fd3-1b26-4351-9ef0-fc8b7549c363)
I have used the same format in your solution but with no success still, please help
Still shows this
![image](https://github.com/user-attachments/assets/fe4f357c-68fe-40b7-aa6f-417c6c7a9616)
console
![image](https://github.com/user-attachments/assets/a2ef322d-b9f8-4a07-ac36-f601db53fc60)

**Comment by arikchakma** [comment]
The project URL will be `https://github.com/GRACENOBLE/TaskTracker` without the `.git` extension.

**Comment by GRACENOBLE** [comment]
Success, thanks a bunch💯🙏😭🥲🥳🥳🥳🥳🥳

**Comment by arikchakma** [comment]
Let me know if you need anything else.
