### ISSUE TITLE
Python roadmap - Need to include `Jinja2` template engine

### ISSUE THREAD

**Issue by salmantec** [kamranahmedse/developer-roadmap#7664]
### Roadmap URL

https://roadmap.sh/python

### Suggestions

It would be good if we can add `Jinja2` template engine in **Python** roadmap.

Jinja2 doc url - https://jinja.palletsprojects.com/en/stable/

**Comment by fellalli** [comment]
Where would you like to add it?

**Comment by dansholds** [comment]
PR created
