### ISSUE TITLE
Performance Management System

### ISSUE THREAD

**Issue by chandanr-7** [kamranahmedse/developer-roadmap#7674]
### What Roadmap is this project for?

Backend Roadmap

### Project Difficulty

Advanced

### Add Project Details

Build a Performance management system that can collect and display User's daily work activity from 

Github [ Ex: Number of lines of code commit, quality of code ]
JIRA [ Ex: Story points, Number of Bugs/Tasks, sprint velocity ]

**Comment by dansholds** [comment]
This is very similar to projects we already have such as the "GitHub Tracker"

**Comment by Alroilim9** [comment]
جديد
