### ISSUE TITLE
Typo in React roadmap

### ISSUE THREAD

**Issue by Ankrat** [kamranahmedse/developer-roadmap#7688]
### Detailed Description

[roadmap/react](https://roadmap.sh/react)

Personal recommendation tick is blue. But the _pick one_ state purple:

![Screenshot 2024-11-06 at 10 18 48](https://github.com/user-attachments/assets/a93879ae-c3b9-4e56-a8e9-4edc0208f3b6)

**Comment by fellalli** [comment]
Let’s update the color from blue to purple to keep it consistent with the other roadmaps.

**Comment by brendancjz** [comment]
Hi @fellalli, I would like to help with this issue. As this is my first task, I need the correct access rights. Running `npm run generate-renderer` fails. Any advice on how to move forward?

**Comment by brendancjz** [comment]
Noted! May I ask what's the hexcode for the purple color? :)

**Comment by fellalli** [comment]
The color is `#874efe`. However, I assume that JSON files where colors like this are stored are auto-generated and will likely be overwritten during the build process.

@arikchakma, could you please confirm if that’s correct?

**Comment by brendancjz** [comment]
Hi @fellalli, roger that. I have made the simple fix and created a PR [here](https://github.com/kamranahmedse/developer-roadmap/pull/7699). Let me know if there's any updates needed. Thanks.

**Comment by kamranahmedse** [comment]
Looks good, thanks @fellalli @brendancjz
