### ISSUE TITLE
How to add links to the roadmap?

### ISSUE THREAD

**Issue by tommygebru** [kamranahmedse/developer-roadmap#77]
How to add links to the roadmap? I am trying to recreate your map but links dont seem to work

**Comment by kamranahmedse** [comment]
Hi @tommygebru, I am planning on adding them soon; will put a contribution guide as well once I put some of them. Thank you.

**Comment by tommygebru** [comment]
Very cool I like that idea, I actually want to put the short "roadmap", first image or git, ssh, https.... on my website of resources
