### ISSUE TITLE
Is there a branch that builds?

### ISSUE THREAD

**Issue by rjnls** [kamranahmedse/developer-roadmap#7703]
### What is the URL where the issue is happening

build

### Describe the Bug

main gives: Could not resolve "../../../editor/utils/roadmap-generator" from "src/components/GenerateRoadmap/GenerateRoadmap.tsx"

Do you have a tag or something to show commits that are buildable?

Thx.

### Output from browser console (if any)

can't see any output because it doesn't build.

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by kamranahmedse** [comment]
Hey @rjnls some of the pieces of the project are not opensource so I don't think so.
