### ISSUE TITLE
Inconsistent Tick Colors on ReactJS roadmap

### ISSUE THREAD

**Issue by icoderarely** [kamranahmedse/developer-roadmap#7723]
### What is the URL where the issue is happening

https://roadmap.sh/react

### What browsers are you seeing the problem on?

Firefox, Chrome

### Describe the Bug

On the legend/key section of the website, tick colors are explained as blue, green, and grey. However, in the actual usage within the roadmaps, the colors appear as purple, green, and grey(assuming if it existed).

The expected behavior should be that the color coding in the legend should match the colors used within the roadmap sections for clarity and consistency.

### Participation

- [X] I am willing to submit a pull request for this issue.

**Comment by fellalli** [comment]
You can change the color from `#2d72d2` to `#874efe` as done [here](https://github.com/kamranahmedse/developer-roadmap/pull/7699).

**Comment by icoderarely** [comment]
Thanks for reviewing and merging my PR! Happy to contribute.
