### ISSUE TITLE
Update URL

### ISSUE THREAD

**Issue by nick4real** [kamranahmedse/developer-roadmap#7755]
### Roadmap URL

https://roadmap.sh/aspnet-core

### Suggestions

In Databases -> Relational -> PostgreSQL update: 
https://www.guru99.com/introduction-postgresql.htmlPostgresql 
on 
https://www.guru99.com/introduction-postgresql.html

**Comment by fellalli** [comment]
@nick4real feel free to submit a PR :rocket:

**Comment by kenshanta** [comment]
This was fixed on #7766
