### ISSUE TITLE
Wrong link

### ISSUE THREAD

**Issue by dudi-w** [kamranahmedse/developer-roadmap#7756]
### What is the URL where the issue is happening

https://roadmap.sh/aspnet-core

### What browsers are you seeing the problem on?

Firefox

### Describe the Bug

Under the roadmap by clicking on "C#" and then clicking on Explore top posts about C#
There is a reference to the link https://app.daily.dev/tags/c#?ref=roadmapsh
But it refers to learning about the C language and not C#
I suggest changing the link to https://app.daily.dev/tags/c%23?ref=roadmapsh

### Participation

- [X] I am willing to submit a pull request for this issue.

**Comment by kamranahmedse** [comment]
Thank you for reporting. Feel free to submit a PR.

**Comment by dudi-w** [comment]
### Issue Closed: Wrong link [#7756](https://github.com/kamranahmedse/developer-roadmap/issues/7756)

The issue has been resolved with the successful merge of [PR #7757](https://github.com/kamranahmedse/developer-roadmap/pull/7757).  

#### **Summary of Fix**  
The incorrect link under **"Explore top posts about C#"** in the ASP.NET Core roadmap was updated to point to the correct URL:  
`https://app.daily.dev/tags/c%23?ref=roadmapsh`.

The new link now correctly redirects to C# resources on daily.dev. 🎉

**Comment by dudi-w** [comment]
### Issue Closed: Wrong link [#7756](https://github.com/kamranahmedse/developer-roadmap/issues/7756)

The issue has been resolved with the successful merge of [PR #7757](https://github.com/kamranahmedse/developer-roadmap/pull/7757).  

#### **Summary of Fix**  
The incorrect link under **"Explore top posts about C#"** in the ASP.NET Core roadmap was updated to point to the correct URL:  
`https://app.daily.dev/tags/c%23?ref=roadmapsh`.

The new link now correctly redirects to C# resources on daily.dev. 🎉
