### ISSUE TITLE
Access Issue: UX Roadmap Article Requires Medium Membership

### ISSUE THREAD

**Issue by adarsh-2425** [kamranahmedse/developer-roadmap#7773]
### Roadmap URL

https://roadmap.sh/ux-design

### Suggestions

This article, 'How to Use Behavioral Science to Influence User Behavior in Design', provides valuable insights into applying behavioral science principles in UX design. However, it is locked behind Medium's paywall, restricting access for non-members. This limits its availability to the broader UX community and impacts the inclusivity of resources for learning and collaboration. 

Article URL: https://uxplanet.org/how-to-use-behavioral-science-to-influence-user-behavior-in-design-581dc0805f7c

**Comment by kamranahmedse** [comment]
Thank you for reporting! Feel free to submit a PR removing this.
