### ISSUE TITLE
Incorrect article attached

### ISSUE THREAD

**Issue by RamdasCoundinya0716** [kamranahmedse/developer-roadmap#7797]
### Roadmap URL

https://roadmap.sh/mlops

### Suggestions

Hey, in the MLOps roadmap, when I click on orchestration, it shows the article for Observability in the Free Resources section. Please look into this.
Thank you.

I have attatched the recording here for the same
https://github.com/user-attachments/assets/e8086491-6ffe-4fea-b140-2f5b136b096f

**Comment by kamranahmedse** [comment]
Thank you feel free to submit a PR.
