### ISSUE TITLE
Need some real project to practice

### ISSUE THREAD

**Issue by ifmung** [kamranahmedse/developer-roadmap#780]
#### What roadmap is this issue about?

- [x] Frontend Roadmap
- [x] Backend Roadmap
- [x] DevOps Roadmap
- [ ] All Roadmaps

#### What is this issue about?

- [ ] Discussion for a pull request I would want to open.
- [ ] Addition of a new item
- [ ] Removal of some existing item
- [ ] Changing in arrangement
- [x] General suggestion
- [x] Sharing an Idea
- [x] Something else

#### Please acknowledge the below listed

- [x] I understand that these roadmaps are highly opinionated. The purpose is to not to include everything out there in these roadmaps but to have everything that is most relevant today comparing to the other options listed.
- [x] This is not a duplicate issue. I have searched and there is no existing issue for this.
- [x] I have read the [contribution docs](../contributing.md) before opening this issue.

#### Enter the details about the issue here

Sometimes it is boring to learn theoretical knowledge, especially in software developing. 

I think it's good idea to adding some real project with specific technology in these roadmap, which will help understanding of these knowledge deeply.

**Comment by iamdeepakvishwa** [comment]
* [ ] Try to Clone all the features from scratch of Some famous Web apps .
## You can also try these
* [ ] A weight tracker app
* [ ] A calculator app
* [ ] A book database
* [ ] A recipes app
* [ ] A bill tracker
* [ ] An expenses tracker
* [ ] A chat application
* [ ] A notes app
* [ ] A personal diary app
* [ ] A pomodoro app
* [ ] A meme generator
* [ ] Tic-tac-toe game
* [ ] The game of life
* [ ] A blog engine
* [ ] A QA engine
* [ ] A forum engine
* [ ] An embeddable live chat
* [ ] API-powered apps
* [ ] A Hacker News client
* [ ] A Reddit client
* [ ] An Instagram client
* [ ] A GitHub API client
* [ ] An Unsplash API client
* [ ] Data for your sample apps
* [ ] Public APIs you can use in example projects
* [ ] Image placeholders for your sample projects
* [ ] Image generators
* [ ] Sample text generator for your sample projects

**Comment by yudi-azvd** [comment]
Well, there are two famous and interesting repositories that include projects. They may not be totally aligned with the Developer Roadmap and the programmer will have to be wise when choosing the projects to match what he/she is learning. Nonetheless these repos are still worth taking a look:

- [App Ideias Collection](https://github.com/florinpop17/app-ideas#ledger-app-ideas-collection)
- [Build Your Own X](https://github.com/danistefanovic/build-your-own-x)

**Comment by ifmung** [comment]
Thank you very much, this helps me a lot!
