### ISSUE TITLE
Can we make this something interactive?

### ISSUE THREAD

**Issue by picwellwisher12pk** [kamranahmedse/developer-roadmap#782]
#### What roadmap is this issue about?

- [ ] Frontend Roadmap
- [ ] Backend Roadmap
- [ ] DevOps Roadmap
- [x] All Roadmaps

#### What is this issue about?

- [ ] Discussion for a pull request I would want to open.
- [ ] Addition of a new item
- [ ] Removal of some existing item
- [ ] Changing in arrangement
- [ ] General suggestion
- [x] Sharing an Idea
- [ ] Something else

#### Please acknowledge the below listed

- [x] This is not a duplicate issue. I have searched and there is no existing issue for this.
- [x] I understand that these roadmaps are highly opinionated. The purpose is to not to include everything out there in these roadmaps but to have everything that is most relevant today comparing to the other options listed.
- [x] I have read the [contribution docs](../contributing.md) before opening this issue.

#### Enter the details about the issue here

If we can make this roadmap interactive I have many ideas to add. But first thing first. These are images made from Balsamiq, can other developers help in making system to use the same JSON file from Balsamiq to make an interactive system. I can also put my effort into making this system. Then we can add more features to the interactive system, at the same time users can also render an image of the roadmap like now.

**Comment by iamdeepakvishwa** [comment]
I guess you can make a pull request with proper documentation and that will be considered if that is not SPAM

**Comment by kamranahmedse** [comment]
Hey @picwellwisher12pk, thank you for the suggestion. It is already in progress and I plan to have something live by the end of this year. Feel free to share your ideas on what you would like to see :)

**Comment by picwellwisher12pk** [comment]
I don't know how to properly document it, what are the methods here for that, but what I can do is make some animated gifs to show my ideas. It is possible you have already covered it but if you like I shall share those.
