### ISSUE TITLE
Projects Complete Status

### ISSUE THREAD

**Issue by Phani-DevOpsTech** [kamranahmedse/developer-roadmap#7829]
### Feature Description

If someone completes a project I dont think they are able to track or differentiate the completed vs new project. Please think on this aspect

**Comment by kamranahmedse** [comment]
We do highlight different project statuses on the roadmap projects page

<img width="966" alt="image" src="https://github.com/user-attachments/assets/43925592-a489-486c-a94e-4615fb18885d">
