### ISSUE TITLE
Mark skill as complete across different roadmaps

### ISSUE THREAD

**Issue by ffisc** [kamranahmedse/developer-roadmap#7861]
### Feature Description

Hi there, great tool.

I've noticed that marking, say, `Git` as done in a roadmap doesn't mark it as done in other roadmaps.
It would be nice if it did, given I'm the same person and this is the same skill.

Cheers

**Comment by fellalli** [comment]
Hi @ffisc, thanks for the feature request, but this is duplicated with #7740.

**Comment by ffisc** [comment]
Oh right, even the example there is the same. I'm ok with closing this then.

**Comment by ffisc** [comment]
Duplicate
