### ISSUE TITLE
Engineering Manger title card is not correct. 

### ISSUE THREAD

**Issue by abdulwahidgul24085** [kamranahmedse/developer-roadmap#7903]
### What is the URL where the issue is happening

https://roadmap.sh/get-started

### What browsers are you seeing the problem on?

Chrome

### Describe the Bug

The title for the following roadmap needs to be corrected. It should say `Engineering Manager` it is currently saying `Engineering Engineer`
![image](https://github.com/user-attachments/assets/de856db4-292a-414c-a900-85984f95af04)

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by fellalli** [comment]
Thank you very much. The typo was fixed in #7905. This issue can be closed.

**Comment by kamranahmedse** [comment]
Thank you this has been fixed.
