### ISSUE TITLE
Interactive links not responding on Roadmap.sh in Chrome

### ISSUE THREAD

**Issue by Teddyjay-04** [kamranahmedse/developer-roadmap#7915]
### What is the URL where the issue is happening

https://roadmap.sh

### What browsers are you seeing the problem on?

Chrome

### Describe the Bug

On the frontend section of the roadmap, clicking on interactive links does not navigate to the expected resource. The issue persists on multiple browsers and devices.

**Steps to Reproduce**

1. .Visit https://roadmap.sh/.
2. Scroll to the "Frontend Development" section.
3. Click on the first interactive link.
4. Observe that nothing happens, or it leads to an incorrect page

**Expected Behavior**
Clicking on interactive links should navigate to the correct resource or open it in a new tab.

### Output from browser console (if any)

Uncaught TypeError: Cannot read properties of undefined (reading 'onclick')  
at script.js:25  

### Participation

- [x] I am willing to submit a pull request for this issue.

**Comment by kamranahmedse** [comment]
Thank you for reporting, could you please upload a recorded video? I am not able to reproduce this.
