### ISSUE TITLE
PHP progress is not updating in my Road Card

### ISSUE THREAD

**Issue by nonamich** [kamranahmedse/developer-roadmap#7919]
### What is the URL where the issue is happening

https://roadmap.sh/card/tall/674354f65434bf319aa6da84?variant=dark

### Describe the Bug

![Screenshot_20241221_205313](https://github.com/user-attachments/assets/14ffb515-8b5f-4a6e-be5d-dc1a9ff287c7)

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by nonamich** [comment]
also noticed this on the account page 
![Screenshot_20241221_220000](https://github.com/user-attachments/assets/4a0ef8d6-db00-4867-8324-4d0544051408)

**Comment by arikchakma** [comment]
I have pushed a fix, can you please check? It should be working fine now.

**Comment by nonamich** [comment]
✅ fixed
