### ISSUE TITLE
Site Unable to Detect Public and Available Repository

### ISSUE THREAD

**Issue by Teddyjay-04** [kamranahmedse/developer-roadmap#7930]
### What is the URL where the issue is happening

https://roadmap.sh/projects/task-tracker

### What browsers are you seeing the problem on?

Chrome

### Describe the Bug

The site is unable to detect that the repository is public and available. Despite the repository being properly set to public and accessible via its URL, the system displays an error or fails to recognize its status. This prevents further actions such as linking the repository or proceeding with related tasks.

### Output from browser console (if any)

![image](https://github.com/user-attachments/assets/6cff1821-c263-4ef4-a3b6-1fb38955566c)

### Participation

- [X] I am willing to submit a pull request for this issue.

**Comment by kamranahmedse** [comment]
Please try by removing `.git` from the URL

**Comment by Teddyjay-04** [comment]
I removed .git and the issue was solved
![image](https://github.com/user-attachments/assets/0c677ef1-56dd-47a3-8dcf-f73e5d183052)
