### ISSUE TITLE
memcache vs memcached

### ISSUE THREAD

**Issue by MOZGIII** [kamranahmedse/developer-roadmap#8]
Am I missing something? Isn't there only one memcached?
Seems like there are implementations of memcache clients for PHP with the matching names, but where they are on a digram seems to be not the right place.
I propose to remove `memcache` and only leave `memcached`.
Other possible option is that you've meant *custom in-memory caching implementation*, it which case it's just confusing.

**Comment by kamranahmedse** [comment]
`Memcached` is the fork of `memcache` and is more feature rich. Removed `memcache` to avoid any confusions though. Thanks.

**Comment by MOZGIII** [comment]
So, it's a server?

**Comment by MOZGIII** [comment]
I could only find info on the client, nvm.
