### ISSUE TITLE
Give a better picture of NoSQL Databases

### ISSUE THREAD

**Issue by loicortola** [kamranahmedse/developer-roadmap#801]
#### What roadmap is this issue about?

- [ ] Frontend Roadmap
- [x] Backend Roadmap
- [ ] DevOps Roadmap
- [ ] All Roadmaps

#### What is this issue about?

- [ ] Discussion for a pull request I would want to open.
- [x] Addition of a new item
- [x] Removal of some existing item
- [ ] Changing in arrangement
- [ ] General suggestion
- [ ] Sharing an Idea
- [ ] Something else

#### Please acknowledge the below listed

- [x] This is not a duplicate issue. I have searched and there is no existing issue for this.
- [x] I understand that these roadmaps are highly opinionated. The purpose is to not to include everything out there in these roadmaps but to have everything that is most relevant today comparing to the other options listed.
- [x] I have read the [contribution docs](../contributing.md) before opening this issue.

#### Enter the details about the issue here

Hello,

thanks for the awesome roadmap.
I've taken a deeper look into DB-related info, and would like to propose some modifications.  
Most NoSQL DBs stated are Document-related DBs :  
 MongoDB, CouchDB, RethinkDB, DynamoDB...

Later in the graph, we can see other mentions such as search engines, and Graph DBs.

I would recommand removing names and stating different "kinds" of NoSQL databases, instead of names.
Beware: RethinkDB is both a document database and a "realtime database" like Firebase, however the company died a couple years ago and the community project is almost dead. Wouldn't recommend anyone investing on it nowadays.

Proposition:

**NoSQL Databases**
 - Document (MongoDB, CouchDB...)
 - K/V Datastores (Redis)
 - Column (Cassandra)
 - Timeseries (InfluxDB)
 - Realtime DBs (Firebase, RethinkDB)
 - Object Storage (S3, Ceph...)

**Comment by loicortola** [comment]
I can do the PR btw, I just want to know if this is something you might be interested in 👍

**Comment by loicortola** [comment]
Ping ?

**Comment by thantkyaw1** [comment]
Close

**Comment by thantkyaw1** [comment]
Open

**Comment by kamranahmedse** [comment]
Thanks for the suggestion Loïc - it makes sense. I have made some changes in the 2021 version to accommodate this
