### ISSUE TITLE
Stolen and relicensed content

### ISSUE THREAD

**Issue by Etheryte** [kamranahmedse/developer-roadmap#809]
#### What roadmap is this issue about?

- [x] Frontend Roadmap
- [ ] Backend Roadmap
- [ ] DevOps Roadmap
- [ ] All Roadmaps

#### What is this issue about?

- [ ] Discussion for a pull request I would want to open.
- [ ] Addition of a new item
- [ ] Removal of some existing item
- [ ] Changing in arrangement
- [ ] General suggestion
- [ ] Sharing an Idea
- [x] Something else

#### Please acknowledge the below listed

- [x] This is not a duplicate issue. I have searched and there is no existing issue for this.
- [x] I understand that these roadmaps are highly opinionated. The purpose is to not to include everything out there in these roadmaps but to have everything that is most relevant today comparing to the other options listed.
- [ ] I have read the [contribution docs](../contributing.md) before opening this issue.

#### Enter the details about the issue here

Sadly, your work has been copied and relicensed as MIT over here: https://github.com/developer-resources/frontend-development

Additionally, the copycat has marked themselves as the sole author in [their readme](https://github.com/developer-resources/frontend-development#authors):

<img width="887" alt="Screenshot 2020-11-02 at 12 41 08" src="https://user-images.githubusercontent.com/3171718/97864315-b21b2780-1d08-11eb-9e66-1d3de3a965c1.png">

The above leads me to believe this is not done in good faith and I would recommend [filing a DMCA complaint](https://github.com/contact/dmca).

**Comment by mojpm** [comment]
Hey, I appreciate that you're pointing this out but I didn't intend to steal this content as mine. I didn't know that it was not allowed to re-use it. I added a credit section to credit the Original creator but that didn't seem to do any good. I've removed both roadmaps as part of the resource until the owner can permit usage

**Comment by valentinradu** [comment]
@Etheryte I just stopped by to say: I can hardly believe how much effort you put into reporting this 😄 This repo should've probably been MIT licensed in the first place since it's growing to be the **collaborative** effort of multiple devs. Relax man, there are more important things in like (and software development) than licenses and copyright.

**Comment by kamranahmedse** [comment]
The content has been taken down so I am going to close this one. Thanks, @Etheryte for reporting, appreciate it.
