### ISSUE TITLE
Mitigation strategies double appearance

### ISSUE THREAD

**Issue by carlosdeque-s** [kamranahmedse/developer-roadmap#814]
#### What roadmap is this issue about?

- [ ] Frontend Roadmap
- [x] Backend Roadmap
- [ ] DevOps Roadmap
- [ ] All Roadmaps

#### What is this issue about?

- [ ] Discussion for a pull request I would want to open.
- [ ] Addition of a new item
- [x] Removal of some existing item
- [ ] Changing in arrangement
- [x] General suggestion
- [ ] Sharing an Idea
- [ ] Something else

#### Please acknowledge the below listed

- [x] This is not a duplicate issue. I have searched and there is no existing issue for this.
- [x] I understand that these roadmaps are highly opinionated. The purpose is to not to include everything out there in these roadmaps but to have everything that is most relevant today comparing to the other options listed.
- [x] I have read the [contribution docs](../contributing.md) before opening this issue.

#### Enter the details about the issue here
There are two instances where Mitigation strategies is listed at the end of the backend roadmap, if this is intentional I would like to know why.
![2 times Mitigation strategies](https://user-images.githubusercontent.com/72588466/98315174-eaa45500-1fd7-11eb-8bbf-e980edc586e9.jpg)

**Comment by Dobrovolskyi** [comment]
It is Mitigation vs Migration.
