### ISSUE TITLE
Plain text or markdown versions of the roadmaps

### ISSUE THREAD

**Issue by EdgarLozano185519** [kamranahmedse/developer-roadmap#815]
#### What roadmap is this issue about?

- [ ] Frontend Roadmap
- [ ] Backend Roadmap
- [ ] DevOps Roadmap
- [x] All Roadmaps

#### What is this issue about?

- [ ] Discussion for a pull request I would want to open.
- [x] Addition of a new item
- [ ] Removal of some existing item
- [ ] Changing in arrangement
- [ ] General suggestion
- [ ] Sharing an Idea
- [ ] Something else

#### Please acknowledge the below listed

- [x] This is not a duplicate issue. I have searched and there is no existing issue for this.
- [x] I understand that these roadmaps are highly opinionated. The purpose is to not to include everything out there in these roadmaps but to have everything that is most relevant today comparing to the other options listed.
- [x] I have read the [contribution docs](../contributing.md) before opening this issue.

#### Enter the details about the issue here

I am a screen reader user and I am unable to access the content of this valuable resource. Screen readers generally do not interact with images at all.
I am opening this discussion to ask if plain text versions of these roadmaps could be made. I think this will help others in my situation and perhaps search engine discovery is a bonus.
I am able to do some analysis of the JSON data, which is helpful to some extent. However, it would be ideal if I could go through the list without parsing through all the code.
I realize there are probably some complex relationships here, but I was thinking we could leverage headings, lists, ASCII chars to represent arrows, etc.
Thank you for considering and I would be happy to contribute in some way (such as find way to parse JSON data in code to generate markdown files).

**Comment by ironman1987** [comment]
@EdgarLozano185519 
Do you have any ideas?

**Comment by ijoseph** [comment]
Related request: _searchable_ PDF image format. I just want to be able to Ctrl-F to see where a particular technology is.

**Comment by GokiSakaguchi** [comment]
坂口は退職しました。
今後のご連絡は ***@***.*** までお願いいたします。
