### ISSUE TITLE
roadmap for data scientist 

### ISSUE THREAD

**Issue by deknos** [kamranahmedse/developer-roadmap#817]
#### What roadmap is this issue about?

- [ ] Frontend Roadmap
- [ ] Backend Roadmap
- [ ] DevOps Roadmap
- [ ] All Roadmaps
- [x] None of the above

#### What is this issue about?

- [x ] Addition of a new item
- [x] General suggestion

#### Please acknowledge the below listed

- [x] This is not a duplicate issue. I have searched and there is no existing issue for this.
- [ x] I understand that these roadmaps are highly opinionated. The purpose is to not to include everything out there in these roadmaps but to have everything that is most relevant today comparing to the other options listed.
- [x ] I have read the [contribution docs](../contributing.md) before opening this issue.

#### Enter the details about the issue here

Please make also a roadmap for data scientist. data science is different from data engineering, but that would be really helpful for beginners in that field.

**Comment by durgeshsamariya** [comment]
Check out https://github.com/durgeshsamariya/data-science-roadmap

**Comment by RodrigoAB93** [comment]
> 
> 
> Check out https://github.com/durgeshsamariya/data-science-roadmap

Thank you, this is very helpfull to getting start in the field.

**Comment by durgeshsamariya** [comment]
@RodrigoAB93 I am glad that you like it.
Checkout this Machine Learning Code Generator.
https://github.com/durgeshsamariya/MLgenerator

**Comment by jess-johnson-msft** [comment]
this guy has pretty awesome video content around data science paths
https://www.youtube.com/watch?v=Akl7ndShTbo&t=1042s
