### ISSUE TITLE
php5 to php7

### ISSUE THREAD

**Issue by babytee** [kamranahmedse/developer-roadmap#82]
Please I only know php5 with msqli(procedural)
But I really need to know php7 and pdo I don't know how to go about it

**Comment by wblondel** [comment]
Maybe [this](http://php.net/manual/en/migration70.php) will answer your questions ?
As for PDO, there are plenty of ressources on the Internet :)

Please post an "issue" only if you think something should be removed or changed etc.

**Comment by babytee** [comment]
OK I get thanks
