### ISSUE TITLE
Credible recommendations for each learning map node

### ISSUE THREAD

**Issue by CeoFred** [kamranahmedse/developer-roadmap#821]
#### What roadmap is this issue about?

- [ ] Frontend Roadmap
- [ ] Backend Roadmap
- [ ] DevOps Roadmap
- [*] All Roadmaps

#### What is this issue about?

- [ ] Discussion for a pull request I would want to open.
- [*] Addition of a new item
- [ ] Removal of some existing item
- [ ] Changing in arrangement
- [ ] General suggestion
- [ ] Sharing an Idea
- [ ] Something else

#### Please acknowledge the below listed

- [*] This is not a duplicate issue. I have searched and there is no existing issue for this.
- [*] I understand that these roadmaps are highly opinionated. The purpose is to not to include everything out there in these roadmaps but to have everything that is most relevant today comparing to the other options listed.
- [*] I have read the [contribution docs](../contributing.md) before opening this issue.

#### Enter the details about the issue here
It would be nice to have some links to either article, videos close to each node incase the learners don't have a clear path to where to learn them.

**Comment by kamranahmedse** [comment]
This was added earlier this year. Thank you!
