### ISSUE TITLE
Using this with respect to the license 

### ISSUE THREAD

**Issue by nargyriou** [kamranahmedse/developer-roadmap#825]
#### What roadmap is this issue about?

- [ ] Frontend Roadmap
- [ ] Backend Roadmap
- [ ] DevOps Roadmap
- [x] All Roadmaps

#### What is this issue about?

- [ ] Discussion for a pull request I would want to open.
- [ ] Addition of a new item
- [ ] Removal of some existing item
- [ ] Changing in arrangement
- [ ] General suggestion
- [ ] Sharing an Idea
- [x] Something else

#### Please acknowledge the below listed

- [x] This is not a duplicate issue. I have searched and there is no existing issue for this.
- [x] I understand that these roadmaps are highly opinionated. The purpose is to not to include everything out there in these roadmaps but to have everything that is most relevant today comparing to the other options listed.
- [x] I have read the [contribution docs](../contributing.md) before opening this issue.

#### Enter the details about the issue here

Hello

I have noticed this paragraph in the licence

> Please note that I am really flexible with allowing the usage of the content in this
repository. If you reach out to me with a brief detail of why and how you would like
to use this content, there is a good chance that I will allow you to use it. The reason
behind this strictness in the license is to stop the people who have been using these
roadmaps in ill manners e.g. ripping people off with suggesting random affiliate links,
redistributing these roadmaps just for the sake of monetizing the traffic.

I have tried contacting you privately (few emails, few tweets) but since it's open source might as well do it publicly

I currently teach some classes at a french university (not private)

I thought the roadmap was a pretty good idea and I'd like to include it in a project of mine, and then distribute it to students 

The project would be open source, with the same licence as yours to be as compliant as possible. 

The project itself is a website to display the roadmap in a canvas, instead of a PNG, and allow my users to click on the skills that they think they know, which would color the boxes in various colors depending on how they click, and user could export this as a PNG & a Json to share the state of their current knowledge with others. This could be useful for a number of things, including assessing before a class the current knowledge of students 

It could have ads depending on hosting, or something else to cover the server costs (maybe sponsors if a company is interested...) so I think this falls under "commercial use" and is prevented by the licence unless I'm given explicit permission from the licence holder

So I'm coming here to ask for permission. Would you be okay with me using the project, mainly your json files?

Thank you

**Comment by Sridhar-rajendran** [comment]
Thank you sir

**Comment by machongda** [comment]
111

**Comment by machongda** [comment]
111

**Comment by kamranahmedse** [comment]
Hey Argyriou, sure go ahead.

**Comment by thantkyaw1** [comment]
No open
