### ISSUE TITLE
what is whmcs

### ISSUE THREAD

**Issue by babytee** [kamranahmedse/developer-roadmap#83]

**Comment by wblondel** [comment]
There are plenty of ressources on Internet that will answer your questions.
You could maybe go to the official website of WHMCS.

Please post an "issue" only if you think something should be removed or changed etc.

**Comment by babytee** [comment]
OK am new to this site can you please give me guide on how to post issues on this site

**Comment by kamranahmedse** [comment]
Closing for being non-issue.
