### ISSUE TITLE
Add Logos from each language or system

### ISSUE THREAD

**Issue by LewisDamy** [kamranahmedse/developer-roadmap#840]
#### What roadmap is this issue about?

- [ ] Frontend Roadmap
- [ ] Backend Roadmap
- [ ] DevOps Roadmap
- [x] All Roadmaps

#### What is this issue about?

- [ ] Discussion for a pull request I would want to open.
- [ ] Addition of a new item
- [ ] Removal of some existing item
- [ ] Changing in arrangement
- [x] General suggestion
- [ ] Sharing an Idea
- [ ] Something else

#### Please acknowledge the below listed

- [ ] This is not a duplicate issue. I have searched and there is no existing issue for this.
- [ ] I understand that these roadmaps are highly opinionated. The purpose is to not to include everything out there in these roadmaps but to have everything that is most relevant today comparing to the other options listed.
- [ ] I have read the [contribution docs](../contributing.md) before opening this issue.

#### Enter the details about the issue here
Please add some pictures about each language just for reference because many people know about those, or even remember by the logos, for instance, I remember the React by the atomic symbol. So please add a couple of logos in programming languages or db's or other things.

**Comment by supzi-del** [comment]
Can I take this up?

**Comment by desnic-cparun** [comment]
Sure

Thanks and Regards,
Arunkumar P
9789102221

**Comment by supzi-del** [comment]
Can you please tell me where I can add logos?

**Comment by CV777-max** [comment]
Sure

Sent from my iPhone

On Feb 17, 2021, at 9:14 AM, Supritha <notifications@github.com<mailto:notifications@github.com>> wrote:


Can I take this up?

**Comment by supzi-del** [comment]
![frontend (2) (1) (1) (1) (1) (1)](https://user-images.githubusercontent.com/78655439/108383435-cdfef680-722f-11eb-9641-22e2e767a067.png)
Hey! Please check this out and let me know if I should do the same for other roadmaps.Thanks

**Comment by kamranahmedse** [comment]
Thank you for opening the issue but this is out of the scope of the project. However, roadmaps are being made interactive so clicking each node can give you more details about the item listed.
