### ISSUE TITLE
Turkish Tranlastion

### ISSUE THREAD

**Issue by Lynicis** [kamranahmedse/developer-roadmap#879]
#### What roadmap is this issue about?

- [ ] Frontend Roadmap
- [ ] Backend Roadmap
- [ ] DevOps Roadmap
- [x] All Roadmaps

#### What is this issue about?

- [x] Discussion for a pull request I would want to open.
- [ ] Addition of a new item
- [ ] Removal of some existing item
- [ ] Changing in arrangement
- [ ] General suggestion
- [ ] Sharing an Idea
- [ ] Something else

#### Please acknowledge the below listed

- [x] This is not a duplicate issue. I have searched and there is no existing issue for this.
- [x] I understand that these roadmaps are highly opinionated. The purpose is to not to include everything out there in these roadmaps but to have everything that is most relevant today comparing to the other options listed.
- [x] I have read the [contribution docs](../contributing.md) before opening this issue.

#### Enter the details about the issue here

There is Typo problems, weird translation problems in Turkish wireframes.

**Comment by maverick-galloway** [comment]
Ok I keep getting emails from you but I havent done anything with you guys
it was my girlfriend who used my info and your guys tools to ruin my life
her and cody beauchamp have ruined my life and all I did was help them
out.  So I'm very grateful for your tools ruining a single dad with 2 kids
life but hey everyone meant well I'm sure.
