### ISSUE TITLE
Add Sanic to Python's async branch

### ISSUE THREAD

**Issue by jumasheff** [kamranahmedse/developer-roadmap#89]
Sanic is young (Flask-like) async framework, but is super active: https://github.com/channelcat/sanic

**Comment by medecau** [comment]
Or not.

This is a useful intro to webdev and not a list of all possible frameworks on all possible languages.
Notices the absence of bottlepy, falcon and webpy? No mention of Lua or Elixir either. That is because this is not a "awesome-webdev-master-list".

**Comment by jumasheff** [comment]
:) well, I like your `not a "awesome-webdev-master-list"` part.
But seriously, Sanic is much simpler to start with, especially for those coming from Flask background.

**Comment by kamranahmedse** [comment]
@jumasheff as @medecau said, we can't include everything. I have left out a few "cool stuff" that I think we could have added under certain leafs but adding each and everything was never the goal.

Thank you for reporting though.
