### ISSUE TITLE
Map Interactive

### ISSUE THREAD

**Issue by JonasRafael16** [kamranahmedse/developer-roadmap#890]
#### What roadmap is this issue about?

- [ ] Frontend Roadmap
- [ ] Backend Roadmap
- [ ] DevOps Roadmap
- [x] All Roadmaps

#### What is this issue about?

- [ ] Discussion for a pull request I would want to open.
- [x] Addition of a new item
- [ ] Removal of some existing item
- [ ] Changing in arrangement
- [x] General suggestion
- [ ] Sharing an Idea
- [ ] Something else

Hello.
It would be very interesting if the map were interactive, being able to mark the knowledge already acquired, the ones that are being studied and that are still pending.
So it would be better to follow the studies.
Thanks and see you later.
Att Jonas Lima

**Comment by kamranahmedse** [comment]
Roadmaps are being made interactive. [Frontend and Backend roadmaps](https://roadmap.sh) are already interactive and the rest of them are being made interactive as we speak. Thank you for opening the issue 🙏
