### ISSUE TITLE
Provide vector-based image files

### ISSUE THREAD

**Issue by kolja-lucht** [kamranahmedse/developer-roadmap#893]
#### What roadmap is this issue about?

- [ ] Frontend Roadmap
- [ ] Backend Roadmap
- [ ] DevOps Roadmap
- [x] All Roadmaps

#### What is this issue about?

- [ ] Discussion for a pull request I would want to open.
- [ ] Addition of a new item
- [ ] Removal of some existing item
- [ ] Changing in arrangement
- [x] General suggestion
- [ ] Sharing an Idea
- [ ] Something else

#### Please acknowledge the below listed

- [x] This is not a duplicate issue. I have searched and there is no existing issue for this.
- [x] I understand that these roadmaps are highly opinionated. The purpose is to not to include everything out there in these roadmaps but to have everything that is most relevant today comparing to the other options listed.
- [x] I have read the [contribution docs](../contributing.md) before opening this issue.

#### Enter the details about the issue here

A little while ago I printed out an older version of your DevOps Roadmap and hung it on my wall as a poster. I'd like to do the same with the latest version. But unfortunately the text is a little pixely. Therefore it would be awesome if you could provide the roadmaps as vector-based files so that it doesn't matter in what size I print them out 🙂

**Comment by semsion** [comment]
Yes I'm sure the old backend roadmap was a vector image.

The React and Frontend roadmaps do not appear to be as such, and are printing out in a very pixelated manner.

**Comment by kamranahmedse** [comment]
We have the SVG available on the website right. You can either get that from each of the roadmaps or use the PDFs available at https://roadmap.sh/pdfs
