### ISSUE TITLE
Link to contribution docs in ISSUE_TEMPLATE is broken

### ISSUE THREAD

**Issue by Foo-x** [kamranahmedse/developer-roadmap#897]
#### What roadmap is this issue about?

- [ ] Frontend Roadmap
- [ ] Backend Roadmap
- [ ] DevOps Roadmap
- [ ] All Roadmaps

#### What is this issue about?

- [ ] Discussion for a pull request I would want to open.
- [ ] Addition of a new item
- [ ] Removal of some existing item
- [ ] Changing in arrangement
- [ ] General suggestion
- [ ] Sharing an Idea
- [x] Something else

#### Please acknowledge the below listed

- [x] This is not a duplicate issue. I have searched and there is no existing issue for this.
- [x] I understand that these roadmaps are highly opinionated. The purpose is to not to include everything out there in these roadmaps but to have everything that is most relevant today comparing to the other options listed.
- [x] I have read the [contribution docs](../contributing.md) before opening this issue.

#### Enter the details about the issue here

It seems that relative links in issues or pull requests are not supported yet, so `../contributing.md` should be `https://github.com/kamranahmedse/developer-roadmap/blob/master/CONTRIBUTING.md`.

**Comment by GoodnessEzeh** [comment]
I guess that has been fixed. I was able to navigate through the links just now.
