### ISSUE TITLE
Make the Navbar Stick to the top

### ISSUE THREAD

**Issue by Aanchal116** [kamranahmedse/developer-roadmap#911]
#### What roadmap is this issue about?

- [ ] Frontend Roadmap
- [ ] Backend Roadmap
- [ ] DevOps Roadmap
- [x] All Roadmaps

#### What is this issue about?

- [ ] Discussion for a pull request I would want to open.
- [ ] Addition of a new item
- [ ] Removal of some existing item
- [x] Changing in arrangement
- [ ] General suggestion
- [ ] Sharing an Idea
- [ ] Something else

#### Please acknowledge the below listed

- [x] This is not a duplicate issue. I have searched and there is no existing issue for this.
- [x] I understand that these roadmaps are highly opinionated. The purpose is to not to include everything out there in these roadmaps but to have everything that is most relevant today comparing to the other options listed.
- [x] I have read the [contribution docs](../contributing.md) before opening this issue.

#### Enter the details about the issue here

Currently, the navbar isn't stick to the top on the webpages. Sticking the navbar to the top would be more convenient for usage and reach of user.

**Comment by rahul-10-byte** [comment]
Please assign this issue to me...I can complete this task.

**Comment by kamranahmedse** [comment]
Thank you for suggesting the change but there have been some changes to the design and this isn't the final version that you see on the website.
