### ISSUE TITLE
DevOps should get DB knowledge too

### ISSUE THREAD

**Issue by lakkeger** [kamranahmedse/developer-roadmap#912]
#### What roadmap is this issue about?

- [ ] Frontend Roadmap
- [ ] Backend Roadmap
- [x] DevOps Roadmap
- [ ] All Roadmaps

#### What is this issue about?

- [ ] Discussion for a pull request I would want to open.
- [x] Addition of a new item
- [ ] Removal of some existing item
- [ ] Changing in arrangement
- [ ] General suggestion
- [ ] Sharing an Idea
- [ ] Something else

#### Please acknowledge the below listed

- [x] This is not a duplicate issue. I have searched and there is no existing issue for this.
- [x] I understand that these roadmaps are highly opinionated. The purpose is to not to include everything out there in these roadmaps but to have everything that is most relevant today comparing to the other options listed.
- [x] I have read the [contribution docs](../contributing.md) before opening this issue.

#### Enter the details about the issue here

First and foremost great work so far.
When I ran through the DevOps branch it seemed to me that the DB/DBA knowledge and the DB source control tools (like Liquibase, Squitch, DBMaestro...etc) were missing points on it, since one hardly can build and change an application/pipeline without the necessity to touch sooner or later the data storage.
I would suggest to add it to the road map.

**Comment by dansholds** [comment]
Hey!

Thanks for raising this, I think this is a valid request for the DevOps Roadmap and an internal ticket has been created to tackle this.

Please join our Discord where we share new features and improvements - https://discord.gg/ejtU9MgB :)
