### ISSUE TITLE
Data structure and Algorithm importance

### ISSUE THREAD

**Issue by Chidalu567** [kamranahmedse/developer-roadmap#913]
#### What roadmap is this issue about?

- [ ] Frontend Roadmap
- [x] Backend Roadmap
- [ ] DevOps Roadmap
- [ ] All Roadmaps

#### What is this issue about?

- [ ] Discussion for a pull request I would want to open.
- [ ] Addition of a new item
- [ ] Removal of some existing item
- [ ] Changing in arrangement
- [x] General suggestion
- [ ] Sharing an Idea
- [ ] Something else

#### Please acknowledge the below listed

- [x] This is not a duplicate issue. I have searched and there is no existing issue with this.
- [x] I understand that these roadmaps are highly opinionated. The purpose is not to include everything out there in these roadmaps but to have everything that is most relevant today comparing to the other options listed.
- [x] I have read the [contribution docs](../contributing.md) before opening this issue.

### Data structure and algorithm
It is important for every backend developer to have an idea of at least 5 concepts in **data structures**. Learning data structures is inevitable as it helps developers think outside the box.
[Data structure](https://towardsdatascience.com/8-common-data-structures-every-programmer-must-know-171acf6a1a42)

**Comment by kamranahmedse** [comment]
It's there [in the introduction](https://github.com/kamranahmedse/developer-roadmap#introduction)
