### ISSUE TITLE
About your gorgeous beautiful image

### ISSUE THREAD

**Issue by NguyenNamUET** [kamranahmedse/developer-roadmap#932]
#### What roadmap is this issue about?

- [ ] Frontend Roadmap
- [ ] Backend Roadmap
- [ ] DevOps Roadmap
- [x] All Roadmaps

#### What is this issue about?

- [ ] Discussion for a pull request I would want to open.
- [ ] Addition of a new item
- [ ] Removal of some existing item
- [ ] Changing in arrangement
- [ ] General suggestion
- [ ] Sharing an Idea
- [x] Something else

#### Please acknowledge the below listed

- [x] This is not a duplicate issue. I have searched and there is no existing issue for this.
- [x] I understand that these roadmaps are highly opinionated. The purpose is to not to include everything out there in these roadmaps but to have everything that is most relevant today comparing to the other options listed.
- [x] I have read the [contribution docs](../contributing.md) before opening this issue.

#### Enter the details about the issue here

Hey, I see your beautiful images. Can you give me the tool to make such images?
I am in need to make a presentation about Database Roadmap.
Thanks you in advance.

**Comment by gridlocdev** [comment]
> Roadmaps are made using [Balsamiq](https://balsamiq.com/download/)

Source: https://github.com/kamranahmedse/developer-roadmap/blob/master/CONTRIBUTING.md#how-are-these-roadmaps-made
