### ISSUE TITLE
What is a relevant source?

### ISSUE THREAD

**Issue by barbier** [kamranahmedse/developer-roadmap#95]
I was wandering..... We have projects like [PHP the right way](http://www.phptherightway.com/), [Javascript the right way](http://jstherightway.org/), [Browser diet](https://browserdiet.com/) and many other I may not know. Are they relevant sources? How to add them?

**Comment by kamranahmedse** [comment]
They are ..sort of.. but I mean the links for each of those leaves in the tree. 

..just wait for it :)
