### ISSUE TITLE
Duplicate Redis

### ISSUE THREAD

**Issue by mihasicehcek** [kamranahmedse/developer-roadmap#96]
I think his place in NoSQL Databases, not in Caching.
Yes, we very often use Redis for chaching, but you can also use for chaching mongoDB and Cassandra and even file writing.
Chaching is only a special case of use of Redis. And in general this is a data storage.

**Comment by kamranahmedse** [comment]
Hey @mihasicehcek, but if you look at it; it has wider usage in the caching and stuff. The chart doesn't mean that one thing in a branch can't go under some other branch as well; it just sketches down the comparatively popular ones in the relevant branches. 

Plus there is a lot more that I could add under each of the branches but you knowing the listed stuff would be more than enough for "becoming a web developer".
