### ISSUE TITLE
Roadmap for C#/.NET 6

### ISSUE THREAD

**Issue by workpebojot** [kamranahmedse/developer-roadmap#960]
As we all know, C#/.NET has been open source for about 5 years now.. I would like to see the roadmap. Most basically which open source libraries, tools etc. are recommended

**Comment by kamranahmedse** [comment]
We are now closing any issues requesting new roadmap requests to clean up the issues. 

However, this doesn't mean that the requested roadmap won't be added to the website. We are putting it in the backlog and will add it to the website depending on how it ranks in the backlog or sooner if we find someone interested in adding that roadmap. Thank you for the request though! 🙏
