### ISSUE TITLE
WHAT'S LIBRARY / TOOLS USED TO CREATE A BEAUTIFUL ROADMAP ???

### ISSUE THREAD

**Issue by iqlal** [kamranahmedse/developer-roadmap#969]
WHAT'S LIBRARY / TOOLS USED TO CREATE A BEAUTIFUL ROADMAP ???

**Comment by rizalandyyy** [comment]
visio

**Comment by iqlal** [comment]
> visio

Thanks

**Comment by iqlal** [comment]
> visio

I dont think so

**Comment by melvnl** [comment]
I think the author utilizes something from chakra UI (I have zero experience in this component library),  but if you go to this [page](https://github.com/kamranahmedse/developer-roadmap/blob/master/pages/%5Broadmap%5D/%5Bgroup%5D.tsx). The component/container that renders the roadmap chart is coming from the chakra UI component library (Box, Breadcrumb, BreadcrumbItem, BreadcrumbLink, Button, Container). I just started to look into the roadmap.sh code just a while ago, hence CMIIW.

**Comment by iqlal** [comment]
> I think the author utilizes something from chakra UI (I have zero experience with this component library), but if you go to this [page](https://github.com/kamranahmedse/developer-roadmap/blob/master/pages/%5Broadmap%5D/%5Bgroup%5D.tsx). The component/container that renders the roadmap chart is coming from the chakra UI component library (Box, Breadcrumb, BreadcrumbItem, BreadcrumbLink, Button, Container). I just started to look into the roadmap.sh code just a while ago, hence CMIIW.

Thats for your info, just wait @kamranahmedse for official answer 😊

**Comment by kamranahmedse** [comment]
Hey @iqlal yes it's Chakra UI for the website and [Balsamiq](https://balsamiq.com/) for the roadmpas

**Comment by iqlal** [comment]
> Hey @iqlal yes it's Chakra UI for the website and [Balsamiq](https://balsamiq.com/) for the roadmaps

I see, thanks
