### ISSUE TITLE
I'd like to know roadmap for Spring developer

### ISSUE THREAD

**Issue by XDXO** [kamranahmedse/developer-roadmap#97]
After deciding on a career as a Spring developer, I noticed that there are many components available for Spring Framework, and it would be nice to show which components are useful in some situations.

**Comment by Grimlek** [comment]
I would start with Spring Initializer to build a project structure for a simple crud web application using Spring Boot, Spring MVC, Thymeleaf and Spring Data JPA. Then I would add login with Spring Security. Then add some transactional business logic utilizing Spring WebFlow and Spring Cache with Guava Cache setup for database intensive queries.

**Comment by kamranahmedse** [comment]
Hi @XDXO, unfortunately I really have no idea about Spring.

Closing for being a non-issue.
