### ISSUE TITLE
Including UI/UX design in front end roadmap

### ISSUE THREAD

**Issue by ramenatorr** [kamranahmedse/developer-roadmap#976]
#### What roadmap is this issue about?

- [x] Frontend Roadmap
- [ ] Backend Roadmap
- [ ] DevOps Roadmap
- [ ] All Roadmaps

#### What is this issue about?

- [ ] Functionality of the website
- [ ] Discussion for a pull request I would want to open.
- [x] Addition of a new item
- [ ] Removal of some existing item
- [ ] Changing in arrangement
- [ ] General suggestion
- [ ] Sharing an Idea
- [ ] Something else

#### Please acknowledge the below listed

- [x] This is not a duplicate issue. I have searched and there is no existing issue for this.
- [x] I understand that these roadmaps are highly opinionated. The purpose is to not to include everything out there in these roadmaps but to have everything that is most relevant today comparing to the other options listed.
- [x] I have read the [contribution docs](../contributing) before opening this issue.

#### Enter the details about the issue here

First off, really cool what you have created here. I’m no expert, but I was thinking that it would make sense to include a node or two about UI and UX design in the front end developer roadmap. This could include things like page design, structure, and other topics like that. Plus also the tooling to help mockup and test designs like Figma or XD. I think those things are pretty useful in becoming a successful front end developer.

**Comment by kamranahmedse** [comment]
This has been fixed and will be published in the coming release. Thank you 🙏
