### ISSUE TITLE
Add knowledge about browser processes to Front-end map

### ISSUE THREAD

**Issue by user1736** [kamranahmedse/developer-roadmap#99]
One of the most essential front-end skills is missing now - "How browser works":
 - how does browser load and parse page (processing order, async/defer)?
 - how does browser render page (repaint/reflow)?

PS Also front-end developers should have at least basic knowledge about HTTP/HTTPS

**Comment by damengilland** [comment]
* Web browser engine - Wikipedia || https://en.wikipedia.org/wiki/Web_browser_engine

* JavaScript engine - Wikipedia || https://en.wikipedia.org/wiki/JavaScript_engine

**Comment by devrelm** [comment]
Agreed. It could very well be its own branch with several limbs:

* Browser Environments
  * Rendering
    * Parsing
    * Layout
    * Painting
  * JavaScript Event Loop
    * Task Queue
    * Microtasks
  * DOM
  * Feature Support Disparity
      * caniuse.com
      * quirksmode.org
  * Network Requests
    * Concepts
      * HTTP/HTTPS
      * REST
      * Headers
      * Caching
    * APIs
      * XMLHttpRequest
      * Fetch API

**Comment by kamranahmedse** [comment]
There have been changes made to that section which makes this issue outdated. Thank you for reporting though 🙏
